### ISSUE TITLE
Parameters fill_include_names and fill_exclude_names in astropy.io.ascii.read don't work as expected

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#10000]
### Description
The parameters `fill_include_names` and `fill_exclude_names` in [astropy.io.ascii.read](https://docs.astropy.org/en/stable/api/astropy.io.ascii.read.html#astropy.io.ascii.read) don't work as expected.

### Expected behavior
Setting a column name in `fill_exclude_names` should exclude that column from the `fill_values` mask.

### Actual behavior
It works in a confusing way.

### Steps to Reproduce
```python
from astropy.io import ascii

test_data = """
ID  x  y
1   99  3.0
99  5.2  6.1
7   1.8  99
"""
fill_msk = [('', '0'), ('99', '0')]
```

1. Works as expected: all columns are masked
```
data = ascii.read(test_data, fill_values=fill_msk)
 ID  x   y 
--- --- ---
  1  -- 3.0
 -- 5.2 6.1
  7 1.8  --
```
1.  Works as expected: only the `x` column is excluded from the mask
```
data = ascii.read(test_data, fill_values=fill_msk, fill_exclude_names='x')
 ID  x    y 
--- ---- ---
  1 99.0 3.0
 --  5.2 6.1
  7  1.8  --
```
1.  Works as expected: only the `y` column is excluded from the mask
```
data = ascii.read(test_data, fill_values=fill_msk, fill_exclude_names='y')
 ID  x   y  
--- --- ----
  1  --  3.0
 -- 5.2  6.1
  7 1.8 99.0
```
1.  Works as expected: only the `ID` column is excluded from the mask
```
data = ascii.read(test_data, fill_values=fill_msk, fill_include_names=('x', 'y'), fill_exclude_names='ID')
 ID  x   y 
--- --- ---
  1  -- 3.0
 99 5.2 6.1
  7 1.8  --
```
1. **Does not** work as expected: the `y` column is excluded from the mask when a different name was given
```
data = ascii.read(test_data, fill_values=fill_msk, fill_exclude_names='nny')
 ID  x   y  
--- --- ----
  1  --  3.0
 -- 5.2  6.1
  7 1.8 99.0
```
1. **Does not** work as expected: the `ID` column is **not** excluded from the mask
```
data = ascii.read(test_data, fill_values=fill_msk, fill_exclude_names='ID')
 ID  x   y 
--- --- ---
  1  -- 3.0
 -- 5.2 6.1
  7 1.8  --
```

### System Details

```
>>> import platform; print(platform.platform())
Linux-5.5.0-050500-generic-x86_64-with-glibc2.10
>>> import sys; print("Python", sys.version)
Python 3.8.2 | packaged by conda-forge | (default, Feb 28 2020, 17:15:22) 
[GCC 7.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.1.dev658+g38423ea0c
>>> import scipy; print("Scipy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'

```

**Comment by taldcroft** [comment]
The basis for the confusing behavior you are seeing is that `fill_include_names` and `fill_exclude_names` must be a list, not a single string.  The fact that it does give the expected results in some of your test cases is an accident of using a single-character column name.  For a multi-character name like `'ID'` that gets interpreted as `['I', 'D']`. The documentation does state that the inputs need to be a list, but that does not excuse us from properly validating the inputs and providing a helpful error message.

I opened #10001 actually prior to noticing this issue, but I will amend that to also prevent the particular problem here, probably by checking for a single string and then turning that into a list of that string.

**Comment by Gabriel-p** [comment]
Thanks for the explanation @taldcroft. What you say makes sense, but it doesn't explain why this gives the expected result:

```
data = ascii.read(test_data, fill_values=fill_msk, fill_include_names=('x', 'y'), fill_exclude_names='ID')
 ID  x   y 
--- --- ---
  1  -- 3.0
 99 5.2 6.1
  7 1.8  --
```

unless setting `fill_include_names` means `fill_exclude_names` is disregarded? If so, this is not entirely clear in the docs.

BTW, this also fails:

    data = ascii.read(test_data, fill_values=fill_msk, fill_exclude_names=('ID'))

so I guess tuples are not valid either?

**Comment by taldcroft** [comment]
`fill_include_names` is applied first, at which point the list of possible columns for filling is `['x', 'y']`.  Then `fill_exclude_names` is applied, in this case "excluding" `['I', 'D']` columns. 

About the `('ID')` example, this is where Python syntax had to make a compromise because of using parentheses for both precedence and tuples. What you wrote is just the string `'ID'`, instead you need to use `('ID',)` to make it a tuple. 

Thanks for the feedback @Gabriel-p , it's clear the docs here could use a new section on the include/exclude parameters.  Basically the same behavior applies to `include_names` and `exclude_names`.  As always contributions welcome.  I appreciate that digging into sphinx and getting docs to build is a bit of a pain, but if you wrote out some text and examples in markdown in this thread I'd be happy to get that into the docs.  This could be officially credited to you and you would show up on the Astropy team contributor list.  (Though it makes me think that we also need a list of people that take time to submit issues, which also takes time.)

**Comment by Gabriel-p** [comment]
Thanks again @taldcroft! I should have realized that myself.

Since you've already opened #10001, I'm closing this one. Cheers
