### ISSUE TITLE
TypeError: sigma_clipped_stats() got an unexpected keyword argument 'iters'

### ISSUE THREAD

**Issue by dkhimey** [astropy/astropy#10161]
### Description
Each time I use a for loop to run through fits images in a folder and use solve from image function that uses Astronomy.net to solve for a header for my images, I get the error "TypeError: sigma_clipped_stats() got an unexpected keyword argument 'iters'". To fix this issue, I have to uninstall and reinstall astropy and astroquery. I run the same code on a single file and it works, but when I try to run it through the loop, it fails. When I go back to run it on a single file (using the exact same code that worked previously), it produces the error once again.

### Expected behavior
Solve image headers (possibly time out if taking too long)

### Actual behavior

TypeError: sigma_clipped_stats() got an unexpected keyword argument 'iters'

### Steps to Reproduce

1. Have an API key, free on nova.astrometry.net with github login
2. Have folder with multiple fits images
3. [and so on...]

```python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib

from astropy.io import fits
from astropy.stats import sigma_clipped_stats

from astropy import wcs
from astroquery.astrometry_net import AstrometryNet


ast = AstrometryNet()
ast.api_key = "____________" #Astrometry.net API key, free on nova.astrometry.net with github login

for filename in Folder: #where Folder contains multiple fits images

    HDUList = fits.open(filename)
    data = HDUList[0].data
    
    wcs_header = ast.solve_from_image(file)
    
    print('wcs header solved')
    
    HDUList[0].header = wcs_header
    
    print(file)


```

### System Details

Darwin-19.2.0-x86_64-i386-64bit
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.18.1
astropy 4.0.1.post1
Scipy 1.4.1

**Comment by dhomeier** [comment]
> TypeError: sigma_clipped_stats() got an unexpected keyword argument 'iters'

That would be because `solve_from_image` is [calling it](https://github.com/astropy/astroquery/blob/52b490c10074d45f0ed84990fd6cfc07a833ccd4/astroquery/astrometry_net/core.py#L393) with a deprecated interface; the keyword was changed to `maxiters` quite a while ago in d702235.

Not sure why it only shows up from the second pass on, much less why you'd need to **reinstall**, but this seems to be primarily an `astroquery` issue.

**Comment by pllim** [comment]
I agree with @dhomeier . Please open this issue with https://github.com/astropy/astroquery/issues . We apologize for any inconvenience caused.

Is the example not complete? I don't think it will even run. `file` is undefined in `wcs_header = ast.solve_from_image(file)`.

Usually when something goes wrong but only after first iteration, it is likely due to namespace being overwritted in the first pass. Or somehow you have multiple copies of `astropy` installed and Python is getting confused. 🤷

**Comment by dhomeier** [comment]
Actually it is already being addressed in https://github.com/astropy/astroquery/pull/1649 - probably no further need for action on your part (unless you are willing to test the PR ;-).
