### ISSUE TITLE
Error cloning repository

### ISSUE THREAD

**Issue by LouisJobert** [astropy/astropy#10225]
Hello all,

When I try cloning the repository, ($ git clone https://github.com/astropy/astropy.git), some errors appear :
error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, errno 0
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

I tried solutions but unfortunately without results. Did you have the same error when cloning ?
Thanks,

**Comment by dhomeier** [comment]
Works for my under Mac OS X 10.12 right now, and I haven't had or heard of any similar errors from github.
Could you provide some more details on your setup, e.g. what OS, versions of `git` and `curl` command line clients, and of your OpenSSL library? Also, what solutions did you try so far?

Thanks

**Comment by pllim** [comment]
What if you try to clone another repository that is not `astropy`? I have a feeling that the problem lies with your `git` and not related to this package. For example: https://forum.manjaro.org/t/solved-git-clone-failed-with-error-rpc-failed-curl-56-openssl-ssl-read-error-1408f119-ssl-routines-ssl3-get-record-decryption-failed-or-bad-record-mac-errno-0/40464

**Comment by dhomeier** [comment]
Mismatch of `curl` and installed `openssl` also looked like a prime suspect to me.

**Comment by LouisJobert** [comment]
Thanks @dhomeier and @pllim for your help. Effectively it was a Git problem, maybe cumulate with an Windows update, I uninstall/reinstall Git, restart Windows, it started correctly. Now ready to start contributions :) ,greetings,
