### ISSUE TITLE
Provide an easy way to generate zero/random coordinates

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10241]
As discussed in https://github.com/astropy/astropy/pull/10185#discussion_r416878148, it would be nice to avoid repetitive code such as

```python
observer = ICRS(ra=0 * u.degree, dec=0 * u.degree,
                pm_ra_cosdec=0 * u.mas/u.yr, pm_dec=0 * u.mas/u.yr,
                distance=0 * u.pc, radial_velocity=0 * u.km/u.s)
```

in tests (or even implementations). Having a way to do ``ICRS.zeros`` or ``np.zeros(ICRS)`` would be convenient, and similarly for random values.

**Comment by taldcroft** [comment]
This feels more like something that should be a test helpers function.  It isn't obvious how this would benefit normal users. The implementation in #10559 is very limited and I don't think it should be on the `ICRS` class.

**Comment by nstarman** [comment]
I recall reading discussion of greater mutability being added to the `BaseCoordinateFrames`. If this is ever implemented than pre-allocating memory before a loop would be quite nice. I certainly use `np.zeros` often to avoid `list.append` over a long array.

**Comment by taldcroft** [comment]
@nstarman - there is https://docs.astropy.org/en/stable/coordinates/inplace.html that can help with pre-allocation for performance-critical code.

**Comment by nstarman** [comment]
That's great. Thanks.

**Comment by mhvk** [comment]
Happened to note #10559 again which brought me here: I think this is indeed best done via a helper function, not a method, being fairly rare.

Thought I'd note that it could also be done by overriding a numpy function rather than adding a new one (via `__array_function__`; see #8610 for the general issue). In particular, one could override `np.zeros_like`. This would effectively do the same as:
```
In [28]: sc = SkyCoord([10, 20], [30, 40], unit='deg')

In [29]: sc._apply(np.zeros_like, shape=())
Out[29]: 
<SkyCoord (ICRS): (ra, dec) in deg
    (0., 0.)>
```
I think this may be closer to what @astrofrog had in mind, since generally one would want a `SkyCoord` similar to another one.

Though note that doing exactly as suggested above could lead to surprises: *any* array-valued attributes on the `SkyCoord` would be zeroed! So one would take some care if one actually defined an override in `SkyCoord.__array_function__`.

**Comment by adrn** [comment]
On second thought, from discussing this on the astorpy.coordinates call today, I'm now somewhat neutral or slightly negative on this idea. There is nothing particularly special about the position/velocity of fully zeroed out values in a frame. So maybe instead it would be more useful to have utility functions to create, e.g., uniform random points (on the sphere or in 3D). Makes writing tests a bit more verbose, but then they are also a bit more explicit about intent, so maybe that's ok...?

**Comment by adrn** [comment]
I'm going to close this, as I no longer think it is a good idea (and my comment in https://github.com/astropy/astropy/pull/10185#discussion_r416878148 instigated this - oops!)
