### ISSUE TITLE
Add TEME tests that are not remote_data

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#10255]
#10149 added the TEME frame, and included necessary unit tests.  However, the tests are `remote_data` because that makes sense for the obvious uses cases for this frame (satellites).  It's not a huge priority, but it would be a bit more robust (and make our coverage stats look better) if there were some tests for this frame that didn't require remote data.

cc @StuartLittlefair

**Comment by StuartLittlefair** [comment]
This is quite a widespread problem, no? Many tests in the coordinates package are marked as remote_data, due to the need to query non-astropy-data for the UTC-UT1 conversion.

Provided this conversion was well tested elsewhere we could remove remote_data marks for many of these tests by manually setting `detla_ut1_utc`?

**Comment by pllim** [comment]
FWIW -- Yes, you can mock it to avoid internet connection.

**Comment by pllim** [comment]
That said, it is no fun to mock, and I think it is part of a bigger problem of coordinates importing time causing IERS leap seconds table download. I can't seem to find that issue but I am pretty sure @mhvk knows which one. 😅
