### ISSUE TITLE
TST: Why so many conftest.py files?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10310]
### Description

I see many copies of `conftest.py` files buried in the package. The most troubling are `astropy/conftest.py` and `conftest.py` that contain duplicated code.

1. `astropy/coordinates/tests/conftest.py`
2. `astropy/table/tests/conftest.py`
3. `astropy/wcs/tests/conftest.py`
4. `astropy/wcs/wcsapi/conftest.py`
5. `astropy/conftest.py`
6. `docs/conftest.py`
7. `conftest.py`

### Expected behavior

One and only one `conftest.py` at root directory.

### Proposed solution

* Move stuff from lower level `conftest.py` files to the root level one. Eliminated duplicate code.
* Move subpackage specfici test helper functions into `subpackage/tests/utils.py` if they are not needed at the root `conftest.py` level.

### Need to know

* Is there a reason why proposed solution above wouldn't work?

**Comment by Cadair** [comment]
Having lower level conftest files which provide subpackage specific pytest fixtures is the recommended way of doing it. [ref](https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions)

I agree it can be a little magic as you have to look for conftest files to see where your fixtures are coming from, but I think it would cause more issues to try and work around pytest (pytest is sufficiently magic you are better off accepting the magic and becoming one with it than fighting against it imo).

I do wonder if the very top most level `conftest.py` file should be removed, I know pytest has been deprecating stuff in there because the behaviour is ill defined.

**Comment by pllim** [comment]
Really? I thought it is the other way around? I remember `pytest` chastising me in another package for having lower level `conftest.py` and implored me to use root-level one.

Besides, we need the root-level one to run `pytest ...` from root level during dev testing locally.

**Comment by Cadair** [comment]
:shrug:

**Comment by pllim** [comment]
I think @astrofrog said something about the test runner. Ah well.
