### ISSUE TITLE
Coverage often errors for no reason 

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10463]
coverage often errors even if no code has been touched (e.g., #10452, #10428, neither of which touched any code). Does anyone know how to fix it? (For my own projects, I cannot even get it to connect, so I'm hopeless...) Until then, I would suggest to at least not make it a requirement for tests to pass...

**Comment by pllim** [comment]
#10452 's "failure" is because the *diff* is not being tested in the coverage job (not surprising considering it is to fix cron jobs).

#10428 's "failure" is because the tolerance is too strict (I think) and it can be relaxed [using codecov.yml](https://docs.codecov.io/docs/codecov-yaml#default-yaml) that we already have. Maybe reducing [precision](https://docs.codecov.io/docs/codecovyml-reference#coverageprecision) from 2 to 1? (I think 1 is less precise though I am not sure because there is not much documentation there.)
