### ISSUE TITLE
astropy.io.votable.parse_single_table incorrectly parses tables with different`name` and `ID` values.

### ISSUE THREAD

**Issue by odysseus9672** [astropy/astropy#10466]
### Description

I have a VOtable downloaded from IRSA. TOPCAT correctly parses the column names from the `name` parts of the `FIELD` tags. Astropy names the columns after the `ID` part of the `FIELD` tags. 
[results.xml.zip](https://github.com/astropy/astropy/files/4741673/results.xml.zip)

### Expected behavior

A table with columns named `['name', 'ra', 'dec',...]`.

### Actual behavior

A table with columns named `['name', 'col_1', 'col_2',...]`.

### Steps to Reproduce

1. Run python or ipython in the directory containing `results.xml`.
2. Execute the following commands:
```python
import astropy.io.votable as apvo
t = apvo.parse_single_table("results.xml").to_table()
t.colnames
```

### System Details

Darwin-19.4.0-x86_64-i386-64bit
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)]
Numpy 1.18.5
astropy 4.2.dev236+g2023292bc
Scipy 1.4.1
Matplotlib 3.2.1

**Comment by pllim** [comment]
@odysseus9672 , the `astropy` behavior you see is correct despite being confusing. ID is used over names because ID is guaranteed by the standards to be unique. This is explained in the green note in https://docs.astropy.org/en/latest/io/votable/index.html#examples . There is also a way to overwrite this behavior, as documented.

Given that you want your table to actually be `astropy.table.Table`, you can also use the `Table` interface directly, like this:
```python
>>> from astropy.table import Table
>>> t = Table.read('results.xml', format='votable', use_names_over_ids=True)
>>> t
```
```
 name      ra        dec     err_maj err_min ... k_msigcom k_psfchi cc_flg   prox     jdate    
          deg        deg      arcsec  arcsec ...    mag                     arcsec    jdate    
object  float64    float64   float64 float64 ...  float64  float64  object float64   float64   
------ ---------- ---------- ------- ------- ... --------- -------- ------ ------- ------------
     2  20.483529  14.806652    0.08    0.07 ...     0.134     1.39    000   114.1 2450699.8958
     1  14.250856  14.627168    0.17    0.16 ...     0.115     0.90    000    76.9 2451877.7954
 clone  14.250856  14.627168    0.17    0.16 ...     0.115     0.90    000    76.9 2451877.7954
     3  21.051937  -1.013808    0.13    0.07 ...     0.078     0.89    000    49.6 2451076.7161
     4  26.319191  -9.754796    0.12    0.06 ...     0.082     1.31    000    74.0 2451116.6580
```

Not part of your question, but running a linter on the file also produced the following warning:
```
$ volint results.xml 
Validation report for results.xml

55: W50: Invalid unit string 'jdate'
      <FIELD name="jdate" datatype="double" ID="col_17" precision="...
``` 

If this answers your question, please close the issue. Thanks!
