### ISSUE TITLE
Add copy=False option to Quantity.to

### ISSUE THREAD

**Issue by bmerry** [astropy/astropy#10514]
### Description
Currently `Quantity.to` always makes a copy of the data, even if the target unit is the same. It would be useful to call `q.to(u.m, copy=False)` which would only copy if necessary.

### Additional context
While the newish `<<` operator helps to reduce copies, it can lead to mistakes because it does two unrelated things:
1. If the left side is a quantity, it performance unit conversion (like `Quantity.to`, but only copying if necessary);
2. If the left side is some other array-like, it performs Quantity construction (like `*`, but only copying if necessary).

If a function is supposed to take a Quantity and uses `<<` to ensure that it is working in a particular unit (maybe so that future arithmetic operations won't need to do conversions, or so that unit errors are caught early), the user could accidentally pass a plain ndarray (which could be in any units) and instead of failing, it will be assumed that it's in whatever units are being converted to.

Additionally, `<<` is not convenient for working with equivalencies.

**Comment by pllim** [comment]
In a way, this is already possible, though perhaps not very obvious from just reading [this section](https://docs.astropy.org/en/stable/units/quantity.html#creating-and-converting-quantities-without-copies):

```python
>>> import numpy as np
>>> from astropy import units as u
>>> a = [1, 2] * u.deg_C
>>> with u.add_enabled_equivalencies(u.temperature()):
...     b = u.Quantity(a, u.imperial.deg_F, copy=False)
>>> np.may_share_memory(a, b)
False
>>> with u.add_enabled_equivalencies(u.temperature()):
...     c = u.Quantity(a, u.deg_C, copy=False)
>>> np.may_share_memory(a, c)
True
>>> a
<Quantity [1., 2.] deg_C>
>>> b
<Quantity [33.8, 35.6] deg_F>
>>> c
<Quantity [1., 2.] deg_C>
```

Maybe @mhvk can elaborate.

**Comment by bmerry** [comment]
I don't see that as being any better than `<<` for my primary concern, which is that I want to force the user to tell me the units of their numeric values, and not accept plain ndarrays.

I also tend to avoid `add_enabled_equivalencies` because it doesn't look thread-safe.

**Comment by mhvk** [comment]
@bmerry - in principle, this is not too difficult - all that is really needed is add the keyword and make this line:
https://github.com/astropy/astropy/blob/437ef257f317c099613bbac78def59f7b011fa09/astropy/units/quantity.py#L689
one that uses `to_value` instead of `_to_value` for `copy=False` (that would still construct a new view, which probably could be avoided too; the `to_value` function tells what one would need to do).

That said, as I used quantities, I found myself that changing the quantity to a specific unit was generally not really necessary - after all, in calculations it gets converted as needed anyway. The only exception is when I need the value, but `to_value` already does return a view when possible. Hence, I'm curious to hear where you do find it useful.

p.s. I guess having `copy=False` has an analogy in its use in `astype`.

**Comment by bmerry** [comment]
> That said, as I used quantities, I found myself that changing the quantity to a specific unit was generally not really necessary - after all, in calculations it gets converted as needed anyway.

Fair question and a reasonable point. I've got a few use cases:
- My motivation for filing the issue is that I'm using `astropy.table.QTable.as_array` to export the values of a table to an API that expects a numpy structured array with specific units. For now I'm solving that by making the units canonical at the same I construct the QTable, but I could probably also do it just before calling `as_array` by calling `to_value` on each column and then assembling the numpy structured array from the individual columns.
- A slightly more theoretical one for me at the moment is computational efficiency. If one is storing a quantity in a class and you know that it'll frequently be needed in a particular unit (e.g. angles that will be used with trig functions are going to needed in radians) then it's probably more efficient to convert them when constructing the class rather than on every use.
- A handy (but expensive) side effect of converting to a particular unit is that it's an assertion that the units are compatible. Functions like `is_equivalent` will do the check but then you still have to generate the exception message yourself; while the `quantity_input` decorator is limited to function arguments and doesn't play nicely with annotations for mypy.

> p.s. I guess having copy=False has an analogy in its use in astype.

Indeed.

**Comment by mhvk** [comment]
Yes, the computational efficiency is a fair point. Also, reading your comments and your note about equivalencies, that gives another reason: where one expects mostly, say, frequency in `u.Hz` but wants the option to pass in wavelength: you'd want to do the conversion only once.

Anyway, I was close to being convinced and since it should be a non-invasive change, I'm happy to go for it. Would you be willing to make a PR? As noted above, the implementation should be easy, so the main work might be to write good test cases (including that, in fact, no data are copied). For documentation, the docstring would be most important, though perhaps an entry in the performance section might make sense too.

**Comment by bmerry** [comment]
> Would you be willing to make a PR?

I can take a look - probably next week.

**Comment by bmerry** [comment]
@mhvk I've created a PR. I hadn't appreciated that `to_value` already avoids unnecessary copies.
