### ISSUE TITLE
Should TableColumns keys and values be generators now?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10525]
I stumbled upon this:

https://github.com/astropy/astropy/blob/1f75aa164539949723971d5b767f9517a3d77344/astropy/table/table.py#L285-L290

The comment said they were defined for PY2/PY3 compatibility. We have dropped PY2 since v3.0. Ideally, we should also be able to remove these if they were indeed only for compatibility. However, they revert to PY2 behavior, which makes removal impossible in the PY3 world. Should `keys` and `values` really by generators now?

**Comment by taldcroft** [comment]
I agree in principle they should both be generators.  I do worry a bit about someone that has code like `t.columns.values()[5]`.  Of course that *should* be written as `t.columns[5]`.  Likewise `t.columns.keys()[5]` should be `t.colnames[5]`.

Since there are easy back-compatible workarounds, maybe it wouldn't be the end of the world to change.

Do you have an opinion @mhvk?

**Comment by mhvk** [comment]
I'm very much in favour of methods behaving as much as possible as python intrinsics, so :+1: to the idea.
When I saw this, I worried about back-compatibility as well, but I agree that given that there are backwards-compatible *preferred* solutions for people who really want a list, that is not a big worry in this case.
I do vaguely recall that we had this discussion before, with a less clear outcome. Maybe for `Row`?
