### ISSUE TITLE
logspace does not work with quantities since version 4

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#10573]
### Description

Calling `numpy.logspace` on dimensionless quantities does not work in astropy 4. 
It used to work in astropy 3.

### Expected behavior

Works.

### Actual behavior
Raises an exception

### Steps to Reproduce

Example with context to show why this might be useful:

```python
import astropy.units as u
import numpy as np

e_min = 100 * u.GeV
e_max = 1 * u.TeV
e_ref = 1 * u.GeV

bins = np.logspace(np.log10(e_min / e_ref), np.log10(e_max / e_ref), 100)
```

Minimal example:

```python
import astropy.units as u
import numpy as np

np.logspace(u.Quantity(1), u.Quantity(3), 100)
```

Result with astropy 3: works

Result with astropy 4:
```
TypeError: no implementation found for 'numpy.logspace' on types that implement __array_function__: [<class 'astropy.units.quantity.Quantity'>]
``` 

### System Details
```
Linux-5.7.8-arch1-1-x86_64-with-glibc2.2.5
Python 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
Numpy 1.19.0
astropy 4.0.1.post1
Scipy 1.5.1
Matplotlib 3.2.2
```

**Comment by MaxNoe** [comment]
As a workaround in the mean time, `.to_value(u.dimensionless_unscaled)` has to be used.

Sidenote, I wish there was a shorter version of `u.dimensionless_unscaled`

**Comment by dhomeier** [comment]
Strangely it also still works with numpy 1.16.

> Sidenote, I wish there was a shorter version of `u.dimensionless_unscaled`

You can use
`np.logspace(np.log10(e_min / e_ref).value, np.log10(e_max / e_ref).value, 100)`
for a slightly shorter variant
 – or even shorter
`np.geomspace(e_min / e_ref, e_max.to('GeV') / e_ref, 100)`
😺 

Why `np.logspace` is not working directly is a bit mysterious, as it is internally just using `linspace` and `np.core.numeric.power`, which both work for quantities.

**Comment by MaxNoe** [comment]
> Why np.logspace is not working directly is a bit mysterious, as it is internally just using linspace and np.core.numeric.power, which both work for quantities.

I think logspace is explicitly implemented in `astropy.units.quantity_helpers.function_helpers` and raises `NotImplemented` for anything that is not a `LogarithmicQuantity`.

> You can use `np.logspace(np.log10(e_min / e_ref).value, np.log10(e_max / e_ref).value, 100)`

No, I cannot, as `(1 * u.TeV / (1 * u.GeV)).value == 1`, the conversion to `u.dimensionless_unscaled` is required.

**Comment by pllim** [comment]
Does astropy 3 still work with the latest numpy (1.19)?

Maybe @mhvk can comment.

**Comment by mhvk** [comment]
In 4.0, all numpy functions became quantity-aware, so the automatic ".value" that used to happen has been removed. Still, supporting `.to_value(u.one)` (which is the short-hand; can also use `.to_value(1)` if really lazy) would probably make sense.

In my implementation, the way it is meant to be used is
```
e_min = 100 * u.GeV 
e_max = 1 * u.TeV 
e_ref = 1 * u.GeV 
np.logspace(u.Dex(e_min / e_ref), u.Dex(e_max / e_ref), 10)
# <Quantity [0.1       , 0.12915497, 0.16681005, 0.21544347, 0.27825594,
#            0.35938137, 0.46415888, 0.59948425, 0.77426368, 1.        ] TeV / GeV>
```
Though for this particular example I think it may be cleaner to use `np.geomspace` instead,
```
np.geomspace(e_min / e_ref, e_max / e_ref, 10)                                                                                                      
<Quantity [0.1       , 0.12915497, 0.16681005, 0.21544347, 0.27825594,
           0.35938137, 0.46415888, 0.59948425, 0.77426368, 1.        ] TeV / GeV>
```

p.s. Actual code for the support for the two at
https://github.com/astropy/astropy/blob/e0f4de3553e99dbee643c759d7364b0c64708201/astropy/units/quantity_helper/function_helpers.py#L789-L807

**Comment by mhvk** [comment]
p.s. I think (hope?) that at least one of the solutions above is backwards compatible with astropy 3!

**Comment by dhomeier** [comment]
> p.s. I think (hope?) that at least one of the solutions above is backwards compatible with astropy 3!

Both work with 3.2.3 and Numpy 1.19.0; the `np.geomspace` solution also with 2.0 and Numpy 1.16 (on Python2.7).
Seems reasonable to use `u.Dex` instead of `np.log10` for a more general solution; however that
`u.Dex(e_min / e_ref)` is a `u.LogQuantity` instance, while `np.log10(e_min / e_ref)` is not (but is a `u.Quantity`) still looks a bit odd. I guess it is because numpy carries over the `Quantity` attribute, but cannot add the `LogQuantity` subclass on its own, so that might be nontrivial to fix.

**Comment by mhvk** [comment]
@dhomeier - note that the *output* of `np.logspace(u.Dex(...))` is still a regular `Quantity`, so in that respect nothing changes.

I guess there are two issues/questions now:
- Code: Should `np.logspace` support dimensionless quantities. I think this is do-able, but the result would be that the output would be dimensionless?
- Documentation: would be good to document expectations; my sense is that this should be auto-generated from the wrapping functions - which can then have examples in their docstrings - otherwise there is no way this will be kept up to date.

**Comment by mhvk** [comment]
p.s. But for the documentation even just having a note about pitfalls (where `np.logspace` is a good example) would be useful...

**Comment by MaxNoe** [comment]
I never knew about `u.Dex`, TIL

**Comment by dhomeier** [comment]
> @dhomeier - note that the _output_ of `np.logspace(u.Dex(...))` is still a regular `Quantity`, so in that respect nothing changes.

As it should of course, since the output is not logarithmic. I did not mean to imply `u.Dex` was not a good alternative, or in fact the best default way to handle this (or at least in cases that `np.geomspace` might not handle), just that users could be justifiably confused about the different behaviour with `np.log10`.
+1 for improved documentation
> 
> I guess there are two issues/questions now:
> 
> * Code: Should `np.logspace` support dimensionless quantities. I think this is do-able, but the result would be that the output would be dimensionless?

Isn't the output in the example already dimensionless, having `unit` `Unit("TeV / GeV")` and `_default_unit` `Unit(dimensionless)`?

**Comment by mhvk** [comment]
@dhomeier - right now, the output is scaled dimensionless; if we were to allow dimensionless inputs, the output would have to be unscaled dimensionless. Though, overall, my sense would be that this will just complicate things.

For the documentation, I made an issue for the elaborate version (#10575) - I just looked at the current documentation and sadly it is not very obvious where to put in a smaller note - as is, the discussion is rather limited and what would be most logical is to have a link to a new page with full (auto-generated...) details; see https://docs.astropy.org/en/latest/units/quantity.html#numpy-functions

**Comment by dhomeier** [comment]
> @dhomeier - right now, the output is scaled dimensionless; if we were to allow dimensionless inputs, the output would have to be unscaled dimensionless. Though, overall, my sense would be that this will just complicate things.

It is unscaled dimensionless for the `e_max.to('GeV')` variant, which yields a `unit` `Unit(dimensionless)` quantity, right (note I cannot even name a clear identifier of dimensionless scaled vs. dimensionless unscaled quantities...)?
I agree it would probably mostly complicate things, but mainly I do not see an obvious use case for a dimensionless _input_ to `np.logspace`.

**Comment by mhvk** [comment]
closing in favour of #10575 - needs better documentation!
