### ISSUE TITLE
The precision of get_sun function

### ISSUE THREAD

**Issue by cnwangfeng** [astropy/astropy#10713]
I got a confused problem when I tried to use get_body or get_sun function. 
The observational time is 2015-11-22T04:50:35.807
Lgt = 115.2505  # local longitude in degree
Lat = 42.211833333  # local latitude in degree
E = 1365  # local altitude in meter

I used get_body() and DE432s ephemeris to calculate the Hour Angle with two different method. The results is listed as follows. 
SUN: RA:237.12564970908176 Dec:-20.008144679939594
UTC: 2015-11-22T04:50:35.807 Local Hour Angle: 11.407194907554697
UTC: 2015-11-22T04:50:35.807 Local Hour Angle: 11.638674726356385 deg

However, the result I expected would be: 
RA: 237.3566174951244
DEC: -20.05154786561006
Hour Angle = 11.406580716728115

Obviously, there are about 0.2 Degrees errors with RA and more tan 0.04 degrees errors with DEC. Is there anything wrong with my codes? 

Thanks a lot. 

Feng (cnwangfen@gmail.com)

My codes: 
```
from astropy.coordinates import SkyCoord
from astropy.time import Time
from astropy import units as u
from astropy.wcs.utils import pixel_to_skycoord
from astropy.coordinates import solar_system_ephemeris, EarthLocation, ITRS
from astropy.coordinates import get_body_barycentric, get_body, get_moon, get_sun
import astropy.coordinates as coord

def sun_position(obs_time):
    location = EarthLocation(lon=115.2505 * u.deg, lat=42.211833333 * u.deg, height=1365.0 * u.m)
    solar_system_ephemeris.set('de432s')
    phasecentre = get_body('sun', obs_time, location, ephemeris='jpl')
    print('SUN: RA:{} Dec:{}'.format(phasecentre.ra.value, phasecentre.dec.value))
    # convert phasecentre into ITRS coordinate
    c_ITRS = phasecentre.transform_to(ITRS(obstime=obs_time))
    local_ha = location.lon - c_ITRS.spherical.lon
    local_ha.wrap_at(24 * u.hourangle, inplace=True)
    print("UTC: {} Local Hour Angle: {}".format(obs_time, local_ha.to('deg').value))
    obs_time1 = Time(obs_time,scale='utc', location=location)
    lst = obs_time1.sidereal_time('mean')
    local_ha1 = lst.to('deg').value - phasecentre.ra.value
    print("UTC: {} Local Hour Angle: {}".format(obs_time, local_ha1*u.deg))
    sun = coord.get_sun(obs_time)
    sun_icrs = sun.transform_to(coord.ICRS)
    print(sun_icrs)

def main(args):
    obs_time = Time(args.start, format='isot', scale='utc')
    sun_position(obs_time)

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description="Output The SUN's position")
    parser.add_argument('-s', "--start", type=str, default='', help='The beginning time ')
    main(parser.parse_args())
```
My environment: 
Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ]
Numpy 1.18.5
astropy 4.0.1.post1
Scipy 1.2.1
Matplotlib 3.2.2

**Comment by ayshih** [comment]
It appears that you are not comparing in the same coordinate system.

> However, the result I expected would be:
> RA: 237.3566174951244
> DEC: -20.05154786561006
> Hour Angle = 11.406580716728115

Your expected values appear to be the apparent RA/dec of the Sun, including the effects of precession and nutation at the observation time.

```python
    phasecentre = get_body('sun', obs_time, location, ephemeris='jpl')
    print('SUN: RA:{} Dec:{}'.format(phasecentre.ra.value, phasecentre.dec.value))
```
Here, you have printed out the RA/dec in GCRS – the coordinate frame that is returned by `get_body()` – which is an ICRF-aligned coordinate system and does not include precession/nutation.

You may have already noted that converting `phasecentre` to `ITRS` has the latitude of -20.0514 deg, which is a lot closer to your expected value for the declination.  That's because `ITRS` accounts for precession/nutation.  Note that your first approach to calculating the hour angle uses the `ITRS` longitude, so precession/nutation are being included, and that's why it's far less discrepant than the RA values.

Incidentally, Astropy's coordinate frame `PrecessedGeocentric` accounts for precession (but not nutation).  If you convert your `phasecentre` to `PrecessedGeocentric` with the `equinox` frame attribute set to your observation time (as opposed to the default value of J2000.0), you will get something much closer to what you're looking for:
```
<SkyCoord (PrecessedGeocentric: equinox=2015-11-22T04:50:35.807, obstime=2015-11-22T04:50:35.807, obsgeoloc=(-1723136.06
056917, -4405002.79651391, 4266414.23553063) m, obsgeovel=(321.20231483, -126.13192675, -0.50070119) m / s): (ra, dec, d
istance) in (deg, deg, km)
    (237.35635672, -20.05600478, 1.47763703e+08)>
```
The remaining discrepancy should be largely due to the missing nutation correction.

**Comment by pllim** [comment]
Hello. If this issue has been resolved for you, please close it.

**Comment by cnwangfeng** [comment]
@ayshih Hi, Many thanks for the help. 

Thanks for telling me that PrecessedGeocentric would get more accurate results. However, is it possible to further consider nutation correction upon the results? 

And I hope to get the transit time of the SUN (or other objects) in astropy? May you tell me the possible solution with high precision? 

Thanks again. 

Feng

**Comment by ayshih** [comment]
There's no existing Astropy coordinate frame that does exactly what you want.  Certainly you can request that such a coordinate frame be implemented.  It would not be difficult to do so, but Astropy may wish to avoid too many similar coordinate frames.

If all you need is RA/dec values, rather than a nice coordinate object, you can use the First Point of Aries to figure out the RA:
```python
>>> from astropy.coordinates import EarthLocation, Longitude, SkyCoord, get_body, solar_system_ephemeris
>>> from astropy.time import Time
>>> import astropy.units as u

>>> obs_time = Time('2015-11-22T04:50:35.807', format='isot', scale='utc')
>>> location = EarthLocation(lon=115.2505 * u.deg, lat=42.211833333 * u.deg, height=1365.0 * u.m)

>>> solar_system_ephemeris.set('de432s')
>>> sun = get_body('sun', obs_time, location)
>>> sun
<SkyCoord (GCRS: obstime=2015-11-22T04:50:35.807, obsgeoloc=(-1723136.06056917, -4405002.79651391, 4266414.23553063) m,
obsgeovel=(321.20231483, -126.13192675, -0.50070119) m / s): (ra, dec, distance) in (deg, deg, km)
    (237.12564967, -20.00814467, 1.47763703e+08)>

>>> aries = SkyCoord(0*u.deg, 0*u.deg, frame='geocentrictrueecliptic', obstime=obs_time, equinox=obs_time)

>>> RA = Longitude(sun.itrs.spherical.lon - aries.itrs.spherical.lon)
>>> RA
<Longitude 237.35660401 deg>

>>> dec = sun.itrs.spherical.lat
>>> dec
<Latitude -20.05141053 deg>
```
You didn't specify where you got your expected values, so I don't know whether the remaining discrepancies  – ~0.05 arcsec in right ascension and ~0.5 arcsec in declination – are easily explained.

Regarding your question about transit times, I don't immediately know the best way to do so using Astropy.

**Comment by cnwangfeng** [comment]
@ayshih, Thanks. 

The expected values are apparent position calculated by JPL ephemeris. Of course, I considered the precession and nutation. The variation of north pole was also considered. I have checked those values and compare them with some online ephemeris such as imcce.fr. I think it's very accurate. 

Actually, I only want to get an accurate result of Topcentric coordinate. It just like the Observer in previous PyEphem. Is there related function or coordinate system in astropy? 

Sorry to trouble you for many times. Thanks a lot. 

Feng

**Comment by astrojuanlu** [comment]
@cnwangfeng perhaps [`AltAz`](https://docs.astropy.org/en/stable/api/astropy.coordinates.AltAz.html) is what you're looking for?

**Comment by cnwangfeng** [comment]
Maybe. Of course, I can transform to AltAz first, and convert it to Equation Coordinates of Hour Angle and Dec.
