### ISSUE TITLE
TST: pyinstaller cron job failed with MATPLOTLIBDATA environment variable was deprecated

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10785]
Example log: https://travis-ci.org/github/astropy/astropy/jobs/731532639

```
ImportError while loading conftest '/home/travis/build/astropy/astropy/.pyinstaller/astropy_tests/conftest.py'.
_pytest/config/__init__.py:570: in _importconftest
    ???
_pytest/pathlib.py:517: in import_path
    ???
_pytest/assertion/rewrite.py:171: in exec_module
    ???
astropy_tests/conftest.py:22: in <module>
    import matplotlib
../.tox/pyinstaller/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py:489: in exec_module
    exec(bytecode, module.__dict__)
matplotlib/__init__.py:1015: in <module>
    ???
matplotlib/__init__.py:878: in rc_params
    ???
matplotlib/__init__.py:731: in matplotlib_fname
    ???
matplotlib/__init__.py:729: in gen_candidates
    ???
matplotlib/__init__.py:276: in wrapper
    ???
matplotlib/__init__.py:653: in _get_data_path
    ???
matplotlib/cbook/deprecation.py:111: in warn_deprecated
    ???
matplotlib/cbook/__init__.py:1993: in _warn_external
    ???
E   matplotlib.cbook.deprecation.MatplotlibDeprecationWarning:
E   The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
ERROR: InvocationError for command /home/travis/build/astropy/astropy/.pyinstaller/run_astropy_tests (exited with code 4)
```

Naive re-pinning didn't work (#10779).

Also see: #10639

**Comment by embray** [comment]
Yeah, I noticed that.  I'll take care of it.

**Comment by embray** [comment]
I was able to reproduce the issue locally, so that's a start.

**Comment by embray** [comment]
#10793 appears to resolve the issue insofar as it affects our CI.  The deprecation being warned about does not appear to otherwise impact successful running of the Astropy tests.

I'm inclined to not go any further with it for now.  In principle this issue can affect users using PyInstaller to bundle astropy in an application.  However, as I noted in the PR, the issue is not unique to astropy, and could affect different applications in different ways (e.g. how soon they import matplotlib compared to astropy).  So I would suggest to leave it for now, and if anyone is actually impacted by this issue we can point them to adding this workaround in their own application.

**Comment by pllim** [comment]
@embray , for clarity, I'll open a new issue that clarifies the issue properly once your fix is in. This one was specifically about the cron job and might confuse people anyway unless they care to read the entire thread. Thanks for your help!
