### ISSUE TITLE
Documentation errors in io.fits

### ISSUE THREAD

**Issue by lbleier-GSFC** [astropy/astropy#10817]
### Description
Documentation shown here: https://docs.astropy.org/en/stable/io/fits/api/files.html has multiple issues

Under `open()`, description of `lazy_load_hdus` parameter states default is `True` yet function signature shows `None`
Under `update()` there is a `header` parameter documented that does not appear in the function signature
Multiple instances of `ext`, `extname`, `extver` in docs but `*args` is shown in function signature (not sure if this is intentional)

**Comment by saimn** [comment]
There are no errors:
- `open`: the value for `lazy_load_hdus` (and `memmap`) is `None` because the default value comes from the configuration file (https://docs.astropy.org/en/latest/config/astropy_config.html#astropy-config-file).
- `update`: `header` is passed through `*args` or `**kwargs`
- `ext, extname, extver`: can be passed both through  `*args` or `**kwargs` as well

When using `*args` and `**kwargs` some arguments will not appear in the signature, but this is the way it works, and the reason why they are documented in the docstring.  `open` also has many arguments passed through `**kwargs` for example.
