### ISSUE TITLE
Inconsistent BPN matrix used in _apparent_position_in_true_coordinates()

### ISSUE THREAD

**Issue by mkbrewer** [astropy/astropy#10827]
The BPN matrix used in `coordinates.solar_system._apparent_position_in_true_coordinates()` is inconsistent with that used in `builtin_frames.utils.get_cip()`. This causes a small error in the apparent position with respect to the true equator and equinox of date when comparing it with the same coordinates obtained by subtracting the equation of the origins from astropy's CIRS right ascension. Now I know that this is an internal function, but it is currently the only way to get the apparent position with respect to the true equator and equinox of date until the appropriate frame is implemented (see issue #10230). Besides, fixing this is trivial. It involves changing only one line of code. From: 
```
    _, _, _, _, _, _, _, rbpn = erfa.pn00a(jd1, jd2)
```
to:
```
    rbpn = erfa.pnm06a(jd1, jd2)
```
This bug is so obvious that I feel that it needs no further documentation. It can easily be verified by mere inspection of `builtin_frames.utils.get_cip()`

**Comment by mhvk** [comment]
Thanks for raising this. I vaguely recalled that I had seen something about `pnm06a` before, but of course that was just you pointing the problem out before in https://github.com/astropy/astropy/pull/10666#issuecomment-679341092. Rereading the discussion, it is sad not to have a specific test case, but as you note, we should at the very least be consistent, and since this is a private routine only used for tests inside astropy, we may as well adjust.  I'll make a PR.

cc @StuartLittlefair

**Comment by mkbrewer** [comment]
@mhvk Thank you! I will close this issue as your PR will fix the problem.
