### ISSUE TITLE
Wrong epoch used in Time.plot_date if matplotlib>=3.3

### ISSUE THREAD

**Issue by kerel-fs** [astropy/astropy#10856]
:beetle: **Problem**

`astropy.Times.plot_date` returns seemingly wrong results when matplotlib>3.3 is installed:

```python
from matplotlib.dates import num2date, date2num
t_astropy = Time('2020-10-14T10:00:00')
num2date(t_astropy.plot_date)
```
Result: ```datetime.datetime(3989, 10, 15, 10, 0, tzinfo=datetime.timezone.utc)```
Expected: ```datetime.datetime(2020, 10, 14, 10, 0, tzinfo=datetime.timezone.utc)``` (1969 years into the future)

This is caused by matplotlib [using a new epoch](https://matplotlib.org/3.3.1/users/whats_new.html#dates-use-a-modern-epoch) starting with 3.3 for dates.

:bulb: **Possible solution**

- Probably astropy should use matplotlib.get_epoch if matlotlib >= 3.3 \[in [time/formats.py#L802](https://github.com/astropy/astropy/blob/e74ae753be1f7d5b0386a38dcf9d98690c669e44/astropy/time/formats.py#L802) \]
  (thanks @maxnoe !)

**Comment by kerel-fs** [comment]
It's a bit harder than I though initially:

The matplotlib date epoch is configurable, [`matplotlib.get_epoch`](https://github.com/matplotlib/matplotlib/blob/405684d6e12494f1604af0b5fbac10f3723e09de/lib/matplotlib/dates.py#L272-L285) returns it as String "parsable by `numpy.datetime64`". So what is left to do is to find a way to calculate our required `epoch_val`, `epoch_val2`, etc from this `numpy.datetime64`. Maybe the [`TimeDatetime64`](https://github.com/astropy/astropy/blob/abd73b51277694338c8eca7639da956dcd06f207/astropy/time/formats.py#L1409-L1454) formatter class can be used here?

---

> p.s. Nice touch with the emojis!

thanks! Inspired by the [bug template for poliastro](https://github.com/poliastro/poliastro/blob/master/.github/ISSUE_TEMPLATE/bug.md).

**Comment by pllim** [comment]
Hopefully @taldcroft or @mhvk can advise. Thanks for looking into this!

**Comment by mhvk** [comment]
Thanks so much for reporting and sleuthing! Since it seems that the epoch is something that the user can set after importing matplotlib, I think we sadly have to call `get_epoch` at instance creation time. But this is not difficult: one can override the `epoch` property that is defined in the `TimeFromEpoch` base class: https://github.com/astropy/astropy/blob/e74ae753be1f7d5b0386a38dcf9d98690c669e44/astropy/time/formats.py#L584-L602

So, I think one would override `epoch` and let it check whether `get_epoch` exists; if so, parse the string (it is just an isot string, so easy) and then set `epoch_val` and `epoch_val2` accordingly (so that later conversion is done correctly), and then return the time instance.

**Comment by taldcroft** [comment]
Ugh, though the original epoch for mpl was silly so I agree with them fixing it. I'll have a go at a quick fix.

**Comment by kerel-fs** [comment]
I can confirm this is fixed in current master (via [this gist](https://gist.github.com/kerel-fs/01b3730cd39222ca531921f0459aa493) [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/kerel-fs/01b3730cd39222ca531921f0459aa493/master)).
Thanks for the pleasant communication and fast fix!

**Comment by mhvk** [comment]
Thanks again for reporting - happy that now for other users it will just work!
