### ISSUE TITLE
Consider adding `__array__` method to `TimeBase` to return `value`?

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#10859]
### Description

From [this slack question](https://app.slack.com/client/T067V5AR2/C0LAMJCRE/thread/C0LAMJCRE-1602705646.012700), I was wondering about a protocol for `Time` that `np.array(tm)` or `np.asarray(tm)` would return `tm.value`. In theory this could apply to `SkyCoord`. Currently in both cases doing `np.array(..)` returns an array of `Time` or `SkyCoord` objects, which in practice is rarely what you wanted.

I guess one snag is if the Time value has missing values and `tm.value` returns a MaskedArray.

There is also the original suggestion of adding a `.value` attribute to `Column` to make it more like `Time` and `Quantity`. Again this could in theory apply to `SkyCoord`, where it would return e.g. an `N x 3` np.array.

This is definitely a question for @mhvk!

**Comment by mhvk** [comment]
@taldcroft - to me, it seems a bit too much magic that the array will depend on the format (or be a particular `Nx3` array for `SkyCoord`). But that aside, I know this would break, e.g., PINT, which uses a `Column` of object array `Time` entries (which they need to do since the `Time` instances are arrival times from different locations, including some satellite ones where `location=None`). And other people are presently relying on, e.g., `np.diff(time)` to return an object array of `TimeDelta` - see https://github.com/astropy/astropy/issues/10501.

I do see a benefit to `.value` for `Column` - if only to (very eventually) replace `.data` with that (and thus get rid of the `MaskedColumn` difficulties from it being defined in both `MaskedArray` and `Column`).

For `SkyCoord`, if we had something like that, I think it would need to be a structured array (say, with `lon,lat,distance`), but I'm not sure there would be that much use for it.

**Comment by pllim** [comment]
cc @barentsen

**Comment by taldcroft** [comment]
@mvhk - fair enough, good points. I'm OK with adding `.value` to `Column`.  And I guess `MaskedColumn` too?

@barentsen - care to do a PR? :smile:

**Comment by barentsen** [comment]
> @barentsen - care to do a PR? 😄

@taldcroft You got it! :+1:

**Comment by barentsen** [comment]
Follow up: I opened a PR to add `.value` to `Column` over at #10962.
