### ISSUE TITLE
Rework argument handling in astropy.utils.data functions that use download_file

### ISSUE THREAD

**Issue by embray** [astropy/astropy#10926]
Follow-up to #10434

There are several functions in `astropy.utils.data` that wrap the `download_file` function.  Many of them take arguments that are passed to `download_file`, but this is handled inconsistently.

For example:

* [`get_readable_fileobj`](https://docs.astropy.org/en/stable/api/astropy.utils.data.get_readable_fileobj.html#astropy.utils.data.get_readable_fileobj) largely copies the arguments to `download_file`, as well as their docstrings (unneccessary duplication).  It could instead take some `**kwargs` and document that they are passed to `download_file`.

* [`download_files_in_parallel`](https://docs.astropy.org/en/stable/api/astropy.utils.data.download_files_in_parallel.html#astropy.utils.data.download_files_in_parallel) takes most of the same arguments as `download_file` but not all

* [`get_pkg_data_filename`](https://docs.astropy.org/en/stable/api/astropy.utils.data.get_pkg_data_filename.html#astropy.utils.data.get_pkg_data_filename) and friends use `download_file` with some specific arguments, but it might be nice to be able to pass additional `download_file` arguments (such as `allow_insecure`).  However, accepting any arbitrary keyword arguments to `download_file` might not work here (for example these functions already take a `remote_timeout` argument, where this is passed to the corresponding `timeout` argument of `download_file`).

It might be nice to brainstorm a plan to clean this up.

I think in most cases it's simply a matter of my suggestion for `get_readable_fileobj`: Allow it to take arbitrary keyword arguments, and document that they are passed to `download_file`.  I'm less sure what to do in cases like `get_pkg_data_filename`.

**Comment by pllim** [comment]
These functions been around for a while and are widely used outside core lib, so we need to see if benefit of doing this outweighs the cost of breakage downstream. Might have to find a middle ground.

**Comment by embray** [comment]
It's more about regularizing the argument nomenclature.

There are two parts to this though: Allowing functions that use `download_file` internally to accept arguments to pass to `download_file` (this should not have any downstream impact).

More disruptive is trying to improve consistency in argument naming (esp. timeout vs remote_timeout).  But I think this can be done with minimal impact.

**Comment by davidmpaz** [comment]
Hi All,

I would like to participate here. My proposed line of work would be:

1.  Analyse where the function is used throughout the framework
2. Document where allowing parameters to the function `download_file` be used internally (no impact downstream)
3. Document where consistency in argument naming is needed (disruptive impact downstream)
4. Discuss how to proceed next
4.1 Possibly tackling point 2 without further hassle.
4.2 Open discussion for point 3 with more infos at hand

What do you think?
Regards,
David

**Comment by davidmpaz** [comment]
Hello,

here are my findings, there are not many usages as I initially thought. I have documented some things in order to get my self into context and since it would be a pity to discard all of that, I put them here.

Another thing regarding my proposals here, I come from a world bloated from "Objects" :) like it is in Java. So bear with me if you find something which is not a pythonic way of thinking or aligned with your current development practices.

## Getting in context

| Function                   | File                                     | Parameter Usage (client of the download function)           |
|:---------------------------|:-----------------------------------------|:------------------------------------------------------------|
| get_icrs_coordinates       | astropy/coordinates/name_resolve.py      | cache                                                       |
| _get_kernel                | astropy/coordinates/solar_system.py      |                                                             |
 | _File.__init__             | astropy/io/fits/file.py                  | cache                                                       |
 | download_files_in_parallel | astropy/utils/data.py                    | cache, show_progress, pkgname, timeout, sources             |
 | export_download_cache      | astropy/utils/data.py                    | pkgname                                                     |
 | get_readable_fileobj       | astropy/utils/data.py                    | cache, show_progress, remote_timeout, sources, http_headers |
 | get_pkg_data_filename      | astropy/utils/data.py                    | data_name, show_progress, remote_timeout                    |
| download_file              | astropy/utils/iers/iers.py               | *args, **kwargs                                             |
| download_image_save_cutout | docs/nddata/examples/cutout2d_tofits.py  | url                                                         |


### get_icrs_coordinates

From the `get_icrs_coordinates` function, it is only passed the `cache` parameter flag to the `download_file` function. Other parameters are provided hard coded or from calculated variables inside the function.

### _get_kernel

All parameters are hardcoded in call. Nothing is reused from `_get_kernel` function parameters

### _File.__init__

Here we can handle everything the same as for `get_icrs_coordinates`

### download_files_in_parallel

Parameters re-packed in a dictionary, kwargs is used as is, no ** used. Parameters are unpacked later when passing them to `download_file` function

### export_download_cache

Only `pkgname` is used, other parameters are hardcoded in call. Noticeable is that `pkgname` parameter is also used to get urls to download

### get_readable_fileobj

All parameter are passed as is from `get_readable_fileobj` to `download_file`, only `remote_timeout` is different since it is passed as `timeout`.

### get_pkg_data_filename

Parameters are all used to pass them to `download_file`. `remote_timout` is used instead `timeout`

### download_file

Overloaded function passing all parameters as ist to original `download_function`, adding only its own `remote_timeout` to configuration and headers.

### download_image_save_cutout

Just download the url given as parameter

## Ideas

If we follow the suggestions from our conversation here, I think a viable solution could be to pass some kind of `**download_kwarg` parameter in order to let it clear that everything in that dictionary will go directly to the `download_file` function or at least will be used to serve that purpose. this should do the job for most of the usages as already noted before in this conversation.

Most usage comes from utils data module: `astropy/utils/data.py`, So I took a closer look to it. Worth to notice that usually in software "utils" are the place where we put code which does fit somewhere else. I tend always to find a place for it.

From conversation, I read that changes will probably come in action in a new major release of the package. This means to me there is place for more freedom to include changes, or I understand wrong here?

I think adding many parameters to functions is counterproductive, specially if they are flags for configuration. In those cases my first impulse is to apply some Clean Code practices and refactor into Objects which encapsulates those parameters.

Regarding caching, I would assume always the use of the cached version if there is one, only allow to update the cached values on demand in case the callee wants to (force a refresh) do it.

There is a `Conf` class. Class is declared and instantiated right there in the module, instance is also imported later by other modules. I think we can exploit more this `Conf`. By extracting many of the function call parameters into this conf object we can simplify function signatures.

## Possible Solutions

With all this in place my proposals would be:

1. Usage of the **kwargs mechanism to further pass parameters to function in a more concise way and make references in documentation.

Or:

1. Encapsulate as much as possible flags parameters in the `Conf` class
2. Create a "Downloader" class which get a `Conf` instance injected to control its behaviour
3. Keep all functions signatures in `astropy/utils/data.py` module the same, with some deprecation mark, with docs and/or decorators to provide backward compatibility and let users know things will change in future
4. Inside deprecated functions use class instances from point 1. and 2.

Or: 

Any mix/combination from above.

Sorry for the long text. I would love to hear other ideas or feedback about everything exposed here.

Regards,
David

**Comment by pllim** [comment]
Thank you for the detailed analysis! Here are my personal comments but then again I have been using these for a long time, so I am a hesitant to change stuff unless it is absolutely necessary or in the situation where long term benefit outweighs the cost of near term pain. Keep in mind that changing this API might break quite a few things downstream.

> remote_timeout vs timeout

For me, I think it makes sense to name it only timeout in `download_data`. That function is all about downloading (remote) data, so having the keyword as `remote_timeout` is redundant.

> This means to me there is place for more freedom to include changes, or I understand wrong here?

More freedom, yes. But complete freedom, probably not. See my reasoning above.

> Conf

I have a love-hate relationship with this one. It exists because of https://docs.astropy.org/en/latest/config/index.html . It is nice if you want to set a bunch of stuff for a system or a group of user. But it is also dangerous because that setting is hidden and you will find it surprising if you are not familiar with the config or if someone else set it for you silently. That is why we provide also the keyword to overwrite if you don't care for some config that is set somewhere and you know what you want to set it to for that one call. So, delegating to `Conf` and only using that is probably a non-starter.

> OOP

`data.py` is a low-level module, so OOP might seem to be overkill to me but I could be convinced otherwise.

> Next step

Thanks again for some really valuable feedback, @davidmpaz . I would bring this up in the next dev telecon and see what other maintainers think. 🙇‍♀️

**Comment by davidmpaz** [comment]
One of the ideas was to brainstorming :) I am glad we are doing it now. I will love to implement whatever it is discussed at the end.

**Comment by nstarman** [comment]
Just throwing this into the discussion: https://docs.scipy.org/doc//scipy/reference/datasets.html#datasets-scipy-datasets
It's never bad to be similar to an upstream-adjacent library. 
We let ``pooch`` do all the heavy lifting and worrying about caches, etc. Lower maintener burden. Our funcs are just thin wrappers.

**Comment by hamogu** [comment]
We discussed this at the [dev telecon](https://docs.google.com/document/d/15JSFh3OMF9Iz6ov3q_xxGO_BL8hRnuse4IMUrqEIvcg/edit#heading=h.y1b7rstf5zlm). We agree that we don't want to break anything since users may rely on old code, but anyone is welcome to open a PR e.g. to use `**kwargs`. 

However, this is pretty low priority - the code works, it's used, it's not broken, it's mostly about making it look nicer. As such, this issue might well by open indefinitely.

**Comment by pllim** [comment]
@nstarman , I had to do this to avoid some SHA error that I don't care about so I am not a big fan of scipy datasets approach:

* #14214

**Comment by alexandrecesarba** [comment]
Hello Astropy community,

I've been reviewing this issue regarding the rework of argument handling in astropy.utils.data functions that utilize download_file. I believe that addressing this issue can lead to a more consistent and flexible handling of arguments, ultimately benefiting the users and maintainers alike.

I'm planning to start working on a PR for this issue. Before diving deep, I wanted to reach out and gather any additional insights or suggestions that might not have been covered in the previous discussions. Specifically:

1. Are there any particular pitfalls or challenges that I should be aware of based on past experiences?
2. Has anyone started any preliminary work on this that I should be aware of to avoid duplicating efforts?
3. Would it be beneficial to have periodic check-ins or updates on the progress to ensure alignment with the community's vision?

I'm eager to contribute and ensure that the solution aligns well with Astropy's standards and the community's expectations. Any feedback or guidance would be greatly appreciated.

Thank you for your time and looking forward to collaborating!

Regards,
Alexandre

**Comment by pllim** [comment]
Thanks for the ping and sorry this slipped off my plate.

Coming back to this again... I think we should just leave the API alone for two reasons:

1. `utils` is really meant for internal use in the core library. If other people find the stuff useful, so be it, but downstream usage is not our main audience. Therefore, the API does not need to win any beauty contest.
2. `download_file` has existed for so long and so widely used in the ecosystem that any API change (even though it would look prettier) would be very disruptive.

Therefore, I now think that the cost of such an effort would outweigh any benefits.
