### ISSUE TITLE
A documentation update required in fits_ccddata_reader

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#10978]
### Description

The [``fits_ccddata_reader``](https://docs.astropy.org/en/stable/api/astropy.nddata.fits_ccddata_reader.html#astropy.nddata.fits_ccddata_reader) documentation says the argument ``hdu`` can only accept ``int``, but as it uses the following lines in the source code, it can actually accept, e.g., string (``EXTNAME``) or tuple of string and integer (``(EXTNAME, EXTVER)``)
```python 
    with fits.open(filename, **kwd) as hdus:
        hdr = hdus[hdu].header
```
I confirmed the following codes work, for example:
```python
CCDData.read("test.fits", hdu=('a', 2), unit='adu')
CCDData.read("test.fits", hdu=('a', None), unit='adu')
```

By the way, I think it is a bit strange that this reader has ``hdu`` while its name (those in ``*args``) is ``ext`` in, e.g., [``getdata``](https://docs.astropy.org/en/stable/io/fits/api/files.html#astropy.io.fits.getdata) 😅

### System Details

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 23 2020, 17:31:31)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.19.2
astropy 4.0.2
Scipy 1.5.2
Matplotlib 3.2.2

**Comment by dhomeier** [comment]
> By the way, I think it is a bit strange that this reader has `hdu` while its name (those in `*args`) is `ext` in, e.g., [`getdata`](https://docs.astropy.org/en/stable/io/fits/api/files.html#astropy.io.fits.getdata) 😅

I'd think it is rather the terminology in `getdata` here that might be a bit misleading. Technically, a Header Data Unit can refer to either the Primary (0) or any of the Extension HDUs, but `getdata` obviously accepts both. Strictly speaking, the reference to a "primary extension" in the `fits_ccddata_reader` docstring is thus wrong.

At the core you are obviously right, any value of `hdu` would be processed that is accepted as `key` argument to `HDUList.index_of()`
https://github.com/astropy/astropy/blob/ab1a1d3c776ff636b844be6799c1c9b91b32a21f/astropy/io/fits/hdu/hdulist.py#L683-L686

**Comment by homeboy445** [comment]
Hi there, I am new to this organization and would like to tackle this task. I would very much like to know what changes should be made as I'm a little confused with the same. Thanks a lot!

**Comment by dhomeier** [comment]
Thanks a lot for addressing this issue @homeboy445 ! If you are not familiar with the general process yet, you can have a look at the guide for [making contributions via pull requests](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md#how-to-contribute-best-practices).

There are several points to be tackled here:

- [ ] The immediate issue at hand is that
https://github.com/astropy/astropy/blob/0ca2203877f70659b432b0cf0b75777979b879d3/astropy/nddata/ccddata.py#L538-L541
just mentions an integer as possible input for `hdu`, but is simply using it as index to an `HDUList`; thus it should accepted anything documented in
https://github.com/astropy/astropy/blob/ab1a1d3c776ff636b844be6799c1c9b91b32a21f/astropy/io/fits/hdu/hdulist.py#L682-L683
and the `fits_ccddata_reader` docstring should basically mirror that.

- [ ] Another point of confusion arose from sloppy or imprecise references of the individual elements of `HDULists`. 
The FITS standard (sections 3.1-3.4) defines these as
> 3.1. Overall file structure
A FITS file shall be composed of the following FITS structures, in the order listed:
– Primary header and data unit (HDU).
– ConformingExtensions(optional).
– Other special records (optional, restricted).

> 3.2. Individual FITS Structures
The primary HDU and every extension HDU shall consist of one or more 2880-byte header blocks immediately followed by an optional sequence of associated 2880-byte data blocks

So the term for any generic element of a `HDUList` should be "Header Data Unit" or `HDU`, e.g. the corresponding part for `fits_ccddata_reader` above should read something like
```
        and no data in the primary HDU, it will search for the first
        extension HDU with data...
```
Beginning with the `getdata` doc at
https://github.com/astropy/astropy/blob/0ca2203877f70659b432b0cf0b75777979b879d3/astropy/io/fits/convenience.py#L132-L134
HDU instances are referred to as `ext`, `extension` or just `header` (even if the data part is obviously concerned) throughout the entire file, so that whole chunk of code could need a good review.
 
- [ ] A nice (but optional) enhancement would be to better clarify what we mean by `hdu` by using ReST definitions in the way it is done in
https://github.com/astropy/astropy/blob/0ca2203877f70659b432b0cf0b75777979b879d3/astropy/io/fits/connect.py#L139-L146

Unfortunately it seems we have no visible class to refer for a generic HDU, and don't always want to repeat the full list, so perhaps this needs to be reserved for mentions of a specific type like `PrimaryHDU` or `BinTableHDU`.
But at least e.g. that same bit of `fits_ccddata_reader` doc might be changed to
```
        and no data in the :class:`~astropy.io.fits.hdu.PrimaryHDU`, it will search for the first
        :class:`~astropy.io.fits.hdu.base.ExtensionHDU` with data...
```
Maybe @saimn has some thoughts about this...

**Comment by saimn** [comment]
I agree we should use "HDU" instead of "extension", but I think we just use "HDU" instead of more specific references (`~astropy.io.fits.hdu.PrimaryHDU` etc.), and then use the Numpydoc xref feature ( #11118) to link HDU to something useful (a glossary entry ?).
Other than that, I think this issue should remain focused on nddata, and another point is to check if there are unit tests with `CCDData.read` and where `hdu` is not an integer.

**Comment by homeboy445** [comment]
Thanks a lot for elaborating on this issue, but I'm still somewhat confused as to what exactly should be done here. Thanks again!

**Comment by pllim** [comment]
@homeboy445 , if you are still confused, I recommend you pick a different issue to work on. Thank you for your interest. Much appreciated!

**Comment by pllim** [comment]
Note to maintainers: I removed "good first issue" label for this one. One does not simply label anything to do with FITS as "good first issue." 😉

**Comment by dhomeier** [comment]
> Note to maintainers: I removed "good first issue" label for this one. One does not simply label anything to do with FITS as "good first issue." 😉

I was a bit worried about that. ;-)
But I might be to blame in part as well for pulling in additional aspects to this issue.

But if you are still willing to give it a shot @homeboy445 , I recommend that once you have set up your local branch for preparing a pull request, you simply start with the task under

1. update the description of `hdu` in `ccddata.py` to the types listed in the `hdulist.py` docstring.

You can then open this as a draft pull request so we can review it, and if necessary, suggest corrections.

2. The documentation in `convenience.py` can also be postponed to a second PR. In principle this is also straightforward replacement of mentions of "extensions" etc., but unless you have a clear concept of what an HDU is and where it is used, this is probably really not a good first (or literally second ;-) issue.

**Comment by homeboy445** [comment]
I really am confused still and I think since I am a new contributor I should tackle some easy tasks so as to get some idea about the codebase and maybe after that I can try to solve this. P.S: Thanks a lot for helping!

**Comment by mzhengxi** [comment]
Hello! I would pick up this issue as my first contribution for the SciPy 2021 sprints
