### ISSUE TITLE
Saving a VOTable with an array of fixed size to a file only saves first element

### ISSUE THREAD

**Issue by druzmieres** [astropy/astropy#11087]
### Description

I am trying to add metadata to a VOTable that I'm creating. This metadata corresponds to a tuple of known length. The data seems to be ok when inserted into the table but, when I save the table to a file, only the first element is saved.

### Expected behavior

What I expect to see is the entire tuple saved in the file. The tuple is `(1.0, 2.0, 3.0)`, what I see when I print `params` is  `[<PARAM ID="sampling" arraysize="3" datatype="double" name="sampling" value="(1.0, 2.0, 3.0)"/>]`

### Actual behavior

Only the first element is saved in the file. When I open it, I see: `PARAM` section I see: `<PARAM ID="sampling" arraysize="3" datatype="double" name="sampling" value="1"/>`

### Steps to Reproduce

What I'm doing to create the table and add the metadata is the following:
```
# Create a new VOTable file
votable = VOTableFile()
# Add a resource
resource = Resource(); votable.resources.append(resource)
# Add a table for the spectra (and add the sampling as metadata)
spectra_table = Table(votable); resource.tables.append(spectra_table)
# Add sampling as param
sampling = tuple([1.0, 2.0, 3.0])
# I'm using a list because, later, I could have more than one param
params = [Param(votable, name='sampling', datatype='double', arraysize='3', value=sampling)]
spectra_table.params.extend(params)
```

When I print `params`, I see `[<PARAM ID="sampling" arraysize="3" datatype="double" name="sampling" value="(1.0, 2.0, 3.0)"/>]` which seems to be ok. However, when I save this to a file: 
```
votable.to_xml('table_with_params.xml')
```
In the `PARAM` section I see: `<PARAM ID="sampling" arraysize="3" datatype="double" name="sampling" value="1"/>`.

I tried sampling being a tuple, list and numpy array, but they all lead to the same result. If I use `*` instead of the fixed known length, the entire array is saved.

### System Details

Linux-5.4.0-52-generic-x86_64-with-glibc2.29
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
Numpy 1.18.2
astropy 4.3.dev268+g883a7c4f5
Scipy 1.4.1
Matplotlib 3.2.1

**Comment by pllim** [comment]
Did you see any warnings? If you manually modify the XML file written with the desired value and then run `volint` on it, does it emit any errors or warnings?

cc @tomdonaldson

**Comment by druzmieres** [comment]
Hi @pllim,

I got no warnings when running the code.

I changed the value to `<PARAM ID="sampling" arraysize="3" datatype="double" name="sampling" value="1.0 2.0 3.0"/>`. And run `volint`:

```
Validation report for table_with_params.xml

4: W41: An XML namespace is specified, but is incorrect.  Expected
  'http://www.ivoa.net/xml/VOTable/v1.3', got
  'http://www.ivoa.net/xml/VOTable/v1.4'
<VOTABLE version="1.4" xmlns="http://www.ivoa.net/xml/VOTable/v1.4"
```

**Comment by pllim** [comment]
Thanks for checking! The warning seems unrelated. I was thinking that if your expected output is somehow against the specs, the validator would complain, so perhaps this is a bug. Let's wait and see what @tomdonaldson says. Please note that this week is USA Thanksgiving week, so response might be delayed. Thank you for your patience!

**Comment by tomdonaldson** [comment]
@druzmieres thanks very much for submitting this issue.  It is definitely a bug that for a `PARAM` with fixed `arraysize` only the first element in the array is being written to the `value` in the xml.  In your example, I would expect the xml for the `PARAM` to be written as:
`<PARAM ID="sampling" arraysize="3" datatype="double" name="sampling" value="1 2 3"/>`

Looking quickly at the code, it's clear why this is happening, and why it only happens for fixed `arraysize`.  The `output()` method of `NumericArray` uses `zip()` to pairwise combine the array values with the mask values for writing: https://github.com/astropy/astropy/blob/87df980318eac43850a3add1e5f32286dad9d723/astropy/io/votable/converters.py#L637 The problem is that the mask is only a single value in this case, and `zip()` doesn't expand that to match the value array shape, instead only yielding the one value.  

`VarArray` uses `np.broadcast()` instead, which does expand the single mask value, which is why the writing works correctly for `arraysize="*"`.  https://github.com/astropy/astropy/blob/87df980318eac43850a3add1e5f32286dad9d723/astropy/io/votable/converters.py#L500

I can think of a couple patches that will definitely fix the behavior, but it's more difficult to prove that it won't break something else.  There doesn't seem to be any test coverage for this case, and the `NumericArray` converter is used for in non`PARAM` cases that actually make use of the mask.  One simple possibility would be to replace that `zip(value.flat, mask.flat)` call with `np.broadcast(value.flat, mask.flat)`, but again, I'm not yet sure that would work for all the non`PARAM` cases.

The namespace warning from `volint` is also correct, and it is noticing a known bug in the writer (#9773)

**Comment by pllim** [comment]
The culprit for this particular bug is here (assuming one `False` mask even if input is iterable):

https://github.com/astropy/astropy/blob/ec983207505a2c1dcaefdb3b32fe0d9f30a2b716/astropy/io/votable/tree.py#L1624

But then again, does it really make sense for the `NumericArray` converter to behave as such?

```python
>>> from astropy.io.votable.tree import Param
>>> # votable created as per original example above
>>> p = Param(votable, name='sampling', datatype='double', arraysize='3', value=(1., 2., 3.))
>>> c = p.converter
>>> c
<astropy.io.votable.converters.NumericArray at ...>
>>> c.output(p.value, False)
'1'
>>> c.output(p.value, [False])
'1'
>>> c.output(p.value, [False, False])
'1 2'
>>> c.output(p.value, [False, False, False])
'1 2 3'
>>> c.output(p.value, [False, False, True])
'1 2 NaN'
>>> c.output(p.value, [False, True])
'1 NaN'
```

Perhaps @tomdonaldson 's idea above to broadcast is the correct solution, but if you really want it to be a localized fix, then we can only patch up `Param.to_xml` to pass in something like `[False] * len(self._value)` if `self._value` is iterable but not string, which is not insignificant extra check for just this use case.

What do you think?

**Comment by druzmieres** [comment]
Hi, in which version of astropy is this patch included? I'd like to try it.

**Comment by pllim** [comment]
Hello. I don't think it is released yet, so you will have to use the dev version for now. Since #11157 was milestoned for 4.0.5, if there is an urgent need, we can try for a release soon; otherwise, it is more likely to happen when 4.3 comes out.
