### ISSUE TITLE
Suggest new method for SkyCoord:  spherical_offset_by()

### ISSUE THREAD

**Issue by janerigby** [astropy/astropy#11199]
### Description

I've been searching for a SkyCoord method, given a SkyCoord object sk, will calculate the position that is an offset away, for example, an offset of 10" N and 5" E.   It should use spherical math on general principles, even though this example would be safe to use a small-angle approximation.

I believe what I'm asking for is the opposite of this SkyCoord method: sc.spherical_offsets_to.  

I believe it's currently possible to do this math using the method sk.directional_offset_by().  However, it's super-clunky (calling the method twice), and not  how an observer thinks, since it uses a position angle and a total distance as the input, rather than the offsets in RA, DEC.  Here's the wrapper function I wrote:

```
def offset_coords(sk, delta_RA=0, delta_DEC=0) :
    ''' From Astropy SkyCoords position sk, compute new coordinates after offsets (in arcsec).  Positive offsets move N and E 
    This should be a method in astropy SkyCoord, but I can't find it.'''
    # Input coords should be in Astropy format, for example sk = SkyCoord(RA, DEC, unit='deg') 
    newsk = sk.directional_offset_by(0. *u.deg, delta_DEC * u.arcsec).directional_offset_by(90. *u.deg, delta_RA * u.arcsec)
    return(newsk)
```

I was shocked that AstroPy doesn't have a method to do something so simple as "Go 10 arcsec S, go 15 arcsec W.")  Am I missing something?  I'm still learning AstroPy, so it's totally possible that I am just not aware of an existing solution.  If so please tell me!  But I do suspect this may be a case where because AstroPy has over-generalized (to all kinds of coordinate systems), it's lacking the tool the astronomer actually wants at the telescope, or while staring at an image.

**Comment by pllim** [comment]
@adrn or @astrojuanlu , are you able to advise?

**Comment by adrn** [comment]
Thanks @janerigby for raising this! It sounds like it would be useful to either add this functionality to `directional_offset_by()`, or add a new method as suggested. On the plus side, I think this would improve discoverability for something that does sound like it would be useful for observational users. On the negative, we are always trying to balance "feature creep." 

@janerigby : Another way to do what you want is to use the `SkyOffsetFrame` class like:

```python
c = coord.SkyCoord(ra=152.234*u.deg,
                   dec=-17.4329*u.deg)
delta_RA = 17.3 * u.arcsec
delta_Dec = 3.5 * u.arcsec

coord.SkyOffsetFrame(delta_RA, delta_Dec, 
                     origin=c).transform_to(coord.ICRS())
```
Would this solution be good enough for you if we had documented it better, or added an example demonstrating this? Fine to say no, just curious!

**Comment by mhvk** [comment]
Darn, I was so willing to say too much feature creep, but then the case is good... one would like to have the reverse of `spherical_offsets_to`...

p.s. In @adrn's example one can even do `.transform_to(c)`. I'm wondering whether we should allow empty origin `SkyOffsetFrame` and allow those to be added/subtracted from `SkyCoord`... Obviously, the same logic would allow one to subtract two `SkyCoord` and produce a `SkyOffsetFrame`. Very liable to misunderstandings...

**Comment by taldcroft** [comment]
Personally I vote for a short and sweet convenience method `spherical_offsets_by` which is roughly the one-liner that @adrn wrote. That particular incantation using `SkyOffsetFrame` is not going to be discoverable by any means but the narrative docs, and even when reading it I had to think for a second.

Adding this "feature" is not really creep in my mind because it does not increase code complexity or maintenance burden. It is just syntactic sugar to do something very common.

**Comment by dhomeier** [comment]
+1 that it is really not that evident from the docs how to implement this with `SkyOffsetFrame`.

An additional comment: in the prior discussion it was brought up that no such method might be existing since there is no obvious unique implementation, the shifts not being commutative in RA and Dec offsets.
Maybe with an observer's view, again, it is clear that `coord.SkyOffsetFrame(delta_RA, delta_Dec)` is different from `coord.SkyOffsetFrame(delta_Dec, delta_RA)` (and of course for typical shifts of some arcsec or arcmin the differences are insignificant), but at least the convention would have to be clearly documented. At least for `SkyOffsetFrame` I would not have automatically assumed that it is applying the declination offset first:
```python
>>> c.directional_offset_by(0*u.deg, delta_Dec).directional_offset_by(90*u.deg, delta_RA)
<SkyCoord (ICRS): (ra, dec) in deg
    (152.23903688, -17.43192771)>
>>> c.directional_offset_by(90*u.deg, delta_RA).directional_offset_by(0*u.deg, delta_Dec)
<SkyCoord (ICRS): (ra, dec) in deg
    (152.23903691, -17.43192771)>
>>> coord.SkyOffsetFrame(delta_RA, delta_Dec, origin=c).transform_to(coord.ICRS())
<ICRS Coordinate: (ra, dec) in deg
    (152.23903688, -17.43192771)>
```

**Comment by janerigby** [comment]
I would prefer not to go the `SkyOffsetFrame` route.  Agreed with @taldcroft that it's not intuitive.  

To me, the existence of `directional_offset_by` says that such a method is needed.  It's just that its inputs are not how an observer would specify things.  

Is there a preference for a new convenience method `spherical_offsets_by`,  versus expanding the possible arguments to `directional_offset_by`?

**Comment by mhvk** [comment]
@eteq, @adrn and I saw this issue again, and think the conclusion basically is that this is a good idea. It seemed to us a new `spherical_offsets_by` methods is the way to go. This should be fairly easy, so labelling accordingly.
