### ISSUE TITLE
TST: keplerscience.arc.nasa.gov is down

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11328]
Link check reported that keplerscience.arc.nasa.gov is broken with `ERR_CONNECTION_TIMED_OUT`. Not sure if this is transient or not. If not, needs to be replaced with something else or removed altogether.

**Comment by barentsen** [comment]
NASA managers demanded we'd take down keplerscience.arc.nasa.gov at the end of Kepler, so this error is permanent.

It looks like the offending url only appears in this sentence of `docs/timeseries/index.rst`:
```
For more information about the Kepler FITS format, see the `Kepler Data Validation Document
 <https://exoplanetarchive.ipac.caltech.edu/docs/KeplerDV.html>`_ and the Kepler Science Center 
`Light Curve Files <https://keplerscience.arc.nasa.gov/PyKEprimerLCs.shtml>`_ documentation.
```

We can edit this sentence to point to Section 2.3.1 ("Light Curve Files") in the [Kepler Archive Manual](https://archive.stsci.edu/kepler/manuals/archive_manual.pdf) at MAST, which is the canonical documentation on this topic (albeit a PDF rather than a web page).

Shall I go ahead and open a PR?

**Comment by pllim** [comment]
Yes, please. Thanks!

**Comment by pllim** [comment]
From my experience `archive.stsci.edu` might block link check but that is a different story and we can just exclude it from check if that happens.

**Comment by barentsen** [comment]
:+1:  I plan to have this done in the next day.
