### ISSUE TITLE
BUG: printing Angle, Latitude, Longitude with a NaN in degrees

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11473]
### Description

Though nan degrees is a valid initializer, it cannot be printed

```
print(coord.Longitude(np.nan * u.deg))
```

### Expected behavior

The same as nan radians, but in degrees.

```
print(coord.Longitude(np.nan * u.rad))
```

### Actual behavior

degrees, unlike radians, appears to call sexagesimal_to_string which has ``int(values[1])``, but nan cannot be converted to an integer, so it fails.

```
~/local/astropy/astropy/coordinates/angle_utilities.py in sexagesimal_to_string(values, precision, pad, sep, fields)
    637     literal = ''.join(literal)
    638     return literal.format(np.copysign(values[0], sign),
--> 639                           int(values[1]), values[2],
    640                           sep=sep, pad=pad,
    641                           last_value=last_value)

ValueError: cannot convert float NaN to integer
```

### Steps to Reproduce

```
import astropy.units as u
import astropy.coordinates as coord
print(coord.Longitude(np.nan * u.deg))
```

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.18.4
astropy 4.3.dev721+g3646d9e6e.d20210403
Scipy 1.4.1
Matplotlib 3.4.1

**Comment by mhvk** [comment]
Confirmed. Note that the bug is a bit higher up: the same holds for `Angle`, and of course the real problem is that it tries to turn it into a hexagesimal string by default. I think it would need a small check whether the value is finite at https://github.com/astropy/astropy/blob/21f367a48b862f077bf00871dd7d9095c38eac73/astropy/coordinates/angles.py#L351-L357

**Comment by mhvk** [comment]
To clarify since in #11491 there seems to be confusion, the issue here is not just that `nan` raises an error, but also that the output should make clear that the value is actually `nan`, i.e., it should be something like what happens for Quantity
```
In [3]: u.Quantity(np.nan, u.deg)
Out[3]: <Quantity nan deg>
```
Of course, a mix of valid and nan values should give sensible output as well.

**Comment by JasonS09** [comment]
Hello. Is someone already working in this issue? If not, I'd like to contribute. I ask because the PR doesn't seem to have recent activity.

**Comment by nstarman** [comment]
@mhvk, would you agree that #11491 has stalled out?

**Comment by eteq** [comment]
@nstarman - I agree #11491 looks like it's probably stalled.  @JasonS09 - if you would like to take the work already in #11491 and carry it forward, you are welcome to do so, by just adding commits to the end of that branch and then opening a separate PR.  Or if you'd rather start afresh that's fine too!

**Comment by mhvk** [comment]
Indeed, seems stalled: do check the comments in that PR, though! We should not be replacing `nan` with 0.

**Comment by JasonS09** [comment]
Sure. I'll take this issue then!
