### ISSUE TITLE
Many Table formats deserialize None to a string

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11709]
### Description

When a column if full of `None`, many formats will deserialize the column to a string instead of None.

These are the problematic formats: {'aastex',  'ascii',  'ascii.aastex',  'ascii.basic',  'ascii.commented_header',  'ascii.csv',  'ascii.fast_basic',  'ascii.fast_commented_header',  'ascii.fast_csv',  'ascii.fast_no_header',  'ascii.fast_rdb',  'ascii.fast_tab',  'ascii.fixed_width',  'ascii.fixed_width_no_header',  'ascii.fixed_width_two_line',  'ascii.html',  'ascii.ipac',  'ascii.latex',  'ascii.no_header',  'ascii.rdb',  'ascii.rst',  'ascii.tab',  'csv',  'html',  'ipac',  'latex',  'rdb',  'votable'}

### Expected behavior

Table/Column correctly roundtrips the data type.

### Actual behavior

`None` becomes a string.

### Steps to Reproduce

Here is an illustrative example
```python
from astropy import table

t = table.Table(dict(a=[0], b=[None]))
print(t["b"][0], type(t["b"][0]))

t.write("temp.csv", format="ascii.fixed_width", overwrite=True)
t2 = table.Table.read("temp.csv", format="ascii.fixed_width")
print(t2["b"][0], type(t2["b"][0]))
```
None <class 'NoneType'>
None <class 'numpy.str_'>

And this will produce the full list of problematic formats
```python
bad_formats = set()
table_formats = set(get_formats(table.Table, "Write")["Format"])
# these are problematic for other reasons
table_formats -= {"pandas.html", "fits", "pandas.csv", "ascii.qdp", "asdf", "jsviewer", "pandas.json", "hdf5"}

t = table.Table(dict(a=[0], b=[None]))

for fmt in table_formats:
    t.write("temp.csv", format=fmt, overwrite=True)
    t2 = table.Table.read("temp.csv", format=fmt)
    if t2[t2.colnames[-1]][0] is not None:
        bad_formats.add(fmt)

bad_formats
```
{'aastex',  'ascii',  'ascii.aastex',  'ascii.basic',  'ascii.commented_header',  'ascii.csv',  'ascii.fast_basic',  'ascii.fast_commented_header',  'ascii.fast_csv',  'ascii.fast_no_header',  'ascii.fast_rdb',  'ascii.fast_tab',  'ascii.fixed_width',  'ascii.fixed_width_no_header',  'ascii.fixed_width_two_line',  'ascii.html',  'ascii.ipac',  'ascii.latex',  'ascii.no_header',  'ascii.rdb',  'ascii.rst',  'ascii.tab',  'csv',  'html',  'ipac',  'latex',  'rdb',  'votable'}

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.18.4
astropy 4.3.dev1486+gddc6fb76f.d20210505
Scipy 1.4.1
Matplotlib 3.4.1

**Comment by hamogu** [comment]
All those the formats above are ascii formats. In ASCII, there is no way to distinguish between the string "None" and the value `None`, so there is no way to round-trip that case, unless you add special meta data that encodes the datatype (like `ecsv`). It would also be wrong to convert `"None"` to `None`, because the string "None" might actually be what the table should be [1]. The ASCII reading makes pragmatic choices about what you are most likely to want. If all values can be converted to int, the output column will be a of type int, even in the numbers you wrote to that table may have been floats (assuming you formatted them to look like ints) or strings. However, there are ways to specify a specific format for a column by running a custom converter.

So, the real question is not why ASCII table with the value "None" ins them deserialize to a string (it's an ASCII table with a string in it after, all, that's what you put in). Instead, you might ask: If an ASCII table cannot properly represent `None` and needs to convert it to something else (a string in this case), why does it no issue a warning or an exception on writing?

Again, it's a pragmatic choice: Write useful tables that in most cases "just work" without reading the manual and that "just read" as many ASCII tables in the wild, most of them not written in Python. If you are looking for a faithful storage of Python objects, ASCII table is not for you.
 
So, I'd like to ask: Do you have a specific use case that causes this issue?


[1] A similar situation might arise in this example:
```
Table({'a':[1,2], 'b': ['2', '3']}).write(sys.stdout, format='ascii')
```
which gives"
```
a b
1 2
2 3
```
So, when you read it back in, you'll get all numbers. But what if I WANT column 'b' be all strings? Write your own custom formatter, or use a table format that saves the datatype separately (e.g. fits).

**Comment by hamogu** [comment]
https://docs.astropy.org/en/latest/io/ascii/read.html#converters

**Comment by nstarman** [comment]
Thanks @hamogu for the detailed explanation.
The method-of-discovery /  motivating reason for this issue is #11559 where the name of a cosmology instance can be a string or None. In this case it is reasonable that ``"None"`` -> ``None`` (and I implemented that case when I raised this issue), but it struck me as odd that a python built-in couldn't be round-tripped. Reading your explanation, it makes sense that a column with a mixture of strings and None cannot be effectively resolved without a custom formatter, but perhaps a reasonable addition to the ascii converters would be recognizing a column of ALL ``None`` (or any python built-in like ``Ellipsis``). It's less useful for #11559, but it would make sense for tables in general.

**Comment by hamogu** [comment]
ASCII tables don't have to be written by Python. What about Java build-ins? Or R? Or Ruby? Or anything that TOPCAT might do? I don't believe that a Python-centric approach for special-casing on read is the right way to go. On the other hand, I could be convinced that we should raise an error when someone tried to **write** a variable that is not a number or string. But than again, Python is strong on duck-typing, so it it represents itself as a string, I should probably treat it like a string and write it.
