### ISSUE TITLE
DOC: Unpin max version of Sphinx when Sphinx 4.0.2 is out (and Jinja2)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11725]
**Update:** If you want to build docs in Python 3.10 or newer, see the pins in  #13587 .

Revert #11724 when sphinx-doc/sphinx#9210 is resolved. @saimn tracked it down to sphinx-doc/sphinx#8935 .

https://github.com/astropy/astropy/blob/642d8aea136d274a82928a8735cd25d6905116ed/setup.cfg#L84-L85

Also revert #12988 .

https://github.com/astropy/astropy/blob/f6569ceaeb81afef80d5a6a0a579698f1c27c6cd/setup.cfg#L103

**Comment by pllim** [comment]
I have been following sphinx-doc/sphinx#9214 . I think it is happening by the end of the week.

**Comment by WilliamJamieson** [comment]
Jinja2 pin is related to sphinx-doc/sphinx#10291

**Comment by eerovaher** [comment]
sphinx-doc/sphinx@7318d1dfd4ba39d9aa74f718bb02fba2ded9648f introduced code to `sphinx` 3.5 that ended up being incompatible with Python 3.10. The fix was provided by sphinx-doc/sphinx@8b2031c747e7c7e6b845ee2e3db47de617d33cc6, but is available only for `sphinx` >= 4.2. Installing `astropy[docs]` currently results in `sphinx` 3.5.4 being installed. If the maximum version of `sphinx` can't be unpinned soon then it should lowered even further to < 3.5.

**Comment by pllim** [comment]
@saimn was going to revisit this when he can but if you are in a rush, you can try use https://github.com/astropy/sphinx-automodapi/pull/150 in this repo and debug the remaining errors.

**Comment by eerovaher** [comment]
For the time being I have installed `sphinx` 3.4.3. This does not address the underlying problems, but at least it enables building `astropy` docs with Python 3.10.

**Comment by pllim** [comment]
@eerovaher , do you want to open a PR to lower the pin and also try to build RTD in Python 3.10 with it? Thanks!

https://github.com/astropy/astropy/blob/d15a689108dc5467c6223792ed34ca3aa829048b/.readthedocs.yml#L8
