### ISSUE TITLE
FITS table documentation uses non-standard FITS unit

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#11820]
### Description

While reading the documentation about fits table data, I noticed that there is a non-standard unit used: 
https://github.com/astropy/astropy/blame/main/docs/io/fits/usage/table.rst#L346
```python
   >>> col2 = fits.Column(name='counts', format='J', unit='DN', array=counts)
```

### Expected behavior

I'd expect that the documentation sticks to the standard.

### Actual behavior

`DN` is not a standard FITS unit, and even not directly supported by `astropy.units`. For example, the following does not work:
```
counts = [0., 1.]
col2 = fits.Column(name='counts', format='J', unit='DN', array=counts)
tbl = QTable([col2])
```

It may sound nitpicking, but we should not encourage people to use phantasy units. The name "counts" would suggest as unit `count`.

**Comment by pllim** [comment]
Looks like this example was imported from PyFITS over 10 years ago back in #102 (`docs/fits/users_guide/users_table.rst`).

**Comment by olebole** [comment]
Note that I tested it with astropy-4.2. In the development version, there is support for `DN`, introduced in #11591 (which gave the docs as one motivation for its inclusion). Therefore, maybe @jdavies-st could comment on that?
However, the FITS standard still does not allow it, right?

**Comment by saimn** [comment]
Indeed it's not a standard FITS unit, and I think (@mhvk could confirm) that it was added to the "generic" units but not the the FITS ones. (at least from what I can see `u.Unit('DN', format='fits')` raises an error)

**Comment by mhvk** [comment]
Agreed that if the unit is not supported, while we can support reading files that use it, we should not have it in our documentation.

**Comment by jdavies-st** [comment]
`DN` are not fantasy units, though it does seem that they exist in some parallel, mystical place, not of this earth.  Most HST, JWST and lots of Spitzer science data use `DN` to indicate `counts`.  That's why that unit was added to `astropy.units` (currently unreleased), so that the data from these telescopes could be read in easily as a `Quantity`.

Agree that the example in the docs should use a FITS standard unit.  Just because there's lots of existing (and soon-to-exist) data using DN, doesn't mean we should encourage its use.

What does it mean?  Some say Data Number.  Some say Dumb Number.  (h.t. @eslavich)

The history is that `astropy.io.fits` came via `pyfits` from STScI where DN was and is common usage for counts amongst the scientists and engineers, and all that pre-dated any standard for units from the FITS working group.  FITS had no standard for units of counts up through 2005, and only adopted `count`, `ct` or `adu` in 2008.

So yeah, let's change the documentation example.
