### ISSUE TITLE
Issues importing Time

### ISSUE THREAD

**Issue by hsergi** [astropy/astropy#11822]
A few days ago I had no issues ... Now (Python 3.9.5):

```
 File "/Users/srhildeb/Documents/GitHub/CGI_Perf_EXOSIMS/roman_cgi_dust_drm.py", line 16, in <module>
    from astropy.time import Time
  File "/Users/srhildeb/Documents/GitHub/astropy/astropy/time/__init__.py", line 19, in <module>
    from .formats import *  # noqa
  File "/Users/srhildeb/Documents/GitHub/astropy/astropy/time/formats.py", line 18, in <module>
    from . import _parse_times
ImportError: dynamic module does not define module export function (PyInit__parse_times)
```

**Comment by embray** [comment]
Hi @hsergi--it looks like from your installation path for astropy (`/Users/srhildeb/Documents/GitHub/`) it seems you're running an astropy installation out of the source code (e.g. with `pip install -e .`).  Is that correct?  Or are you doing something with `sys.path`/`PYTHONPATH` (discouraged)?

What Python version were you using before?

Chances are you need to re-build some extension modules.  You can go into the astropy sources and run `./setup.py build_ext --inplace` to re-build the extension modules in-place.

Since this is likely not a problem with astropy itself I am going to close this issue, but please feel free to follow up if you need further assistance.

**Comment by embray** [comment]
Update: It might also be easier if you re-run `python3.9 -m pip install -e .`

**Comment by hsergi** [comment]
Thank you, and very sorry for the belated reply. I appreciate it. I re-install astropy and it worked. Sorry I cannot be more specific. Since I am not an expert at all on these issues, I'll keep your response in mind if anyone else in my team comes up with the same issue. Thanks, again @embray.
