### ISSUE TITLE
AttributeError: '_HeaderCommentaryCards' object has no attribute 'keys'

### ISSUE THREAD

**Issue by vandalt** [astropy/astropy#11866]
### Description

The `_HeaderCommentaryCards` class is registered as a `Mapping` (via its parent `_CardAccessor`, [here](https://github.com/astropy/astropy/blob/main/astropy/io/fits/header.py#L2143)), but has no method `keys()`. Therefore, when using `isinstance` to check if a commentary card instance is a mapping before using a `Mapping` method such as `keys()` leads to an error. This seems true for `_CardAccessor` and its two subclasses (`_HeaderCommentaryCards` and `_HeaderComments`). I encountered this bug in a code that parses a header and treats each value differently depending on its type (in the [munch](https://github.com/Infinidat/munch) package, but I reproduced a simple example below).

Is this behaviour expected, in which case using `hasattr` or `try/except` instead of `isinstance` in the client code would fix the issue ?

If this is indeed a bug in astropy, I'd be happy to help, although I don't have prior experience with astropy development.

### Expected behavior

I think the expected behaviour would be that `_HeaderCommentaryCards` is treated as a Sequence, according to [this section](https://docs.astropy.org/en/stable/io/fits/usage/headers.html#comment-history-and-blank-keywords) of the documentation. It seems that having keys would be useful in the case of `_HeaderComments`, and for `_CardAccessor` itself I do not know. I am not very experienced with the inner workings of `astropy` so I might be wrong on the expected behaviour. But in any case it seems the object should either be recognized as a mapping and have keys, or be registered as a sequence if it does not have keys. (There is [a TODO comment](https://github.com/astropy/astropy/blob/main/astropy/io/fits/header.py#L2086) about dict/list methods for `CardAccessor` in the source code.)

### Actual behavior

`_HeaderCommentaryCards` (and all `_CardAccessor` instances) are regognized as mappings, but have no `keys()` method. This results in an error: `AttributeError: '_HeaderCommentaryCards' object has no attribute 'keys'`.

### Steps to Reproduce

1. Read or create a header with commentary cards.
2. Iterate trough keys (iterating items does not reproduce because it parses commentary card values one at a time).
3. Check if keys are instances of mapping.
4. If true, try to access access their `keys()` method.

```python
from typing import Mapping
from astropy.io import fits

hdr = fits.Header()

hdr['SOMEKEY'] = 'somevalue'  # regular value, no error

# NOTE: Commenting all of the commentary keys removes the issue
hdr['HISTORY'] = 'history1'
hdr['HISTORY'] = 'history2'
hdr[''] = 'blank1'
hdr[''] = 'blank2'
hdr['COMMENT'] = 'A comment'
hdr['COMMENT'] = 'Another comment'


for k in hdr.keys():
    if isinstance(hdr[k], Mapping):
        k.keys()
```

### System Details

Linux-5.12.11-300.fc34.x86_64-x86_64-with-glibc2.33
Python 3.9.5 (default, May 14 2021, 00:00:00)
[GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
Numpy 1.20.3
astropy 4.3.dev1751+gf911ec116
Scipy 1.7.0
Matplotlib 3.4.2

**Comment by saimn** [comment]
`_CardAccessor` doesn't inherit `Mapping` so it doesn't get the extra methods. Not sure why it is registered as a `Mapping` and `Sequence`, maybe @embray remembers ?

**Comment by embray** [comment]
Apparently I added these ABC registrations in 7c8e49350.  I have no recollection what was motivating that, and I don't see any follow-up commits that depend on this behavior.

As @saimn wrote, the class does not actually subclass `Mapping`, so it does not automatically get the `keys()` method.  I'm not really even sure it should be registered as `Mapping` since according to PEP-3119, `Mapping.__iter__` must be:

> Abstract method returning each key in the key set exactly once.

which is *not* what `_CardAccessor.__iter__` does (it iterates over the cards themselves).

So I think this ABC registration should just be removed.  It doesn't appear to be providing any value.

In your report you wrote:

> I encountered this bug in a code that parses a header and treats each value differently depending on its type

What do you mean by "type" in this case?  Perhaps there is a better way to support your use case (either an existing way, or one we need to add...).  ISTM what we really want is a way to check if something like `header['HISTORY']` contains multiple lines, or something like that?

**Comment by vandalt** [comment]
> What do you mean by "type" in this case? Perhaps there is a better way to support your use case (either an existing way, or one we need to add...). ISTM what we really want is a way to check if something like header['HISTORY'] contains multiple lines, or something like that?

Sorry, that was not very clear. I just meant that the code iterates over keys, checks the type of the corresponding value with `isinstance(hdr[key], Mapping)`, and then if the type is mapping it executes some code that requires a `keys()` method (similar to the example code above). In my specific use case just not detecting `header['HISTORY']` as a mapping would work because anything else is handled in a different way if it has no keys. Maybe another solution would be to use `hasattr` instead of `isinstance`, but given the PEP-3119 excerpt from above, it seems both should work.

I encountered this in the munch package ([here](https://github.com/Infinidat/munch/blob/develop/munch/__init__.py#L470), more specifically), but I suspect this way of checking before using `keys()` or other mapping methods/attributes is quite common (I might be wrong here, however).

**Comment by embray** [comment]
@vandalt I see, so if I understand correctly there was not a specific use case regarding FITS headers, but more a problem with generic code in munch that assumes that a `Mapping` instance has a `keys()` method?

My understanding of the `Mapping` ABC is that keys is *not* a required method.  That in order to be a `Mapping` it is sufficient to implement the 3 abstract methods `__getitem__`, `__len__`, and `__iter__`.  *If* these 3 methods are implemented, then you can also use `Mapping` as a mix-in class to automatically get the functionality of `.keys()`, `.values()`, etc. but that these extra methods are *not* required to satisfy the requirements of the ABC.

OTOH, there is no `Mapping.__subclasshook__` such that any class that implements those methods is *not* automatically considered a `Mapping` (since there are other requirements for `Mapping` that cannot be checked just by the presence of those methods).

I can't find anything either in the [`collections.abc`](https://docs.python.org/3/library/collections.abc.html) docs or [PEP 3119](https://www.python.org/dev/peps/pep-3119/) concerning whether or not the mixin methods provided by the `Mapping` ABC base class are *required* to satisfy the `Mapping` interface or not.  I'd be interested if anyone else has a resource on that...

(Nevertheless, theoretical questions aside, I think these `Mapping.register` in `astropy.io.fits` calls can just be removed.)

**Comment by embray** [comment]
I started a discussion about this hoping to get a bit more insight... https://discuss.python.org/t/mapping-abc-and-friends-are-the-mixin-methods-required-to-satisfy-the-interface/9499

**Comment by vandalt** [comment]
Thanks for the detailed feedback and for opening the discussion on discuss.python.org !

> I see, so if I understand correctly there was not a specific use case regarding FITS headers, but more a problem with generic code in munch that assumes that a Mapping instance has a keys() method?

At first I thought it was an issue with the FITS headers being registered as mappings without a `keys()` method, but the issue might indeed be the assumption in munch. It definitely seems more robust to use `hasattr` in munch, unless I'm missing something in their implementation. I just tried registering an empty class as a mapping and it worked, so `isinstance` returning `True` is definitely not a guarantee that an attribute is available from a practical point of view (in the sense that it is possible not to respect it, regardless of what the best-practice is). I'll open an issue with munch about that.

For the abstract vs. mixins, my understanding was that both are expected to be there, but that abstract methods always needed to be implemented while mixins have a default implementation if the class inherits from the ABC. I know very little about mixins, so I might be wrong. Here are two excerpts from [PEP 3119](https://www.python.org/dev/peps/pep-3119/) that give me the impression `keys()` was required:

>Another example would be someone who wants to define a generic function (PEP 3124) for any sequence that has an `append()` method. The `Sequence` ABC (see below) doesn't promise the `append()` method, while `MutableSequence` requires not only `append()` but also various other mutating methods.

This paragraph states that `append()` is required by `MutableSequence`, and `append()` is listed as a mixin for [`MutableSequence`](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes).

> The following invariants should hold for any mapping m:
> ```
> len(m.values()) == len(m.keys()) == len(m.items()) == len(m)
> [value for value in m.values()] == [m[key] for key in m.keys()]
> [item for item in m.items()] == [(key, m[key]) for key in m.keys()]
> ```

This snippet from the [Mappings section](https://www.python.org/dev/peps/pep-3119/#mappings) here says that the following should hold for any mapping. This seems to imply that `keys()` and `values()` are required.

**Comment by embray** [comment]
@vandalt I believe your understanding is correct, and it tracks with what I wrote here: https://discuss.python.org/t/mapping-abc-and-friends-are-the-mixin-methods-required-to-satisfy-the-interface/9499/3?u=embray

I just wish this were made more clear in the documentation.

I think I will just remove the `Mapping`.register calls.  I don't think they're providing any necessary value.
