### ISSUE TITLE
Consider allowing a numpy dtype as a value for io.ascii converters

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#11896]
### Description

As mentioned here https://github.com/astropy/astropy/pull/11892#pullrequestreview-693349877, one reasonable and small-footprint idea for improving the io.ascii.read `converters` API is to allow specifying a numpy dtype directly.

In other words (quoting @mhvk):
```
if not callable(converters): 
    converters = [convert_numpy(converters)]
```
This is syntactic sugar but will make the interface substantially easier to use. I'm very much in favor of this and have had the same thought many times but just never gotten around to doing it. Along with this I would make doc examples all use this formalism and put the original syntax as effectively a technical footnote.

### Additional context

#11892

**Comment by taldcroft** [comment]
cc: @hamogu @mhvk @bsipocz

**Comment by hamogu** [comment]
Sounds useful. And if the docs then say "This is how you set the dtype" then it would probably also solve @bsipocz use case.

**Comment by hamogu** [comment]
That leaves the question though if it would be useful to have a `dtype` argument that mirrors the table API, as suggested by @bsipocz. I like that idea. Most users use `io.ascii` through the table interface an likely don't even know that there is all this extra machinery with extra classes and converters etc. under the hood. 
If we do that, we unfortunately have yet one more way to set the dtype (converters, dtype, in the Outputter class), but maybe that's a price we are willing to pay.

**Comment by mhvk** [comment]
I agree I like the `dtype` argument that mirrors that of the initializer, even though it breaks the one way paradigm a bit. But at some level we can keep that as a separate issue, all it would add is something along the lines of,
```
converters.update({name: dt for (name, dt) in zip(names, dtypes) if dt is not None})
```

**Comment by taldcroft** [comment]
From my usage it is quite convenient to specify the dtype by column name and not have to provide a complete list. For reading in ASCII tables I think it is quite common that there are just a small number of columns that don't get the right type by inference.  More radically, what about allowing a list or a dict, and extending that API change to Table? Just throwing that out there...

The Table API is somewhat driven by the very old connection to numpy structured arrays. I don't remember the history of `dtype` but I've never thought it was especially convenient.

**Comment by pllim** [comment]
Would be nice to see some "real world" examples in the original post w.r.t. `converters` vs `dtype`. I think that would help drive the conversation.

**Comment by bsipocz** [comment]
My only real world examples are in fact the same case that I run into multiple times:
 - read in something with a string column rather than int/float
 
 For this: I could not find the solution myself, reading our own documentation. I was searching for the keyword `dtype`, it was nowhere mentioned in connection of `converters`, see https://github.com/astropy/astropy/issues/11278 and linked issues within.
 
Same example came up then multiple times with different users who were asking for help on this. Others suggested the workaround of using pandas for the read in, set the dtype, then convert back to Table. Again, they were looking for a type/dtype way to specify what they want rather than think how the internals work, the logic of converters.

So yes, I think we certainly need a  user facing, user friendly`dtype ` kwarg, at least for `Table.read`.  Whether that processes everything into a `converters` for `ascii.io` under the hood, I don't mind. 
And we need more docs as converters are not at all intuitive.

**Comment by bhayden53** [comment]
To add a voice to this, I just spent ~30 minutes trying to figure out how to force ascii to read a column in as a string. It was a string with leading zeroes, and was being converted automatically to an integer. I first started looking for exactly this issue; a way to simply pass a dictionary of dtypes keyed on column name. After I realized that was impossible I had to dig through the docs and figure out how to use a converter to accomplish this. In the end it was possible, but the proposal here would be so much more user-friendly.

I also find the Table read/write docs a little hard to navigate; there's just so much to get through and it can get spread over several different pages depending on which reader you're using.
