### ISSUE TITLE
quantity_input could provide access to the unwrapped function

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#11987]
### Description

It is very handy to use the `quantity_input` decorator to ensure the inputs to a function are Quantities with appropriate units. But this checking makes it impossible to use the function with the python package `uncertainties` or other automatic-differentiation tools that rely on passing things that behave enough like numbers to pass through simple mathematics. In an ideal world one would be able to attach units to such exotic objects, but in practical terms the easiest thing to do is to pass these objects through the raw un-decorated version of the function - if the decorator provided that.

### Additional context

I suggest usage that looks like:
```python
@quantity_input
def f(x: u.m):
    return x**2

f(1*u.m)

f.raw(ufloat(1, 0.1))
```

This should be implementable, if desired, just by storing the function to be wrapped in an attribute of the wrapper object.

**Comment by nstarman** [comment]
@aarchiba, ``units.quantity_input`` uses ``functools.wraps`` to create the wrapper. For more detailed information, see https://docs.python.org/3/library/functools.html#functools.wraps. The actual wrapper creating function, https://docs.python.org/3/library/functools.html#functools.update_wrapper, adds a reference to the original function via the attribute ``__wrapped__``, so you can do

```
@quantity_input
def f(x: u.m):
    return x**2

f(1*u.m)

f.__wrapped__(ufloat(1, 0.1))
```

While this is not super discoverable just by function introspection, it is the solution built into the standard library. Perhaps a note in the docs point people to ``.__wrapped__`` would be helpful.

**Comment by mhvk** [comment]
Slightly off topic, but since `uncertainties` was mentioned: I've long meant to have a proper `Measurement` class in `astropy.uncertainties`, and got quite a bit of the way to make an array-based version of `uncertainties` - see #3715 for an initial implementation and discussion about pitfalls as well as the current version at https://github.com/astropy/astropy/compare/main...mhvk:uncertainty?expand=1

If I remember correctly, yhe main problem is tracking covariances for operations involving non-trivial broadcasts. I may get back to that once `Masked` is really fully functional...

**Comment by nstarman** [comment]
https://github.com/nanograv/PINT/issues/1106#issuecomment-890551534 mentions the solution from the above discussion.

**Comment by aarchiba** [comment]
We had some discussion that the documentation for `quantity_input` wasn't as friendly and discoverable as we wished, so a PR that fleshed it out and mentioned the availability of `__wrapped__` would be nice. My schedule is a little full just now, though.
