### ISSUE TITLE
UCD list is still on version 1.3

### ISSUE THREAD

**Issue by msdemlei** [astropy/astropy#11983]
### Description

On June 16, the IVOA have published version 1.4 of the list of UCDs.
The UCD list included in astropy,
astropy/io/votable/data/ucd1p-words.txt, still is on version 1.3.

### Expected behavior

Version 1.4 should be adopted.

### Remarks

By the way, the document is now being maintained on github,
https://github.com/ivoa-std/UCDList, with the UCD list itself at
https://github.com/ivoa-std/UCDList/blob/master/ucd-list.txt

Regrettably, the new upstream list has a lot of whitespace diff against
what is currently in astropy, which is one reason I'm not doing the
(rather trivial) PR myself. 

Note that astropy shouldn't just pull ucd-list.txt from upstream by some
magic at this point, as merges to master can happen at any time without
community review (the content of master is the object of the review).
I'm sure we could establish a current-release (say) branch, though, if
you would like to automatically pull from somewhere.

**Comment by pllim** [comment]
Thank you for the report!

@tomdonaldson , is this a follow-up of #9475 ?

**Comment by tomdonaldson** [comment]
> Thank you for the report!
> 
> @tomdonaldson , is this a follow-up of #9475 ?

@pllim No these are not directly related.  The version numbers (1.3 and 1.4) are coincidence only.

**Comment by tomdonaldson** [comment]
This does seem like a case where we could draw from an external resource to keep the list current without requiring a new astropy release.  I want to be a bit careful though since lack of internet or an unreliable resource would produce frustrating results for CI and users.

I also wouldn't want to delay supporting the new list until that's figured out, so I'll try to take a look at manually getting the new version, which seems to be reliably available as a download of the [UCDList-1.4 EN release](https://github.com/ivoa-std/UCDList/releases/tag/v1.4-EN) .

**Comment by bsipocz** [comment]
Closing as this is now on v1.5
