### ISSUE TITLE
Angle bug for (d, m, s) tuple input (deprecate dms_to_degrees)

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#12239]
`Angle` does not handle the sign correctly for a `(d, m, s)` tuple input if `d=0`:

```python
>>> from astropy.coordinates import Angle
>>> ang = Angle((-0, -42, -17), unit='deg')
>>> print(ang)
0d42m17s
>>> print(ang.dms)
dms_tuple(d=0.0, m=42.0, s=16.999999999999886)
>>> print(ang.signed_dms)
signed_dms_tuple(sign=1.0, d=0.0, m=42.0, s=16.999999999999886)
```

### Expected behavior

```python
>>> ang = Angle((-0, -42, -17), unit='deg')
>>> print(ang)
-0d42m17s
>>> print(ang.dms)
dms_tuple(d=-0.0, m=-42.0, s=-16.999999999999886)
>>> print(ang.signed_dms)
signed_dms_tuple(sign=-1.0, d=0.0, m=42.0, s=16.999999999999886)
```

**Comment by webbdays** [comment]
Hi larrybradley and others,
I am recently working on this issue.
In the process..
I cannot find the definition of namedtuple()
I don't know yet whether it is a class or function.
Please help me here.

**Comment by webbdays** [comment]
I came to know that the namedtuple is from python collections module.

**Comment by webbdays** [comment]
@larrybradley 
It looks like the problem is with d =-0
It is being treated as d=0 .
The sign is lost at the time of arguments passing.
We need to preserve that sign.
Solution_1 :
Take (d,m,s) arguments as strings at first.
Like ("-0","-2","-3")
Get the sign that we needed.
And then convert them to numeric when needed.

**Comment by webbdays** [comment]
@larrybradley 
please give some clarity here.
Are (d,m,s) = (-1,2,3) and (-1,-2,-3) and (1,-2,3) different or the same ?

**Comment by larrybradley** [comment]
@webbdays - A `coordinates` package maintainer should help you with this.

Pinging @adrn, @mhvk, @eteq, @StuartLittlefair

**Comment by adrn** [comment]
Haven't checked what is actually supported, but I think the logic should be:
if d=0, check sign of m
if m=0, check sign of s
Take the sign from any non-zero elements.
if m != 0 and s != 0, but have different signs, throw an exception.

So: (0, -40, -30) is valid input for -0.675º, (0, 0, -30) is valid, but (0, -40, 30) is not valid.

Note: This could also be the case for hms input!

**Comment by webbdays** [comment]
@adrn 
I have proposed the same, earlier in my solution 1.
Sign can depend on subsequent d,m,s.

The proposed solutions are described in the doc string of the function.

And the code for solution 1 was added.

Please see those details in my pull request that I submitted earlier.

Please help me there.
I had problems. There bots are doing some checks.
I have resolved some pep8 style errors in my subsequent commits.

But remaining checks are still there to pass.

Please help.

I am new to pull requests.

**Comment by mhvk** [comment]
I have not followed this closely, since there are some release blockers right now, but I think the tuple input is rarely if ever used, so we should not overthink too much. I guess there are two suggestions right now:
1. @webbdays just above: Just do (effectively) `result = deg + min/60 + sec/3600` -- hence individual signs are possible.
2. @adrn: Error if the signs are inconsistent (but perhaps ignoring sign of 0).

If we were starting from scratch, my tendency would be to go with (1) for its simplicity, but the current implementation in `angle_formats.dms_to_degrees` is really not consistent with that logic: it checks ranges of minutes and seconds, and also happily truncates results, resulting in (to me) very surprising behaviour:
```
In [7]: Angle((-1.5, 0.5, 0.5), 'deg')
Out[7]: <Angle -1.00013889 deg>
```
(here the .5 on the degrees and minutes have been removed, and the signs on minutes and seconds are explicitly ignored...)

Given such behaviour, I'm not sure this is worth much effort!  If anything, I'd say that I'd just try getting the sign from minutes if deg == 0 and sign is positive (and from seconds if minutes is also 0 with positive sign).

For reference, code is: https://github.com/astropy/astropy/blob/993cf238fe26fa543b31de0d147cd532d9d205e9/astropy/coordinates/angle_formats.py#L412-L436

**Comment by webbdays** [comment]
Yes, it is ignoring the fractional part.

And Yes,

If d=0 check m, if m==0  check s 

Is good to go.

**Comment by webbdays** [comment]
@adrn and @mhvk
Thanks for your efforts in the discussion.
@mhvk , you brought good solution with solves all these problems in a single shot.
Please make  pull request with this :
result = deg + min/60 + sec/3600 .
I think it solves this issue #12239 .

It is simple without any struggle with if else statements for sign determination.

And also it solves the problem with fractional parts also. (One can give fractional arguments also. )

**Comment by webbdays** [comment]
For range checking giving positive d,m,s values as arguments to those range checking functions is good to go.

**Comment by webbdays** [comment]
if to follow above mentioned solution,
there is need for some changes in dms and signed_dms methods of Angle class.
And may be in many other places where this sort of thing for d,m,s (can be + or - , can be 0, can be fractional) is used.

Example :
what is Happening
>>> ang1 = Angle((-0, -42, -17), unit='deg')
>>> ang2 = Angle((-0,-42,17),unit='deg')
>>> ang1.dms
dms_tuple(d=-0.0, m=-42.0, s=-16.999999999999886)
>>> ang2.dms
dms_tuple(d=-0.0, m=-41.0, s=-43.000000000000114)

what is Expected
>>> ang1 = Angle((-0, -42, -17), unit='deg')
>>> ang2 = Angle((-0,-42,17),unit='deg')
>>> ang1.dms
dms_tuple(d=-0.0, m=-42.0, s=-16.999999999999886)
>>> ang2.dms
dms_tuple(d=-0.0, m=-42.0, s=16.999999999999886)


And also,
I cannot understand what is the use of signed_dms and sign attribute when sign can be included in d,m,s itself.

what about signed_dms 
for (d=-1,m=-2, s=3) => dms_tuple(sign=-1.0, d=1, m=2, s=3)?
for (d=-1, m=-2, s=-3 ) => dms_tuple(sign=-1.0, d=1, m=2, s=3) ? 

what is the significance of signed_dms and sign there?.

**Comment by mhvk** [comment]
@webbdays - the problem is that a change in implementation may well break people's code...

**Comment by webbdays** [comment]
Ok.
But how to solve the problem raised in this issue ?

**Comment by pllim** [comment]
Given https://github.com/astropy/astropy/pull/12443#issuecomment-982050880 , I am editing the title to deprecate this function.

**Comment by eteq** [comment]
Note in #12239 I've added a deprecation for `dms_to_degrees`, which I think we'll consider addressing this. 

If @larrybradley or someone comes back and says "no, critcial use case!" an alternative approach that keeps it but forces the user to pick a specific way of dealing with negative signs was begun here: https://github.com/eteq/astropy/commit/82fa4dc9755d7f568f854bdc75902d797d2d8dcf (although I hadn't yet included the @adrn case of "check the signs" before deciding it wasn't worth the time if no one will use it)
