### ISSUE TITLE
`SpectralCoord` values cause validation failure in `astropy.modeling.bounding_box._Interval`

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/astropy#12439]
### Description
Issue astropy/specutils#893 some of the issues described by @rosteen indicate that In astropy 5.0 there can be some issues when bounding boxes validate their interval components. In particular, these errors seem to occur when interval bounds are assigned as `SpectralCoord` types.

The following should reproduce the error in a more controlled fashion:
```python
import astropy.units as u
from astropy.modeling.bounding_box import _Interval
from astropy.coordinates import SpectralCoord

lower = SpectralCoord(1, u.um)
upper = SpectralCoord(10, u.um)
interval = _Interval.validate((lower, upper))
```

This interval should validate and be constructed without issue. However, it currently produces the following traceback:
```python
interval = (<SpectralCoord 1. um>, <SpectralCoord 10. um>)

    @staticmethod
    def _validate_shape(interval):
        """Validate the shape of an interval representation"""
        MESSAGE = """An interval must be some sort of sequence of length 2"""

        try:
            shape = np.shape(interval)
        except TypeError:
            try:
                # np.shape does not work with lists of Quantities
                if len(interval) == 1:
                    interval = interval[0]
                shape = np.shape([b.to_value() for b in interval])
            except (ValueError, TypeError, AttributeError):
>               raise ValueError(MESSAGE)
E               ValueError: An interval must be some sort of sequence of length 2

bounding_box.py:73: ValueError
```

**Comment by nden** [comment]
The issue here is that [SpectralCoord.to_value()](https://github.com/astropy/astropy/blob/main/astropy/coordinates/spectral_quantity.py#L181) overwrites [Quantity.to_value()](https://github.com/astropy/astropy/blob/main/astropy/units/quantity.py#L855) and makes `unit` a required argument.

What is the reasoning behind this?  I understand why  [SpectralCoord.to()](https://github.com/astropy/astropy/blob/main/astropy/coordinates/spectral_quantity.py#L181)  needs to require a unit but shouldn't [SpectralCoord.to_value()](https://github.com/astropy/astropy/blob/main/astropy/coordinates/spectral_quantity.py#L181) allow `unit=None` and return the value itself?

Perhaps @astrofrog or @eteq can clarify this.

**Comment by astrofrog** [comment]
I don't think there was a reason, if Quantity allows it we should probably allow it in SpectralCoord to be consistent
