### ISSUE TITLE
USNO IERS services are back online, but do we still care?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#12777]
From Malynda Chizek Frouard, "https://maia.usno.navy.mil and https://aa.usno.navy.mil are back!"

But do we still care, @eteq and @mhvk ? Follow-up of #9427

https://github.com/astropy/astropy/blob/a643a37a33f87c2566c1b484066cb6563ef93b3d/astropy/utils/iers/iers.py#L42

**Comment by eteq** [comment]
I don't have hard numbers on this, but my subjective feeling right now is that we do still care because the mirrors we're using now are not as reliable as the old USNO site was.  It also appears these new servers are https instead of ftps, which is *much* better from a support perspective.

That said, not clear that the new USNO servers are going to be the same as the old ones.  There's also some questions that we never got answered before about whether non-US IPs can access this as well (or at all) as those inside the US.

I think the thing to start with is to try to access the following URL from lots of places over a few weeks and see how reliable it is:
https://maia.usno.navy.mil/ser7/finals2000A.all

I just did `wget https://maia.usno.navy.mil/ser7/finals2000A.all` several times now and got ~4 MB/s and no failures. I am currently in what I'm guessing is the best place possible to access a USNO server, though (physically close to both USNO and relevant data centers.)

Maybe @mhvk, @dhomeier, @saimn , or @ceb8 can try this a few times whenever you get a chance to both get a "real-life" spread of non-US data on this?
