### ISSUE TITLE
Astropy fitting not actually fitting

### ISSUE THREAD

**Issue by janerigby** [astropy/astropy#12809]
I'm running into an issue doing very simple fitting of a 5007 emission line using astropy.  The problem is, it doesn't actually fit -- the result has the same parameters as the initial guess.  

The data file to be fit, subset.csv, is here:
 https://drive.google.com/file/d/19NbBb5jgyc_R5v75BK1QZ9e-Ug5gKbvk/view?usp=sharing

And here's the minimal code:

```
import pandas
import matplotlib.pyplot as plt
from astropy.modeling import models, fitting

restwave = 5006.9
subset = pandas.read_csv("subset.csv")
model = models.Gaussian1D(amplitude=1.2E4, mean=restwave, stddev=0.8) # + models.Gaussian1D(0.5E4, restwave, 2)
fitter =  fitting.LevMarLSQFitter()
gg_fit = fitter(model, subset['wave_rest_A'], subset['src1_flagged'])  # now fit it.
plt.plot(subset['wave_rest_A'], subset['src1_flagged'], color='k') 
plt.plot(subset['wave_rest_A'], gg_fit(subset['wave_rest_A']), color='y')
plt.show()
```

Help much appreciated

**Comment by WilliamJamieson** [comment]
@janerigby, I have been exploring this issue. I might have a solution to the bug, does this seem like a better fit:
![output](https://user-images.githubusercontent.com/20687711/152065276-44497a36-1e58-4070-9c26-33032db3f505.png)
(Note that it does not use the commented out model being added to the initial model from your reproducer.)

**Comment by janerigby** [comment]
@WilliamJamieson , yes, at least your fit is different from the initial model!  I'm not sure it's the best fit, but it's at least changing the fit from the initialization. What did you try?

**Comment by WilliamJamieson** [comment]
@janerigby, in investigating the source of your issues I determined that you where correct in the assertion that the `Gaussian1D` model's parameters where not being changed by the fit. This is despite the fitting algorithm being correctly applied, and several iterations occurring.

In my analysis, I found that the [objective function](https://github.com/astropy/astropy/blob/ed8cab8ec1443838bf9dab406614b00be87a24a4/astropy/modeling/fitting.py#L1069-L1089) for the `LevMarLSQFitter` was returning `NaN` values to the least-squares algorithm in use. The current least-squares algorithm is `scipy.optimize.leastsq` (a legacy method in scipy now), which notes that the [objective function "must not return `NaN`s or fitting might fail](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/optimize/minpack.py#L292-L295). This is exactly what is taking place in your case. I am not exactly sure why its producing `NaN` values for your case however.

To produce the plot I posted, I modified the objective function in `LevMarLSQFitter` to run `np.nan_to_num` on its result prior to passing these values back to `scipy.optimize.leastsq`. I am unsure if "fix" is the correct way to proceed at this time. I want to investigate further why your case is producing `NaN` values to start with.

**Comment by WilliamJamieson** [comment]
Note that in PR #12051 I introduce a `TRFLSQFitter`, which is a wrapper of the [`scipy.optimize.least_squares` ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares) method. As @saimn pointed out, `scipy`'s documentation indicates that this is the the recommended method for performing least-squares optimization. This issue may indicate that we might want to consider implementing the `TRFLSQFitter` and depreciating the `LevMarLSQFitter`'s use of `scipy.optimize.leastsq` in favor of the `TRFLSQFitter` with the `lm` option used.

I will investigate applying the fitters in PR #12051 to this case and report back.

**Comment by WilliamJamieson** [comment]
After investigating with PR #12051, I have found that the `scipy.optimize.least_squares` method checks if the[ results from the `objective_function` are finite](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/optimize/_lsq/least_squares.py#L826-L827). Since `objective_function` is the same between #12051 and astropy-main, I think more investigation into why `objective_function` is returning some `NaN` values is needed.

Note that if the same `np.nan_to_num` is applied in #12051, the fit `TRFLSQFitter` obtains under both `trf` and `lm` fitting methods is identical to the fit obtained from `LevMarLSQFitter`.

**Comment by WilliamJamieson** [comment]
Alright, I figured out the reason for the numerical errors resulting in `NaN` values. In your data table `src1_flagged` is missing some data in the first 6 cells of the column. When `pandas` reads that column and passes it to astropy, it fills those empty cells with `NaN` values. The `objective_function` is essentially computing `model(x) - y`, where `y` is the `src1_flagged` data in your case. So the computed difference in the `objective_function` will be `NaN` in the positions corresponding to the empty data cells. As scipy notes, `leastsq` does not handle `NaN` values gracefully, so the algorithm fails to make any adjustments to the model for a better fit.

I can fix your "bug" with no changes to astropy by simply cutting off the first 6 entries of your `wave_rest_A` and `src1_flagged` data columns, which should not effect the fit in any meaningful way as there is no data to be fit in these cases.

For now, I suggest filtering out any `NaN` (empty cells) from your data prior to passing it to astropy. I will see if I can work on a mitigation for this "trap" in astropy, so that it at least raises a warning to the user.

**Comment by WilliamJamieson** [comment]
Linking issue #3575, as this is essentially the same problem.

**Comment by janerigby** [comment]
Agreed with your comment from yesterday.  Essentially, this is a philosophical problem with how to treat NaNs.  The Observer say, contaminated wavelengths have unknown flux, so I will replace those fluxes with NaNs.  And then the fitter is freaked out by the NaNs, but then as you say, does not report that freak-out in a graceful way to the user.  Agreed it would be very helpful to astropy to raise a helpful warning.

I did get the fitter to iterate, by changing my bad-pixel-flagging from "replace flux with NaN" to "delete the row".  Which is the test you suggested.
