### ISSUE TITLE
`Quantity.__ilshift__` throws exception with `dtype=int`

### ISSUE THREAD

**Issue by wtbarnes** [astropy/astropy#12964]
### Description

The `astropy.units.quantity_input` decorator throws a `UFuncTypeError` when used on a function that returns a `Quantity` with `dtype=int` and a return type annotation. 

### Expected behavior

For the function to return a `Quantity` with `dtype=int` with the appropriate units or to throw an exception if the output units are of the wrong type.

### Actual behavior

Using the decorator results in a `UFuncTypeError`

### Steps to Reproduce

```python
import astropy.units as u
@u.quantity_input
def foo()->u.pix: return u.Quantity(1, 'pix', dtype=int)
foo()
```

gives

```python-traceback
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 foofoo()

File ~/anaconda/envs/aiapy-dev/lib/python3.9/site-packages/astropy/units/decorators.py:320, in QuantityInput.__call__.<locals>.wrapper(*func_args, **func_kwargs)
    316     _validate_arg_value("return", wrapped_function.__name__,
    317                         return_, valid_targets, self.equivalencies,
    318                         self.strict_dimensionless)
    319     if len(valid_targets) > 0:
--> 320         return_ <<= valid_targets[0]
    321 return return_

File ~/anaconda/envs/aiapy-dev/lib/python3.9/site-packages/astropy/units/quantity.py:1087, in Quantity.__ilshift__(self, other)
   1084     self.view(np.ndarray)[...] = value
   1086 else:
-> 1087     self.view(np.ndarray)[...] *= factor
   1089 self._set_unit(other)
   1090 return self

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### System Details

```
macOS-10.16-x86_64-i386-64bit
Python 3.9.7 (default, Sep 16 2021, 08:50:36)
[Clang 10.0.0 ]
Numpy 1.22.3
pyerfa 2.0.0.1
astropy 5.0.2
Scipy 1.8.0
Matplotlib 3.5.1
```

**Comment by pllim** [comment]
Don't you want fractional pixels?

**Comment by wtbarnes** [comment]
In general, yes. My specific use case is perhaps a bit silly. There are times where I want to use the output of the function as the input for the shape for a new array (which has to be of type `int`). Without specifying `dtype=int`, I have to `.value.astype(int)`.

I just struck me as odd that I can create a `Quantity` with `dtype=int`, but that this does not play nicely with the `quantity_input` decorator.

**Comment by pllim** [comment]
@Cadair , didn't you originally implemented that decorator?

**Comment by nstarman** [comment]
I don't think the problem is with the decorator, but in `Quantity`

```python
x = u.Quantity(10, u.km, dtype=int)
x <<= u.pc
```

Will raise the same error.

**Comment by nstarman** [comment]
I changed the issue name to reflect the source of the error.

**Comment by nstarman** [comment]
@mhvk I think all we need to do is upcast the dtype of the view?

```python
self.view(float, np.ndarray)[...] *= factor
```

The question is what dtype to upcast to. Maybe
```python
dtype = np.result_type(x.dtype, type(factor))
x.view(dtype, np.ndarray)[...] *= factor
```

**Comment by mhvk** [comment]
As noted in #13638, I'm wondering about whether we should actually fix this.  The previous behaviour is that
```
q = <some quantity>
q2 = q
q <<= new_unit
q2 is q
# always True
```
Similarly with views of `q` (i.e., shared memory).

Above, the request is either to raise an exception if the units are of the wrong type. Currently, we do raise an error but I guess it is very unclear what the actual problem is. So, my preferred route would be to place the inplace multiplication in an `try/except` and `raise UnitsError(...) from exc`. (I guess for consistency we might then have to do the same inside the check for unit transformations via equivalencies...)

**Comment by nstarman** [comment]
The problem appears to be that numpy can't change dtype without copying. If that were possible this wouldn't be an issue.

```python
>>> x = np.arange(10, dtype=int)
>>> y = x.astype(float, copy=False)  # it copies despite this, because int->float = 😭 

>>> np.may_share_memory(x, y)
False
```

**Comment by nstarman** [comment]
So either we give up the assurance of shared memory, or this should error for most cases.
We can make this work for the case that ``factor`` in https://github.com/astropy/astropy/issues/12964#issuecomment-1073295287 is an integer (e.g. ``(10 * u.km) <<= u.m``  )

**Comment by mhvk** [comment]
Yes, numpy cannot change in-place since also the number of bytes is not quaranteed to be the same (`int32` can only be represented safely as `float64`).

On second thought about the whole issue, though, I think it may make more sense to give up the guarantee of shared memory. In the end, what the user wants is quite clear. And in a lot of python, if `a <<= b` does not work, it returns `NotImplemented`, and then one gets `b.__rlshift(a)` instead. Indeed, this is how `array <<= unit` is able to return a quantity.
