### ISSUE TITLE
Regarding FITS standard definition for 'Jy/beam'

### ISSUE THREAD

**Issue by spectram** [astropy/astropy#13217]
Astropy unit definition for Jy/beam currently exports it as 'beam-1 Jy'
`from astropy import units as u`
`(u.Jy/u.beam).to_string('FITS')`
'beam-1 Jy'

This is contrary to how most radio astronomy packages define the unit. 'Jy/beam' seems to be the accepted convention. The space after beam-1 makes parsing needlessly cumbersome as well. Is this something that can be fixed? See related issues opened in SpectralCube and SoFiA2.

https://github.com/radio-astro-tools/spectral-cube/issues/806

https://github.com/SoFiA-Admin/SoFiA-2/issues/74

**Comment by pllim** [comment]
Err what does the FITS standards paper(s) have to say about this?

**Comment by spectram** [comment]
https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf This one mentions 'Jy/beam' as an example. But the unit is not defined anywhere in the document.

**Comment by saimn** [comment]
`beam-1 Jy` is a valid FITS unit. I think the `-1` is preferred by Astropy because using more than one `/` is discouraged, but @mhvk has probably more to say about this.

**Comment by mhvk** [comment]
Hmm, that may be valid but I agree it is not the most readable! It is also a bit odd that the generic format, i.e., with `(u.Jy/u.beam).to_string()`, one gets 'Jy / beam' .

@spectram - would 'Jy beam-1' be sufficiently better? I think that might be relatively straightforward to implement, and at least easier than trying to work with `/`. Though I should add that I have not actually looked at the code in `units/format/fits.py`, nor do I see much time for it in the near future... But a PR that solves this more or less generally would certainly be welcome!

**Comment by vdhulst** [comment]
Writing `Jy beam-1' would already make infinitely more sense. It may be good to point out that all major radio observatories/software packages use Jy/beam as unit so in principle that is the preferred way for now.
The IAU has Jy as recognised unit, but does not stipulate anything about Jy/beam (https://www.iau.org/publications/proceedings_rules/units/). Beam is mentioned as a 'miscellaneous unit' table 4 in the FITS document https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf

**Comment by AlecThomson** [comment]
Hey all,

I just wanted to bump this thread, if possible. Astropy does seem to be the outlier here since (as already mentioned) CASA, wsclean, YandaSoft, etc. all produce images with
```
BUNIT   = 'Jy/beam '           / Brightness (pixel) unit
```
Looking at the [WCS papers](https://www.atnf.csiro.au/people/mcalabre/WCS/wcs.pdf), notably Table 3:
![image](https://user-images.githubusercontent.com/9074527/218953706-e0914d74-1e91-4586-891f-b88a56c554dc.png)
a number of string-denoted operations are supported. So the FITS standard could be any of:
```
Jy beam**-1
Jy beam^-1
Jy/beam
```
It would be really nice to have the last option be the default. This would also help the downstream packages, as mentioned in the OP.

**Comment by pllim** [comment]
Since CASA is mentioned, I am obligated to ping @keflavich . 😸

**Comment by keflavich** [comment]
Yeah I'll put my weight behind the rest here: `Jy/beam` is the most readable, followed by `Jy beam^(-1)` and its variants.  We read the unit as "Janksys per beam" out loud (and in my head).

`beam` is itself a horrendous unit that is incredibly useful, which is likely why it's overlooked in IAU rules.

I think we have broad consensus here that *some* alternative that puts inverse `beam` after `Jy` is desired, so we just need an implementation.

**Comment by keflavich** [comment]
To help get this rolling:
`beam` comes before `Jy` because of this alphabetization:
https://github.com/astropy/astropy/blob/main/astropy/units/format/generic.py#L633

Past that, I'm not sure what the preferred way is to fix this. I don't see an obvious place to inject specific exceptions to this rule.

**Comment by mhvk** [comment]
Note that `generic` actually does this right (because positive powers come first, I think. 

Anyway, I think there is general consensus that ideally it be `Jy / beam` and at the very least `Jy beam-1`. It all boils down to the question who has time to actually implement it...

**Comment by mhvk** [comment]
See #14439 for a possible fix.
