### ISSUE TITLE
TST: ASDF test_isot fails with AssertionError in dev job

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13338]
Example log: https://github.com/astropy/astropy/runs/6908150791?check_suite_focus=true

It ran with `asdf: 2.12.1.dev26+g7e34de4`.

```
__________________________________ test_isot ___________________________________
tmpdir = local('/tmp/pytest-of-runner/pytest-0/test_isot0')
    def test_isot(tmpdir):
        tree = {
            'time': time.Time('2000-01-01T00:00:00.000')
        }
        helpers.assert_roundtrip_tree(tree, tmpdir)
        ff = asdf.AsdfFile(tree)
        tree = yamlutil.custom_tree_to_tagged_tree(ff.tree, ff)
>       assert isinstance(tree['time'], str)
E       AssertionError: assert False
E        +  where False = isinstance({'value': '2000-01-01T00:00:00.000', 'base_format': 'isot'}, str)
.../astropy/io/misc/asdf/tags/time/tests/test_time.py:92: AssertionError
```

The dev job [succeeded in main 4 days ago](https://github.com/astropy/astropy/runs/6852052360?check_suite_focus=true) with `asdf: 2.12.1.dev21+g5bfe173`.

@WilliamJamieson , any idea what happened and how to fix? Thanks!

**Comment by WilliamJamieson** [comment]
Why is `asdf-astropy` installed for these tests?

There has been no changes to `asdf` in the past 4 days which could cause this (just docs changes). Since `asdf-astropy` is installed I suspect that these tests are no exercising any astropy code, and that the detected failure is due to astropy/asdf-astropy#86. Indeed, the `base_format` keyword was added by that PR in order to resolve roundtrip bugs.

I suggest that astropy not install `asdf-astropy` during testing, as this will override all the `asdf` related things in astropy.
