### ISSUE TITLE
Error when fitting zero-degree polynomial

### ISSUE THREAD

**Issue by EdBehn** [astropy/astropy#13617]
### Description

When trying to fit data with a zero-degree 1-dimensional polynomial, a ValueError is raised. 

### Expected behavior

I expected a model object to be returned that represents a constant at the average of the data points. 

### Actual behavior

A ValueError is raised. The message is dependent on the fitter used. 

### Steps to Reproduce

Simply run the following script:

```
#!/usr/bin/env python3

import numpy as np

from astropy.modeling.models import Polynomial1D
from astropy.modeling.fitting import TRFLSQFitter, LevMarLSQFitter, DogBoxLSQFitter

if __name__ == '__main__' :
    model = Polynomial1D(0, c0=0)
    fitter = TRFLSQFitter() # Also fails with LevMarLSQFitter or DogBoxLSQFitter
    
    # Should work
    # Actually produes an error
    # The exact error depends on the fitter used
    # TRFLSQFitter    : ValueError: The return value of `jac` has wrong shape: expected (10, 1), actual (10, 10).
    # LevMarLSQFitter : ValueError: The array returned by a function changed size between calls
    # DogBoxLSQFitter : ValueError: The return value of `jac` has wrong shape: expected (10, 1), actual (10, 10).
    fit = fitter(model, np.arange(10, dtype=float), np.ones((10,)), weights=np.ones(10,))
    print('fit :', fit)
```

It seems that the error is in `_NonLinearLSQFitter._wrap_deriv` method. 
There is a try/except block. The except section returns a value that gives the correct behavior. However, the try section gives incorrect behavior. 

### System Details

```
>>> import platform; print(platform.platform())
Windows-10-10.0.19044-SP0
>>> import sys; print("Python", sys.version)
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.22.0
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0.1
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.9.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.5.3
```

**Comment by pllim** [comment]
Why not use a Constant1D model instead?

**Comment by EdBehn** [comment]
@pllim - That's a good point. I didn't know about Const1D. However, I still think this bug should be fixed.

**Comment by WilliamJamieson** [comment]
@pllim this *should* work.

Note that, I can reproduce the error. However, it only seems to appear when specifying weights, and only seemingly for the polynomial model.

> There is a try/except block. The except section returns a value that gives the correct behavior. However, the try section gives incorrect behavior.

Are you referring to this try/except block: https://github.com/astropy/astropy/blob/59144bcc3d449e8c4623365b4b0a691bc71b475c/astropy/modeling/fitting.py#L1142-L1149

If so, I think the issue here is that for some historical reasons (before I got involved with astropy) our polynomial models specify their `fit_deriv` as the transpose of what we typically expect. The try/except block is intended to catch this for polynomials and properly compute it. The issue is that no one ever anticipated fitting with weights for 0-degree polynomials.

I'll see if I can figure out a reasonable bugfix.

**Comment by WilliamJamieson** [comment]
As a side note, since polynomials are linear in their parameters, `LinearLSQFitter` is the recommended fitter.

**Comment by EdBehn** [comment]
@WilliamJamieson 
That is indeed the try/except block I'm referring to. 

I stumbled on this by accident. I'm creating a tool where the user can compose their own model as the sum of simpler components. (ie several gaussians and a polynomial background). That's why I wasn't using `LinearLSQFitter`.

**Comment by WilliamJamieson** [comment]
> I stumbled on this by accident.

Thanks, we are always looking for the corner cases.

> I'm creating a tool where the user can compose their own model as the sum of simpler components. (ie several gaussians and a polynomial background). That's why I wasn't using `LinearLSQFitter`.

No worries, I often see users wanting to always use the non-linear fitters because they "always work"; however, whenever possible one should use the linear fitter because it will be faster, more stable, and more accurate. 

For your application it makes sense to use a more general tool, as your problems will generally be non-linear.
