### ISSUE TITLE
DOC: Replace Anaconda with Miniconda in dev doc

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13724]
https://docs.astropy.org/en/latest/development/workflow/virtual_pythons.html

We should encourage the use of Miniconda over Anaconda. We do not want user to get bloated base env before they even start doing dev work on astropy.

* Replace Anaconda with Miniconda.
* Maybe even add a note to discourage the use of full Anaconda install.

**Comment by parejkoj** [comment]
Also change `conda` to `mamba` where it works (which isn't quite everywhere: e.g. `mamba activate ENV` doesn't work.

**Comment by parejkoj** [comment]
These pages also should be updated to reflect the install process/make links to the virtual env docs more prominent:
* https://docs.astropy.org/en/latest/development/workflow/development_workflow.html
* https://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#test-your-development-copy

**Comment by parejkoj** [comment]
As I noted on slack: there's a bunch of intertwined information on the above three pages, so someone who understands how it all links together should probably make the PR, but I'm happy to review and/or be a guineapig for stepping through it.

**Comment by dhomeier** [comment]
> mamba activate ENV doesn't work

In which setup? Using this regularly now on my `osx-arm64` installation (though I am still pretty much a conda dilletante, so cannot vouch that everything is working as it's supposed to).

**Comment by parejkoj** [comment]
`mamba activate ENV` gives the following message; maybe you ran that command yourself previously. This is with the lsst science pipelines Conda install.

```
Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate.
```

**Comment by BSGalvan** [comment]
Hello all!
I would like to work on this.
I have been using `mambaforge` exclusively for some time now, so the hardest part of this will be making sure I don't miss any `conda -> mamba` changes!

Just to clarify (since issue title and the discussions give me different conclusions), which of the following would we like the new devs to use?

List of minimal versions of Anaconda:
-  [miniconda](https://docs.conda.io/en/latest/miniconda.html): provides `conda`, and is configured to download from the Anaconda repository by default.
- [miniforge](https://github.com/conda-forge/miniforge#miniforge3): provides `conda`, and is configured to download from the (community-led) `conda-forge` repository by default.
- [mambaforge](https://github.com/conda-forge/miniforge#mambaforge): similar to Miniforge (also config'd to download from `conda-forge`), but provides `mamba`. Faster at dependency resolution, and supports parallel downloads.

From my understanding, miniconda can be tweaked to set `conda-forge` as the default channel, which would make it similar to miniforge (not same, since packages in the `base` environment would still be from the Anaconda channel, as opposed to `conda-forge`).

That being said, `mambaforge` is (non-trivially) faster for environments with complex dependency trees, and I would suggest considering this.

Let me know what seems sensible, and I'd be happy to get working on this!

**Comment by pllim** [comment]
So, before we go too far, does this make `mamba` moot?

https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community

```
conda install -n base conda-libmamba-solver
conda create -n demo --experimental-solver=libmamba --dry-run install <some package>
```

**Comment by BSGalvan** [comment]
I guess this does mean that you can reap all the benefits of `mamba` without having to switch to it wholesale!

Although there are some features which are unique to `mamba` (see [here](https://github.com/mamba-org/mamba#additional-features-in-mamba-and-micromamba)), I believe these may not warrant a complete switch of our recommendations for devs.
We may simply recommend switching to the experimental solver (with a _caveat emptor_ for bugs), and go ahead with updating docs for `miniconda`.

**Comment by pllim** [comment]
@parejkoj , is replacing Anaconda with Miniconda good enough, or do you insist on mamba too?

**Comment by parejkoj** [comment]
The reason I suggested it is that mamba is drastically faster at solving. I don't know what the difference is like in miniconda vs. e.g. the LSST environment, but the latter its an order of magnitude or more faster (few seconds vs. many minutes).

**Comment by pllim** [comment]
Maybe we should split this issue into multiple PRs. The one to change from Anaconda to Miniconda should be uncontroversial, but the conda/mamba thing is fast-evolving situation, and we don't want to keep coming back to update the docs.

**Comment by BSGalvan** [comment]
Alright, that seems like a sensible thing to do.
Is it alright if I go ahead and make a pull request to update the doc pages mentioned in this thread (along with others, if any)?
This will be for the Anaconda → Miniconda change alone. Later, when the `mamba` situation has suitably stabilized we can revise docs once more.

**Comment by pllim** [comment]
Sounds like a plan @BSGalvan . Thanks!

**Comment by pllim** [comment]
Thank you for your contribution, @BSGalvan !

@parejkoj , if you have strong feelings about mamba, please open a new issue. Thanks!
