### ISSUE TITLE
APE 20: Of black and backport

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13794]
In [APE 20](https://github.com/astropy/astropy-APEs/blob/main/APE20.rst), an implementation plan was laid out and the target was for v5.2. Since we are still on the hook to support v5.0.x as LTS until end of 2023 (see [APE 2](https://github.com/astropy/astropy-APEs/blob/main/APE2.rst) and [Release Calendar](https://github.com/astropy/astropy/wiki/Release-Calendar)), there is the matter of how do we backport to v5.0.x branch in a sane way after this implementation for v5.2.

Some ideas:

* We also apply `isort` and `black` to v5.0.x branch to keep it in sync enough for the auto-backport bot to still work.
    * Concern: While the automation part should be relatively painless, any manual edit that has to go in risk actually breaking the code that we have promised would be "long-term stable."
* We keep v5.0.x as-is but only limit manual backport to critical fixes in the event that auto-backport fails for any reason. See existing LTS policy at https://docs.astropy.org/en/latest/lts_policy.html .

This issue was a result of 2022-10-04 dev telecon discussions. cc @saimn @dhomeier @eerovaher @WilliamJamieson @braingram

Also cc @astropy/astropy-project-release-team

**Comment by mhvk** [comment]
Really this should be left to the black proponents to worry about, but I thought one nice thing about black at least is that it is guaranteed to not change the code, so no visual inspection would be necessary. This is a bit less true for `isort`, though any problems really should be caught by testing -- and doing `isort` is less important since changes in the imports are less common(?).

I do think later in a LTS release cycle we can be a bit stricter about backporting and, as you suggest, when automatic backports fail, only do a manual one for critical fixes.

p.s. Of course the easier solution is to postpone the conversion till the next LTS...

**Comment by taldcroft** [comment]
I think that applying black formatting to v5.0.x is safe and will reduce headaches. We can just run vanilla `black` on the entire v5.0.x code without any manual edits. Statistically speaking this will substantially reduce failed backports.

About isort, that seems safe enough to run as well and it seems extremely unlikely that we would have both (1) a bug in `isort` which (2) results in a change that does not show up in testing.

I did a test:
- Start with a blackened version of `astropy/io/fits/hdu/compressed.py`
- Make a trivial "bug fix" to change from using column 1 to column 2 in one line
- Try to cherry-pick this commit to the current main file.

No joy, merge conflict:
```
<<<<<<< HEAD
        self._header.set('TFORM1', tform1,
                         'data format of field: variable length array',
                         after='TTYPE1')
=======
        self._header.set(
            "TFORM2",
            tform2,
            "data format of field: variable length array",
            after="TTYPE2",
        )
>>>>>>> dcda09d462 (Fake fix)
```
Since black does end up hitting a large fraction of code lines, I would guess that backports will fail more often than not.

**Comment by astrofrog** [comment]
I agree that just running black without any exceptions on LTS is probably the best bet - it doesn't matter if some of the code ends up a bit ugly since no one is going to be working on editing that code directly. If someone does have time to add in some of the manual exceptions for black in LTS then that would be great, but agree it might not matter too much.

Backports usually get harder after about a year of LTS anyway so I suspect things will be a little harder even with applying black and isort to LTS, so either way I think we're going to have to be more picky on backporting only important/critical fixes to LTS.

**Comment by eerovaher** [comment]
I'm not sure if the `black` adoption timeline can be altered anymore, but I'll quote https://github.com/astropy/astropy-APEs/pull/76#discussion_r958562405

> [`darken`](https://pypi.org/project/darker/) can apply `black` formatting to only the lines that are being edited. This would allow for a transition period during which all new code would be `black`-formatted, so when the final switch to `black` finally happens the diffs would be smaller.

A transition period until the next LTS release could also help with backporting because `darken` would not cause any additional merge conflicts between the different branches. Either the patch being backported would be the first to edit the lines since the last branching, or a preceding patch would have caused a merge conflict anyways.

**Comment by mhvk** [comment]
I like the darkening suggestion but perhaps it is indeed too late.  And people doing the work should have the final say!

**Comment by taldcroft** [comment]
I'm :-1: on `darker` for a couple of reasons:
- Puts a new dependency into the process which is effectively a single-person project (https://github.com/akaihola/darker/graphs/contributors)
- Greatly increases conceptual and process complexity (see e.g. the shenanigans for editor integration https://pypi.org/project/darker/).

Not to mention that it is too late. The APE-20 discussion was open for quite some time and the wheels are now turning on implementing the agreed-upon strategy.

**Comment by WilliamJamieson** [comment]
I agree with @taldcroft.

**Comment by pllim** [comment]
This was decided upon and sent out as memos to mailing list.
