### ISSUE TITLE
`astropy.unit` not cooperative with static type checkers

### ISSUE THREAD

**Issue by ziriuz84** [astropy/astropy#13816]
I'm using astropy.Unit in my code. When I use something like 
`float(config['Observatory']['latitude'])*u.deg`
Neovim return an error like
`  Operator "*" not supported for types "float" and "Unit | IrreducibleUnit | ((H0: Unknown | None = None) -> Equivalency)"  Operator "*" not sup Pyright (reportGeneralTypeIssues) [168, 48]
`
My Neovim uses pyright and black. Is it really a problem or only a linter misunderstanding? My software run withouth problem

**Comment by nstarman** [comment]
This isn't [``black``](https://black.readthedocs.io/en/stable/), which does code formatting. [``Pyright``](https://github.com/Microsoft/pyright) is a static type checker. It's the latter tool which is having trouble with Astropy, since Astropy is not typed nor provides [type stubs](https://typing.readthedocs.io/en/latest/source/stubs.html). This is not a run-time issue, but it does mean any static analysis is tricky. If you need to use a static analyzer then you can [cast](https://docs.python.org/3.8/library/typing.html#typing.cast) values to their correct type, as required.
