### ISSUE TITLE
Catch common typos with codespell

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#13814]
### Description

https://github.com/codespell-project/codespell + pre-commit.

### Additional context

We can configure custom common misspells that are Astropy-specific.

**Comment by pllim** [comment]
@astrofrog tried something like that a long time ago but didn't quite work because we have too many jargons, I think.

**Comment by nstarman** [comment]
I think this one is a bit different.
"It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf"". So it's less jargon sensitive.

**Comment by pllim** [comment]
But but... US English vs UK English?

**Comment by astrofrog** [comment]
Here was my previous attempt: https://github.com/astropy/astropy/pull/7761

**Comment by nstarman** [comment]
> But but... US English vs UK English?

Configurable, so we can choose ⚖️👀

**Comment by pllim** [comment]
That is the problem. We couldn't get a consensus on which one. 😆

**Comment by nstarman** [comment]
I don't think we do much localization (e.g. https://www.sphinx-doc.org/en/master/usage/advanced/intl.html), which is, an accessibility Issue. Run-time docstrings can't easily be localized, but the docs can. Unfortunately, sphinx-itl doesn't differentiate between US & UK English. Thankfully none of these issues have to apply to code-spells if we don't want them to. Codespells does not have an allow-list of correct spellings, but only a block-list of incorrect spellings. So we just wouldn't include "colour" as a misspelling of "color" (or vice versa). We just don't block regionalisms in the spell checker. Codespells will be good for, e.g. "teh" vs "the".

**Comment by nstarman** [comment]
I've played around with codespell for my own stuff and did a quick dry run on Astropy. So many things are REALLY close to words but are actually things like column names for fits files in tests. All these trigger codespell. So it's possible to add to Astropy but will take some careful configuration. I did spot a LOT of misspells in the docs.

**Comment by nstarman** [comment]
Lots of small real ones. See https://github.com/nstarman/astropy/tree/pre-commit-codespell for a very small start. Since I don't have the correct config, I manually did a few in code spell's interactive mode.

**Comment by namurphy** [comment]
We've had a really good experience using codespell for [PlasmaPy](https://github.com/PlasmaPy/PlasmaPy).  

We didn't get many false positives because of its strategy of only looking for common misspellings.  The tradeoff is that it misses some misspellings, though we can catch those through code review or by using a more thorough spell checker.  

I think some of the false positives were because of short/abbreviated variable names...and I think it also ended up finding a few "misspellings" in binary images stored in pre-executed Jupyter notebooks or something.  We put these exceptions in [`setup.cfg`](https://github.com/PlasmaPy/PlasmaPy/blob/dc7056f77a65ffab3b583b11570cf5c63d70129d/setup.cfg#L313) (soon to be moved into `pyproject.toml`).  

For our [tox environment](https://github.com/PlasmaPy/PlasmaPy/blob/dc7056f77a65ffab3b583b11570cf5c63d70129d/tox.ini#L146) that we use for codespell in CI, we added text for new contributors that gets printed out describing how to add codespell exceptions.

**Comment by nstarman** [comment]
@namurphy If you have experience setting up codespell.... 😆

**Comment by namurphy** [comment]
A question!  Which option(s) would you prefer?

1. Add codespell as a pre-commit hook.
2. Add a tox environment and GitHub Action for codespell.
  - I took this approach for PlasmaPy so that the GitHub Action for this prints out how to add & words to ignore. In practice, I don't know if we've ever needed this.

**Comment by pllim** [comment]
What are the pros and cons between suggestions 1 and 2?

**Comment by namurphy** [comment]
My thoughts on pros & cons at the moment:

 - pre-commit hook
   - Would be able to catch misspellings locally and fix them quicker when using pre-commit
   - When there is a false positive (which is a fairly rare occurrence), it's unlikely that the error message will say how to add it to the list of ignored words 
   - On GitHub, it'll take longer to realize that it was a spelling error
 - tox environment & GitHub Action
   - Contributors will typically not learn about typos until commits are pushed to GitHub (unless they're good about running tox ahead of time)
   - Upon a push, it's quick to find out if any typos are caught
   - Can print out info on how to add to the list of ignored words
   - Yet another GitHub check on each PR to have to scroll through

**Comment by pllim** [comment]
We have a precommit CI, do you think we can piggyback this check on that job and also allow people to use precommit?
