### ISSUE TITLE
Diffing Time objects or values changes original time scale and format

### ISSUE THREAD

**Issue by HealthyPear** [astropy/astropy#13831]
### Description
Not sure if this is a bug or expected behaviour, but it's for sure unexpected to me...

When diffing times the scale and format change.

### Expected behavior

The resulting TimeDelta object should maintain scale and format of the original Time array (or list of Times) and return time in seconds since I start from UTC

### Actual behavior

Given `scale='utc', format='isot'` I get `scale='tai' format='jd'` resulting of course in a different time difference value

### Steps to Reproduce

```python
from math import ceil

import astropy.units as u
import astropy.Time as Time
import numpy as np

total_time=24*u.h
time_step=1*u.min
time_samples = ceil(total_time.to_value(time_step))
start_time=Time.now()
start_time.format="iso"
obstime = start_time + np.linspace(0, 24, time_samples) * u.h
print(obstime.format)
print(obstime.scale)
print(np.diff(obstime[:2]))
```

results in

```pycon
iso
utc
[<TimeDelta object: scale='tai' format='jd' value=0.000694927032661552>]
```

### System Details

macOS-11.7-x86_64-i386-64bit
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52) 
[Clang 13.0.1 ]
Numpy 1.23.3
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.9.1
Matplotlib 3.6.0

**Comment by taldcroft** [comment]
This is expected behavior. Astropy only directly supports delta times that are convertible to SI seconds. This is what is expressed by the `TAI` scale with format of `jd` (which is exactly 86400 SI `sec`).

A scale of `UTC` for a time delta would not be absolutely convertible to SI seconds since that conversion depends on the start time in case there is a leap second during the interval.

About the format, the astropy `Time` formats provide the representation of an absolute time and cannot be applied to a time delta. For instance `isot` format `YYYY-MM-DDThh:mm:ss.sss` cannot be used as the string representation of time delta like 25.3 seconds.

**Comment by HealthyPear** [comment]
I see.

What would be then the correct way to diff an observation time array or list of times to get the steps in seconds?

Do I have to convert each resulting delta by going through the array a second time?

`delta_seconds = [delta_jd.to("s") for delta_jd in np.diff(obstime)]`

**Comment by taldcroft** [comment]
You can do this:
```
In [10]: times = Time.now() + np.arange(4) * u.s

In [11]: delta_times = times[1:] - times[:-1]

In [12]: delta_times.sec
Out[12]: array([1., 1., 1.])
```
Using `np.diff` does not play perfectly well with `Time` and you end up getting a numpy object array of the `TimeDelta` objects.

**Comment by HealthyPear** [comment]
> Using np.diff does not play perfectly well with Time and you end up getting a numpy object array of the TimeDelta objects.

mmm yeah I noticed that some numpy methods change the nature of the Time arrays in numpy arrays of time objects

I was using e..g `np.tile` and `astropy.utils.masked.Masked` and I always end up with arrays of Time objects, not Time objects with array-like values

for what concerns the diffing I think we can close this issue.
