### ISSUE TITLE
WCSAxes broken with current `main` brach of Matplotlib

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#13873]
Trying to use `WCSAxes` with the latest `main` branch of Matplotlib (231d1c83f8b16e11580436ed19349dca368ea92f as of writing) is broken with the following traceback:
```python
Traceback (most recent call last):
  File "/Users/dstansby/github/matplotlib/test.py", line 12, in <module>
    plt.subplot(projection=wcs)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/pyplot.py", line 1277, in subplot
    ax = fig.add_subplot(*args, **kwargs)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/figure.py", line 745, in add_subplot
    ax = projection_class(self, *args, **pkw)
TypeError: WCSAxes.__init__() got multiple values for argument 'wcs'
```

Code to reproduce below. I'm not sure whether this is something that needs fixing with astropy or Matplotlib and don't have time to look into it now, but thought I'd open for info!

```python
import matplotlib.pyplot as plt

from astropy.wcs import WCS
from astropy.io import fits
from astropy.utils.data import get_pkg_data_filename

filename = get_pkg_data_filename('galactic_center/gc_msx_e.fits')

hdu = fits.open(filename)[0]
wcs = WCS(hdu.header)

plt.subplot(projection=wcs)
plt.imshow(hdu.data, vmin=-2.e-5, vmax=2.e-4, origin='lower')
plt.grid(color='white', ls='solid')
plt.xlabel('Galactic Longitude')
plt.ylabel('Galactic Latitude')
```

**Comment by ConorMacBride** [comment]
I haven't investigated this further, but this is no longer an issue for the latest astropy release when https://github.com/matplotlib/matplotlib/pull/23573 is reverted.

**Comment by pllim** [comment]
So, will https://github.com/matplotlib/matplotlib/pull/23573 be reverted? I don't see any indication of that when I read the comments of that PR.

**Comment by ConorMacBride** [comment]
I think the issue is that Matplotlib's `Axes` API (specifically, the signature of `_AxesBase.__init__`) has been changed, and is therefore no longer compatible with the signature of `WCSAxes.__init__`. The error is occurring when Matplotlib tries to use the new API with `WCSAxes.__init__`:
>``*args`` can also consist of three numbers or a single three-digit number; in the latter case, the digits are considered as independent numbers.  The numbers are interpreted as ``(nrows, ncols, index)``: ``(nrows, ncols)`` specifies the size of an array of subplots, and ``index`` is the 1-based index of the subplot being created.  Finally, ``*args`` can also directly be a `.SubplotSpec` instance.

Don't think it will be reverted. I just meant that when I reverted the commit it works again. Hopefully it's easy to update `WCSAxis`.

**Comment by ConorMacBride** [comment]
I think the issue is that Matplotlib's `Axes` API (specifically, the signature of `_AxesBase.__init__`) has been changed, and is therefore no longer compatible with the signature of `WCSAxes.__init__`. The error is occurring when Matplotlib tries to use the new API with `WCSAxes.__init__`:
>``*args`` can also consist of three numbers or a single three-digit number; in the latter case, the digits are considered as independent numbers.  The numbers are interpreted as ``(nrows, ncols, index)``: ``(nrows, ncols)`` specifies the size of an array of subplots, and ``index`` is the 1-based index of the subplot being created.  Finally, ``*args`` can also directly be a `.SubplotSpec` instance.

Don't think it will be reverted. I just meant that when I reverted the commit it works again. Hopefully it's easy to update `WCSAxis`.
