### ISSUE TITLE
TST: Add codecov flags for better coverage math

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13936]
As suggested by @jdavies-st in https://github.com/astropy/astropy/pull/13928#issuecomment-1296804175

*If you have one CI job that does one subset of tests and another that does some other subset, then you'll want to use codecov flags to label these. That way they can be compared to like "flags" and one subset won't be compared to another.*

**Comment by Cadair** [comment]
I assume this is the documentation for this feature: https://docs.codecov.com/docs/carryforward-flags

**Comment by jdavies-st** [comment]
Yes, if you have tests that cover one part of the code, and other tests that cover other parts, flags can help in coverage comparisons.

If the tests cover all the code, but only get run sometimes, say like regression tests, or slow tests, then one will want to use carryforward flags.  We do this in `jwst` so that the nightly regression tests get only compared for coverage with previous runs of the nightly regression tests, and that the per-PR unit tests only get compared for coverage with previous runs of the per-PR unit tests.

One can configure flags and if they are carryforward or not in `.codecov.yml`, and then `-F flagname` for uploading, or use the github action booleans.

**Comment by pllim** [comment]
Is it like https://github.com/astropy/astropy/pull/13941 or did I totally misunderstood the doc?

**Comment by pllim** [comment]
OK so this is no longer relevant, according to discussions in #13941 , right?
