### ISSUE TITLE
Conversion from kron-magnitude to AB magnitudes or similar

### ISSUE THREAD

**Issue by Nestak2** [astropy/astropy#13983]
### Description

I have received for a project Pan-STARRS observational data from a colleague. It only comes with kron-magnitudes. I would like to convert it to magnitudes in other systems (e.g. the AB system). Is this doable with astropy? I couldn't find in the astropy pages instructions how to do this. Some kind of a link reference or a code snippet would be very appreciated. Tnx!

**Comment by parejkoj** [comment]
If your Pan-STARRS data is processed following the usual PS pipeline, they're probably already on the AB system. They're not directly comparable to other fluxes because of the nature of how kron magnitudes are computed (an adaptive aperture).

https://outerspace.stsci.edu/display/PANSTARRS/PS1+Kron+photometry+of+extended+sources
