### ISSUE TITLE
Models with tied parameters do not pass units to tying functions while fitting

### ISSUE THREAD

**Issue by smsutherland** [astropy/astropy#14097]
### Description
When tying model parameters, the model which is passed into the tied function looses the units on its parameters. After fitting is complete, the returned model maintains the original units. It is (to my knowledge) only an issue with the model passed to the tying functions.

### Expected behavior
Since the model was created with units on its parameters, I expect to be able to use units while tying these parameters.

### Actual behavior
The model passed into the tying function has parameters which are unitless.

### Steps to Reproduce

The following code snippet demonstrates the effect.

```python
from astropy.modeling.models import Gaussian1D
from astropy.modeling.fitting import LevMarLSQFitter
import astropy.units as u
import numpy as np

# create a test gaussian to fit to
xs = np.linspace(-2, 2, 100)*u.m
ys = np.exp(-xs.value**2)

# create gaussian model
gaussian1 = Gaussian1D(amplitude=1, mean=0*u.m, stddev=1*u.m)

#tie stddev to mean
def tie(model):
    print(f"during fitting: {model.mean}")
    # I expect to be able to do this:
    # return model.mean + 1*u.m
    # or
    # return model.mean.quantity + 1*u.m
    # but instead I have to do this
    return model.mean + 1
gaussian1.stddev.tied = tie

print(f"before fitting: {gaussian1.mean}")
fitter = LevMarLSQFitter()
fitted = fitter(gaussian1, xs, ys)
print(f"after fitting:  {fitted.mean}")
```

The output of this looks like:
```
before fitting: Parameter('mean', value=0.0, unit=m)
during fitting: Parameter('mean', value=0.0)
... (many iterations of "during fitting")
during fitting: Parameter('mean', value=-6.057243013355982e-17)
after fitting:  Parameter('mean', value=-6.057243013355982e-17, unit=m)
```

As you can see, before and after fitting, the parameter has `unit=m`, but not during fitting.

### System Details

Windows-10-10.0.19044-SP0
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Numpy 1.21.2
pyerfa 2.0.0
astropy 5.3.dev53+ga93dd3dc2
Scipy 1.8.0
Matplotlib 3.4.3

### Edit
Simplified code snippet to better demonstrate issue.

**Comment by WilliamJamieson** [comment]
This is expected, the `LevMarLSQFitter`'s internal code (in particular, calls into `scipy`) does not support `Quantity` objects. So the units are stripped off all parameters and inputs during the fitting process using: https://github.com/astropy/astropy/blob/0e923721d7d26a075732f9f5593b86634f6508d2/astropy/modeling/fitting.py#L192-L198

This process is controlled by the `model.input_units_equivalencies` attribute so one needs to be somewhat careful when fitting models (and using things like `tied`) in order to handle units correctly. Indeed, for performance reasons it is recommended that one manually resolves all the units and strips them off inputs and model parameters manually prior to fitting (if possible).

**Comment by smsutherland** [comment]
Ah I understand. Thank you for the quick response!
