### ISSUE TITLE
Code links in docs

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#14279]
Might be nice!

https://github.com/felix-hilden/sphinx-codeautolink

**Comment by pllim** [comment]
Please elaborate more on why you think this is necessary.

I am hesitant to keep introducing new dependencies only to waste time removing them again in a few years when the maintainer disappears.

**Comment by mhvk** [comment]
I'm also a bit wary; dependencies like these typically seem to break things every year or so, and each time it will cost ~1 day of developer time to fix them. I think here the benefit is quite minimal.

Relatedly, it may be wise to go for more mature and stable packages rather than the latest and greatest that are still being heavily developed. I'm getting a bit grumpy with `ruff`'s continues updates, whcih keep breaking my emacs set-up with warnings that whatever new type of check that was introduced a day or so ago is not available in my ruff version from last week. As the warning occurs any time I open an astropy python file, it is quite annoying... Note that for `ruff`, I do see the advantage (and indeed `flake8` broke once in a while too) and hopefully things will stabilize as more and more of those type codes are removed by the corresponding issues being fixed, but I do worry a bit about the balance between formatting and content.

**Comment by nstarman** [comment]
Just as an example for how useful this can be for tutorials https://hypothesis.readthedocs.io/en/latest/quickstart.html.
I'm setting up a hypothesis test and having everything linked in the tutorial has made life much easier.

**Comment by pllim** [comment]
Maybe of more interest for the Learn team then. We can revisit if a bigger project picks up its maintenance. Personally, I think it is too risky right now.

**Comment by astrofrog** [comment]
If we were to consider this, I'd like to know what the impact on our build time would be given how many code examples we have (the docs build is already waaaay too slow)
