### ISSUE TITLE
Representing masked SkyCoord column in Table

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#14292]
```python
from astropy.table import Table,Column,MaskedColumn
from astropy.coordinates import SkyCoord
from astropy import units as u

tb = Table()
tb['skycoord'] = SkyCoord([0,1,2]*u.deg, [0,1,2]*u.deg, frame='fk5')
tb['foo'] = tb['skycoord']
tb['foob'] = Column(tb['skycoord'])
tb['fooc'] = Column(tb['skycoord'], dtype=SkyCoord)
```

`tb` is then:
```
<Table length=3>
skycoord   foo                                    foob                                                                fooc
deg,deg  deg,deg
SkyCoord SkyCoord                                object                                                              object
-------- -------- ------------------------------------------------------------------- -------------------------------------------------------------------
 0.0,0.0  0.0,0.0 <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (0., 0.)> <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (0., 0.)>
 1.0,1.0  1.0,1.0 <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (1., 1.)> <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (1., 1.)>
 2.0,2.0  2.0,2.0 <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (2., 2.)> <SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg\n    (2., 2.)>
```

How can I create Columns directly from SkyCoord objects while retaining their SkyCoord nature?

For example, I want to convert a `SkyCoord` column to a `MaskedColumn`.  How can I do that?

**Comment by keflavich** [comment]
I'm trying to answer my own question, and _part_ of the answer is on this page:
https://docs.astropy.org/en/stable/table/mixin_columns.html
which took me a long time to find.  I still haven't figured out how to mask out `SkyCoord` rows though.

**Comment by mhvk** [comment]
Masked `SkyCoord` are sadly not yet possible. (In principle, the underlying `Quantity` can now be masked, but the mask doesn't propagate up). On the wishlist at #11539

A `MaskedColumn` with `dtype=object` is possible, but then does not have any of the `SkyCoord` attributes.

**Comment by mhvk** [comment]
@pllim - One but last.

@keflavich - It would actually help #11539 if you would have an explicit idea about how masks should behave. Do all items in a `SkyCoord` share a mask? What should happen if I do `skycoord.data.lon.mask[10] = True` (likely indirectly of course!)? Part of the reason `SkyCoord` does not have a `mask` is that I never really felt sure what the best behaviour would be...

**Comment by keflavich** [comment]
@mhvk is it possible for just one coordinate to be masked?  Does that make sense? I would have thought it only makes sense for a whole coordinate to be masked or not-masked.

However, I'm not sure of this; I can see a use case for a coordinate having one or the other coordinate masked to indicate an entire ring of latitude or longitude.  Or, have the distance masked, or the distance unmasked and the celestial coordinate masked.  Those could all be useful in some case.  Nevertheless, they're not _obvious_ use cases, while simply masking out a "whole row" is a pretty obvious & clear case.

**Comment by mhvk** [comment]
@keflavich - I agree that the basic case should be a shared mask. I was really more worried about how to implement that, whether, e.g., one should then give all the coordinates just links to a shared mask, or whether they hold copies. And how does one ensure the sharing doesn't break or copies are kept up to date? Plus, of course, it may be that a `SkyCoord` also has an `obstime` - should that have masks as well? What happens if one passes in an `obstime` with masked values, while the coordinates have no masks? I'm probably overcomplicating things, but this certainly kept me from actually implementing it!

**Comment by keflavich** [comment]
@pllim is this a duplicate?  It seems that this issue discusses the use cases for and possible challenges with one of the checklist items in the other issue, so it's more detailed and specific.  But if you prefer to have fewer open issues, that's fine (I'm not sure what our "standard" is).

@mhvk OK, :scream: at the technical challenges there.  I agree, there are a lot of technical questions and unfortunately I don't know the answers.  I would naively think there needs to at least be a `SkyCoord.mask` attribute, but what that points to under the hood is unclear to me.  The simplest (again, naively) implementation would seem to be to have an optional `.mask` attribute that is an array the same shape as the `SkyCoord`, and accessing any underlying attribute (lon, lat, time) would then inherit that mask.  But... again, not sure how easy that is to do.

**Comment by mhvk** [comment]
@keflavich - nonetheless useful!

**Comment by pllim** [comment]
OK, will keep this issue but crosslink.

**Comment by taldcroft** [comment]
Mostly agreeing here with @mhvk, but I'll just throw in my 2c that I think the concept of masking for coordinate should be strictly the simplest possible interpretation. For a `SkyCoord` with some shape `(m, n, ..)` the mask for that object should have exactly that shape with no possibility for additional degrees of freedom representing the different attributes.

In one sense this is required, since you can change the representation from equatorial (2-components) to cartesian (3-components), so even the idea of masking `lon` is not well-defined. Hopefully keeping the mask to the simplest possible interpretation will help make the implementation *possible*, though still not *easy*.

As you said, accessing any attribute will inherit the mask, and on object creation any existing data/attribute masks would get `logical-or`'d together.

Overall I think astropy suffers some technical debt from too much flexibility. I'm guilty of this and now deal with the consequences... :smile:

**Comment by mhvk** [comment]
We can now have masked `SkyCoord` (#17016), so I'll close this issue - if it does not quite suffice, then it would probably be best to open a new one.
