### ISSUE TITLE
Some unicode unit representations are wrong when used in combinations

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#14403]
### Description

For example,
```Python
>>> import astropy.units as u
>>> print(f'{5*u.arcsec:unicode}')
5.0 ″
>>> print(f'{5*u.arcsec**2:unicode}')
5.0 ″²
```

For latex, this however works:
```Python
>>> import astropy.units as u
>>> print(f'{5*u.arcsec:latex}')
$5 \; \mathrm{{}^{\prime\prime}}$
>>> print(f'{5*u.arcsec**2:unicode}')
$5 \; \mathrm{arcsec^{2}}$
```

### Expected behavior

If used in combinations, unicode should switch to the longer forms, similarly to latex.
```Python
>>> import astropy.units as u
>>> print(f'{5*u.arcsec:unicode}')
5.0 ″
>>> print(f'{5*u.arcsec**2:unicode}')
5.0 arcsec²
```

**Comment by mhvk** [comment]
Darn! But I guess at least the solution is easy -- copy whatever we did for `latex`... see #9218. Though it is a bit trickier since it is less obvious which unicode symbols are OK -- things like Å² are obviously fine... One option might be to actually look at the `latex` representation and check whether that includes a superscript. Or just have a list of special cases (angles, electron, and perhaps deg C)...

p.s. For the angles, there really shouldn't be a space between the number and "unit". Sigh!
