### ISSUE TITLE
Models should support Quantity

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#1464]
I just noticed the following behavior:

```
In [1]: from astropy.modeling import models
In [2]: m = models.Linear1DModel(slope=1,intercept=0)
In [3]: m([1,2.] * u.m)
Out[3]: array([ 1.,  2.])
```

even though you give a `Quantity` in, a regular array comes out.

Also,

```
In [28]: m = models.Linear1DModel(slope=1,intercept=2 * u.m)
InputParameterError: Don't know how to convert parameter of <class 'astropy.units.quantity.Quantity'> to float
```

So even if I wanted to use quantities as the variable in the model, I can't do it because the parameters are forced to be a float.  

So it would be much more valuable if parameters could be a quantity where `q.isscalar == True`, and the varaible in the model can be any sort of quantity.

cc @nden @adrn @astrofrog

**Comment by astrofrog** [comment]
I don't think this will get resolved before 1.0, so removing milestone.

**Comment by embray** [comment]
:construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction::construction:
^Big line of barriers to make it easier to find the resumed discussion on this already quite long issue.

I'm working on this now and hope to have an early prototype soon.  Below I'm going to try to address some of the questions/comments from the earlier discussion on this issue.

One point I want to make early on is that the first prototype probably won't address every possible issue that one could raise with this, and that's fine.  I think the most important thing will be to get something working that can evaluate models with quantities.  I believe it will be important for Models to continue to work either with or without Quantities.  To be clear, if Quantities are used at all (that as, any one of the inputs or parameters have units) then it will be required that *all* inputs and parameters are Quantities (even if their unit is 'dimensionless')--this is necessary to have any hope for consistency.  Allowing both is important for at least three related reasons:

1) Backwards compatibility must be maintained.
2) Not all use cases call for Quantities.
3) For corner cases where Quantities don't immediately make sense to use, we can still fall back on purely numeric results.

**Comment by embray** [comment]
Okay, I'm going to respond to a few comments from the original discussion (before things got side-tracked) which I have now re-re-re-reviewed.  First up:

@mhvk in https://github.com/astropy/astropy/issues/1464#issuecomment-28583312

>> I know quantities support most math operations but within modeling/fitting it's much simpler to work with numbers.

> If so, I would consider it undesired behaviour in Quantity! My sense would be to approach it from the opposite end: convert both parameters and inputs to Quantity automatically; with that, outputs would automatically be Quantities too.

I'm still trying to figure out exactly what to do here.  I want to actually avoid using Quantity arithmetic for all evaluation of the models, as this could get unbearably slow for fitting.  On the other hand I also want to be able to determine the correct output units for some evaluation (where the required units haven't already been fixed), so I think it will also be necessary to pass the values as Quantities through the evaluate function to get the correct units.  Perhaps this could be the default for simple evaluation, while for fitting we can drop the units.  Note that in either case quantities will all be converted to the same set of base units for internal storage in the model's parameters array, so the arithmetic will work out correctly when calling the evaluate without units.  On the other hand, maybe I could go ahead and enable different storage mechanisms for different parameters.  For example, just keep each parameter internally as a Quantity to start with, but convert to the flattened array storage for fitting purposes.  That isn't my initial plan and is not something I've tried yet, but we could resort to that if the benefits are clear.

In short, there needs to be some balance found between keeping simple one-time evaluation efficient, and also making evaluation in loops efficient.  That will take some playing around.

In https://github.com/astropy/astropy/issues/1464#issuecomment-36147463

> I think your example of the Gaussian is a very good one, in that, yes, many models typically will have units, but, no, these will not be known until initialisation.

> For those types of models, I think the only sensible solution is to write them such that no conversion of quantity at all is done, i.e., if one initializes the Gaussian with a sigma with some unit, the user has to make sure the independent variable has the same unit. Since quantities now work just like numbers, this means the code for Gaussian would remain trivially simple. 

Some details aside, that's still the idea.  Little to nothing should have to be changed in the evaluate methods in order to support units.  While there are some things we'll be able to do in terms of validation, at the end of the day it will be up to users to make sure their inputs are consistent.  Maybe in the future we *could* add some additional constraints to parameters regarding units.  For example we could have some way of specifying (on Gaussian1D, for example) that we know a priori that the independent variable, mean, and stddev must all have the same (or compatible, up to equivalencies) units.  This won't be in the initial prototype though, unless it turns out to be more important than I think it will be.

**Comment by embray** [comment]
Responding to myself in https://github.com/astropy/astropy/issues/1464#issuecomment-28587050

> The only issue I have with this currently is that right now the Parameter class, while neither an array nor a number, does act as a proxy that encapsulates info about the parameter, but can still be used in expressions like an array or number. ... But you can't do something like `g.mean.mean()` because it does not proxy all of the ndarray methods or attributes.  `Parameter.value` gives direct access to the underlying data object. Maybe that would be sufficient for Quantities. If nothing else Parameter could maybe grow a unit attribute, or just use `default_unit` as @nden suggested.

It seems like this will work for all Quantity arithmetic now, so long as the Parameter has a `.unit` attribute.

And relatedly, to @eteq in https://github.com/astropy/astropy/issues/1464#issuecomment-36294109

> So I'm willing to accept @mhvk's idea of `QuantityParameter` or similar, but only if there's a clear reason why it won't work to just use `Quantity` all the time, by just auto-converting to a dimensionless `Quantity` if you do something like `Gaussian1D(amplitude=1, stddev=5, mean=6563)`. It seems like that addresses the problem of how to deal with something like polynomials - as long as the input is dimensionless (or a raw array), the output will be dimensionless. So then it seems like we get the best of both worlds.

Converting everything to dimensionless Quantities, in all cases, is a bit too much trouble, at least for now.  However, when all parameters are explicitly given as Quantities, it should be possible to use those parameters in any arithmetic with other Quantities (since the parameters will have .unit attributes).  It might not work *transparently* equivalently to a `Quantity` in all cases as it won't have all the ndarray methods.  But if we really want to we could maybe have it proxy any ndarray/Quantity methods where applicable.

**Comment by embray** [comment]
To @cdeil in https://github.com/astropy/astropy/issues/1464#issuecomment-36059110

> I'm not sure the API and / or implementation would simplify if quantities were used for those. E.g. we probably soon want to have covariance matrices to represent fit errors, and if some parameters have units and others don't or different parameters have different units, what type of object is the covariance matrix then?

Yes, if you need a covariance matrix that might be one of those cases where one should not use Quantities.  However, this might not be entirely meaningless.  As I responded to @mhvk above, all units will be converted to a common base (if possible--if not I'm not sure what the best action is) for fitting.  So for something like a covariance matrix we could have an auxiliary list somewhere specifying what units were used for each of the variables.

Somewhat beyond the scope of models+Quantities, but this leads me to think it might be useful to have some kind of array type in which each element can have its own unit.  This would not be terribly efficient or useful for vectorized operations, but it might be convenient just as a user interface.  This would not be entirely unlike an interface I've already been working on for working with Model parameters more conveniently, though I've set that work aside for now.

**Comment by embray** [comment]
And to @astrofrog in https://github.com/astropy/astropy/issues/1464#issuecomment-36521400

> The model requires a parameter in certain units - for example a position angle in degrees. Then when it defines the Parameter it can specify `unit=u.deg`, and when someone sets the parameter, whatever is passed, it is converted to a float value in degrees. If the model and the user access the parameter value differently, we can make it return the value for the model, and the quantity for the user.

This speaks to a point I've been struggling with a little bit.  Right now there are some models that require inputs in degrees (the namely the rotation models, and other models that have a rotation parameter like `Gaussian2D`.  There's nothing special about degrees in this example; it's just one that's already applicable to many models.  Right now, the models that require values in degrees will take just any array of floats and assume they have been correctly specified in degrees.  For the sake of backwards compatibility, I want to keep this functionality *for now*, at least on models that already use this.  However, in the long term, I want to change this so that if a model specifies `unit=u.degree` for some `Parameter`, then the user *must* supply a Quantity for that parameter, with units compatible with degrees.  It might also be important to specify on some parameters what base unit that parameter should be converted to for evaluation.  For degrees we might want to always store in radians, for example.  It may be necessary in some cases to make this explicit; not sure yet though.

> The model does not require a parameter in certain units - in that case, the `Parameter` class can just split up the value and the unit, and again when the model requests the value, the value is given, and when the user requests it, the quantity is returned.

Not always so simple.  If the model is supplied parameters in different, but equivalent units then we still need to convert them to common units before storing them away so that evaluation can proceed correctly.  But the original units could still be saved too, and returned to that unit when the user requests the parameter.

**Comment by mhvk** [comment]
@embray - great to see your thoughts!  Two answers and one comment:

> It seems like this will work for all Quantity arithmetic now, so long as the Parameter has a .unit attribute.

Yay to ducktyping!

> Somewhat beyond the scope of models+Quantities, but this leads me to think it might be useful to have some kind of array type in which each element can have its own unit.

Maybe just an `ndarray` with `dtype='O'? I know this is possible because annoyingly, currently,
```
In [2]: np.ma.array([1., 2.]) * u.m
Out[2]: 
masked_array(data = [<Quantity 1.0 m> <Quantity 2.0 m>],
             mask = False,
       fill_value = ?)
```

Finally, a comment on speed: with `__numpy_ufunc__`, speed differences will become substantially less since each calculation will just be done once (instead of twice, once with the wrong units, and once with the right ones).  But like you, I hope that in the end so much of the code can be agnostic about whether or not input is in quantities or in numbers that it will not be too hard to support both explicitly, in which case pure arrays can still be used for cases where speed is of the essence.

**Comment by embray** [comment]
@mhvk Yeah, an object array might be fine for that, actually.  I was still thinking it might be nice to have a special array subclass that, if nothing else, presents an array of mixed-unit Quantities more nicely (cut out all `<Quantity ...>` noise, so that you just have something like `[1.0 m, 2.0 m, 0.3 Jy]` or whatever.

**Comment by pllim** [comment]
@astrofrog ,  can we close this now?
