### ISSUE TITLE
`ndarray.__setitem__` allows `value` to have incompatible units if `item` is a slice

### ISSUE THREAD

**Issue by byrdie** [astropy/astropy#14706]
### Description

I would expect the following code to raise a `TypeError`, but it doesn't complain at all
```
In [1]: import numpy as np

In [2]: import astropy.units as u

In [3]: a = np.ones((2, 2))

In [4]: a[0] = 2 * u.mm

In [5]: a
Out[5]:
array([[2., 2.],
       [1., 1.]])
```
Is there anything we can do here, or does the problem lie with numpy?

### Versions

Windows-10-10.0.19044-SP0
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
astropy 5.3.dev663+g2b75ce84b8.d20230428
Numpy 1.24.1
pyerfa 2.0.0.1
Scipy 1.10.0
Matplotlib 3.6.3

**Comment by pllim** [comment]
This does not throw error too, so maybe more of a numpy issue than astropy? 🤷 

```python
a[0] = ('111', )
```

**Comment by eerovaher** [comment]
This problem is already [documented in the known issues page](https://docs.astropy.org/en/v5.2.2/known_issues.html#quantities-lose-their-units-with-some-operations). Furthermore, this issue is a duplicate of #7582, so unless something has changed recently in `numpy` I don't think there's too much left to discuss here.

**Comment by byrdie** [comment]
I was looking everywhere in the astropy.units documentation for that known issues page, because I knew I had read it several times before. Turns out it's one level up, in `index.html`. Thanks for pointing that out!
