### ISSUE TITLE
An Angle is a quantity, but viceversa is not True when unit is e.g. "deg"

### ISSUE THREAD

**Issue by HealthyPear** [astropy/astropy#14747]
### Description

See title :)

### Expected behavior

Probably there is a good deep reason why this doesn't happen, but I would expect that a quantity initialized with an angle unit is effectively an angle. 

### How to Reproduce

```python
import astropy.units as u
from astropy.units import Quantity
from astropy.coordinates import Angle

rotation = 5 * u.deg
isinstance(rotation, Angle) # this returns False

angle = Angle("5d")
isinstance(angle, Quantity) # this returns True
```

### Versions

macOS-11.7.6-x86_64-i386-64bit
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:55:37)
[Clang 14.0.6 ]
astropy 5.2
Numpy 1.24.0
pyerfa 2.0.0.1
Scipy 1.9.3
Matplotlib 3.6.2

**Comment by eerovaher** [comment]
Whether `5 * u.deg` should return a `Quantity` or an `Angle` was discussed is the pull request that made `Angle` a subclass of `Quantity`: #1006. The decision that  the return type should be `Quantity` instead of `Angle` was uncontroversial and is consistent with how `5 * u.m` returns a `Quantity` instead of a `Distance`.

What is your use case that requires your quantities to be `Angle` and not `Quantity` instances?

**Comment by HealthyPear** [comment]
Sorry, I completely forgot about this open issue.

I don't even remember why I opened it, but since it appears there was indeed a good reason behind this decision I'll live with it.
