### ISSUE TITLE
pre-commit check cannot see missing import

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15055]
pre-commit on the PR was green, and my editor hooked up to flake8 did not catch it anymore (it used to). What is going on here? This sounds like a bug in the pre-commit/ruff checks. I feel like we went overboard with such checks, making them so complicated that it is starting to fail because half the devs don't know how to read all the settings.

`E           NameError: name 'nullcontext' is not defined`

(The problem above is I forgot to add `from contextlib import nullcontext` but it was not caught until CI ran.)

@nstarman , @eerovaher , or @WilliamJamieson , do you know how to fix this in the settings?

**Comment by WilliamJamieson** [comment]
That should be an F821 error; however that has been turned off in both configurations (ruff and flake8).

I do not believe we have touched the flake8 configuration at all (on mobile so I cannot use blame meaning this is based on my memory). So this issue is likely the result of your editor now pulling the flake8 configuration from the project directory rather than an issue with the linting configuration. 

This being said why do we have F821 ignored? That seems a bit weird as the cases where this should be ignored should be rare.

**Comment by nstarman** [comment]
> I do not believe we have touched the flake8 configuration at all 

Sort of. Before we set up Ruff we first cleaned up the flake8 config because there were 2 sets of rules: ones that an editor might pick up, and the ones enforced by CI. When we cleaned up flake8 we opted to use the latter set of rules as that's what a _user_ actually saw. Later, Ruff was set up to exactly match the flake8 config. So if you are seeing a change it's not due to Ruff it's due to how we cleaned up flake8.
 
> This being said why do we have F821 ignored? That seems a bit weird as the cases where this should be ignored should be rare. 

I agree, we should in-ignore F821!
In both ruff and flake8.

**Comment by WilliamJamieson** [comment]
Ah I see, I forgot that the editor vs CI flake8 configs were different at first.

In any case, F821 shouldn't be too hard to enforce. Unless something is dynamically generated at runtime anything flagged by F821 should raise a NameSpace error when the code reaches it. This means it is likely the tests have gotten the majority of these errors already.

**Comment by WilliamJamieson** [comment]
I looked into the flake8 config and currently it is extremely out of sync with our current linting/formatting with ruff/black. This seems partially to do with the fmt on/off usage for black.

As a result running flake8 on our code seems to pick up a bunch of issues. We should probably run flake8 with the current config and resolve the errors it reports or drop support for it entirely. 

On a side note, I did find a few places where F821 errors are legitimate, but are apparently not visited by our tests.

Note that the main culprits for "invalid" F821 errors appear to be units (for unit symbols) and wcs (for keywords added directly by the C library). This is likely what prompted the ignoring of this error in the first place.
