### ISSUE TITLE
DOC: image is missing from docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#15080]
There is a code cell with plotting commands, yet the figure is missing from the docs:

https://docs.astropy.org/en/latest/io/fits/usage/cloud.html#using-cutout2d-with-cloud-hosted-fits-files

**Comment by saimn** [comment]
I remember some discussion about S3 credits, maybe that's the reason why those doctests are not run ?

**Comment by bsipocz** [comment]
Chose an image from the public AWS data (any hst would do), and then there are no S3 costs. It's just not exactly right to have a plot example but no figure, I don't think it's the approach anywhere else in the docs.

**Comment by pllim** [comment]
It is not really a bug as the doc was not written with any plot directive that would generate a plot. The snippets on that page also requires `fsspec` to be installed (which is fine since looks like RTD picks up `all` requirements anyway).

We already access the S3 bucket for doctest, so rendering the plot would incur one more call to that same bucket but from RTD. 🤞

**Comment by bsipocz** [comment]
it's a bug as there is an mpl example without the plot. To fix it, that part of the example could be removed, or a plot directive to be placed there, but a plot without a plot is a very much a bug... 🤷‍♀️

**Comment by pllim** [comment]
The solution then is to duplicate all that code but in a plot directive (without the `>>>`). AFAIK, plot directive and doctestplus are mutually exclusive.

**Comment by bsipocz** [comment]
yes, that is the way it's being done elsewhere in the docs. Or, showing the source with the plot directive. IMO, in this case it can be removed altogether, after all there are figures in the `Cutout2D` docs itself.
