### ISSUE TITLE
Add remove-star pre-commit

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#15270]
### What is the problem this feature will solve?

Ensure only `__init__.py` files have `import *`

### Describe the desired outcome

Enforce this with pre-commit.

I opened an issue in the repo https://github.com/asmeurer/removestar/issues/33 asking if this tool could add a pre-commit hook. Unfortunately this repo is not actively maintained. Thankfully someone noticed my issue and forked the
repo — https://github.com/Saransh-cpp/rmstar/ — and is working on a pre-commit hook.
When it's ready we should add it to pre-commit.

### Additional context

Adding / removing from pre-commit is very easy and if something breaks it only affects CI, not the actual code, so the stakes are low to add hooks.

**Comment by MridulS** [comment]
(let me know if I should open a new issue instead of using this closed one)

The removestar pre-commit takes a non-trivial amount of time (atleast compared to ruff) to run the linting locally with `tox -e codestyle` and I'm not sure why not just use the [ruff F403 lint rule](https://docs.astral.sh/ruff/rules/undefined-local-with-import-star/) help catch these cases?

**Comment by neutrinoceros** [comment]
note that ruff doesn't have an auto-fix for F403, which might be the initial reason for using a (slow) specialised tool instead. My concern is that there are still 150+ occurrences of `import *` in the codebase now so I don't get what `removestar` is actually doing.

**Comment by eerovaher** [comment]
The tooling is only meant to prevent `import *` occurrences outside `__init__.py` files.

`removestar` is convenient in the case when a new `import *` statement is added (outside a `__init__.py` file) because it can automatically replace it, but in practice it seems that this does not happen frequently enough to justify slowing down our `pre-commit` checks. I wouldn't mind removing this hook. Ruff will still guard against F403 violations.

**Comment by pllim** [comment]
> I wouldn't mind removing this hook. Ruff will still guard against F403 violations.

Okay, let's remove it then. I am no good with ruff stuff, so any of you interested?
