### ISSUE TITLE
TST: s390x and ppc64le jobs fail to pull in numpy on v5.3.x

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#15289]
Example log: https://github.com/astropy/astropy/actions/runs/6110923286/job/16585031743

It should have grabbed a wheel but didn't. Maybe because NumPy stopped shipping wheels for these archs? Do we care for v5.3.x? I milestoned this issue so we remember to close it if we don't get to fixing it before we drop v5.3.x support altogether.

```
        Collecting numpy<2,>=1.25
          Downloading numpy-1.25.2.tar.gz (10.8 MB)
```

**Comment by mhvk** [comment]
On those architectures, we download numpy from the ubuntu repositories using `apt` (mostly to make things faster, but also to ensure that one can do things without getting duplications of everything with `pip`). I think the problem is that we insist that `numpy>=1.25`, which is probably not on the repositories. Is there a reason we require `numpy>=1.25` rather than just the minimum supported version?

**Comment by pllim** [comment]
But then again, why don't we have the same problem on `main`?

https://github.com/astropy/astropy/actions/runs/6069740149

**Comment by pllim** [comment]
Ah, looks like v5.3.x uses `distro: ubuntu_latest` but main uses `distro: ubuntu_rolling`.

So, what is the preferred solution here? We update the workflow with rolling distro or reintroduce `oldest-supported-numpy`?

**Comment by WilliamJamieson** [comment]
I had to switch to `ubuntu_rolling` on main so that we could get pre-built versions of `numpy >= 1.22`. `ubuntu_latest` does not have these.

**Comment by pllim** [comment]
Superseded by #15351
