### ISSUE TITLE
Angular/Sphere distance for measuring the separation of SkyCoord

### ISSUE THREAD

**Issue by datajungler** [astropy/astropy#15518]
### What is the problem this feature will solve?

Haversine is one of the formula to quantify the separation. Meanwhile, I just noticed a post from Stackoverflow that someone mentioned this formula to tackle the performance issue of separation method.
(reference link: https://stackoverflow.com/questions/71506875/faster-alternative-to-skycoord-separation)

As a package novice, I would like to attempt to integrate this into the `coordinates` package if it is worth including. Thank you.

### Describe the desired outcome

A new method to derive the angular distance between two points on a sphere given longitude and latitude coordinates

**Comment by pllim** [comment]
Thank you for the suggestion.

First of all, if someone is serious in pursuing this, I would like to see some benchmarks (a few data points vs a few million).

Secondly, https://github.com/pydata/numexpr is yet another dependency. In fact, it is currently asking for people to volunteer to keep maintaining it, so very unlikely any code that requires it will run without people installing this package separately because `astropy` will probably not make it a required dependency.

That said, nothing stops you from using it downstream yourselves without touching `astropy`.

**Comment by eerovaher** [comment]
I agree with what @pllim has already said. The function on Stackoverflow was posted by @taldcroft, maybe he has something to add.

**Comment by datajungler** [comment]
I understand your all concern. Instead of relying solely on `numpexr`, it would be beneficial to consider creating an additional method that utilizes the `numpy` package to calculate the sphere distance with haversine formula between the two coordinates on a sphere. This might provide an alternative to derive the distance besides the method of angular `separation` and `position angle` from the package of `coordinates`.

**Comment by eerovaher** [comment]
`astropy` used to provide implementations of the haversine formula, but they were removed in #1397. If you want to reintroduce it then you will have explain why that pull request should be reconsidered.

**Comment by datajungler** [comment]
Thank you for bringing this to my attention.

Upon reviewing the historical issues, I discovered that there have been extensive discussions regarding the performance of the separation in the open issue #3908. As a result, I am closing this duplicate issue.
