### ISSUE TITLE
FLRW.luminosity_distance returns unexpected type

### ISSUE THREAD

**Issue by mj-will** [astropy/astropy#15576]
### Description

When calling `FLRM.luminosity_distance` with an instance of `pandas.Series` as the input, the output is another `pandas.Series` rather than an instance of `astropy.units.Quantity`. This is inconsistent with other similar methods, such as `comoving_distance` or `comoving_volume`.

### Expected behavior

`FLRM.luminosity_distance` should return an instance of `astropy.units.Quantity`.

### How to Reproduce

1. Install `astropy`, `scipy` and `pandas` using `conda`
2. Run the code snippet below and check the types of the outputs

```python
from astropy.cosmology import WMAP9 as cosmo
import pandas as pd
z = pd.Series([1, 2])
dl = cosmo.luminosity_distance(z)
print(type(dl))
dc = cosmo.comoving_distance(z)
print(type(dc))
vc = cosmo.comoving_volume(z)
print(type(vc))
```

On my system, this outputs

```
<class 'pandas.core.series.Series'>
<class 'astropy.units.quantity.Quantity'>
<class 'astropy.units.quantity.Quantity'>
```

### Versions

```
Linux-3.10.0-1160.71.1.el7.x86_64-x86_64-with-glibc2.17
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
astropy 5.3.4
Numpy 1.26.0
pyerfa 2.0.0.1
Scipy 1.11.3
# Matplotlib is not installed
```

**Comment by pllim** [comment]
@nstarman , is this behavior intentional? Please advise. Thanks!

**Comment by nstarman** [comment]
This is an issue. But it actually an issue for units. @mhvk might want to see this as well.
The problem is that a Pandas Series * Quantity does not return a Quantity!

```python
>>> import pandas as pd
>>> import astropy.units as u

>>> z = pd.Series([1, 2])
>>> d = u.Quantity([10, 20], u.Mpc)

>>> z * d
0    10.0
1    40.0
dtype: float64
```

**Comment by nstarman** [comment]
I found https://github.com/astropy/astropy/issues/11247, so this is a known problem.
We could change `aszarr`
https://github.com/astropy/astropy/blob/e42dfc0b16b4b53fbcea793957d369e3b26a1954/astropy/cosmology/_utils.py#L72-L75
to check for pandas and convert to numpy?

**Comment by nstarman** [comment]
But the more optimal solution would be to have `Quantity` correctly handle interactions with Pandas.

**Comment by mhvk** [comment]
See my comment in the earlier issue: https://github.com/astropy/astropy/issues/11247#issuecomment-759742700
We cannot change the fact that `Series * unit` does not work because our code is never called -- that really needs a change in pandas... Given that that very basic way of converting `Series` into a `Quantity` cannot be made to work, I don't see much point in changing `Quantity` at all -- as is, the initializer works properly.

Obviously, one can make changes to specific methods in cosmology if you wish - in a way, the problem here is that in trying to get better performance, one skips making `Quantity` and therefore passes in `Series` where they do not belong. You could also add something like `np.asanyarray` and be done with it, but then of course you also prevent well-behaved duck-types from working (if any exist, not sure! maybe dask array these days?).

Anyway, my bottom-line suggestion would be to raise an issue with pandas.

**Comment by nstarman** [comment]
> We cannot change the fact that Series * unit does not work because our code is never called

The issue here is not ``Series * unit``, which I agree is problematic but we cannot address, but ``Quantity * Series``, which we can!

```python
class Quantity:

    def __mul__(self, other):
        if other.__module__.startswith("pandas"):  # no pandas dependency
            return self * np.array(other)  # now we get a Quantity
```

**Comment by mhvk** [comment]
I guess we can do that in principle deeper inside, in `__array_ufunc__`, perhaps by looking for an `__array__` method. But it should be in a `try/except`, with the check in the `except` part - there shouldn't be any performance regressions for this!

**Comment by pllim** [comment]
Rather than patching Quantity, which as you stated, is a separate issue and requires upstream fix, is it possible to apply a more hacky but local patch just for that cosmology API? Then in the other larger issue, we can add a reminder to undo the cosmology one when/if we ever get to it.

**Comment by nstarman** [comment]
Yeah. In `aszarr` which processes each input we can do essentially the same thing I suggested for `Quantity`. I can push a PR soon.
