### ISSUE TITLE
Re-enable RTD beta add-on option when we can (was: Documentation warnings missing from RTD)

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#15695]
### Description

I have found three examples where documentation warning sections `.. warning::` are just not there. I'm going to guess they are all missing. For example https://github.com/astropy/astropy/blob/b7fa097273a10ac1bb0353618fa1e88da9d4a093/docs/coordinates/inplace.rst?plain=1#L36.

Compare to: https://docs.astropy.org/en/stable/coordinates/inplace.html

### Expected behavior

The sphinx docs should include warnings and other admonitions.

**Comment by taldcroft** [comment]
If I build the docs locally (`tox -e build_docs`) then the warnings are there as expected. Weird. I note also in the published HTML docs, the text from the warnings is not in the HTML. Meaning I inspected the source and grepped (so it is not just hidden due to some JS funny).

**Comment by pllim** [comment]
I tried turning off analytics and turning off version warning banner (separate efforts) and none of those helped. Not sure what else I can tweak on the RTD admin panel. Given that local builds work, I am hesitant to touch the actual docs settings. Looking at the HTML page source of the problematic RTD builds, the warning was not rendered at all (as opposed to rendered into HTML but failed to show). Maybe this is something ReadTheDocs people need to fix, @humitos? 🙏 

What is even more weird is that the warning shows fine on RTD in a different project: https://jdaviz.readthedocs.io/en/latest/

ref: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/notes_warnings.html

**Comment by pllim** [comment]
@astrofrog , as Tom A said in https://github.com/astropy/astropy/issues/15695#issuecomment-1847202271 , it was already a problem with the old theme. So I don't think theme is the problem here. I suspect it is some RTD add-ons that they are injecting on their server-side that we have no control over.

**Comment by pllim** [comment]
We might have to deploy doc build on CircleCI and inspect the artifacts here (like the images but now docs) to prove to RTD that it is them and not us.

**Comment by bsipocz** [comment]
FWIW astroquery and photutls too have the warnings, both in narrative docs and docstrings. I haven't yet had the time to switch over the theme, but it should not be an issue as e.g. sunpy still has the warning while it has its theme updated

https://astroquery.readthedocs.io/en/latest/esa/hubble/hubble.html#getting-hubble-products
https://photutils.readthedocs.io/en/stable/api/photutils.detection.DAOStarFinder.html#photutils.detection.DAOStarFinder
https://docs.sunpy.org/en/stable/tutorial/timeseries.html#inspecting-timeseries-metadata

**Comment by agjohnson** [comment]
It's not quite clear what exactly happening here, but just to clear up a few points to help you narrow this down:

> It looks like RTD (or somebody) is rebuilding old documentation versions

This does not look to be the case. The page you linked has not been updated in our storage since 2021, for both 4.2.1/4.3.1/4.2.x versions.

> We might have to deploy doc build on CircleCI and inspect the artifacts there

Your later versions have the feature disabled, but at least the 4.x releases expose the reST sources already:

- https://docs.astropy.org/en/v4.2.x/_sources/coordinates/inplace.rst.txt
- https://docs.astropy.org/en/v4.3.1/_sources/coordinates/inplace.rst.txt

> I note also in the published HTML docs, the text from the warnings is not in the HTML. Meaning I inspected the online RTD source and grepped (so it is not just hidden due to some JS funny).

This does seem missing from the HTML, but the `warning` admonition is in the source file above.

So far, this is pointing to Sphinx/docutils not rendering the admonition for some reason.

> So I don't think theme is the problem here.

I don't think the theme would be the problem here either. I would expect some signs of the HTML in the output even if the theme was not styling the elements. However, indirectly, any of the extensions or customizations in the Sphinx theme could be a culprit.

>  I suspect it is some RTD add-ons that they are injecting on their server-side that we have no control over.

Our addons do not alter admonitions or page body contents outside some additions at the end of the body. You can test this by disabling JS, you should still not see the admonition with JS disabled.

> If I build the docs locally (tox -e build_docs) then the warnings are there as expected.

A couple things to try:

- Ensure that you are installing the exact same versions locally as the RTD build. The RTD builds do not use Tox, though I didn't inspect the versions installed. You can compare the dependencies installed on the builds.
- There are a few extensions that could all be influencing the build, I would probably bet one of these are incompatible or maybe defined with differing versions.

Sorry I don't have more guidance for you yet, but perhaps experimenting with your dependencies will help surface the problem.

**Comment by humitos** [comment]
I read the thread here and I don't have anything else to add to what @agjohnson said. I guess this is probably a mismatch on the versions installed locally than on Read the Docs as he pointed out.

> You can test this by disabling JS, you should still not see the admonition with JS disabled.

This is a good test as well, since everything that Read the Docs modifies happens on the client side (since you have the new addons enabled).

**Comment by pllim** [comment]
> You can test this by disabling JS

@agjohnson or @humitos , is disabling JS an option on the RTD admin panel? Can you please clarify? When I looked at the admin panel last week, I didn't see any "disable JS" toggle but maybe I missed it. Thank you for your help.

**Comment by agjohnson** [comment]
Sorry, to clarify I meant disable JS on your browser to debug. You can do this with uBlock origin and other tools or browser settings. Either way, the JS wouldn't be interfering with the output here, there must be something happening at the output step instead. The most common problem is differences in dependency versions, I would start there.

**Comment by pllim** [comment]
Since the actual HTML source does not have that warning text at all, I also think it isn't the JS on my browser. I will compare versions when I get the chance. Thanks for the guidance!

**Comment by pllim** [comment]
For the record, this is the warning reported in original post rendered into HTML. I see it locally:

```html
<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>You <em>must</em> include the step to clear the cache as shown. Failing to do so
will cause the object to be inconsistent and likely result in incorrect
results. <a class="reference internal" href="../api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord" title="astropy.coordinates.SkyCoord"><code class="xref py py-obj docutils literal notranslate"><span class="pre">SkyCoord</span></code></a>
and <a class="reference internal" href="../api/astropy.coordinates.BaseCoordinateFrame.html#astropy.coordinates.BaseCoordinateFrame" title="astropy.coordinates.BaseCoordinateFrame"><code class="xref py py-obj docutils literal notranslate"><span class="pre">BaseCoordinateFrame</span></code></a> cache various kinds of
information for performance reasons, so you need clear the cache so that
the new representation values are used when required.</p>
</div>
```

![Screenshot 2023-12-13 143128](https://github.com/astropy/astropy/assets/2090236/310df849-4075-4462-8323-4265a8b51886)

**Comment by pllim** [comment]
So, I think it is one of them beta add-ons. I disabled beta add-ons for `astropy` and rebuilt RTD. The warning now appears:

https://docs.astropy.org/en/latest/coordinates/inplace.html

Locally, I tried to bump versions to match what RTD has, and unable to reproduce the problem. (But it is not a completely identical env.)

**Comment by agjohnson** [comment]
Ooookay, I think I understand what is happening here now. I took a deeper look into the code here and this is not a bug with addons, but with how addons are injected.

We perform injection of the addons with a Cloudflare worker, which removes features and JS that would have previously been injected by our build process. One of these features is the version warning. The selector used to remove these warning is far too loose and could select and remove your warning admonitions.

This explains everything, and why disabling JS didn't resolve anything. We'll need to patch the worker code to resolve this, @humitos has a better idea of what needs to happen there though.

Sorry to send you off in the wrong direction. If I come up with a workaround before we can patch things, I'll also let you know here.

**Comment by pllim** [comment]
Thanks for the clarification! I will be happy to re-enable the beta add-ons to help you test as needed, but for now, I have disabled it.

**Comment by agjohnson** [comment]
I (hopefully) put in a temporary fix, just skipping this logic for your project. If you enable addons, you should immediately (give or take a cache timeout) notice addons working and your warning admonitions should not disappear. No rebuild should be required.

**Comment by pllim** [comment]
Thanks for the quick fix and the update! I'll give it a try tomorrow.

**Comment by pllim** [comment]
Update: OK, I re-enabled the beta add-on. How do I know if I am looking at the old cache or the new stuff? 🤔

**Comment by humitos** [comment]
@pllim thanks a lot for all your help and your feedback here! 🙏🏼 

@agjohnson thanks for debugging this bug and deploying a quick fix 🚀 


> How do I know if I am looking at the old cache or the new stuff?

This can be done by inspecting the HTTP header `Age` in the response [^1]:

```
$ curl -IL -s 'https://docs.astropy.org/en/latest/coordinates/inplace.html' | grep -i age
age: 238
cache-control: max-age=1200
```

That means that we are showing a page from 238s ago.

[^1]: you can check the same HTTP header from the browser itself if you want. In Firefox, this is: F12 -> Network -> Click on the `inplace.html` file -> Age header is shown at the right under "Response Headers"

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy/issues/15695#issuecomment-1857568732

Mine says "175" so I think we good?

**Comment by pllim** [comment]
Thanks everyone! Now warning shows, search works, and beta add-ons still enabled. 👏
