### ISSUE TITLE
Missing fits attribute in astropy.io

### ISSUE THREAD

**Issue by divenex** [astropy/astropy#15720]
### Description

    from astropy import io
    t = io.fits.open('test.fits')

raises an error

> AttributeError: module 'astropy.io' has no attribute 'fits'

Loading the unrelated `cosmology` folder as follows fixes the error

    from astropy import io, cosmology
    t = io.fits.open('test.fits')

loads the `fits` file as expected.

### Versions

Python 3.11.6
AstroPy version  3.8.2

**Comment by saimn** [comment]
`io` doesn't import its subpackages (to avoid increasing import time) so it's normal that `from astropy import io` doesn't give access to `io.fits` or `io.ascii` etc. 
Importing `cosmology` "fixes" that because it imports the io registry which imports many subpackages, but you should not rely on that. So as mentioned by @neutrinoceros you should use `from astropy.io import fits`.

**Comment by divenex** [comment]
Thanks @saimn and @neutrinoceros for the explanations. I was aware of the usual `from astropy.io import fits`, but not about `io` not importing subpackages.
