### ISSUE TITLE
Popup label for "stable/latest" docs makes documentation unbrowsable for other versions

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#15928]
### Description

See reports on [Slack#docs](https://astropy.slack.com/archives/C01UHS62TMW/p1701891601640329).
The warning label popping up when browsing anything but the current stable version (including in particular the Developer docs which exist only in `latest`) of the Astropy docs is annoying and making those versions rather unnavigable as the popup appears on loading or reloading every single page, and dismissing it reloads at the top of the page, losing any section links one may have been following.

### Expected behavior

Ideally the popup should not reappear all the time while browsing a given version, especially one that does not exist in `stable`. Short of that dismissing it should not lose section or topic anchors in the URL.

### How to Reproduce

Open https://docs.astropy.org/en/latest/development/workflow/development_workflow.html#pre-commit

### Versions

Safari 17.2.1, Firefox 121.0.1

**Comment by pllim** [comment]
I think I can disable this, if that is what everyone wants. It is not a bug.

**Comment by dhomeier** [comment]
The label as such is certainly useful, but with the current behaviour it's probably more trouble than help.

**Comment by tactipus** [comment]
It's not a bug. Since this is a feature on the web app, I'm not sure how I would be able to contribute directly.

**Comment by pllim** [comment]
Only RTD admin can do this, unfortunately, so outside help is not possible.

**Comment by pllim** [comment]
That didn't work. Trying again but from Beta dashboard.

<img width="543" alt="Screenshot 2024-01-23 124847" src="https://github.com/astropy/astropy/assets/2090236/bdddf59d-229f-4ee9-9621-af44cc0aee0b">

**Comment by dhomeier** [comment]
What is this dashboard? Might there be anything that could be configured in `conf.py`?

**Comment by pllim** [comment]
AFAIK the banner stuff was never exposed as YAML setting but maybe @humitos can confirm.

**Comment by pllim** [comment]
Huh, still pops up for me. I wonder if my browser is refusing fresh reload.

https://astropy.readthedocs.io/en/latest/

**Comment by humitos** [comment]
I will reply to each comment:

* The option changed in https://github.com/astropy/astropy/issues/15928#issuecomment-1906557534 is "broken" and deprecated. It's only available for projects that were using it before and it's not shown to the rest of projects. Besides, it incompatible with the beta addons.
* This page was _just deployed_ (I'm impress you already found it): https://github.com/astropy/astropy/issues/15928#issuecomment-1906607251. Prior today, users were able to enable/disable _all the addons_ at the same time. Starting with today's deploy, they can enable/disable each particular addon. We are going to improve that page and add more options in the future.
* We don't plan to make this options configurable via the YAML since they are per-project settings, instead of per-version: https://github.com/astropy/astropy/issues/15928#issuecomment-1906618050
* I don't see any notification when loading Astropy docs now: https://github.com/astropy/astropy/issues/15928#issuecomment-1906623380

Thanks a lot for all the feedback 🙏🏼 and let me know if things are working as expected.
