### ISSUE TITLE
DEPR: should we deprecate `astropy.utils.console.terminal_size` ?

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16042]
This function was added in https://github.com/astropy/astropy/pull/2878, and first released in astropy 1.0 (feb 2015)
At the time, it made perfect sense to ship our own function for this, since Python 2 was still supported, and `os.get_terminal_size` was never fully portable (to this day, it only supports UNIX and Windows).

However, there's been an equally portable function in the standard lib since Python 3.3: https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size

While not a 1:1 replacement (`shutil.get_terminal_size` doesn't have a `file` argument), I note that `console.terminal_size` is very rarely used internally (only twice, one of which is a test !), so I think it'd make sense to just deprecate it. Thoughts ?

**Comment by pllim** [comment]
Hmm weird that `file=` was implemented but we don't actually use it. Since this would affect `Table`, I would like to see if there are objections from `astropy.table` maintainers: @taldcroft and @mhvk 

If no objection, maybe open a draft PR to deprecate it. @saimn , should such deprecation happen in v6.1 or v7.0 given how long it has already existed?

Personally, I am fine with deprecating this, especially if Python standard library already gives something similar now. Thanks for bringing this up!

**Comment by mhvk** [comment]
Looks to me like it can be deprecated indeed - the `file` argument seems used only in a context where one is resizing, so clearly connected to a real terminal.

**Comment by saimn** [comment]
>  should such deprecation happen in v6.1 or v7.0 given how long it has already existed?

6.1 is fine, the question is more when to remove it and actually break things.
