### ISSUE TITLE
Coordinate transform graph not following expected path

### ISSUE THREAD

**Issue by Joshuaalbert** [astropy/astropy#16317]
### Description

I've defined an `ENU` frame as below, as a simple axes permutation and relabelling of `AltAz` axes. The transforms defined are `ENU->AltAz`, `AltAz->ENU`, and `ENU->ENU` (via intermediate an `AltAz`). Unittests show that it obeys all the expected rules of ENU. However, a problem arise in transforming to `ITRS`, in that doing `ENU->ITRS` gives different results than `ENU->AltAz->ITRS`. Though it one case they are they same (when the observing location is the north pole and units are dimensionless).

### Expected behavior

Since all paths to and from `ENU` are defined via `AltAz` they should be equivalent. Furthermore, the result from `ENU->AltAz->ITRS` is correct, while `ENU->ITRS` is incorrect. Code below.

### How to Reproduce

Define ENU as follows:

```python
from __future__ import (absolute_import, unicode_literals, division, print_function)

from astropy.coordinates import AltAz
from astropy.coordinates.attributes import (TimeAttribute, EarthLocationAttribute)
from astropy.coordinates.baseframe import (BaseCoordinateFrame, RepresentationMapping, frame_transform_graph)
from astropy.coordinates.representation import (CartesianRepresentation)
from astropy.coordinates.transformations import FunctionTransform


class ENU(BaseCoordinateFrame):

    frame_specific_representation_info = {
        'cartesian': [RepresentationMapping('x', 'east'),
                      RepresentationMapping('y', 'north'),
                      RepresentationMapping('z', 'up')],
    }

    default_representation = CartesianRepresentation

    obstime = TimeAttribute(default=None)
    location = EarthLocationAttribute(default=None)


@frame_transform_graph.transform(FunctionTransform, AltAz, ENU)
def altaz_to_enu(altaz_coo: AltAz, enu_frame: ENU):
    '''Defines the transformation between AltAz and the ENU frame.
    AltAz usually has units attached but ENU does not require units
    if it specifies a direction.'''
    rep = CartesianRepresentation(x=altaz_coo.cartesian.y,
                                  y=altaz_coo.cartesian.x,
                                  z=altaz_coo.cartesian.z,
                                  copy=False)
    return enu_frame.realize_frame(rep)


@frame_transform_graph.transform(FunctionTransform, ENU, AltAz)
def enu_to_altaz(enu_coo: ENU, altaz_frame: AltAz):
    rep = CartesianRepresentation(x=enu_coo.north,
                                  y=enu_coo.east,
                                  z=enu_coo.up,
                                  copy=False)
    return altaz_frame.realize_frame(rep)


@frame_transform_graph.transform(FunctionTransform, ENU, ENU)
def enu_to_enu(from_coo: ENU, to_frame: ENU):
    # To convert from ENU at one location and time to ENU at another location and time, we go through AltAz
    return from_coo.transform_to(AltAz(location=from_coo.location, obstime=from_coo.obstime)).transform_to(to_frame)
```

You can see the full set of unittests here: https://gist.github.com/Joshuaalbert/1ce82625de6a7b4ef95595a01ac70463

Here is the test that fails in all cases  **except it passes when array_centre is the North Pole and units are dimensionless**.

```python
import numpy as np
import pytest
from astropy import time as at, coordinates as ac, units as au

@pytest.mark.parametrize("array_centre", [
    ac.EarthLocation.from_geodetic(lon=0. * au.deg, lat=0. * au.deg, height=0. * au.m),  # Centre of the Earth
    ac.EarthLocation.from_geodetic(lon=0. * au.deg, lat=90. * au.deg, height=0. * au.m),  # North Pole
    ac.EarthLocation.from_geodetic(lon=0. * au.deg, lat=-90. * au.deg, height=0. * au.m),  # South Pole
])
@pytest.mark.parametrize("unit", [au.dimensionless_unscaled, au.km])
def test_enu_to_itrs(array_centre: ac.EarthLocation, unit: au.Unit):
    obstime = at.Time("2019-03-19T19:58:14.9", format='isot')

    # Test Zenith direction
    zenith_altaz = ac.AltAz(az=0. * au.deg, alt=90. * au.deg, distance=1 * unit, location=array_centre, obstime=obstime)
    zenith_enus = zenith_altaz.transform_to(ENU(location=array_centre, obstime=obstime))
    zenith_itrs = zenith_enus.transform_to(ac.ITRS(obstime=obstime))
    zenith_via_altaz = zenith_altaz.transform_to(ac.ITRS(obstime=obstime))

    print(zenith_itrs)
    print(zenith_via_altaz)

    np.testing.assert_allclose(zenith_itrs.cartesian.xyz, zenith_via_altaz.cartesian.xyz, atol=1e-6)

```

### Versions

```
Linux-5.15.0-100-generic-x86_64-with-glibc2.31
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
astropy 5.2.2
Numpy 1.24.2
pyerfa 2.0.0.3
Scipy 1.10.1
Matplotlib 3.7.1
```

**Comment by neutrinoceros** [comment]
Thanks a lot for reporting and for providing such a complete reproducer.
I note that I needed a couple edits to be able to run it on my machine:
1. The test is missing a couple import statements, namely
```python
import pytest
from astropy import coordinates as ac
from astropy import units as au
from astropy import time as at
import numpy as np
```
2. There's an indentation error in the class definition for `ENU`: removing one leading space from the first line (`frame_specific_representation_info = {`) fixes it
3. if run within astropy's directory, the test needs the following decorator, and should be run with `pytest --remote-data=any`
```python
@pytest.mark.remote_data
```


Could you edit the description and apply the first to changes so it's easier for others to process ? (the third one isn't necessary since it's context-dependent)

With all these, I'm able to reproduce locally with astropy 7.0dev, so supposedly there hasn't been any relevant changes since v5.2.2 (used in the report).

**Comment by Joshuaalbert** [comment]
fixed

**Comment by ayshih** [comment]
I haven't reviewed your code closely, but most likely the discrepancy is because you are not transforming using `SkyCoord`.  `SkyCoord` propagates frame attributes across intermediate frames, while calling `.transform_to()` on the lower-level frame classes does not.  `SkyCoord` is the interface that users are recommended to use.

**Comment by Joshuaalbert** [comment]
@ayshih Thanks for the explanation. Regarding using SkyCoord: I prefer explicit typing in my code, as Python coding convention is moving more toward stronger typing. It make code more readable, and also there are even cases where instance checking relies upon having specific types. I wonder is there a specific reason why that design choice was made?

**Comment by ayshih** [comment]
Someone like @mhvk can speak about the design choice, but I think of it this way... A `Quantity` is the combination of a number and a unit, and is not an instance of either.  Similarly, a `SkyCoord` is – conceptually – the combination of a coordinate representation (a subclass of `BaseRepresentation`) and a coordinate frame (a subclass of `BaseCoordinateFrame`), and is not an instance of either.  The fact that the *implementation* of `BaseCoordinateFrame` allows an instance of coordinate frame to also contain coordinate data is more for performance reasons rather than something that makes conceptual sense.

In your specific case, the bug in your code is that your `ENU`<->`AltAz` transformation functions ignore the possibility that the `location` frame attribute may not be the same on the two ends of the transformation.  What you need to do is to transform through an internal intermediate frame to properly trigger the `AltAz`->`AltAz` loopback transformation, along the lines of this:
```python
@frame_transform_graph.transform(FunctionTransform, AltAz, ENU)
def altaz_to_enu(altaz_coo: AltAz, enu_frame: ENU):
    intermediate_altaz_coo = altaz_coo.transform_to(intermediate_altaz_frame)
    return enu_frame.realize_frame(intermediate_altaz_coo.data)

@frame_transform_graph.transform(FunctionTransform, ENU, AltAz)
def enu_to_altaz(enu_coo: ENU, altaz_frame: AltAz):
    intermediate_altaz_frame = AltAz(location=enu_coo.location, obstime=enu_coo.obstime)
    intermediate_altaz_coo = intermediate_altaz_frame.realize_frame(enu_coo.data)
    return intermediate_altaz_coo.transform_to(altaz_frame)
```

**Comment by mhvk** [comment]
It sounds like it no longer quite relevant, but indeed `SkyCoord` is a container, and we do greatly encourage using it. It is a bit  sad if something as supposedly informational-only like typing is keeping people from that! Note that there is a bit of an effort underway to type astropy itself, so eventually we may have some version of `SkyCoord[ICRS]`, etc.

Note that arguably I think it would indeed be more logical if `SkyCoord`t held the representation and the frame only defined their origin and orientation - having frames both with and without data has always felt rather wrong to me... Anyway, that is even less relevant here (though it makes me realize that if one were to change it, all those transformations would have to be rewritten...).

**Comment by Joshuaalbert** [comment]
Thanks for the explanations both, and I definitely understand the ire of wishing people to use your code as intended. Regarding any planning to type the code, I super strongly support it. It will increase the efficiency of development of astronomical software. And from experience when there is some peculiarity that suggests typing is hard to do it often means a better pattern could have been followed. In your case bounded generics will do the trick. And I think they are fairly common in python code. Regarding the big effort to rewrite code, I think such things should happen rarely and with good reason. Making code more maintainable and increasing the efficiency of the use of your code is a big enough reason in my opinion. A good discussion of what other changes should happen at the same time is always helpful.

**Comment by Joshuaalbert** [comment]
@ayshih getting a failing unittest.

```python
@pytest.mark.parametrize("array_centre", [
    ac.EarthLocation.from_geodetic(lon=0. * au.deg, lat=0. * au.deg, height=0. * au.m),  # Centre of the Earth
    ac.EarthLocation.from_geodetic(lon=0. * au.deg, lat=90. * au.deg, height=0. * au.m),  # North Pole
    ac.EarthLocation.from_geodetic(lon=0. * au.deg, lat=-90. * au.deg, height=0. * au.m),  # South Pole
])
@pytest.mark.parametrize("unit", [au.dimensionless_unscaled, au.km])
def test_enu_of_array_centre_should_be_zero(array_centre: ac.EarthLocation, unit: au.Unit):
    obstime = at.Time("2019-03-19T19:58:14.9", format='isot')
    enu_frame = ENU(obstime=obstime, location=array_centre)
    array_centre_enu = array_centre.get_itrs(obstime=obstime).transform_to(enu_frame)
    print(array_centre_enu)
    np.testing.assert_allclose(array_centre_enu.east, 0. * unit, atol=1e-6)
    np.testing.assert_allclose(array_centre_enu.north, 0. * unit, atol=1e-6)
    np.testing.assert_allclose(array_centre_enu.up, 0. * unit, atol=1e-6)
```

For example this prints out: `<ENU Coordinate (obstime=2019-03-19T19:58:14.900, location=(6378137., 0., 0.) m): (east, north, up) in m    (-281.48124226, 252.85840771, -0.04156678)>`. I would expect the array centre to be the origin

**Comment by ayshih** [comment]
So, you've encountered an understandably confusing aspect of the coordinates framework.  Here's a minimal example (e.g., without your `ENU` frame) of what you're seeing:
```python
>>> import astropy.units as u
>>> from astropy.coordinates import AltAz, EarthLocation
>>> from astropy.time import Time

>>> location = EarthLocation.from_geodetic(0*u.deg, 0*u.deg, 0*u.m)
>>> obstime = Time("2019-03-19T19:58:14.9")
>>> altaz_frame = AltAz(obstime=obstime, location=location)

>>> geocentric_itrs = location.get_itrs(obstime=obstime)
>>> print(geocentric_itrs)
<ITRS Coordinate (obstime=2019-03-19T19:58:14.900, location=(0., 0., 0.) km): (x, y, z) in m
    (6378137., 0., 0.)>
>>> print(geocentric_itrs.transform_to(altaz_frame))
<AltAz Coordinate (obstime=2019-03-19T19:58:14.900, location=(6378137., 0., 0.) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt, distance) in (deg, deg, m)
    (311.93378221, -0.00629426, 378.37688331)>
```
When you call `.get_itrs()` the way that you have, you've created a *geocentric* `ITRS` coordinate, that is, as measured from an observer at Earth center (hence the `location=(0., 0., 0.) km`).  The problem is that `ITRS` is implemented to assume that the coordinate includes stellar aberration for the observer (here, Earth center), that is, a deflection of ~20 arcseconds of the apparent location of an object.  So, when you convert to `AltAz`, it removes the stellar aberration that it thought was there, and now the coordinate no longer coincides with the origin of the `AltAz` frame by ~400 meters.

This tripping point is described at some level in the [docstring of `ITRS`](https://docs.astropy.org/en/stable/api/astropy.coordinates.ITRS.html) and as one of the coordinates [common mistakes](https://docs.astropy.org/en/stable/coordinates/common_errors.html#altaz-calculations-for-earth-based-objects).

What you need to do is to create a *topocentric* `ITRS` coordinate for the specific location on the Earth by specifying `location` in the `.get_itrs()` call.  When transforming that coordinate, the stellar aberration will be evaluated for an observer at that location:
```python
>>> topocentric_itrs = location.get_itrs(obstime=obstime, location=location)
>>> print(topocentric_itrs)
<ITRS Coordinate (obstime=2019-03-19T19:58:14.900, location=(6378137., 0., 0.) m): (x, y, z) in m
    (0., 0., 0.)>
>>> print(topocentric_itrs.transform_to(altaz_frame))
<AltAz Coordinate (obstime=2019-03-19T19:58:14.900, location=(6378137., 0., 0.) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt, distance) in (deg, deg, m)
    (0., 0., 0.)>
```
Now that the `ITRS` coordinate is a zero vector away from the location on Earth surface, the `AltAz` is also a zero vector away.

-----
Notes:

- The topocentric `ITRS` frame was added in 5.2 (#13398)
- The convenient way to get a topocentric `ITRS` position was added in 5.3 (#14628)

**Comment by Joshuaalbert** [comment]
Thanks for the explanation, I totally missed that!
