### ISSUE TITLE
Add missing SI-Units to astropy.units.si

### ISSUE THREAD

**Issue by henrikef** [astropy/astropy#16527]
### What is the problem this feature will solve?

Currently, several units specifically named in the [SI brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf) table 4 ("The 22 SI units with special names and symbols") and table 8 ("Non-SI units accepted for use with the SI units") are missing from the module `astropy.units.si`: gray, sievert, katal, neper, bel, hectare.

### Describe the desired outcome

I would like `astropy.units.si` to define the following SI-Units and non-SI-Units accepted for use with SI: 

- gray, Gy = m^2/s^2 (absorbed dose [of ionizing radiation], kerma)
- sievert, Sv = m^2/s^2 (equivalent dose [of ionizing radiation])
- katal, kat = mol/s (catalytic activity)
- hectare, ha = 1e4 m^2 (area)
- logarithmic units bel, B (base 10) and neper, Np (natural logarithm).

### Additional context

According to the  [BIPM](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf) table 4 ("The 22 SI units with special names and symbols"), it is important to use the correct units when referring to radioactivity and ionizing radiation:

> In the field of ionizing radiation, the SI unit becquerel rather than the reciprocal second is used. The SI units gray and sievert are used for absorbed dose and dose equivalent, respectively, rather than joule per kilogram. The special names becquerel, gray and sievert were specifically introduced because of the dangers to human health that might arise from mistakes involving the units reciprocal second and joule per kilogram, in case the latter units were incorrectly taken to identify the different quantities involved.

**Comment by mhvk** [comment]
@henrikef - yes, no problem to add most of those. While most are unlikely to be used in astronomy, it is good to cover the SI bases.

Would you be willing to make the PR? gray and sievert can go under "radioactivity" in `si.py`, maybe katal can be with `mol` in amount of substance. hectare might be done in `misc.py`, together with barn, though perhaps best in `si.py` for consistency?

For `Bel` - we already have `dB`, which really is the only one actually used, but we could add it as an alternative name to `dex` in `units/function/units.py` (it needs to be there since it can have an enclosed unit  -- just like `dB(mW)`, there could be `Bel(something)`).

That is where neper would belong too, and in principle it is not difficult to add (need to make a new `NeperUnit` in `units/function/logarithmic.py`), but then that would also require tests, etc.

Anyway, I think it is fine to split this in pieces, and do the easy stuff first.

**Comment by henrikef** [comment]
Sounds good! I think either me or my colleague will make the pull request :)

**Comment by pllim** [comment]
Please see https://github.com/astropy/astropy/pull/16729 . Thanks!
