### ISSUE TITLE
astropy.utils.introspection.minversion fails when running pytest using the development version

### ISSUE THREAD

**Issue by Parkerwise** [astropy/astropy#16601]
### Description

I am trying to get into the world of helping to contribute to Astropy, so if I've made any mistakes with this report let me know! I am working through the development section of the astropy docs and I have gotten to the point where I am testing the developers copy. I am running astropy in a conda environment and I got one failure on astropy.utils.introspection.minversion. The docs said to report this, so that is what I am doing. The conda environment is working just fine, I just figured I should clarify I am not running in my base environment. I also ran a test using tox and got the same failure.

JSON report: [report.json](https://github.com/user-attachments/files/15946361/report.json)

### Expected behavior

Install development version of astropy in conda environment using python -m pip install --editable ".[test]"
run pytest in the astropy directory
no test failures

### How to Reproduce

1. clone astropy 
2. create conda environment 
3. run python -m pip install --editable ".[test]"
4. run pytest in the astropy directory

### Versions

```
platform
--------
platform.platform() = 'Linux-6.9.5-arch1-1-x86_64-with-glibc2.39'
platform.version() = '#1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000'
platform.python_version() = '3.12.4'

packages
--------
astropy              0.1.dev37458+gcacde01
numpy                2.0.0
scipy                1.13.1
matplotlib           3.8.4
pandas               --
pyerfa               2.0.1.4
```

**Comment by neutrinoceros** [comment]
Hi @Parkerwise, I think I know where your problem is : `astropy              0.1.dev37458+gcacde01` is clearly wrong, but indicates that your local copy of the code doesn't include our version tags. Here's how to fix this
```
git remote add upstream https://github.com/astropy/astropy.git
git fetch upstream --tags
python -m pip install -e .
```
This may be an oversight in our documentation, in which case we should mention it there.
Let me know if this is sufficient to get back on track !
(Also, disclaimer: I typed this message from my phone, and even though I've tried to be careful, the code _might_ still contain typos, but at least it gives you the gist of it!)

**Comment by Parkerwise** [comment]
thank you @neutrinoceros that resolved the issue! I'll be marking this as closed now.
