### ISSUE TITLE
MNT: migration to ruff 0.6

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#16863]
*previously on Ruff VS Astropy*: #16621

ruff 0.6 is out with yet-another round of rules, and its own [migration guide](https://astral.sh/blog/ruff-v0.6.0#migrating-to-v06).
I expect this one to go smoother than v0.5 but this time around I'd like to avoid making the mistake of bundling all changes in a single world-pinging PR. Instead, here's a plan in 3 steps (the first 2 of which can be split across several PRs, one for every subpackage)

Here are the subpackages affected by autofixes:
- [x] `io.ascii` (3 changes) #16864
- [x] `io.fits` (2 changes) #16865
- [x] `table` (3 changes) #16866
- [x] `visualization` (1 change) #16867

after that, there remains 9 violations to [`PLW0642`](https://docs.astral.sh/ruff/rules/self-or-cls-assignment/) across the following subpackages:
- [ ] `coordinates` (2 violations)
- [ ] `io.fits` (1 violation)
- [ ] `time` (1 violation)
- [ ] `uncertainty` (1 violation)
- [ ] `units` (1 violation)
- [ ] `utils.masked` (2 violations)
- [ ] `utils.tests` (1 violation)

these are not auto-fixable. They should also be very easy to fix manually albeit potentially noisy. Maybe we want to ignore this rule ?

There are also a couple rules being renamed in this version, including `PT001` and `PT023`, which are currently listed in `.ruff.toml`, so an update is needed there.
Also note that `PT004` (also listed in `.ruff.toml`) is now deprecated. There's already a note about it in `.ruff.toml`; I don't think we need to do anything else for now (it doesn't hurt to ignore a deprecated rule, I think ?).

**Comment by mhvk** [comment]
I just looked at all four PRs, and in general the change looks good. Though I guess it is a little in the eye of the beholder what is clearer: for `max` and `min`, I always have to think a little what is really being done, while for the `if` statements that are replaced, that is simply spelled out.

Also thought I should at least mention that the replacement with `max` or `min` makes the code a little slower, maybe mostly because in all cases done here it replaces a two-argument (rather than random-number of argument) case:
```
def mymax(a, b):
    if a < b:
        a = b
    return a

def regmax(a, b):
     a = max(a, b)
     return a

a, b = 2, 1
%timeit regmax(a, b)
# 162 ns ± 1.1 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
%timeit mymax(a, b)
# 63.3 ns ± 0.721 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
%timeit mymax(b, a)
# 65.4 ns ± 0.0924 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

**Comment by mhvk** [comment]
Separately, this feels like another rule one might one to look at once in a while, rather than something one should enforce.

**Comment by mhvk** [comment]
Also separately, I had a quick look at our use of assignments to `self` and `cls` (PLW0642) and they are very much not like the examples given by ruff, but rather fairly logical, with replacing them just adding needless extra code. Hence, agreed with your suggestion to ignore it.

**Comment by taldcroft** [comment]
My 2c is that we should ignore PLR1730 (https://docs.astral.sh/ruff/rules/if-stmt-min-max/):
- As @mhvk noted it can be slower.
- There are situations where the intent of the original code is more clear to me, e.g.
```
if count < 0:
    count = 0
# vs
count = max(count, 0)
```

We already ran into this PLR1730 in our Chandra code and it just ended up causing discussions that are distracting and waste time.

**Comment by neutrinoceros** [comment]
I did *not* anticipate PLR1730 could raise any concerns, but I totally get the sentiment. Now I'm hesitant to just close my PRs and open a new one to propose permanently ignoring this rule instead. My main goal is to find the path of least resistance and I'm not confident that such a proposition would be resolved quickly either, but I think @taldcroft has the authority to make the call at least for `table` and `io.ascii`, right ?

**Comment by mhvk** [comment]
Since you did the work, I think we should just judge the different PRs separately (great that they are!) and put PLR1730 in the list of "may be useful to check once in a while, but we don't enforce it".

**Comment by taldcroft** [comment]
> "may be useful to check once in a while, but we don't enforce it".

What would that mean in practice in terms of a process? I think we definitely want to have a consistent project-wide policy and put that in place now. Otherwise we just keep coming back to this and it sucks up more time. 

One option would be to keep the existing code where it improves readability. Looking at the diffs, it looks to me that cases like this are definitely improved:
```
<            if maxprec < fmt[1] + fmt[2]:
<                maxprec = fmt[1] + fmt[2]
>            maxprec = max(maxprec, fmt[1] + fmt[2])
```
But this is worse:
```
<            if idx < 0:
<                idx = 0
>            idx = max(idx, 0)
```
So maybe just keep the rule and `# noqa: PLR1730` cases like the latter?

**Comment by mhvk** [comment]
I see your point, but personally I really have those `noqa` - why distract the reader with something they have no idea what it means? When we have already decided the code in question is clearer this way, we should mark it just because some linter thinks it is not?

But I see your point about that adding a rule to a "sometimes try this just to see if you can make things a bit better" just gets to repeating the same discussion. So, maybe we should just decide now that this rule does not get enforced? Since it is basically a matter-of-taste rule that is just not important enough?

**Comment by pllim** [comment]
I agree with https://github.com/astropy/astropy/issues/16863#issuecomment-2302519231 that we should just blanket ignore this rule. It is undesirable for `ruff` to suggest something that actually makes things slower. Maybe open issue upstream as well?

**Comment by neutrinoceros** [comment]
How about this:
- merge #16866 and #16867
- close #16864 (and possibly #16865)
- in a new PR, ignore PLR1730, PLW0642, and bump ruff at the same time (closing this issue)

?

**Comment by pllim** [comment]
Sounds like a plan! Looks like Marten already approved https://github.com/astropy/astropy/pull/16866 but would be nice to make sure @taldcroft is also okay with it, given his concern above. Thanks for your patience!

**Comment by mhvk** [comment]
Thanks, @neutrinoceros! Plan sounds good to me too.

**Comment by dhomeier** [comment]
In terms of conciseness, is there any drawback to
`idx = 0 if idx < 0 else idx` (or will the `else` introduce an extra penalty)?

**Comment by neutrinoceros** [comment]
Not that I know of. A ternary assignement should compile to the exact same byte code as the equivalent if/else, and having an `else` doesn't change the number of branches as compared to a single `if`.

**Comment by taldcroft** [comment]
> In terms of conciseness, is there any drawback to `idx = 0 if idx < 0 else idx` (or will the `else` introduce an extra penalty)?

I would say we are striving for readability not conciseness. I like the ternary when there are really 3 parts, but I'm not a fan of using it instead of a more straightforward if statement. The useless `idx = idx` bothers me.

**Comment by dhomeier** [comment]
> I would say we are striving for readability not conciseness. I like the ternary when there are really 3 parts, but I'm not a fan of using it instead of a more straightforward if statement. The useless `idx = idx` bothers me.

Agreed, I would much prefer if the one-liner was possible without the concluding `else`; this just seemed an alternative to fit everything on a single line without the performance impact of `max()`.
