### ISSUE TITLE
[6.1.4] radio-astro-tools test has a regression

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#17096]
### Description

When running pytest on https://github.com/radio-astro-tools/radio-beam with the just-released Astropy 6.1.4, I get the following error:
```
_____________________ ERROR collecting tests/test_beams.py _____________________
/usr/lib/python3/dist-packages/radio_beam/tests/test_beams.py:508: in <module>
    @pytest.mark.parametrize(("beams", "target_beam"), casa_commonbeam_suite())
/usr/lib/python3/dist-packages/radio_beam/tests/test_beams.py:479: in casa_commonbeam_suite
    Beam(major=4 * u.arcsec, minor=4 * u.arcsec,
/usr/lib/python3/dist-packages/radio_beam/beam.py:87: in __new__
    if u.deg.is_equivalent(pa):
/usr/lib/python3/dist-packages/astropy/units/core.py:1013: in is_equivalent
    return self._is_equivalent(other, equivalencies)
/usr/lib/python3/dist-packages/astropy/units/core.py:1024: in _is_equivalent
    if self._get_physical_type_id() == other._get_physical_type_id():
/usr/lib/python3/dist-packages/astropy/units/core.py:695: in _get_physical_type_id
    unit = self.decompose()
/usr/lib/python3/dist-packages/astropy/units/core.py:2485: in decompose
    x = CompositeUnit(
/usr/lib/python3/dist-packages/astropy/units/core.py:2358: in __init__
    raise UnitScaleError("cannot create a unit with a scale of 0.")
E   astropy.units.core.UnitScaleError: cannot create a unit with a scale of 0.
```
[Full test log](https://ci.debian.net/packages/r/radio-beam/testing/amd64/52597818/)
This also happens when [running pytest for spectral-cube](https://ci.debian.net/packages/s/spectral-cube/testing/amd64/52597826/).
This may also a newly disclosed bug in radio-astro-tools/radiobeam; however I'd guess that **Unit.is_equivalent()** should not raise an exception?

**Comment by pllim** [comment]
I think it is caused by https://github.com/astropy/astropy/pull/17048 😬 

cc @mhvk @eerovaher @nstarman

**Comment by pllim** [comment]
Maybe @keflavich can speak from the downstream side (radio-beam, spectral-cube).

**Comment by mhvk** [comment]
The underlying problem is the use of `unit.is_equivalent(quantity)` rather than `unit.is_equivalent(quantity.unit)`. This used to work fine (if slow), since the quantity gets converted to a unit, with its value as the scale. But the quantity here is `pa = 0 * u.deg`, so one gets a scale of zero, which we decided is not a meaningful unit. In this case, of course, it is quite obvious what the user wants: just to check that the unit is OK...

I think we'll have to fix this at least for 6.1.5 - maybe simplest is to special case in `is_equivalent`  https://github.com/astropy/astropy/blob/04dfd245ac7815e20908ff7d079f5ad98dd0b2e4/astropy/units/core.py#L977-L982

L980 could become
```
other = Unit(getattr(other, "unit", other), parse_strict="silent")
```
From a quick check, that seems to solve the warnings in `radio-beam`. However, it would be a different type of API change, in that now it is OK to put in an array-valued quantity to `is_equivalent()`.

@eerovaher, @nstarman - what do you think? Also whether to only backport (i.e., 7.0 has an API change) or just try to be generous generally.

**Comment by nstarman** [comment]
IMO backport only. I would say that were `is_equivalent` a standalone function in the units package, not a method on a unit object, then we might want to special-case passing a quantity.

**Comment by e-koch** [comment]
Thanks all. I've opened an PR to fix this behaviour in radio-beam: https://github.com/radio-astro-tools/radio-beam/pull/128

Presumably this should also fix the spectral-cube errors, @olebole .

**Comment by pllim** [comment]
Oh, does that mean astropy does not need to revert anything then?

**Comment by eerovaher** [comment]
I'll point out that according to the docstring of `UnitBase.is_equivalent()`, `astropy` has not made the promise that `Quantity` inputs are supported. We have therefore not made a breaking change in our public API, we are now just stricter about enforcing it.

https://github.com/astropy/astropy/blob/6130037fc72111ec24c31421884b7859f2b02745/astropy/units/core.py#L954-L962

**Comment by mhvk** [comment]
Agreed, but one should try not to break things even if they worked in ways never intended (and in this case how it worked was certainly logical). But I think in the present state we let things be unless we hear of other breakage. Happily, effectively we get some detailed checking of lots of packages by them being packaged for Debian - thanks so much, @olebole!
