### ISSUE TITLE
Latitude/Longitude parsing accepts wrong cardinality

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#17129]
### Description

`Longitude` / `Latitude` string parsing accepts the wrong cardinalities without complaining (warning or error).

### Expected behavior

Issue an error or at least a warning.

### How to Reproduce

```
In [10]: Longitude("45°21'48.7\"N")
Out[10]: <Longitude 45.36352778 deg>

In [11]: Longitude("45°21'48.7\"S")
Out[11]: <Longitude 314.63647222 deg>

In [12]: Latitude("14°24'48.9\"E")
Out[12]: <Latitude 14.41358333 deg>

In [13]: Latitude("14°24'48.9\"W")
Out[13]: <Latitude -14.41358333 deg>
```

### Versions

```
Linux-6.10.10-arch1-1-x86_64-with-glibc2.40
Python 3.11.10 | packaged by conda-forge | (main, Sep 22 2024, 14:10:38) [GCC 13.3.0]
astropy 6.1.4
Numpy 2.0.2
pyerfa 2.0.1.4
Scipy 1.14.1
Matplotlib 3.9.2
```

**Comment by mhvk** [comment]
Hmm, that is bad. It arises because EW and NS are just used as alternatives to a sign in the general angle parser: https://github.com/astropy/astropy/blob/217431fa0bb9f8b25a1b5032257039cd05f51c01/astropy/coordinates/angles/formats.py#L125-L135

I guess `Latitude` and `Longitude` should special-case this, or, maybe easier, error on the wrong ending. Or perhaps we can pass in the type of class to the parser, so that it can exclude those.

**Comment by mhvk** [comment]
See #17132 for a fix (simplest solution...)
