### ISSUE TITLE
`AstropyLogger` does not handle lazy formatting

### ISSUE THREAD

**Issue by snbianco** [astropy/astropy#17191]
### Description

Log messages are not formatted correctly when using lazy formatting, i.e. `log.debug("Example %s", "test")`

### Expected behavior

Expect that arguments are correctly inserted into the message template.

### How to Reproduce

```python
import logging
from astropy.logger import AstropyLogger

def setup_logger():
    orig_logger_cls = logging.getLoggerClass()
    logging.setLoggerClass(AstropyLogger)
    try:
        log = logging.getLogger('logger')
        log._set_defaults()
    finally:
        logging.setLoggerClass(orig_logger_cls)
    return log

log = setup_logger()
log.setLevel('DEBUG')
log.debug('Example: %s', 'test')
```

### Versions

```python
import astropy
try:
    astropy.system_info()
except AttributeError:
    import platform; print(platform.platform())
    import sys; print("Python", sys.version)
    import astropy; print("astropy", astropy.__version__)
    import numpy; print("Numpy", numpy.__version__)
    import erfa; print("pyerfa", erfa.__version__)
    try:
        import scipy
        print("Scipy", scipy.__version__)
    except ImportError:
        print("Scipy not installed")
    try:
        import matplotlib
        print("Matplotlib", matplotlib.__version__)
    except ImportError:
        print("Matplotlib not installed")
```
```
macOS-14.4.1-arm64-arm-64bit
Python 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]
astropy 6.1.2
Numpy 1.24.4
pyerfa 2.0.1.4
Scipy 1.10.1
Matplotlib 3.7.5
```

**Comment by pllim** [comment]
Thanks for the report!

That said, I am guessing you encountered this over at astroquery? As noted on top of https://docs.astropy.org/en/latest/logging.html , the logger in astropy was meant for `astropy` internal usage. Is there an issue downstream to move away from astropy logger?

**Comment by snbianco** [comment]
Yep! It doesn't look like there's any astroquery issues that pertain to this yet, but I can write one.

**Comment by pllim** [comment]
Well, our logger would need some tech debt exorcism regardless. Patches are welcome. Also see: https://github.com/astropy/astropy/issues?q=is%3Aissue+is%3Aopen+label%3Alogging

**Comment by bsipocz** [comment]
Yeap, I rather fix the logger here than doubling on the debts downstream.

**Comment by neutrinoceros** [comment]
I spent a bit of time down the rabbit hole and here's what I found so far:

While I can reproduce the problem by running @snbianco's snippet, it seems difficult to formally test: say that we rewrite the snippet in a form that allow it to be run as a script *or* a test module, like so

```python
# t.py
import logging
from astropy.logger import AstropyLogger

def setup_logger():
    orig_logger_cls = logging.getLoggerClass()
    logging.setLoggerClass(AstropyLogger)
    try:
        log = logging.getLogger('logger')
        log._set_defaults()
    finally:
        logging.setLoggerClass(orig_logger_cls)
    return log

def test_logger_lazy_formatting(caplog):
    main()
    assert caplog.messages == ["Example: test"]

def main():
    log = setup_logger()
    log.setLevel('DEBUG')
    log.debug('Example: %s', 'test')
    
if __name__ == "__main__":
    main()
```

Now run  it as a script, then as a test
```
❯ python t.py
DEBUG: Example: %s [__main__]
❯ pytest t.py --no-header -s
======================================= test session starts ========================================
collected 1 item                                                                                   

issues/17191/t.py DEBUG: Example: %s [t]
.

======================================== 1 passed in 0.05s =========================================
```

the behavior is clearly not what we intend, but the test still pass. I don't know at this stage whether that's caused by pytest itself and whether it should be considered a bug there.

The other important thing I found is that subclassing the standard library logger class is [documented as tricky](https://docs.python.org/3/howto/logging-cookbook.html#customizing-logrecord). I'll quote the relevant paragraph here:
> This has usually meant that if you need to do anything special with a [LogRecord](https://docs.python.org/3/library/logging.html#logging.LogRecord), you’ve had to do one of the following.
>
> -    Create your own [Logger](https://docs.python.org/3/library/logging.html#logging.Logger) subclass, which overrides [Logger.makeRecord()](https://docs.python.org/3/library/logging.html#logging.Logger.makeRecord), and set it using [setLoggerClass()](https://docs.python.org/3/library/logging.html#logging.setLoggerClass) before any loggers that you care about are instantiated.
>
> -    Add a [Filter](https://docs.python.org/3/library/logging.html#logging.Filter) to a logger or handler, which does the necessary special manipulation you need when its [filter()](https://docs.python.org/3/library/logging.html#logging.Filter.filter) method is called.
>
> The first approach would be a little unwieldy in the scenario where (say) several different libraries wanted to do different things. Each would attempt to set its own [Logger](https://docs.python.org/3/library/logging.html#logging.Logger) subclass, and the one which did this last would win.

Other approaches are explained too, some of which are available since Python 3.2, which is now well behind our support range, but wasn't at the time this class was created.
ref https://github.com/astropy/astropy/pull/192

It may still be that the fix is actually easy (though I could not find an obvious culprit yet), but it may also be worth exploring the alternative approaches that are now available to customize logging, the first step of which would be unearthing #192 to understand what were the initial motivations.

**Comment by neutrinoceros** [comment]
Actually I think I found the bug. Fix in https://github.com/astropy/astropy/pull/17196

**Comment by pllim** [comment]
p.s. I think @Cadair suggested that we replace our logger with something called "log guru" or something like that a while ago but I cannot find that issue. Did I imagine it?

**Comment by Cadair** [comment]
> p.s. I think @Cadair suggested that we replace our logger with something called "log guru" or something like that a while ago but I cannot find that issue. Did I imagine it?

eh probably not, but maybe.

**Comment by neutrinoceros** [comment]
I believe you mean https://pypi.org/project/loguru/

I've used it in the past but from what I remember it is not suited for a library, because it is build around the idea of a single logger instance, which wouldn't work for any one downstream who'd want to use astropy _and_ loguru (or anything that already uses it).
