### ISSUE TITLE
astropy.table: should join, hstack, vstack be methods instead of functions?

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#1783]
I use a custom class that is derived from `astropy.table`. This class has some custom attributes that need to be dealt with when I join tables.
In the sources code of `astropy.table.operations.join` it even says:

```
    # Merge the column and table meta data. Table subclasses might override
    # these methods for custom merge behavior.
    _merge_col_meta(out, [left, right], col_name_map, metadata_conflicts=metadata_conflicts)
    _merge_table_meta(out, [left, right], metadata_conflicts=metadata_conflicts)
```

However, since `_merge_table_meta` is not a method of the table class, but instead a function defined on the `astropy.table.operations` level, how do I override this?
All I can think of is monkey-patching `astropy.table._merge_table_meta`, but then I would loose the ability to join anything that's not my specific table subclass.

Thus, I wonder if `join`, `hstack` and similar operations (or at least `_merge_col_meta` and `_merge_table_meta`) should be methods and not functions?
This would make for a call like this

```
tab1.join(tab2, join_type = ... )
```

I could then override the appropiate methods for my class of `tab1`, if I want.

**Comment by taldcroft** [comment]
I've been thinking about this recently and would propose making these available as class methods, e.g. `Table.hstack([t1, t2])` etc.  This would allow things like `QTable.hstack('[t1, t2]')` and indeed the original problem of `MyTable.hstack(..)`.  The functional forms could be (very) slowly deprecated, or just phased out from common usage by means of taking them out of the narrative docs.

In using table operations I've been annoyed by having to either import the `table` module explicitly for `table.hstack` or `from astropy.table import hstack`.

**Comment by astrofrog** [comment]
+1 to having class methods, but I think we should keep the functional forms 'forever' even if we remove them from the docs - this would break a lot of scripts...

**Comment by mhvk** [comment]
I like it too.  I think if you write the method carefully, one can also use it with the class, i.e., `Table.hstack(...)` would return a new `Table` instance. Here, `utils.decorators.sharedmethod` might be handy, constructing something like
```
@sharedmethod
def hstack(cls, tables, ...):
    if isinstance(cls, Table):
        # we're an instance; add ourselves to the list and ensure that
        # the output cls is of our type.
        tables = [cls] + tables
        cls = type(cls)
    <... stuff from current table.hstack ...>
    return cls(...)
```
Obviously, with the above one could redefine `table.hstack = Table.hstack` and be done with it!

**Comment by taldcroft** [comment]
Yup, leaving the functional forms there 'forever' seems fine.

The `@sharedmethod` looks interesting.  I'm not 100% sure we want to go from one way to hstack/etc to three (functional + class method + instance method), but I'm open for discussion.

**Comment by mhvk** [comment]
I think the preferred method would end up being the class method.  I actually do not like the instance method too much -- like you noted above, `t1.hstack([t2])` just isn't that obvious -- but on the other hand if we define a class method and do not treat instances separately, it would return `t2`, which also seems counterintuitive.

**Comment by cdeil** [comment]
+1 to add the standalone functions that create table objects (`hstack`, `vstack`, `unique` and `join`; see [here](http://astropy.readthedocs.io/en/latest/table/index.html#functions)) as classmethods.

Basically for the same reason @taldcroft already gave above:

> In using table operations I've been annoyed by having to either import the table module explicitly for table.hstack or from astropy.table import hstack.

Today I was editing many large `.py` files where I have many variables called `table` and also import `vstack` from `numpy`. For now I've adopted the pattern:
```python
from astropy.table import vstack as table_vstack
from astropy.table import join as table_join
```
but I don't like having to add those separate import lines to many files and would much prefer to call those as classmethods:
```
Table.vstack(...)
Table.join(...)
```

Is there agreement how exactly this should be implemented and presented in the docs?
Are there difficult test cases that must be written that check whether this works for subclasses?
Or is it just a matter of adding this (+ a few tests and high-level docs)?
```python
class Table:

    @classmethod
    def vstack('copy arguments here'):
    """Copy docstring here"""
        return vstack('copy arguments here')
```

**Comment by mhvk** [comment]
@cdeil - I think everybody agrees that we should have those methods as class methods. There are some catches, though. First, what should happen if one does it from an instance, i.e., `t1.vstack([t2, t3]])`. We could either have it just return `vstack([t2, t3])` or `vstack([t1, t2, t3])`. The latter would make it a `sharedmethod` (see above). Above, I preferred the latter, but on second thought, I'm quite fine with just the former as well -- we just need to document it well.

Second, it probably should always return at least a subclass of `cls`, independent of the classes of the input tables? I.e., probably one would need something like
```
@classmethod
def vstack(cls, *args, **kwargs):
    out = vstack(*args, **kwargs)
    if not isinstance(out, cls):  # or always??
        out = cls(out)
    return
```

I think we're probably at the stage where a PR would be most welcome...

**Comment by taldcroft** [comment]
I'm -0.5 on `sharedmethod` here, exactly for the ambiguity that it introduces.  If someone is reading code like `t1.vstack(..)` then it isn't obvious what it does.  It seems to me that `QTable.vstack(..)` is clear and covers nearly all use cases.  In rare cases you might have to do `type(t1).vstack(..)`, which is fine.

About the implementation, even though it is messier I would prefer to duplicate the exact args and (mostly) docstrings of the current functions.  The new `Table.vstack/hstack/join` class methods will be the primary interface so they should have a real method signature and not just `*args/**kwargs` pass through.

I think we might need something like a `subok` argument to distinguish between possibilities:
```
Table.vstack([qtable1, qtable2], subok=False)  # I really want a Table
Table.vstack([qtable1, qtable2])  # returns QTable
QTable.vstack([table1, table2])  # returns QTable
```

**Comment by taldcroft** [comment]
And oh yeah, this is a technically easy but very high-impact change, someone should jump on it!

**Comment by mhvk** [comment]
@taldcroft - agreed on all points (i.e., let's not do `sharedmethod`). I like the `subok` flag too. 

As for the docstrings, if done right can we not just move the functions to the class altogether and then define the functions in `operators` as `function = Table.function`? (obviously for this, the default has to be `subok=True`).

**Comment by taldcroft** [comment]
@mhvk - about `function = Table.function`, that will do the right thing, but I was worried about help and the docstring.  If I have a class method `hstack` in a class `Junk` then:
```
>>> hstack = Junk.hstack
>>> help(hstack)
Help on method hstack in module __main__:
hstack(cls, x) method of __builtin__.type instance
```
Instead what you would expect is that `hstack` is a function.  I imagine there is some magic or decorator so that we can do `hstack = classmethod_to_function(Table.hstack)`, but I don't know it off hand.

Likewise the operations functions docstrings are pretty explicit in usage examples and so they need to be customized slightly.

Also, as you alluded, for the function call there is no meaning to `subok`, so strictly speaking that should not be an argument.  One can imagine `hstack = functools.partial(Table.hstack)`, but again `help(..)` on that is misleading because it gives you help on a `functools.partial` object.

**Comment by nstarman** [comment]
- I think we should keep them as separate functions
- Add ``__array_(u)func(tion)__`` to table so that we can use ``np.join/hstack/vstack``, which just point to our functions
- We can do `functools.singlespatch` on these functions so that table subclasses can very easily implement custom rules. The one drawback is that the table subclass will need to be the first argument, but I think this is the same limitation that changing to table methods will suffer. And we can fix this issue by having the function look at all the other arguments and if return `NotImplemented` to have numpy cycle to that arg if there's a function we'd rather use.

We can implement all this very easily with https://pypi.org/project/overload-numpy/, which I wrote for my research but I think would benefit Astropy immensely, here and in places like `Representation / CoordinateFrame`. Happy to discuss further.

**Comment by mhvk** [comment]
Agreed this should be solved via `__array_function__`. I'll label this `close?` since I think the actual issue is answered: we should not define new methods on the table class.

**Comment by taldcroft** [comment]
I'm not convinced we should punt on the class method solution. First off it is worth noting that there is no `np.join`, and even if there were the arguments would be very different. 

Even for `hstack,vstack,dstack`, the `table` versions have additional arguments. I'll confess I'm not sure if `__array_function__` overrides can handle additional arguments that are not in the numpy version, but no matter it will be confusing for users since `np.vstack?` won't tell them what they need to know about using this with `Table` subclasses.

Finally, the workarounds suggested in the last bullet `We can do functools.singlespatch on these functions` seem like a lot of shenanigans / complexity compared to the very simple and very Pythonic mechanism of class overrides. Which is to say that I have a lot more experience than most our users and I have no clue what all that means.

**Comment by nstarman** [comment]
> Finally, the workarounds suggested in the last bullet We can do functools.singlespatch on these functions seem like a lot of shenanigans / complexity compared to the very simple and very Pythonic mechanism of class overrides. 

I have a worked example here: https://overload-numpy.readthedocs.io/en/latest/getting_started.html#dispatching-overloads-for-subclasses
Think of single-dispatch as class overrides, but you can make it work with *any* class, not just the one in a single inheritance tree. And the implementation doesn't have to live on the class.

If you start at https://overload-numpy.readthedocs.io/en/latest/getting_started.html, I walk through how we can very easily make any array-like object (like a Table) work with any numpy function.

```python
TABLE_OVERLOADS = overload_numpy.NumPyOverloader()

class Table:
    ....
    NP_OVERLOADS = TABLE_OVERLOADS

stack_funcs = {np.vstack, np.hstack, np.dstack, np.column_stack, np.row_stack}
@ TABLE_OVERLOADS.assists(stack_funcs, types=Table, dispatch_on= Table)
def stack_assists(cls, func, tables, *args, **kwargs):
    .... # the implementation
```

And for a custom subclass

```python
class MyTable:

@TABLE_OVERLOADS.assists(stack_funcs, dispatch_no= MyTable)
def my_stack_assists(cls, func, tables, *args, **kwargs):
    .... # the implementation
```

That's it.
To have functions that accept arguments beyond what numpy accepts, we can support this with

```
def vstack(...):
    func = ... # code to get the assist function out of TABLE_OVERLOADS
    return func(...)
``` 

The assistance functions can work with arguments beyond what numpy accepts, so long as they are kwargs with defaults (so accessing them through numpy works also).

**Comment by taldcroft** [comment]
@nstarman - looks simple on the outside, but I expect that this is hiding quite a bit of complexity under the hood. So my reservations about this approach include:

1. The astropy table operations functions are really quite different from the numpy functions in signatures. If someone looks at code and sees `out = np.vstack([t1, t2], metadata_conflicts='silent')` and googles `np.vstack`, they are going to be completely confused. Just because a function shares the same name and roughly the same idea does not mean it is helpful to dispatch via the numpy function. Personally I think we should limit this kind of overloading to cases where the signature and behavior are *very* similar.
2. How does the average user who doesn't read documentation get help on e.g. table `vstack` within IPython? If the narrative documentation gives examples that use `np.vstack` then I don't know what they can do.
3. What are we gaining via this overloading? For the vast majority of users it means removing one line like `from astropy import table` and using `np.vstack` instead of `table.vstack`. But they still need to call `table.join` and `table.setdiff` because numpy doesn't happen to have a `join` or `setdiff`.
4. Replacing a core feature of Python (class inheritance) that everyone understands very well with custom overload machinery dependent on a new single-maintainer package. Basically there is no way that most folks would know what to do besides copying the example in the docs. Even though the idea of single/multiple dispatch is very well known in other languages, it is not really deeply ingrained in Python. Users that just know enough Python to scrape by are going to be confused.
6. Despite the excellent heritage, it would not be consistent with past astropy core practice to have a hard dependence on a package that is new like `overload-numpy`.

**Comment by mhvk** [comment]
I think I agree with @taldcroft here, including that the numpy functions are not really appropriate anyway -- I think `np.concatenate` and friends do really make sense for `Time`, `SkyCoord` (and really other `ShapedLikeNDArray`) but @taldcroft's arguments make clear they make less sense for tables (sorry to have to be re-convinced; this really came up before).

That said, as methods, these make not much sense to me either: these are functions that table tables; tables need to know nothing about how they should get joined together, how to deal with disparate table types, etc. It is also contrary to how numpy does it for arrays (but perhaps similar to what pandas does? I don't know, since `QTable` fills my needs well enough!)

**Comment by taldcroft** [comment]
So we are perhaps back to doing nothing and letting **Close?** do its job. :smile:

One slight off-shoot from this is that I wonder if we should move to recommending (via the docs) an idiom like:
```
import astropy.table as tbl

t1 = tbl.Table(...)
t2 = tbl.QTable(...)
t12 = tbl.vstack([t1, t2])
```
Of course people could still also do `from astropy.table import QTable`, but I've seen recommendations about generally keeping some sort of namespace identifier in front of external symbols. OTOH using a modern IDE it is always trivial to know where a symbol comes from. Just a thought.

**Comment by mhvk** [comment]
Bit of a matter of taste.  In general, I feel in typical use I need nothing but the class itself (like for `Time`), but when checking things I suddenly do want `Column`, etc., and then having the module around helps. ..
