### ISSUE TITLE
Add support for Heliocentric and Barycentric Julian Dates

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#2244]
From a discussion on astropy-dev:
https://groups.google.com/forum/#!topic/astropy-dev/5KH5Ny1m6WY

The tentative conclusion there was to support Heliocentric and Barycentric Julian Dates via utility functions that accept a Time and Coordinate object.

**Comment by taldcroft** [comment]
Summary:

- High priority

**Comment by StuartLittlefair** [comment]
Has anyone yet formed a strong opinion about the need to develop a coherent framework for this? The problem is that a barycentric/heliocentric corrected time really has a position attached so it might be considered ideal implement this together with a framework that supports velocities, proper motions etc.

However, it's also an option to add a utility function to the time package that simply accepts a ```Time``` object and possibly an ```EarthLocation``` and returns a ```Time``` object in an appropriate scale. The location attributes for this new ```Time``` object would be nonsense of course.

If people are happy with the latter approach I can have a go at implementing this. It will be my first contribution to a big collaborative project though, so go easy on me...

**Comment by taldcroft** [comment]
@StuartLittlefair - I'm good with doing this as utility functions like you have outlined, probably putting this into a new module within the `time` subpackage and exporting the new public function(s).  If it ever comes to pass that a grander framework is developed that includes this functionality then we can slowly deprecate the functional interface.

**Comment by mhvk** [comment]
@StuartLittlefair - Help would be great! I think the first thing would be to split the problem up into pieces -- as your sample code above does already:
1. We need something to convert `EarthLocation` into a position relative to the solar system barycentre or the Sun. I *think* this may already be possible within coordinates, since the same would seem to be needed to support heliocentric ecliptic coordinates. @eteq? Otherwise, this might for now be a utility function that replaces your `_obs_pos` method.
2. Same for unit vector to object. My sense would be that coordinates supports this already too... @eteq?
3. The remainder is quite trivial, of course, and easiest may be to have a `Time` method that takes a `SkyCoord` instance as import and uses the functions in (1) and (2), returning a time or velocity offset (i.e., a `Quantity`), just like it is now possible to get a sidereal time. Similarly, or perhaps alternatively, one may want to have `SkyCoord` methods that takes a `Time` as an input.
4. With all the above in place, we might want to consider having `Time` support more general locations (not only `EarthLocation`). Since the corrections depend on the source one looked at, this doesn't seem trivial, and probably is of much lower priority.

The nice aspect of the separation that you already have, is that it should be relatively straightforward to substitute `erfa` approximations in (1) and (2) for functions that use the full JPL ephemerides.

Anyway, in the end I think @taldcroft is right in that the best way to start is with some utility functions, though arguably best within `coordinates` rather than `time`. Maybe @eteq can point us to what exists already -- by prodding around in the transformations, we may at the same time be able to help address #4268...

**Comment by StuartLittlefair** [comment]
@mhvk - I agree that looks like a very sensible way forward.

With a few changes to the coordinates package I think the point 1 is quite straightforward. I'm not sure about 2, but as you say from that point on it is quite trivial, and just a question of API design.
