### ISSUE TITLE
ProgressBar dosen't work in a Qt Python interpretor

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#2297]
Running the following code in a Qt Python interpretor (like in Spyder) doesn't print anything:

``` Python
from astropy.utils.console import ProgressBar

pbar = ProgressBar(10000)

for i in xrange(10000):
    pbar.update()
```

**Comment by swt30** [comment]
Browsing the issues list and saw this. Basically, `isatty` is false for a Qt console, so you need to either override that, or the ipython console needs to be changed so that stdout is treated as a tty inside the Qt console. The offending line is [here](https://github.com/astropy/astropy/blob/19c7568126573ddd8f33d67d2ee6f94828fa2fa6/astropy/utils/console.py#L132).

**Comment by swt30** [comment]
Also, for reference, an [example of determining if one is running inside a qtconsole](https://gist.github.com/kergoth/813057/520205dd67e948f302e9f220bb9833a132e0607c#gistcomment-1477091).

**Comment by embray** [comment]
There really isn't a reliable way to determine "if one is running inside a qtconsole" with IPython, since multiple clients can be connected to the same kernel and the kernel is generally agnostic as to which frontends are connected to it (except, to some extend, when determining how to send outputs).  There are hacks one can come up with to sort of work around that but none of them are reliable.  And even less so now that qtconsole is part of Jupyter and is even more divorced from what kernel is in use too.

The only reliable approach this would have right now is to use the same approach as the `ipython_notebook` option--just have a separate argument to ProgressBar that specifies qtconsole--it would be nice if this then output as some sort of interactive Qt widget. I don't know if that's possible though.

**Comment by bsipocz** [comment]
@Cadair - Could you test whether this issue is still an issue or maybe something got fixed upstream in the past 3 years?

**Comment by pllim** [comment]
This looks pretty old, I am going to put a marker for bot to auto-close in a few months if there are no replies.

**Comment by pllim** [comment]
@Cadair I am closing this as it appears "stale". Please re-open if that is not the case.
