### ISSUE TITLE
Bug when multiplying a masked column with a unit

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2701]
Discovered during a live demo at SciPy 2014 ;)

```
In [13]: t = Table(masked=True)

In [14]: t['a'] = [1,2,3]

In [15]: t['a'].unit = 'deg'

In [16]: t['a'] * u.deg
Out[16]: 
<MaskedColumn name='a' unit=None format=None description=None>
masked_array(data = [<Quantity 1.0 deg> <Quantity 2.0 deg> <Quantity 3.0 deg>],
             mask = [False False False],
       fill_value = 999999)
```

This should return just a single quantity, as it does for non-masked tables.

cc @taldcroft

**Comment by mhvk** [comment]
Just to keep this up to date: in current numpy master, `MaskedArray` now respects `__array_priority__` (due to https://github.com/numpy/numpy/pull/5864). The result is not super yet, in that now masks get ignored, but that is now *our* problem (Quantity just converts masked arrays to regular ones), so it is also under our control to get it to work.
```
MaskedArray([0., 2., 3.], mask=[True, False, True]) * u.m
# <Quantity [ 0., 2., 3.] m>    -> mask is ignored, since Quantity converts to regular array
```

**Comment by mhvk** [comment]
p.s. https://github.com/numpy/numpy/pull/3907 should help further.

**Comment by bsipocz** [comment]
@mhvk  - I think this can be closed as the original issue is already fixed with the latest numpy. However the masking issue may deserve a new separate issue?

**Comment by mhvk** [comment]
@bsipocz - I agree this particular issue can be closed -- what remains is the general problem that we do not have masked quantities, which is already raised in #1852.
