### ISSUE TITLE
Test source tarball as part of release process

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2717]
I already do test the tagged version whenever making a release.  But it would be good to have a step, after running `./setup.py build sdist`, of making a fresh venv and pip installing the freshly created tarball into it, then running `import astropy; astropy.test()`.

Definitely something to include when I redo the release scripts, given the recent spate of me uploading tarballs to PyPI that didn't have all the files.

**Comment by bsipocz** [comment]
@cdeil - This looks like a relevant issue for the discussion you initiated in #5019.

My suggestion would be to limit ourself to test the release candidates. We already have the the infrastructure to install it from pip for affiliates. Alternatively we need to come up with a better system to test the release candidates, those errors should have come up before, but I think most of us were (I definitely was) focusing on getting the test pass, rather than building the docs, etc.

**Comment by bsipocz** [comment]
Closing this now, as the sdist testing is now part of the docs for the release procedure. Setting up a test on travis is another issue though, and would benefit a little bit of brainstorming.
