### ISSUE TITLE
Add a reference TOC

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#282]
This was discussed a while back in #162, but makes more sense as a separate issue: it would be nice to have a page somewhere on the docs that just stores links to the reference section for "power users".

@taldcroft expressed a preference for naming the "References/API" sections in the docs just "Reference", which seems fine, and could also be done as part of this.

**Comment by bsipocz** [comment]
There is currently an ``Index``, ``Module Index`` and ``Search Page`` right at the bottom of http://docs.astropy.org/en/latest/ 

Would that be enough to close this issue?

**Comment by mhvk** [comment]
Rereading this issue, I think we can indeed close it. Not so much because of those 3 items at the end -- which seem mostly autofilled very large files that are not so obviously useful -- but because I've found the docs quite good as they are. What is still missing somewhat (to me at least) is overviews of the organisation of different modules. These might make most sense as the docstrings of the top-level `__init__` in each module. Anyway, that really is a different issues;:+1: on closing this one.
