### ISSUE TITLE
Angstrom and erg are allowed units in the FITS standard

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2933]
As per the FITS standard (http://www.aanda.org/articles/aa/pdf/2010/16/aa15362-10.pdf), Table 4, Angstrom and erg are explicitly listed as allowed units in the FITS standard. My interpretation of the footnote is that since the units are in the table, they are allowed, even though they deviate from McNally 1988. I came across this today when I got a warning about erg and thought that _can't_ be right :)

**Comment by mhvk** [comment]
Moving the label to `io.fits`, since I don't really think this is a `units` issue -- the unit conversion should just be done with a less strict flag in `io.fits`.

**Comment by saimn** [comment]
I would like to get rid of these annoying warnings about Angstrom and erg units, without filtering other units warning. From the discussion above, my understanding is that these units are not *deprecated*, but just *not recommended*. So, what would be the best option here ?

- Replacing warnings with INFO messages, as suggested by @astrofrog 
- Adding a "pedantic" flag as suggested by @embray (in `fits.open` and other convenience functions ?)
- Other options ? (the "rework of how the FITS module handles validation and warnings/errors" would be great but it's unlikely to happen in a near future)

**Comment by pllim** [comment]
@saimn , the "pedantic" option would be a good compromise for now. However, instead of sticking it into every FITS function (which can be a lot of work), I suggest just make it a configuration item (like VO table) and set the default to `False`.

**Comment by Cadair** [comment]
I just found myself reading the FITS 3.0 standard (as one does) and this notification cropped up. Both Angstrom and erg are present in Table 4 (Pence et. al 2010) titled "Additional Allowed Units".

**Comment by mhvk** [comment]
If the units are in fact allowed, easiest may be just to change `units/formats/fits.py`. Do add a note there with a full reference.

**Comment by saimn** [comment]
@Cadair - yes, but the point of the discussion above is that it's not really clear. 
These units are listed in the "Additional Allowed Units" table, but with the mention that they are "Deprecated in IAU Style Manual (McNally 1988)...". And in the text (4.3): "The units of all FITS header keyword values, with the exception of measurements of angles, should conform with the recommendations in the IAU Style Manual (McNally 1988)."

So, with the fitsbits message mentioned above (https://github.com/astropy/astropy/issues/2933#issuecomment-61715571) I think it's clear that these units are not deprecated. The question that remains is to know if `io.fits` should have a way to warn when "not recommended" units are used. And the consensus above was towards adding a "pedantic" option. 
But if it was just me, I would simply remove the deprecation warnings, as it would be much easier to do ;-). Otherwise a configuration item as suggested by @pllim can be a good solution.

BTW, the two other units that are marked as deprecated in `units/formats/fits.py` ('G' and 'barn') are in the same table, so the same solution should apply.

**Comment by saimn** [comment]
So, what's to be done here ? Would a "pedantic" flag be really useful (I doubt it) ?

**Comment by hamogu** [comment]
:+1: to just allow those units. Practicality beats purity.
Yes, if I understand it correctly, @embray says that the standard that the fits standard is based on does not recommend these units, but they are not listed as deprecated in the fits standard which is what astronomers should adhere to. If/When the fits framework gets reworked, finer level of detail can be put in, but for now just allowing those units seems good enough for me.

(And maybe that buggs some purist enough to actually rework the fits framework at some point).

**Comment by astrofrog** [comment]
I think we should just allow these units

**Comment by mhvk** [comment]
Also agreed that we should just allow it. I think the only remaining question is whether we should, at least by default, not *write* those units.

**Comment by saimn** [comment]
Here we go: #5929

**Comment by MSeifert04** [comment]
> If we agree that these units are not deprecated, there is no reason to prevent their use when writing.

They are not deprecated but it's recommended **not** to use them. So it's a valid point about complaining on **write**. 

But for all practical purposes: Agreed!
