### ISSUE TITLE
Add fits.diff convenience function

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2979]
A user pointed out to me that the object-oriented interface provided by the `FITSDiff` and related classes is not necessarily the easiest to use for a non-programmer in an interactive analysis interface.  And they're right--it's more an API for building higher level tools.  And as I pointed out we already provide such a higher level tool in the form of the included `fitsdiff` program, which one can easily call from within IPython.

That said, this also seems like it would be a good candidate for a "convenience" shorthand a la `fits.info()`.
`fits.diff(a, b)` need be little more than:

```
def diff(a, b, **kwargs):
    print(FITSDiff(a, b, **kwargs).report())
```

but even that could potentially save a lot of hassle, and may be easier to find in the documentation as well.  It could also be extended to be somewhat universal in its arguments.  The FITS diff API has differs for full FITS files all the way down to just comparing FITS headers.  So `fits.diff()` could take any two objects and compare them so long as they're the same type.

**Comment by astrofrog** [comment]
Not critical for 1.0, so removing milestone

**Comment by SaraOgaz** [comment]
@embray I'm looking to maybe add this in, since it sounds like it's "astropy" approved?  I wanted to check before I actually started working on (@justincely).  I'm guessing I can use fits.info() as a guide here?

**Comment by astrofrog** [comment]
@SaraOgaz - feel free to work on it, it seems like people were in favor of it above. As @embray pointed out, there won't be much code, though the docstring should be clear since it will be what people will likely look at.

**Comment by embray** [comment]
Yup--looks like I practically wrote the code in the issue, but you'll want to flesh out the function signature more, maybe, to better support some of the other features  common to the "convenience" functions, like some way to select the HDU to compare (if comparing just a single HDU), and a detailed docstring referring , at some point, to the full FITSDiff API.

**Comment by SaraOgaz** [comment]
So @embray and @astrofrog, (or @MSeifert04)

I started working on this, and I'd really like to provide an option to specify both a extension if desired (as @embray pointed out) and the option of telling diff you want just the header or just  the data (assuming you're providing the full filename, not the HDU object directly). 

But this seems to be not very nice, as I'd like the header/data keyword to be optional, but that doesn't seem to work very well with [`_getext`](https://github.com/astropy/astropy/blob/master/astropy/io/fits/convenience.py#L824)  (I was looking at [`update`](https://github.com/astropy/astropy/blob/master/astropy/io/fits/convenience.py#L614) as an example of adding in another keyword argument in addition to the ext ones, but in my case the extra keyword is a string, so I can't really do the ``isinstance`` checking.

So I see three possible options here.
1 Not have this header/data option at all.
2 Make the keyword specifying wether you want header,data,all to be NOT optional
3 Restrict the specification of extensions so that I don't have to interpret it positionally (the last being my least favorite option)

I'll note here that @pllim voted to restrict the extension specification with the argument that we should do this at some point and might as well start now with this new function.

**Comment by embray** [comment]
I'm not sure I understand the problem.  You could add arguments like `diff_header=True` and `diff_data=True`, then just get the requested extension.  If both are `True` you can just pass the whole extension into the diff interface.  If just `diff_header=True` pass just the extension's header.  If just `diff_data=True` pass in just the extension's data.  If neither are `True` I'm not sure what should happen--I guess it should just be a no-op (it doesn't really make sense to do but it's not necessarily *wrong*)...

**Comment by SaraOgaz** [comment]
Yeah, I had earlier tossed out that idea to try and reduce the number of new keywords I was adding, but that seems unrelated, unless you're saying it's fine to have those be required keywords...

I think I just figured out why there's not a problem.  I was thinking I couldn't add anything to the **kwargs dictionary since I'm using that to pass on any keywords to FITSDiff, but I can just pop out the keywords i'm adding before I pass that on right?

**Comment by SaraOgaz** [comment]
Uh yeah, just checked with someone else, and I don't know why I didn't realize I could do that before... closing this call, thanks @embray

**Comment by SaraOgaz** [comment]
Okay,

I have a working function.  I'll put in a PR while I'm working on adding something into the sphinx documentation.  Also, I don't see many tests in [test_convenience.py](https://github.com/astropy/astropy/blob/master/astropy/io/fits/tests/test_convenience.py), should I add one for mine?

**Comment by SaraOgaz** [comment]
@embray or @pllim (i'm guessing you guys have this power?) we can close this now!
