### ISSUE TITLE
Change Table repr to be nicely formatted

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#3012]
Somewhat driven by #2790, but more inspired by pandas behavior and being annoyed at having to `print()` tables, this issue proposes making the Table repr be essentially the same as the current `str` output from `print()`.  This also makes it more consistent with the IPython notebook behavior.

```
>>> t = Table([[1], [1.0], ['hello']])
>>> t
col0 col1   col2
---- ----  ------
  1   1.0   hello
```

This would go hand-in-hand with the new `info()` methods proposed for `Table`, `Row`, `Column`, which would be the preferred new way to get detailed information about these objects (in a nice-to-read format unlike the current reprs).

The reason this is good for #2790 is that replicating the current Table repr requires either re-implementing the numpy array repr (:-1:) or generating a temporary ndarray representation of the Table purely for passing to `__repr__` (:-1:).  So this takes an end run around that by punting on the current `__repr__` entirely.

**Comment by cdeil** [comment]
@taldcroft – I have a large table (10M rows), and repr is very slow (~20 seconds?).
This computation happened when I tried to look up the source code for the new `info` method, see [example](https://gist.github.com/cdeil/f4280c6ef940cd265b44).
I find this a bit weird and would prefer if `repr` was always fast, even if it means I have to type some letters so that the table gets printed.
Apart from that, I guess it would also be possible to only do the computation what to print on the rows that are actually shown, speeding it up for very large tables?

**Comment by taldcroft** [comment]
Yes this problem has been on my list for a while.  Can you just open a new issue?
