### ISSUE TITLE
Add astropy.cite() function

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3114]
Going through some old notes I came across this one:

https://twitter.com/fperez_org/status/525096002831646721?s=09

`astropy.cite()` would simply print a citation for Astropy, possibly with options for different formats (bibtex by default, say).  

This could probably in some way make use of the CITATION file in the source, although it would have to be copied into an installation as well.  Alternatively if we do offer different formats some kind of template file might be in order.  In any case this doesn't have to be anything deeply fancy.

**Comment by Utkarshdevd** [comment]
@eteq: Is there a citation file for all functions in use for Astropy?
I am trying to work on a toy example, that uses eval function on a list of functions returned by dir() on a particular class
so a user must input to a function like `astropy.cite(class)` to get all citations from imported modules' docstrings

**Comment by embray** [comment]
@Utkarshdevd I'm not sure I follow.  There aren't different citations for different functions in Astropy...

**Comment by Utkarshdevd** [comment]
@embray perhaps I misunderstood this, you need a functionality to attach a citation to a function that is used in a code? so i am thinking of using inspect functionality to get a list of functions used in a file, identify the citable ones and prepare citations from a citation list. for example the Distance measures in cosmology paper by Hogg, 1999 implemented in the cosmology function when used in a user code should look up and add Hogg 1999 as a citation, preferably in bibtex format or directly into a paper.

**Comment by embray** [comment]
@Utkarshdevd that sounds potentially interesting.  Not too many methods in Astropy even have citations in their docstrings, but a few do.

This just has to do with generating a citation for Astropy itself.

**Comment by Utkarshdevd** [comment]
Well, how do I go about a PR, given I have to make a good request for GSoC? I have a toy example that I am trying to apply to the cosmology functions in astropy.

**Comment by bmorris3** [comment]
For another GSoC 2015 PR, I've put together a quick solution along the lines of what Jake suggested in the tweet above, so you can call `astropy.__bibtex__` to get the BibTeX reference. 

It uses regular expressions to grab the BibTeX reference from the CITATION file, assuming that the reference is the contents of the outermost curly brackets in the file. If no CITATION file is found, `astropy.__bibtex__` is an empty string.

**Comment by eteq** [comment]
Since this issue was introduced, there's been a call for more "fine-grained" control over keeping track of citations/acknowledgements for specific functions/classes whatever.  The idea would be that there would be some registry of the citations somewhere, and whenever you imported astropy you'd always get the astropy citation... but then if you called a function that uses a method described in a paper, the registry would automatically get updated with the relevant citation.  Then at the end, you can ask it "give me all the citations I should make for my current python session", basically. 

So to answer @Utkarshdevd's question, there's not citations anywhere yet.  It would *not* work to just search the docstrings, because some of those citations are "how to get more information" rather than "work you should cite if you use this".  Deciding actually how this would be recorded at a per-function level an implementing it is hence an entire GSoC project, not just a quick PR.

That said @bmorris3's approach is a good one for simpler things like just the citation for all of astropy. We might end up wanting to use that on its own if it turns out the numpy/scipy crowd get behind it, even if the above more controlled citation machinery should also be available.

**Comment by embray** [comment]
Yeah, it definitely sounds like a good idea.

**Comment by mdboom** [comment]
Just an FYI on citations: https://groups.google.com/forum/#!topic/numfocus/_BJgDYGc6Q0
