### ISSUE TITLE
Quantity notation proposal: easier way to not copy data on Quantity creation

### ISSUE THREAD

**Issue by demitri** [astropy/astropy#3174]
I recently spoke with @eteq about using `Quantity` in a large code base I'm writing. I added `astropy.units` to most of my numerical quantities, and it slowed down my code a fair bit. It wasn't doing any conversions; at this point the units are basically being carried along for the ride.

A lot of my code takes this form:

```
spectrum.wavelengths = some_array * u.angstrom
```

Eric suggested that part of the slowdown was that `some_array` was being copied as part of the implicit creation of the `Quantity` object, and that I should replace my code with this:

```
spectrum.wavelengths = Quantity(some_array, u.angstrom, copy=False)
```

(This actually slowed my code a bit further, but let's assume that this is the correct thing to do to avoid the hit of needlessly copying the array.) I feel that this a) is a _very_ common use case and b) kills the elegance and readability of using `Quantity`. There are cases (e.g. high performance) where you care about whether a copy is made, and other cases where it doesn't matter. Erik explained why having `copy=True` be the default is preferable (which he can explain here again with an example as I don’t remember in enough detail), however, I would like to retain the elegance of `Quantity` when you don’t want a copy operation.

I propose the following notation: for every defined unit in `astropy.units` there is also defined a second unit with an underscore suffix to indicate a `copy=False` operation. For example, since `u.angstrom` is defined, `u.angstrom_` would also be defined. Under this proposal, this

```
spectrum.wavelengths = some_array * u.angstrom_
```

would be equivalent to this:

```
spectrum.wavelengths = Quantity(some_array, u.angstrom, copy=False)
```

This is an "opt-in" notation: one who knows (or cares) nothing about `copy=False` will not be affected. Other thoughts:
- It's important that this indication be a single character, i.e. `u.angstrom_nocopy` would lead to horrible readability, e.g.
  
  ```
  a = x * u.m_nocopy / (u.s_nocopy * u.s_nocopy)
  ```
- There is the concern of someone who is unfamiliar with the “_” notation reading code that uses it not knowing what is going on. I agree it's not obvious to that person, but I feel the trade off considering how common the use case is and the significant gain in readability when one is concerned with performance (once one knows what it means) is worth the price. It would be on us to teach this distinction early on in tutorials and documentation.
- The choice of the trailing character is obviously arbitrary, but chosen to be as unobtrusive as possible when placed into an equation. It has no analogous mathematical symbol (i.e. using a trailing "*" or "^" would be clearly bad), and any alphabetical character will similarly reduce readability.

Any comments/thoughts welcome.

**Comment by astrofrog** [comment]
I've somewhat changed my mind on the context manager since I'm worried about side effects inside functions called inside the context manager. For example:

```
with u.no_copy():
    some_function(...)
```

It may be that ``some_function`` is not safe if used with views instead of copies.

If people want to keep the context manager idea, one option would be something like:

```
with u.no_copy() as un:
    array * un.m / un.s
```

then this does not impact called functions/methods. I also mentioned some other options https://github.com/astropy/astropy/issues/6578#issuecomment-330988465

**Comment by MSeifert04** [comment]
An alternative would be to use a `numexpr`-like approach that, besides avoiding copies, performs additional optimizations, for example avoids intermediate array, etc.

**Comment by mhvk** [comment]
@astrofrog - I like the idea of having the context manager provide an output "module"; I think one could even do `with u.no_copy() as u:` and no code would need to be changed (but it still wouldn't propagate down).

Overall, I do think a context manager remains the way to go: explicit and context-limited, with the code inside remaining the same.

**Comment by astrofrog** [comment]
I think it would be nice to converge on something for 3.1 (or close this if we think there is no viable solution). So just to recap, it seems there is overall preference for a context manager - but I think that if we are to avoid having side-effects on functions called from the context manager, the context manager needs to not modify the global state of units but rather return a module:

```python
with u.no_copy() as un:
    array * un.m / un.s
```

Will this cause problems if people start to do:

```python
from astropy import units as u

with u.no_copy() as u:
    array * u.m / u.s
```

In particular, what will ``u`` be equal to after the context manager?

There may be cases where using the context manager is a bit obnoxious in terms of having to indent large chunks of code, so what if we were to *also* have a way to do:

```python
import astropy.units.view as uv
```

Would it really be that harmful to have two ways to do it, for different use cases?

Finally, I'm not convinced that I've seen a good argument for not going the much simpler route of simply overloading an operator such as ``|`` or ``**`` and ``//`` (so we can have both * and / with no copy). From a purist point of view, I can see why this might not be satisfying, but I personally feel like this is a case where practicality beats purity. It would be easy to implement, completely backward compatible, and it wouldn't be the first thing people try which would mean it's opt-in. It would be immediately obvious in code that there is something different going on, whereas in the case of the different import or context manager, in long blocks of code, this won't be so obvious. Finally, it makes it easy to mix the copy/no copy modes in code without having to reorder code to have all the views together. I know some people can feel strongly about adding new syntax (PEP 572 is a good example of that...) but I really do think we should at least consider it, rather than dismissing it just because it's not the same as written syntax.

At the end of the day, I do think something would be better than nothing, so most of my opinions are weak - my only strong opinion is that I think it would be dangerous for a context manager to modify the behavior of functions called inside the context.

**Comment by mhvk** [comment]
I was about to write that I didn't really like overloading the operators when I changed my mind... But how about keeping it *very* simple and just defining `array | unit` to mean "join the unit and the array". The nice thing is that since `|` has lower precedence than `*` and `**`, `unit` can be a full unit expression and it will just work. Of course, the implementation is trivial:
```
def __ror__(self, array):
    return u.Quantity(array, unit=self, copy=False, subok=True)
```
Note that this would still make a copy if `array` were a `Quantity` already and had a different unit; I think that is actually a good thing, since then one could use this in a function to assign its input a given unit without risking an in-place change in the underlying array -- but if we decide differently, all it would take was to define `Quantity.__or__` as well and we'd have in-place unit changes (I'd rather define `Quantity.__ior__` for that purpose, though)... As another alternative, `Quantity.__or__` could just mean "raise an exception if the unit is not equivalent", but return `self` otherwise.

p.s. To start bike-shedding: should it be `array & unit`? Or even `array in unit`? (`Unit.__contains__`?) Mildly in favour of `|` is that that is used by [amuse](http://amusecode.org/doc/install/getting-started.html#example-interactive-session) to add units to numbers...

**Comment by astrofrog** [comment]
I agree than ``|`` would be better than ``**`` and ``//``. Not sure about ``in`` as to me it suggests conversion rather than attaching. I don't really mind w.r.t ``|`` vs ``&``, but indeed for consistency with amuse ``|`` might be a good idea (btw, does amuse do copies or views?)

I personally think that ``quantity | unit`` should also not copy, since a copy can be forced with ``quantity * unit``, so if someone took the time to write ``quantity | unit`` they probably mean it? But if we can't agree, then initially it might make snese to not allow ``quantity | unit`` at all and then implement it later if we make a decision?

**Comment by astrofrog** [comment]
To move this forward and get a fresh pair of eyes, what about opening a PR with the ``__ror__`` solution and showing some examples then emailing astropy-dev for feedback on the PR?

**Comment by mhvk** [comment]
@astrofrog - if we go with my implementation, then `quantity | unit` would effectively be equal to `quantity.to(unit)` except that when the units are the same no copy is made. This is quite different from `quantity * unit` where the unit the quantity had and the new `unit` get combined.

**Comment by mhvk** [comment]
I'll make a quick PR...

**Comment by mhvk** [comment]
See #7652

**Comment by astrofrog** [comment]
@mhvk - thanks for the PR! Is there any reason why we can't make ``|`` always be equivalent to ``*`` but just without copies? That is, ``quantity | unit`` would be equivalent to ``Quantity(quantity.value, quantity.unit * unit, copy=False)``? I think having the operator sometimes mean conversion and sometimes mean multiplication will get confusing.

**Comment by mhvk** [comment]
I didn't quite see `|` as an in-place substitute for `*` but rather as a operator that sets the unit, i.e., ensures whatever results is in the unit behind it. The conceptual difference with `*` for non-quantities is then that they are treated as having an unset unit (implying that no change of internal values is necessary) instead of being dimensionless (as is the case with `*`).

For quantities, my suggestion would really be better served by `in`: at least, I think `q in u.m/u.s` is clearer than `q | u.m/u.s`. But that looses the in-place option. Would the intent be clearer if we use `__rshift__`?
Maybe good to see it visually:
```
# __or__
q = array | u.m
q2 = q | u.cm
q |= u.km

# __rshift__
q = array >> u.m
q >>= u.cm
q2 = q >> u.km

# __contains__
q = a in u.m
q2 = q in u.cm
# in-place not possible
```
(Note that on purpose I'm staying away from `%` and `@` since I want an operator that has lower precedence than `*` and `/`, so units automatically get combined first.)

Finally, we could of course define *both* `|` and `&` where `&` "combines" the units as you suggest, and `|` "chooses".

**Comment by astrofrog** [comment]
This was addressed by https://github.com/astropy/astropy/pull/7734! 🎉
