### ISSUE TITLE
make model.name settable

### ISSUE THREAD

**Issue by nden** [astropy/astropy#3251]
#3231 allows models to have name and it can be set by

```
model = Gaussian1D(*params, name="SII")
```

 or by 

```
model = Gaussian1D(*params)
new_model = model.rename(name="SII")
```

which makes a copy of the model. 

There are use cases where it would be convenient to be able to set the attribute after the model is created. One  example is setting the name of a compound model (without making a copy).
Another example is setting the name of a submodel in a compound model without disecting and recreating the compound model. I need this last one for the WCS. 

I haven't looked at that part of the code. How hard is it to make it settable and are there reasons not to?

**Comment by embray** [comment]
After a meeting with @nden I have a better understand of why this is useful.  My preference is still to be able to copy a compound model and update the names of any of its individual components in the process.  But I admit that that *feels* kludgy, and that it would be nice to be able to do something like:

```#python
>>> model['A'].name= 'B'
```

after which, of course, `model['A']` would no longer work, and that component would be addressable as `model['B']`.

I'm still concerned about this implementation-wise though.  The main concern I can think of is how to handle conflicts.  I think maybe somehow a model that is a component of a compound model will have to tie back to the compound model so that it can keep track of the name.  There is *some* precedence for this in how parameters are handled as well, so maybe it can be done without too much trouble.

**Comment by embray** [comment]
Also, for what it's worth, that last use case can be implemented now like (schematically):

```python
>>> a = MyModel(name='A')
>>> b = MyModel(name='B')
>>> c = MyModel(name='C')
>>> d = MyModel(name='D')
>>> e = MyModel(name='E')
>>> m = a + b + c + d + e
>>> m2 = m[:'b'] + m['c'].rename('Important') + m['d':]
```

Unfortunately there are two inconveniences to this.  The first is that it's not obvious how to get the names of the models before and after 'C'.  The second is that there is no obvious way to get the operators that combine 'C' with those models on the left and on the right.  I think those issues should be addressed as well, but I'm not swimming in ideas at the moment.

**Comment by astrofrog** [comment]
@nden @embray - is this critical for 1.0 or can I remove the milestone?

**Comment by nden** [comment]
Not critical for 1.0 in my view.

**Comment by astrofrog** [comment]
@nden - thanks for clarifying!

**Comment by embray** [comment]
Should still get done sooner rather than later, but I'm a bit stuck on how to go about it.  I suppose there is one "obvious" way, but it will make the code that much more of a sticky mess :(

**Comment by pllim** [comment]
I think the name is settable now, as implied by the test in #5741, so closing.

**Comment by nden** [comment]
It's not settable until (if) #5741 is merged.
