### ISSUE TITLE
Unify section header characters

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#328]
This is a placeholder if someone has the desire to unify the section header characters throughout the astropy docs to use the same ordering, which is now standardized as `* = - ^ " + : ~`.

I wrote a quick script to determine all unique sets of character orders used in the RST section headers.  I _think_ it works, but this was fast without too much test.  It's here in this gist: https://gist.github.com/3208992.

Upshot: for astropy RST files in docs/ the sets we use are:

```
  % find . -name "*.rst" | xargs ./header_chars.py
  ...  # bunch of files and their section orderings
  #*=
  *=-"
  *=-^"
  -^".
  -^">
  =-^"
  =-`
```

You can find which files correspond to a particular set with (e.g.):

```
  % find . -name "*.rst" | xargs ./header_chars.py | grep '=-`'
  ./wcs/history.rst =-`
  =-`
```

It's probably not much work to take this script and extend to actually do the fixing.

**Comment by AMAN3003** [comment]
@taldcroft  I have solved this issue and tested it. Do I need to submit the patches and test run or only the patches.This was my first so apoloize if I had not follow any protocol.

**Comment by AMAN3003** [comment]
I was unable to commit and pull  so i have the link of the script please review it and pull it .

https://gist.github.com/AMAN3003/181c8760c65f5f3a8336

**Comment by embray** [comment]
@AMAN3003 I think the open issue here was to change @taldcroft's script to edit the files passed as arguments to it, so that they all use mutually consistent section ordering (what's not clear is which ordering the should use?  The one from the first file?  The most common one?  One specified on the command-line?  Maybe all of those could be options...)

I admit I'm a bit puzzled by what your revision to the script is solving...

**Comment by taldcroft** [comment]
I never am able to find a reference in our developer docs on what the ordering is supposed to be.  Am I being blind or is does that not exist?

**Comment by embray** [comment]
@taldcroft I could swear I documented a recommended ordering once.  But now I can't find it either.  Maybe I just mentioned it in some issue somewhere, but it never went into the docs on [writing documentation](http://docs.astropy.org/en/stable/development/docguide.html#documentation-guidelines).  Ultimately it doesn't matter much as long as it's consistent within a file, but it would be nice to have a standard...

**Comment by AMAN3003** [comment]
@taldcroft  in your script https://gist.github.com/3208992.     
i edited the files passed as arguments to it, so that they all use mutually consistent section ordering
(both the command line and the file should be consistent)
line no 87 "header_chars_list[:-1], header_chars_list[1:] " hc0 and hc1 are not giving the reverse in case of alphanumeric character.both ,header_chars_list[:-1] and header_chars_list[1:]  are returning the same .so the ordering is not check properly. so in my script i properly reverse the alphanumerics.and then check the ordering by your logic

**Comment by taldcroft** [comment]
@AMAN3003 - I don't see any code in https://gist.github.com/AMAN3003/181c8760c65f5f3a8336 that is fixing the input .rst files to use a common ordering.  I would say that the code should determine the most frequent ordering that is in the existing files in astropy and then use that as the standard.

About the ordering and reversal issue you mention, your description is not very clear.  Can you give an example of what you mean?  Perhaps showing the original code output in a specific case where it is wrong, and then what it looks like after fixing.

**Comment by AMAN3003** [comment]
okk i understand the issue and i am working on this issue

**Comment by AMAN3003** [comment]
@taldcroft  do you want me to update the rst file with the ordering -=* to * = - ^ "(standard ordering )
