### ISSUE TITLE
stable tag or branch?

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3302]
The Astropy git repo has a branch called "stable" that we always update at the end of the release to point to the latest stable release (see step 21 [here](http://docs.astropy.org/en/stable/development/releasing.html)).

However, there is an "annoyance" in more recent versions of zest.releaser that when you do a release it automatically does this for you, except it creates (or updates) a _tag_ called stable, rather than a branch.  This has led to a bit of confusion in the past since we wind up with both a tag and a branch called stable.

I end up just deleting the tag.  Though in retrospect I think it makes more sense that it's a tag rather than a branch (just a tag that happens to change where it points from time to time, but it does not necessarily represent a branch that development should split off from).  Or does it?

**Comment by bsipocz** [comment]
We still do the ``stable`` branch, rather than the tag (that nevertheless comes back from people's forks). Ideally we need to make a decision on this, and close off this issue. 

Milestoning this to 2.0.1 as a deadline to make that decision (doing nothing is also a decision in my book for keeping everything as is).

cc @eteq @astrofrog @taldcroft as release coordinators and committee

**Comment by taldcroft** [comment]
This makes more sense to me as a tag than branch.  But I don't have a strong opinion on this.

**Comment by bsipocz** [comment]
The same question stands for 'lts': https://github.com/astropy/astropy/pull/6566#issuecomment-331658528

Let's make a decision, and I'll tag/branch it accordingly.

**Comment by astrofrog** [comment]
Having thought about this a bit, I think I agree this should be a tag, provided that it's not easy to over-write a tag accidentally.

**Comment by bsipocz** [comment]
OK, so I've added an LTS tag for the latest 2.0.2 release. I'll set it up for RTD, too.

How should I proceed with stable? Delete the branch, and tag the latest release as stable?

**Comment by pllim** [comment]
Is this how it is going to work?
```
LTS -> 2.0.x
stable -> 3.x (when released)
latest -> dev
```

**Comment by bsipocz** [comment]
Yes. Though unlike "stable" and "LTS", "latest" is not a tag in the git repo, but automatically pointed to the top of master by RTD. Stable so far is a branch, but I'm reluctant to delete it before many people agrees.

**Comment by pllim** [comment]
> Delete the branch, and tag the latest release as stable?

👍 from me!

**Comment by bsipocz** [comment]
OK, so I go ahead with this given that 2 coordinators among others above prefers having tags, and no one showed preference for keeping it as a branch.

**Comment by astrofrog** [comment]
I've added LTS to the list of versions to build on RTD

**Comment by bsipocz** [comment]
Thanks @astrofrog. I'm updating the release instructions, too.

**Comment by bsipocz** [comment]
Reopening as the stable branch is back. Someone needs to investigate why the RTD stable become the dev version after doing the tagging. Or just take the decision that we go with branches, and create a branch for LTS, too and delete the current tags.

**Comment by bsipocz** [comment]
Copying @eteq's comment from slack:

@bsipocz - I just noticed that the rtd “stable” build is wrong (points to a dev version).  It looks to me like this is because “stable” is now a tag instead of a branch.  It also looks like the most recent commit on that tag is the 2.0.2 release - did you make that tag (and delete the branch)? (edited)


[5:20] 
It may not be recorded anywhere other than my head, but there’s a “quirk” of RTD that makes it not update correctly for things that are tags. (I asked their dev team once and they said something like “tags aren’t meant to be updated so we don’t support that”.)  A tag makes more sense conceptually, but it turns out that doesn’t work with RTD


[5:23] 
At any rate, I’ve switched it back to being a branch and hopefully that will make RTD right again.  This brings up a related question, though: do we want the “LTS” tag to instead be a branch as well?  For whatever reason it seems to be *correct* right now, but if what the RTD devs told me that one time is true we can’t count in it if it is a tag… (edited)

**Comment by eteq** [comment]
I agree with my comments above... :trollface:

**Comment by astrofrog** [comment]
We've been using a branch for a long time now, and the release docs support this (https://docs.astropy.org/en/latest/development/releasing.html). I'm going to close this.
