### ISSUE TITLE
Flag collection part of NDData?

### ISSUE THREAD

**Issue by wkerzendorf** [astropy/astropy#3307]
Hi @mwcraig, just a quick question. Should this be gone: https://github.com/astropy/astropy/blob/master/astropy/nddata/flag_collection.py as part of the big NDData restructure you started? If not please close this issue (sorry, I'm not really up-to-date how far that went).

**Comment by mwcraig** [comment]
@wkerzendorf -- ``FlagCollection``  wasn't discuss explicitly in the APE. My thought was to let it linger for a bit and see if ti goes anywhere. If so, great, if not we'd pull it. Thoughts, @astrofrog?

Relevant discussion in the APE is at https://github.com/astropy/astropy-APEs/pull/8#issuecomment-66697083 and https://github.com/astropy/astropy-APEs/pull/8#issuecomment-67177256

**Comment by hamogu** [comment]
Since there was no further input for ~1 year (I guess that's "let it linger a bit"), can we just close this issue? Given that we have > 500 open issues, it's very unlikely that somebody even finds this one to continue the discussion - more likely, they would open a new issue.
(That's not to say that should be no flags, I just don't think that keeping this issue open will help the decision.)

**Comment by mwcraig** [comment]
Agreed, @hamogu, thanks for catching this.
