### ISSUE TITLE
Angle array formatting shows up as raw latex in IPython notebook

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#3332]
With Python 3 and Astropy master I find that Angles are not displayed nicely in the IPython notebook ... it works for scalars, but not arrays:

![screen shot 2015-01-22 at 10 45 04](https://cloud.githubusercontent.com/assets/852409/5853427/c708eec2-a223-11e4-968d-8953988394db.png)

I guess this is a bug?

Actually I don't see why complicated formatting like dms and latex generation should be used by default here ... but I guess this discussion already took place and is not up for debate?

**Comment by astrofrog** [comment]
There was an issue for this before with quantities:

https://github.com/astropy/astropy/pull/2271

Maybe it would be worth looking at the solution there to see if it can be applied to Angle.

**Comment by eteq** [comment]
Oops, missed this one, but  #3480 should fix it.

**Comment by eteq** [comment]
Oh, and to address @astrofrog's suggestion here: it turns out using the `Quantity._repr_latex_` is non-trivial because `Angle` has its own `to_string` that operates different from the standard `Quantity` stringifying stuff because it has to support extra options. #3480 does something more like #2271, but less general because it can assume its operating on angles.  But it also has the extra complication that it has to deal with strings with backslashes.  Turns out numpy doesn't do this very well and tends to double them for no reason.  So #3480 also eals with that.
