### ISSUE TITLE
Affiliated package instructions: editing .travis.yml

### ISSUE THREAD

**Issue by PBarmby** [astropy/astropy#3404]
In the docs [How to create and maintain an Astropy affiliated package](https://github.com/astropy/astropy/blob/master/docs/development/affiliated-packages.rst), step 8 for "Managing the template files manually" says edit `.travis.yml` but not what the edit should be. Perhaps this edit is not for people like me who don't know what they are doing, but in that case the text shuold probably say that too.

**Comment by embray** [comment]
:+1: I've gotten a lot of questions lately, actually, about editing the .travis.yml for affiliated packages.  I've mostly had to tell people I have no idea because I didn't write it and don't know how it's intended to be used or edited.  But just from my personal experience with that it seems to me that could be better elucidated what should be done, if anything, with the .travis.yml.

**Comment by astrofrog** [comment]
@PBarmby - I'll try and provide some clarification, but basically in the file itself there should be comments indicating which parts should be edited. More soon.

**Comment by tepickering** [comment]
looks like this should be closed here. @bsipocz will check that this is indeed documented at https://github.com/astropy/package-template and, if not, reopen an issue there.

**Comment by bsipocz** [comment]
The documentation on this can still be extended, so a follow-up issue for this is https://github.com/astropy/package-template/issues/317
