### ISSUE TITLE
setup.py build --debug being flaky

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3410]
When I run `./setup.py build --debug` (or build_ext directly) the first extension module to build is the `_wcs` module, and that seems to honor the `--debug` flag, adding `-fno-inline -O0 -g` (strangely this also results in an error

```
astropy/wcs/src/distortion.c:180: error: ISO C90 forbids mixed declarations and code
```

that I don't get otherwise--I'll submit a PR for that).

But what's weirder is that after WCSLIB and the Python wrappers are built it gives up and doesn't include the debug flags in any further module compilations, at least as far as I can tell by eyeballing it.

**Comment by embray** [comment]
Oh, well, it looks like this is easily explained.. it seems that `astropy.wcs.setup_package` itself *specifically* adds those flags if building in debug mode.  All `--debug` adds by default is `-g`.  I think it should do `-g -O0` at a minimum, and `-fno-inline` isn't bad to have either.  I'll see if we can change this....

**Comment by mdboom** [comment]
Yeah -- that stuff in `astropy.wcs` predates astropy, IIRC.  Having a more general solution that worked across everything would be preferable.  It's probably not too hard since everything goes through the `get_extensions` callback to just go through all of the extensions at that point and fix up the cflags there.

**Comment by bsipocz** [comment]
@astrofrog - can we close this now that we move away from the helpers, and even then I feel it's an issue for `extension_helpers` and not the core package itself.

**Comment by astrofrog** [comment]
The ``--debug`` flag is actually not handled by extension-helpers but is now just handled directly in our ``setup_package.py`` files - see https://github.com/astropy/astropy/pull/9731. However since the way we add the flag has changed now, I'm inclined to just close this and if anyone runs into this again in future they can open a new issue.
