### ISSUE TITLE
consider setting fittable=False for join compound models

### ISSUE THREAD

**Issue by nden** [astropy/astropy#3444]
In general compound models created with the jjoin `&` operator should be fittable (assuming all submodels are) but since they increase the output dimensions of the compound model and fitters work only with up to 2 output dimensions this will not work with the current fitters. I think @embray has a plan to generalize the fitters to work with arbitrary number of inputs. When this is implemented joined models could be fitted. Until then perhaps it's best to set the `fittable` attribute of such a model as `False`.

**Comment by embray** [comment]
That's correct, re the fitters.  I don't know that it's worth changing this since *in principle* anyone could define a fitter *right now* that works on arbitrary in/out dimensions, so why limit it?

More importantly is to just make sure that unsupported fitters will give a useful error message instead of just crashing in weird ways.  Is that the case currently?  I'm not sure...  (I think it is).

**Comment by embray** [comment]
To go further, instead I'd consider removing the `fittable` attribute altogether, at least at some point.  I don't know--maybe there are some models where the concept of "fitting" really truly never applies?  Otherwise, the more important information is "Will this model work with this fitter?"  And I think there needs to be information both on a model, and potentially on a fitter, by which a fitter can determine whether or not to accept a given model.  (This also plays in to the open issue of allowing models to have one or more default fitters that are recommended for use with them.

**Comment by nden** [comment]
AFAIK this is not a problem any more, perhaps fixed by  some  work on `Mapping`.
