### ISSUE TITLE
Implement Lupton et al. RGB color composite algorithm

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3452]
It might be worth seeing if we can implement the RGB algorithm from [Lupton et al.](http://arxiv.org/abs/astro-ph/0312483) into `astropy.visualization`.

cc @barentsen

**Comment by barentsen** [comment]
@astrofrog The snippet below is what I am using now, which can no doubt be optimized.  Of course `values` has a very specific meaning in this stretch, because it *has* to be a MxNx3 (RGB) array.  Another difference is that the constructor takes the "actual" stretching function as an argument, which may cause confusion.

(PS: Are you aware that all the stretches in `astropy.visualization.stretches` have an `out` parameter, but none of them actually seem to support it?)

```Python
class LuptonColorStretch(BaseStretch):
    """
    Stretch a MxNx3 (RGB) array using the colour-preserving method by
    Lupton et al. (arXiv:astro-ph/0312483).

    Parameters
    ----------
    intensity_stretch : object derived from `BaseStretch`
        The stretch to apply on the integrated intensity, e.g. `LogStretch`.
    """
    def __init__(self, intensity_stretch):
        super(LuptonColorStretch, self).__init__()
        self.intensity_stretch = intensity_stretch

    def __call__(self, values, out=None, clip=True):
        """Transform the image using this stretch.

        Parameters
        ----------
        values : `~numpy.ndarray` of shape MxNx3 (RGB)
            The input image, which should already be normalized to the [0:1]
            range.

        Returns
        -------
        new_values : `~numpy.ndarray`
            The transformed values.
        """
        values = _prepare(values, out=out, clip=clip)
        intensity = values.sum(axis=2) / 3.
        old_settings = np.seterr(divide='ignore', invalid='ignore')
        for channel in range(3):
            values[:, :, channel] *= self.intensity_stretch(intensity) / intensity
            values[:, :, channel][intensity == 0] = 0
        np.seterr(**old_settings)
        maxrgb = values.max(axis=2)
        maxrgb_gt_1 = maxrgb > 1
        for channel in range(3):
            values[:, :, channel][maxrgb_gt_1] /= maxrgb[maxrgb_gt_1]
        return values

    @property
    def inverse(self):
        raise NotImplementedError
```

**Comment by astrofrog** [comment]
@barentsen - thanks! Can you clarify what you mean by ``out`` not being supported?

**Comment by astrofrog** [comment]
Here is an example of using ``out``:

```
In [1]: from astropy.visualization import SqrtStretch

In [2]: import numpy as np

In [3]: x = np.array([0.1,0.2,0.3])

In [4]: s = SqrtStretch()

In [5]: y = np.zeros(3)

In [6]: s(x, out=y)
Out[6]: array([ 0.31622777,  0.4472136 ,  0.54772256])

In [7]: y
Out[7]: array([ 0.31622777,  0.4472136 ,  0.54772256])
```

**Comment by astrofrog** [comment]
For this functionality, it might make sense to not inherit from basestretch - instead maybe we should have  a function that takes three arrays and a stretch instance, and returns the RGB arrays? We could also imagine returning a PIL object (just brainstorming)

**Comment by barentsen** [comment]
Please ignore my silly comment about `out`.  I failed to notice that `_prepare` takes care of dealing with it. All is well.

I agree there isn't any point at all in having this inherit from basestretch.  How about a `ColorImage(r, g, b)` class with methods `stretch()`, `as_array()`, `as_image()`, `as_fits()`, `imsave(fn)`?

**Comment by sahmed95** [comment]
Is anyone else working on the issue ?

1. How are the r,g,b values passed. (as FITS object, HDU, ndarray, list ??)

Instead of making the user input r,g,b values, we can also simple have a numpy array as generated by Matplotlib's image using imread(filename), or generated as an Image instance by "Image"

2. Should normalization be done using interval(array) by importing /astropy.visualization/MinMaxInterval ?
Will the user pass normalized r,g,b arrays or should the stretch function carry out the normalization inside the stretch def
 
3. In the paper, logstretch is recommended. Should the stretch function be user specified or fixed as log. Should use existing stretch methods in stretch.py ?? These will again require some use of BaseStretch. Should it be avoided ? 

4. What should be the min and max values for the transformation ? 

Any help would be appreciated. I am not very familiar with the way images are handled in astropy....

**Comment by larrybradley** [comment]
This was implemented in https://github.com/astropy/astropy/pull/5535.
