### ISSUE TITLE
Inconsistency in creating new FITS file: BITPIX value forced to -64

### ISSUE THREAD

**Issue by mrkite92** [astropy/astropy#3487]
Dear astropy gurus,

I need to create stamps from (quite big) FITS images from the public VVV survey (from the ESO VISTA telescope). The original images are coded with BITPIX = 32. If I read those images with the option do_not_scale_image_data=True, the resulting stamps created using astImages.clipImageSectionWCS from astLib show a huge difference of background level, compared to the original one, say from 500 to 2500. This is of great consequence for the next step of processing photometry.

Conversely, if I set do_not_scale_image_data=False, the background level is kept unchanged, but the BITPIX value is set to -64, whatever I attempt to preserve the original 32 value. As I need to propagate the original WCS solution to the stamps, I coded:

```
WCS = astWCS.WCS(img)
IMAGE = hdulist[0].data
if not WCS.coordsAreInImage(ra_target, dec_target):
     print 'Target', id_target, 'out of image'
     hdulist.close()
      continue
      try:
          SUBIMAGE = astImages.clipImageSectionWCS(IMAGE, WCS, ra_target, dec_target, box_arcmin / 60., returnWCS=True)
      except:
          continue
new_header = fits.Header(hdulist[0].header)
new_header['BITPIX'] = 32
new_header['CRPIX1'] = SUBIMAGE['wcs'].header['CRPIX1']
new_header['CRPIX2'] = SUBIMAGE['wcs'].header['CRPIX2']
new_stamp = fits.PrimaryHDU(data=SUBIMAGE['data'], header=new_header, scale_back=False)
new_stamp.writeto(os.path.join(dir_stamp, stamp_img))
```

Whatever the value of the scale_back option, the resulting BITPIX value is always -64

And I do need to preserve the mandatory BITPIX=32 for the next step of processing...

Any hint welcome,
Cheers,
JB

**Comment by mdboom** [comment]
The BITPIX is automatically set from the data being passed in to the HDU constructor.  What is the dtype of `SUBIMAGE['data']` here?  If it's not `int32`, you'll need to explicitly convert it first.

**Comment by embray** [comment]
As a general principle with this library you should not manually set header keywords that relate to the physical type and dimensions of the data.  Setting `header['BITPIX']` manually doesn't do anything because it will always ensure that in the end that keyword is set to reflect whatever is in the `.data` attribute, though it may also depend on if you've called methods like `.scale()`.

(Note: the unfortunate double-negative `do_not_scale_image_data=False` is the default behavior.  It means that any 'BSCALE' and 'BZERO' keywords will be applied to the data when it is made available to the user, and will of course scale to float64 for best accuracy.  Since these are the actual "physical" values and not quantized integer levels it makes sense that you'd be seeing this jump in background levels.

When you write
```
new_stamp = fits.PrimaryHDU(data=SUBIMAGE['data'], header=new_header, scale_back=False)
```
the `scale_back` here does nothing, as it only applies to existing HDUs from an opened file (it just means that before saving changes to the file scale the data back to integer values).  But because you're creating a new HDU this has no effect since there is no "original" scaling.  

Instead, when you create the new HDU, you can use the [`scale`](http://docs.astropy.org/en/v0.4.3/io/fits/api/images.html#astropy.io.fits.ImageHDU.scale) method to re-apply the original scale factors, and this will rescale the data properly as well.  Granted, trying to find out the original scale factors is a pain since when you open an image with `do_not_scale_image_data=False` it actually hides away the original bscale and bzero values for that data.  It might be nice to have a better way at gettting at that.

You can read more about scaled image data here: http://docs.astropy.org/en/v0.4.3/io/fits/usage/image.html#scaled-data

**Comment by embray** [comment]
Since the reported behavior is expected I'm closing this issue, though please feel free to follow up in the comments.
