### ISSUE TITLE
Parsing TUNIT header keyword values

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#3517]
I have source catalogues in binary fits tables, where units of the columns are defined in the header with the corresponding 'TUNIT' keywords.  It would be great if these could be directly parsed. Although I'm not sure whether 'RADIANS' in this formatting follows the fits standard (I guess not), but this is unambiguous (and recognized by the parser) and the ESO archive is full of files like this one. 

Somewhat similar to #2933.

```
TTYPE59 = 'RA      '           / label for field  59                            
TFORM59 = '1E      '           / data format of field: 4-byte REAL              
TUNIT59 = 'RADIANS '           / physical unit of field                         
TTYPE60 = 'DEC     '           / label for field  60                            
TFORM60 = '1E      '           / data format of field: 4-byte REAL              
TUNIT60 = 'RADIANS '           / physical unit of field


In [167]: u.Unit(hdu[ext].header['TUNIT59'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-167-fabb447b9b21> in <module>()
----> 1 u.Unit(hdu[ext].header['TUNIT59'])

/home/bsipocz/devel/astropy/astropy/units/core.pyc in __call__(self, s, represents, format, namespace, doc, parse_strict)
   1777                            .format(s, format_clause, six.text_type(e)))
   1778                     if parse_strict == 'raise':
-> 1779                         raise ValueError(msg)
   1780                     elif parse_strict == 'warn':
   1781                         warnings.warn(msg, UnitsWarning)

ValueError: 'RADIANS' did not parse as unit: At col 0, RADIANS is not a valid unit. Did you mean radian?
```

**Comment by pllim** [comment]
My recommendation would be to convert 'RADIANS' to 'radian' in your script before passing it into `Unit` constructor.

**Comment by mdboom** [comment]
Both the FITS standard and the CDS unit standard (which is often used in FITS files) says it should be spelled `rad`.  In order to ensure that these files are interchangeable with other tools, you should report this as a bug to the tool or project that produced this file.  FITS has a long history of using units "for human eyes only" so there are a lot of these things in the wild that haven't been caught.

@pllim's suggestion of fixing the unit yourself outside of astropy is a good one, if you trust the source of the file and know how to map it unambiguously.

You should be passing the kwarg `format="fits"` or `format="cds"` to the `Unit` constructor since the unit is coming from a FITS file.  You could also pass `parse_strict='silent'` if you don't want the exception, but in that case you'll get an unrecognized unit out, which can't be used for much of anything.

**Comment by pllim** [comment]
`pysynphot` also has this behavior where it would insert some non-standard `TUNIT` but it has been used for so many years that it is quite impossible to update all the existing FITS files now. Therefore, the only viable solution in that case is to manually convert the value to a valid name before passing it into `Unit`.

**Comment by bsipocz** [comment]
@mdboom @pllim - Thanks for the suggestions. Actually it was a question more about the policy (and whether there is a plan to have an option to automatically accept the suggested alternative (now only listed in the error or warning message).  As the workaround is quite simple for this example, and I could as well hard wire the unit without checking it in the header (as I know it's hard wired in the pipeline producing those survey catalogues (and it is very unlikely to be changed in future versions)).

**Comment by pllim** [comment]
Incidentally, this was discussed in the mailing list. Maybe this is the solution you're looking for?
http://mail.scipy.org/pipermail/astropy/2015-February/003607.html

**Comment by bsipocz** [comment]
@pllim - Indeed, and I like this option.

**Comment by embray** [comment]
The more of these we catch the better, since I really do want to integrate unit support deeper into the FITS reader, with Headers that return Quantity objects for keyword values, etc.  Units that looks like units but can't be parsed will not be converted to Quantity but should probably be yelled about, at least by default...

**Comment by mhvk** [comment]
@pllim - thanks for the link; neat!  More generally, since these questions about fits headers come up time after time, it does suggest it is worth documenting work-arounds.

**Comment by pllim** [comment]
@embray , try not to be too strict, or you will break HST pipelines! :ghost:

**Comment by mdboom** [comment]
@pllim: The HST pipelines will continue to work just fine, ignoring the units for the most part as they always have.  It's only when trying to *do something* with the units that there should be any problem :wink:

**Comment by embray** [comment]
@pllim @mdboom Perhaps, though it's true that if we suddenly start returning `Quantity` objects from headers, there could be calculation that break due to unit incompatibility.  I'd say that's a good thing anyways.  But regardless when this feature is introduced there should probably be a flag to disable it.

**Comment by pllim** [comment]
@bsipocz , can this be closed now that Table supports units and has unified I/O to FITS?

**Comment by bsipocz** [comment]
@pllim - Sure, thanks for merging the fix.
