### ISSUE TITLE
Automatically ignore NaN values in fitting

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3575]
Currently astropy.modeling returns incorrect results if NaN values are present. We should either raise an error, or (better) simply filter out NaN values automatically. Example of non-functioning code:

```
In [1]: import numpy as np

In [2]: from astropy.modeling import models, fitting

In [3]: x = [1,2,3,4,5]

In [4]: y = [2,2,np.nan,2,2]

In [5]: m_init = models.Const1D(amplitude=1)

In [6]: fit = fitting.LevMarLSQFitter()

In [7]: m_best = fit(m_init, x, y)
WARNING: Model is linear in parameters; consider using linear fitting methods. [astropy.modeling.fitting]

In [8]: print(m_best)
Model: Const1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Parameters:
    amplitude
    ---------
          1.0
```

**Comment by pllim** [comment]
If you choose to automatically exclude NaNs, there should at least be a warning that it was done.

**Comment by astrofrog** [comment]
Yes, I agree

**Comment by embray** [comment]
I think this is primarily a limitation of the `scipy.optimize` routines used currently by most of the fitters.  For example the one used in your example is:

http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html

The docs actually aren't terribly clear about what happens with NaNs, but it does say of the objective function "must not return NaNs or fitting might fail", which implies in this case that if any of the inputs/outputs contain NaNs this will also result in NaNs being returned from the objective function.  But it seems like it doesn't produce any errors or warnings--it just doesn't work.

I wonder how it would work, if at all, with maskedarrays.  Otherwise we'd need some way around that...  Optionally raise an error on NaNs, or allow them to be ignored/dropped from the fit automatically.

**Comment by embray** [comment]
And since one in principle could write a fitter that supports missing values, this conditioning should be something the fitter does depending on whether or not it knows it supports missing values natively.

**Comment by hamogu** [comment]
The most common way to fit  array that has nans in it is probably (continuing from above):
```
x = np.array(x)
y = np.array(y)
index = ~(np.isnan(x) | np.isnan(y))
m_best = fit(m_init, x[index], y[index])
```
However, I believe it should be on the user to either do this him/herself and to actively set a switch to ignore nans.

A related issue are infs. In most cases, arrays with infs in will not give meaningful fits either (and I might want to ignore them). If we implicitly ignore nans, we should state clearly in the docs that that does not affects infs.

**Comment by embray** [comment]
I agree--I think ignore-nans should be opt-in, and it could just do exactly what you described above, as a convenience.  We could treat inf and nan together.

**Comment by astrofrog** [comment]
I'm fine with whatever most people are ok with, but just out of curiosity, in what cases is it not appropriate to ignore NaN values? (i.e. why not make it opt-out?)

**Comment by pllim** [comment]
```
If we implicitly ignore nans, we should state clearly in the docs that that does not affects infs.
```

I don't see why `nan` and `inf` have to be treated separately. Either I want to only use `isfinite` data or not.

**Comment by hamogu** [comment]
@astrofrog : I might not be aware of NaN values. Let's say I want to fit a spectrum. That spectrum should not have any NaN values in it. If it has, that typically means that something earlier went wrong and I would like to know about it before I decide it all the bins that are NaNs can be ignores. You might say, I should check that after every step, but in practice, most people don't. They just run with it and assume "If the fit works, the steps before must have been OK". That's where an opt-in is the safer option. If I opt-in, I presumably thought about it.

**Comment by embray** [comment]
In principle one could also implement an optimizer that handles invalid values implicitly in the algorithm. I don't know about any such thing personally but my depth of knowledge in that area is limited.  In any case, the possibility shouldn't be ruled out, which is why I think we shouldn't let the user think that handling invalid values is just implicit.

**Comment by hamogu** [comment]
I can imagine a situation like @embray mentions: I have a code that calculates the properties of a shock front between stellar wind and disk wind in young stars as a function of distance from the star. Under certain conditions the shock front only forms up to a finite distance and the equations will give NaN if evaluated for larger distances.
This project predates `astropy.modelling`, so I used a different fitting package, but one (among several) approaches would be: Populate a vector with observational quantities for the shock front. Fill with NaN where no shock is observed (using NaN as missing values is quite common). In that case, I want an optimizer that checks that the shock simulation gives me NaN for all distances where the observations give me NaN. (Defining the appropriate figure of merit for that fit is a different matter and I am not saying that this would be the best way to set up the fit. I am just supporting @embray that we should not rule out using NaNs in the fit for all possible fitters and models.)

**Comment by hamogu** [comment]
@pllim: I just read your comment. In the example I just gave, inf and NaN have a very different meaning. A "NaN" for the shock temperature means "value is at distances so large that it is beyond the shock front"; an "inf" would be "Temprature is higher than max(float)". So, a "NaN" might be a good fit (if the shock is indeed not observed at that distance), and "inf" would be a bad fit.

Again, there are other ways to set up the fit (e.g. I can have an additional parameter that contains just the largest distance that the shock reaches and then define an optimizer that ignores all values at larger distances), but I would be cautious to rule out using NaN and inf as "valid" values.

**Comment by jehturner** [comment]
Yes, there should be **some** way to ignore bad/masked values -- otherwise (for example), I'm not sure how one can implement fitting with sigma rejection properly, similar to IRAF fit1d. I'm just wondering how to go about that; things would get very awkward if I actually had to remove pixels from the input arrays (ie. make them shorter), since I'm fitting N-1D-model sets simultaneously to potentially-multi-dimensional arrays and would end up with lots of vectors of different lengths to fit and then reassemble into the original shape. Perhaps for now I'll just have to substitute the mean value of each vector or interpolate or something, instead of ignoring the pixels.
