### ISSUE TITLE
Masked tables lose mask when written to HDF5 files.

### ISSUE THREAD

**Issue by matteobachetti** [astropy/astropy#3597]
Very quick example:

```
In [1]: from astropy.table import Table

In [2]: import numpy as np

In [3]: a = Table(masked=True)

In [6]: a['x'] = np.arange(10)

In [7]: a
Out[7]: 
<Table masked=True length=10>
  x  
int64
-----
    0
    1
    2
    3
    4
    5
    6
    7
    8
    9

In [9]: a.write('bu.hdf5', path='bu')

In [10]: b = Table.read('bu.hdf5', path='bu')

In [11]: b
Out[11]: 
<Table masked=False length=10>
  x  
int64
-----
    0
    1
    2
    3
    4
    5
    6
    7
    8
    9
```

**Comment by embray** [comment]
Related: #3567, #3568.

**Comment by matteobachetti** [comment]
@embray the above PR does solve the related issues, but not this one, and I don't really know how to address this. Any pointers?

**Comment by embray** [comment]
I'm not really the one to ask. I don't deal with masked tables.  It's certainly not something that's simply natively supported in HDF5.  There's no sense in which HDF5 knows anything about "masked data"--one has to invent some kind of convention for storing data along with a mask in and HDF5 format (along with code that knows how to reconstruct the masked Table object from reading that convention).  Since it's a special convention built on top of HDF5 users would have to opt into it.  That's what the issues I referenced above are about.

**Comment by taldcroft** [comment]
Closing this as the concept of a "masked Table" is no longer relevant now that masked and unmasked columns can be stored in a Table. Masked tables are only recommended for legacy or specialize applications.
