### ISSUE TITLE
Link to recent docs is broken in some cases

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3638]
As pointed out by Molly Peeples on twitter, the link in this page:

http://docs.astropy.org/en/v0.3/api/astropy.cosmology.funcs.luminosity_distance.html

is broken. This is because the new API no longer contains the standalone functions. In general, I wonder whether for any links that no longer exist we should not add an additional note such as 'This page no longer appears to exist in the new documentation' and then link to the top-level page of the docs?

Only issue is, we can't really update the 0.3 docs now :( But maybe we can make this work in future?

Also, given that google keeps returning old versions of the docs, I wonder how useful it is to keep the old versions online. Maybe we should just keep the two latest versions?

**Comment by mdboom** [comment]
In order to make this work, it has to be dynamic, because old versions of the docs can never predict what future versions will look like.  How does this work now?  Is this something readthedocs provides for us?

It would be nice if the 404 page went to the table of contents of the documentation version in question, rather than a generic readthedocs page.  There an old issue about making that possible on readthedocs (https://github.com/rtfd/readthedocs.org/issues/353), but as far as I can tell it doesn't exist yet.

We could probably emulate this with some JavaScript: try an AJAX request of the page, if it fails redirect to the table of contents (or maybe the package root).

**Comment by astrofrog** [comment]
I just realized that we have another option - which is to set up redirects in the new docs. This can be easily done with this Sphinx plugin:

https://github.com/glue-viz/glue/blob/master/doc/redirect.py

and this type of file:

https://github.com/glue-viz/glue/blob/master/doc/redirects

This might be the cleanest solution. We could certainly start off by generating the ones needed for the ``_generated`` -> ``api`` move, then for others we could link e.g. the broken one above to the top-level of ``cosmology``.

**Comment by embray** [comment]
Oh, I always assumed that link would just take you to the index page of the latest docs.  A search in the docs for the old function would bring up the changelog entry mentioning that it has been removed.

**Comment by bsipocz** [comment]
With adding robots.txt to RTD and removing the old versions, I feel it's safe to close this issue as "worked around" if not fixed.

Feel free to reopen if you think otherwise.
