### ISSUE TITLE
Adjusting the Left/Right/Center alignment of latex tables

### ISSUE THREAD

**Issue by agroener** [astropy/astropy#3645]
I don't know if this is already a thing, but it would be cool to be able to adjust the left/right/center alignment of columns of a latex table written out to file from an astropy.table.Table object. 

We've just recently added the 'align' kwarg for the pprint() function, and have also added the ability to align columns in a table via 'format', too (see #3037 and #3644 ). As an example, I could align the following table using one of two methods:

Firstly, I could adjust an individual column's alignment by doing:

```
>>> from astropy.table import Table
>>> t = Table()
>>> t['col1'] = [1,2,3,4,5]
>>> t['col2'] = [1,2,3,4,5]
>>> t['col3'] = [1,2,3,4,5]
>>> t.pprint()
col1 col2 col3
---- ---- ---- 
   1    1    1
   2    2    2
   3    3    3
   4    4    4
   5    5    5
>>> t['col3'].format = '<'
>>> t.pprint()
col1 col2 col3
---- ---- ----
   1    1 1   
   2    2 2   
   3    3 3   
   4    4 4   
   5    5 5   
```

Secondly, I could pass in a kwarg, 'align', into pprint():

```
>>> t.pprint(align=['<','^','0='])
col1 col2 col3
---- ---- ----
1     1   0001
2     2   0002
3     3   0003
4     4   0004
5     5   0005
```

What I would like to see, is a latex table which I have the option of passing in alignment arguments. And to be consistent with the above example, it could look something like this:

```
>>> t.write('/Users/uname/Desktop/test.tex',format='latex', align=['<','^','>'])

\begin{table}
\begin{tabular}{lcr}
col1 & col2 & col3 \\
1 & 1 & 1 \\
2 & 2 & 2 \\
3 & 3 & 3 \\
4 & 4 & 4 \\
5 & 5 & 5 \\
\end{tabular}
\end{table}
```

One could even imagine the ability to add vertical lines in between the l/r/c specifiers.

**Comment by mhvk** [comment]
@agroener - related to this would be to make the latex table writer recognize the `<`, `^`, `>` signs in column formats. Then, just like for `pprint`, one can have the `align` keyword override defaults taken from the column format string.

**Comment by agroener** [comment]
@mhvk Absolutely - what you propose is exactly what I had in mind. It would allow more latex table customizability when writing them out to file.

**Comment by hamogu** [comment]
LaTeX tables had the ability to define the column alignment long before pprint could do that. In that sense it's a little unfortunate that pprint introduced a new notation for that, it would have been easier if pprint could understand the same l c r that latex uses.
The option is called col_align and can be specified either in the latexdict together with other LaTeX options or as a separate keyword.
See http://docs.astropy.org/en/stable/api/astropy.io.ascii.Latex.html#astropy.io.ascii.Latex

**Comment by hamogu** [comment]
The command would be
```
t.write('/Users/uname/Desktop/test.tex',format='latex', col_align=['lcr'])
```

**Comment by agroener** [comment]
Ah okay. Yea, had I known this was a feature of latex tables I could have considered unifying the syntax.

By the way, are there any examples in the docs exhibiting this kind of alignment for latex tables? I must have missed it if it does exist.

**Comment by agroener** [comment]
Didn't follow the link. Never mind the last comment :)

**Comment by hamogu** [comment]
@agroener : I see three main differences to the `pprint` interface. 

- `lrc` vs `<^>`. I don't know why `<^>` was chosen for `pprint`, but LaTeX itself uses `lcr`, which is why we chose this for the LaTeX writer. If this cannot be unified any longer (*) it should be easy to accept both notations in both places.
- in the LaTeX writer you pass a string (`lllrccc`) not a list of characters (`['<','<','^','^','^']`. You might argue that a list of strings is has a better correspondance to the list of columns that make up a table, but the thought behind taking a single string is exactly what @agroener mentions above: This way you can write `|c|c|lr`. Again, we could easily do `col_align = ''.join(col_align)` which would accept both forms.
- The keyword argument is called `col_align` for the LaTeX writer and `align` for `pprint`. The reasoning for LaTeX is this: `align` does not say if this aligns columns or the caption or the table as a whole (all of which can be specified separately in LaTeX, although the astropy writer currently only supports `col_align` through a keyword [there are other ways to put a \begin{center} \ end{center} round your data using the `latex_dict`]).

Unfortunately, I missed the PR where this was implemented for `pprint` or I would have commented there. Was this very recent? In other words, could we still change the `pprint` to use the LaTeX writer conventions without breaking backwards compatibility?

**Comment by agroener** [comment]
@hamogu I understand that there are differences - but this actually might not be a bad thing. We originally chose the strings <,^,>, and 0= because python string objects have a method called 'justify' (https://docs.python.org/2/library/string.html), which deals with formatting of strings in that way. 

If we were to switch the left, right, and center strings in the align property of pprint, it would cause a bit of confusion in my opinion. Especially since I am not aware of a latex format for zfill. Additionally, astropy column objects now have an intrinsic property which includes the alignment in the way we have already implemented. What this means is that you can change the alignment of a single column with:

    >>> t['col1'].format = '<'

and it is a persistent change to the alignment of this column. The other way is temporary (and is the kwarg align in pprint). 

Actually, I would advocate for separate but consistent syntax for both pprint and latex tables, and do not think changing alignment in pprint adds any real value.

**Comment by hamogu** [comment]
@agroener : Maybe keep this issue open, though. The point @mhvk raised is still valid: The LaTeX writer could check if any of the table column has an alignment set and then translate that to `lcr` for writing. I'm happy to implement that (but not in the next few days).

**Comment by taldcroft** [comment]
@hamogu @agroener 

Since this is just affects dev there are no restrictions on API changes at this point.  We can still change our mind!  For instance changing from `align` to `col_align` for the `pprint` kwarg seems like it would be a fine thing.

In the original PR I was advocating allowing a single-string format, and I still think that would be a good idea.  Unification with the latex syntax is an additional driver.  One way to do this is to accept having a few ways of doing the same thing.  I originally argued against this, but maybe it's OK in the interest of making this all easy and natural for different users.  Some people might be use to Python format syntax, others used to latex.  E.g. have `r`, `>`, and `right` all be synonyms.  We could have `z`, `=0`, and `zero_fill` as well.

`col_align` could accept a string, list or dict.  This certainly is swinging completely to the side of making this a bit more complicated to document and code, but might be more general and cover more use cases.  We could actually have a common utility which parses the `col_align` arg into a base representation and then use that in both `pprint` and the `Latex` writer(s).

**Comment by taldcroft** [comment]
:+1: to allowing the Latex reader to use existing column `format` values to define alignment if `col_align` is not explicitly specified.  Likewise setting the `format` using the latex alignment value when reading a table would be cool if this is a reasonably well-contained problem.

**Comment by taldcroft** [comment]
So for example, values of `col_align` could be:
```
'rrccl'
['r', 'r', 'right', '=0', 'zero_fill']
{'col1': 'right', 'col2': 'left'}
'<<=0>>'
'right left zero_fill > < r c ^'
```
This would require a mini-parser, but it would be pretty easy to write.

**Comment by hamogu** [comment]
@taldcroft In principle you are right of course, in practice we can probably achieve 90% of what you are suggesting with 10% of the effort and my feeling is that that would be totally sufficient. There should be a mechanism (in fact there already are two) to set the column alignment but it's not core functionality of astropy - we are not a typesetting library. 
I advocate for a medium solution with an easy implementation.

**Comment by agroener** [comment]
@taldcroft I like your statement about the Latex reader trying to be smart about alignment if <code>col_align</code> is not already defined.
@hamogu I also agree with you - we can unify things, but only if it is clean and simple. I think devoting a huge amount of time to something like this is probably unnecessary, since both work well enough as standalone features.

So, it looks like we would be looking at (unless any of these things are already being done):
1) Writing some code such that when reading latex tables from file, the <code>format</code> attribute of each column is updated according to the latex table metadata (e.g. - <code>|c|c|lr</code>). This probably wouldn't be too hard to do, though it would take some thinking about what one should do with the vertical dividers.
2) Making sure that when writing latex tables out to file, if no <code>col_align</code> is specified, perhaps it should use the intrinsic alignment of columns (if they exist).
3) Writing a small parser which unifies the latex syntax with the string justify characters pprint and format are using. This would allow users to supply latex syntax <code>llrrc</code>, characters like <code>['<','<','>','>','^']</code> (or even <code>'<<>>^'</code>), actual human readable input like <code>['left','left','right','right','center'] (or its equivalent 'left left right right center')</code>, or I suppose even a dictionary.

**Comment by pllim** [comment]
I have a related question. I see that the `pprint()` method has an `align` keyword that supposedly accept "left", "right", etc. But it is not doing anything for me. All columns are right-justified no matter what I do.

**Comment by agroener** [comment]
Not sure if I'm looking at the latest documentation (https://astropy.readthedocs.org/en/v0.3/api/astropy.table.table.Table.html#astropy.table.table.Table.pprint), but it doesn't appear that it has been pushed up yet. Where are you seeing this?

**Comment by taldcroft** [comment]
You need to look in latest:

https://astropy.readthedocs.org/en/latest/api/astropy.table.Table.html#astropy.table.Table.pprint

**Comment by taldcroft** [comment]
@pllim - yes the `pprint()` docstring is misleading.  See:

https://astropy.readthedocs.org/en/latest/table/access_table.html#column-alignment

**Comment by taldcroft** [comment]
@agroener - there seems to be some leftovers in the docstrings, which refer to defaults of `right` that don't seem to apply in the code anywhere.

**Comment by pllim** [comment]
@taldcroft , thank you for the clarification, `tab.pprint(align=['<', ...])` works for me in the dev version!

**Comment by taldcroft** [comment]
@pllim - with #4214 you will be able to do `tab.pprint(align='<')`.  #4214 does some cleanup of the original alignment PR.

**Comment by taldcroft** [comment]
Seems like this has been sufficiently addressed.
