### ISSUE TITLE
Fix ColDefs.add_col/del_col

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3647]
Over in #3283 I basically fixed the `ColDefs.change_attrib` interface for changing FITS column attributes.  I also fixed things so that the somewhat more obvious interface of just updating the attributes on `Column` objects, such as setting `Column.name`, work as expected.

I had previously said I would never bother to fix this because I never liked the interface anyways, and would rather focus on implementing a new Table interface.  But after giving it a second thought, fixing the existing interface would actually help with implementing the new interface.  And it would just be nice to have fixed so I don't have to keep handling the FAQ of why this wasn't working as advertised.

There are two other interfaces that never quite worked as advertised, and those are `ColDefs.add_col`, and `ColDefs.del_col`, which give the impression that they can be used to add/remove columns from a table.  Again, I was previously never going to bother fixing these.  But I think with the work in #3283, it will be much easier to do so now, and I already started on this.  I just wanted to break it off into a separate PR.  Again, if it's not too hard then it's worth having fixed until a new Table interface is in place.  It will also help with backward compatibility.

**Comment by saimn** [comment]
From the discussion triggered by #6649, the most obvious solution would be to prevent `add_col` and `del_col` to modify in-place the `ColDefs` object. For instance `add_col` can be used like this
```
fits.BinTableHDU.from_columns(f[1].columns.add_col(column)) [1]
```
or directly with an addition.
```
fits.BinTableHDU.from_columns(f[1].columns + column) [2]
```

The other (better in theory) option would be to update the `TableHDU` when its columns are modified. I tried quickly to do this in `_update_column_added` and `_update_column_added` but it doesn't work. It's tricky because of the way the ColDefs object and data are linked.

So, not sure about the best option:
- prevent in-place modification of the ColDefs object, but this breaks direct use of ColDefs, and forces uses of [1,2].
- issue a warning from a Table HDU when its coldefs is modified. But this would also affect [1,2]
- just remove `add_col` and `del_col` ...

**Comment by hamogu** [comment]
I just run into this problem, thinking that `add_col` would allow me to add a column. It took me some experimenting to convince myself that the problem was not with my code, but with `add_col` not actually being able to add a columns. I want to suggest a forth option: Modify the docstring to explain what's discussed here and add an example along the lines of [2] to the narrative documentation. That does not fix the code itself, but it's also certain to not break backwards compatibility. The fact that this issue has been open for so long indicates that it's not a terribly common case, but when you run into it it might take a long time to understand what's going on, so we should do something about it.
