### ISSUE TITLE
add bayesian blocks to stats

### ISSUE THREAD

**Issue by astronomeralex** [astropy/astropy#3706]
add bayesian blocks to astropy.stats beyond and in addition to those in astroML

from unconference at pyastro15 on astropy.stats

**Comment by eteq** [comment]
In principal this is straightforward, but it does require a little bit of thinking, because we don't want to duplicate the same functionality that's in astroML.

In that direction, @jakevdp, how do you feel about the idea of moving this into astropy.stats (and having astroML use that in a future release?)

**Comment by jakevdp** [comment]
In general I'm all for moving useful tools upstream, and astropy is already a dependency of astroML (though astroML certainly needs to be updated to remove some duplicative code!)

For the Bayesian blocks code, here's some code cleanup & streamlining that would be good to do in the process – I've learned a lot in the ~2 years since I wrote that. I'd be happy to work on this in a couple weeks if it's something that the community would like in astropy.

**Comment by astronomeralex** [comment]
@jakevdp -- thanks for being will to work on this. we had an unconference session at python in astronomy on astropy.stats and many folks there were interested in having bayesian blocks in astropy.

**Comment by jakevdp** [comment]
Great. Sorry I missed that conference! I was planning to go up until February, but couldn't make it for family reasons.

I'll try to put together a Bayesian Blocks contribution some time in early May.

**Comment by embray** [comment]
Could somebody who knows something about this include some links/information about what this actually means and what it would involve?

**Comment by jakevdp** [comment]
I started a PR at https://github.com/astropy/astropy/pull/3756

**Comment by crawfordsm** [comment]
closed by #3756
