### ISSUE TITLE
Performance when grouping/matching large tables

### ISSUE THREAD

**Issue by joezuntz** [astropy/astropy#3721]
I'm opening this following some discussion at Astronomy In Python 2015.
I have a particular use case where performance has been quite poor.

I have two tables, one called "A" with ~ 10 million rows and another, "B", with ~ 40 million.  The are related by a single "ID" column.  The IDs are unique in A but not in B, and both tables are sorted. Each has dozens of columns.

I want to, for each ID in A, find all the rows in B with the same ID, and run some very simple function (e.g. np.mean) on them, and add this into a new column in A.  I couldn't find a solution to this within astropy that was fast and not extremely low level and fiddly.

**Comment by taldcroft** [comment]
@joezuntz 

I've put together an IPython notebook that should roughly represent your use case.  The only real difference using just 11 columns in each table.  With "dozens" of columns in each table my mac started running out of physical memory so this messed up the timings.  In all the process took about 2 minutes on my machine.  Is that similar to what you've seen which would count as quite poor performance?

http://nbviewer.ipython.org/gist/taldcroft/72ed9dda91222bc07e04

I did a comparison with pandas.  In this case the merge (join) time is comparable to astropy, while the pandas group_by is much faster because it is working on an already-indexed column.  If I give a column that is not indexed this it is slower.  The final aggregate operation is noticeably faster in astropy Table.

The end-to-end time for astropy Table is within a factor of 2 of pandas, and I am not aware of any other Python implementations of database-type operations that are faster.

The hope is that at the end of this summer astropy Table will support column indexing.

**Comment by embray** [comment]
So it sounds like lack of indexing is the major contributing factor here? That would make sense.

I do wonder why the Astropy aggregate is so much faster than the Pandas version--I wonder what additional overhead it has, and it makes me wonder if there's something that can be improved on their end.

**Comment by taldcroft** [comment]
@embray - maybe a bit of a cheat there since we special case some funcs to use `np.reduceat`:

https://github.com/astropy/astropy/blob/stable/astropy/table/groups.py#L228

**Comment by joezuntz** [comment]
Just getting back to this - sorry for the super long delay.  The main issues I saw earlier seem to have been caused by a combination of using an older astropy version and sub-optimal coding on my part.  

There's only one remaining issue with speed that regularly hits me:  the ```repr``` function on large tables seems very slow given that it only displays a few rows at the start and end of the table.

**Comment by taldcroft** [comment]
> There's only one remaining issue with speed that regularly hits me: the repr function on large tables seems very slow given that it only displays a few rows at the start and end of the table.

Upgrade to 1.0.3 and you should be happier.  #3796 fixed this.

**Comment by joezuntz** [comment]
Cool, then that's great I'm happy to close this.
