### ISSUE TITLE
Include diagram of forks/clone/etc for pull requests

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3732]
@mwcraig - we should include a diagram similar to what you drew in the GitHub tutorial at pyastro15 in the development docs - what do you think?

**Comment by mwcraig** [comment]
Sounds good, feel free to assign it to me if you want.

**Comment by astrofrog** [comment]
Done - thanks!

**Comment by mwcraig** [comment]
@astrofrog -- any quick reactions to this before I look at embedding in the docs?

![foo](https://cloud.githubusercontent.com/assets/1147167/9103214/25996214-3bc1-11e5-8917-825a6a90f658.png)

**Comment by taldcroft** [comment]
I have sketched that same diagram many times, so definite :+1:to include.

**Comment by mdboom** [comment]
:+1: from me also.

**Comment by embray** [comment]
:+1: 

Next need to add an extended version of this diagram that includes adding other people's forks as remotes and making pull requests to their pull requests :)

**Comment by astrofrog** [comment]
@mwcraig - I've sometimes found it easier to present it with the GitHub box *above* the Your computer box (I somehow visualize the internet 'above' my computer, but maybe that's just me :wink:)

**Comment by taldcroft** [comment]
Each of us on this discussion should try to show this picture to a colleague you know who is at the novice-ish level with git/github and see if it makes sense.

**Comment by mwcraig** [comment]
Thanks for the feedback! 

@taldcroft -- good idea! I can try it out on one early next week.

@astrofrog -- yeah, I agree, but put it together in graphviz, and laying it out vertical looked awful. Could redo it in something else if necessary... Feedback from novices would be helpful here.

**Comment by taldcroft** [comment]
Here is feedback I got from a colleague who has been walked through the github process once or twice but not really gotten to the level where he could drive himself.  So this is a good view of how the diagram looks to a novice:

"That’s somewhat helpful; in particular the notion of creating a copy of the project on github (I gather that’s a ‘fork’) is not something I noticed in what I’ve done. Calling this copy “origin” seems counterintuitive to me. The “pull” and “push” metaphors still make no sense to me, but that’s probably just me. And of course I worry about the dotted “pull updates” arrow across the bottom, because there’s no general solution (that I’m aware of) to the problem of merging several different people’s updates to the same code base. And the checking it all in at the end thing is unclear in this diagram, possibly because it’s been simplified away. I shouldn’t be able to modify the official repo."

**Comment by taldcroft** [comment]
I forgot to add that his comment about not realizing he's made a fork before is because in our case he was making branches directly in `upstream`, so indeed he did not fork the repo.  This highlights the fact that there are common variations in github workflow, including a small team collaboration where everyone has commit rights.

**Comment by bsipocz** [comment]
I remember being a novice when I had the problem that my local clone didn't update  to the remote astropy/master (it said "Already up-to-date." even when I know it isn't). Apparently I didn't say ``git fetch --all". 
However I'm not sure how to visualize it. Maybe write "fetch and then pull updates" on the arrow?, I'm not sure.

**Comment by mhvk** [comment]
Agreed this is good to have. I'd use a solid line for "pull updates" since it is something one has to do regularly and may call the line "update by fetching and rebasing".  ... ... At least, that is how I keep up to date, but reading `git pull --help`, I see this is the same as `git pull --rebase upstream` -- learn something new every day...  So maybe "pull to keep up to date" with below it "(regularly)".

**Comment by astrofrog** [comment]
Side note regarding diagrams - I liked this one from GitHub:

![diagram](https://cloud.githubusercontent.com/assets/1319791/8943755/5dcdcae4-354a-11e5-9f82-915914fad4f7.png)

from [this](https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows) page. Of course, it's not enough, but liked the vertical layout.

**Comment by mwcraig** [comment]
Ooh, that is nice!

**Comment by mwcraig** [comment]
Will cycle back around to this later this week, incidentally....

**Comment by bsipocz** [comment]
Do we still plan to do this, or rather close as "won't fix"? There are zillion github tutorials out there, so while rolling our own diagram would be nice, it's not really necessary.

**Comment by mwcraig** [comment]
Closing...most of those zillion tutorials have better graphic designers anyway.

**Comment by mhvk** [comment]
Can we refer to one of those tutorials in our documentation?

**Comment by bsipocz** [comment]
Both http://try.github.io/ and https://git-scm.com/book/en/v1/Getting-Started-Git-Basics is linked here: http://docs.astropy.org/en/stable/development/workflow/development_workflow.html#new-to-git, and there are tons of links from those pages, too.

**Comment by mhvk** [comment]
OK, thanks, I should have looked what we have...
