### ISSUE TITLE
Error with get_pkg_data_filename in clean Python 2.7 environment

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3754]
I created a clean conda environment with Python 2.7 and Astropy 1.0.2 and the following code:

``` python
from astropy.utils.data import get_pkg_data_filename    
get_pkg_data_filename('galactic_center/gc_bolocam_gps.fits')
```

gives the following error:

```
  File "test.py", line 2, in <module>
    get_pkg_data_filename('galactic_center/gc_bolocam_gps.fits')
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/site-packages/astropy/utils/data.py", line 548, in get_pkg_data_filename
    timeout=remote_timeout)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/site-packages/astropy/utils/data.py", line 948, in download_file
    with _open_shelve(urlmapfn, True) as url2hash:
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/site-packages/astropy/utils/data.py", line 1214, in _open_shelve
    shelf = shelve.open(shelffn, protocol=2)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/shelve.py", line 223, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/Users/tom/miniconda3/envs/test-data/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
```

@eteq @embray @mdboom - any ideas?

**Comment by mdboom** [comment]
Miniconda doesn't include the `bsdbm` stdlib module by default (but it's just a `conda install bsdbm` away).  

In this case, I would guess that you previously imported astropy in a Python *with* `bsddb` installed, and it left its cache in `bsddb` format on your filesystem in `~/.astropy/cache`.  When it tries to load it again in a Python interpreter without that module it fails in this way.  Had you just started with the clean miniconda environment, you wouldn't have triggered this because it would have fallen back to another database backend (at worst `dumbdbm` in pure Python) and used that.

There are a couple of ways to resolve this:

- When loading the cache file fails, just throw it out and start over: it's only a cache after all
- Consider making `bsddb` a hard requirement (it is a stdlib module after all).  While perhaps more annoying for users, it has the advantage that we don't silently fall back to a slow implementation and run into a potential performance problem (only matters when the cache gets large, though, I suspect).

**Comment by astrofrog** [comment]
@mdboom - ah yes, I think that's what happened. We could ask the conda folk to include ``bsddb`` as a dependency in the Anaconda package?

**Comment by mdboom** [comment]
Yes -- we could ask for that change in Anaconda, but if we do, I think we should accompany it with a change that errors or warns if it's not available.

**Comment by embray** [comment]
I'm gonna take this off the v1.0.4 milestone for now--#3755 has a partial workaround for the immediate symptom (the cache is unloadable and you get an unhandled exception).  I'd like to keep this issue open beyond #3755 since I think it's worth exploring other options for what to do with this (including maybe making the db library a hard requirement, or something else...)

**Comment by adrn** [comment]
Since we now only support Python 3, can we close this?
@astrofrog

**Comment by pllim** [comment]
Yes, `bsddb` does not exist in Python 3.
