### ISSUE TITLE
modeling different shape when calling or evaluating

### ISSUE THREAD

**Issue by wkerzendorf** [astropy/astropy#3776]
@embray This is strange behaviour (the two different sets of brackets in the second array):

```python
spec_grid.evaluate(5780, 4.4, 0.0)
Out[2]: 
(array([ 2000.05000063,  2000.1000025 ,  2000.15000563, ...,  8999.52844134,
         8999.75343236,  8999.97842901]),
 array([  5.75495471e+12,   5.61469203e+12,   5.45274546e+12, ...,
          4.06387211e+14,   4.05685295e+14,   4.05407972e+14]))

In [3]: spec_grid()
Out[3]: 
(array([ 2000.05000063,  2000.1000025 ,  2000.15000563, ...,  8999.52844134,
         8999.75343236,  8999.97842901]),
 array([[  8.02623633e+12,   7.90324501e+12,   7.75040884e+12, ...,
           5.08103597e+14,   5.06904470e+14,   5.06432697e+14]]))
```

**Comment by embray** [comment]
I agree, it looks a bit strange that the second output is getting a seemingly unnecessary dimension added to it.  I wonder if this is related to #3772.  That said, could you provide a little more context?  It *is* expected that what is returned by a model's `evaluate` method is not necessarily the same as what's returned by calling an instance of the model.  Remember, `Model.evaluate()` is in general *not* intended for direct use, and it is expected that `Model.__call__` will have different behavior.  The main difference being that `Model.evaluate()` performs a simple calculation, while `__call__` conditions all inputs through the `prepare_inputs` and `prepare_outputs` methods.

Another fact (although poorly documented) is that for internal use, anyways, it is assumed that all arguments passed to `evaluate()` will be arrays (even 1x1 arrays in the case of otherwise "scalar" inputs).

**Comment by wkerzendorf** [comment]
I see, yes I think that was one of the problems that arguments are becoming 1x1 arrays. But for now that explains the behaviour. Feel free to close this issue.

**Comment by embray** [comment]
So are you agreeing there's no issue?
