### ISSUE TITLE
Adding properties to Parameters

### ISSUE THREAD

**Issue by wkerzendorf** [astropy/astropy#3784]
@embray well as discussed I wanted to extend the Parameter class to have additional properties.  
Simply subclassing it doesn't easily work - as it's a descriptor (I tried). 

Any suggestion how to do that?

**Comment by pllim** [comment]
I didn't follow the original discussion, so this might have already come up, but in case it has not -- Is it possible for a simpler approach to add these properties into the `metadata` attribute in the `Model`?

**Comment by embray** [comment]
Details?  There's nothing about being a descriptor per se that prevents subclassing.

**Comment by wkerzendorf** [comment]
Sorry

```python
class StarKitParameter(Parameter):

    @property
    def prior(self):
        return getattr(self, '_prior', None)

    @prior.setter
    def prior(self, value):
        self._prior = value

    def __init__(self, *args, **kwargs):
        prior = kwargs.pop('prior', None)
        self.prior = prior
        super(StarKitParameter, self).__init__(*args, **kwargs)

``` 
that does not work - as I can't access the prior after creation. Does that make sense?

**Comment by wkerzendorf** [comment]
when I attach this Parameter to a model the prior is always `None`: https://github.com/wkerzendorf/starkit/blob/master/starkit/gridkit/base.py#L95

**Comment by pllim** [comment]
I see that you imported `StarKitParameter` as `Parameter`. Maybe that causes namespace confusion. Because this works for me:
```
>>> s = StarKitParameter(prior=1)
>>> s.prior
1
```

**Comment by embray** [comment]
See https://github.com/astropy/astropy/blob/master/astropy/modeling/parameters.py#L177

Also something perhaps surprising about how `Parameter` works is that there's little to no actual information stored in the Parameter instances.  All the parameter info is stored in the Model objects themselves.  Parameter is just a user front-end to that information.  I would suggest storing this "prior" attribute in the `model._param_metrics` dict.

**Comment by embray** [comment]
Sorry, I should clarify that a bit more.  It's fine that there's a `._prior` attribute in the `Parameter` instance--this is where the unbound parameter could store a default value for `.prior`.  However, that only applies to the `Parameter` that's attached to the class itself.  *Instances* of the model will have to store values for that attribute elsewhere.  This goes back to my point about the difference between "unbound" and "bound" parameters.  "Unbound" parameters are class attributes that declare some properties about a parameter.  "Bound" parameters are the `Parameter` objects returned when accessing a parameter attribute on a model instance.  It has to reflect information *specific* to that model instance, and not just to the class as a whole.

(One thing you'll notice also is that every time a parameter is accessed on a model instance, a new `Parameter` objects is created.  There's no real reason for that I can think of; we could just as easily create the bound parameter once and cache it on the model.  Doing it this way just avoids a reference cycle, and hasn't proven to be a serious performance issue (since again, its only purpose is as a user front-end).

**Comment by embray** [comment]
By the way, you'll notice in the link in my last comment that the `__get__` definition is a bit tedious, since all the properties that were used to define the unbound Parameter need to still be passed to the `__init__`.  I would definitely consider a patch to list all properties of a `Parameter` class so that all the relevant properties can be listed in one place, so that less work needs to be done to add a new property.

**Comment by wkerzendorf** [comment]
@pllim This works for you until the Parameter is attached to a class. Once you attach it to a class. things will break. 

@embray yes, I saw that at the moment you do not call `return Parameter(**kwargs)` that would be much appreciated.

**Comment by wkerzendorf** [comment]
@embray so for now, I'll just overwrite `__get__`?

**Comment by embray** [comment]
For now you could probably just extend it like:

```python
def __get__(self, obj, objtype=None):
    parameter = super(StarKitParameter, self).__get__(obj, objtype)
    if parameter is not self:
        parameter._priors = self._priors

    return parameter
```

or something to that effect.  That assumes that nothing in the class's `__init__` depends on a prior being passed in.  Otherwise you would have to completely override `__get__`, at least for now.
Just remember that you'll still have to store values of `.prior` on the model instance, for bound parameters.  Otherwise any value you set on the `.prior` property will be lost.  The thing to do is here is check if `self._model is not None` in `prior.setter`.  See for example the `fixed` property: https://github.com/astropy/astropy/blob/master/astropy/modeling/parameters.py#L323

**Comment by wkerzendorf** [comment]
I might just chuck it in `_constraints` for now. Let me know if any of this is useful for astropy. I can make a PR.

**Comment by embray** [comment]
That seems like an okay place to put it for now.

**Comment by wkerzendorf** [comment]
@embray well - this works ... but, I'll loose my priors as soon as I concatenated and make compound models - the priors disappear. https://github.com/wkerzendorf/starkit/blob/master/starkit/base/parameter.py

**Comment by embray** [comment]
Yes, we'll need to figure out a way to propagate those.  You might be able to make something work if you added "priors" to the list of parameter_constraints.

**Comment by wkerzendorf** [comment]
@embray that makes it appear in the parameter representation, but it does not propagate them.

**Comment by nden** [comment]
With the rework of `Parameter` and `CompoundModel` in v 4.0 this is now possible.
