### ISSUE TITLE
Unicode column types not intuitive in table repr output?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3806]
For string columns in tables, the datatype shown in the repr or repr_html output is a bit strange:

![screen shot 2015-05-31 at 6 29 53 pm](https://cloud.githubusercontent.com/assets/314716/7902730/1ae08b0e-07c3-11e5-9f91-de3e63d307aa.png)

This is because these are unicode columns (in Python 3). The 'real' dtype is:

```
dtype([('name', '<U4'), ('obs_date', '<U10'), ('mag_b', '<f8'), ('mag_v', '<f8')])
```

Can we show U4 or unicode4 or something similar instead?

**Comment by taldcroft** [comment]
That's always bothered me as well, but I kinda thought that having a mix of long-form types and short-form types would just as bad.  I don't like having all short-form because for the less common types it isn't obvious what they are.  Anyway, I was basically always on the fence about using `S` and `U` for string types, so if there is consensus to change it then that's fine.

If we're changing the repr then while we're at it I would like to take out the `masked=False` for unmasked tables.  It's just noise.

**Comment by embray** [comment]
I'm :+1: for 'unicode<len>'

**Comment by taldcroft** [comment]
@embray - would you prefer that `<len>` be in bits, following the convention for numbers, or for string-like types should len be the number of characters?

**Comment by embray** [comment]
I meant the number of characters.

**Comment by taldcroft** [comment]
The question is whether to unify the Py 2 / 3 behavior or not.  Here are the dtype.name values:
```
        S3        U3
Py2   string24  unicode96
Py3   bytes24   str96
```
It's a pain writing tests and docs that are Py2 / 3 compatible with this difference, so I would propose that we unify the the dtype names in astropy (in info and repr type methods).

So first of all I think we need a function somewhere in utils to take a `dtype` and return the type "name" that we think is most useful / pleasing (for all of astropy, since I'm already running into this in multiple places).  In some sense `S3` and `U3` are good since they are already unified and actually work as inputs to `dtype`.  They are not exactly human friendly, but maybe the different form from types like `int8` will serve as a reminder that the number is a character length not a bit length.

The other obvious unified possibility is always using `string<N>` for `S` and `unicode<N>` for `U`.  That might be confusing though since for Py3 it is somewhat backwards from `dtype.name`.

**Comment by embray** [comment]
Ah, I didn't realize these names came straight from Numpy.  Maybe that's not always the "friendliest" name to use for a high-level UI element.  So I'm in favor of unifying it so that it's the same on Python 2 and 3.

**Comment by mdboom** [comment]
I feel like the least ambiguous naming would be "bytes" and "unicode".  "string" may lead to confusion because it's defined differently on Py2 vs. Py3.

**Comment by taldcroft** [comment]
While technically correct, for the (still) majority of users on Py2 it seems like `bytes` is slightly opaque.  I think some newbies would not immediately connect something called `bytes` to a string.  But if they have ever seen a numpy dtype printed out they are likely to recognize something like `S5`.

**Comment by taldcroft** [comment]
But note that I'm not really adamant on any of the choices...

**Comment by astrofrog** [comment]
I'd be in favor of using string for bytes in 2 and unicode in 3, and bytes for bytes in 3. Python 3 users might not even know that str = unicode.

**Comment by taldcroft** [comment]
@astrofrog - I see the logic but it's a major pain for docstring testing.  We're running docstring tests in Py3 now on travis right?  Having this 2 / 3 difference means every time you print a table in a docstring example you either skip the test or don't include string columns.

**Comment by astrofrog** [comment]
In principle, I think that users should never really encounter bytes when doing simple things. For example if you make a column with strings like this:

```
t['a'] = ['a','b','c']
```

it should be a bytes column in Python 2 and a unicode one in Python 3. So then in both cases the header would say 'string'.

**Comment by taldcroft** [comment]
I was going to say that this happens commonly when reading a FITS file since I thought you would get a `bytes` column.  Alas I was surprised:
```
In [31]: hdus = fits.open('astropy/io/fits/tests/data/table.fits')

In [32]: hdus[1].data.dtype
Out[32]: dtype([('target', 'S20'), ('V_mag', '>f4')])

In [33]: hdus[1].data['target']  # this is what Table uses when passed hdus[1].data
Out[33]: 
chararray(['NGC1001', 'NGC1002', 'NGC1003'], 
      dtype='<U20')
```
So when converted to Table the FITS bytestring column is unicode.  I guess this is done to prevent the endless breakage otherwise, at the expense of memory.  However, this is not the case when reading an HDF5 file, as bytes remains bytes there in Py3.

**Comment by astrofrog** [comment]
@taldcroft - the HDF5 behavior could be treated as a bug in principle (I didn't consciously make that decision when writing the reader/writer). If FITS does the conversion, then HDF5 probably should to. Basically, users should never really see bytes unless they ask for them IMHO.

**Comment by taldcroft** [comment]
The problem with HDF5 is that you are more likely to encounter a huge column that would blow up to huge * 4 and cause problems.

**Comment by taldcroft** [comment]
Thinking about this more in Python 3 if you have a bytes type then it's probably useful to the user to see that as `bytes` because it will be unusual and likely won't work with their code as expected.  So I'm on board with the suggestion from @astrofrog.

**Comment by embray** [comment]
@taldcroft The column size blowup is a problem for FITS too--I've had people come to me with like 1 GB string columns in a FITS table :/  I might go ahead and see if my encoded_text_array type could be useful there too.

**Comment by mhvk** [comment]
I'm not very keen on introducing new names for numpy dtype. I might actually go the other route and use short forms everywhere -- as a fortran user I find `f4` and `f8` quite understandable -- i.e., just put `col.dtype.str` in the header instead of `col.dtype.name` (which is what I think is there now, correct?). 

As yet another alternative, one could use `str(dtype)`, which gives the same as the present for float/int, but `<U1`, etc., for string/unicode.

I'd think that ideally it should be such that `col.dtype == <whatever>` evaluates to True. Some checks:
```
np.dtype('i1') == 'i1'
# True
np.dtype('i1') == 'int8'
# True
np.dtype('U1') == 'U1'
# True
np.dtype('U1') == 'str32'
# TypeError: data type "str32" not understood
```

**Comment by embray** [comment]
I have the extreme opposite view on this.  I don't think there's anything inherently preferable about using the string names of Numpy dtypes in any form.  In many cases they're fine ('int32', etc.) but why should anything be otherwise Numpy-specific?

If you wanted to see the Numpy dtype `col.dtype` is already accessible.  But from a high-level user experience / UI standpoint it doesn't add anything.  To many users Numpy is an implementation detail.

**Comment by taldcroft** [comment]
One of the points that sold me (eventually) was that for the string-like types the astropy table info long form should match the Python type that would work for comparison.  This is mostly relevant for Python 3 of course since for Py2 most things just work.  So the string types would be:
```
Numpy          S<N>      U<N>
Python 2    string<N>  unicode<N>
Python 3    bytes<N>   string<N>
```
The logic is to make it obvious to users what kind of Python types can be used to compare or set values in a numpy array of the given type.

I can see the points of "well at the end you just need to know numpy dtypes to do astronomy with Python" and "don't invent another standard".  But at the same time I would rather see informative long-form types than having to know:
'b'	boolean
'i'	(signed) integer
'u'	unsigned integer
'f'	floating-point
'c'	complex-floating point
'O'	(Python) objects
'S', 'a'	(byte-)string
'U'	Unicode
'V'	raw data (void)

**Comment by mhvk** [comment]
Hmm, I see the arguments against obscure numpy letters. Python names has a certain appeal, but if we go for that it is less obvious why float and int would need the number of bits -- that's not accessible in python anyway. More useful would be a possible shape of the array (for each element) Note that if we'd go with python names, it would have to be `str`, not `string`.
Another question would be, I guess, whether we need it at all? Looking at the example from @astrofrog, it may be good to know that `obs_date` is a string, not a `Time` instance, but to paraphrase @embray, the type is only a `type(t['col'])` away...

**Comment by taldcroft** [comment]
I'd be OK with `str<N>`.

Looking at a table repr I find it very useful to know the types, so I definitely want to keep that as part of the standard output.  As a practical matter it does tend to be important to know if a numpy array type is 32-bit or 64-bit, or unsigned, etc.

**Comment by taldcroft** [comment]
We *could* always make the type names schema be a configuration option, so the Martens of the world could choose `col.dtype.str`, but the default would be `col.dtype.name` except for the string types.  This may be overkill, but it wouldn't be that hard since I plan to make a centralized function to return the astropy type name for a given dtype.

As a start, does anybody have objections to using `obj.dtype.name` except:
```
Numpy          S<N>      U<N>
Python 2    str<N>     unicode<N>
Python 3    bytes<N>   str<N>
```

**Comment by mhvk** [comment]
No need for too much configuration on my behalf... What you suggest is definitely an improvement over what we have!

**Comment by embray** [comment]
Well, if there's a per-column method for formatting its type string, even if that's an internal method right now it could always be exposed later in a way that it can be overridden.  I think that's not a bad idea.
