### ISSUE TITLE
Undesired result when multiplying mixed quantities

### ISSUE THREAD

**Issue by fred3m** [astropy/astropy#3819]
When adding quantities we get

    a = 2*u.arcsec
    b = 2000*u.mas
    a+b

which returns

    <Quantity 4.0 arcsec>

If we reverse the order

    b+a

we get

    <Quantity 4000.0 mas>

But if instead we multiply them

    a*b

we get a mixed quantity

    <Quantity 4000.0 arcsec mas>

It would be nice to not have to use

    (a*b).to('arcsec2')

to get

    <Quantity 4.0 arcsec2>

as we won't always know that we have mixed quantities and the current behavior seems inconsistent with the addition/subtraction behavior.

**Comment by mhvk** [comment]
@fred3m - the difference between addition and multiplication is that for addition we *have to* convert the unit because otherwise we cannot do the addition, while for multiplication we do not *have to*. Since a scale-change can be quite costly if the arrays are big, by default we only do it if we have to. 

I should add that after using quantities for a long time, I have stopped worrying about the exact unit that they currently are in; the beauty is that it does not matter whether it is arcsec2 or mas2, when you need it in some unit, you can convert at that time.

Does this answer your concern?  If so, just close this.

**Comment by fred3m** [comment]
That makes sense, thanks for the response.

**Comment by embray** [comment]
To add, in the past there's been some discussion whether or not to make compound units when multiplying (or dividing) units of the same physical type.  Or for that matter returning a dimensionless quantity when dividing.  It was decided that since there are some cases where it *is* desirable to have quantities in mixed units of the same physical type (e.g. pc/km) it was decided best to leave it mixed until the user specifies otherwise.
