### ISSUE TITLE
Upload astropy wheel to PyPI

### ISSUE THREAD

**Issue by sYnfo** [astropy/astropy#3902]
Installing a package as big as astropy using wheel is a much more pleasant experience, is there any particular issue that would prevent it from being available in such fashion?

See [0] for more information on wheels.

[0] http://pythonwheels.com/

**Comment by embray** [comment]
I'm gonna go ahead and close this as a duplicate of #802 and #2628.  I think there are already a couple people working on infrastructure to build wheels for Astropy, but when it comes to PyPI uploads it's a question of what platforms they'll be uploaded for, etc.  I think it hasn't been a high priority since more users are using Anaconda.

I definitely want to get wheel builds going for Windows releases sooner rather than later though (I haven't even made binary Windows releases for the last few releases, and haven't heard any outcry about that, but having wheels would definitely be good).

**Comment by sYnfo** [comment]
Fair enough, thank you! :)

**Comment by embray** [comment]
It's worth adding--the current version of pip now, by default I believe, makes a wheel out of any package it installs and stores that in a cache for future installs.  This is nice if you're making lots of virtualenvs for example.

**Comment by Cadair** [comment]
@embray oh that is awesome!!
