### ISSUE TITLE
Make default astropy.table notebook repr jsview? (or just prettier?)

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#3937]
This is inspired by a talk at scipy 2015 about the Beaker notebook project.  They have some sort of magic that makes Pandas DataFrames look pretty _and_ have tricks like being able to sort in the browser:
http://sharing.beakernotebook.com/gist/anonymous/ee2a39c529e07ae3c2ca

It occurs to me that this is very similar to the existing `Table.show_in_browser(jsviewer=True)` functionality.  Perhaps we should consider trying to make the notebook repr use the jsviewer mode? 

Or alternatively, perhaps we should just inject some CSS to make the notebook-generated tables look a bit prettier?

cc @taldcroft

**Comment by embray** [comment]
Let's not assign milestones unless there's something more concrete...

**Comment by embray** [comment]
That looks nice though--there's been a lot of progress, it seems, on being able to use interactive widgets to repr objects in the notebook, and something like this should be doable.

**Comment by taldcroft** [comment]
@embray - that's sounds intriguing.  A slider that scrolled through the table could be good.  Do you know of any specific projects or code that we might peek at to get a running start?

**Comment by eteq** [comment]
:+1: to the idea of something widgety as a way to make this even nicer.

For a project that has some pretty in-depth widgets you might want to check out https://github.com/mwcraig/reducer (possibly watch his [talk at scipy](https://www.youtube.com/watch?v=hyxCDdBH1Mg&list=PLYx7XA2nY5Gcpabmu61kKcToLz0FapmHu&index=99) to see examples of the widgets in action).

**Comment by embray** [comment]
Now that I look, in the original work on the jsviewer @keflavich did [try to make it work in IPython Notebook](https://github.com/astropy/astropy/commit/5ba32761ebf1367ff9a34b59b1e0ae25229ecbbd#diff-f0015555c1a6a31c82fa4ab42c66d2ff).  However, in 934f8303d2719b2a8de60cbeaafdaa0d7441ec64 the ability to actually invoke the IPyNB support through the `Table.show_in_browser` API was quietly revoked.  I don't know if this was intentional on @keflavich's part, or just because it never quite worked or what.  So the existing code is essentially dead code.  Furthermore, it predates even IPython 2.0 and the widget interface.  So we should get IPython/Jupyter support going again, but in the form of a widget.

**Comment by keflavich** [comment]
@embray I can't say why I removed the `if ipynb` part of this... I think it might have just gotten lost in a refactor, and I don't really use notebooks much so I never noticed.  I think using more modern ipython tricks is a good idea.

**Comment by pllim** [comment]
Given https://github.com/astropy/astropy/pull/15905 , this is no longer relevant.
