### ISSUE TITLE
Question: concatenating FITS files in a memmap

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#3989]
I have a series of large files that I need to concatenate into one larger file.  They are 20 subsets of a large (45 GB) cube that I want to all be in the same cube.  I can do this by creating a `numpy.memmap` and writing each entry into that file, but I'd then have to read the memmap array in and write it back out as a FITS file.  Is there a way to create a new FITS memmap of the appropriate size so that I can write to it?  I can hack together the necessary commands from the `_File` class in `astropy.io.file`, I think, but it would involve using a lot of private methods.

cc @embray

**Comment by embray** [comment]
http://docs.astropy.org/en/stable/io/fits/appendix/faq.html#how-can-i-create-a-very-large-fits-file-from-scratch  is a good starting point.  You would figure out how large the final image would be first, and create an empty file for it, then just open the empty image in update mode and fill in the slices one at a time.

(P.S. I'm closing this since the issue tracker is not the place for questions like this, though feel free to reopen if you have any ideas for adding a way to do this through the API--I think there should be a way but I haven't thought very hard about it).
