### ISSUE TITLE
Deprecated examples in coordinate documentation

### ISSUE THREAD

**Issue by JaiPEG** [astropy/astropy#4024]
As docs/coordinates/index.rst mentions, "the recommended way to use coordinate functionality is via the `~astropy.coordinates.SkyCoord` class, instead of classes like `~astropy.coordinates.ICRS` classes (now called "frame classes")."

However, many of the other files in the docs/coordinates/ directory continue to use these deprecated frame classes. A few simple adjustments should do the trick.

**Comment by astrofrog** [comment]
Note that the frame classes are not deprecated - just not the easiest way to use coordinates. However, they can be faster, so we should still mention them in the docs.

**Comment by JaiPEG** [comment]
Oh. I was under the impression that they should never be used in v0.4 and up because index.rst says, "This compatibility feature will issue a deprecation warning, and will be removed in the next major version".

Maybe the speed increase could be mentioned for those who still want to use the frame classes or are using a pre-v0.4 version of astropy.

**Comment by eteq** [comment]
@JaiPEG - ah, I think you're thinking of usage like this:
```
>>> coordinate = ICRS(123.4, 56.7, unit=('deg', 'deg'))
WARNING: AstropyDeprecationWarning: Initializing frame classes like "ICRS" using string or other non-Quantity arguments is deprecated, and will be removed in the next version of Astropy.  Instead, you probably want to use the SkyCoord class with the "frame=icrs" keyword, or if you really want to use the low-level frame classes, create it with an Angle or Quantity. [astropy.coordinates.baseframe]
```
the idea is that you post v0.4 you shouldn't use the non-quantity objects (strings, or numbers with ``unit`` keywords) to create frame objects, but rather you should use quantities with frame objects or `SkyCoord` with the ``unit`` keyword.  That is, frame objects are to be thought of as "low-level" without smart parsing capabilities, while `SkyCoord` is much more flexible in what it accepts.

Does that make sense?  Looking at it now, you're definitely right that the docs aren't too clear about this.  Are you willing to try to issue a PR to clarify this, @JaiPEG? (My experience is that new contributors are the best people to write docs, because those of us who are core devs tend to be overly terse because we already understand whatever we're documenting...)

**Comment by JaiPEG** [comment]
Thank you; that's crystal clear. I've also done some poking around the baseframe.py file to get the details more internalized. So if I understand it correctly, frame classes can still be used, are still used, they aren't however as flexible as the SkyCoord class with regard to parsing, and they only accept arguments that are instances of either units.Quantity or BaseReprestation?

Although, I'm still a little confused about what happens when this is written:
`>>> coordinate = ICRS(123.4, 56.7, unit=('deg', 'deg'))`

Index.rst says that in v0.4, it will return a SkyCoord object but one that "behaves more like the pre-v0.4 `~astropy.coordinates.ICRS`". So is it specifically the initalization of ICRS with non-quanitity arguments that is deprecated, or is it this quasi-compatible SkyCoord/ICRS object that is deprecated?

I can try to issue a PR once I figure out all these little details.

**Comment by adrn** [comment]
@JaiPEG Could you reference me to the confusing text in the coordinates documentation, or close this issue if you think it has been updated? Thanks!

**Comment by JaiPEG** [comment]
@adrn Yes, it looks the warning of backwards compatibility for pre-v0.4 frame classes has been removed in the current documentation of astropy. Thanks for the heads up! I'll close this issue now.
