### ISSUE TITLE
coordinates submodule disappeared

### ISSUE THREAD

**Issue by tbhkuiper** [astropy/astropy#4029]
I was trying to find a way to convert a cycle to a string hh:mm:ss.ss this way:
c = astropy.coordinates.Longitude(0.5,unit='cycle')
Finding that c.hms gave me a tuple instead of a string I tried to obtain the sexagesimal components and did
```
In [44]: c.hour
*** Error in `/usr/bin/python': free(): invalid pointer: 0x00007f2eeee0ae40 ***
Aborted
```
After that when I restarted ipython:
```
In [6]: astropy.
astropy.Conf              astropy.cython_version    astropy.logging
astropy.UNICODE_OUTPUT    astropy.extern            astropy.online_docs_root
astropy.absolute_import   astropy.find_api_page     astropy.test
astropy.conf              astropy.log               astropy.utils
astropy.config            astropy.logger            astropy.version
```
coordinates is gone.

**Comment by tbhkuiper** [comment]
So disregard that.  It has something to do with namespaces that I don't understand.  This works:
```
In [1]: import astropy
In [2]: from astropy.coordinates import Longitude
In [3]: c = Longitude(0.5,unit='cycle')
```
This does not, although it did before,
```
In [1]: import astropy
In [2]: c = astropy.coordinates.Longitude(0.5,unit='cycle')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-cbc3c3255c03> in <module>()
----> 1 c = astropy.coordinates.Longitude(0.5,unit='cycle')

AttributeError: 'module' object has no attribute 'coordinates'
```

**Comment by embray** [comment]
The fact that you're getting a double-free coming from your Python executable is highly suspect.  What OS are you on, and what Python version?  This sounds more like a problem with your Python installation than anything.

**Comment by embray** [comment]
>  It has something to do with namespaces that I don't understand.

Oh, that I can explain though.  When you import a *package* in Python (like "astropy") which has submodules/subpackages like "astropy.coordinates", the subpackages are not all automatically available in the namespace of "astropy".  This is because Python only discovers subpackages as you import them.

It's possible that the top-level package "astropy" can automatically import subpackages into its namespace, but large packages like Astropy don't do this deliberately--it would make start-up time too slow, and load possibly large packages into memory when they aren't explicitly needed.  You have to type `import astropy.coordinates` or, sometimes more simply `from astropy.coordinates import <specific objects you need>`.

**Comment by tbhkuiper** [comment]
On 08/03/2015 08:02 AM, Erik Bray wrote:
> It's possible that the top-level package "astropy" can automatically 
> import subpackages into its namespace, but large packages like Astropy 
> don't do this deliberately--it would make start-up time too slow, and 
> load possibly large packages into memory when they aren't explicitly 
> needed. You have to type |import astropy.coordinates| or, sometimes 
> more simply |from astropy.coordinates import <specific objects you need>|.
Thanks, Erik.  That explains why it sometimes works and sometimes 
doesn't.  It's good to be aware of.

Best regards,

Tom

**Comment by embray** [comment]
There's been renewed talk in the Python dev mailing lists in the last year on lazy-loading of modules, so that it will be easier to find all the submodules in a namespace without actually fully importing them.
This would definitely be very nice to have and would resolve this problem properly, but it turns out to be pretty tricky to get just right due to subtleties of the Python import system.
