### ISSUE TITLE
astropy.time.Time does not support missing values

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#4032]
Should `astropy.time.Time` accept `np.nan` as input? After discussion, @eteq suggested I ping @taldcroft to find out. 

For example, let's say I have three derived Julian dates, and one turns out to be nonsense. Should the `Time` constructor fail every time with `ValueError: Input values did not match the format class jd`?

**Comment by eteq** [comment]
To add a bit more on this: One "solution" is to use masked arrays:
```python
>>> np.ma.masked_where([False,True,False], [1,2,3])
masked_array(data = [1 -- 3],
             mask = [False  True False],
       fill_value = 999999)
>>> mjds=np.ma.masked_where([False,True,False], [1,2,3])
>>> t=Time(mjds,format='mjd')
>>> t
<Time object: scale='utc' format='mjd' value=[1.0 -- 3.0]>
>>> t.jd
masked_array(data = [2400001.5 -- 2400003.5],
             mask = [False  True False],
       fill_value = 1e+20)
```
But that has the problem that if I want to use the same idiom for something that might be a *scalar* `Time`, it doesn't work - `Time` raises a `ValueError` if I try to give it `np.ma.masked`.

So is there a specific reason why `NaN` is disallowed?  Or is it an oversight?

@mhvk might have opinions here too

**Comment by mdboom** [comment]
A side note: if we *do* decide to support NaNs, we'll need to make sure that ERFA can handle them.  (I can't find anything explicitly said about them, which probably means ERFA has undefined behavior with NaNs and we'll need to adapt our wrappers to skip over them.)

**Comment by taldcroft** [comment]
The short answer about why there is no support for missing data is that we (or at least I) didn't think about it.

I think that both approaches (masked arrays or NaN) will require some finesse to get to the point of being fully or even mostly functional.  Masked array has the advantage of supporting strings and providing a clear signal on object creation that masking is needed.

**Comment by taldcroft** [comment]
Thinking about integration with Tables, using masked arrays might work out better.

**Comment by mhvk** [comment]
I think in principle it should not be too hard to use `MaskedArray` instead of regular array for `jd1` and `jd2`. I think there may indeed be a problem, though, with `erfa` throwing its own warnings/exceptions, and removing masks for many operations. It may become a rather large overhead. In that respect, supporting `nan` may be nicer, though as @mdboom noted, it would also require updating the erfa glue.

However, for the use case in astroplanners, would it be possible to use empty `Time` instances for sources that do not rise/set/transit at all?

**Comment by taldcroft** [comment]
If using `nan`, what would be done in the case of asking for any string output?  We can invent our own "missing" token and use that.  Likewise `datetime` would probably be `None`.  I guess a harder case is any output that is a pure integer.  Pandas handles this by using arrays of Python objects or representing integers with float as needed.

**Comment by eteq** [comment]
@mhvk - can you clarify a bit more what you mean by "empty `Time` instances"? That sounds like exactly what we need to keep moving forward now, to perhaps later be replaced by a more consistent solution like what's being used here.

**Comment by eteq** [comment]
Also,  I just did a quick experiment of something like:
```
t = Time.now()
t.format = 'jd'
t._time.jd1 = t._time.jd2 = np.array(nan)
t.mjd (and tai/tcb/etc)
```
and most things quite happily passed `nan` around just like you'd expect, suggesting maybe there's no need to fiddle with the ERFA wrappers.  They gave errors like "dubious year", but that's reasonable enough... The one failure is `ut1`, which complains about being out-of-range for IERS, but that could be straightforwardly adjusted to be ignored when it's caused by a `nan`, right?

**Comment by taldcroft** [comment]
> They gave errors like "dubious year", but that's reasonable enough...

Reasonable enough if you are just tinkering or want an answer now for a specific case, but not reasonable for production-hard code that could be used in a telescope control system.  E.g. in your example if you convert to `iso` then it gives a valid (though odd) value without any indication that it started from a missing value.  So I'd be hesitant to actually advertise support for missing values (by NaN or masks) until it is somewhat feature-complete.

**Comment by eteq** [comment]
@taldcroft - yeah, fair enough.  Maybe the thing to do for now (i.e. v1.1 of astropy) is to allow it as an input via Time(float('nan')) or similar, but with a clear note in the docs that it's an experimental feature?

**Comment by taldcroft** [comment]
@eteq - what about allowing NaN in the input to `Time` or `TimeDelta`, but issuing a warning "Your input values contain NaN and astropy.time is not well tested for this case, so use at your own risk.  Some features, like conversion to string formats, are known to give spurious results.  Not recommended for production code."

**Comment by eteq** [comment]
:+1: @taldcroft - and then hopefully we can get some people trying it to uncover the broken cases (and hopefully fix them?)

**Comment by taldcroft** [comment]
@eteq - yes, we can probably get patches to make things work in a limited way using sentinel values to indicate a missing value.

But I think that any *clean* solution is going to need to use masks.  Basically ERFA is going to be unhappy with NaN in the JD values and issue warnings which are spurious.  So we have to strip out or overwrite the NaN's prior to calling any ERFA routine and then re-insert afterward.  That can be done since we have control of the wrapper generator, but one needs some memory of where the NaNs are, i.e a `mask`.

Once we're starting to carry around a mask, then it's a quick hop to saying let's just use masked arrays.  Then you get full support for any time format, including `datetime` which crashes completely for NaN input right now.  

Part of this plan would be that each time format would have a predefined `missing_value` that gets used to generate the `jd1` and `jd2` values for masked elements.  This missing value would be contrived to not break anything, and most likely would be something like 2000-01-01T00:00:00 in whatever format.  The point is to permanently stub in reasonable values so that ERFA never complains, but from the user perspective they are always hidden behind the mask.

What would be really sweet is to have a `mask` property on the `Time` object that is read/write and hooks in to the underlying `jd1` and `jd2` masks.  Then with any luck a `Time` mixin column could participate in operations that require a functioning `mask`, i.e. database table operations like `join`.

**Comment by mhvk** [comment]
@eteq - belatedly:
```
In [1]: from astropy.time import Time

In [2]: Time([], format='jd')
Out[2]: <Time object: scale='utc' format='jd' value=[]>
```
but it doesn't work for string-based formats like `iso` (which arguably is a bug...)

**Comment by eteq** [comment]
@mhvk - Ah, gotcha.  @bmorris3 figured that's what you meant, but critically for our application, that also has ``time.isscalar == False``.  What we need is a `time` that's NaN/masked/whatever, but also has ``time.isscalar == True``.

**Comment by eteq** [comment]
@taldcroft - yeah, that plan works fine too, I think (although maybe @bmorris3 has some thoughts here?)  One possible caveat is that it needs to also work for scalar `Time`s, as I just mentioned above.  But the `mask` property could be a boolean in that case.  And I guess it'd possible to use scalar masked arrays as the internal representation.

**Comment by bmorris3** [comment]
I'm opposed to making the scalar time value `False` (see above by @eteq), because I find the `Time` constructor returning a boolean to be counter-intuitive, but that's still better than returning a length-1 masked array instead of a scalar (@taldcroft).

**Comment by mhvk** [comment]
If `Time.isscalar or Time.size == 0` (latter is empty) would work, why not just `Time.size <= 1`? Or do you really care about `Time` instances that are not scalars but have `size=1`?

**Comment by bmorris3** [comment]
@mhvk Maybe it would make more sense if I described our application and how we'd like to use it (and if it's not useful, ignore the following). We're calculating rise/set times for lists of targets. Since some targets never rise/set, we'd like the `astropy.time.Time` output to have the same length as the target list, and have a placeholder value for the rise/set time of targets that don't rise/set, like `nan` for example. We'd like to have consistent behavior for the single circumpolar target case where the output is expected to be a scalar `Time` object but the value is `nan` or similar.

**Comment by embray** [comment]
Perhaps this is a stupid idea, but maybe `Time(np.nan)` could return a special `NotATime` subclass of `Time` (arrays would work the same way they do currently, but accessing a single value that has `nan` would return a `NotATime`)

**Comment by taldcroft** [comment]
I still lean toward using masked array underneath as providing an overall solution that is more consistent.  Note that right now a "scalar" Time is stored under the hood as a scalar array, not a true scalar.  There is a close analog in masked arrays:
```
In [21]: a = np.ma.array(1, mask=True)
In [22]: a.mask
Out[22]: array(True, dtype=bool)

In [23]: a[()]
Out[23]: masked

In [24]: t = Time.now()

In [25]: t._time.jd1
Out[25]: array(2457252.5)
```
The thing I don't understand about the `np.nan` solution is what you get for `t.iso` or `t.datetime`, particularly for the array situation.  Even if `np.ma` has its warts, it does handle most of what we need.  And by gosh, from numpy-discussion: "masked array and recarray fixups for astropy" is currently the number 2 goal for numpy 1.11!

I would say we should make having `Time` support masking via masked arrays be a goal for astropy 1.2 (unless @mhvk goes on a rampage in the next week).  I expect to be busy with GSoC etc in the next couple weeks before the 1.1 freeze.

**Comment by eteq** [comment]
Seeing as how we're past feature freeze and the aforementioned rampage has not materialized, I tagged this for 1.2

**Comment by taldcroft** [comment]
Summary:

- Implementation will be via masked tables, NaN is rejected.
- Medium priority (esp. for support of Table high level operations, masking is useful)

**Comment by bsipocz** [comment]
Just another :+1: for this.

My use case is to deal with a super messy light curve format. (``hjd`` is stored as seconds in an ``ImageHDU`` containing loads of NaNs, too).

```
>>> from astropy.time import Time, TimeDelta
>>> import astropy.units as u
>>> import numpy as np
>>> 
>>> basetime = Time('2004-01-01T00:00:00')
>>> td = np.arange(1.0,16).reshape((3, 5))
>>> td[1, 1] = np.nan
>>> tdu = td * u.s
>>> 
>>> basetime + tdu
Traceback (most recent call last):
  File "/sw/lib/python3.5/site-packages/astropy/time/core.py", line 1314, in __add__
    other = TimeDelta(other)
  File "/sw/lib/python3.5/site-packages/astropy/time/core.py", line 1484, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/sw/lib/python3.5/site-packages/astropy/time/core.py", line 262, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/sw/lib/python3.5/site-packages/astropy/time/core.py", line 306, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class jd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/lib/python3.5/site-packages/astropy/time/core.py", line 1316, in __add__
    raise OperandTypeError(self, other, '+')
astropy.time.core.OperandTypeError: Unsupported operand type(s) for +: 'Time' and 'Quantity'
```

I've though of using this as a workaround, but its masked value handling is utterly wrong, and also doesn't work for array of non second values (however both can be easily dealt with).

```
>>> tdm = np.ma.array(td, mask=~np.isfinite(td))
>>> 
>>> tdm_td = TimeDelta(tdm, format='sec')
/sw/lib/python3.5/site-packages/numpy/ma/core.py:809: RuntimeWarning: invalid value encountered in greater_equal
  return umath.absolute(a) * self.tolerance >= umath.absolute(b)
>>> (basetime + tdm_td).mjd
WARNING: ErfaWarning: ERFA function "taiutc" yielded 1 of "dubious year (Note 4)" [astropy._erfa.core]
array([[   53005.00001157,    53005.00002315,    53005.00003472,
           53005.0000463 ,    53005.00005787],
       [   53005.00006944,  2506010.99958333,    53005.00009259,
           53005.00010417,    53005.00011574],
       [   53005.00012731,    53005.00013889,    53005.00015046,
           53005.00016204,    53005.00017361]])
```

My question is whether you think the original version will ever work out of the box? Also I wonder whether there is a better workaround.

**Comment by taldcroft** [comment]
@bsipocz - this looks like a good candidate for an astropy feature request on the new page recently mentioned on astropy-dev.  Could you make an entry?  (It doesn't have to be very long and can mostly just reference this issue.)

I think your final question is whether having NaN's in your input to Time will be supported.  One problem is that it is hard to know all/any problems that will come up without diving into a trial implementation.  I don't even know if ERFA/SOFA is considered "nan-safe" in the sense that it is guaranteed to produce reasonable and predictable results with NaN inputs.  But as mentioned previously in the bigger scheme of supporting all available formats and for consistency with Table columns, I would advocate using masks instead of NaN.

**Comment by bsipocz** [comment]
@taldcroft - I've though of adding this to there, but all the rest were more big-picture-like new features :)

**Comment by taldcroft** [comment]
@bsipocz - this won't be a trivial thing to implement so it's useful to see how much interest there is.

**Comment by bsipocz** [comment]
I think #6028 has addressed this, and indeed my example above now returns a masked array rather than nonsensical value (but I still get the warning from erfa). 

@eteq @bmorris3 - Please open a follow-up issue if any of your use cases are still not working.
