### ISSUE TITLE
vstack and/or add_rows() for Columns

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4047]
I would like to `vstack` two `Column` objects. Alternatively either an `append()` or an `add_rows()` method would work as well. Neither of these exists as far as I see. 
Is there a way to go around this? Currently `_get_list_of_tables()` makes sure that only `Table` and `Row` objects are allowed for any of the operation functions.

I have a slight deja vu that I needed this feature in the past, but cannot find out whether I had a good workaround, or any issue opened about it.

**Comment by embray** [comment]
I think most of these would work if you wrap them as single-column Tables.  Though I suppose `astropy.table.vstack` could be modified to work on Columns as well?  Note this can also be done with `Column.copy` as I'll demonstrate below.

This raises one issue though--we treat Columns as 1-D arrays.  For example:
```python
>>> c = Column([1, 2, 3])
>>> c.shape
(3,)
```
If you use `np.vstack` it's *not* (despite our mental picture) the same as stacking one column on top of another to extend a column:
```python
>>> np.vstack((c, c))
array([[1, 2, 3],
       [1, 2, 3]])
```
This is confusing--maybe by default we should always append an extra dimension to `Column` arrays so that they can be reasoned about more like vertical columns:
```python
>>> cc = c.reshape((3, 1))
>>> cc
<Column name='c' dtype='int64' shape=(1,) length=3>
1
2
3
```
This is mostly the same as the original column `c` except for the `shape=(1,)`.  I'm arguing that maybe this should be the default, and that `Column` arrays should always get an axis appended to make it a vertical column (and the `shape=(1,)` would be ignored in this case).

Now we get the more "natural" behavior:
```python
>>> np.vstack((cc, cc))
array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])
```
Or even 
```python
>>> c.copy(data=np.vstack((cc, cc)))
<Column name='c' dtype='int64' shape=(1,) length=6>
1
2
3
1
2
3
```
Currently the above example will work to do what you want to do if you use `np.hstack` instead of `np.vstack`:
```python
>>> c.copy(data=np.hstack((c, c)))
<Column name='c' dtype='int64' length=6>
1
2
3
1
2
3
```
But I for one find that utterly confusing.

**Comment by taldcroft** [comment]
I could see putting a little shim within `table.vstack` to allow for a list of all `Column` objects, wrapping them up as `Table`, then unwrapping at the end.  Conceptually it makes sense to me.

**Comment by taldcroft** [comment]
@embray - about making `Column` have a 2-d shape like `(N, 1)` by default, I think that would break a whole lot of stuff.  In your example doing `cc[1]` would yield an `array([2])` instead of a `np.int64(2)`.

The whole thing where columns *should* be vertical but aren't is always confusing, but the same is true of numpy structured arrays, recarray, pandas, etc.  You just have to do that little mental flip and use `hstack`.

So the question is: is it just adding to the confusion if we allow column inputs to `table.hstack` and `table.vstack` and have those do the *right* thing (which happens to be opposite to `np.[hv]stack`)?  I would say no, that allowing column inputs to our stack functions would be a good thing.

**Comment by embray** [comment]
Well, in that case you don't need to convert columns to tables and back--`table.vstack((col, col))` can just be shorthand for `col.copy(data=np.hstack((col, col)))`.

**Comment by taldcroft** [comment]
But then you lose metadata merging (in the more usual case of `table.vstack([col1, col2])`).

**Comment by taldcroft** [comment]
The change to support this should be pretty simple and (mostly) contained here:
https://github.com/astropy/astropy/blob/198343ba2f65b2ee59e6db0589110a065dff776d/astropy/table/operations.py#L104

I am thinking this routine can be generalized a bit to just make sure everything that gets passed in which isn't a `Table` can be used to initialize a table, either directly (e.g. `Table(row)` => row-like or table-like) or enclosed in a list (e.g. `Table([col])` => column-like).  Then you just need to keep track of whether *every* element in the input list was column-like, and set (and return) an `all_column_like` variable.  If `all_column_like == True` then at the end of stacking return `out_table.columns[0]` instead of `out_table`. 

By doing this then the `hstack` and `vstack` functions become much less type-specific and you could do stuff like:
```
table.hstack([[1,2,3], Column([3,4,5]), Table(...)])
```
There is still the mental flip that `[1,2,3]` is a *vertical column*.

**Comment by bsipocz** [comment]
@embray, @taldcroft  - Thanks for the ideas.
I thought of @embray's the first option, to convert them to a singe column Table. However it would be quite ugly, to juggle so many single column Tables, vstacking them, and then join/hstack for the sake of generating the one big one I'm after.

Thanks for the ``np.hstack`` trick though, I'm quite happy with that solution even if it's confusing (tried ``np.vstack``, didn't work, thus abandoned that path). I don't need any metadata here, so this would make the trick in this specific case.

**Comment by mhvk** [comment]
I think you're looking for `np.concatenate`, which by default joins along `axis=0`, which would always be the column length. It also doesn't propagate information, though. Still, if we go for a new method, I'd pick `concatenate` as being the most obvious.

Generally, note that `hstack` and `vstack` work just like for `ndarray`, since `Column` is an `ndarray` subclass. In numpy 1.10, because of mental confusion similar to here, a much nicer, more general `np.stack` version will be introduced, where you just give the new axis along which you want to stack.

**Comment by SaOgaz** [comment]
I've run into a similar need for this but I would really like to keep the meta data.  It's really awkward and annoying for me to package everything up into tables first, I've got 4 separate columns going that I have to add to one at a time, so I can't put them all into a final table until the very end.

**Comment by SaOgaz** [comment]
I should add that the "insert" method on the `Column` object almost works, but I need to insert at the very end of the first column, and there doesn't seem to be a way to do that?

**Comment by mhvk** [comment]
@taldcroft - see comments from @SaOgaz above about insertion, etc.

**Comment by bsipocz** [comment]
I'm happy to see that this feature is useful to others, too.
I'm fairly certain that vstacking `Column`s now work (as of #7674 got merged yesterday), but I completely forgot about this issue. Could you @SaOgaz try it again with the latest master?
