### ISSUE TITLE
Timezone convenience method for astropy.time.Time

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#4119]
Right now, if you want to get a localized datetime from an astropy time, you have to type a long string of calls to `pytz` like this: 
```python
>>> import pytz
>>> from astropy.time import Time
>>> t = Time.now()
>>> pytz.utc.localize(t.datetime).astimezone(pytz.timezone('US/Hawaii'))
datetime.datetime(2015, 9, 2, 9, 15, 26, 284400, tzinfo=<DstTzInfo 'US/Hawaii' HST-1 day, 14:00:00 STD>)
```
(localize the naive datetime as a UTC time, convert to another timezone with `pytz`). I’ve been thinking about how to make timezone manipulations more convenient in [astroplan](https://github.com/astropy/astroplan) and it seemed like this would be a convenient way to solve the problem also for other users outside of astroplan. 

Are there good reasons not to make a method on `astropy.time.Time` objects called `astimezone` that does what that last line does – accepting one argument that goes into the `datetime.astimezone` method and returning the result? For example, the above code would become: 

```python
>>> t = Time.now()
>>> timezone = pytz.timezone("US/hawaii")
>>> t.astimezone(timezone)
```

I tried to implement this, but the mysterious workings of `TimeFormat` prevented me. If this isn't a dumb idea, I'd love some advice on how to implement it. 

cc @taldcroft @mhvk

**Comment by taldcroft** [comment]
I could see having something like this, though the method name `astimezone` seems wrong to me since it is returning a `datetime` not a time zone.  Maybe `t.as_datetime(timezone=None)`, where you can enter a time zone in any convenient way (string, pytz object etc) and it gives you back a localized `datetime.datetime` object.  

This is explicitly not a `TimeFormat` because our `Time` object doesn't have a concept of time zone.  Instead it is just a regular object method, so implementation should be relatively straightforward.  You do need to consider that a `Time` object can be an array of arbitrary dimensions and obviously `datetime.datetime` doesn't handle that.  The existing `datetime` TimeFormat should provide guidance since it does the right thing (returns numpy array of datetime objects).

**Comment by mhvk** [comment]
Agreed with @taldcroft's approach (though I would call it `to_datetime`, in analogy with `to_string` that we use in quite a few other instances).

I do worry a bit about it being a relatively half-baked solution. One could also think of having a `to_value` method, which by default is equal to `time.value`, but allows one to pass on a desired format, as well as possible arguments:
```
    def to_value(self, format=None, *args, **kwargs):
        if format is None:
            out = self._time.to_value(*args, **kwargs)
        else:
            out = getattr(self, format)._time.to_value(*args, **kwargs)
        return self._shaped_like_input(out)

    value = property(get_value)
```
Then, the `TimeDatetime` (and all the other time formats) also would need to have a `to_value` method, which takes a timezone as an argument. 

Overall, though, in all of these approaches I don't quite like that the timezone is not kept in the `Time` instance. A more complete one might entail storing the timezone, e.g., in the location (but, like for `sidereal_time`, we could still give the option of explicitly passing on the timezone).

**Comment by taldcroft** [comment]
It seems to me that a time zone only makes sense for the `utc` scale, so I'm not sure it should be a generic `Time` attribute.  From that perspective `to_value()` would only do something different and meaningful if the scale is `utc`.  (What would it mean to apply a time zone to a `tcb` scale time?)

**Comment by mhvk** [comment]
`*args, **kwargs` could differ depending on scale. But yes, overall, it may be more logical to think of all those timezones as alternatives to utc.

In some sense, this discussion is why I'm a bit uncomfortable moving ahead. I feel it would be good to think through how best to deal with timezones; in principle, they can be given/represented in `iso/isot` as well.  But maybe the analogy of sidereal time can help: that is connected to `UT1` via a dotted line on purpose, in that it is some kind of `UT1` but needs extra information. Similarly, local times could be connected to `UTC` via a dotted line (maybe with arrows both ways), i.e., via a somewhat unusual extra routine.

**Comment by eteq** [comment]
@mhvk - I'm a bit confused by your last comment here: `sidereal_time` actually returns an `Longitude`, so it's explicitly *not* an alternate scale.

My sense of why the approach @bmorris3 is suggesting is better is based mostly on that analogy: in my head, `Time` is a thing that does *not* require any information beyond what scale/format you're in, in contrast to all the stuff in coordinates, which often require additional information (the frame attributes).  So am I understanding right that you're suggesting to break with this and allow formats that require further information (In this case that's "the time zone it's representing")?

In the end, regardless of exactly how it's implemented, I'm strongly in favor of something that's very easy-to-use like what @bmorris3 says here.  E.g. ``timeobj.some_thing(timezone)`` should give me a datetime with a timezone.  Anything more complex ends up very awkward (we've learned this by trying to do it in `astroplan`).

**Comment by mhvk** [comment]
@eteq - I guess I'm simply a bit ambivalent, in that I feel either `Time` doesn't support timezones, in which case I prefer it had nothing to do with it altogether, or it does, but then it should work not just for `datetime` but also for `iso` and `isot`.  My mention of `sidereal_time` is simply because that has somewhat similar problems (indeed, you may remember you argued quite strongly it didn't belong in `Time`).

**Comment by mhvk** [comment]
Anyway, more concretely: currently, `TimeDatetime` does support timezones in `datetime` on input, so it does seem reasonable to support it on output as well, and it seems to make most sense to do this via the `TimeDatetime` format class. Currently, the way to communicate with any time format is via `.value`, which is why I suggested above to create a `to_value` method. (Like @taldcroft, since a timezone only makes sense for `UTC`, I think it is a bit odd for `Time` to have a top-level method that is specifically aimed at providing timezone support.)

Note that the above is independent of whether `Time` stores the timezone itself. Though in principle, one could store any timezone in input datetime's in the `TimeDatetime` instance itself, just `TimeFITS` stores some information on the fits scale (which, however, gets lost in format changes). Indeed, if we had a general `to_value` method, it could be used by `TimeFITS` to pass on time-scale information that is supported by the fits standard, but not by `Time`, so there may be a bit more value in this generalization.

**Comment by eteq** [comment]
@mhvk - in the past I would have agreed that `Time` shouldn't be concerned with timezones. In fact, I said as much to some users who were asking about time zone support. But then we tried actually using local times in `astroplan`, and found that it was awkward because expressions as complex as ``pytz.utc.localize(t.datetime).astimezone(pytz.timezone('US/Hawaii'))`` are necessary basically any time you want to get local times.  So I am now more sympathetic to the users' complaints that they either find it difficult or can't figure out how to get local times from `Time` objects.  As you noted @mhvk,  *input* is much easier - it just works.  So from purely a user-level perspective, it's awkward that output is so much harder.

With that in mind, from a user-facing perspective I prefer something like ``as_timezone`` (or maybe something completely different like ``localize``?) because that's what people are going to look if they ask the question of "how do I get this in a particular time zone?".  ``to_datetime`` (which I think is what your ``to_value`` suggestion would actually look like to a user, right?) is slightly worse because if a user says "how do I get this in my timezone?" they may not be thinking "it needs to be in a python `datetime` to do that".

Whether or not `to_value` is useful in other context I have no idea, though - I trust in @mhvk and @taldcroft's experience to judge that best.

**Comment by taldcroft** [comment]
Somehow the `to_value(format=..)` doesn't feel natural.  It also doesn't allow easy discovery of what arguments are allowed for what formats.  This is the battle we have been fighting with the unified I/O interface.

What we're skirting around is that some formats need or want to have optional arguments when creating the representation of the time object.  This is a limitation imposed by the original API choice, but we could get around this by allowing for an (optional) `to_value(self, ...)` method in every `TimeFormat` class and then routing `time_obj.to_<format>(...)` to that method.

So this is probably pretty similar to what @mhvk is saying, but with a different API.  Maybe with the right metaclass magic we can make `to_datetime` and `to_fits` be proper methods that get put onto the `Time` class during the `TimeFormat` registration process.  This would enable both tab-discovery and proper online API docs.

**Comment by eteq** [comment]
(oops, my last comment collided with @taldcroft's I think... although they're fairly orthogonal I guess?)

**Comment by taldcroft** [comment]
@eteq - I am hoping my suggestion would be a solution that will satisfy both you and @mhvk (and me).

About `to_datetime` not being entirely obvious, I agree but think we could address that with documentation.  Imagine a full section called `Dealing with time zone`.  Then hopefully googling `astropy time zone` would get you right there.

**Comment by taldcroft** [comment]
One reason to keep the word `timezone` out of the `Time` API is that it could give the false impression that `Time` really handles time zones internally.  Instead we are saying "we have time zone support only at the interface (input and output) via Python's datetime.datetime object".

**Comment by bmorris3** [comment]
That's the idea behind what I was trying to propose, @taldcroft, though my sketch code didn't make that clear. The timezone handling can all be punted to pytz. Maybe something like `time.as_datetime_via_pytz` would get that point across.

**Comment by eteq** [comment]
I see your points here, @taldcroft - a section in the docs that clearly says "how to deal with time zones" that demonstrates this would probably do the trick.  I have a bit of a twinge because that then is expecting users to read the documentation, which is always a dicey proposition... But you're probably right in this case that they'll have to anyway.  And it is better than giving them a mistaken impression that it's "baked-in".

I'm not sure I like the ``time.as_datetime_via_pytz``, though, because hopefully it would *not* be limited to ``pytz``: there are other time zone packages that conform to the ``tzinfo`` rules that ``datetime`` sets, and ideally this would be set up to support all of them if possible?

**Comment by taldcroft** [comment]
> I'm not sure I like the name as_datetime_via_pytz

I agree, no need to hardwire the implementation into the method name.  The method could check for available time-zone support packages and choose the best.  The `timezone` input itself could be anything from a string to a `pytz` object.

**Comment by taldcroft** [comment]
BTW, another thing I like about my idea :smile: is that we can do the *easy* thing now, which is for @bmorris3 to implement `Time.to_datetime(timezone=None)` right now as a straightforward new method in `Time`, in time for 1.1.  Then we can come back and generalize the concept outlined above [noting that it is basically @mhvk's idea] without changing the API.

**Comment by bmorris3** [comment]
I'd love to get started. If I were to write this as a method on `astropy.time.Time`, how can I get access to `self.datetime`?

**Comment by mhvk** [comment]
@taldcroft - I like your generalisation of my suggestion; much cleaner indeed to have `to_<format>` methods which allow one to pass arguments to the normal `<format>` properties. And I especially like the benefit of having an easy way forward right now!

@bmorris3 - as @taldcroft noted, with this idea it is fine to define a separate `to_datetime` method now; we can then see later if there is a need to generalize it for other time format classes in `__getattr__` (e.g., by checking whether a format class has a `to_value` method and then using that docstring). I think it would still be cleanest to go through a new `TimeDatetime.to_value(...)`, so that we keep the real changes there. If so, it might just be
```
    def to_datetime((self, timezone=None):
        tm = self.replicate(format='datetime')
        return tm._time.to_value(timezone)
    to_datetime.__doc__ = TimeDatetime.to_value.__doc__

class TimeDatetime(TimeUnique):
    ...
    def to_value(self, timezone=None):
        """<documentation>"""
        if timezone is not None:
            if self._scale != 'utc':
                raise ScaleValueError("...")
            ...
        <stuff from value>

    value = property(to_value)
```

**Comment by mhvk** [comment]
p.s. If you go for this, please do start with current master, as we just split the humongous `time/core.py` in several parts.

**Comment by taldcroft** [comment]
@mhvk - your skeleton code looks great.
@bmorris3 - go!  :smile:

**Comment by bmorris3** [comment]
@mhvk I don't quite understand the skeleton code. Is `<stuff from value>` supposed to be a copy of the contents of value? How and where should the new timezone specific part go?

**Comment by mhvk** [comment]
Indeed, `<stuff from value>` would be what is currently defined in the `TimeDatetime.value` property, but changed to ensure that any timezone information is added (if given). Inside the `if` statement, you would prepare that part.

But feel free to do it differently; the main suggestion was really to define a `TimeDatetime.to_value(timezone=None)` method, and use that for the `value` property.

**Comment by bmorris3** [comment]
It seems like the `iterator` implementation there forces the output to be a `numpy.ndarray` of `datetime` objects. Is there a way to force it to output lists?

**Comment by bmorris3** [comment]
Also, [will this line](https://github.com/astropy/astropy/blob/master/astropy/time/formats.py#L546) behave appropriately when `tzinfo` is not `None`?

**Comment by mhvk** [comment]
I think for consistency with the other format classes, we should output an object ndarray. However, one just does `t.datetime.tolist()` to get a list instead.

The line you point to is for *input* using `datetime`; I'm not quite sure how it would work with *output*, but I assume you want to have something before the actual assignment to [`out[...]`] (https://github.com/astropy/astropy/blob/master/astropy/time/formats.py#L572).

**Comment by bmorris3** [comment]
This is probably a silly question, but when I use a scalar time, this implementation gives me a 0d `ndarray` output, which prevents me from using the `datetime` methods in my tests. How can I expose those methods?

**Comment by mhvk** [comment]
Ah, I think what's missing is something that `.value` does, which is call `_shaped_like_input`, so my example above should have been:
```
    def to_datetime((self, timezone=None):
        tm = self.replicate(format='datetime')
        return tm._shaped_like_input(tm._time.to_value(timezone))
    to_datetime.__doc__ = TimeDatetime.to_value.__doc__
```
With that, for scalar input, you should just get out a `datetime` instance.

**Comment by eteq** [comment]
Closing this because #4124 solved it.
