### ISSUE TITLE
vstacking tables with different shaped array columns 

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4183]
I aim to collect light curves of objects of interest in a common table. However they contain slightly different number of epochs, and thus ``vstack`` refuse to work as those multidim columns have different shapes. I wonder whether there is a good workaround with masking the smaller ones to have the same size at the end?

Would you consider this as a sensible feature request?

These are the shapes:
```
In [14]:

[lc_tokeep[i]['hjd'].shape for i in range(6)]

Out[14]:

[(144, 168), (147, 168), (153, 164), (469, 164), (544, 164), (884, 162)]
```

The traceback is here. I can build up a standalone example if you think that would be useful.
```
---------------------------------------------------------------------------
TableMergeError                           Traceback (most recent call last)
<ipython-input-6-eeb37fe17aaa> in <module>()
      8         lc_tokeep.append(lc[is_cccp])
      9 
---> 10 lc_to_keep = vstack(lc_tokeep)

/home/bsipocz/devel/astropy/astropy/table/operations.pyc in vstack(tables, join_type, metadata_conflicts)
    250     col_name_map = OrderedDict()
    251 
--> 252     out = _vstack(tables, join_type, col_name_map)
    253 
    254     # Merge column and table metadata

/home/bsipocz/devel/astropy/astropy/table/operations.pyc in _vstack(arrays, join_type, col_name_map)
    732     n_rows = sum(lens)
    733     out = _get_out_class(arrays)(masked=masked)
--> 734     out_descrs = get_descrs(arrays, col_name_map)
    735     for out_descr in out_descrs:
    736         name = out_descr[0]

/home/bsipocz/devel/astropy/astropy/table/operations.pyc in get_descrs(arrays, col_name_map)
    476         uniq_shapes = set(col.shape[1:] for col in in_cols)
    477         if len(uniq_shapes) != 1:
--> 478             raise TableMergeError('Key columns {0!r} have different shape'.format(name))
    479         shape = uniq_shapes.pop()
    480 

TableMergeError: Key columns 'hjd' have different shape
```

**Comment by embray** [comment]
Hmm, interesting thought. I don't know exactly how that would work though. If something like this were built in it would have to be very general, and it's not obvious what the "best" way is to mask out a larger array with the shape of a smaller one.  Where do you place the mask? In the center?  At one end/corner?  According to a general function?

This is a problem that applies to more than just merging too (though I can see how it would be useful for merging).  What it really needs is some general way for comparing two arrays of different shapes in such a way that it's only comparing some intersection, if I understand correctly.

In the meantime I think the best thing to do would be to apply such a mask to your columns manually before trying to merge them.  I'm not exactly sure how to do that though...

**Comment by bsipocz** [comment]
I don't see a case where the place of the mask would matter, but most probably I'm already too focused on my own case and can't see out of the box. What operation do you in mind other than ``vstack``? The other ones seems unaffected by it as far as I see. 
(Maybe overwriting a Column with another different shaped one, but it's just one extra line to delete it first). 

At the moment I have this very ugly hack that does the job, but I'm not sure how it can be ported back nicely to the ``vstack`` function itself.

```
epoch_num = [len(lc_tokeep[i]['hjd'][0]) for i in range(len(lc_tokeep))]
max_epoch = np.max(epoch_num)

for i in range(len(lc_tokeep)):
    if epoch_num[i] != max_epoch:
        for col in ['flux', 'fluxerr', 'hjd']:
            new_col = np.zeros((len(lc_tokeep[i][col]), max_epoch))
            new_col[:, :] = np.nan
            new_col[:, :epoch_num[i]] = lc_tokeep[i][col]
            del lc_tokeep[i][col]
            lc_tokeep[i][col] = new_col
```

**Comment by taldcroft** [comment]
I agree with @embray that trying to generalize this is going to be difficult and might not be what people want for specific cases anyway.  For instance my first instinct would be to mask with masked arrays so that it can work for any dtype.  But you have chosen `nan` probably because that's comfortable for your workflow.  Then you get into cases where the number of dimensions don't agree, or there are 4 dimensions and 2 of them agree and 2 don't, etc.

So I'm inclined to say that users need to pre-process their tables in this case prior to stacking.

BTW, have you considered using an object dtype for the spectra?  In other words instead of a column of floats that is (n_objects, n_epochs), use a column of objects that is (n_objects) long and each element is an ndarray object.  Then you can happily stack and you don't have to mess around with all the `np.nan`s later.

**Comment by bsipocz** [comment]
@taldcroft - Thanks for the idea of putting them into an ``objects`` column. I'll check whether it brakes my code elsewhere.
The individual tables were originally read in from different fits bintables, and thus they automatically became floats.

**Comment by taldcroft** [comment]
@bsipocz - closing this per previous discussions.  Feel free to re-open if you have some ideas for resolving some of the concerns that were raised.

**Comment by bsipocz** [comment]
@taldcroft - Nope, closing it makes total sense. 

I didn't think beyond having only two dimensions, and you're right then it gets overcomplicated with many ambiguities.

**Comment by embray** [comment]
I think my point was that in general a merge needs to be able to compare the elements in two columns.  For different-shaped N-dimensional values we just throw up our hands because we don't know how to compare them.

So my point is that if we had some general function for comparing two differently shaped arrays, with different options for how their overlap should be determined, then I could see including support for that in merge (maybe even as a custom merge strategy).  But we would need such a function first.
