### ISSUE TITLE
astropy.io.fits  hdu.index_of

### ISSUE THREAD

**Issue by alainahenry** [astropy/astropy#4188]
hdulist.index_of() is really handy for processing fits files with lots of extensions.       It would be even more handy if it exited gracefully when, for example, hdulist.index_of('object_200')  doesn't exist.  Instead, it just crashes with the error "Extension not found."

**Comment by embray** [comment]
Thanks for the report.  However, this is fairly normal behavior for methods on collection-like objects in Python.  Take for example `list.index`:

```python
>>> lst = ['a', 'b', 'c']
>>> lst.index('b')
1
>>> lst.index('asdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 'asdf' is not in list
```

Asking for the index of an item not in the list raises an exception.  This shouldn't be viewed as a "crash" so much as an exception raised for an exceptional condition.  The (more C-like) alternative might be to return a negative integer, like `-1`.  But this is dangerous in Python, since many sequence-like collections in Python accept negative indexing.  Consider the following (contrived) example, if `list.index` returned a negative number:

```python
>>> names = ['apple', 'orange', 'pear']
>>> prices = [0.99, 0.75, 1.25]
>>> prices[names.index('orange')]
0.75
>>> prices[names.index('whatever')]
1.25
```

Same principle applies here.  Alternatively, if `index` returned `None` that might be okay, but can still lead to bugs in some cases.  This is where defensive coding comes in.  You can either look before you leap:

```python
if extname in hdulist:
    ext_indx = hdulist.index_of(extname)
else:
    # Do something else...
```

*or*, more efficient for cases where you expect failures to be uncommon, you can ask for permission:

```python
try:
    ext_indx = hdulist.index_of(extname)
except KeyError:
    # Do something else...
```

In "Pythonic" terms, this is "exiting gracefully".
