### ISSUE TITLE
1.1b1 does not work with wcslib 4.24

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4277]
The Beta version does not work with the "4" branch of wcslib, since wcslib_version is undefined:

```
==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
_pytest.runner:149: in __init__
    ???
[...]
_pytest.config:548: in importconftest
    ???
E   ConftestImportFailure: (local('/tmp/astropy-test-uRPzM6/lib.linux-x86_64-2.7/astropy/table/tests/conftest.py'),  (<type 'exceptions.ImportError'>, ImportError('astropy/wcs/_wcs.so: undefined symbol: wcslib_version',), <traceback object at 0x7f22f426c638>))
=========================== 1 error in 0.39 seconds ============================
```

**Comment by embray** [comment]
I think we're requiring wcslib 5.x, but I'm not positive if that's the case or where that would be documented.

**Comment by embray** [comment]
Adding to milestone to confirm and/or document this before v1.1.0 release.

**Comment by olebole** [comment]
@mdboom  [commented earlier](https://github.com/astropy/astropy/pull/3751#issuecomment-100201006) that 4.24 support will not be dropped yet. I could live with a 5.0+ requirement; however it may have a few drawbacks:

* I then need to schedule the transition to wcslib-5 in Debian to be in parallel with the update of Astropy. Any difficulty on one of these two tasks would influence the other.
* backporting to Jessie is much more difficult, since it involves a wcslib backport (and this will affect other packages)

The issue I reported here seems not to be too difficult to solve (I'll see if I find some time to create a patch myself).

**Comment by embray** [comment]
Okay, thanks for tracking that down.  It's still a rather old comment.  The one thing that makes me unsure is that I know a number of bugs have been fixed in newer versions of wcslib, and there may be tests related to those bugs that might fail if run against wcslib 4.24.  

If we can get the version issue fixed then it will be interesting to see what else works or doesn't work with wcslib 4.24..  I'll see what I can do with this as well.

**Comment by embray** [comment]
@nden or @mcara might have some thoughts about this as well since they know WCS much better than I do.

**Comment by eteq** [comment]
@embray - hmm... I did get it to work insofar as when I did ``astropy.wcs._wcs.__version__`` it showed 4.x instead of 5.10 (when my system wcslib was 4.25.1).  And even then the tests passed.

Perhaps it's that somehow my system was circumventing the bug, but @olebole's is not for some reason? (Not sure why that would be, but maybe I'll be able to check when you put in the patch...)

**Comment by embray** [comment]
I think the bug I encountered was only because I did `./setup.py build_ext --inline --use-system-wcslib`.  I think that if you just do `./setup.py install --use-system-wcslib` it should work.  In any case though, when I did this with wcslib 4.24 I got the same problem.  So at least now I can figure out what's going on.

**Comment by embray** [comment]
Okay, I think I see what's going on here.  

If you first build astropy without `--use-system-wcslib` it will generate a header file that is used to configure `astropy.wcs._wcs` to work with the wcslib that's compiled into it.  This file is output to a file called `wcsconfig.h` (there are a few copies of it for some reason).

If you then re-build with `--use-system-wcs` you need to make sure to start with a clean environment first or else it will include defines in that header file that are specific to the bundled wcslib and may not apply to the system version.

It would probably be good to automatically clean up these generated files, if they exist, when rebuilding with different flags.

**Comment by embray** [comment]
(TL;DR, run `git clean -dfx` and try again)

**Comment by embray** [comment]
(Also fwiw I did find that all the astropy.wcs tests still pass with wcslib 4.24--with 3 skipped and 2 xfailed).

**Comment by astrofrog** [comment]
@olebole - can you confirm that cleaning between builds fixes it for you?

If so, then this is no longer a blocker for 1.1

**Comment by olebole** [comment]
When removing all appearances of `wcsconfig.h`, this problem disappears; thank you for the hint.

**Comment by astrofrog** [comment]
@olebole - thanks! I've closed this since this issue is now resolved.

**Comment by embray** [comment]
I want to leave it open as a reminder to clean up the header files when building with `--use-system-wcslib`.

**Comment by bsipocz** [comment]
https://github.com/astropy/astropy-helpers/pull/205 is supposed to solved the underlying issue, so I'm closing this now. If there is any more action items regarding ``--use-system-*``, an issue should be opened in https://github.com/astropy/astropy-helpers for it.
