### ISSUE TITLE
WCS drops precision in to_header

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy#4292]
This appears to be a major regression.

I have loaded a file from disk, then created a WCS from its header.  This is the problem:

```
In [11]: w.wcs.crval[0]
Out[11]: 290.93293749999998

In [12]: w.to_header()['CRVAL1']
Out[12]: 290.9
```

cc @mdboom, even though I know you're off this now - maybe you can forward it appropriately?

EDIT: I cannot reproduce this programmatically:

```
In [19]: w = wcs.WCS()

In [20]: w.wcs.crval[0]=290.91231231231

In [22]: w.to_header()['CRVAL1']
Out[22]: 290.91231231231
```

EDIT2: here is a header that does reproduce the problem:
```
SIMPLE  =                    T /Standard FITS
BITPIX  =                  -32 /Floating point (32 bit)
NAXIS   =                    3
NAXIS1  =                  512
NAXIS2  =                  512
NAXIS3  =                  100
EXTEND  =                    T
BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO
BZERO   =   0.000000000000E+00
BMAJ    =   1.199828336636E-04
BMIN    =   1.125207212236E-04
BPA     =  -2.071810913086E+01
BTYPE   = 'Intensity'
OBJECT  = 'w51     '
COMMENT   1 blank line
BUNIT   = 'Jy/beam '           /Brightness (pixel) unit
EQUINOX =   2.000000000000E+03
RADESYS = 'FK5     '
LONPOLE =   1.800000000000E+02
LATPOLE =   1.450780000000E+01
PC01_01 =   1.000000000000E+00
PC02_01 =   0.000000000000E+00
PC03_01 =   0.000000000000E+00
PC01_02 =   0.000000000000E+00
PC02_02 =   1.000000000000E+00
PC03_02 =   0.000000000000E+00
PC01_03 =   0.000000000000E+00
PC02_03 =   0.000000000000E+00
PC03_03 =   1.000000000000E+00
CTYPE1  = 'RA---SIN'
CRVAL1  =   2.909329375000E+02
CDELT1  =  -1.444444444444E-05
CRPIX1  =   2.570000000000E+02
CUNIT1  = 'deg     '
CTYPE2  = 'DEC--SIN'
CRVAL2  =   1.450780000000E+01
CDELT2  =   1.444444444444E-05
CRPIX2  =   2.570000000000E+02
CUNIT2  = 'deg     '
CTYPE3  = 'FREQ    '
CRVAL3  =   2.335257723944E+11
CDELT3  =   4.999695392456E+05
CRPIX3  =   1.000000000000E+00
CUNIT3  = 'Hz      '
PV2_1   =   0.000000000000E+00
PV2_2   =   0.000000000000E+00
RESTFRQ =   2.340000000000E+11 /Rest Frequency (Hz)
SPECSYS = 'LSRK    '           /Spectral reference frame
ALTRVAL =   6.075635023296E+05 /Alternate frequency reference value
ALTRPIX =   1.000000000000E+00 /Alternate frequency reference pixel
VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio
COMMENT casacore non-standard usage: 4 LSD, 5 GEO, 6 SOU, 7 GAL
TELESCOP= 'ALMA    '
OBSERVER= 'keflavich'
DATE-OBS= '2015-04-23T09:59:29.760000'
TIMESYS = 'UTC     '
OBSRA   =   2.909329375000E+02
OBSDEC  =   1.450780000000E+01
OBSGEO-X=   2.225142180269E+06
OBSGEO-Y=  -5.440307370349E+06
OBSGEO-Z=  -2.481029851874E+06
DATE    = '2015-11-04T13:56:46.442251' /Date FITS file was written
ORIGIN  = 'CASA 4.5.0-REL (r35166)'
END
```

**Comment by mcara** [comment]
The reason for this behavior is in the way the `wcshdo_format()` function in the WCSLIB's [wcshdr.c](https://github.com/astropy/astropy/blob/master/cextern/wcslib/C/wcshdr.c) was designed to work: it computes precision using a single (for all `CRVAL`s) `expmax`. For example, see line 1676 in the above file:
```c
precision = nsig - (expmax + 1);
```
Unfortunately, in your case one of the `CRVAL` values, specifically `CRVAL3=2.335257723944E+11`, so it finds that `expmax=11` resulting in negative `precision` which is later set to 1:
```c
if (precision < 1)  precision = 1;
```
Probably this was by design as the whole code in the `wcshdo()` function in the same [wcshdr.c](https://github.com/astropy/astropy/blob/master/cextern/wcslib/C/wcshdr.c) file was designed to have a single format for all `CRVAL`s (see lines 800-809):
```c
  /* Coordinate value at reference point. */
  wcshdo_format('G', naxis, wcs->crval, format);
  for (i = 0; i < naxis; i++) {
    wcsutil_double2str(keyvalue, format, wcs->crval[i]);
    comment[0] = '\0';
    if (wcs->cunit[i][0]) sprintf(comment, "[%s] ", wcs->cunit[i]);
    strcat(comment, "Coordinate value at reference point");
    wcshdo_util(relax, "CRVAL", "CRV", WCSHDO_CRPXna, "CRVL", i+1, 0, 0, alt,
      colnum, colax, keyvalue, comment, nkeyrec, header, &status);
  }
```
This also explains why you cannot reproduce this behavior in your "programmatic example": you have a single `CRVAL`. Also, the code works OK with two "regular" (sky) `CRVAL`s but your real header has a third `CRVAL` of much larger value than the first two.

A fix would be:
```c
  /* Coordinate value at reference point. */
  for (i = 0; i < naxis; i++) {
    wcshdo_format('G', 1, &(wcs->crval[i]), format);
    wcsutil_double2str(keyvalue, format, wcs->crval[i]);
    comment[0] = '\0';
    if (wcs->cunit[i][0]) sprintf(comment, "[%s] ", wcs->cunit[i]);
    strcat(comment, "Coordinate value at reference point");
    wcshdo_util(relax, "CRVAL", "CRV", WCSHDO_CRPXna, "CRVL", i+1, 0, 0, alt,
      colnum, colax, keyvalue, comment, nkeyrec, header, &status);
  }
```
but it has to be done in `WCSLIB` and not in `astropy`. I will e-mail Dr. Mark R. Calabretta to report this issue.

**Comment by embray** [comment]
Is this not a duplicate of #3375?

**Comment by keflavich** [comment]
I don't think so - that is about a fixed loss of precision due to print formatting, this is about... The same thing but controlled by a different variable.  mcara can probably explain better if I'm right.

**Comment by nden** [comment]
Agreed, it's a different issue. It's not fixed by wcslib 5-11 as in #4263 either.

**Comment by mcara** [comment]
Indeed, this is a different issue from #3375, though both problems happen in the same function ``wcshdo()`` function in the same [wcshdr.c](https://github.com/astropy/astropy/blob/master/cextern/wcslib/C/wcshdr.c) file that I have mentioned above. The code affecting this issue is on lines 800-809 as I have mentioned above and it affects the format of CRVAL while the issue discussed in #3375 relates to the format ("%20.**12**G") used for (almost) everything else (such as LONPOL, LATPOL, RESTFRQ, etc.) which results in unnecessary loss of accuracy - see, e.g., lines 811-813:
```c
  /* Parameter values. */
  for (k = 0; k < wcs->npv; k++) {
    wcsutil_double2str(keyvalue, "%20.12G", (wcs->pv[k]).value);
```
By the way, the same function ``wcshdo_format()`` and the same logic of using a single format that is responsible for the loss of accuracy reported  by @keflavich in this issue is being used to write the PC matrix. So, for matrices with elements that have significantly different orders, one would expect to see the same problem as reported here.

**Comment by mcara** [comment]
Dr. Mark R. Calabretta reported that WCSLIB 5.12 released today fixes the original issue reported by @keflavich. However, I have checked the code and it seems that the code for writing the PC matrix still uses a single format for all matrix elements and the issue of limited accuracy in other WCS parameters (format "%20.**12**G" - see #3375) also was not addressed.

For the very least this issue can be closed once astropy starts using WCSLIB5.12.

**Comment by mcara** [comment]
Also CDELT is affected by this bug...

**Comment by nden** [comment]
I will package wcslib-5.12 with astropy if it can go in 1.1. If it's too late for it to be included in 1.1 it may be better to wait for further precision improvements in wcslib. @embray @astrofrog

**Comment by astrofrog** [comment]
@keflavich - can we close this now? It's a shame we didn't follow up on this sooner, I'd forgotten this was open before!

**Comment by keflavich** [comment]
Yeah, I guess #4612 is a duplicate of this and #4616 solves it.
