### ISSUE TITLE
which python version is good for contributing in astropy ?

### ISSUE THREAD

**Issue by RajuPilani** [astropy/astropy#4317]
most of astropy contributers use which python version (2.7 or 3.5 or 3.4).

**Comment by embray** [comment]
That's actually a good question.  @astrofrog has been carrying out regular surveys of the community, the most recent of which showed just 16% on Python 3.4 (3.5 wasn't out yet), but still a significant increase since 2012: http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/  This is a broad survey though--I don't actually have a good sense of what most of the regular Astropy contributors are using now.  I've tried to push people toward Python 3, but I don't think everyone has made the switch.

I'm still using Python 3.4 as my default Python right now.  I plan on switching to 3.5 at some point but just haven't gotten around to it yet.  In the future though questions like this should be addressed to the mailing list.  The issue tracker should only be used for issues in the code / feature requests.
