### ISSUE TITLE
1.1rc1: vo_test.py::TestThroughBinary::test_string_test fails on i386

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4352]
On i386, `vo_test.py::TestThroughBinary::test_string_test` fails without any further information ([full log](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=i386&ver=1.1~rc1-1&stamp=1448403295)):
```
astropy/io/votable/tests/vo_test.py::TestThroughTableData::test_schema PASSED
astropy/io/votable/tests/vo_test.py::TestThroughBinary::test_string_test debian/rules:56: recipe for target 'test-python2.7' failed
make[1]: *** [test-python2.7] Error 245
```
During the test run, this happens when the test is executed the second time -- it seems that many VO tests are execute twice (for the same Python version).
Since on another i386 architecture (GNU HURD) [all tests are fine](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=hurd-i386&ver=1.1~rc1-1&stamp=1448424911), I am not sure whether this is reproducible; it may be a one-time problem with our builder.

**Comment by eteq** [comment]
@pllim or @mdboom - any ideas?

I have also noticed that some of the `votable` tests run twice for no clear reason... I wonder if its because some of them are classes instead of functions?  I admit to very little experience using that idiom...

**Comment by embray** [comment]
@eteq The reason some of them run twice is because of the [`# TEST_UNICODE_LITERALS`](https://github.com/astropy/astropy/blob/master/astropy/io/votable/tests/vo_test.py#L3) http://astropy.readthedocs.org/en/latest/development/testguide.html?highlight=test_unicode_literals#testing-with-unicode-literals

**Comment by embray** [comment]
I wonder if there's some off chance this is related to #4240 since it's also an unexplained test exist in the votable tests. Not sure though.

The platform specificity also suggests the problem could be something deeper, not specific to Astropy.  For example this would not be the first time a libexpat bug has been encountered in such a context.

**Comment by eteq** [comment]
@olebole - can you clarify if this is a *repeatable* failure?  #4240 is about a problem that seems to be non-deterministic (once in a while it happens on travis, but not too often), so it would be useful to know if it's actually this platform as opposed to just that the failure happens once in a while on *any* architecture.

**Comment by olebole** [comment]
I hope that I can make a test at the weekend. However, I guess that it happens only occasionally -- otherwise I would expect the HURD-i386 to fail as well.

**Comment by olebole** [comment]
Sorry; I couldn't find time. However, I now uploaded 1.1rc2 which succeeds. So, this is non-deterministic and probably covered by #4240. Therefore, I am closing this.
