### ISSUE TITLE
Electric charge base unit in cgs should not be Coulomb

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4354]
The following example returns a unit of Coulomb-centimeter, but Coulomb is an SI unit:

```
In [1]: from astropy import units as u

In [2]: u.debye.decompose(bases=u.cgs.bases)
Out[2]: Unit("3.33333e-28 C cm")
```

**Comment by eteq** [comment]
I think this *might* be intended behavior, although admittedly a bit counter-intuitive.  Remember that "cgs" alone isn't enough to determine how E&M constants and units behave: you have to decide if you're using electrostatic, gaussian, or one of the other conventions.  So maybe the choice was made to do `C` instead of picking one of them? There's some discussion of this in #745, although I think there's some elsewhere too that's more relevant.  @embray or @mdboom might also remember more clearly.

Regardless, the current behavior does seem counter-intuitive, though. See #4355 for an alternative approach.
