### ISSUE TITLE
Some "edit on github" links lead to 404

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#4361]
Look at, e.g. http://astropy.readthedocs.org/en/latest/api/astropy.stats.poisson_conf_interval.html#astropy.stats.poisson_conf_interval

There is a link in the top left saying [edit on github]. This link **does** work.
However, there is also a "edit this page on github" link in the footer at the very bottom of the page. That link does **not** work. Presumably, that's true for all autogenerated API pages.
I don't think it's urgent or really a problem, but I open an issue here, so that we can look at it, if we ever modify the sphinx templates again.

**Comment by eteq** [comment]
Ah, good point.  Probably the thing to do is just hide it for anything that's generated.

It looks like the `edit_on_github` sphinx extension has an option called `edit_on_github_skip_regex` (which defaults to ``"_.*"``) that gives a regex for things that should *not* get the link.  Maybe it's as simple as adding ``api/.*`` to the default regex?

**Comment by souravsingh** [comment]
I can work on this

**Comment by hamogu** [comment]
Great! I'm looking forward to see the PR, since I don't know much about the tricks used for the doc builds myself!

**Comment by sudheesh001** [comment]
After fixing this as @eteq pointed out, When I open the documentation I do not see the `Edit on github` link at the bottom as mentioned and I believe this is right since this page is generated ? 
Should this be linked to `astropy.stats.poisson_conf_interval.rst` but that file is a generated file in `api/*` ?

This was the result of building the docs, has something gone wrong ? 
```bash
generating indices... genindex py-modindex
 (177 module code pages)Traceback (most recent call last):
  File "<stdin>", line 31, in <module>
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 252, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 326, in build
    self.finish()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 456, in finish
    self.finish_tasks.add_task(self.gen_additional_pages)
  File "/usr/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 39, in add_task
    res = task_func()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 482, in gen_additional_pages
    self.handle_page(pagename, context, template)
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 787, in handle_page
    templatename, ctx, event_arg)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 512, in emit_firstresult
    for result in self.emit(event, *args):
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "/Users/sudheeshsinganamalla/Documents/astropy/astropy_helpers/astropy_helpers/sphinx/ext/edit_on_github.py", line 140, in html_page_context
    doc_path = os.path.relpath(doctree.get('source'), app.builder.srcdir)
AttributeError: 'NoneType' object has no attribute 'get'
Sphinx Documentation subprocess failed with return code 1
```
Here's the git diff
```diff
diff --git a/docs/conf.py b/docs/conf.py
index 1935a3e..b9ce5fb 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -193,6 +193,8 @@ else:
 edit_on_github_source_root = ""
 edit_on_github_doc_root = "docs"

+edit_on_github_skip_regex = "api/.*"
+
 github_issues_url = 'https://github.com/astropy/astropy/issues/'

 # Enable nitpicky mode - which ensures that all references in the docs
(END)
```
Is this the way this is supposed to be fixed ?

**Comment by embray** [comment]
Where did the edit_on_github sphinx extension come from?  Did you write that @eteq?  It looks like the `edit_on_github_skip_regex` option doesn't actually work properly.

**Comment by embray** [comment]
Or actually, more importantly, what it looks like is this extension always fails on documents that match the default regex of `_.*`, but more by accident by anything else.  We skip those on Astropy because in the Astropy docs there are some generated pages that happen to start with `_`.  But there's no reason that needs to be the case for some arbitrary project's docs either.

I think instead `html_page_context` should always pass over pages that don't have a doctree (`doctree is None`).  This will need to be fixed in astropy-helpers.

Meanwhile instead of setting `edit_on_github_skip_regex = 'api/.*'` should should also incorporate the default value for that option.  So it should set `edit_on_github_skip_regex = '_.*|api/.*'`.  @sudheesh001 if you want to try that, it should work around the crash you demonstrated.
