### ISSUE TITLE
1.1 pypi tarball contains `astropy_helpers/build/lib.macosx-10.10-x86_64-2.7/` subdir

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4396]
Hi,

the tarball downloaded from pypi contains a leftover from a previous build: `astropy_helpers/build/lib.macosx-10.10-x86_64-2.7/`.

Best

Ole

**Comment by astrofrog** [comment]
Sorry about that! @eteq @embray - shall we do a ``post1`` release? Or just ``1.1.1``?

**Comment by olebole** [comment]
It is not urgent at all; just to remind to check these things before 1.1.1 :-)

**Comment by astrofrog** [comment]
I think that this happened because I included ``build`` before ``sdist`` by reflex (even though it's not needed) as described in step 5 here:

http://docs.astropy.org/en/stable/development/affiliated-packages.html#releasing-an-affiliated-package

for affiliated packages. But I think that ``build`` should be explicitly excluded in the MANIFEST?

**Comment by eteq** [comment]
@astrofrog - hmm... I'm pretty sure I did ``python setup.py build sdist`` too when creating the tarball for the core package v1.1, and that did *not* end up with a `build/anything` dir... And the ``MANIFEST.in`` there *does* have a line ``prune build``.  So that's probably it?

**Comment by embray** [comment]
That shouldn't have been there--you need to make sure to clean your astropy_helpers submodule too--`git clean` does not go into submodules.

I'll release a new tarball with .post1

**Comment by embray** [comment]
It occurs to me now that we should also add to the release documentation procedures for making and uploading post-release tarball.  I started out doing this by updating the version in the setup.py and tagging a new release, going through the full procedure again.

But that means that users who install this will see `astropy.__version__` as `v1.1.post1` but I don't want to confuse them with that, since `v1.1.post1` is no different substantively from `v1.1`.  It's just a different release tarball.

I'm still trying to work out what the best procedure should be, in this case.  In the future it will be nice to have a way to automate this.

**Comment by embray** [comment]
Okay, here's what I wound up doing:

1. Check out the v1.1 tag-- `$ git co v1.1`
2. Make sure the source is clean-- `$ git fresh; (cd astropy_helpers && git fresh)` (note: `git fresh` is an alias I use that's equivalent to `clean -d -f -x -e .tox` so that it preserves my local tox envs)
3. Temporarily edit `setup.py` to set `VERSION = '1.1.post1'`. DO NOT COMMIT.  Instead, just run `./setup.py build register`, then revert the `setup.py`.  This is just a convenient way to register the new release and upload all the proper metadata to PyPI.  The release could also be registered manually through the PyPI web interface, but then one has to manually fill in all the metadata and that's a pain.
4. With the version reverted to the original `v1.1`, run `$ ./setup.py build sdist`.  This will create a new sdist equivalent to the original one for v1.1 (though presumably cleaned up).  Double check that it does in fact have all the desired files, and no undesired files.  Double check that `astropy/version.py` gives the version as `'1.1'`.
5. Now rename the sdist to `astropy-1.1.post1.tar.gz`.  Also generate a signature-- `$ gpg --armor --detach-sign dist/astropy-1.1.post1.tar.gz`
6. Finally, manually upload the new source tarball, along with the signature, through the PyPI web interface as a new file for astropy 1.1.post1.

Now `pip install astropy` grabs astropy 1.1.post1 by default.  However, the installed package is otherwise no different, including the package version and other metadata, from astropy 1.1.  Only the release metadata is slightly different, and users generally won't care about that.

I'm not sure if this is the best approach or not. It would be great if there were more guidance from the community on this.  I'll ask on distutils-sig (or see what's been said in past discussion about this, as I know there has been some).  It might also be helpful if the `./setup.py register` and `./setup.py upload` commands allowed some kind of manual overrides for the release metadata.  For example `./setup.py register --version 1.1.post1` might register the package's version as 1.1.post1 regardless of what metadata would otherwise be produced from the setup.py script.  That would be effectively equivalent to what I did, but would make it less of a hassle.

**Comment by embray** [comment]
Also for posterity the new release is at https://pypi.python.org/pypi/astropy/1.1.post1
