### ISSUE TITLE
fits.open throws up error: 'Could not find appropriate MS Visual C Runtime '

### ISSUE THREAD

**Issue by conor-byrne** [astropy/astropy#4398]
![image](https://cloud.githubusercontent.com/assets/15220966/11768095/6f58f05e-a1ba-11e5-8c98-4fb9a0ae773c.png)

    Python 3.5.1
    msvc_runtime 1.0.1
    astropy 1.1

Apologies if it's a really simple error on my part. Just can't seem to figure it out.

**Comment by mwcraig** [comment]
I'm wondering....how do you really feel about iraf? ;)

Thanks for reporting this. I believe this is the same issue reported in #4342 where the upshot was you can safely ignore the warning for now. 

Closing because it looks like a duplicate, but @conor-byrne please reopen if it turns out you can't use the `hdu_list` you created.

@embray, please reopen this if I'm wrong.

**Comment by embray** [comment]
@conor-byrne As @mwcraig wrote it's a known issue.  You can ignore the warning--it's not important unless you're passing in an open file object to `fits.open` (as opposed to just a file name), and even then it's not that important.  Please continue telling IRAF where it can stick it :)
