### ISSUE TITLE
Upgrading to 1.1 via pip fails

### ISSUE THREAD

**Issue by abhimat** [astropy/astropy#4402]
I am getting the following error while upgrading to Astropy 1.1 via pip:

`Command python setup.py egg_info failed with error code 1 in /Users/abhimat/software/Ureka/variants/common/build/astropy`

Any ideas on what’s going on and how I can upgrade?

This is on OS X 10.6.8, and I have Python installed via Ureka 1.5.1.

Thanks!

**Comment by astrofrog** [comment]
@abhimat - could you send the full output log?

**Comment by pllim** [comment]
STScI has been getting a lot of help calls about Ureka and the latest Astropy in the past 24 hours. @jhunkeler submitted a fix in #4401.

**Comment by abhimat** [comment]
Here’s the full pip log attached:
[piplog.txt](https://github.com/astropy/astropy/files/63082/piplog.txt)

**Comment by pllim** [comment]
I think this is the source of the problem. Something is missing...

```
Downloading from URL https://pypi.python.org/packages/source/a/astropy/astropy-1.1.tar.gz#md5=358122aa42a5ae1e7d6c955cf3ed2f35
Running setup.py (path:/Users/abhimat/software/Ureka/variants/common/build/astropy/setup.py) egg_info for package astropy
...
    warning: manifest_maker: standard file '-c' not found
    
    Compiler specified by CC environment variable
                                (cc:i686-apple-darwin10-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.9)
    Copyright (C) 2007 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.) will fail to compile
                                astropy.
    
                                Please set CC=clang and try again.
                                You can do this, for example, by running:
    
                                    CC=clang python setup.py <command>
    
                                where <command> is the command you ran.
...
```

**Comment by astrofrog** [comment]
@abhimat - can you do ``echo $CC``?

**Comment by abhimat** [comment]
It prints out `cc`. Should I set `$CC` to `clang`?

**Comment by abhimat** [comment]
Setting `$CC` to `clang` appears to solve the issue. Thanks for all your help!

**Comment by astrofrog** [comment]
@abhimat - you could also have unset ``$CC`` I think. I'm not sure why some people have it set to ``cc`` do you have any ideas where that came from?

**Comment by abhimat** [comment]
It gets set to `cc` when I run `ur_setup` for Ureka

**Comment by astrofrog** [comment]
Huh, that doesn't seem right

@jehturner, can you comment on this?

**Comment by pllim** [comment]
Uhhh you mean @jhunkeler?

**Comment by astrofrog** [comment]
@pllim - I meant @jehturner because I thought he might know the reason for this (as one of the Ureka authors)

**Comment by jehturner** [comment]
I believe it's there for IRAF compilation. It was probably put there by Mark serveral years ago and I'm not certain what happens if it's unset but it wouldn't surprise me if it causes IRAF builds to fail. When we initially did this stuff, there wasn't actually much expectation of users compiling things as a matter of course but then pip came along...

We should probably reconsider these environment settings. You might have seen that we're planning to re-base Ureka on Anaconda next year anyway, which will mean replacing or reimplementing ur_setup. Also, we do need to investigate compilation on newer MacOS versions anyway. It would be a nuisance if IRAF compilation no longer works "out of the box", which was one of our improvements, but it doesn't make much sense if it breaks the newer stuff. Maybe we can hack the IRAF compiler to pick up the right CC without that setting.

It looks like we're actually using gcc to build the Python packages on MacOS, including AstroPy. Is there a special reason why AstroPy now wants clang? Is it because of #4401? Thanks for pointing this out.

**Comment by embray** [comment]
I'm going to go ahead and close this since it's due to a known issue that already has a workaround.  Thanks.
