### ISSUE TITLE
1.1.post1 naming doesn't work with pip

### ISSUE THREAD

**Issue by defjaf** [astropy/astropy#4406]
When I `pip install --upgrade astropy`, it downloads and installs just fine, but `pip` somehow doesn't realise that it's happened, and it shows up again if I do `pip list --outdated`.

I'm on OS X, with python.org python 2.7.11 or 3.5.1

		% pip list --outdated
		astropy (Current: 1.1 Latest: 1.1.post1 [sdist])

		% pip install --upgrade --no-deps astropy
		Collecting astropy
		  Using cached astropy-1.1.post1.tar.gz
		Installing collected packages: astropy
		  Found existing installation: astropy 1.1
		    Uninstalling astropy-1.1:
		      Successfully uninstalled astropy-1.1
		  Running setup.py install for astropy
		Successfully installed astropy-1.1

		% pip list --outdated
		astropy (Current: 1.1 Latest: 1.1.post1 [sdist])

**Comment by olebole** [comment]
FYI, this is connected to #4396.

**Comment by astrofrog** [comment]
@embray - any ideas why this is happening?

**Comment by embray** [comment]
This appears to be an artifact of [how I build the 1.1.post1](https://github.com/astropy/astropy/issues/4396#issuecomment-165579651) source distribution, in such a way that the package version is still just "1.1" and not "1.1.post1".  This was out of a desire to publish a new source tarball release without actually increasing the package version, since there is no actual difference in the package.

Turns out when you do this though, the generated metadata for the package will not contain the .post1, so pip gets confused about what's being installed.  What a nuisance.  There really ought to be a better way to distinguish the software version from the release version, which are two different things (for example I don't think `astropy.__version__` should report the `.post1` which has *nothing* to do with the software.  However, `setup.py` needs to report the version as `1.1.post1` in order for the distribution metadata to be correct.  I can make changes in astropy-helpers' version utilities to facilitate this.  In the meantime I will make a new release tarball.

**Comment by embray** [comment]
Okay, I've pushed astropy 1.1.post2 which fixes this.

I made the new release by the following procedure (which should supersede the one I described in #4396):

1. Check out the original release tag: `$ git co v1.1`
2. Clean the git checkouts: `$ git clean -dfx; (cd astropy_helpers && git clean -dfx)`
3. Manually edit the `VERSION = ` line in setup.py to `VERSION = '1.1.post2'`.  This ensures that the *distribution*/release version as reported by setup.py, and all metadata generated from the setup.py, is "1.1.post2".  Do not commit to git or anything, for now.
4. Run `$ ./setup.py build`.  This outputs the generated `astropy/version.py` file.  Manually edit this file to change the `version =` line from `version = '1.1.post2'` to just `version = '1.1'`.  This "version" in this file should be the *software* version, not the distribution version.  In the past there's been no reason to make a distinction.  In this case there is though.
5. Edit the setup.py again to comment out the call to `generate_version_py` to prevent the manually updated file from being overwritten again.
6. Now run `$ ./setup.py register` and `$ ./setup.py sdist upload --sign`.  The newly posted release has the correct release metadata, but also the correct software version.
7. Revert the temporary changes to setup.py.

Obviously this is all far from ideal.  This is the first time we've had to post updated release tarballs since the new PyPI policy was enacted.  I will make some small updates to astropy-helpers to more clearly differentiate between distribution version and the actual software package version, so that "post releases" like this can be made without any tinkering.

I still want to bring this up on distutils-sig too.  Having now been through this process I think there needs to be a clearer way built into the tooling (i.e. in setuptools) for making these kinds of post-releases that don't otherwise contain any code changes, now that it's being required by PyPI.
