### ISSUE TITLE
Time.get_delta_ut1_utc() is not consisent with Time.ut1.value-Time.utc.value during leap seconds

### ISSUE THREAD

**Issue by danielsf** [astropy/astropy#4409]
If I instantiate an astropy.time.Time instance in the middle of a day in which a leap second occurs and then calculate dut1 using get_delta_ut1_utc(), I get different (often by a minus sign) values than if I calculate the dut1 using ut1.value-utc.value.

The script below demonstrates what I mean.

utc_list is a list of JD's selected from the list of leap seconds published at

http://maia.usno.navy.mil/ser7/tai-utc.dat

I first loop over them, calculating dut1 using both methods described above and printing the results.  They agree.

If I take utc_list, subtract 0.2 (so that utc_list is in the middle of the day on which the leap second is applied), and perform the same analysis, the two methods for calculating dut1 give wildly different results.

If I take utc_list, subtract 1.2, and perform the same analysis, the two methods for calculating dut1 again agree.

This is using version 1.1 of astropy.
```
import numpy as np
from astropy.time import Time

if __name__ == "__main__":

    utc_list = np.array([2445516.5, 2446247.5, 2447161.5, 2447892.5,
                2448257.5, 2448804.5, 2449169.5, 2449534.5,
                2450083.5, 2450630.5, 2451179.5, 2453736.5])

    print '\ncompare get_delta_ut_utc with ut1-utc at exact moment of leap second'
    print '#'
    print '# get_delta_ut1_utc().value, 86401.0*(ut1.value-utc.value)'
    for utc in utc_list:
        jd = Time(utc, scale='utc', format='jd')
        print jd.get_delta_ut1_utc().value, 86401.0*(jd.ut1.value-jd.utc.value)

    print '\n'
    print 'displace by 0.2 days so that we are considering a moment during'
    print 'the day of the leap second'
    print '#'
    print '# get_delta_ut1_utc().value, 86401.0*(ut1.value-utc.value)'
    for utc in utc_list:
        jd = Time(utc-0.2, scale='utc', format='jd')
        print jd.get_delta_ut1_utc().value, 86401.0*(jd.ut1.value-jd.utc.value)

    print '\n'
    print 'displace by 1.2 days so that we are outside of the leap second day'
    print '#'
    print '# get_delta_ut1_utc().value, 86400.0*(ut1.value-utc.value)'
    for utc in utc_list:
        jd = Time(utc-1.2, scale='utc', format='jd')
        print jd.get_delta_ut1_utc().value, 86400.0*(jd.ut1.value-jd.utc.value)
```

**Comment by mhvk** [comment]
@danielsf - the problem here is the comparison between to `value` that you are doing.  Given that you set `format='jd'`, the `value` you get is a julian date. For UTC, this has an odd but well-defined result, which is that, as you in fact use, on days with leap seconds, one day equals 86401 seconds:
```
(Time(2445516.5, format='jd') - Time(2445516.5 - 1, format='jd')).sec
# -> 86401.0
```
However, this is *not* true in other time scales. A UT1 JD always has 86400 s seconds (because by definition it is one full rotation of the earth):
```
(Time(2445516.5, scale='ut1', format='jd') - Time(2445516.5 - 1, scale='ut1', format='jd')).sec
# -> 86400
```

So your problem arises because you take `.value` of two different entities, which have different scales, and can thus not be compared directly. Indeed, the only *correct* answer is that `jd.utc - jd.ut1` should yield 0, since they refer to exactly the same instance in time. And indeed, this is, fortunately, the case:
```
n [9]: t = Time(2445516.5 - 0.2, format='jd')

In [10]: t.get_delta_ut1_utc()
Out[10]: -0.24936691999973204

In [11]: (t.ut1 - t.utc).sec
Out[11]: 0.0
```

These kinds of issues can be avoided by sticking to `Time` classes, and calculating differences directly (i.e., getting `TimeDelta`). For conversion, I'd strongly recommend sticking with just using `(t1-t2).to(u.s)`, etc., i.e., converting to `Quantity` -- it helps avoid a lot of hard-to-track problems!

If this answers this issue, is there something in the documentation that would have helped to avoid it?

**Comment by danielsf** [comment]
Thanks.  Sorry for the confusion.

I'm not sure that anything needs to be added to the astropy documentation.  My confusion arises more from the 'documentation' of the various time systems.  For example, I was not aware that the JD was defined to always be 86400 seconds in UT1.  Actually, I haven't managed to find a reference that defines the length of a day in any of the interesting time scales -- TAI, UTC, UT1, TT, TDB.  The focus seems to be more on seconds of displacement between the systems.  Is there a reference you would recommend reading to get a handle on all of this?

Thanks again.

**Comment by mhvk** [comment]
The second is 1/86400 of a day in all time scales *except* UTC. Which of course happens to be the one we use most...  I don't have a particularly good reference beyond those @taldcroft added to the `Time` documentation: http://docs.astropy.org/en/latest/time/index.html#time-scale

Anyway, I'll close this issue -- feel free to re-open if you have further questions. And please don't hesitate to raise other issues if you think something is wrong: it is quite likely the next time you've run into a real bug!

**Comment by embray** [comment]
Indeed, the `.value` of different times in different scales should not be compared directly--it's akin to dropping units.
