### ISSUE TITLE
Compiling Astropy Six Module?

### ISSUE THREAD

**Issue by rankinstudio** [astropy/astropy#4418]
I have tried cx freeze, py2exe, and pyinstaller. They all return the same error stating the Astropy requires the six module and it should be bundled with it? Is there any way to compile astropy into a distributed windows exe? 

Thanks!!

python 3.4.3 pyinstaller 3

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

    "distribution.".format(_SIX_MIN_VERSION))
ImportError: Astropy requires the 'six' module of minimum version 1.7.3; normall
y this is bundled with the astropy package so if you get this warning consult th
e packager of your Astropy distribution.

C:\Users\David\Desktop\pyins\dist\ASTEROIDHUNTER>

**Comment by rankinstudio** [comment]
As a temp solution for those running into this error, you can use Pyfits with pyinstaller to compile an EXE which can read fits files.

**Comment by embray** [comment]
It's not a trivial thing to do.  It's going to require some changes in Astropy, as well as probably a PyInstaller hook.  I got this working once before for WebbPSF but it required deep knowledge and some tweaking.  See #960 for the existing discussion.  I worked on this a couple years ago but there hasn't been enough demand to see this through as something that will "just work".  If you want to try reading the existing discussion on that PR and following up there with any questions feel free, but I'm closing this issue as a duplicate.

**Comment by embray** [comment]
(As for the specific issue with the `six` module you will find many examples of this in the course of trying to bundle a complex package like Astropy using PyInstaller or its ilk--these programs *attempt* to determine what files and modules will be used by the package *by* your executable, and strips packages down to what it thinks is the bare minimum.  But it's making guesses here and those guesses aren't always correct--in many cases they exclude files that should not be excluded.  That's why you need to write a hook for PyInstaller specific to Astropy, providing rules for how Astropy should be bundled.  You'll find this to be the case with any complex package (see for example Numpy))

**Comment by rankinstudio** [comment]
Thanks for the reply Embray. I was able to accomplish what I needed by including pyfits instead of astropy. Cheers!

**Comment by embray** [comment]
@rankinstudio Okay, but you should be aware that support for pyfits as a standalone package is effectively ended.
