### ISSUE TITLE
Issue while subclassing astropy.modeling.core.Fittable1DModel

### ISSUE THREAD

**Issue by ycopin** [astropy/astropy#4419]
In this [gist](https://gist.github.com/ycopin/cd07f3c6fe3b8b024fba), I tried to implement the Gauss-Hermit expansion (e.g. [van der Marel & Franx 1993](http://adsabs.harvard.edu/abs/1993ApJ...407..525V)) from standard `Gaussian1D` and newly implemented polynomial class `Hermite1D`. 

Yet, this simple example does not work for some **unknown** reasons: the parameters of the model are just not updated correctly. Any guidance in the internal bits of `astropy.modeling` would be much appreciated.

**Comment by embray** [comment]
I don't think it's a very simple example, and I provided some feedback in the original gist a long while ago.  

Implementing polynomial-like models that take different numbers of parameters depending on some attribute like their degree or order is still tricky business.  I've also had a lot of conversations with @wkerzendorf about this.  You may be interested in evaluating my experimental PR for updating how to make polynomial models:  #4049

Based on my conversations about it with @wkerzendorf I think it may still be a little too confusing, but it's a start.  Another thing I have in mind is to make it easier to add a parameter that is required to take an array as a value, where that array can for example represent a sequence of coefficients.

Since this doesn't really identify a single issue I'm going to close it but I'm happy to discuss this more offline.

**Comment by ycopin** [comment]
I take your point that this issue is not specific enough, but I still wonder how I should proceed on this specific issue which, as you mentioned, is rather old. Any hope with `astropy.modeling.custom_model`? (but the number/name of parameters have to be known a priori)

**Comment by embray** [comment]
I'll see if I can implement your example myself.  I think that what's really needed here is better support for subclassing polynomial models.  #4049 made some progress on that but I haven't fully tested.

**Comment by nden** [comment]
@ycopin @embray Perhaps the easiest way to do this model (may not be the most efficient) is to use a combined model. I left an example of this in the gist. Let me know what you think.
