### ISSUE TITLE
Disable raising deprecations as exceptions in runtime dependencies

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#4430]
It would be great to have a way to only enable raising the deprecations as exceptions in the tested packages and not in upstream dependencies (affiliates use `astropy.tests.pytest_plugins.enable_deprecations_as_exceptions` to do this, thus I open the issue here).

I got an exception when testing numpy 1.10 with gammapy and it's dependency (sherpa) triggered a numpy `DeprecationWarning` that made the test fail. Ideally using `enable_deprecations_as_exceptions` I would be only interested in the warning triggered by gammapy itself.

**Comment by embray** [comment]
I have mixed feelings about this.  On one hand I want to know about warnings coming from my dependencies too, because users are probably going to see those warnings, which means it becomes my job (unfortunately) to report them to the upstream dependencies.  I'm less likely to notice.

On the other hand I've been annoyed by this too and it would be good to have an option for this.  In fact I'd be inclined to make it disabled by default (but for CI purposes it should be enabled...)

**Comment by bsipocz** [comment]
#6223 probably provides the feature I asked for here, so closing.
