### ISSUE TITLE
QTable not always converting to Quantity?

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#4497]
I've noticed some odd behavior with QTable that seems counter-intuitive, but I'm not sure whether it's a bug or a feature.  Consider the following snippet:
```
tab = QTable.read(...)
tab['X'].unit = u.Mpc

top2 = []
for k,v in elvii_pairs.items():
    top2.append(v['X'][:2])
top2 = u.Quantity(top2).flatten()
```

I would have thought that top2 would then be a Quantity with units Mpc, but instead it ends up as a *dimensionless* Quantity.

Similary, I would have thought this would also do the same:
```
top2 = []
for k,v in elvii_pairs.items():
    top2.extend(v['X'][:2])
top2 = u.Quantity(top2)
```
But this also yields a dimensionless result.  The cause of this at least I understand, given this snippet:
```
qornot = top2['X'][0]
assert hasattr(qornot, 'unit')  # AssertionError!
```
That is, indexing a single element of a column yields a python number, *not* a Quantity.  But that seems very unexpected behavior given that `QTable` is supposed to yield Quantities.

@taldcroft @mhvk, are any/all of these bugs, or intended behavior?

**Comment by mhvk** [comment]
@eteq - yes, this seems wrong, but before anything else, what is`type(v['X'])`? Are you sure it is a `Quantity`? (Also, to understand your snippet, what is `elvii_pairs`? How does it relate to `tab`?)

**Comment by taldcroft** [comment]
@eteq - this is intended in the current design.  If you initialize a QTable with something that does not have units, it is a `Column`.  (This answers the question from @mhvk).  You can provide a unit and that does get carried through a slice.  I don't quite understand in your example why you are not getting `u.Mpc` out as the unit.
```
In [3]: t = QTable([[1]], names=['a'])

In [4]: type(t['a'])
Out[4]: astropy.table.column.Column

In [5]: t['a'].unit = 'ascdas'

In [6]: type(t['a'].unit)
Out[6]: astropy.units.core.UnrecognizedUnit

In [7]: type(t['a'][:2].unit)
Out[7]: astropy.units.core.UnrecognizedUnit

In [8]: u.Quantity(t['a'][:2])
Out[8]: <Quantity [ 1.] ascdas>
```
When you iterate over a `Column` object then the unit is lost and you just get numpy scalars.  That is the source of your issue here.

In theory we might consider upgrading a `Column` to `Quantity` if the unit is assigned (within a `QTable`).  

I haven't thought about this recently or in detail, but I think that making the default within `QTable` to create a `Quantity` (potentially dimensionless) for everything would introduce compatibility problems.

**Comment by mhvk** [comment]
> In theory we might consider upgrading a `Column` to `Quantity` if the unit is assigned (within a `QTable`).

This may not be a bad idea.

> I haven't thought about this recently or in detail, but I think that making the default within `QTable` to create a `Quantity` (potentially dimensionless) for everything would introduce compatibility problems.

Certainly would have to exclude strings. Also, '`Quantity` by default turns all numbers into `float`, which may or may not be a problem. Finally, if the reader did immediately create a `Quantity`, one could not set the unit any more (though it may be possible within `Quantity` to allow one to set a unit if the unit has not yet been defined; I think that would make some sense, in fact).

All this said, @eteq's problem shows that the current behaviour can be unexpected; we may need to think about allowing more choice and/or changing the defaults.

**Comment by mhvk** [comment]
p.s. I thought the following might be a nice work-around for @eteq, but it doesn't work:
```
t['a'] = t['a'] * u.Mpc
t
# <QTable length=1>
#   a  
# int64
# -----
#     1
```
This is because internally the code does `self.columns[item][:] = value`, and `ndarray` and subclasses happily ignore the unit.  What does work is:
```
t.replace_column('a', t['a']*u.Mpc)
t
# <QTable length=1>
#    a   
#   Mpc  
# float64
# -------
#    1.0
```

**Comment by mhvk** [comment]
Thinking just a little more, I think my preference for defaults would be that `QTable` read returns dimensionless `Quantity` at least for any float columns; for integer, `Column` may be better, since often those types of columns contain flags. But this just goes to show it is not so obvious. It may be easiest to just provide a simple method to change the column type (like setting the unit).

**Comment by taldcroft** [comment]
I think that it's important to keep the behavior as simple and consistent as possible (since the whole concept is confusing to start with).  So I would state the rule for `QTable` as: *"If a numeric column has a defined unit then it is converted to a Quantity"*.  That applies to both creation and if the unit is assigned.  

This is not strictly back-compatible (different behavior when unit is *assigned*), but I would say that this is what most people would expect for a `QTable`.

Automatically making any *float* column into a dimensionless Quantity, but not *int*, just seems to muddy the water.  It would also not be back compatible.  Remembering that we still don't have masked Quantity, this could be a real issue if someone needs a masked QTable.

**Comment by eteq** [comment]
I agree with @taldcroft's https://github.com/astropy/astropy/issues/4497#issuecomment-172119288 here.  That is, different behavior for float vs. int would be very unintuitive, and the underlying problem is that the current result, while not precisely "wrong", is counter-intuitive.  So  I think @taldcroft's heuristic sounds good.
So this requires an actual change, right?  I'm not clear if it's in the iterator for column or in `QTable` itself, though...

**Comment by taldcroft** [comment]
OK, here is a POC.  First an update to `Column.__setattr__`:
```
    def __setattr__(self, item, value):
        if not isinstance(self, MaskedColumn) and item == "mask":
            raise AttributeError("cannot set mask value to a column in non-masked Table")
        super(Column, self).__setattr__(item, value)

        if (item == 'unit' and
                issubclass(self.dtype.type, np.number) and
                hasattr(self, 'parent_table')):
            from .table import QTable
            if isinstance(self.parent_table, QTable):
                self.parent_table.replace_column(self.name, self)
```
And..
```
In [2]: t = QTable([[1]], names=['a'])

In [3]: type(t['a'])
Out[3]: astropy.table.column.Column

In [4]: t['a'].unit = u.m

In [5]: type(t['a'])
Out[5]: astropy.units.quantity.Quantity

In [6]: t
Out[6]: 
<QTable length=1>
   a   
   m   
float64
-------
    1.0
```

**Comment by taldcroft** [comment]
It might be cleaner to make `unit` be a property, but that is an implementation detail and not strictly necessary.

**Comment by mhvk** [comment]
Looks good overall, though I wonder if one can test for whether the conversion is necessary using:
```
converted = self.parent_table._convert_col_for_table(self)
if converted is not self:
    self.parent_table.replace_column(self.name, converted)
```

**Comment by eteq** [comment]
Just tried it now and it appears that this will do the trick:
```
    def __setattr__(self, item, value):
        if not isinstance(self, MaskedColumn) and item == "mask":
            raise AttributeError("cannot set mask value to a column in non-masked Table")
        super(Column, self).__setattr__(item, value)

        if (item == 'unit' and
                issubclass(self.dtype.type, np.number) and
                getattr(self, 'parent_table', None) is not None):
            converted = self.parent_table._convert_col_for_table(self)
            if converted is not self:
                self.parent_table.replace_column(self.name, converted)
```
I can make a PR to do that + a test if desired, although perhaps @taldcroft or @mhvk wanted to do it if either think more should be added?

**Comment by taldcroft** [comment]
@eteq @mhvk - your approaches look fine.  One question is whether the promotion of Column to Quantity should generate a user warning for informational purposes.  There is some precedent there.

@eteq - if you can do this it would be great!

**Comment by mhvk** [comment]
Not sure about the warning, but I think we do need to be sure to document this behaviour for `QTable`. After all, users might well get confused if they can set the unit once, but not twice!

Aside: I'd probably rewrite slightly using `try/except`, just in case a column gets attached to a table subclass that for some reason does not have `_convert_col_for_table`:
```
        if (item == 'unit' and
                issubclass(self.dtype.type, np.number)):
            try:
                converted = self.parent_table._convert_col_for_table(self)
            except AttributeError:  # Either no parent table or parent table is None
                pass
            else:
                if converted is not self:
                    self.parent_table.replace_column(self.name, converted)
```

**Comment by eteq** [comment]
OK, will issue a PR on this soon and we can have remaining detailed discussion there.
