### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by AMAN3003** [astropy/astropy#4575]
any python file in pycharm results in this error when tried to run as individual file.is any fix available to run the scripts in pycharm to happen relative import in pycharm for future refrence and debug in pycharm.

**Comment by AMAN3003** [comment]
![screenshot from 2016-02-07 04 16 05](https://cloud.githubusercontent.com/assets/16108341/12869880/02fd3762-cd52-11e5-8c76-e27c4e05991c.png)

**Comment by pllim** [comment]
I would say that this is not something that is currently supported. Can you please try to run the tests in one of the ways listed here -- http://docs.astropy.org/en/latest/development/testguide.html ?

**Comment by AMAN3003** [comment]
@plim of course i would like to work on it

**Comment by AMAN3003** [comment]
@plim do you want me to write test for the failure of relative import?

**Comment by pllim** [comment]
I never use pycharm, so I don't have motivation to have Astropy support this. This decision depends on its core maintainers.

**Comment by eteq** [comment]
This is definitely not supported behavior.  Relative imports by design require that the whole structure of the package will be visible.  So this is not something that's special to astropy.

It's possible that pycharm can implement some sort of machinery to go look for the root of the package.  But this is really up to the pycharm devs.

**Comment by AMAN3003** [comment]
@eteq you are right sir.but could you tell which IDE are you and other astropy developers are using.
