### ISSUE TITLE
How to transform from Jy/beam to  Jy

### ISSUE THREAD

**Issue by jzamponi** [astropy/astropy#4623]
Hello, I'd like to know how can I convert my measurements from Jy/beam to Jy, or Jy/beam·km/s to Jykm/s, in order to have the intrinsic values. How can I obtain that (beam) value?

**Comment by astrofrog** [comment]
Maybe @keflavich can help here?

In the mean time, I'm going to close this, since this is more a question about usage, which doesn't belong in this issue tracker. In future, please ask questions about using Astropy and other packages on the [astropy@scipy.org mailing list](https://mail.scipy.org/mailman/listinfo/astropy) or other support venues such as the [Python users in Astronomy Facebook group](https://www.facebook.com/groups/astropython/).

**Comment by keflavich** [comment]
The "beam" unit is not handled within astropy, but it is dealt with in the radio-beam package: https://github.com/radio-astro-tools/radio_beam.  Unfortunately, we're missing docs right now.
