### ISSUE TITLE
Missing "import matplotlib.pyplot as plt" in .rst files

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4635]
Mostly accidental I tried copying the example from http://docs.astropy.org/en/stable/modeling/#simple-2-d-model-fitting into my notebook and it wasn't directly executable because ``import matplotlib.pyplot as plt`` was missing in the code-block. Since the astropy imports are all there would it be senseable to include the matplotlib import there too?

I couldn't test the doctests and didn't want to create a PR without tests and without asking if this might fail because astropy does have ``matplotlib`` only as additional dependency.

**Comment by eteq** [comment]
This seems very reasonable, @MSeifert04, especially given the `numpy` imports are also in those blocks.

One thing you can do to get around the doctests problems is use the ``  # doctest: +SKIP`` command to skip running the doctests on a particular line.  I think those pages might be *completely* skipped due to the matplotlib, though?  Feel free to just issue a PR and let travis tell you if it works, though.
