### ISSUE TITLE
Error when importing astropy.io in iPython 4.0.1

### ISSUE THREAD

**Issue by CANMoose** [astropy/astropy#4640]
I receive the following error when importing astropy.io in ipython 4.0.1,

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)

I'll try and see which file is causing this import error. Its not a serious error as far as I can tell. 

I suppose its coming from the astropy/io/\__init\__.py which imports "py3compat" and "config"

**Comment by mwcraig** [comment]
@CANMoose -- thanks for reporting! I think this was fixed in #4279 or #4078, both of which should have been included in recent releases of astropy.

Could you please check which version of astropy you are using? This should do the trick:  `import astropy; print(astropy.__version__)`

**Comment by CANMoose** [comment]
Yes, it looks like i'm behind. Sorry, I should have checked that before reporting!

**Comment by mwcraig** [comment]
@CANMoose -- not a problem, it took two PRs to fix this warning because it came up in a couple different ways.

The anaconda python distribution keeps a binary build pretty up to date (but would require you to start using anaconda), or you could build it from source: `pip install --upgrade --no-deps astropy` (would upgrade you to the latest, which is 1.1)
