### ISSUE TITLE
Incorrect WCS conversion with SIP distortions (error ~1 arcmin!)

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4761]
I am trying to convert world to pixel coordinates using the following header:

https://gist.githubusercontent.com/astrofrog/57bcb965eab79f99d953d2c1b162af02/raw/29ecd814239f11237ebe3bb5668582977976e9d1/header.hdr

Here's an example of converting (19500,6500) in pixel coordinates to (ra,dec):

```
In [1]: from astropy.io import fits

In [2]: from astropy.wcs import WCS

In [3]: header = fits.Header.fromtextfile('header.hdr')

In [4]: wcs = WCS(header)

In [5]: wcs.all_pix2world(19500, 6500, 1)
Out[5]: [array(215.17565987230577), array(52.917709465941066)]
```

I'm using origin=1 to be able to compare to ds9 results. If I now open ds9, and convert this same position, I get:

ra=215.0174
dec=52.948131

which is almost an arcminute.

If I then try and convert the world coordinates back to pixel coordinates, I get an error, even though the world coordinates are inside the image:

```
In [8]: wcs.all_world2pix(215.17565987230577, 52.917709465941066, 1)
---------------------------------------------------------------------------
NoConvergence                             Traceback (most recent call last)
<ipython-input-8-e392834de60b> in <module>()
----> 1 wcs.all_world2pix(215.17565987230577, 52.917709465941066, 1)

/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/astropy/wcs/wcs.py in all_world2pix(self, *args, **kwargs)
   1806                 adaptive=adaptive, detect_divergence=detect_div,
   1807                 quiet=quiet),
-> 1808             'input', *args, **kwargs
   1809         )
   1810 

/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/astropy/wcs/wcs.py in _array_converter(self, func, sky, *args, **kwargs)
   1242                     "a 1-D array for each axis, followed by an origin.")
   1243 
-> 1244             return _return_list_of_arrays(axes, origin)
   1245 
   1246         raise TypeError(

/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/astropy/wcs/wcs.py in _return_list_of_arrays(axes, origin)
   1198             if ra_dec_order and sky == 'input':
   1199                 xy = self._denormalize_sky(xy)
-> 1200             output = func(xy, origin)
   1201             if ra_dec_order and sky == 'output':
   1202                 output = self._normalize_sky(output)

/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/astropy/wcs/wcs.py in <lambda>(*args, **kwargs)
   1805                 *args, tolerance=tolerance, maxiter=maxiter,
   1806                 adaptive=adaptive, detect_divergence=detect_div,
-> 1807                 quiet=quiet),
   1808             'input', *args, **kwargs
   1809         )

/Users/tom/miniconda3/envs/dev35/lib/python3.5/site-packages/astropy/wcs/wcs.py in _all_world2pix(self, world, origin, tolerance, maxiter, adaptive, detect_divergence, quiet)
   1786                     .format(k), best_solution=pix,
   1787                     accuracy=np.abs(dpix), niter=k,
-> 1788                     slow_conv=ind, divergent=inddiv)
   1789 
   1790         return pix

NoConvergence: 'WCS.all_world2pix' failed to converge to the requested accuracy.
After 2 iterations, the solution is diverging at least for one input point.
```

@mcara @nden - do you have any idea what could be going on here?

**Comment by astrofrog** [comment]
Might it be that the SIP corrections are getting applied twice, once in astropy and once in WCSLIB? I wonder if it's related to https://github.com/astropy/astropy/pull/3845 - maybe we accidentally are using both calculations for SIP?

I'm going to cc @mdboom in case he also has any free time to chime in on this.

**Comment by mcara** [comment]
@astrofrog I doubt that corrections are being applied twice but I cannot exclude this. Hopefully @nden can verify this.

I also wanted to ask you how did you get your DS9's RA&DEC ? I am not sure that DS9 takes into account SIP corrections. To check this, in your first example, do this:
```python
wcs.wcs_pix2world(19500, 6500, 1)
```

Does the result from `wcs_pix2world()` agree with DS9 values?

**Comment by mcara** [comment]
My strong feeling is that this is the same problem as in #3203 [by the way, I believe you could close that issue after two years].

To verify this, I would suggest that you try to do the coordinate conversion closer to CRPIX.

**Comment by astrofrog** [comment]
@mcara - in this case, shouldn't the distortions be correct at least over the image extent? (in #3203 we were looking at positions outside the image?). Also, why would the pixel to world conversion differ from ds9?

**Comment by astrofrog** [comment]
Sorry just saw your previous comment, will check if ds9 is taking into account the distortions

**Comment by mcara** [comment]
I already checked:
```python
>>> from astropy.io import fits
>>> from astropy import wcs
>>> h = fits.Header.fromtextfile('header.hdr')
>>> w = wcs.WCS(h)
>>> w.wcs_pix2world(19500, 6500, 1)
[array(215.0174007627572), array(52.94813087820363)]
```
Pixel to world conversion differs from DS9 because DS9 does not take into account SIP distortions while `all_world2pix()` does (however, `wcs_world2pix()` does not).

**Comment by astrofrog** [comment]
Ok, thanks! Now the remaining question is why we can't convert from world to pixel coordinates inside the image.

**Comment by mcara** [comment]
Good question :) This will require more work. Let's start with the following question: how large is your image (naxis1, naxis2)? It would also be useful to have some information about the origin (provenience) of your SIP [but this could wait until I investigate the issue].

**Comment by astrofrog** [comment]
Ah yes I'm missing the size from the header above, here it is:

```
SIMPLE  =                    T  /  FITS STANDARD                                
BITPIX  =                  -32  /  FITS BITS/PIXEL                              
NAXIS   =                    2  /  NUMBER OF AXES                               
NAXIS1  =                40800  /                                               
NAXIS2  =                12600  /                                               
```

**Comment by astrofrog** [comment]
@mcara - here's some public data from CANDELS that has the same issue:

https://archive.stsci.edu/pub/hlsp/candels/egs/egsb02/v0.5/hlsp_candels_hst_wfc3_egsb02_f160w_v0.5_drz.fits

The following code shows that the world to pixel coordinates don't work:

```python
from astropy.wcs import WCS
wcs = WCS('hlsp_candels_hst_wfc3_egsb02_f160w_v0.5_drz.fits')
ra, dec = wcs.all_pix2world(19500, 6500, 1)
wcs.all_world2pix(ra, dec, 1)
```

because of a convergence issue.

**Comment by astrofrog** [comment]
(and just to be clear, 19500, 6500 is inside the image)

**Comment by mcara** [comment]
@astrofrog It may very well be inside the image but this does not mean anything. The fundamental issue is "is the method converging inside the image?" I do not know this yet. For example, in issue #3203 convergence is much larger than the actual SPITZER image. Let's imagine that we will make *that* image 2000x2000 large while keeping the same SIP coefficients as in the original 256x256 image. Just because the pixel (1999,1999) is "inside this larger image, it does not mean that the inversion will work. That is, the fundamental issue is how well behaved (for the current method used in `all_world2pix`) are SIP polynomials.

**Comment by astrofrog** [comment]
@mcara - since this may be algorithm dependent, I wonder if it might make sense to have a more robust/slower algorithm we could fall back to if the current method breaks?

**Comment by mcara** [comment]
@astrofrog Current method should be robust enough for vast majority of cases (I can't imagine a *realistic* SIP for which this method would fail). However, if you wish to add a more robust method, please do so. I think, if implemented, such a method should be called *only* on the points for which existing method diverges.

**Comment by astrofrog** [comment]
@mcara - ah, but the case I pointed out is a real-life case :)

https://archive.stsci.edu/pub/hlsp/candels/egs/egsb02/v0.5/hlsp_candels_hst_wfc3_egsb02_f160w_v0.5_drz.fits

Could it be that there is bug for a specific corner case in the existing algorithm? I tried looking at the map of RA/Dec produced by Astropy, and it looks quite smooth, so it's not clear to me why it would fail. Would it be possible for you to check why exactly the method is failing here?

**Comment by mcara** [comment]
No, current case is not a real case. Please give me a 1/2 hour to post all my findings.

**Comment by astrofrog** [comment]
@mcara - ok, thanks for looking into it! :)

**Comment by mcara** [comment]
So, I looked at SIP from your header and analyzed the convergence of the current inversion method for your header.

Below I show plots of the *displacement* of the pixel position from its "undistorted" value. You can immediately see that the distortions in your image are **huge**: for low values of X (regardless of Y) the pixel position displacements get as large as 400000 pixels (10x as the longest side of your image).

![x-displacement](https://cloud.githubusercontent.com/assets/5985250/14332007/b33549c0-fc15-11e5-84e0-4080376be588.png)

![y-displacement](https://cloud.githubusercontent.com/assets/5985250/14332009/b665e672-fc15-11e5-9eee-ff9781136a57.png)

**Comment by mcara** [comment]
A convergence map (similar to the one I did in issue #3203), shows that the inversion method would have converged in a region (see magenta contour) as large as 16000x12000 pixels which would be 6x-8x larger than an WFC3/IR image.

![all_world2pix_convergence](https://cloud.githubusercontent.com/assets/5985250/14332235/83349856-fc16-11e5-9d09-a65ae20d537f.png)

**Comment by mcara** [comment]
If the above distortions were even marginally realistic, I would suggest that you try a different method of coordinate inversion. However, I doubt that the original method in `all_world2pix` that my algorithm has replaced or even the method used in the WCSLIB (I've heard there is one in the latest version) would be able to invert your coordinates for these SIP that you have.

**Comment by astrofrog** [comment]
Thanks for all the insight! This is interesting - so I wonder if somehow the SIP coefficients were just taken from one of the images during the mosaicking process. I should get in touch with the CANDELS team to report this as a possible issue.

**Comment by mcara** [comment]
Now, when I asked you how was your SIP computed I really meant **"how; by which process/algorithm"**. By looking at the image ``hlsp_candels_hst_wfc3_egsb02_f160w_v0.5_drz.fits`` that you have mentioned above, I realized that the ``_drz`` suffix in its file name indicates that the image was drizzled which is also indicated in the header:
```
D001VER = 'WDRIZZLE Version 3.4.2 (Jul 3rd 2006)' / Drizzle, task version
```
Also, it was obvious that such a large image could not have come *directly* from any of the HST instruments. Thus, it had to be a mosaic.

A drizzled image is not supposed to have distortions. ``CTYPE?`` keyword in your header as well in that image ``hlsp_candels_hst_wfc3_egsb02_f160w_v0.5_drz.fits`` indicate that WCS is not distorted:
```
CTYPE1  = 'RA---TAN'
CTYPE2  = 'DEC--TAN'
```
(notice ``CTYPE`` is missing ``-SIP`` suffix).

For whatever reason (I guess a bug) these SIP coefficients have been left over in the drizzled image's header.

So, my advice to you is to manually delete all SIP coefficients from your image headers before working on them.

**Comment by mcara** [comment]
Well, if data were processed 10 years ago, I doubt they will reprocess them with the latest version of drizzlepac.

**Comment by mcara** [comment]
You may also find a good discussion on the related issue of ``astropy.wcs`` ignoring the absence of ``-SIP`` suffix in the ``CTYPE`` and reading SIP coefficients anyway [which I strongly believe is wrong] here: #4387

**Comment by mcara** [comment]
@astrofrog please remove "Bug" label from this issue and close it if you think the issue was solved/clarified. Also #3203 should be closed too.

**Comment by astrofrog** [comment]
@mcara - thanks for the detailed investigation! I've reported this to the people who made the FITS file.

**Comment by pllim** [comment]
Weird. This is the second time this week someone gets in trouble with messed up WCS in a CANDELS image. The other one was `goodsn_all_acs_wfc_f606w_060mas_v2.0_drz.fits`.

**Comment by hcferguson** [comment]
hi Harry

thanks for letting me know, I'll look into what the options might be, in terms of revising the image headers or providing a quick script. It might be worth noting that these were produced during an earlier incarnation of astrodrizzle, while I think the current version removes the problematic SIP keywords when making a final drizzled image.

It might be worth inserting into the astropy community discussions the idea of whether someone could look at the astropy code, to see whether it can be made to recognize images that have already been distortion-corrected and if so then ignore any residual SIP keywords (which is what much of the rest of non-astropy does when dealing successfully with such files, eg ds9, idl etc), though this would be complementary to actually modifying the file headers.

thanks again,
- Anton.

**Comment by mcara** [comment]
@hcferguson There are two ways of detecting presence of SIP distortions:
1. Detect ``-SIP`` suffix in the ``CTYPE``;
2. Look for presence SIP coefficients in the header.
I think first approach is the best one. Unfortunately historically suffix in ``CTYPE`` is ignored - see https://github.com/astropy/astropy/issues/4387 and so second option is the **only** option. Therefore Anton should fix image headers.

**Comment by mcara** [comment]
@hcferguson Let me also comment on another part of the message reported by you:
> _"...someone could look at the astropy code, to see whether it can be made to recognize images that have already been distortion-corrected and if so then ignore any residual SIP keywords (which is what much of the rest of non-astropy does when dealing successfully with such files, eg ds9, idl etc)..."_

I wish I knew the idea of astropy being able to "recognize images that have been already corrected"? How would you do it when the parameters that we look for in order to recognize this are incorrectly left over in the header. This is a bug in their software and needs to be fixed. There are no miracles here.

In addition, _"which is what much of the rest of non-astropy does..."_ is kind of incorrect, for the very least with regard to DS9: DS9 simple ignores SIP regardless of the presence of suffix ``-SIP`` in ``CTYPE`` or presence of SIP coefficients. I guess, if astropy would do the same people would not like it either [but this indeed can be done].

**Comment by hcferguson** [comment]
Thanks for the info & history. All good points, @mcara.

**Comment by nden** [comment]
I feel like I need to set the record straight here.

The `-SIP` suffix should be present in `CTYPE` if there's `SIP` distortion. It was never ignored by `astropy.wcs`. #4387 was a bug introduced in `astropy.wcs` at the time `wcslib` started working with `SIP`. This was fixed and `-SIP` is now part of `CTYPE` _again_ when `SIP` coefficients are present.

`astrodrizzle` manipulates the `WCS` heavily and should take sufficient care to produce correct headers. The presence of `SIP` coefficients at some point in the past in drizzled images was a bug in `astrodrizzle` which is not related to `astropy.wcs`. 

I am told modern versions of DS9 now use `AST`, not `wcslib` and understand `SIP`. I have not tested this but it would be nice to know this for sure.

**Comment by antonkoekemoer** [comment]
Hi, looks like I need to join the discussion since this concerns CANDELS mosaics. Thanks to Harry for forwarding some of it to me.

So to respond to @mcara -- when I wrote about "recognize images that have been already corrected", I am referring exactly to the CTYPE convention. Specifically, in these CANDELS mosaics, which were distortion-corrected using drizzle, the CTYPE keywords are already set correctly, for mosaics that are distortion-corrected and rectified, according to the FITS standard, as:
CTYPE1 = 'RA---TAN'
CTYPE2 = 'DEC--TAN'
They do not have "-SIP" appended (ie RA---TAN-SIP' or 'DEC--TAN-SIP').

Therefore, when reading the fits header, if astropy finds that the CTYPE keywords are set to this, with no "-SIP" appended, then it should not go looking for SIP keywords but should instead treat this image as being already rectified. I hope this clarifies what I meant by what the astropy software should be doing.

thanks
- Anton.

**Comment by mcara** [comment]
@nden You are right that issue #4387 was in principle reporting a bug due to which astropy was not postpending suffix ``-SIP``. However, the astropy code was working just fine even though images did not have ``-SIP`` suffix in ``CTYPE``. And *that* is very important and pertinent to this current issue.

Specifically, I have raised the issue of suffix ``-SIP`` in ``CTYPE`` not being a **"trigger"** (search for "trigger" in #4387):
https://github.com/astropy/astropy/issues/4387#issuecomment-163675135
https://github.com/astropy/astropy/issues/4387#issuecomment-163675957
to which @nden [replied](https://github.com/astropy/astropy/issues/4387#issuecomment-163678412):
> _"I think this is probably better discussed in a different ticket. The problem here is that astropy.wcs now produces different headers and we need to find why."_

So, I do understand that the main issue of #4387 was about a bug in `astropy.wcs` of not prepending suffix ``-SIP`` to ``CTYPE``, but the issue of the presence of this suffix in ``CTYPE`` and its use as a "trigger" for applying SIP was discussed as well and that is why I was referring to ticket #4387 in my previous comments.

**Comment by mcara** [comment]
@antonkoekemoer See [my comment] (https://github.com/astropy/astropy/issues/4387#issuecomment-163675135) (citation from @stargaser): _**"...Regrettably, this fine idea was later discarded..."**_ So, unfortunately, using presence of ``-SIP`` in ``CTYPE`` is not supported.

**Comment by antonkoekemoer** [comment]
@mcara In the same thread #4387  there is a comment:
https://github.com/astropy/astropy/issues/4387#issuecomment-163679347
implying support of the extended SIP specification on these fits keywords, in astropy, as follows:

> @mcara ...
> But because we do use this SIP specification we will generally allow this one special case
>  exception to the FITS Standard (if we want to be pedantic we could say that FITS+WCS+SIP
>  is a new format that is a superset of proper FITS). It's all unfortunate, because we started using
>  SIP, IIUC, before the paper was adopted into the FITS Standard, and under the assumption
>  that it eventually would be.
> 
> It's not the only otherwise defunct feature from that paper that we've adopted. For example
>  PyFITS (and by extension astropy.io.fits) uses the "record valued" header card format, that
>  is otherwise not specified anywhere. But we support this.

So the above comment from that thread appears to imply that astropy can/should/would interpret the distinction between CTYPE1="RA---TAN" (which again is set correctly in our distortion-corrected CANDELS mosaics) and CTYPE1="RA---TAN-SIP" (expected for images that are still distorted and need to have SIP applied), and then astropy should ignore the SIP coefficients once it has read the keyword correctly and made the distinction between these two cases.

**Comment by mcara** [comment]
@antonkoekemoer 
> _"...So the above comment from that thread appears to imply that astropy can/should/would interpret the distinction between CTYPE1="RA---TAN" ... and CTYPE1="RA---TAN-SIP"..."_
No, @embray was referring there only to the fact that longer ``CTYPE`` are supported and thus the presence of ``-SIP`` in ``CTYPE`` is supported and so, according to that discussion, presence of distortions in a WCS should result in presence of ``-SIP`` in ``CTYPE``. However, @embray statement does not imply that lack of ``-SIP`` in ``CTYPE`` can be interpreted as lack of distortions in a WCS (that is, @embray does not imply that ``-SIP`` is a "trigger").

It was my strong desire that presence of ``-SIP`` in ``CTYPE`` were used as a trigger to perform SIP corrections. Unfortunately, my understanding from the discussion in #4387 (and also "private communications") is that this was never implemented in this way and, unfortunately, I assume it is now too late to change this behavior simply because it will have dramatic effects on existing code.

**Comment by mcara** [comment]
In https://github.com/astropy/astropy/issues/4387#issuecomment-163678412 @nden suggested to open a new issue to discuss this subject. Therefore @astrofrog , maybe this issue should be re-opened or maybe a new issue should be created to discuss specifically the use of ``-SIP`` as a "trigger" for applying SIP distortions in a WCS.

**Comment by mcara** [comment]
@antonkoekemoer Regardless of the outcome of this investigation (which I strongly suspect will not change the way things are in astropy.wcs) I would encourage you or @astrofrog to create a simple tool available to your users that goes through all ``SCI`` headers of an image and check that if ``CTYPE`` does not contain ``-SIP`` suffix then it deletes all SIP coefficients if they are present in the ``SCI`` header.

**Comment by antonkoekemoer** [comment]
@mcara wrote
> Regardless of the outcome of this investigation (which I strongly suspect will not change the way things are in astropy.wcs)

Could you tell us please who is currently responsible for deciding the behaviour of tasks like astropy.wcs? Since you confirmed the comment by @embray that longer CTYPE values (like "RA---TAN-SIP") are in fact supported in astropy, then that suggests that when astropy reads in a valid, conformant, FITS value like "RA---TAN", without "-SIP" appended, then it should not look for SIP keywords and attempt to apply them.

Or, putting the above another way, astropy should *only* look for SIP coefficients if it reads in a CTYPE that has "-SIP" appended, which appears to have been the original intent of introducing the "-SIP" suffix.

**Comment by mcara** [comment]
@nden might provide more information.

**Comment by nden** [comment]
Decisions in `astropy`, about relatively small changes, follow roughly this route:

- The person who wants to introduce a change submits a new issue to github describing what the proposed change is and the reasons for it.
- There's a discussion by interested parties, including what the impact on the community would be.
- Then one of two things happens
  - Opinions converge and there's a decision (it may include compromises).
  - There're strong opinions and no agreement for a long time. Then the coordinattion committee decides what's best to be done.

We strive to get an agreement. I hope this helps.

**Comment by mcara** [comment]
In the "SIP - Simple Imaging Polynomial" section of this document http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/dis_8h.html

There it says: _"SIP's A_ORDER and B_ORDER keywords are not used. WCSLIB would recognise a FITS header containing the above keywords..."_ Thus, it appears that WCSLIB will look to the presence of SIP coefficients (``CTYPE`` is not included in the _"above keywords"_ listed there).

Even though personally I think it would have been sensible for WCS to ignore these coefficients when ``CTYPE`` does not include ``-SIP``, unfortunately if too many people rely on existing behavior, then maybe we should leave the things the way they are.

**Comment by antonkoekemoer** [comment]
@nden  and @mcara thanks for those replies, which are quite helpful.

In terms of what to propose then, going forward, there seem to be at least a couple of options:

1) at a minimum, could astropy.wcs issue a warning in cases like this, where CTYPE is properly FITS-compliant (eg "RA---TAN") and does not have "-SIP" appended, but there are SIP keywords in the header- - this warning would inform the user that the image may already be distortion-corrected, but that the SIP coefficients are still being used to calculate coordinates, and that this may result in potentially incorrect coordinates.

2) Providing an optional parameter, when running astropy.wcs, to force SIP not to be used (ie treat the image as already distortion-corrected) even if there are SIP coefficients in the header. This optional parameter would not be active by default (ie, default behaviour would remain unchanged), but if it's invoked by the user then this would at least enable accurate coordinates to be obtained in cases like this.

Note that neither of the above options would change the current default behaviour, but would at least alert users to this issue and provide them with a way to mitigate it.

There could also be a 3rd option as discussed earlier in this thread, which may have wider impact, ie:

3) modify the default behaviour to only apply SIP coefficients if the CTYPEn keywords contain "-SIP". I would agree that any change to the default behaviour should not be considered lightly, so my preferred route for right now may be actually options (1) and (2) above; however it may help to not take this third option off the table completely, but keep it for future discussion.

So, in order to move forward.. would it be possible for someone (@mcara perhaps?) to initiate a pull request and have a look at getting the code to issue a warning message in this type of case, and perhaps also look at providing a parameter to work around the issue as in option (2) above? Ie, this would retain the current default behaviour, but would at least alert users to the issue and also provide a workaround.

If agreeable, then at this point you could probably also close this thread and open it as a completely new issue to github, as @nden  was suggesting.

**Comment by mcara** [comment]
This present ticket was started by @astrofrog as a possible case of `wcs.all_world2pix()` not working correctly. Now half of this ticket has become a discussion on an unrelated issue.

I think the changes that you are proposing deserve a more wide discussion by the community and therefore following @nden https://github.com/astropy/astropy/issues/4761#issuecomment-213520111 and therefore a new **issue** should be open to discuss specifically the problem of using the presence of the ``-SIP`` in ``CTYPE``as a trigger to applying SIP corrections.

@antonkoekemoer @hcferguson Please open a new astropy issue to discuss the problem of using the presence of the ``-SIP`` in ``CTYPE``as a trigger to applying SIP corrections.

**Comment by nden** [comment]
@antonkoekemoer 
Adding a `Warning` sounds good to me and pretty uncontroversial.
Regarding 2) - there's an argument to the WCS class, `minerr` which does something similar. `minerr` is a float representing the minimal value a distortion component must have in order to be applied. For example, `wcs.WCS(header, minerr=5)` will ensure no distortion is applied. However, `wcs.WCS(header, minerr=.05)` will apply only `SIP` but not `NPOL` (in the HST case). So it provides more control over what distortions to apply. Would that be useful instead of adding one more parameter? (As a side note, I just discovered it's broken in master but it will be fixed.)

@mcara Do you have time to work on these two? If not I'll try to get them in `1.2`.

**Comment by mcara** [comment]
I doubt I will have time to work on this until second week of May, the earliest. The point of having a separate *open* issue is to have this widely discussed. For example, I have some issues with all of the points proposed by @antonkoekemoer . Specifically, point 3 in https://github.com/astropy/astropy/issues/4761#issuecomment-213551802 is a no go for me as it will make astropy.wcs diverge from WCSLIB as well as from the historical way SIP was handled (even though I disagree with the way things have been handled in the past regarding SIP). Moreover, we have other distortions such as NPOL, CPDIS are turned on simply by their presence: there is no suffix that can be prepended to ``CTYPE`` to turn on/off NPOL & CPDIS. Why treat SIP differently when WCS standard as well as SIP paper do not require/do this.

However, even points 1 & 2 are not without consequences and it is important to discuss this more thoroughly. For example, if you are going to perform the check that SIP coefficients are present in the header but ``CTYPE`` does not have ``-SIP`` suffix at WCS initialization - that's one thing. However, will you also check this every time `all_world2pix` (or wcs.sip) is run? Do we sacrifice performance? Is it worth it? Checking at every stage is required as, for example, I could create a WCS object from a valid file, and then I might add SIP to that object *withought* adding ``-SIP`` to ``ctype``, that is, I could add SIP *after* initialization of the WCS object. This is perfectly fine now (and was in the past). Do we warn users now that they do something wrong? Is it even wrong? I do not think it is wrong... Then why warn users about something that is not wrong? Do we modify software/standards because a project was producing drizzled (=distortion-free) images with SIP copied from input images? At the very least these issues deserve a discussion.

**Comment by mcara** [comment]
By the way, if all that @antonkoekemoer and @astrofrog need is to turn off SIP (and they know they want it OFF), then there is no need for an extra parameter: all they need is to set ``sip`` property of the ``WCS`` object to ``None``. For example, using @astrofrog example in his first comment:

```python
>>> from astropy.io import fits
>>> from astropy.wcs import WCS
>>> header = fits.Header.fromtextfile('header.hdr')
>>> w = WCS(header)
>>>
>>> # Verify that sip is not None:
>>> w.sip
<astropy.wcs.Sip object at 0x103c12ce0>
>>>
>>> # Compute RA, DEC using SIP:
>>> w.all_pix2world(19500, 6500, 1)
[array(215.17565987230577), array(52.917709465941066)]
>>>
>>> # For reference, see what is the RA,DEC without SIP:
>>> w.wcs_pix2world(19500, 6500, 1)
[array(215.0174007627572), array(52.94813087820363)]
>>>
>>> # Now turn off SIP as I suggested above. It is as simple as:
>>> w.sip = None
>>>
>>> # Now verify that SIP is OFF (all_pix2world() produces same results as wcs_pix2world()):
>>> wcs.all_pix2world(19500, 6500, 1)
[array(215.0174007627572), array(52.94813087820363)]
```

**Comment by pllim** [comment]
:+1: to open a new issue to move the conversation under a more relevant subject.

This issue (as far as the original one is concerned) is already CLOSED.

**Comment by nden** [comment]
Filed an issue #4803

**Comment by pllim** [comment]
Thank you, @nden !
