### ISSUE TITLE
WCS when `-SIP` is missing from `CTYPE` but SIP coefficients are present

### ISSUE THREAD

**Issue by nden** [astropy/astropy#4803]
On several occasions (the latest at #4761) there was some confusion about WCS results caused by the fact that SIP informaiton in the headers was incomplete or incorrect. `astropy.wcs` looks at `A_ORDER` and `B_ORDER` keywords to determine if there is SIP distortion in the headers. It does not look for `-SIP` suffix in `CTYPE` because for a long time `wcslib` did not allow `CTYPE` to be longer than 8 characters.

@antonkoekemoer made 3 suggestions in #4761 to deal with cases when `-SIP` is not present in `CTYPE`. I'm opening this issue to discuss these and use it as a reference in the future.

1. At a minimum, could astropy.wcs issue a warning in cases like this, where CTYPE is properly FITS-compliant (eg "RA---TAN") and does not have "-SIP" appended, but there are SIP keywords in the header- - this warning would inform the user that the image may already be distortion-corrected, but that the SIP coefficients are still being used to calculate coordinates, and that this may result in potentially incorrect coordinates.

2. Providing an optional parameter, when running astropy.wcs, to force SIP not to be used (ie treat the image as already distortion-corrected) even if there are SIP coefficients in the header. This optional parameter would not be active by default (ie, default behaviour would remain unchanged), but if it's invoked by the user then this would at least enable accurate coordinates to be obtained in cases like this.

Note that neither of the above options would change the current default behaviour, but would at least alert users to this issue and provide them with a way to mitigate it.

3. Modify the default behaviour to only apply SIP coefficients if the CTYPEn keywords contain "-SIP". I would agree that any change to the default behaviour should not be considered lightly, so my preferred route for right now may be actually options (1) and (2) above; however it may help to not take this third option off the table completely, but keep it for future discussion.

**Comment by mcara** [comment]
Below I will be summarizing some of the things that I have mentioned in #4761.

**[Regarding Issuing Warnings]** In the "SIP - Simple Imaging Polynomial" section of this document http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/dis_8h.html it says: _"SIP's A_ORDER and B_ORDER keywords are not used. WCSLIB would recognise a FITS header containing the above keywords..."_ Thus, it appears that WCSLIB will look to the presence of SIP coefficients (``CTYPE`` is not included in the _"above keywords"_ listed there). Therefore, it is perfectly fine both under the WCS standard as well as SIP standard (see https://github.com/astropy/astropy/issues/4387#issuecomment-163675135) for a FITS file header to contain SIP coefficients **and not have** ``-SIP`` suffix in the ``CTYPE``. While STScI always postpends this ``-SIP`` suffix to ``CTYPE`` when images have SIP, STScI's approach does not contradict WCS standard. **Therefore, I do not think it would be appropriate to issue warnings to users whose images do not deviate from standard.**

**[Parameter for turning OFF SIP]** As mentioned in https://github.com/astropy/astropy/issues/4761#issuecomment-213736769, turning off SIP in WCS is as simmple as setting ``sip`` parameter of the WCS object to ``None``. However, if one really really wants a separate parameter for this - I guess it's OK, especially if by default SIP is not ignored.

**Comment by antonkoekemoer** [comment]
@nden thanks very much for opening this as a new issue; greatly appreciated.

Regarding the additional points by @mcara -- of the 3 options I suggested (1: a simple warning; 2: an added parameter; 3: a change in default behaviour), I would advocate that at a minimum it should be considered to add a warning to the code (ie option 1); I am happy to hear that it might be possible to turn off sip when running the code in a way that does not require an extra parameter (option 2).

Adding a warning is really motivated by the fact that we have now identified cases where this code gives incorrect results. If the code runs in such cases and produces output, without generating even as much as a warning, then users may not be aware of a potential error in their results. Users might then wonder why the code does not generate a warning in such cases but appears to complete successfully, even though we are now aware of the problem and have discussed it in this forum.

The warning that it generates can simply provide a statement that the computed coorindates may be incorrect in this case, along with information on how to rerun it by turning off the sip distortion if the image is already distortion-corrected (such as providing the actual instructions on how to set the sip parameter of the WCS object to none).

**Comment by mcara** [comment]
I disagree with @antonkoekemoer comment: _"Adding a warning is really motivated by the fact that we have now **identified cases where this code gives incorrect results**."_

The code produces perfectly correct results for all cases where WCS is correct. However, for images that **unintentionally** contain SIP distortions (when they should not have had SIP coefficients in them), the WCS *will* contain SIP. This does not mean that the code is incorrect. Rather it confirms [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out). Per references in my previous comment neither SIP nor WCS standards allow ``-SIP`` suffix in ``CTYPE`` and this suffix is "partially supported" by ``astropy`` in a limited sense that this suffix *may be present* **if** image has distortions (=has SIP coefficients). However, based on https://github.com/astropy/astropy/issues/4387 and other private communications, the use of ``-SIP`` suffix in ``CTYPE`` as a switch to turn on/off SIP corrections was never supported just as WCS standard states and SIP standard has accepted in the end.

Therefore, in the light of WCS standards, there is nothing wrong with providing SIP coefficients in an image header without postpending ``-SIP`` suffix to ``CTYPE``. Therefore, users who choose to provide SIP coefficients without postpending ``-SIP`` to ``CTYPE`` should not be warned of doing something wrong (as they follow the standards) because such a usage *is supported*.

**Comment by astrofrog** [comment]
What about using an INFO-level message?

**Comment by mcara** [comment]
@astrofrog I don't know... INFO seems pretty innocuous. But then again: why inform users that they do things right? I would be pretty annoyed if every time I run ``all_world2pix()`` it would keep informing me that my WCS has SIP (or that I chose ``origin`` to be ``1`` instead of ``0``).

The fundamental problem with your #4761 case is not that software is misbehaving or incorrectly interpreting user input, but rather the user input is the problem. I think that ``-SIP`` suffix is like an appendix and that we should move away from the use of ``-SIP`` in ``CTYPE``. I think SIP team decided to stick ``-SIP`` into ``CTYPE`` because ``CTYPE`` is the only string type keyword in the WCS definition (all others are numeric) even though SIP has nothing to do with projection type described by ``CTYPE``.

Without relying on ``CTYPE`` how can one detect *possibly incorrect* user inputs? For example, what if your CANDELS image had an extension for D2IM corrections? How would ``astropy.wcs`` know that D2IM is by mistake there? Or, do we create redundancy in WCS definition to detect user errors? It is not that it would not be possible to do this...

**Comment by mcara** [comment]
I also suspect that the problems with SIP in CANDELS drizzled images is an old problem that went undetected for a long time, indicating that users mostly did the analysis in image coordinates. One way of detecting this kind of problem could have been an approach by which the coordinate of a star in the drizzled image was compared to the coordinate of the same star in the reference catalog (or something like that) - that is the simple description - the real test is more complicated if automated.

**Comment by antonkoekemoer** [comment]
@mcara I'd support the idea from @astrofrog to have the code output an INFO statement, if not a Warning. Otherwise, with no change to the code, there is no way for the user to be aware of any potential problem, and the code announces that it has completed "successfully" even though the coordinates may be incorrect.

Also, as far as I'm aware, in practice, the only images that currently require SIP to be applied are those that actually have "-SIP" appended to the CTYPE keyword. Ie, our HST calibrated files (*_flt.fits) all have "-SIP" appended to this keyword value, and Spitzer images also have "-SIP" appended where necessary (eg, IRAC Instrument Handbook 5.1.20). Can you provide us with a case where CTYPE1 is currently just set to "RA---TAN" (not "RA---TAN-SIP"), and yet requires SIP to be applied in order to obtain correct WCS? Currently this seems to be a hypothetical case only (as the images that triggered this discussion have CTYPE1="RA---TAN" and are not supposed to have SIP applied).

The current FITS standard (v3.0 described in Pence et al. 2010) in section 8.2 says the following about the 8-character CTPYEn:
>
>  ...the remaining three characters specify an algorithm code for computing the world coordinate value.
>
Therefore, according to this definition, if those three characters are "TAN" then that is the algorithm to be used in computing the coordinate value -- ie, a pure TAN projectopn, without any additional distortion.

@mara wrote:
>  I also suspect that the problems with SIP in CANDELS drizzled images are old issues that
> went undetected for a long time, indicating that users mostly did the analysis in image coordinates. 
> 
In fact that is not the case: users have not been doing image analysis in pixel coordinates, but have been using RA and Dec, which are accurately computed from these mosaics according to the formal FITS convention (ie using a pure TAN projection). The CANDELS mosaics adhere to this FITS standard - ie, CTYPE1="RA---TAN", and the WCS is correct when you apply a pure TAN projection as defined in FITS v3.0. If that is done (ie without SIP), then the resulting coordinates are correct.

The current implementation in astropy deviates from the above v3.0 FITS description, in that two different algorithms are used, depending on whether SIP keywords are present in the header or not, even though the FITS standard specifies that just a single algorithm is to be used for a particular CTYPE (eg, pure TAN projection when CTYPE1="RA---TAN").

Hence the suggestion to at least inform the user of this fact, and to inform the user about how to run it in a way that adheres to the strict FITS convention (ie, turning off SIP in order to use a pure TAN projection), if that is necessary.

**Comment by nden** [comment]
Let's keep other projects related discussions off this issue.

1)  [SIP](http://fits.gsfc.nasa.gov/registry/sip.html) is a FITS registered convention since 2009. The FITS Standard page states:

```
CTYPE1   = 'RA---TAN-SIP' 
CTYPE2   = 'DEC--TAN-SIP'
```

Practically speaking there are files with and without `-SIP` in `CTYPE` out in the world. Is there a harm in using a `Warning`? `astropy.wcs` uses Warnings for things like incorrect/old spelling of keywords or units (since they are case sensitive). I think this type of problem fully deserves a `Warning` as well. I don't see this as what's (who's) wrong/right but what would be most useful to users. And certainly this had created problems and users have no information or clues of what's happening. 
:+1: to adding a warning stating that there's inconsistency in the header but using the `SIP` coefficients to create the WCS, i.e. no change in behaviour.

2) Distortion can be ignored at runtime now by using `wcs_pix2world` instead of `all_pix2world`. `minerr` can provide fine control over which distortions are read in (different from read the distortion but don't execute it at runtime). 

3) I think this has the potential of breaking applications so :-1: to this.

**Comment by mcara** [comment]
>  Can you provide us with a case where CTYPE1 is currently just set to "RA---TAN" (not "RA---TAN-SIP"), and yet requires SIP to be applied in order to obtain correct WCS?

No, I can't: I use HST images most of the time that are essentially identical to Spitzer (with regard to SIP). However, many other distortion types are turned on/off by their mere presence: [TPV](http://iraf.noao.edu/projects/ccdmosaic/tpv.html) (also see http://authors.library.caltech.edu/36801/1/84511M.pdf), NPOL distortions in HST images (D2IM, CPDIS). There wouldn't be enough characters even in the 12 characted ``CTYPE`` to individually turn on/off all these distortions.

> Therefore, according to this definition, if those three characters are "TAN" then that is the algorithm to be used in computing the coordinate value -- ie, a pure TAN projection, without any additional distortion.

I don't think this is really true: it is just the projection from "￼Intermediate World Coordinates" to "World Coordinates" (see Fig. 2 in FITS paper) that is performed without distortions. However, SIP intervenes in a different stage: "Pixel Coordinates" to "￼Intermediate Pixel Coordinates" (Fig. 2) in a non-standard way.

> The CANDELS mosaics adhere to this FITS standard - ie, CTYPE1="RA---TAN", and the WCS is correct when you apply a pure TAN projection as defined in FITS v3.0. If that is done (ie without SIP), then the resulting coordinates are correct.

I guess you are saying that users used `wcs_pix2world()` and `wcs_world2pix()` when working with CANDLES *drizzled* images. That is definitely a valid approach of turning off SIP distortions present in the drizzled images. And definitely users can continue using these to functions. And possibly #4761 was a case of user using incorrect function for coordinates conversion. Maybe all that is needed is clear instructions to users as to which functions need to be used when working with CANDELS drizzled images.

> The current implementation in astropy deviates from the above v3.0 FITS description, in that two different algorithms are used, depending on whether SIP keywords are present in the header or not, even though the FITS standard specifies that just a single algorithm is to be used for a particular CTYPE (eg, pure TAN projection when CTYPE1="RA---TAN").

This is not very clear to me... For example: _"...even though the FITS standard specifies that just a single algorithm is to be used for a particular CTYPE..."_ Fits standard will always specify a single projection type as `-SIP` suffix in `CTYPE` is not supported in the FITS standard. The whole SIP distortion is a hack of the standard... So far, astropy has followed WCSLIB and other types of distortions in that it looks for the presence of SIP coefficients to decide whether to load SIP into a WCS. Functions suchh as `all_world2pix()` *have to* ignore suffix in `CTYPE` (past 8th character) if they are to use distortions at all.

One can always use `wcs_pix2world()` and `wcs_world2pix()` to ignore any loaded distortions.

However, there are users who want to find correct coordinates in FLT images that do contain distortions. For those users, `astropy.wcs` provides distortions-functions such as `all_pix2world()` and `all_world2pix()`. It is up to the user to decide which function to use based on the understanding of what these functions do and what distortions their actual images and headers have.

So, I am not sure I understand correctly your comment above: should we have only one type of functions (such as `all_pix2world()`) that should turn off distortions based on `CTYPE`'s suffix?

===

In any case, if you feel that having an info message would enhance user experience - so be it.

**Comment by mcara** [comment]
Upon further investigation, it appears to me that [WCSTools](http://tdc-www.harvard.edu/wcstools/) is using ``-SIP`` as a switch for SIP (though I am not sure WCSTools supports TPV or tabular (NPOL) distortions).

Therefore, if there are **no** "legit" images out there that **do not have** ``-SIP`` in their ``CTYPE`` **but** do have SIP coefficients, then maybe we should consider making ``-SIP`` suffix a trigger for applying SIP corrections just as WCSTools does (even though, personally, at this time I am opposed to this because it is a departure from the FITS standard and from how all the other distortions are treated).

**Comment by eteq** [comment]
My perspective is this:

* We should not change the current default behavior without at least a few versions' warning.  Regardless of whether it's "wrong" or not, the underlying issue (as I understand it) is that the presence or absence of ``-SIP`` (or its expectation) has changed over the time that images "in the wild" used it.  A lot of people probably have used this code on such images already, and they don't expect it to change given that the original choice was somewhat arbitrary.
* It's a reasonable assumption by an un-informed user that "``-SIP`` means use SIP".  Images that violate this rule (either by having the coefficients without ``-SIP`` or vice versa) should at least be brought to the users attention, because it's a sign the user might be unintentionally doing something without realizing it.  Seeing a new warning/info message is much less dangerous than silently changing behavior.
* Users should be able to say "I know what I'm doing, don't bug me"

So I conclude from that that some combination of (1)+(2) is best. I.e., some message should raised, but with a way to explicitly say "use sip or not" that would silence things.  The default should only be changed down the road *if* there's a clear argument that one is definitively more right than the other (and my read of the above is that that's not true.)

I don't think it matters too much whether it's INFO vs WARNING - either way the point of the message is "Hi user.  Your assumptions might be wrong because the file you gave me is a bit ambiguous.  Don't panic, but FYI", which is kind of both.  

I understand @mcara's point that it seems weird to have two ways to deal with (2), though: if setting ``sip`` to None does the job then that should be the solution.  The question, though, is if there's a way to do that that would prevent the warning from *ever* occurring.  I think the answer is that the only way to do that is to have it be a new keyword to the ``WCS.__init__``, right?  It should be clear from the docstring that this is just doing ``self.sip = None`` and not showing the warning, though.

**Comment by eteq** [comment]
It also occurs to me that (2) might be unnecessary if the warning message says something like "oh, and if you want to silence this message in the future, do xxx.  And just use `wcs_world2pix ` instead of `all_world2pix` to do the transformations"

**Comment by mcara** [comment]
The more I dig into this problem the more I am inclined to believe that the omission of the check for the presence of ``-SIP`` in ``CTYPE`` was an omission on the part of the original developers - [PyWCS](https://aeon.stsci.edu/ssb/trac/astrolib/#pywcs) was ignoring SIP suffix since it was first implemented in PyWCS - see pywcs v1.1a3-4.3.

Therefore I am inclined to believe that @antonkoekemoer has a valid point that probably there are very few (if any) users who created images that (like CANDENLS drizzled images) do not have ``-SIP`` in ``CTYPE`` but have SIP coefficients in the header **but unlike CANDLES** *expect* WCS to perform SIP corrections.

Therefore, now I strongly believe that we should support [SIP](http://fits.gsfc.nasa.gov/registry/sip.html) convention of ``-SIP`` being a trigger/switch for applying SIP corrections. It does not make much sense to support incorrect use of SIP convention when there are no users that have created their files with coefficients but without ``-SIP`` suffix in ``CTYPE`` AND who expect WCS to apply corrections.

I understand this change may be inconvenient to some users (I doubt there will be any), but if they need a deprecation period - we could provide it. Moreover, we could introduce a new [relaxation constant](http://docs.astropy.org/en/stable/wcs/relax.html#relaxread) such as ``WCSHDR_NOSIP_CTYPE`` that when provided to the WCS constructor, will revert to the current behavior.

**Comment by mcara** [comment]
@eteq using ``wcs_pix2world()`` instead of ``all_pix2world()`` is not the same as setting ``w.sip=None`` and using ``all_pix2world()`` as in the second case ``all_pix2world()`` would still apply other NPOL (D2IM, CPDIS) distortions while ``wcs_pix2world()`` would *turn off all distortions*.

Also, I wonder, should we be warning users that their WCS has SIP distortions and recommend the use of ``all_pix2world()`` if they use ``wcs_pix2world()``? What if they do this by mistake? How is that different from @astrofrog use of ``all_pix2world`` instead of ``wcs_pix2world`` with images that do not have ``-SIP`` in ``CTYPE``...?

I think we ought to simplify the issues instead of introducing complex checks that will need to be repeated at every call of coordinate conversion functions and making astropy code compliant with SIP convention is probably the best way to go.

**Comment by perrygreenfield** [comment]
Those whom the gods wish to destroy they first make use FITS WCS. They're having a great laugh.

(Apologies for the editorial comment. Please return to the main program.)

**Comment by mcara** [comment]
So, was the decision made to not comply with SIP standard and have `astropy`'s own variety of SIP? I think we are rushing to implement a minor update without addressing the root problem of WCS code not respecting SIP paper.

**Comment by nden** [comment]
I have to disagree with this statement. We are respecting the SIP paper and the user by providing enough information when we detect inconsistent headers. Mind reading is hard. How do you know what is worng - the presence of SIP keywords or the absence of "-SIP" in CTYPE? The only thing we can do is point out the inconsistency.

What `astropy` does is consistent with `wcslib`. If `wcslib` was used directly to read headers without "-SIP" in CTYPE it will create the SIP distortion. I'm not saying it's right or wrong, simply pointing out the fact that it works in the same way. There are many occasions in the FITS world of incomplete headers. There are two ways of dealing with this - the purist way (reject these headers) or the practical way (find the balance where you can deal in a reasonable way with the header). Sofar `astropy.wcs` has taken the second approach, accepting the headers and issuing warnings. Why is this different?

**Comment by eteq** [comment]
To support @nden's point here: [PEP 20](https://www.python.org/dev/peps/pep-0020/) tells us that practicality beats purity, and that's *generally* the approach Astropy takes (and hence it's what users expect).   More specifically, the point here is that there is *not* an obvious right way, and this thread is more then sufficient to demonstrate that the "SIP standard" is anything but.

To be clear, while this is a *very* specific case, it's one where if we actually make the change, any users affected will be *seriously* affected: their code will silently start giving different answers.  That's the worst kind of change to make for scientists.  Given that the eventual goal is to phase out FITS WCS *anyway*, I see no compelling reason to deal with the deprecation and then inevitable complaints after the change is made.

**Comment by mcara** [comment]
I never though one would need a PEP to be reasonable

**Comment by mcara** [comment]
> _"...any users affected will be seriously affected: their code will silently start giving different answers."_ 

To this I could say that it is highly unlikely that there are any users who did *intentionally* created files without ``-SIP`` in ``CTYPE`` **and** had SIP coefficients in the header **and** these users were expecting WCS to apply SIP. I am pretty confident that users who added SIP coefficients also added ``-SIP`` to ``CTYPE``. On the contrary, it is quite likely that some users turn off SIP by removing ``-SIP`` from ``CTYPE`` and leaving SIP coefficients in the header (like CANDELS). These users right now are getting *wrong results* (just like @astrofrog in #4761) compared to what they expected to get unless they *knew* they had to use ``wcs_pix2world()`` instead of ``all_pix2world()``.

Therefore I can add to _"...their code will silently start giving different answers"_: right - their code will finally start giving the correct answer.

Also, it does not have to be "silent" - in case ``-SIP`` is missing from ``CTYPE`` but SIP coefficients are present - we can give a real warning and tell users to turn on relaxation constant to support SIP without ``-SIP`` just as described in https://github.com/astropy/astropy/issues/4803#issuecomment-214570886.

> _Given that the eventual goal is to phase out FITS WCS anyway..._

No comment on this.

**Comment by mcara** [comment]
Please feel free to do whatever you feel is the best for `Astropy` and its community.

**Comment by astrofrog** [comment]
In the **short term**, we need a warning/info message by default to just warn about the current behavior.

In the **long term**, we could of course consider changing the default behavior, through a deprecation process as mentioned by @eteq.

Those are two separate discussions in my view, and I think that for 1.2 it's important we at least include the warning. So maybe we can just focus on this part for now and discuss wording.

If the strictly correct WCS/SIP standard is that ``-SIP`` should be included in CTYPE, then maybe the warning should be:

``WARNING: the celestial CTYPE values do not end in -SIP, but SIP coefficients are present and will be used (this behavior may change in future, since such headers are ambiguous). To get rid of this warning, you can either add -SIP at the end of the celestial CTYPE values or remove the SIP coefficients from the header.``

The warning is long, but it's probably good to be as clear as possible (note that this even could constitute the start of a deprecation period if we decided to go ahead with that)

**Comment by astrofrog** [comment]
And if people feel we should be able to ignore the warning without editing the header, we could have an ``ignore_sip`` keyword in the ``WCS`` initializer too?

**Comment by mcara** [comment]
@astrofrog I like your wording for the warning message very much: I think it is very clear.

> So maybe we can just focus on the warning part for now and discuss wording.

I disagree with this: if we do not decide how to fix a simple omission in the implementation of SIP in astropy, based on the current mood of astropythonists, I doubt it will ever get done. Therefore I think that your warning message should be the beginning of the deprecation period.

While it would be possible to introduce a new parameter to ``WCS.__init__`` I would suggest that we use an already existing and very appropriate ``relax`` parameter and just define a new relaxation constant - see https://github.com/astropy/astropy/issues/4803#issuecomment-214570886 for more details/links. The same constant could be used now to turn off warnings and to enable old ``-SIP`` behavior once it is fixed.

**Comment by nden** [comment]
I agree with @astrofrog that it's good to have a warning out with `1.2`. This does not influence in any way what is decided about 2) and 3) above. The minimum useful action we can take is tell users header information is inconsistent. The worst that can happen is just keep talking and not doing anything for the next `n` releases. Please comment about wording on #4814 .

**Comment by eteq** [comment]
One question for @antonkoekemoer (or any others who care) given the looming 1.2 deadline: is the ``ignore_sip`` keyword something we want in for 1.2, also?  Would be pretty easy to add post #4814, but the clock is ticking...

**Comment by antonkoekemoer** [comment]
@eteq As far as I can see, the proposed edits in #4814 now address the main issues, especially in printing sufficiently informative messages when headers are inconsistent in terms of SIP (both to inform the user of the diagnosis of the issue, and also providing sufficient instructions on how to proceed either way).

**Comment by astrofrog** [comment]
@nden - we can close this now, right?

**Comment by eteq** [comment]
I'm going to assume yes and go ahead and close this just so we don't forget... But it can be re-opened if anyone feels it's necessary.
