### ISSUE TITLE
Use higher-level error type for io.registry

### ISSUE THREAD

**Issue by duncanmmacleod** [astropy/astropy#4831]
The use of `Exception` as the error class in `io.registry` (e.g. [here](https://github.com/astropy/astropy/blob/ea043f497c139c17608f85ff2871aff32bdbd816/astropy/io/registry.py#L285)) means catching these errors and not everything else is harder than it could be.

Is it possible to use a higher-level exception class for this, perhaps `TypeError` or a custom `RegistryError`?

**Comment by taldcroft** [comment]
Sounds like a fine idea to me, perhaps `IORegistryError`?  Go for it!  :smile:

**Comment by duncanmmacleod** [comment]
@taldcroft, I'm happy to put this together as a PR.

I would like to _not_ have the `IORegistryError` inherit directly from `Exception`, but rather one of the higher-level objects, mainly to give a better context, but also so that codes don't have to import the error object directly - maybe that's not a good enough reason.

I would go for `KeyError`, since this is all `dict`-based storage underneath, but its not my code...

**Comment by taldcroft** [comment]
@duncanmmacleod - inheriting from `KeyError` or `ValueError` would be fine.  If I were doing this I would go for `ValueError` since the fact that the underlying implementation uses a `dict` based on a tuple of the input values is not important to the user who is trying to get a reader.  I think of the input values being bad.  But it's not a big deal.

What is a bigger deal is that the application code should really just import and use the precise version of the error class.  Particularly with common errors like `KeyError` you can be hiding code mistakes in astropy by catching that.  The import will be free and just takes one extra code line.
