### ISSUE TITLE
Incorrect information on "description of galactocentric coordinates transformation"

### ISSUE THREAD

**Issue by zhu-wei-pku** [astropy/astropy#4841]
Hi astropy developer,

I found the following page contains incorrect information:
http://docs.astropy.org/en/stable/coordinates/galactocentric.html#coordinates-galactocentric

This page says \eta = 148.5986320 \deg, but in fact it should be 58.5986320 \deg. 

In addition, it is better to indicate in this page that the rotation matrix has taken into account the negative sign of \delta_GC. Otherwise people using Dec=−28:56:10.23 deg for the Galactic Center position would find wrong answer.

**Comment by astrofrog** [comment]
cc @adrn @eteq

**Comment by adrn** [comment]
Ah, yes, it looks like the value in the documentation is from a previous (incorrect) version. Thanks for catching this.

On your second point -- could you elaborate? The transformation code does not (or should not) "take into account" the negative sign -- you can see here that the declination of the Galactic center is defined to be -28.936175 deg: https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/galactocentric.py#L130

**Comment by astrofrog** [comment]
I'm re-opening this since the second point may still need addressing

**Comment by astrofrog** [comment]
@zhu-wei-pku - can you clarify what you meant regarding the negative sign? (see @adrn's question)

**Comment by adrn** [comment]
@zhu-wei-pku Pinging here -- do you still see an issue with a negative sign?

**Comment by zhu-wei-pku** [comment]
Sorry for this very late response... No problem with the negative sign now. I was just treating the angle slightly differently, which was why I had the puzzle.

Thanks for correcting the angle value.

**Comment by adrn** [comment]
Looking at this again with @timothydmorton and I think there is actually an issue with the documentation -- but I've totally confused myself right now. Can you re-open this and I'll take a closer look? @pllim @eteq

**Comment by pllim** [comment]
It is re-opened.

**Comment by adrn** [comment]
From reviewing this class during the velocities overhaul, I think it is ok.

**Comment by jvo203** [comment]
Please would you re-examine this issue? I have re-implemented the transform_to -> galactocentric in Julia (before the final implementation in C/C++) by copying/pasting the equations for the documentation (http://docs.astropy.org/en/stable/coordinates/galactocentric.html). But the only way to get an agreement between Julia and Python is by inverting the sign of \delta_GC!

Is the astropy code correct? Is the documentation correct? Either that or there is some error in my Julia code that I fail to see (it was a direct copy/paste from the documentation) so I am at a complete loss... Please help!

The sample python code:

import numpy as np
from astropy.visualization import astropy_mpl_style

import astropy.coordinates as coord
import astropy.units as u

c1 = coord.ICRS(ra=89.014303*u.degree, dec=13.924912*u.degree,
                distance=(37.59*u.mas).to(u.pc, u.parallax()),
                pm_ra_cosdec=372.72*u.mas/u.yr,
                pm_dec=-483.69*u.mas/u.yr,
                radial_velocity=0.37*u.km/u.s)
print(c1)

gc1 = c1.transform_to(coord.Galactocentric)
print(gc1)

The corresponding Julia code:

ra = 89.014303
dec = 13.924912
ω = 37.59

α = deg2rad(ra)
δ = deg2rad(dec)
d = 1000.0 / ω

pmra = 372.72
pmdec = -483.69
radial_velocity = 0.37

η = deg2rad(58.5986320306)
αGC = deg2rad(266.4051)
δGC = - deg2rad(-28.936175)#the sign in the rotation matrix as per documentation seems to be inverted; cannot understand the root cause of the problem
dGC = 8300
xGC = [1, 0, 0]
z = 27
θ = asin(z / dGC)

r_icrs = d * [cos(α) * cos(δ), sin(α) * cos(δ), sin(δ)]

R₁ = Matrix(undef, 3, 3)
R₁[1,1] = cos(δGC)
R₁[1,2] = 0
R₁[1,3] = - sin(δGC)
R₁[2,:] = [0 1 0]
R₁[3,1] = sin(δGC)
R₁[3,2] = 0
R₁[3,3] = cos(δGC)
println("R₁:", R₁)

R₂ = Matrix(undef, 3, 3)
R₂[1,1] = cos(αGC)
R₂[1,2] = sin(αGC)
R₂[1,3] = 0
R₂[2,1] = - sin(αGC)
R₂[2,2] = cos(αGC)
R₂[2,3] = 0
R₂[3,:] = [0 0 1]
println("R₂:", R₂)

R₃ = Matrix(undef, 3, 3)
R₃[1,:] = [1 0 0]
R₃[2,1] = 0
R₃[2,2] = cos(η)
R₃[2,3] = sin(η)
R₃[3,1] = 0
R₃[3,2] = - sin(η)
R₃[3,3] = cos(η)
println("R₃:", R₃)

R = R₃ * R₁ * R₂
println("R:", R)

R = Matrix(undef, 3, 3)
R[1,1] = cos(αGC) * cos(δGC)
R[1,2] = cos(δGC) * sin(αGC)
R[1,3] = - sin(δGC)
R[2,1] = cos(αGC) * sin(δGC) * sin(η) - sin(αGC) * cos(η)
R[2,2] = sin(αGC) * sin(δGC) * sin(η) + cos(αGC) * cos(η)
R[2,3] = cos(δGC) * sin(η)
R[3,1] = cos(αGC) * sin(δGC) * cos(η) + sin(αGC) * sin(η)
R[3,2] = sin(αGC) * sin(δGC) * cos(η) - cos(αGC) * sin(η)
R[3,3] = cos(δGC) * cos(η)
println("R:", R)

H = Matrix(undef, 3, 3)
H[1,1] = cos(θ)
H[1,2] = 0
H[1,3] = sin(θ)
H[2,1] = 0
H[2,2] = 1
H[2,3] = 0
H[3,1] = - sin(θ)
H[3,2] = 0
H[3,3] = cos(θ)
println("H:", H)

r = R * r_icrs - dGC * xGC
rGC = H * r

println("distance:", d)
println("r_icrs:", r_icrs)
println("r:", r)
println("rGC:", rGC)

**Comment by jvo203** [comment]
Perhaps in the documentation R₁ should be using the clockwise rotation matrix like this:
R₁[1,1] = cos(δGC)
R₁[1,2] = 0
R₁[1,3] = sin(δGC)
R₁[2,:] = [0 1 0]
R₁[3,1] = - sin(δGC)
R₁[3,2] = 0
R₁[3,3] = cos(δGC)

**Comment by pllim** [comment]
@jvo203 , please open a new issue and repost your examples there. Please also provide version info for Python, Astropy, and Numpy versions that you are using. And please include the output values you see for both of your Python and Julia examples. Thank you.

**Comment by jvo203** [comment]
OK, done.

https://github.com/astropy/astropy/issues/8645
