### ISSUE TITLE
Move stats subpackage out of Astropy?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#4846]
As stated by @adrn [here](https://github.com/astropy/astropy/pull/4811#issuecomment-215964807):

_I think all of `astropy.stats` belongs in an affiliated package... Right now, `astropy.stats` is just a repository for dumping random statistical utilities and, I would argue, is still somewhat exploratory. That to me sounds like one of the visions for an affiliated package: a place to add / try out new features before merging in to `astropy` core as a more mature subpackage. It could end up going the other direction (start in `astropy` core -> affiliated package) if it is developed enough. Maybe that's ok? Anyways, just expressing my thoughts!_

**Comment by astrofrog** [comment]
I disagree, I think it's fine to have high-quality stats functions in astropy.stats. I agree we shouldn't put functions that aren't well documented etc. But once they are ready, why not include them in the core? This is different from trying to set up for example WCSAxes which has a complex class structure, and needed several iterations to get right.

**Comment by taldcroft** [comment]
I agree there is enough "core" functionality in the existing `stats` sub-package to merit staying in astropy core.  Admittedly there are some functions in there that fall into the grab-bag category, and it's worth noting that by my census there is only one use of `astropy.stats` in astropy core itself.  But overall I don't think that the pain of moving `astropy.stats` into an affiliated package would be worth it.

**Comment by bsipocz** [comment]
While I see sense in the suggestion (atm ``stats`` contains some ad-hoc looking functions, that are there only because someone took the time and implement them rather than because they were needed for some other core or affiliate functions). 
But. There are some functions in there (e.g. ``sigma_clip``) that are needed by several affiliated packages, and thus I think introducing a new affiliate stats package will be a drawback for those. 

So in my opinion the separation would need some people who are willing to take the blame to decide which ones are core functionality and which are extra ones, and willing to maintain a separate stats affiliated package with the "extra" functionalities. If we don't have these individuals, then stats are better of staying and growing as is.

**Comment by mhvk** [comment]
I rather agree with the sentiment, but it would seem too late. Also, at some level it is true just as much for all of the packages in the "Astronomy computations and utilities" section of the documentation (apart from VO, which should really be under I/O -- will make PR). I think one can recognize these parts just from the fact that they do not have an overall description, but just give links to individual functions.

All that said, even if like @adrn I'd probably not have them included initially, I do think that a set of good statistical tools makes sense as part of the core of astropy. The main question to me would seem to be how to ensure it starts to develop coherence, with tools grouped by their function, with the documentation providing links to `scipy` where relevant, etc.

**Comment by mhvk** [comment]
p.s. My statement about little coherence in "computations and utilities" very much does *not* hold for `cosmology` -- but that also sets the standard for the other packages! (Or, arguably, that it belongs in "core data structures").

**Comment by mhvk** [comment]
I do wonder if it is useful to think a bit more about astropy organisation, mostly in order to avoid the core from becoming so big that it becomes faster to write one's own routine than to find the best matching existing routine in the documentation.

In that sense, in the spirit of @adrn's suggestion, but in the opposite direction, one could envision that rather that removing some parts, one could make others the "true core". I think this is possible since there is somewhat of a hierarchy within astropy, where higher levels use lower ones, but not vice versa. E.g.

0. units/constants/quantities
1. time; coordinates; modelling (all need units)
2. tables; wcs
3. nddata

(Ignoring I/O here which at some level needs much of the above).

Ensuring that this structure holds is good from the general principle of "separation of concerns" but also has the advantage that one could have much smaller subpackages that do not depend on all of astropy. This would make it easier, eg., to eventually move units into numpy or scipy (it is hardly astronomy specific!), and allow people who just want, e.g., good times and coordinates to not have to download tens of MB of package.

Anyway, getting somewhat off topic here...

**Comment by MSeifert04** [comment]
Just a thought: One common problem with any statistical function is over/underflow and correct implementation and interpretation. The latter point means one needs very good documentation (or links to good documentation) while the other points require good knowledge of floating point arithmetics and floating point representation error minimization. 

So no matter where they "end up" one should try to have them in a place where regular statisticians might be so that they can review them and especially point out "common mistakes" or "gotchas".

**Comment by astrofrog** [comment]
> Ensuring that this structure holds is good from the general principle of "separation of concerns" but also has the advantage that one could have much smaller subpackages that do not depend on all of astropy. This would make it easier, eg., to eventually move units into numpy or scipy (it is hardly astronomy specific!), and allow people who just want, e.g., good times and coordinates to not have to download tens of MB of package.

This is probably a discussion that best belongs on astropy-dev, but while this is on my mind I think there are different issues here that it would be good to disentangle:

* From the **user** point of view I don't think anyone's ever complained about having the download size for Astropy, and users prefer fewer packages. I regularly run into users who don't even understand why they still have to install ``astroquery`` and ``photutils`` separately from ``astropy``. So if we told them they  had to install a smaller core package and then more packages to get what's in the core currently, it will be more burden on users. In addition, I've **never** heard anyone complain about the download size for astropy (the tar file is 7MB). So from the user perspective, fewer packages are better (I'm not advocating for putting way more in the core, just that I don't think we are in a bad place currently).

* From the **developer** point of view, there are a couple of things to consider: first, the more we fragment packages the harder it is to make sure that the different versions work with each other and makes it hard to change the API of functions (all different packages have to be robust to different versions of other packages). This is already something we encounter with affiliated packages, but would be more of an issue with smaller sub-packages. However, the pro of having smaller sub-packages is the ability to have a faster release cycle, faster development (including faster CI), separation of concerns as you say.

The main benefit of splitting into multiple packages is for the developer, not the user, and that is reason enough in my eyes to not go down the more/smaller packages route.

However, there are several potential avenues that could be worth exploring. For example, we could develop different parts of astropy in different repositories and make astropy into a namespace package. Then at the point of distribution to users, we could bundle them up into a single tar file for ease of installation. Another thing we can do in terms of separation of concerns is have a travis job that removes things from the core package that should not be used in other parts of the core package and then makes sure the CI still runs on the rest (I do this in [glue](https://github.com/glue-viz/glue/blob/master/.travis.yml#L147) to make sure that non-qt code doesn't depend on qt code). Anyway, this is just to say that there are ways of getting some of the benefits of compartmentalizing things without going to full way towards having many smaller packages (which I believe would not be something that would benefit the users).

**Comment by mhvk** [comment]
@astrofrog - agreed with your main point that the primary benefit is for the developers, and my suggestion was very much not to change anything for the regular users. Apart from the developers -- where I think the benefits are real and ever increasing -- there are also some benefits for other packages. E.g., if another package, maybe not even astronomy-related, just need units, they can have a dependency just on that rather than on all of astropy (this may also be relevant for distributions such as debian and fedora). Indeed, I think this is perhaps where @adrn came from -- astropy itself seemed meant as a core of essential tools needed for almost anything one could think of in astronomy, and most of what is now in `stats` arguably doesn't belong in such a core.

Anyway, I think overall we seem to agree to leave `stats` in, but perhaps try harder to improve the docs for stats; in that respect, #4811 is a shining model!

**Comment by crawfordsm** [comment]
Very interested in hearing people's opinions on these points, so thank you for everyones thoughts and please keep them coming!   

The stats package is definitely under-supported and does need a clear APE to define its use (which I have been meaning to work on for quite some time, but if anyone else wants to step up to do it, please do so).   It could certainly use more documentation and some further tightening of some of the tasks and more tests.   Looking at the docs, the list of functions could be more coherently organized (before we didn't even have enough functions to organize!) and I'll open an issue about that.

At this time, its vision is a  collection of statistical tools used in astronomy.    Right now, I use a very inclusive requirement for what should be included:  if an astronomer finds or would find this tool useful and it is not easily found in the same form in scipy/numpy  than it is included.  My feeling is what one person may not find core, another person finds absolutely essential to their work; and as such, it is better to be inclusive.   Obviously, the stats package is a relatively small portion of the overall astropy code and I would be very hesitant to accept something that substantially added to the size of astropy in the stats package or overly complicated the installation. 

However, if there is strong feelings that this should change, then it would be great to hear what a definition of an essential astronomy statistical tool should be (as I think we all agree that statistical tools are essential to astronomy).

**Comment by mhvk** [comment]
My closing thought: the PR that triggered this, #4811, will, I think, go some way to set the standard expected from `astropy.stats`!

**Comment by embray** [comment]
>  I regularly run into users who don't even understand why they still have to install astroquery and photutils separately from astropy

You could add a metapackage to PyPI--call it "astropy-full" that includes "astropy" (which is understood to be the astropy "base" system), along with any stable and well-support affiliated packages.

**Comment by astrofrog** [comment]
> At this time, its vision is a collection of statistical tools used in astronomy. Right now, I use a very inclusive requirement for what should be included: if an astronomer finds or would find this tool useful and it is not easily found in the same form in scipy/numpy than it is included. My feeling is what one person may not find core, another person finds absolutely essential to their work; and as such, it is better to be inclusive. Obviously, the stats package is a relatively small portion of the overall astropy code and I would be very hesitant to accept something that substantially added to the size of astropy in the stats package or overly complicated the installation.

I think that, in the spirit of the rest of the core, we should nevertheless have a bar below which we say 'no' to including a function - I personally would define that as being the place where it becomes useful to only a sub-domain of astronomy. For example, solar-specific statistics can go in sunpy, gamma-ray specific can go in gammapy. If there was a statistic used in e.g. exoplanets and not anywhere else, I would also argue it's not 'core' enough.

**Comment by adrn** [comment]
Sorry for sparking this discussion and then disappearing! Thesis defense mumble mumble...

Anyway, I now agree that moving `astropy.stats` out is probably not worth the effort at this point. But I do think that it is worth thinking about what "astropy core" means going forward. For example, I don't think `astropy.stats` fits in this description of the core from the docs:

> The core also provides this documentation, and a variety of utilities that simplify starting other python astronomy/astrophysics packages

In fact, I think the 3 outliers from this perspective are `stats`, `modeling`, and `cosmology`. For future possible subpackages that fall in similarly grey areas I would argue they should be (or at least start as) affiliated packages. 

@astrofrog I disagree that users find it simpler to install one package vs 2. Once they learn to use `conda`, package installation is not really the hurdle that it used to be. We're talking about the difference between `conda install astropy` and `conda install astropy astropy-stats` or whatever. But, yea it would make it harder to maintain and could lead to annoying issues with package versions, etc. 

@embray That is an interesting idea!

**Comment by pllim** [comment]
Astronomy is all about statistics, right? I don't follow that part of the argument that statistics should not be a part of core.

**Comment by taldcroft** [comment]
> Once they learn to use conda, package installation is not really the hurdle that it used to be. We're talking about the difference between conda install astropy and conda install astropy astropy-stats or whatever. 

Until we have data showing > 95% adoption of conda, I'm not sure I would be that cavalier.  Remember also that `astropy` is fortunate to be in the conda core, but that won't necessarily (or likely) be the case for most affiliated packages.  So users would need to learn to add the appropriate channel, and all the package managers (astropy conda channel, debian, macports, etc etc) need to maintain *more* packages.  Certainly everything is possible, but it's a bit *easier* from the distribution side to just have one.

(This comment doesn't really apply for satellite packages that get bundled into core astropy at the end (option 3)).

**Comment by adrn** [comment]
@taldcroft that's fair!

**Comment by eteq** [comment]
@adrn - I appreciate the sentiment here, and won't reiterate too much of the whole "practicality" argument for `stats`(as we seem to be pretty much all in agreement there). 

But in the spirit of what both @adrn and @astrofrog mentioned about thinking about what belongs in the core: I think `astropy.stats` *does* belong in the core: As @pllim pointed out, astronomy is very much about statistics.  And there's a lot of statistical tools that are either astronomy-specific, or that have quirks in how they're used in astropy that make at least an astronomy-specific interface valuable (the Lomb-Scargle periodogram of #4811  being a great example of the former, and `sigma_clip` being an example of the latter).  That said, it's very much case-by-case to decide what is "standard" vs. "experimental".

`cosmology` I think is similar: *lots* of people want a standard tool that just does typical calculations and does them reasonably well. 

As for `modeling`, I think there `modeling.models` is very *much* an area that fits well with `astropy`: shared data models/interface layers.  `modeling.fitting` is much more debatable, though (*some* sort of built-in fitter is useful, but the existing machinery may have gotten too large just as @adrn says).


As a more "meta" point, I think it's likely that all of those wouldn't really exist now if they weren't in the core.  The folks who maintain those probably don't have time to maintain them if they *also* had to deal with release, web pages, advertising, etc.  And it would be even harder with the inevitably smaller user base that would come from being independent packages.  All of that goes out the window if the "option 3" from the mailing list is possible to maintain as easily as the current scheme, but as I said there I have serious doubts about that...
