### ISSUE TITLE
Copying io.fits.Header with copy.copy()

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4990]
After I realized that `astropy.wcs.WCS` objects behave strange when copied #4989 I found another astropy object that doesn't behave as expected:

```
>>> import astropy
>>> import copy
>>> a = astropy.io.fits.Header([('a', 1), ('b', 1)])
>>> b = copy.copy(a)
>>> a['c'] = 100
>>> a
A       =                    1                                                  
B       =                    1                                                  
C       =                  100                                       
>>> b
A       =                    1                                                  
B       =                    1                                                  
C       =                  100        # why is C present in the copy?     
```

This behaviour is different from the `.copy()` method:

```
>>> a = astropy.io.fits.Header([('a', 1), ('b', 1)])
>>> b = a.copy()
>>> a['c'] = 100
>>> a
A       =                    1                                                  
B       =                    1                                                  
C       =                  100  
>>> b
A       =                    1                                                  
B       =                    1  
```

Maybe one could overload the `__copy__` method here (which will be called by `copy.copy`). Or is this behaviour intentional?

**Comment by mcara** [comment]
I would expect that behavior of ``copy.copy()`` be similar to the ``.copy()`` method. It seems that ``.copy()`` actually returns a partially-deep copy:
```python
>>> c = a.copy()
>>> id(a._cards)
4377423672
>>> id(b._cards)
4377423672
>>> id(c._cards)
4302217728
```

**Comment by mcara** [comment]
After a quick look at the code, especially for the ``Card`` object, I am now pretty sure that ``Header.copy()`` de-facto returns a deep copy.

**Comment by astrofrog** [comment]
I think that we've usually gone the route of making ``.copy`` behave like ``.deepcopy`` deliberately. Maybe @eteq or @taldcroft can comment here, if this is to be a matter of general policy?

**Comment by MSeifert04** [comment]
@mcara Isn't a partial deepcopy (at least concerning the ``_cards``) required to provide a copy? I don't mean in a literal sense but a Header is some kind of wrapper for a key-value-comment structure and currently the shallow copy doesn't copy the key-value-comment structure?

**Comment by mcara** [comment]
@MSeifert04 I do not think we have a disagreement here. I was just stating what I have noticed: ``.copy()`` returns a deep copy of a header while when you use ``copy.copy()`` you get a "true" shallow copy (possibly because ``__copy__`` was not implemented to call ``.copy()`` - why? - I don't know). Maybe, under some circumstances, it may be useful to be able to create "true" shallow copies but I am not aware of any such circumstance.

**Comment by mhvk** [comment]
Having brought here from #4989, I agree with @mcara that a shallow copy here makes little sense: like for a python `dict`, one expects to be able to add new items to the copy without changing the original.

**Comment by pllim** [comment]
I think it is deliberate that the `.copy()` method here behaves like the method in a Numpy array.

```python
In [1]: import numpy as np
a = n
In [2]: a = np.array([1,2,3])

In [3]: b = a.copy()

In [4]: a[0] = 100

In [5]: a
Out[5]: array([100,   2,   3])

In [6]: b
Out[6]: array([1, 2, 3])
```

The above is the behavior I would expect, not a shallow copy.

**Comment by mcara** [comment]
Ah, @pllim ... I wish things were so simple... 
```python
>>> import numpy as np
>>> d1 = {'a': 1, 'b': 2}
>>> ar1 = np.array([d1], copy=True)
>>> ar2 = ar1.copy()
>>> d1['a'] = -1
>>> ar1
array([{'a': -1, 'b': 2}], dtype=object)
>>> ar2
array([{'a': -1, 'b': 2}], dtype=object)
>>> ar1[0]['a'] = 5
>>> ar2
array([{'a': 5, 'b': 2}], dtype=object)
```
So, numpy's copy() actually is not a true deep copy.

**Comment by pllim** [comment]
@mcara , what would be the equivalent of such a case in FITS header?

**Comment by MSeifert04** [comment]
I think Header actually prevents using mutables as values, so there is no equivalent?!

**Comment by mcara** [comment]
@pllim My conter-example illustrates that even for numpy arrays, the behavior of the copy is not as simple as indicated by your example https://github.com/astropy/astropy/issues/4990#issuecomment-223001884.

**Comment by mcara** [comment]
numpy array's behavior has nothing to do with ``fits.Header`` which most closely resembles lists of tuples and so it is expected to behave like a list of tuples. Tuples are immutable while lists are not. However, ``copy.copy()`` on a list of tuples should produce a **new** list of tuples. @MSeifert04 example in https://github.com/astropy/astropy/issues/4990#issue-157542882 illustrates that ``copy.copy(Header)`` produces unexpected behavior, unlike a ``copy.copy()`` of lists:
```python
>>> import copy
>>> l1 = [1, 2, 3]
>>> l2 = copy.copy(l1)
>>> l1[0] = -1
>>> l1
[-1, 2, 3]
>>> l2
[1, 2, 3]
```

**Comment by MSeifert04** [comment]
I actually think of a Header more like a dictionary (with the exception that one cannot use mutable values):

```
a = {'a': 1, 'b': [1,2,3]}
b = a.copy()
b['a'] = 3
b['b'][0] = 3
b['c'] = 3
a # {'a': 1, 'b': [3, 2, 3]}
b # {'a': 3, 'b': [3, 2, 3], 'c': 3}
```

**Comment by mcara** [comment]
@MSeifert04 You are right - from outside ``Header`` does resemble an *ordered dictionary* (see also https://github.com/astropy/astropy/issues/4648#issuecomment-191110235). When comparing ``Header`` to a list I was thinking about inner working of this class.

**Comment by mcara** [comment]
Actually, I think of ``Header`` as a list of *cards* (=tuples of 'name', 'value', 'comment') that can be accessed by name using dictionary syntax.

In the end it does not matter exact formulation of ``Header`` - what matters is that we all agree that *in the case of ``Header``* ``copy.copy(Header)`` should produce a new list/dict of cards unlike what is currently happening as illustrated in your original post.

**Comment by pllim** [comment]
I disagree. The `copy` method clearly states it returns a new `Header` instance. It mentioned nothing about replacing `copy.copy()` function. Perhaps the solution is simply to clarify in the `copy()` method documentation that it behaves differently from `copy.copy()`.

**Comment by mcara** [comment]
@pllim What do you exactly disagree with?

The issue being discussed here is that ``copy.copy()`` should produce an object that behaves in line with "reasonable expectations" of such an object. Specifically, many people think of ``fits.Header`` as a dictionary (personally, I view ``fits.Header`` as a list of tuples (immutables) that can be accessed/indexed using dictionary syntax with first elements of the tuples as keys - effectively this does not affect the discussion here). Therefore it is worth comparing the behavior of ``copy.copy()`` when applied to ``fits.Header`` and when applied to a dict:
```python
>>> # copy.copy() applied to a dict:
>>> import copy
>>> d1 = {'a': 1, 'b': 2}
>>> d2 = copy.copy(d1)
>>> d1['a'] = -1
>>> d2
{'a': 1, 'b': 2}
```
Notice that changing the value of item with key 'a' in dictionary ``d1`` **did not affect** the value of the item with key 'a' in ``d2``. Let's see what is happening in ``fits.Header``:
```python
>>> # copy.copy() applied to a fits.Header:
>>> import copy
>>> from astropy.io.fits.header import Header
>>> d = {'a': 1, 'b': 2}
>>> h1 = Header(d)
>>> h1
A       =                    1                                                  
B       =                    2                                                  
>>> h2 = copy.copy(h1)
>>> h1['a'] = -1
>>> h2
A       =                   -1                                                  
B       =                    2                                                  
```
Notice that changing the value of item with key 'a' in ``h1`` **did affect** the value of the item with key 'a' in ``h2``. This is different from what we would expect either from a dictionary or a list of immutables.

**Comment by pllim** [comment]
@mcara , the original issue is whether `copy.copy()` should behave like `hdr.copy()`. My answer is no.

**Comment by mcara** [comment]
In your last message I think you have formulated the problem the way I understand it unlike your description in https://github.com/astropy/astropy/issues/4990#issuecomment-223103686 Well, I strongly disagree with you: I think ``copy.copy()`` should return a shallow copy of the header **as if it were** a dictionary (because of our expectations with regard to ``fits.Header``).

That is, the fundamental issue here is: "Do we want ``fits.Header`` to behave like a dictionary"? Currently, 
``fits.Header`` behaves differently from a (an ordered) dictionary, at least with regard to ``copy.copy()``. In
https://github.com/astropy/astropy/issues/4990#issuecomment-223103686 you say: _"The ``copy`` method clearly states it returns a new ``Header`` instance. It mentioned nothing about replacing ``copy.copy()`` function."_ Both ``copy.copy()`` and ``Header.copy()`` return a **new** ``fits.Header`` object:
```python
>>> import copy
>>> from astropy.io.fits.header import Header
>>> d = {'a': 1, 'b': 2}
>>> h = Header(d)
>>> h1c = copy.copy(h)
>>> h2c = h.copy()
>>> id(h)
4377451024
>>> id(h1c)
4363799824
>>> id(h2c)
4364171408
```
The difference between these "new objects" is that ``h1c`` *behaves* as if it were created with assignment (``h1c=h``) and this is an *unexpected behavior*.

**Comment by pllim** [comment]
I think I might have to invoke @embray here to comment, if he wishes.

**Comment by MSeifert04** [comment]
Actually I find it confusing to have different ways of copy. But I feel the same way about ``WCS`` and ``Header``. The minimal copy should copy all required and necessary parts of a class, only exluding _deliberatly_ set mutable attributes (for example a list nested in a list/dict). But iif the required type of an attribute is a list it should be copied as well. At least that's my interpretation of a minimal (shallow) copy.

But that's one opinion, I can see that there are lots of other opinions here mcara disagrees on the wcs and pllim disagrees on Header. Maybe the best way would be to omit the ``copy`` methods altogether and just stick with the ``copy`` module and only overwrite behaviour if the actual result would be "buggy" otherwise.

**Comment by mcara** [comment]
@MSeifert04 Oh, you've touched so many issues 😰 

1. 

 > _Actually I find it confusing to have different ways of copy._

 Well, even the "stdlib" ``copy`` module provides two ways of copying an object (plus there is also the assignment operator as @pllim mentioned above). This how things are in Python. I have no problem with this (but I realize it can be confusing: for example, I was surprised that ``w2 = w1`` does not create a shallow copy like in C++ but rather it creates a new reference to the same instance - so weird!)

2. 

 > _But I feel the same way about WCS and Header._

 I look at this problem from the following perspective: Will we ever have the need to modify internals of a ``Header`` or ``WCS``? In the case of the ``fits.Header`` I do not see anything that anyone would want to modify. Even the ``cards`` property clearly states that it should not be modified directly. On the other hand, for ``WCS`` objects there are real situations when being able to do shallow copies of WCS object can come handy. For example, this can be used to make "quick" copies of WCS objects and turn off specific distortions. In https://github.com/astropy/astropy/issues/4989#issuecomment-222776148 I have shown how to turn off SIP. More importantly, the same idea can be used to turn off ``det2im1``, ``det2im2``, ``cpdis1``, and/or ``cpdis2`` distortions which can not be turned off reliably otherwise. So, the idea is that we are expected to modify internals of a WCS object. Sometimes it is useful to be able to modify the internals without creating a deep copy of WCS.

3. 

 > _The minimal copy should copy all required and necessary parts of a class, only exluding deliberatly set mutable attributes (for example a list nested in a list/dict). But iif the required type of an attribute is a list it should be copied as well. At least that's my interpretation of a minimal (shallow) copy._

 That would be **yet another** 😧 (even more confusing!) kind of copy operation: "partially deep copy"  Now, do you really want to get users to read documentation? (see _"Note that users in general don't read the docs..."_ in https://github.com/astropy/astropy/issues/4989#issuecomment-222932772 😉 ) Also, your interpretation of shallow copy is different (it does not mean it is wrong to want such a copy operation) from its definition either in Python or C++.

 As a side note, your description of what needs to be copied is confusing, at least for me. For example, now I have to wonder what would be _"**deliberatly set** mutable attributes"_.

4. 

 > _Maybe the best way would be to omit the copy methods altogether and just stick with the copy module and only overwrite behaviour if the actual result would be "buggy" (inconsistent state) otherwise._

 Omitting or not copy methods will make no difference: one can still use copy and deepcopy from the copy module - so still too many methods... I think the intention of ``.copy()`` and ``.deepcopy()`` methods was to avoid having to import the copy module and not to introduce some new weird way of copying. Thus I would expect ``copy.copy(object)`` to be identical to ``object.copy()`` (or ``object.copy(deep=False)`` as proposed by @astrofrog) and ``copy.deepcopy(object)`` to be identical to ``object.deepcopy()``. Of course no one can prevent you from implementing some other copy method such as ``object.copy_a_la_mseifert()`` that would do some sophisticated copying that you wish on some objects.

**Comment by taldcroft** [comment]
> For this reason I believe that Header.__copy__() should be implemented exactly as Header.copy().

This is my default expectation.  For instance in Table:
```
    def copy(self, copy_data=True):
        '''
        Return a copy of the table.


        Parameters
        ----------
        copy_data : bool
            If `True` (the default), copy the underlying data array.
            Otherwise, use the same data array
        '''
        out = self.__class__(self, copy=copy_data)

        # If the current table is grouped then do the same in the copy
        if hasattr(self, '_groups'):
            out._groups = groups.TableGroups(out, indices=self._groups._indices,
                                             keys=self._groups._keys)
        return out

    def __deepcopy__(self, memo=None):
        return self.copy(True)

    def __copy__(self):
        return self.copy(False)
```
Perhaps we should have called the argument `deep` instead of `copy_data`, but the meaning is exactly the same.  However, there are nuances that are specific to the class in question.  For instance with `Table`, the `meta` attribute gets a deep copy no matter what.  I think it would be too dangerous otherwise.

Unfortunately my expectation isn't quite met in astropy even for the `Time` class that I initially wrote.  That exposes two public methods `copy()` which is a deep copy and `replicate()` which is a shallow copy.  And then:
```
    def __copy__(self):
        """
        Overrides the default behavior of the `copy.copy` function in
        the python stdlib to behave like `Time.copy`. Does *not* make a
        copy of the JD arrays - only copies by reference.
        """
        return self.replicate()

    def __deepcopy__(self, memo):
        """
        Overrides the default behavior of the `copy.deepcopy` function
        in the python stdlib to behave like `Time.copy`. Does make a
        copy of the JD arrays.
        """
        return self.copy()
```
The original rationale was that most users, not knowing about `deepcopy` as a concept, would assume that `copy` is in fact a deep copy.  It would be nice to be able to now go back in time and specify a more consistent API across astropy core, but alas that isn't going to happen.

For now on this one question I would vote :+1: for making the FITS header `__copy__` just call the header `copy()` method.  That seems the least surprising to me.

**Comment by mcara** [comment]
I really do not want to start another long thread. That being said,

> _For instance with Table, the meta attribute gets a deep copy no matter what. I think it would be too dangerous otherwise._

I do not understand why it would be too dangerous to not deep copy ``meta``... This parameter is essentially a pass-through, I think, and really it should be up to the user to take care of things. In addition, this fact that ``meta`` is being deep-copied is not described anywhere [which I do find dangerous]. 

For example, if I work with a catalog of stars derived from an image, I might link the "parent" image to the catalog using ``meta`` parameter. Does this mean that when a ``Table`` is copied the entire image will be deep-copied as well regardless of what kind of copy do I choose to do?

**Comment by taldcroft** [comment]
@mcara - documentation PR welcome!  

About the auto deep-copy of `meta`, you have a point, but we're walking the line about choosing a behavior that is least surprising for most users.  Automatically deep copying meta might incur performance problems but it will never generate subtle bugs that confuse non-expert users.  I tend to think of `meta` as an attribute of a table one would never share, just like `Column` has `unit` or `format` that are effectively deep-copied regardless of whether a `Column` has a shallow or deep copy.

**Comment by MSeifert04** [comment]
@mcara I wasn't talking only about ``copy.copy()`` and ``copy.deepcopy()`` but also calling the constructor ``type(instance)`` or even ``type(instance, copy=True/False)`` and then also the customized ``instance.copy(deep=True/False)`` or ``instance.copy()``/``instance.deepcopy()``. Then there are some type-conversion methods ``type.from_other(instance)`` (they probably copy?).

As much as I like the idea about ``copy_a_la_mseifert`` (can't wait to implement that somewhere :smile:) I think users shouldn't be bothered how something is implemented. For example the ``Header`` could be a subclass of ``dict`` then it would by default always copy the "cards". As it is it was implemented as ``dict``-like and therefore the "cards" are not copied. For the ``wcs`` the internal ``wcs`` attribute could be a named-tuple or another instance. Without knowing which type it is it's hard to "know" if it's copied or not. And at least in my opionion every attribute essential for a class should either be immutable or copied even during shallow-copies. That's just what I would expect as user, that doesn't mean it's feasable or even desired - it's just what I would expect.

About disabling distortions: It's good to know there is a use-case for disabling distortions with copy, but why with copy? Just because there is no other way? I mean even slicing deepcopies the whole wcs (which rather contradicts previous experiences with slicing). I do have to confess "I read documentation" but these use-cases and the behaviour during copy are not even documented. I think someone who doesn't read documentation should expect to be surprised but not those who read it.

Regarding the discussion: I don't really know anymore what I'd like. Even the "simple" case with ``Header.copy()`` vs. ``copy.copy(Header)`` isn't that simple: Why would we deepcopy here and not somewhere else. Does a shallow copy make sense for ``Header``? 

Maybe I should've started the discussion on the mailing list and not in here.

**Comment by mcara** [comment]
With regard to ``fits.Header`` I have expressed my opinion previously, see e.g., https://github.com/astropy/astropy/issues/4990#issuecomment-223120565, that, since ``fits.Header`` (in opinion of many people) was designed to mimic a ``dict``, it should behave like a ``dict`` when copied. The analogy between ``fits.Header`` and a ``dict`` is not perfect though: while a true ``dict`` can have any kind of values, ``fits.Header`` is restricted to tuples of FITS keywords, values, comments. Furthermore, I think ``fits.Header`` restricts type of keywords/values/etc. to immutables. Thus, a shallow copy here (if implemented correctly - not as it is now) would effectively be a a deep copy.

> _For the ``wcs`` the internal ``wcs`` attribute could be a named-tuple or another instance. Without knowing which type it is it's hard to "know" if it's copied or not._

If you look at the documentation for [``astropy.wcs.WCS``](http://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS) you can see that it is derived from [``astropy.wcs.WCSBase``](http://docs.astropy.org/en/stable/api/astropy.wcs.WCSBase.html#astropy.wcs.WCSBase) that has an attribute ``wcs`` of type [``astropy.wcs.Wcsprm``](http://docs.astropy.org/en/stable/api/astropy.wcs.Wcsprm.html#astropy.wcs.Wcsprm) that itself is derived from ``object``. Therefore once can conclude that ``astropy.wcs.WCS.wcs`` (sorry for so many wcses) is a mutable object which will not be copied during a shallow copy of a ``astropy.wcs.WCS`` object.

> _About disabling distortions: It's good to know there is a use-case for disabling distortions with copy, but why with copy? Just because there is no other way?_

Disabling distortions in ``WCS`` was just one example of how shallow copies can be used. Of course you can set ``sip=None`` on the original object (which will modify the object). However, if you want to keep the original object intact - then you need to disable distortions on a copy. There is nothing that forbids you from using a deep copy to make a copy of the original object. However, why would you make copies of (potentially - speaking in general) very large objects when it is not necessary. Thus, in my example shallow copy is used to improve performance while not modifying the original object. However, shallow copies have other uses such as _"...referenced objects are thus shared, so if one of these objects is modified (from A or B), the change is visible in the other..."_ (see https://en.wikipedia.org/wiki/Object_copying#Shallow_copy) It may not seem obvious why would anyone need this kind of evil "feature", but it comes handy. It is true that most users expect a copy to be a deep copy (in fact your issue https://github.com/astropy/astropy/issues/4989 essentially expresses your desire that *only* deep copies be allowed). Personally, I believe that both type of copies have their place and users should simply learn how Python works. I do not think we should be introducing new "ways" of copying such as [``replicate()`` in ``astropy.Time``](https://github.com/astropy/astropy/issues/4990#issuecomment-223170611) which return "replicas". This just deepens the mystery of copying.

> _I think someone who doesn't read documentation should expect to be surprised but not those who read it._

I agree! That is why I have agreed with you (see https://github.com/astropy/astropy/issues/4990#issuecomment-223069310) that ``fits.Header`` has a problem which needs to be fixed for example by making ``Header.__copy__()`` internally to call ``Header.copy()``. However, I am surprised that you are surprised about how a shallow copy works on a WCS object - I do not find any problems with ``copy`` in ``astropy.wcs.WCS`` and I think it functions as any regular Python shallow copy.

**Comment by MSeifert04** [comment]
It seems they already have a name for `copy_a_la_mseifert`: [Combination](https://en.wikipedia.org/wiki/Object_copying#Combination) :disappointed:

@mcara I don't disagree with your opinions. I just mentioned the `astropy.wcs.WCS.wcs` because it _could_ also be implemented in another way that _would_ be copied during a shallow copy. That's an implementation detail that I only look up in case a shallow copy does something unexpected. I'm surprised that you are surprised at me being surprised by this: I don't regularly modify ``WCS`` and therefore it went unnoticed, also because the ``__repr__`` of ``WCS`` includes attributes that aren't copied with a shallow copy.

But before we go deeper into that discussion, am I right that most (except for @pllim) agree on:
- `astropy.io.fits.Header.__copy__` should just call `Header.copy()`
- `astropy.wcs.WCS.copy` should get a docstring warning that `WCS.deepcopy()` might more appropriate in most cases? (https://github.com/astropy/astropy/issues/4989#issuecomment-222884421)
- `astropy.table.Table.copy` should mention that `meta` is always deepcopied.

**Comment by mcara** [comment]
@MSeifert04 I do agree with your last three points.

Do not be disappointed that your ``copy_a_la_mseifert`` has a name: you have invented, I believe, a new method which I would call "adaptive copy" (which knows what user wants by looking at how attributes were originally set) 😄 as illustrated in your example https://github.com/astropy/astropy/issues/4989#issuecomment-223253360 - that is entirely different from "Combination" (or what I had previously referred to as "partially-deep copy")! The copy implemented in ``astropy.time.Time`` is an example of a combination copy as it performs deep copy on its 'meta' attribute even when shallow-copying everything else *regardless* of how ``meta`` was set.
