### ISSUE TITLE
can't use numpy.linspace with units

### ISSUE THREAD

**Issue by lauralwatkins** [astropy/astropy#5000]
Linspace doesn't work when inputs have units.

For example:
`np.linspace(0*u.km/u.s, 5*u.km/u.s, 6)`

I expected this as output:
`<Quantity [ 0., 1., 2., 3., 4., 5.] km / s>`

But instead I get errors:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-143-cf6fb9cd1e18> in <module>()
----> 1 np.linspace(0*u.km/u.s, 5*u.km/u.s, 6)

~/Library/Python/2.7/lib/python/site-packages/numpy/core/function_base.pyc in linspace(start, stop, num, endpoint, retstep, dtype)
    113 
    114     if endpoint and num > 1:
--> 115         y[-1] = stop
    116 
    117     if retstep:

ValueError: setting an array element with a sequence.
```

**Comment by mhvk** [comment]
@lauralwatkins - thanks for the report! What version of numpy are you using? We had this issue before (#4543) and at that time it turned out the problem was with numpy, but that should have been fixed by https://github.com/numpy/numpy/pull/7156. So, hopefully you can resolve it by upgrading numpy! (If so, just close this issue.)

**Comment by lauralwatkins** [comment]
Ah ha, that did it, thanks!

**Comment by pllim** [comment]
Just noticed that this is issue number five thousand! :fireworks:

**Comment by eteq** [comment]
And an easy fix, too.  That's how will get to 10,000, right! ;)
