### ISSUE TITLE
generalize orbital elements machinery from calc_moon

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#5067]
In #4963, @StuartLittlefair implemented machinery to compute the location of the moon.  This includes some standard algorithms for getting the location of an object given its standard orbital elements.  That's useful for lots of other things like e.g. minor planets, artificial satellites, etc.  We should see about expanding that machinery to support other use cases like this as long as the user can provide something to compute the orbital elements (possibly as a function of time).

**Comment by mhvk** [comment]
I'm removing the milestone, since this seems very unlikely to happen for 1.3 (also, feature requests shouldn't really have milestones beyond "future").

**Comment by Juanlu001** [comment]
I've implemented conversion between classical (Keplerian), equinoctial and cartesian elements in poliastro:

http://poliastro.readthedocs.io/en/v0.6.0/user_guide.html#from-classical-orbital-elements

which makes it easy to compute the osculating orbit of the planets. Is this something in the lines of what you're thinking of including in Astropy?

**Comment by mhvk** [comment]
@Juanlu001 - that looks nice! Since you seem to use astropy quite a bit already, I would certainly encourage you to think about making poliastro an affiliated package. 

About the specific issue here: I'm actually not quite sure what @eteq had in mind: as it is, if you provide geo- or heliocentric cartesian coordinates, the coordinates package can already convert that to any other system; beyond that results will depend so much on one's approximations that it doesn't seem all that obvious that one wants to provide a general interface. The one exception I can think of is providing objects other than the major planets as jpl ephemerides (which would be relatively easy to do).

But maybe @eteq can expand...

**Comment by bsipocz** [comment]
@eteq - is this still on the table now that astroquery provides a way to query JPL horizon ephemerids, as well as that now we have `sbpy` as an affiliated package?
