### ISSUE TITLE
Quantity._repr_latex_ should work for all types.

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5071]
Currently, `Quantity._repr_latex_` mangles anything except float; a quick fix to try to make only floats have nice power-of-ten representations ~~is~~ was merged in #5068, but it would be better to be able to format also complex numbers and possible record arrays.

As these cases are rare, this is not urgent; hence the "future" milestone and priority low label.

**Comment by mhvk** [comment]
The route to this might be to define a `to_string` method and use that; see #5964. This is substantially more work, though, so just addressing this may be a good start.

**Comment by RebecaMelo** [comment]
I am interested in solve this, so I am trying to clarify for myself this issue.

First, I thought that I wouldn't be able to manipulate a float with Quantity._repr_latex_ (because of the first sentence explanation). However, I was able to do it. So, I don't think that's the problem.

![issue_5071](https://user-images.githubusercontent.com/29133196/43690882-78944056-98e8-11e8-831f-eaa735ee2561.png)

After, I understood that the problem would be the power-of-ten representation. As you can see in the print, the function does not give such representation. So, my question is if it's the problem.

The merge in #5068, it's not implemented on astropy, right? Should I try fix this representation in the code? And another point is trying to expand also to complex numbers representations, correct? Thanks!

**Comment by mhvk** [comment]
@RebecaMelo - thanks for your interest! We just had complex numbers take care of in #7676, so really this issue should have been closed (I think the structured array one is really a lot of work for very little benefit, especially as I am working on a separate class for that case).

**Comment by mhvk** [comment]
@RebecaMelo - My overall suggestion would be to try to tackle something that you care about, i.e., that slightly irritates you, or is unclear to you, or something that you wish astropy had.
