### ISSUE TITLE
WCS with inconsistent SIP representation

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#5145]
This issue is a followup (and consolidation) of the lengthy discussions in #4761 and #4803.  To briefly summarize, if a `WCS` object contains `SIP` coefficients, then `all_world2pix` applies them regardless of the `CTYPE`.  In other words, there is no on/off switch for applying SIP coefficients.  If they are present, then they are always used by `all_world2pix`.

This issue arose with CANDELS data, which are rectified (undistorted) data, but contain `SIP` coefficients in the header.  Obviously that is inconsistent.  `all_world2pix` applies the `SIP` coefficients on undistorted data and gives invalid (or non-converging) results.

The merged fix (#4814) was to simply issue a warning to the user when such a header is encountered.  The warning states that the user should use `wcs_world2pix` instead of `all_world2pix`.  However, the warning is insufficient because the call to `all_world2pix` might have been made in a tool where the user has no control to use `wcs_world2pix` instead.  A specific example is the `astropy.nddata.utils.Cutout2D` class, which internally calls `all_world2pix` so that it can be used on both distorted and undistorted data.  In that case, the user has no control to use `wcs_world2pix` instead of `all_world2pix`.  Further, changing `Cutout2D` to use `wcs_world2pix` would restrict its usage to only undistorted data.  The user has no recourse here and thus `Cutout2D` cannot be used on CANDELS data.

I propose that we actually fix this issue in `astropy` `WCS`.  In my (perhaps limited) understanding, the best solution is to use `CTYPE` as a switch:  do not use SIP coefficients unless `-SIP` is present in the `CTYPE`.  My understanding is that this was the intent of the SIP developers.  In my proposal, `astropy` `WCS` would simply remove SIP coefficients when the `WCS` is read if `-SIP` is not present in `CTYPE`.  I propose that we issue a warning in this case for the rare user who does not have `-SIP` in `CTYPE`, but actually wanted to use included SIP coefficients.  The simple fix for such rare cases would be to add `-SIP` to `CTYPE`.

cc: @nden, @mcara, @antonkoekemoer, @astrofrog, @eteq, @hcferguson, @stsci-hack, @pllim

**Comment by stsci-hack** [comment]
Support for revising astropy WCS to use CTYPE as a switch comes directly from the definition paper for SIP ([http://fits.gsfc.nasa.gov/registry/sip/SIP_distortion_v1_0.pdf]).  The library originally developed by the Spitzer team to work with SIP specifically stated that "the functions key off the extended CTYPEn" keywords.  This would allow the library to be very predictable, even when incorrectly populated headers are provided as input as demonstrated by the CANDELs data.  The currently reported warning could still be presented to the user to let them know there was some ambiguity in the header (SIP coefficients found, but -SIP not specified in CTYPE) so they could decide whether it should be fixed or not.  I would stress that this would be a secondary optional feature to retain if it would cause additional problems.

**Comment by mcara** [comment]
Based on my conversation with @stsci-hack it seems that in the past STScI was producing FLT images (those are the images that are supposed to have distortions) that did have SIP coefficients present in their headers but did have SIP coefficients. Therefore, using the presence of ``-SIP`` in ``CTYPE`` as a switch to applying SIP corrections is not possible without creating a new set of problems.

Therefore, this implies that images that do not have ``-SIP`` in ``CTYPE but do have SIP coefficients in their headers are perfectly legitimate and therefore we should not be issuing any warnings. The problem with warnings raised for legitimate images is that users will start ignoring warnings altogether be they legitimate or not.

Instead I am proposing to have a separate section in the WCS documentation describing the historical background for current WCS behavior (e.g., loading SIP even when ``-SIP`` is not in ``CTYPE``) and making users aware of this problem of ``-SIP`` so that they can fix their headers according to how they intend to use the images.

This implies that in the particular case of CANDLES either they fix their drizzled image headers by stripping out SIP coefficients or maybe we provide a tool somewhere within ``astropy.utils`` or ``astropy.wcs.tools`` that can make user files "consistent" with regard to the use of ``-SIP``: for example, this tool could add ``-SIP`` to ``CTYPE`` if it detects SIP coefficients in the header or it could strip these coefficients from the header (the behavior of the script could be controlled either via a parameter or interactively).

**Comment by mcara** [comment]
FYI [historical background]: STScI was producing FLT images without ``-SIP`` because at that time there were no tools (e.g., DS9) that could support 12 characters in ``CTYPE`` so, probably, a decision was made to load SIP coefficients from the headers when present regardless of the value of ``CTYPE``. That is my understanding...

**Comment by mcara** [comment]
Ah, I just noticed a mistake in my previous to last comment:

> _Based on my conversation with @stsci-hack it seems that in the past STScI was producing FLT images (those are the images that are supposed to have distortions) that did have SIP coefficients present in their headers but did have SIP coefficients._

should have been:

> Based on my conversation with @stsci-hack it seems that in the past STScI was producing FLT images (those are the images that are supposed to have distortions) that did have SIP coefficients present in their headers but did have __``-SIP`` suffix in their ``CTYPE``__.

**Comment by antonkoekemoer** [comment]
@mcara at least since OPUS-2009.3, all ACS FLT files have had SIP coefficients in the header and -SIP appended to the CTYPE keywords; also the drizzlepac documentation in section [3.2.1](http://documents.stsci.edu/hst/HST_overview/documents/DrizzlePac/ch33.html) says that SIP coefficients were not used by the archive pipelines prior to Astrodrizzle being implemented (which was in 2012). Finally, the recommendation in the 2009 [Multidrlzzle Handbook](http://www.stsci.edu/hst/HST_overview/documents/multidrizzle/multidrizzle.pdf) (Fruchter, Sosey, Hack et al), in section 4.2.5, says that for any earlier ACS FLT files the user needs to:
"append -SIP to the CTYPE keywords in all science extensions to allow DS9 and other SIP-aware software to use the SIP coefficients recorded in the science headers."

So the above remains consistent with the convention for needing to have "-SIP" appended to the CTYPE values when SIP coefficients are intended to be used.

**Comment by mcara** [comment]
@antonkoekemoer I strongly support using ``-SIP`` as a switch, and now this new information is very useful. If only more people would support it...

**Comment by mcara** [comment]
I just realized that I flip-flopped on this issue so many times, people might think I am running for president :)

**Comment by nden** [comment]
A resolution was agreed on and implemented in #5239.
