### ISSUE TITLE
ipac reader blows up in memory usage.

### ISSUE THREAD

**Issue by rainwoodman** [astropy/astropy#5257]
I was trying to read in a 600 MB ipac tbl file with about 30 columns with astropy.table.Table. 

The peak memory usage approaches 10GB. 
Version of astropy is 1.2.1.

I didn't find an immediate duplicate of this issue. This maybe related to https://github.com/astropy/astropy/issues/3334

If the try catch logic is still there then it is possibly indicating a leak from the exception or something?

**Comment by pllim** [comment]
@rainwoodman , did you try reading it in as chucks, as suggested by @taldcroft in [this comment of #3334](https://github.com/astropy/astropy/issues/3334#issuecomment-71035704)?

Not very sure which "try catch" logic you are referring to. Could you be more specific?

**Comment by taldcroft** [comment]
@rainwoodman - unfortunately this sort of memory usage is typical because of the way the file is first read as a list of Python strings, then every element the whole table is parsed into a list of strings that is also held in memory.  These pure Python objects have a lot of memory overhead associated with them.  

Chunked reading is the way to go, and there is an open initiative to implement this in astropy.  Doing this in a general way turns out to be somewhat difficult and this project got stuck.   However, feedback like yours does provide motivation to make this happen.  I'm closing this issue, but feel free to re-open if you like.
