### ISSUE TITLE
PyQT4 no longer needed?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5360]
https://github.com/astropy/astropy/pull/5348 pinned pyqt4, but now that causes a failure on travis: https://travis-ci.org/astropy/astropy/jobs/162031663

I'm guessing it is no longer needed?

**Comment by MSeifert04** [comment]
Yes, we don't need to pin it anymore **but** the new pyqt release (4.11.4-py35_7) forces sip to downgrade (4.16 instead of 4.18) producing the error: `RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt4.QtCore module requires API v11.3`

I hope someone already told anaconda/conda/pyqt that this is happening. To make the builds work _right now_ one would also need to pin sip=4.18. :smile:

**Comment by MSeifert04** [comment]
see https://github.com/ContinuumIO/anaconda-issues/issues/1090
