### ISSUE TITLE
Leap second day utc2tai interpolation 

### ISSUE THREAD

**Issue by luojing1211** [astropy/astropy#5369]
Hi astropy developers,

I am from North American pulsar time group(Nanograv). When I am processing some data taken in a leap second day(more exactly mjd 56109 ), I realize in that day, the leap second is interpolated. Here is a test I made.
```
>>> from astropy.time import Time
>>> test_leap = np.linspace(56107,56110,500)
>>> test_time = Time(test_leap, format='mjd', scale='utc')
>>> plt.plot(test_time.mjd, (test_time.tai.mjd - test_time.mjd)*86400.0)
```
And I have the plot. 
![astopy_tai](https://cloud.githubusercontent.com/assets/5324931/19005871/73bcb7ae-8722-11e6-9fb8-416568d86b75.png)

My question what is the reason to do an interpolation, and is there any way to shut the interpolation off. 

Thank you. 

-Luo Jing

**Comment by mhvk** [comment]
@luojing1211 - The problem is how to express a UTC in units of days on a leap-second day. The definition of JD means that any integer number has to be 12:00 UTC, so the choice to just make leap-second days be 1 second longer and interpolate is a reasonably logical one. At least, I don't know what else one could do; otherwise, how do you take care of a 23:59:60 time? What fraction of a day is that? Or, in other words, what would your expected behaviour be?

The way I think of it is that UTC is always a combination of day and time (more like the ISO string), and that a UTC JD is something one tries to avoid, instead always using TAI JD.

cc @taldcroft in case he has other suggestions.

**Comment by taldcroft** [comment]
@luojing1211 - I agree with the explanation from @mhvk.  I would just add that this behavior actually comes from the underlying IAU SOFA library (aka ERFA), so it is really an upstream implementation decision by the IAU that is very unlikely to change.  I'm closing this for now, but feel free to re-open if you have additional questions.

**Comment by mwcraig** [comment]
One more comment here: the [SOFA manual](http://www.iausofa.org/sofa_ts_c.pdf) explicitly says that this SOFA convention should *not* be exposed to users (footnote 9, p.  20):

> The quasi-JD that SOFA uses internally to represent UTC is obtained by treating days that end in a leap second as having a different length from usual, namely 86401s (or 86399s in the case of a negative leap second), when forming the fractional part. The scheme has no official status outside SOFA, and it is strongly recommended that applications do **not** exploit it.

Earlier they imply that the appropiate output from `my_on_utc_scale.jd` should be some sort of error (p. 13 bottom paragraph):

>  In particular, it is inappropriate to express UTC as a Julian Date, because there will be an ambiguity during a leap second—so that for example 1994 June 30 23h 59m 60s and 1994 July 1 00h 00m 00s would both come out as MJD 49534.00000—and because subtracting two such JDs would not yield the correct interval in cases that contain leap seconds.

It is not clear to me that astropy is currently doing the right thing here...I'm not sure what it should do instead, except maybe forbid expressing UTC in JD. I'd hazard a guess that going that route will break existing code (I know I have some 😮 ) but might be better in the long run.

**Comment by luojing1211** [comment]
Hi @mwcraig thanks for the comment. But forbidding expressing UTC in JD/MJD will make a lot of trouble for processing pulsar timing data, which is UTC time sample saved in MJD format.

**Comment by mwcraig** [comment]
@luojing1211 -- yeah, I'm pretty sure that change would be a mistake. Ultimately this is a science problem: what time scale are results reported in, and what is the meaning of a time in JD in UTC on a leap second day.

Fixing that is probably out of scope for astropy.

**Comment by mhvk** [comment]
Arrghh, this is not one with an easy answer! I think best is indeed to stick to just using dates and times for UTC (i.e., work in strings only), but I don't know that we can enforce this at this time...

@luojing1211 - out of curiosity, what does pulsar timing actually do? Just ignore the leap second in calculating the MJD? If so, what would be the MJD for a TOA that happened to land right on a leap second? Or is it simply deemed too unlikely to happen?

More practically, it would be possible to define a new `TimeMJD` format in which, if the scale is `utc` you explicitly convert the fraction of the day the way that is useful for pulsar timing. But I think this would probably best live within PINT. (Suggestions otherwise very welcome though; this clearly is tricky and it would be nice to resolve; I just don't see an elegant way to do it...)

**Comment by demorest** [comment]
In tempo/tempo2, the fractional part of the UTC MJD is always seconds_within_day/86400.0 and leap seconds are handled as a discontinuity (step function) in the UTC->TAI conversion.  I think this means it is actually impossible to have a TOA that occurred during the leap second itself.  While I agree the "86401-sec day" approach does make some sense, it's not clear there is a "right" answer.  And regardless of what is "right," for practical reasons we need to be consistent with previous pulsar software.  Maybe defining a time format within PINT is fine for this, unless there are other people out there who define UTC MJD this way and might want this format in astropy.

**Comment by taldcroft** [comment]
> In tempo/tempo2, the fractional part of the UTC MJD is always seconds_within_day/86400.0

I don't understand how you can uniquely represent a time within a leapsec as MJD in this scheme.

**Comment by demorest** [comment]
> I don't understand how you can uniquely represent a time within a leapsec as MJD in this scheme.

That's right, you can't.  That's why I said it's impossible to have a TOA that occurs during a leap second.  Not sure what the original reasoning behind this was, but I think we are kind of stuck with it for interpreting existing data files.

**Comment by taldcroft** [comment]
In theory we can add a warning when anyone uses the `jd` or `mjd` attributes of a UTC time object.  I'm not generally a huge fan of warnings, but this always seems like a good case of "you are doing something that is likely to get you into trouble because there is a subtle implementation detail you might not be aware of."

**Comment by mwcraig** [comment]
> In theory we can add a warning when anyone uses the jd or mjd attributes of a UTC time object.

This seems like a good compromise, especially since there is a *correct* way to calculate time differences in astropy given UTC input (difference the Time objects not the julian dates):

```
# A time one second before a leap second
pre_leap_second = Time("1994-06-30T23:59:59", scale='utc', format='isot')

# A time one second after the same leap second:
post_leap_second = Time("1994-07-01T00:00:00", scale='utc', format='isot')

# The Wrong Way to get the difference:
bad_interval = post_leap_second.jd - pre_leap_second.jd
print(bad_interval * 86400)
# Prints 1.9999891519546509, which is not 2.

# The Right Way:
good_interval = post_leap_second - pre_leap_second
print(good_interval.jd * 86400)

#prints 1.9999999999939178, which is 2 to machine precision
```
