### ISSUE TITLE
Overwrite parameter in ascii writers

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5438]
This issue is a follow-up comment / question to #5007 for @taldcroft and @evertrol .

We use `table.write(filename, format='ascii.ecsv')` in several places in Gammapy.
Now I'm getting the `AstropyDeprecationWarning`.
I can't add the `overwrite=True` in Gammapy, because we (obviously) still support Astropy 1.2.

Is there a way for us to write the code so that it works on Astropy 1.2 and 1.3 and doesn't raise deprecation warnings on 1.3+ all the time?

If yes, could you please let me know and add that info to the changelog entry?
If no, could you please be more specific in the changelog when you plan to raise an error here?
(It currently says "In a future version this will be changed  ...")

Just to be clear: I'm +1 for your change towards consistency in Astropy. Thank you for implementing it.

**Comment by pllim** [comment]
A temporary workaround is to use `warnings.catch_warnings()` on that warning and silence it.

**Comment by MSeifert04** [comment]
Isn't overwrite an allowed argument in 1.2? I had some problems with 1.0 but I thought 1.2 worked.

**Comment by cdeil** [comment]
> A temporary workaround is to use warnings.catch_warnings() on that warning and silence it.

Ah, of course. Thanks.
I'll do that, unless someone posts a better solution.

> Isn't overwrite an allowed argument in 1.2?

I think no, it'll raise an error.
But I'm not 100% sure, don't have Astropy 1.2 at hand.
If it really is an error on 1.2, you could also remove the deprecation warning for now, and make a reminder issue to add it later, i.e. give people more time to adjust without having to modify their libraries with `warnings.catch_warnings()` or have their users see deprecation warnings left and right.

**Comment by pllim** [comment]
Someone who used 1.2 told me that there is no overwrite keyword but rather it overwrites silently. I didn't test it, just passing the info along.

**Comment by taldcroft** [comment]
@cdeil - that is a pesky problem indeed.  I was just struck at the realization that other mature packages now need to support multiple versions of astropy.  This puts a new twist on our own discussions of API changes and deprecations.  Kind of an obvious point, but for years astropy has had to manage multiple numpy versions, typically with constants that indicate numpy version is less than X.Y.  

This is not pretty, but you might consider the same for gammapy so that version-specific code is obvious and can be removed when support for a particular version is dropped.  (For example in 10 years nobody might remember why warnings were caught around a particular table.write() call).

**Comment by evertrol** [comment]
Some other ptions I've used myself for such issues:
- use the new format, but wrap it in an exception block:

        try:
            table.write(filename, format='ascii.ecsv', overwrite=True)
        except TypeError:
            table.write(filename, format='ascii.ecsv')

  More work than the `catch_warnings` option, but it doesn't silence warnings (and if the `overwrite` parameter mismatch is not causing the `TypeError`, the exception handling part will cause it again).

- let the warning go out. It's annoying, but with a FAQ / wiki entry, you can tell users why this happens, and how to avoid it themselves. A bonus might be that users upgrade to astropy 1.3.
  I would preferably *not* put the silencing of the warning in the package itself, only at the user/script level.

**Comment by pllim** [comment]
I think version checking is more elegant than `try ... except ..`. Maybe something like this:

```python
kwargs = {'format': 'ascii.ecsv'}
if astropy >= X.Y:
    kwargs['overwrite'] = True
table.write(filename, **kwargs)
```

**Comment by evertrol** [comment]
My reasons for the try-except clause are the following:
- traditional (Python) wisdom suggests to use try-except in case the if-clause would most often be `True`, otherwise to use the if-clause. Over time, most people will upgrade and have an astropy version that supports the `overwrite` parameter (or whatever else may have changed), and the if-clause will be `True` most of the time.
- I've always felt version checking to be tricky, especially where you want to compare with version `1.3.5-dev` and such. Of course, there are routines to split that nicely, but that's still less fool proof than a simple try-except.
- it may happen that something similar would be coded like examples I've come across: `if PY2: ... elif PY3: ...`, and one runs into the Python 4 problem in the future (as per astrofrog's post).
- there's no problem if we'd ever happen to revert back to the old form in a future version.

I'm also not fond of putting everything in `kwargs`, since it makes it harder to found out what parameters are actually used in that call (especially in the case of a traceback). Or when one feels safe to remove the version check and revert back to a single `table.write()` line.

**Comment by taldcroft** [comment]
@evertrol 

- The always-present concern with try/except is that you can mask a real underlying error if the code throws an unrelated `TypeError`.  In this case I would be more worried about that than any of the later worries you mentioned.
- As a matter of style one should also heed the Don't Repeat Yourself principle.  In the example you showed of using try/except it would start looking pretty repetitious if there were more than a couple of args.  The solution from @pllim is not putting everything in `kwargs`, just one specific thing.
- Version checking is reliable and easy these days for major packages like astropy using distutils.version.

FYI https://github.com/astropy/astropy/pull/3100/files is the PR to remove support for numpy 1.5.  As you can see there was a mixture of styles handling numpy 1.5 at the time.  This PR was done by someone who did not know most of the affected code in detail.   So whatever you do, *make sure it is carefully commented so that future maintainers know what is happening and can find compatibility patches and update code accordingly*.  I would wager that there are still some remaining compatibility patches in astropy that Mike and others did not find in grepping.

**Comment by cdeil** [comment]
Thanks everyone for the suggestions and feedback.

IMO the two options mentioned to write code that works simultaneously with Astropy 1.2- and 1.3+ without raising warnings are both OK. It seems that there's a preference to keep the warning in 1.3 already, as opposed to adding it in a later version?

@taldcroft and @evertrol - What should we do to finish up this discussion and issue?
Maybe extend the changelog entry mentioning the issue and giving the recommended code snippet how to handle it?

Once it's clear what to put, I'd be happy to attach a commit to this issue, but it's not clear to me yet what the conclusion is.

**Comment by joleroi** [comment]
Without having followed the above discussion in detail, I think the following is an issue. I am using the latest astropy version I get from conda.

```
In [5]: import astropy

In [6]: from astropy.table import Table

In [7]: astropy.version.version
Out[7]: u'1.2.1'

In [8]: table = Table(data=[[1,2,3]], names = ['data'])

In [9]: table.write('text.csv', format='ascii.csv', overwrite=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-ed211fe3f14c> in <module>()
----> 1 table.write('text.csv', format='ascii.csv', overwrite=True)

/home/kingj/Software/miniconda3/envs/stableversions/lib/python2.7/site-packages/astropy/table/table.pyc in write(self, *args, **kwargs)
   2347         passed through to the underlying data reader (e.g. `~astropy.io.ascii.write`).
   2348         """
-> 2349         io_registry.write(self, *args, **kwargs)
   2350
   2351     def copy(self, copy_data=True):

/home/kingj/Software/miniconda3/envs/stableversions/lib/python2.7/site-packages/astropy/io/registry.pyc in write(data, *args, **kwargs)
    401
    402     writer = get_writer(format, data.__class__)
--> 403     writer(data, *args, **kwargs)
    404
    405

/home/kingj/Software/miniconda3/envs/stableversions/lib/python2.7/site-packages/astropy/io/ascii/connect.pyc in io_write(format, table, filename, **kwargs)
     41     from .ui import write
     42     format = re.sub(r'^ascii\.', '', format)
---> 43     return write(table, filename, format=format, **kwargs)
     44
     45

/home/kingj/Software/miniconda3/envs/stableversions/lib/python2.7/site-packages/astropy/io/ascii/ui.pyc in write(table, output, format, Writer, fast_writer, **kwargs)
    685     writer = get_writer(Writer=Writer, fast_writer=fast_writer, **kwargs)
    686     if writer._format_name in core.FAST_CLASSES:
--> 687         writer.write(table, output)
    688         return
    689

/home/kingj/Software/miniconda3/envs/stableversions/lib/python2.7/site-packages/astropy/io/ascii/fastbasic.pyc in write(self, table, output)
    173         output masked values as empty fields.
    174         """
--> 175         self._write(table, output, { 'fill_values': [(core.masked, '')] })
    176
    177 class FastTab(FastBasic):

/home/kingj/Software/miniconda3/envs/stableversions/lib/python2.7/site-packages/astropy/io/ascii/fastbasic.pyc in _write(self, table, output, default_kwargs, header_output, output_types)
    150         # user kwargs take precedence over default kwargs
    151         write_kwargs.update(self.kwargs)
--> 152         writer = cparser.FastWriter(table, **write_kwargs)
    153         writer.write(output, header_output, output_types)
    154

astropy/io/ascii/cparser.pyx in astropy.io.ascii.cparser.FastWriter.__cinit__ (astropy/io/ascii/cparser.c:15659)()

TypeError: __cinit__() got an unexpected keyword argument 'overwrite'
```

**Comment by cdeil** [comment]
@joleroi - This is expected, `overwrite` doesn't exist in Astropy 1.2.

For now I suggest you put this as a workaround (suggested by @evertrol above):
```
try:
    table.write(filename, format='ascii.ecsv', overwrite=True)
except TypeError:
    table.write(filename, format='ascii.ecsv')
```
and then in a few weeks update to Astropy 1.3 when it comes out and remove that workaround.

**Comment by saimn** [comment]
Looks like this one can be closed, @cdeil ?

**Comment by cdeil** [comment]
OK, closing this issue now. Thanks all for the help!
