### ISSUE TITLE
Need release soon to ensure leap-second fix is available before 2017

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5532]
Just got a note from David Kaplan asking whether the upcoming leap second (31 Dec 2016) would be in astropy. I realised I had to tell him that it would be in 1.3 and in 1.0.11, but that neither of those were likely to be available before the leap second took place. This is no good of course. Any suggestions (for those who use the bundled erfa -- most linux distributions will be fine since one gets the updated erfa automatically). My own sense is that if we do not have 1.3 out before the end of the year, we should have a 1.2.2 with just the erfa update (#5418)

The above does beg the question whether, longer-term, we should get leap second data independently from erfa -- e.g., the IERS tables that we download anyway do contain this information as well.

**Comment by cdeil** [comment]
> The above does beg the question whether, longer-term, we should get leap second data independently from erfa -- e.g., the IERS tables that we download anyway do contain this information as well.

I think yes, it would be good to separate leap second data versions from ERFA / Astropy versions.
It might even be useful to have a mechanism that allows users to provide a new leap second table instead of using the bundled one.

And it would be really good to have a docs section explaining where leap second data is coming from, and also a function to get (e.g. as a Table or dict) and print info about which leap seconds one is using. As far as I can see this doesn't exist yet:
http://astropy.readthedocs.io/en/latest/search.html?q=leap&check_keywords=yes&area=default

I think many codes / telescopes / pipelines are struggling with this, it's a common maintenance nightmare. In the experiment I work for, we have a leap second table in a MySQL database, and in an ascii file bundled with the code. So in principle it is flexible, but in practice most people don't know which version they are using, because there's no docs and no function to print from the pipeline or analysis code which leap second table was actually used and what it contained.

Probably some observatories (like LSST or JWST or ...) have this well figured out, and the same setup / solution could be implemented for Astropy?

**Comment by mhvk** [comment]
To trace the IERS, we should use https://hpiers.obspm.fr/eoppc/bul/bulc/Leap_Second.dat
It is updated in January and July, and has an expiry date.

For reference, `erfa` has its leap seconds at https://github.com/astropy/astropy/blob/master/cextern/erfa/dat.c#L147; I think it would be good at least to expose that.

**Comment by eteq** [comment]
> The above does beg the question whether, longer-term, we should get leap second data independently from erfa -- e.g., the IERS tables that we download anyway do contain this information as well.

Definitely!

> For reference, erfa has its leap seconds at https://github.com/astropy/astropy/blob/master/cextern/erfa/dat.c#L147; I think it would be good at least to expose that.

Now you've hit on the reason why it hasn't happened yet.  I tried to do exactly that, and the way it's currently written, that's a `` static const`` so it isn't *supposed* to be modifiable.  We *could* loosen that constraint in `erfa` and then just inject new leap seconds using the `IERS` data tables (I'm pretty sure either A or B *already* include leap second information). But when I tried to mock this up I got C errors coming out of erfa that I didn't have the time to debug.

**Comment by eteq** [comment]
As for the "underlying" issue, though, definitely 1.3 will be out in time (should be either today or Monday). A new 1.0.x and a 1.2.2 should be out before Dec 31, too...

**Comment by mhvk** [comment]
Indeed, IERS A exposes leap seconds.  Maybe we can try to get this working for 2.0

**Comment by eteq** [comment]
Just finished the 1.0.11, 1.2.2 and 1.3 release now.  Should be on conda and announcements going out tomorrow, so closing this.
