### ISSUE TITLE
Cosmology: Om(z) depends on H0?

### ISSUE THREAD

**Issue by gerrit01** [astropy/astropy#5596]
Hi all,

I just noticed that the evolution of OmegaM seems to depend on the Hubble constant, which I think should not be the case.
```
flcdm = cosmology.FlatLambdaCDM(100,0.3)
print flcdm.Om0,flcdm.Om(1.)
0.3 0.774037106352


flcdm = cosmology.FlatLambdaCDM(10,0.3)
print flcdm.Om0,flcdm.Om(1.)
0.3 0.758856169507
```
The correct value at z=1 should be 
0.77419354838709697

astropy version 1.1.2

**Comment by astrofrog** [comment]
@aconley @nhmc - could you take a look at this? Thanks!

**Comment by aconley** [comment]
Yes, as it should.

That's because the cosmologies specified include relativistic species (photons and massless neutrinos) specified in terms of T_cmb at z = 0, and @gerrit01 is not including that.  The conversion from that to Omegas involves the Hubble constant.  Since H_0 = 10 is a rather extreme value, for that cosmology the contribution of Omega_relativistic to the total is about 0.01, which explains the difference.

If you want something that doesn't depend on H_0, turn off relativistic particles

```
  cos1 = cosmology.FlatLambdaCDM(100, 0.3, Tcmb0=0)
  cos2 = cosmology.FlatLambdaCDM(10, 0.3, Tcmb0=0)
  (cos1, cos2)
```

These both do give the value @gerrit01 expects (or at least pretty close), 0.7741935.

**Comment by gerrit01** [comment]
I see, thanks for the answer!

**Comment by aconley** [comment]
In retrospect, I think we should have defaulted Tcmb to 0 under the theory that we shouldn't include any components the user didn't ask for.  But I'd be worried about subtly breaking code using astropy if we changed it now.

**Comment by saurabhwjha** [comment]
Glad I found this thread; for some applications (e.g., peculiar velocities), it's nice to work with "distances" in km/s, i.e. H_0*d. Setting H_0 = 1 was a shortcut to do this, but I was getting some strange H_0-dependent results. Setting Tcmb = 0 resolves the issue, but also probably means some more careful consideration is required.
