### ISSUE TITLE
Feature request: mix-in column for Table with automatic unicode conversion

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5618]
In Python 3, string columns in tables can take 4x the memory they really need because Numpy ``U<n>`` arrays take up 4x the memory of ``S<n>`` arrays even if only ASCII characters are present.

@embray mentioned (and provided code) in https://github.com/astropy/astropy/issues/4829 that he wrote a ndarray sub-class that stores the data as ``S<n>`` but automatically converts to unicode when the user accesses certain elements. This made me think that we could make this into a mix-in column type for Table. I would imagine the behavior would be as follows when using this type of mix-in column:

* The data would be stored using ``S<n>`` and the encoding would be stored too
* When the user requests an item, it is decoded on-the-fly to unicode (in Python 3)
* When the user sets an item, provided it can be encoded to ASCII, it is encoded into bytes and put back into the array
* If the user sets an item to a unicode string, we could either raise an error with explicit instructions for converting the mix-in column to a full unicode column, or the mix-in column could be smart enough to 'switch' to unicode and emit a warning (to disable the warning, the user would need to explicitly ask for the conversion to be done)

With this in place, readers such as the HDF5 and FITS readers for ``Table`` could automatically make use of this mix-in column type, which would avoid unexpectedly large memory usage when reading in tables with strings.

cc @taldcroft @mhvk

**Comment by taldcroft** [comment]
What we *really* want is an upstream fix in numpy to add a one-character unicode dtype which is encoded as latin1 (probably, or else ascii).  But in lieu of that, a general 👍 to this proposal.

One question is about performance / memory trade-off.  In order to really care about the factor of 4 in memory, you need of order 1 giga-characters (within a factor of a few).  So if the code is actually doing anything with all those strings and using on-the-fly decoding, then it may be very slow.  I can see wanting to re-implement `__eq__` to potentially encode the other operand, but will this start us down a rabbit hole?   Not sure.

**Comment by taldcroft** [comment]
OK, I see that the patch from @embray does re-implement `__eq__` and friends.

**Comment by taldcroft** [comment]
A fix for this is #5700.

**Comment by bsipocz** [comment]
#5700 got released in 2.0, so I'm closing this now.
