### ISSUE TITLE
ENH: Seamless combination of SkyCoord, Table, WCS and fits

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#5626]
Here is some code that does **not** work:
```
In [19]: sk = SkyCoord([-10., 20.], [0, 12], unit='deg')

In [22]: t = Table()

In [23]: t['coo'] = sk

In [24]: t
Out[24]: 
<Table length=2>
   coo   
 deg,deg 
  object 
---------
350.0,0.0
20.0,12.0

In [25]: t.write('temp.fits')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-0d9dc958c365> in <module>()
----> 1 t.write('temp.fits')

/Users/hamogu/anaconda/lib/python2.7/site-packages/astropy-1.3.dev16327-py2.7-macosx-10.6-x86_64.egg/astropy/table/table.pyc in write(self, *args, **kwargs)
   2350         passed through to the underlying data reader (e.g. `~astropy.io.ascii.write`).
   2351         """
-> 2352         io_registry.write(self, *args, **kwargs)
   2353 
   2354     def copy(self, copy_data=True):

/Users/hamogu/anaconda/lib/python2.7/site-packages/astropy-1.3.dev16327-py2.7-macosx-10.6-x86_64.egg/astropy/io/registry.pyc in write(data, *args, **kwargs)
    516 
    517     writer = get_writer(format, data.__class__)
--> 518     writer(data, *args, **kwargs)
    519 
    520 

/Users/hamogu/anaconda/lib/python2.7/site-packages/astropy-1.3.dev16327-py2.7-macosx-10.6-x86_64.egg/astropy/io/fits/connect.pyc in write_table_fits(input, output, overwrite)
    209     """
    210 
--> 211     table_hdu = table_to_hdu(input)
    212 
    213     # Check if output file already exists

/Users/hamogu/anaconda/lib/python2.7/site-packages/astropy-1.3.dev16327-py2.7-macosx-10.6-x86_64.egg/astropy/io/fits/convenience.pyc in table_to_hdu(table)
    447                        if not isinstance(col, table.ColumnClass)]
    448         raise ValueError('cannot write table with mixin column(s) {0}'
--> 449                          .format(mixin_names))
    450 
    451     # Create a new HDU object

ValueError: cannot write table with mixin column(s) ['coo']
```

It would be cool if the writer recognized that a SkyCoord can be transformed into a to normal (non-mixin) columns for Ra and Dec on writing and then add the appropriate WCS to the fits header.

All this can be done manually, but providing functionality like this is a perfect use case where astropy could shine as a unified package not just a collection of mostly independent modules.

How can this be done? My first idea is to add a method to the mixin protocol that returns a list of normal table columns and possibly some meta information that goes into the table header. For SkyCoord or Time the default representation could decide if that method gives ra and dec columns in degrees, in radian, or maybe just a single column as a string. `Table.write` would thne check if mixin columns provide this method and make a temporary copy of the table where mixin columns are replaced with the new regular table columns before writing.

**Comment by mhvk** [comment]
Indeed, maybe this is a good goal for the next release? We do indeed need some default way to write `SkyCoord` (for `Time` a formal FITS definition exists; see #3000). I think with @taldcroft's yaml work, there is a path forward to list classes, perhaps in the comment of fits headers. We may need to discuss with the relevant fits committee...

**Comment by hamogu** [comment]
@mhvk : I think you suggest a good "longterm goal". Anything that involves defining a fits standard is not going to happen for the next few releases. I was thinking about a much simpler solution. I want to preserve *information as much as possible in the existing file standards*, not prserve the full classes. So, if I do `tab.write('filename.ecsv')`, I would get @taldcroft 's complete yaml representation of everything, if I write a fits file, I get a WCS header and two ra, dec columns (which will preserve most, but not all of the information), and if I write in `format='latex'`, I will just get some nicely formatted strings for Ra and Dec (either decimal or sexagesimal, depending on the default represenation of the `SkyCoord` in question).

Because information will not always be complete, this will not round-trip in all formats. We can issue a warning ("Reading file with incomplete definition of coordinate system. Assuming ICRS.") or just put a fat warning in the docs. 

Also, I think we might want to tackle writing first. Information will generally degrade if the file format does not supply a standard way to store all information required to recover the original object. Obviously, we aim for full round-trip capability, but in some cases we might just have to admit that not all files support that. It's not astropy's fault and should not stop us from implementing this at least for writing.

**Comment by taldcroft** [comment]
> My first idea is to add a method to the mixin protocol that returns a list of normal table columns and possibly some meta information that goes into the table header...

Indeed!  I've been spending a fair bit of "background" time thinking along these lines, primarily to support 100% round-tripping of any table to ECSV.  The first step is, as you imagined, making mixin columns a bit smarter about representing themselves.  This means declaring to the parent table that it should be considered as effectively an embedded table (dict of columns) for purposes of representation.  This will all work and is a very high priority for me.

The issue of FITS is thorny.  As mentioned in #3000, putting `Time` into FITS is mostly possible (with the exception of vectorized `location` and custom `delta_*` attributes), but is basically a pretty big project.  GSoC 2017 will be here before we know it...    For `SkyCoord` is there a relevant standard for rich coordinate tabular data in FITS?  In any case FITS is not my priority.

**Comment by eteq** [comment]
> is there a relevant standard for rich coordinate tabular data in FITS

As far as I know, there is not, because there are pretty much no official FITS standards for tables other than the actual table HDU itself.  *but* it would be pretty straightforward to write a "good enough" format, which would  automatically use the default representation names (or only lat/lon  if a UnitSphericalRepresentation) as the columns, and then write out the frame attributes in appropriately-named `meta` entries.  That might be a bit tricky for some of the more obscure situations where the frame attributes are themselves something complex... But I've hacked together ways to deal with that in the past.

>> My first idea is to add a method to the mixin protocol that returns a list of normal table columns and possibly some meta information that goes into the table header..
>
> I've been spending a fair bit of "background" time thinking along these lines

Great!  I would love to see that feature too.  I independently have had this same idea as @hamogu and @taldcroft apparently did, so the wisdom of crowds would seem to suggest this is a good way to go 😉

**Comment by hamogu** [comment]
Sounds like we have a GSoC project on out hands...

**Comment by taldcroft** [comment]
BTW, if we feel free to invent our own standard for storing objects in FITS, then the sky is the limit (no pun intended)!  I had always thought was discouraged since of course when everyone uses their own standard then FITS becomes a little less useful.  But then I found some precedent by way of a method for [storing arbitrary AST objects in FITS](http://www.starlink.rl.ac.uk/docs/sun211.htx/sun211se16.html).  Hmmm, sounds familiar...

**Comment by mhvk** [comment]
There is certainly precedent of organisations having forced the issue (ESO's `HIERARCH` structure for longer names, STScI...). But we should consult where possible, and can at least start by implementing things that *do* exist... (`Time` -- #3000).

**Comment by taldcroft** [comment]
Oh yeah, essentially what we will need is a way to store an arbitrarily long ASCII string inside the FITS table header.  This should be possible using carefully constructed COMMENT cards.  Then one basically uses the ECSV definition (actually the not-quite-yet-existent ECSV 1.0 definition) to serialize all required metadata into a single YAML string.  So if we are willing to just do it (define a standard for storing Astropy objects in FITS), then this won't be nearly enough work for a GSoC project.  :smile:

**Comment by taldcroft** [comment]
@mhvk - ah yes, Time.  That will be the rub, since doing Time like I just said will come for *free*, while doing it the right way is indeed something approaching at least half of a GSoC project...

**Comment by taldcroft** [comment]
And our Time object is richer than the existing FITS standard.

**Comment by mhvk** [comment]
We do need to do `Time` right, I fear, if only since we will at some point need to *read* fits files with time information written by other packages (and once you have a reader, adding a writer is not so much work any more; indeed, it may be the best way to ensure your reader is correct...). But, yes, we also need to get metadata serialized.

**Comment by mhvk** [comment]
> And our Time object is richer than the existing FITS standard.

Is it really? What specifically did they miss? (Best to add as a comment to #3000, so we can keep track...)

**Comment by hamogu** [comment]
@mhvk @taldcroft : This discussion is running of into the direction of "the perfect format that stores all mate data and round-trips". Yes, that would be nice, but most people don't need that. A couple of examples where less than perfect is really good enough:

- Latex output for publication: Imagine a Ra, Dec list of objects I found. The latex table needs to have two columns called "ra" and "dec", but can throw away epoch and equinox. That's going to be given in article text or hand-written figure caption.
- Multiple inputs, one output: I have several data catalog in possibly different coordinate systems. Then I convert all to the same system with astropy (e.g. ICRS). Now, I save the intermediate table and will continue to work on it tomorrow using ds9/ciao/montage/something else that does not understand the astropy format you are about to invent. I know it's ICRS and if I forget a human readable header keyword entry is enough. I need to columns Ra, Dec, but no meta-data because my other program won't understand that anyway.
- I have data from a small 1.2 m telescope. Images don't have a good WCS because the pipeline was handwritten by some student in IDL many years ago. I identify some objects and estimate coordiantes of the others. Again, Ra, Dec is good enough, I don't really know the other meta data to begin with.

I could make a similar list for examples where I really want a time column, but don't care about the details that the fits standard forgot to implement.

Again, I don't want to intentionally degrade the capabilities of astropy, but "Now is better than never.".

**Comment by taldcroft** [comment]
@hamogu - I agree fully that "perfect is the enemy of good", it's one of my mantras.  But in this case putting the full meta-data as comments into a file format where it can be supported (e.g. ECSV or FITS) is really easy, so why not do it.  

The real work here is defining a formalism where a mixin column has a definition of its subcolumns so that downstream functions automatically get the right thing.  This is not very tricky but has to be done right.  Anyway, this is all basically my highest priority for 2.0, so barring unforeseen circumstances it will get done.  And I am fairly obsessed with round-tripping whenever possible, so that will just happen as a by-product whether or not you need it.  :smile:

It might kill you to know that probably the *hardest* part of what I'm working on is just *printing* a table, because it will support arbitrarily nested columns.  In other words you will be able to have a table column that is itself a table.  So I need to rework `pformat` a fair bit.

**Comment by mhvk** [comment]
@hamagu - very good points. For `SkyCoord` in particular, it means we have to ensure we stick to the (more or less) obvious, i.e., use fits table columns named `ra`, `dec` rather than try to define a supposedly smart way of storing both in a `2D` column. As far as I can see, though, this is what @taldcroft is aiming for as well -- just wrap things that fits cannot easily handle in strings  that are stored as `COMMENT`.

@taldcroft - I 'm definitely game for trying to help here (just wish I understood FITS a bit better...)

**Comment by taldcroft** [comment]
> use fits table columns named ra, dec

This will probably come up later, but my working plan was that for a coordinate column named `sc`, one would end up with table columns named `sc.ra` and `sc.dec`.

**Comment by hamogu** [comment]
"sc" for "Such a Column"?

**Comment by taldcroft** [comment]
I commonly use `sc` for a SkyCoord.

**Comment by hamogu** [comment]
I added this as a GSOC idea to https://github.com/astropy/astropy/wiki/Google-Summer-Of-Code-2017-Project-Ideas Please improve the text there and volunteer as a mentor ;-)

**Comment by taldcroft** [comment]
Re the GSoC project, would it make sense to add a (major) component of addressing #3000?  It is still my full intention to personally do the ASCII / ECSV component of this for astropy 2.0.

**Comment by hamogu** [comment]
Yes, I think #3000 should be part of this.

**Comment by swapsha96** [comment]
I am computer science student who has experience with FITS file and very interested to work on Astropy by OpenAstronomy under Google Summer of Code '17. Currently I am working on STScI project, 3D-HST data extractor and API interface with Dr. Ivelina Momcheva (Mentor) and Mr. Ayush Yadav (full stack developer). During this project, I developed a new endpoint in which I used various Python libraries to provide pictures of the object from actual 3D-HST observation from FITS files. For example, image of COSMOS.1296.V41 (http://narwhal.astro.yale.edu/singleobject?id=cosmos.1296.v41) captured by F160W filter (http://narwhal.astro.yale.edu/morphology/cosmos/1296/H/image).

Can you tell me what can I do right now to gain creditability? Is there any task that I can perform or something you want me to work on?

**Comment by mhvk** [comment]
@swapsha96 - thanks for your interest!  I think arguably the best issue related to this to start with is #3685 -- it describes where the problem is but it will need a logical implementation and good test cases.

More generally, be sure to
- Read the [Astropy guidelines](https://github.com/astropy/astropy/wiki/GSoC-2017-Guidelines) and [OpenAstronomy guidelines](http://openastronomy.org/gsoc/student_guidelines.html).
- Fill in the student application form.

**Comment by taldcroft** [comment]
The original example in this issue now works without problems.  I can't speak for WCS, but I would say that astropy now largely achieves the original goal of "Seamless combination of SkyCoord, Table, WCS and fits".

@hamogu - can we close this?

**Comment by hamogu** [comment]
Sure. I'll close this and, should I run into something similar will open a new issue.
