### ISSUE TITLE
Better document ASCII reader for files with both tab and space delimiters

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5666]
EDIT: Just make the documentation more obvious is enough. See discussions below.

During the [Using Python for Astronomical Data Analysis](https://aas.org/meetings/aas229/events#workshops) workshop, there was an issue with an ASCII file using both tab and space separators. `pandas` could read it fine, but `Table.read(..., format='ascii')` threw an error until @eteq dug through the documentation and set delimiter to `\s`, leading to the thought that perhaps it is better to make that the default behavior.

p.s. Erik, I hope you don't mind that I opened this issue on your behalf.

**Comment by taldcroft** [comment]
Without more convincing I'm :-1: on this.  As with Python source code, mixing tabs and space is just a bad idea.  Changing the default behavior of the ASCII reader should not be taken lightly because it can easily break code.  For instance a tab separated file can have unquoted spaces so you get ambiguity about how to parse.

But certainly better docs about reading this kind of file would be useful.

**Comment by pllim** [comment]
@taldcroft , good point! Yes, just improving the documentation about this would also help.

**Comment by rahul-kumi** [comment]
I would like to work on this issue, @pllim could you please guide me with the essentials.

**Comment by pllim** [comment]
@rahul-kumi , http://docs.astropy.org/en/latest/index.html#developer-documentation should tell you how to contribute.

As for *where* to add the documentation, I think it should be somewhere in http://docs.astropy.org/en/latest/io/ascii/read.html . However, @taldcroft might have a better idea on exactly where.

**Comment by pllim** [comment]
Haven't seen a PR for this, so I'll submit one shortly.
