### ISSUE TITLE
Skycoord __getitem__ not being applied to frame attributes

### ISSUE THREAD

**Issue by dmopalmer** [astropy/astropy#5743]
I have a bunch of observations of the same object at different times (e.g. for an asteroid).  According to the [SkyCoord documentation](http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html)
`Inputs may be scalars or lists/tuples/arrays, yielding scalar or array coordinates (can be checked via SkyCoord.isscalar).`

So I assumed that I could have a coordinate array with the ra,dec and obstime inputs being lists:
```
path=SkyCoord([5,10],[20,30],unit=u.deg,obstime=['2017-01-01T00:00','2017-01-01T00:10'])
```

This initially seems to work:
```
In[14]: for i in range(len(path)):
...         print(path.ra[i],path.dec[i],path.obstime[i])
... 
5d00m00s 20d00m00s 2017-01-01T00:00
10d00m00s 30d00m00s 2017-01-01T00:10
```
but it actually doesn't
```
In[15]: print(path[0].obstime)
['2017-01-01T00:00', '2017-01-01T00:10']
```

And things can go bad in other ways.  The conclusion is that you can't have multiple obstimes in an array coordinate.

So to clarify the documentation, I suggest adding the word:
`**Coordinate** inputs may be scalars or lists/tuples/arrays, yielding scalar or array coordinates (can be checked via SkyCoord.isscalar).`

**Comment by taldcroft** [comment]
@dmopalmer - that's a bug!

@mhvk - The `_apply` method (which implements `__getitem__`) indicates that this should work:

        It will be applied to the underlying arrays in the representation (e.g., ``x``,
        ``y``, and ``z`` for `~astropy.coordinates.CartesianRepresentation`),
        as well as to any frame attributes that have a shape, with the results
        used to create a new instance.

**Comment by mhvk** [comment]
That's no good indeed.  There is actually something else that is weird:
```
path=SkyCoord([5,10],[20,30],unit=u.deg,obstime=['2017-01-01T00:00','2017-01-01T00:10'])
path.obstime
# ['2017-01-01T00:00', '2017-01-01T00:10']
type(path.obstime)
# list
```
I would have thought this would have been translated to `Time` internally (this certainly is suggested by the `SkyCoord` docstring). Obviously, a `list` cannot be sliced like a numpy array! But doing that explicitly doesn't change the bug...

Looking further, it seems clear the underlying problem is that `obstime` is not a "normal" frame attribute for ICRS coordinates. If I change the frame to one in which it is, it does work:
```
path=SkyCoord([5,10],[20,30],unit=u.deg,obstime=['2017-01-01T00:00','2017-01-01T00:10'], frame='fk4')
type(path.obstime)
# astropy.time.core.Time
path[0].obstime
# <Time object: scale='utc' format='isot' value=2017-01-01T00:00:00.000>
```

Indeed, looking a `SkyCoord.__init__`, I see that there are two ways things get initialized: all attributes get stored in their own name prefixed by `_` just as they were given [first](https://github.com/astropy/astropy/blob/master/astropy/coordinates/sky_coordinate.py#L215), and then those that are actually needed for a given frame are passed on (and validated/converted) by the frame itself [next](https://github.com/astropy/astropy/blob/master/astropy/coordinates/sky_coordinate.py#L222)

I must admit that I don't know how best to solve this... @taldcroft - since you wrote this, any suggestions? It seems hard to avoid breaking the "separation of concerns" here and have `SkyCoord` acquire some knowledge about attributes that are not always needed (i.e., it should validate/convert at least `obstime` and `equinox`, rather than leave those to the frame).

**Comment by dmopalmer** [comment]
If frame attributes are allowed to have shape, then there is at least one other bug (which is where I actually found the problem):
```
obst1 = SkyCoord(10, 20, unit=u.deg, frame=FK5, equinox='J2000', obstime=Time('2017-01-01T00:00'))
obst2 = SkyCoord(11, 21, unit=u.deg, frame=FK5, equinox='J2000', obstime=Time('2017-01-01T00:10'))
obst12 = SkyCoord([10,11], [20,21], unit=u.deg, frame=FK5, equinox='J2000', obstime=Time(['2017-01-01T00:00','2017-01-01T00:10']))

print(obst12.is_equivalent_frame(obst2))
```
raises
```
/Users/palmer/anaconda/envs/astro/lib/python3.5/site-packages/astropy/coordinates/sky_coordinate.py in is_equivalent_frame(self, other)
    638
    639             for fattrnm in FRAME_ATTR_NAMES_SET():
--> 640                 if getattr(self, fattrnm) != getattr(other, fattrnm):
    641                     return False
    642             return True

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

As the error message says, wrapping the comparison with a numpy.any() should fix that particular error message, but I don't know where else the equivalent bug resides in the code.

**Comment by mhvk** [comment]
@dmopalmer - a solution to your particular case (possibly even a better one) may be to use a `QTable` with `obstime` and `coordinate` columns.

**Comment by mhvk** [comment]
@dmopalmer - yes, that should have an `any()`... Definitely a problem with writing the multi-D code but never quite having had the time to make higher-order tests...

**Comment by dmopalmer** [comment]
@mhvk I just tried a Table.  I might get it to work but #5745 came up immediately.

But a table of obstime (adding the Times individually, or leaving them as datetime.datetimes), ra, dec (not SkyCoord) values would probably work for my actual use case.

**Comment by taldcroft** [comment]
@mhvk - I think this is a variant of #5749 and that one solution is indeed violating separation of concerns by having the `Frame` object get a `parent` attribute (a weakref) that let's it look skyward and see other attributes that need to be included in `_apply`.  Restricting `Frame` objects to strictly the attributes required for that frame was not my first choice, but that was the driver for creating `SkyCoord` and I think we can deal with it.

Note that for *this* issue, we could probably manage without a `parent`, but I don't see how to fix #5749 cleanly without it.

**Comment by mhvk** [comment]
Maybe we can keep things separately still? Since `obstime` can be passed in explicitly for a `SkyCoord`, I don't think it would be strange at all to have its default be whatever it finds on a `frame`, if that is given. And I think it would make sense to extend this to all possible frame attributes: if we pass on `obstime`, why not relative humidity, etc. Just to see where this goes, I think all it would need:
1. `__init__` to treat all frame attributes as defaults for keyword arguments;
2. `__init__` to not just recognize attributes that do not belong to a frame, but also properly initialize them (convert strings to `Time`, etc.); for this, we'd have to change our (cached; #5703) `frame_attrnames_set` into a `dict` with also the appropriate `FrameAttribute` class -- since it is constructed from such dictionaries, this should be trivial);
3. `_apply` to also work on any attribute that `SkyCoord` has but that is not on the frame.

I think with this no weak link to the parent would  be required, especially if one indeed allows the `frame` argument to be given a `SkyCoord`.

**Comment by mhvk** [comment]
p.s. I think the idea above is working....  hope to have PR semi-soon.

**Comment by taldcroft** [comment]
@mhvk - I was thinking more about this and agree that `parent` is not needed.  In my thinking the solution for this issue would only be your point (3).  

This could be done pretty straightforwardly by refactoring the attribute handling in `BaseFrame._apply` into a common function that does the `apply` to all appropriate attributes (where a dict of attributes would be an input to the refactored function).  Then us that new common function in `SkyCoord._apply` as well.

About the "properly initializing" frame attributes that do not belong to a frame, that doesn't quite make sense to me.  Say I make a ICRS SkyCoord with an`obstime` attribute.  There is no unambiguous way to determine the right type for that attribute since multiple frames define that attribute.  It happens they are all `Time` but that is not a requirement, e.g. a frame could use a specialized `Time` subclass.

Anyway, the initialization of `SkyCoord` is already very complex because it tries to make sense of multiple inputs providing overlapping information.  I'm a little wary of too much fiddling with the front-end `__init__`.

**Comment by mhvk** [comment]
@taldcroft - the problem is that one cannot write a generalised `apply` unless all the attributes are guaranteed to be `FrameAttribute` classes (or, more precisely, either `ndarray` or `ShapedLikeNDArray` subclasses). My own sense here is that if someone wants a different attribute, they'd have to create a new `FrameAttribute` with a new name, at least if it is also intended to be compatible with being carried over from one frame to another.

Anyway, I think I'll have a possible implementation fairly soon, so we can discuss based on actual code!

**Comment by mhvk** [comment]
See #5751 for a fix.
