### ISSUE TITLE
Support programatic leap seconds

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#5783]
Currently, there's no way for `astropy` to programmatically change what the leap-seconds are, because the leap seconds are accessed through ERFA.  This is problematic because it means when there's a new leap second we have to do a bugfix release.

The fix in Astropy itself would be pretty easy, as it can be extracted from the IERS files that we already are using for DUT1 and such.  But the non-trivial part is updating ERFA to have an interface for setting the leap second - see liberfa/erfa#43 for discussion on that.  

cc @mhvk

**Comment by eteq** [comment]
At the astropy coordination meeting, @adrn, @timj, @stargaser, et al. decided this is a good thing to prioritize for 3.2 (which means working on the `liberfa` fix asap).

**Comment by bsipocz** [comment]
ping @eteq - would you say at this point it's realistic to remilestone for 4.0?

**Comment by mhvk** [comment]
After discussion with @eteq: The plan now is to add the ability @jwoillez created to [load custom leap seconds into erfa's `dat.c`](https://github.com/liberfa/erfa/pull/49) into astropy's version, so that we can experiment with it - in particular update it as needed based on the IERS tables (from `IERS_Auto` by default). Then, with the interface worked out, we can push it back up to `liberfa` so that it is more generic and can be used elsewhere.

**Comment by bsipocz** [comment]
Is this now fixed with the ERFA update?

**Comment by mhvk** [comment]
@bsipocz - no, not yet, we now have in principle the ability to update the leap second table, but we still need to put in place the machinery to get that updated table.

**Comment by astrofrog** [comment]
Was this done in https://github.com/astropy/astropy/pull/9365?

**Comment by mhvk** [comment]
Yes, fixed!
