### ISSUE TITLE
Making the str equivalent of the dimensionless_unscaled unit more discoverable

### ISSUE THREAD

**Issue by jonathansick** [astropy/astropy#5850]
We're using `astropy.unit` in a context where we want every value to be an astropy `Quantity`. We're also serializing definitions of the things we're measuring in YAML, so we're making heavy use of the string representations of astropy `Unit`s. Some of these things have intrinsically `dimensionless_unscaled` units, so we're seeing a lot of:

```yaml
unit: ''
```

in our YAML files. While `unit: 'mmag'` → `Unit('mmag')` is easy to understand, my colleagues have asked a lot of questions about these "empty string" units.

So I'm wondering if we can improve the UX of the string representations of `dimensionless_unscaled` units a bit. I have two ideas:

- Make the string `'dimensionless_unscaled'` an alias for the string `''` so that we can write `'dimensionless_unscaled'` in text serializations of `Unit`s.
- Improve the discoverability of the `dimensionless_unscaled` in the documentation. Most units are featured in a nice table on the package page (http://docs.astropy.org/en/stable/units/index.html) but `dimensionless_unscaled` is only explicitly mentioned on a deeper topic page (http://docs.astropy.org/en/stable/units/standard_units.html#the-dimensionless-unit) and even then its string representation is only mentioned in passing.

What does astropy think about these proposals? I'm happy to turn this into a PR if one or both of these ideas seem useful.

**Comment by pllim** [comment]
Not that this will be less confusing but you can also initialize dimensionless unit this way:
```
>>> from astropy import units as u
>>> u.Unit('1')
Unit(dimensionless)
>>> u.Unit('1') is u.dimensionless_unscaled
False
>>> u.Unit('1') == u.dimensionless_unscaled
True
```

**Comment by jonathansick** [comment]
Thanks @pllim, I didn't realized that `Unit('1')` also worked, not just `Unit(1)`. It'd be worth adding that to the "documentation improvement" aspect of this issue.

**Comment by mhvk** [comment]
I think using `'1'` would indeed seem the best. I note that this is also what the fits people told me when I asked how to represent logarithmic dimensionless units (fits allows `log(Jy)` and they suggested `log(1)` rather than `log()`)

On the documentation: the dimensionless unit is indeed a bit of an outlier, in that unlike all other units it is cannot be defined easily in terms of base units, and therefore is not automatically picked up for the lists, etc. Suggestions for where to document it so that people will find it most welcome!

**Comment by parejkoj** [comment]
Getting back to this now: how is `'1'` better than `''`, as far as clarity for someone reading a description of a `Quantity`?

Definitely at least getting `''` and `dimensionless_unscaled` on the main units page, possibly in a short section to itself, would be a good start.

**Comment by pllim** [comment]
> how is '1' better than ''

I am not arguing that it is. I agree that having a more description init string can be helpful as well. A PR is certainly welcome.

**Comment by pllim** [comment]
Revisiting this again, I don't think making `Unit('dimensionless')` to be same as `Unit('')` work is worth it. This is because

https://github.com/astropy/astropy/blob/ba2e4a74a97835279b9cae4553116fbd2007ac17/astropy/units/core.py#L2058-L2062

shows that unit can be dimensionless and have different scales. Since `Unit(1)` already works for you and it has been 2 years, maybe that is sufficient?

**However**, I agree that dimensionless unit doc in [Getting Started](https://astropy.readthedocs.io/en/latest/units/index.html#getting-started) can be expanded a little to include `Unit(1)` example and a link to [The dimensionless unit](http://docs.astropy.org/en/latest/units/standard_units.html#the-dimensionless-unit) section. @tcjansen , do you want to take a stab at the doc?

**Comment by tcjansen** [comment]
@pllim - Yes, I actually had a similar confusion with the documentation recently so I'd be happy to give it a shot!

**Comment by parejkoj** [comment]
Thanks @tcjansen : that new documentation is helpful!
