### ISSUE TITLE
Column names not preserved when initializing Table from a list of Rows

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5923]
The following code:

```python
import numpy as np
from astropy.table import Table

t1 = Table()
t1['a'] = [1,2,3]
t1['b'] = [2.,3.,4.]

print(t1)

rows = []
for row in t1:
    rows.append(row)

t2 = Table(rows=rows)

print(t2)
```

illustrates that column names are lost:

```
 a   b 
--- ---
  1 2.0
  2 3.0
  3 4.0
col0 col1
---- ----
   1  2.0
   2  3.0
   3  4.0
```

Of course, this isn't the recommended way of getting a Table subset, but I think that it's nevertheless a bug?

**Comment by taldcroft** [comment]
Yup, that does look like a bug.

**Comment by nancyirisarri** [comment]
I think it happens because of the way that you make `t2`. I suppose that the flexibility of being able to make a table from many types of input, such as a `list` as you do, outweighs the loss of column names. If you want to keep the column names you could make `t2` in this way:
`
t2 = Table(rows=rows, names=t1.colnames)
`

You instantiate a `Table` and pass a value to the argument `rows`. If I understand the `Table` source code correctly, this means that the following line is executed: [link to line in Table](https://github.com/astropy/astropy/blob/master/astropy/table/table.py#L281
). There the function `recarray_fromrecords()` is invoked. If I understand that code correctly, then this line [link to line in `recarray_fromrecords()`](https://github.com/astropy/astropy/blob/master/astropy/table/np_utils.py#L197) eventually calls code in `Row` where the column names are lost [link to line in `Row`](https://github.com/astropy/astropy/blob/master/astropy/table/row.py#L92).
