### ISSUE TITLE
fits.open() doesn't support compression on already open file-handles

### ISSUE THREAD

**Issue by astrogreen** [astropy/astropy#5948]
When opening a FITS file on disk by providing the path string:
```python
fits.open("my_file.fits.gz")
```
compression in the files is handled automatically. This is taken care of by the `_File` class, which appears to check either for the '.gz' extension or for the right "magic" number at the start of the file.

However, this logic is not present when using a file handle, e.g.:
```python
file_object = open("tmp.fits.gz")
f = fits.open(file_object)  # raises IOError
```

Here is a MWE:

```pthon
from astropy.io import fits
import numpy as np

# Create gzipped fits file:
fits.PrimaryHDU(np.random.random((20, 20))).writeto("tmp.fits.gz")

# Open using the usual way (no errors):
f = fits.open("tmp.fits.gz")

# Open using a filehandle:
file_object = open("tmp.fits.gz")
f = fits.open(file_object)  # raises IOError
```

See http://stackoverflow.com/questions/43220542/how-to-open-a-remote-fts-gz-file-with-astropy-io-fits-open for a particular use-case.

**Comment by drdavella** [comment]
I created a unit test for this issue on a [topic branch](https://github.com/drdavella/astropy/tree/fits-compression). In order to implement this in a reasonable way, it will be necessary for `fits.open` to make sure that all file handle arguments have been opened in binary mode. This is because in order to test whether the file represents compressed data, it will be necessary to read at least a portion of the file (either to test for a magic value or to do a trial decompression). However, if the underlying file handle was not opened as a binary file, it will not be possible to read the file since the encoding is assumed by default to be UTF-8, and compressed binary data will not decode.

I suppose it is also possible that if the file is not opened in binary mode, then `fits.open` will not attempt to check whether the file was compressed, so it will simply fail to process a compressed file in those cases.

**Comment by drdavella** [comment]
It's also worth mentioning that detection of compressed data is not entirely reliable (see [these](https://stackoverflow.com/questions/19120676/how-to-detect-type-of-compression-used-on-the-file-if-no-file-extension-is-spe) [answers](https://stackoverflow.com/questions/13044562/python-mechanism-to-identify-compressed-file-type-and-uncompress) on stackoverflow) and trial decompression of an entire file could be fairly expensive.

**Comment by pllim** [comment]
@drdavella , thanks for the input! Feel free to open a PR with your proposed change if you want. Even if it ends up not being merged, it serves as a spot for discussion and future reference.

**Comment by drdavella** [comment]
I've made progress towards a solution but it needs some cleanup and some additional unit tests. Should I wait until I'm a little further along or go ahead and open a PR now?

**Comment by pllim** [comment]
I'll leave that up to your judgement. People have opened WIP PRs here, so there are precedents. Just remember to put "[ci skip]" in commit message to skip CI if it's not ready.
