### ISSUE TITLE
Attribute "FWHM"?

### ISSUE THREAD

**Issue by ysBach** [astropy/astropy#5980]
I have realized that `Fittable1DModel` and `Fittable2DModel` (including Gaussian and Moffat) has no attribute of `FWHM`, while quite many of them actually need it for astronomical purposes. 

A built-in function `astropy.stats.gaussian_sigma_to_fwhm` can be used only for Gaussian, while we need much more functions' FWHM values in practice.

I guess it will be very useful if we have something like attribute to calculate FWHM.

**Comment by MSeifert04** [comment]
I think this has already been proposed but I can't find where. 

I actually like the idea about a FWHM property on these classes. 👍

**Comment by nden** [comment]
While I have no preference, I think this comes up often enough that the reasoning behind the decision to go with stddev instead of fwhm should be documented somewhere (the original definition of Gaussian was in terms of fwhm). I'll try to find the discussion and link to it here. This doesn't mean we can't  add a property, it's just good to know the original motives.

**Comment by nden** [comment]
#1077 lists some reasons behind the decision to remove `fwhm` altogether from the Gaussian model.

**Comment by ysBach** [comment]
@nden Oh thanks for letting me know the previous issue! I kind of understand the reason for the removal of `fwhm`.

But since the relationship between sigma (`stddev`) and FWHM is not the same for all different functions, it is quite bothersome to make my own function which converts sigma to FWHM and vice versa. I cannot find some important functions which needs FWHM other than Gaussian and Moffat, (Lorenz has infinite sigma so excluded) but still I want to have some feature for Moffat at least, which is very useful in astronomical image reduction. Only Gaussian is supported via `astropy.stats.gaussian_sigma_to_fwhm` as of now, which seems too specific for me.

We might have a function like `astropy.stats.calc_fwhm` and it gets the model as `astropy.modeling.FittableModel`, which contains all the parameters (`amplitude`, `mean`, and `stddev` for Gaussian1D, `amplitude`, `x_0`, `y_0`, `gamma`, and `alpha` for Moffat2D, etc). Then the desired FWHM can be given based on the model type.

```python
gauss1 = models.Gaussian1D(amplitude=1, mean=1, stddev=1)
moffat2 = models.Moffat2D(amplitude=1, x_0=0, y_0=0, gamma=2, alpha=2)
calc_fwhm(gauss1) # gives 2.35...
calc_fwhm(moffat2) # gives array([2.574..., 2.574...])
```

By the way, this reminded me of the fact that elliptical Moffat is not supported via Astropy...

**Comment by nden** [comment]
Since this came up several times I think it's worth revisiting the issue. Pinging everyone who weighed in on the decision originally - @cdeil @astrofrog @eteq . 
Are you opposed to having a `fwhm` property in models while still using `stddev` as the fittable parameter.

**Comment by pllim** [comment]
+1 to FWHM. I have to subclass Gaussian1D to use that currently.

**Comment by cdeil** [comment]
What's the proposal exactly? Would `fwhm` just be a property that returns a multiple of `stddev`?
I think that could be a nice convenience.

A separate `calc_fwhm` function with a hard-coded list of models would be an inferior solution compared to adding the `fwhm` computation on the classes that support it's computation, no? (A standalone function would require a registry to be extensible to new built-in and user-defined models.)

Or would `fwhm` do more, like have a setter that modifies `stddev`, or be optionally allowed in `__init__` or even other things how it interacts with the class? I think on that I'm -1 (or at least would like to see the full proposal first) because of the extra complexity it introduces.

**Comment by nden** [comment]
I suggest we take a minimal approach because it can easily get complicated. 
For all models for which this makes sense, have a getter property `fwhm` which computes `fwhm` from `stddev`. `fwhm` is not going to be a settable property and not allowed in `__init__`.

**Comment by cdeil** [comment]
@nden - I'm +1 on that addition.

And in general there can be other properties of interest on models in the future if very commonly used. If they are getter-only properties they don't add complexity to the overall class and are simple to add  and write a test for. The initial problem and why we removed `fwhm` years ago was that it was optionally allowed in `__init__` and that was causing complex initialisers and bugs.

**Comment by pllim** [comment]
> Or would `fwhm` do more, like have a setter that modifies `stddev`...?

#4936 was proposed along this line and was shot down pretty fast.

**Comment by pllim** [comment]
Potential fix in #6027

**Comment by pllim** [comment]
@ysBach why did you close the issue? Are you retracting your request?

**Comment by ysBach** [comment]
Oh I'm so sorry. 
I thought the "potential fix" meant the issue should be closed (as I am still quite new to Github).
I am not retracting, so I guess I must not close this. Sorry for confusion.

**Comment by bsipocz** [comment]
@ysBach - We usually keep issues open until the fixes are merged. In most cases the merge will auto-close them.
