### ISSUE TITLE
Extraneous frame attribute mumbojumbo in StaticMatrixTransform

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6044]
@eteq and I think [this and following lines](https://github.com/astropy/astropy/blame/master/astropy/coordinates/transformations.py#L780) might be vestigial. 

cc @mhvk

**Comment by eteq** [comment]
Just to clarify a bit more: in a very early version of the coordinates machinery, the transform functions were responsible for carrying frame attributes forward.  Now that happens in `SkyCoord`.  But the static matrix machinery seems to have the old form.  Probably this was never noticed because it's only in the galactic<->supergalactic transform, which has no frame attributes.
