### ISSUE TITLE
Shortcut for Quantity q.to(unit).value?

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#6125]
First, is there a shorter way to do `q.to(unit).value` where `q` is a `Quantity`.

If not, could we make one?  For instance `as`?
```
q = 1 * u.m
q_km = q.as(u.km)
```

**Comment by mhvk** [comment]
There is a mechanism to access values in a given unit by a corresponding attribute; this is turned off by default but used in `Angle`:
```
q = 1.*u.m
q._include_easy_conversion_members = True
q.km
# 0.001
```
We had a (very) long discussion about this, and I don't think I'd want to include this by default (try to do tab-completion on `q` after doing the above example... `len(dir(q))` gives 628...), since in typical usage one would (hopefully) never want to convert to straight arrays, especially once speed considerations have largely disappeared (which they will have with numpy 1.13, with long-delayed introduction of `__array_ufunc__`; see my PR #2583). Though one option would be to make the default configurable or allow enabling within a context.

What might be a better option is to expose the `getter` for the `.value` property, and define it such that one can give a unit. This could then even be used within the `.to` method. It would be something like:
```
def get_value(unit=None, equivalencies=[]):
    value = self.view(np.ndarray)
    if unit is not None:
        new_val = self.unit.to(unit, value,
                               equivalencies=equivalencies)
    if self.shape:
        return value
    else:
        return value.item()

value = property(get_value)

def to(self, unit, equivalencies=[]):
    return self._new_view(self.get_value(unit, equivalencies), unit)
```
I particularly like that this would just reorganize code, not introduce more. Would this be a solution?

A final alternative, depending on what exactly you want this for, is the function decorator that was discussed some time ago, to help with general code that uses arrays internally, which, like `quantity_input`, allows you to define what units input should be in, but returns array views of quantities converted to that unit instead of just checking that the input has a consistent unit.

**Comment by mhvk** [comment]
p.s. for the property getter solution, of course we're free to call the getter anything we want. I'd use `in` if it weren't a reserved keyword; perhaps `to_value(unit)` or `value_in(unit)` is clearer than `get_value(unit)`.

**Comment by taldcroft** [comment]
Sounds good, thanks!  :+1: for `value_in` as that will be close in the tab-completion list.

**Comment by mhvk** [comment]
@taldcroft - with the many replacements that suddenly became possible (see #6137), it is quite clear that this is useful to have, despite my initial doubts; a few things will even become faster! And, of course, with this the decorator should be even simpler to implement.
