### ISSUE TITLE
Update GaussianAbsorption1D

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6195]
The GaussianAbsorption1D needs to be updated in one of two ways:

- Either the continuum level should be made a parameter so that the model can be used with units

or

- The model should be deprecated if we think no one is using it

See https://github.com/astropy/astropy/pull/6183/files#r121763241 for some discussion.

**Comment by pllim** [comment]
I just blasted `astropy-dev` mailing list about this. I propose we just deprecate it if we don't hear strong objection by Friday. AFAIK no one is using it and I didn't find it terribly useful with composite model and unit support now.

**Comment by astrofrog** [comment]
@pllim is... THE DEPRECATOR 😆

**Comment by pllim** [comment]
"I'll be back!"

![Terminator](http://tailgate365.com/wp-content/uploads/2012/08/The-Terminator.jpg)

**Comment by adrn** [comment]
👍 to deprecate + remove!

**Comment by bsipocz** [comment]
Having a quick github search, it seems that a few people are using it, most notably https://github.com/spacetelescope/specview
However they should get plenty of warning with the deprecation, so 👍 to go for it.

**Comment by pllim** [comment]
"specview" is defunct, so don't worry about it. :smile:

**Comment by hamogu** [comment]
It is a common use case to fit absorption lines, but as the linked discussion above points out this can be done as `constant - absorption model`. Maybe this can be one example in the docs? It's a common use case, and the deprecation warning could even point to it.

(As an aside, this issue is exactly why I have not used astropy models in any science or production code: It just changes too fast, so I have to spend too much time just to keep up with astropy changes. I hope that settles down after 2.0.)

**Comment by pllim** [comment]
@hamogu , Python itself changes too. You can always pin your Astropy requirement to a LTS until you have time to catch up. As discussed in the given link above, `GaussianAbsorption1D` as-is cannot support units. And I did mention that you can use `Const1D - Gaussian1D` in the deprecation message. Hope this clarifies the issue.
