### ISSUE TITLE
Galactic cartesian components (uvw/UVW) are incorrectly named

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#6328]
In v1.3 and master, the component names / mappings are: w -> x, u -> y, v -> z

AFAIK, this is wrong. It should be: u -> x, v -> y, w -> z

cc @eteq

**Comment by adrn** [comment]
FYI: from git blame, it looks like this goes all the way back to the first commit of `Galactic`

**Comment by eteq** [comment]
> FYI: from git blame, it looks like this goes all the way back to the first commit of Galactic

Do you mean  db55cb66f7a9a6b6961af253d3f7ca9c5cde5cd3 when you say that?  That's not actually the first commit of `Galactic`, but rather when it was *moved* to its current file.

It looks to me like the origin is actually 2f732d9c25d3d7e1b2980040f3b293a8fceb909a - relevant mainly because it looks like it was part of a much bigger commit so it's unlikely to have been on purpose.

**Comment by eteq** [comment]
Also, note that there is some degree of inconsistency about what convention uvw follows (right- or left- handed and u pointing - for more on this see http://adsabs.harvard.edu/abs/1987AJ.....93..864J).  But AFAIK it's never out-of-order letters.  So this does indeed look like an old bug.
