### ISSUE TITLE
clobber warning could be more helpful

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#6349]
Currently it is hard to know where the warning comes from:
```
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
```
Using `stacklevel` it should be possible to show the module that use the deprecated call instead of `astropy.utils.decorators`. This could be done for all `deprecated_` decorators, maybe with an optional parameter to override `stacklevel` if needed ?

**Comment by pllim** [comment]
Shouldn't you know that warning by heart by now? :wink:  On a more serious note, I agree.

**Comment by MSeifert04** [comment]
Interesting question. I don't know if it's possible to use `stacklevel` in this case because the warning is raised in the decorated function. The stacklevel is useful if the warning is raised in a helper function but decorators really replace the function so it's **really** `astropy.utils.decorators.deprecated_renamed_argument.<wrapper>` that is called and warns.

**Comment by MSeifert04** [comment]
The interesting bit about warnings is in my opinion the fact that you can turn them into exceptions and then the `stacklevel` isn't meaningful at all because the tb unwraps the whole stack.

It would be nice to specify the function name as "source" which triggered the exception though 😄
