### ISSUE TITLE
How to make biweight midvariance backward compatible?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6364]
Some changes to `biweight_midvariance()` between Astropy 1.3 and 2.0 broke a satellite trail detection algorithm for HST's Advanced Camera for Surveys (see spacetelescope/acstools#28). Could it be from #5991?

It was used simply as `biweight_midvariance(array)` with default parameters. Using Astropy 2.0, adding `modify_sample_size=True` did not fix the problem. What else should we set as non-default to obtain same behavior as Astropy 1.3?

c/c @dborncamp

**Comment by bsipocz** [comment]
@pllim - It must be #5991 and it was argued there that the previous behaviour is the broken one. cc-ing @larrybradley as the author.

**Comment by pllim** [comment]
Unfortunately the "broken" code worked well for us... How do we re-break it? 😅

**Comment by larrybradley** [comment]
In Astropy <= 1.3, `biweight_midvariance` was *actually* calculating a standard deviation estimator (i.e. `biweight_scale`) instead of a variance estimator.  That was very bad.  😮   After this discovery, I fixed it #5991.

In Astropy >= 2.0, `biweight_midvariance` now correctly calculates a variance estimator.

In #5991, I added a `biweight_scale` function, which calculates a standard deviation estimator:
http://docs.astropy.org/en/stable/api/astropy.stats.biweight.biweight_scale.html#astropy.stats.biweight.biweight_scale

So, if you want to reproduce the output of the old (*wrong* `biweight_midvariance`), this should work:
`biweight_scale(...., modify_sample_size=True)`

Again, note this is a *standard deviation* estimator.  If instead your code was expecting variance, then your code was actually broken with the old `biweight_midvariance`.

**Comment by larrybradley** [comment]
I should also mention that Astropy >= 2.0 `biweight_scale` and `biweight_midvariance` now exactly agree with the `R` implementations (I tested this) when `modify_sample_size=False` (default).

**Comment by pllim** [comment]
Good to know. Thanks!

**Comment by dborncamp** [comment]
We were expecting standard deviation so `biweight_scale` is what we want now.
Thanks @larrybradley !
