### ISSUE TITLE
Type change for quantities created from 0D numpy arrays

### ISSUE THREAD

**Issue by DTHaydon** [astropy/astropy#6389]
When accessing the `value` attribute of an `astropy.units.quantity.Quantity`, the output type changes for "0D" numpy arrays from `numpy.ndarray` to `float`. 

This means that the output of `astropy.units.quantity.Quantity.value` cannot be treated the same as the initial input array.

## Code

    from __future__ import print_function
    
    from astropy import units
    import numpy
    
    print("----- Input arrays -----")
    array_0d = numpy.array(1.)
    print("type: array_0d: ", type(array_0d))
    print("shape: array_0d: ", array_0d.shape)
    array_1d = numpy.array([1.])
    print("type: array_1d: ", type(array_1d))
    print("shape: array_1d: ", array_1d.shape)
    
    print("----- Quantity -----")
    array_0d_units = array_0d * units.meter
    print("type: array_0d_units: ", type(array_0d_units))
    array_1d_units = array_1d * units.meter
    print("type: array_1d_units: ", type(array_1d_units))
    
    print("----- Quantity.value -----")
    print("type: array_0d_units.value: ", type(array_0d_units.value))
    print("type: array_1d_units.value: ", type(array_1d_units.value))

### Output
    ----- Input arrays -----
    type: array_0d:  <type 'numpy.ndarray'>
    shape: array_0d:  ()
    type: array_1d:  <type 'numpy.ndarray'>
    shape: array_1d:  (1,)
    ----- Quantity -----
    type: array_0d_units:  <class 'astropy.units.quantity.Quantity'>
    type: array_1d_units:  <class 'astropy.units.quantity.Quantity'>
    ----- Quantity.value -----
    type: array_0d_units.value:  <type 'float'>
    type: array_1d_units.value:  <type 'numpy.ndarray'>

----------
Astropy: 1.3.2
Numpy: 1.12.1
Python: 2.7.13
OS: macOS 10.12.4

**Comment by mhvk** [comment]
I saw this issue while going over old ones -- and should apologize for having missed it originally (holidays are good for that...). The main underlying problem is that we always represent quantities, even scalar ones, as arrays, while numpy makes a distinction between array scalars (`shape=()`) and proper scalars. In general, for an `ndarray`, if you do `array[0]` you get out a numpy scalar, not an array scalar:
```
In [3]: type(np.array([1.])[0])
Out[3]: numpy.float64
```
So, for quantity, the idea is that, similarly, you get a scalar out when you do `.value` of a scalar quantity.

Now, looking at this again, I note we're not quite consistent in returning a `float` rather than `numpy.float64`...

For your particular issue, though, if you want to be sure to stick with an array, you could do `q.view(np.ndarray)`

**Comment by mhvk** [comment]
Going to close this, as I put this inside #8876 as something to discuss.
