### ISSUE TITLE
Cutout2D attributes listing is missing a (the?) key attribute

### ISSUE THREAD

**Issue by josePhoenix** [astropy/astropy#6407]
If you look at http://docs.astropy.org/en/stable/api/astropy.nddata.utils.Cutout2D.html#astropy.nddata.utils.Cutout2D you could be forgiven for not realizing that `my_cutout_instance.data` is the way to get at the array or view created by Cutout2D. It is used in the examples, but it is curiously absent from the attributes listing

**Comment by pllim** [comment]
That is because it is set within `__init__` at https://github.com/astropy/astropy/blame/master/astropy/nddata/utils.py#L669 . "autodoc" will not pick it up as a separate attribute to document. One could add an "Attributes" section to the docstring and manually list out all the user-facing ones if so desired. @larrybradley ?

While we are at it, the docstring under `__init__` should be removed and instead appended to the one under `class ...`.

**Comment by larrybradley** [comment]
Addressed in #6411.
