### ISSUE TITLE
Support creating astropy.time.Time from numpy.datetime64 and pandas datetime columns

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#6428]
It would be great if this just worked:

```
import numpy as np
from astropy.time import Time

t =  np.array(['2017-01-01 20:00', '2017-01-01 21:00'], dtype='datetime64[ms]')
t = Time(t)
```

But right now, this results in a value error:
```
ValueError: No time format was given, and the input is not unique
```

**Comment by astrofrog** [comment]
This would be nice - also for the pandas datetime column we should make sure this works when using ``QTable.from_pandas`` too (and gives a Time column).

**Comment by mhvk** [comment]
This is not terribly hard in principle: it just means defining a new `TimeDatetime64` class in `time.formats` and allowing arrays with `dtype.kind=='M'` - a super-quick trial is in https://github.com/astropy/astropy/compare/master...mhvk:time-numpy-datetime?expand=1

But to do it *right* is trickier, as numpy datetime has a unit, which should be taken into account [1]. This influences both the precision and the full range that the time can represent, and can both be coarser and finer than a regular `datetime`. 

Hence, it may well be better not to route the conversion via python's `datetime`, but rather use the way the numpy values are stored, as integer offsets from unix time = 0. Indeed, the following works even in present master:
```
t =  np.array(['2017-01-01 20:00', '2017-01-01 21:00'], dtype='datetime64[ms]')
tm = Time(t.view('i8') * u.ms, format='unix')
tm.iso
# array(['2017-01-01 20:00:00.000', '2017-01-01 21:00:00.000'], 
#       dtype='<U23')
```
And by the vagueries of unix time, this seems to work for other units as well, even in the presence of leap seconds.

So, I think the better approach is indeed via `UnixTime`. Independently, though, there has to be some way to determine what the output `dtype` should be. Arguably most logical is to use `precision`, maybe reducing it as necessary to be able to reproduce the range in times present.

Anyway, maybe the above serves as a starting point (I don't really have time to push this further myself); also cc @taldcroft since he may well have thought above `datetime64` before...

p.s. If one implements `datetime64` there probably should be a `TimeDelta` for `timedelta64` as well...

[1] https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html

**Comment by Cadair** [comment]
So @alex-ian-hamilton and I expanded on @mhvk's hack and I came up with this:
```python
 ❯ d = np.datetime64("2011-01-01T00:10:10.00998")

 ❯ Time(d.view('i8') * u.Unit(d.dtype.str.split('[')[1][:-1]), format='unix').isot
'2011-01-01T00:10:10.010'
```
Which is *real* ugly. Does anyone have a better way of extracting the unit from the dtype?

**Comment by mhvk** [comment]
@Cadair - this actually seems relatively sane...  I think if this is hidden in a `TimeDatetime64` class, it should be quite fine. The main trouble would then be how to determine the output unit.

**Comment by astrofrog** [comment]
Another possibility is:

```
DATETIME64_TO_UNIT = {
    'datetime64[as]' = u.attosecond,
    'datetime64[fs]' = u.femtosecond,
    ...

d = np.datetime64("2011-01-01T00:10:10.00998")

Time(d.view('i8') * DATETIME64_TO_UNIT[d.dtype.name], format='unix').isot
'2011-01-01T00:10:10.010'
```

which feels less hacky.

**Comment by vn-ki** [comment]
The above would not work correctly if `dtype.name` is `datetime64[M]` or `datetime64[Y]`.

One would've to use the method in [this gits](https://gist.github.com/vn-ki/01b6d32b7a255e796ea54e8b882c8512)(using the above logic with a bit of `datetime`).

**Comment by vn-ki** [comment]
@mhvk
I ran into some problem while using your method.

```python
>>> t = np.datetime64('2014-02-07T16:47:51.008188123')
>>> Time(t.view('i8')*u.nanosecond, format='unix', precision=9).isot
'2014-02-07T16:47:51.008188248'
```

I then went with string parsing of `numpy.datetime64` shown in [this gist](https://gist.github.com/vn-ki/28edbc581b1218118b40df29855d1c6c). This appears to return the proper Time.

Is there any problem with this method? Can this be used to `set_jds` the custom numpy format class?

I'm sorry for bugging you with `Time` again and again.

**Comment by vn-ki** [comment]
pandas datetime coloumns are still not supported. Only numpy datetime64 was added in #7361.

Maybe a new issue should be opened for datetime coloumns?

**Comment by astrofrog** [comment]
@vn-ki - it looks like this does work for pandas?

```
In [23]: Time(pd.to_datetime(df), format='datetime64')
Out[23]: <Time object: scale='utc' format='datetime64' value=['2015-02-04T02:00:00.000000000' '2016-03-05T03:00:00.000000000']>

In [24]: df = pd.DataFrame({'year': [2015, 2016],
    ...:                    'month': [2, 3],
    ...:                    'day': [4, 5],
    ...:                    'hour': [2, 3]})
    ...:                    

In [25]: Time(pd.to_datetime(df), format='datetime64')
Out[25]: <Time object: scale='utc' format='datetime64' value=['2015-02-04T02:00:00.000000000' '2016-03-05T03:00:00.000000000']>
```

and

```
In [27]: Time(pd.date_range('1/1/2011', periods=4, freq='H'), format='datetime64')
Out[27]: 
<Time object: scale='utc' format='datetime64' value=['2011-01-01T00:00:00.000000000' '2011-01-01T01:00:00.000000000'
 '2011-01-01T02:00:00.000000000' '2011-01-01T03:00:00.000000000']>
```

Do you have other examples in mind that might not work?

**Comment by vn-ki** [comment]
I was thinking the value itself would not be `DataFrame` or `DatetimeIndex`. 

```
In [3]: Time(pd.date_range('1/1/2011', periods=4, freq='H'), format='datetime64').value
Out[3]: 
array(['2011-01-01T00:00:00.000000000', '2011-01-01T01:00:00.000000000',
       '2011-01-01T02:00:00.000000000', '2011-01-01T03:00:00.000000000'],
      dtype='datetime64[ns]')

In [9]: pd.date_range('1/1/2011', periods=4, freq='H')
Out[9]: 
DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00'],
              dtype='datetime64[ns]', freq='H')
```

But I guess that's not big of a hiccup.
