### ISSUE TITLE
InvalidTransformError after setting crval on WCS from celestial_frame_to_wcs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6490]
The following example demonstrates the issue:

```python
In [6]: from astropy.wcs.utils import celestial_frame_to_wcs

In [7]: from astropy.coordinates import Galactic   

In [8]: wcs = celestial_frame_to_wcs(Galactic(), projection='CAR')

In [9]: wcs.wcs.crval = 100, -30

In [10]: print(wcs.wcs)
---------------------------------------------------------------------------
InvalidTransformError                     Traceback (most recent call last)
<ipython-input-10-c917a9900192> in <module>()
----> 1 print(wcs.wcs)

InvalidTransformError: ERROR 7 in wcsset() at line 2101 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameter.
ERROR 4 in celset() at line 422 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.
```

@nden - any idea what could be causing this?

**Comment by nden** [comment]
I get the same error without using `celestial_frame_to_wcs`. 
```
w = wcs.WCS()
w.wcs.ctype = ["GLON-CAR", "GLAT-CAR"]
w.wcs.printcontents()
w.wcs.crval = 100., -30
w.wcs.printcontents()
InvalidTransformError: ERROR 7 in wcsset() at line 2101 of file cextern/wcslib/C/wcs.c:
Ill-conditioned coordinate transformation parameter.
ERROR 4 in celset() at line 422 of file cextern/wcslib/C/cel.c:
Ill-conditioned coordinate transformation parameters
No valid solution for latp for these values of phip, phi0, and theta0.
```
I will post a workaround shortly but I think there's a deeper problem in wcslib or the wrappers which does not always set the WCSPRM struct correctly when a set() command is called more than once in a row. Note that `set` is called internally when any method is executed. The above error will also be triggered if you run `all_pix2world` instead of `print_context()`.  

Part of the issue is that the transform is not fully defined until you specify CRVAL. CRVAL has default of (0, 0) and this is used to set the auxiliary attributes. In the specific case of `CAR` projection if you happen to give CRVAL2 a positive value the command will work because the auxiliary attributes do not have to change.
