### ISSUE TITLE
Consistency with FITS Header string types

### ISSUE THREAD

**Issue by dr-rodriguez** [astropy/astropy#6504]
When getting text values from a FITS header, I've noticed they will not always pass simple Python 2.7 checks. For example, 
```python
from astropy.io import fits
from __future__ import (absolute_import, division, print_function, unicode_literals)
from future.builtins import bytes, int, str

hdu = fits.open(myfile)

x = hdu[1].header['DATE-OBS']
print(x, type(x), isinstance(x, str))
```
This returns: `2018-03-30T18:27:38.816Z <type 'str'> False`
However, this: 
```python
y = '2018-03-30T18:27:38.816Z'
print(y, type(y), isinstance(y, str))
```
returns: `2018-03-30T18:27:38.816Z <type 'unicode'> True`
Perhaps `astropy.io.fits.header.Header` objects should return unicode values by default under Python 2?

In my code, I can get it to work using the `six` package:
```python
from six import string_types
print(x, type(x), isinstance(x, string_types))
```
which produces: `2018-03-30T18:27:38.816Z <type 'str'> True`

I'm OK with using `six` at the moment, but wanted to mention how this fails with `future.builtins`

**Comment by pllim** [comment]
Astropy is dropping Python 2 support in v3 -- FYI.

**Comment by saimn** [comment]
This is because you use `unicode_literals` (`y = '2018-03-30T18:27:38.816Z'` becomes unicode). But the default type on Python 2 is `str`, and `unicode_literals` is usually causing more annoyance than benefits. (Even in the stdlib - for Python 2 - many functions expect `str` as input, and return `str`, not `unicode`).
So it's better to avoid `unicode_literals`, and anyway Astropy is close to dropping Python 2 :)

**Comment by pllim** [comment]
Is it safe to mark this as "won't fix" and close?

**Comment by saimn** [comment]
I guess so, closing.
