### ISSUE TITLE
Revisit xpassed tests and remove xfail from them

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#6665]
For example, there are 3 `xpassed` tests in https://travis-ci.org/astropy/astropy/jobs/283303458 and https://ci.appveyor.com/project/Astropy/astropy/build/1.0.8822 , respectively (probably the same ones). We should remove `xfail` from those because they are no longer failing.

```
astropy\table\tests\test_mixin.py .....................................sss.s.s...................................................X.............
astropy\table\tests\test_operations.py .......x...x.x.x...........x.....x.......................x...xXX.x.........................x.............
```

Hint: Using this setting turns any `xpass` into a failure (ref: https://docs.pytest.org/en/latest/skipping.html).
```
[tool:pytest]
xfail_strict=true
```

**Comment by bsipocz** [comment]
and are these xpasses on all platforms?

**Comment by pllim** [comment]
I see them on Travis and Appveyor, so theoretically yes.

**Comment by MSeifert04** [comment]
Is it possible to enable that setting and let it run through CI without these 3 xfails?

**Comment by bsipocz** [comment]
So the 2 xpassing one is due to the heisenbug in operations: https://github.com/astropy/astropy/issues/6291
It's great that it's passing, but we need to make sure it's indeed gone for good.

In there, it's suggested (https://github.com/astropy/astropy/issues/6291#issuecomment-312958701) that running the test as ``pytest astropy/table/tests/test_operations.py --pdb -sv -k test_col_meta_merge_inner`` always makes it fail, but it's still xpasses for me now on master, but also on 2.0...

**Comment by pllim** [comment]
Heisenbug... Maybe they only fail when you run them on your second cellphone, I mean, laptop.

**Comment by bsipocz** [comment]
They even pass not using my own laptop now (though for some weird reason I cannot run the tests with ``-t``, nor the command above, but both run perfectly on my own laptop).

Anyway, we can try to remove that xfail and monitor the situation, maybe the fail is indeed gone.

**Comment by mhvk** [comment]
Closing, since the passing tests are now all enabled! (And crossing fingers that they continue to pass...)
