### ISSUE TITLE
Celestial Navigation with image processing!

### ISSUE THREAD

**Issue by masoudline** [astropy/astropy#6702]
Hi everybody
I'm a sailor and I want to locate my position from the celestial image and use it for navigation.
my skill: opencv, python
I want a full code or project for this propose.

thanks for your favor.

**Comment by adrn** [comment]
Hi there. Cool! We don't have plans to provide end-to-end functionality for this, in principle, all the software pieces exist to do what you need (but not inside Astropy). From an image of the sky, you can determine the WCS header information using [astrometry.net](http://astrometry.net/) (but it is primarily a web service). The WCS header (see the [wcs subpackage](http://docs.astropy.org/en/latest/wcs/index.html) in astropy) contains information about how to transform coordinates in the image to coordinates on the sky. If you knew exactly what your bearing was in coordinates of the image, you could then transform to sky coordinates using the WCS information. If you knew your longitude and latitude, you could get back to local compass directions by transforming to [Altitude-Azimuth](http://docs.astropy.org/en/latest/api/astropy.coordinates.AltAz.html#astropy.coordinates.AltAz) coordinates. If you also want to solve for your latitude and longitude, it requires a bit more work...

_Disclaimer: I'm not a sailor and there may be a much easier way mathematically._

But, since this is a bit beyond the scope of astropy (the core package), where this issue is, I would suggest instead raising this question on the [astropy email list](https://mail.scipy.org/mailman/listinfo/astropy). Please re-open if you disagree!
