### ISSUE TITLE
Confusing documentation for matching catalogs

### ISSUE THREAD

**Issue by smoh** [astropy/astropy#6718]
Hi, I found the documentation on `match_to_catalog_sky` always confusing, so I thought I'd finally raise an issue. I can't figure out what is returned as dist3d when I only use 2d sky coordinates.

- The function docstring has no mention of what this means when only using 2d sky coordinates.
- "Matching Catalogs" section in astropy documentation page says "You can also find the nearest 3d matches, different from the on-sky separation shown above only when the coordinates were initialized with a distance:" so I thought maybe it's just the same as sep2d when only 2d sky coordinates are provided, but even after converting to radians the values are not exactly the same and has small differences.

I'm a little confused what the motivation is for returning dist3d when only 2d info is given, but in any case I think it'd be good to have a sentence clearing this up in both -- please let me know if I'm missing something.

**Comment by adrn** [comment]
Ah, yea, this should be clarified in the docs!

but FYI: When no distance is passed, the points are assumed to be on the unit sphere, so when converting to Cartesian they are assumed to have (dimensionless) distances = 1. The dimensionless 3d distance would then be different than the sky separation: it becomes that "chord length" that I (for some reason) always talk about (e.g., [Equation 6 in our paper](https://arxiv.org/pdf/1709.03532.pdf) 😄). 

But I'm actually not sure why it returns a 3d distance at all when the distance isn't given. (just guessing) It was presumably @eteq's design choice so that the number of returned objects doesn't depend on the input? In any case, I agree that this should be stated in the docstring.

**Comment by adrn** [comment]
An example in case it helps clarify:

```python
import astropy.coordinates as coord
import astropy.units as u
import numpy as np

catalog = coord.ICRS(ra=np.random.uniform(0, 2*np.pi, 128)*u.radian,
                     dec=np.arcsin(2*np.random.uniform(size=128) - 1)*u.radian)
c1 = coord.ICRS(ra=150*u.deg, dec=-11*u.deg)

idx, sep, dist3d = coord.match_coordinates_sky(c1, catalog)

chord_length = 2*np.sin(0.5*sep)
np.isclose(chord_length, dist3d)
```

**Comment by smoh** [comment]
Thanks, that explains the small differences!
