### ISSUE TITLE
fill_values requires a list with multiple entries

### ISSUE THREAD

**Issue by kdpenner** [astropy/astropy#6759]
Hello,

Here's a table:

```
#  fI  fIerr   fIap  fIaperr     fV  fVerr   fVap  fVaperr
1.612  0.033  1.704  0.035  1.158  0.021  1.418  0.026
1.704  0.033  1.801  0.035  0.456  0.020  0.558  0.024
NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
```

This code:
`q = Table.read('IVaper.cat', format = 'ascii.commented_header')`

shows this:
```
   fI    fIerr    fIap  fIaperr    fV    fVerr    fVap  fVaperr
float64 float64 float64 float64 float64 float64 float64 float64
------- ------- ------- ------- ------- ------- ------- -------
  1.612   0.033   1.704   0.035   1.158   0.021   1.418   0.026
  1.704   0.033   1.801   0.035   0.456    0.02   0.558   0.024
    nan     nan     nan     nan     nan     nan     nan     nan
```

This code:
`q = Table.read('IVaper.cat', format = 'ascii.commented_header', fill_values = 'NaN')`

shows the same thing:
```
   fI    fIerr    fIap  fIaperr    fV    fVerr    fVap  fVaperr
float64 float64 float64 float64 float64 float64 float64 float64
------- ------- ------- ------- ------- ------- ------- -------
  1.612   0.033   1.704   0.035   1.158   0.021   1.418   0.026
  1.704   0.033   1.801   0.035   0.456    0.02   0.558   0.024
    nan     nan     nan     nan     nan     nan     nan     nan
```

Only when I run:
`q = Table.read('IVaper.cat', format = 'ascii.commented_header', fill_values = ['NaN', 'NaN'])`

do I get the expected output:
```
   fI    fIerr    fIap  fIaperr    fV    fVerr    fVap  fVaperr
float64 float64 float64 float64 float64 float64 float64 float64
------- ------- ------- ------- ------- ------- ------- -------
  1.612   0.033   1.704   0.035   1.158   0.021   1.418   0.026
  1.704   0.033   1.801   0.035   0.456    0.02   0.558   0.024
     --      --      --      --      --      --      --      --
```

I'm using astropy v2.0.2

**Comment by hamogu** [comment]
That's intentional. In earlier versions of astropy you would have to the value you want to be replaced and the value that it's replaced with, e.g. to replace NaN with '0' one would write ('NaN', '0'). Now, we use masked tables, so it does not really matter what the string 'NaN' is replaced with because it gets masked anyway - so in ['NaN', 'NaN'] you replace the string 'NaN' with 'NaN', but then the value gets masked, so it does not matter.

However, we did not change the way the fill_values are specified, because that would break previous code. Imagine you have code with this `fill_value = ['NaN', '0']`. In the old scheme that would replace NaN with 0. If we were to change this to say "if it's a list just replace all of them", then that old could would suddenly mask "NaN" and "0" which seems like a dangerous thing.

That still does not explain why `fill_values = 'NaN'` worked at all instead of just throwing an error. That's something we should investigate. I suspect it's treating it like `('N', 'a', 'N')` would replace (and mask) all values 'N' with 'a' (which you don't see because it would be masked) in the column named 'N' (which your table does not have, which is why nothing happens.

See https://astropy.readthedocs.io/en/latest/io/ascii/read.html#bad-or-missing-values and the "Note" box for the explanation I tried to give above.

**Comment by hamogu** [comment]
@kdpenner Besides changing the way `fill_values` is specified (which we'd really like to avoid because it breaks backward compatibility), is there anything else you think we could do, e.g. is there a specific place in the docs or an error message we could improve?
