### ISSUE TITLE
hstack requires a sequence of Tables or Rows

### ISSUE THREAD

**Issue by kdpenner** [astropy/astropy#6791]
I am horizontally stacking a Column and a Table and get this error:
```
.../anaconda2/lib/python2.7/site-packages/astropy/table/operations.pyc in _get_list_of_tables(tables)
     50     # Make sure each thing is a Table or Row
     51     if any(not isinstance(x, (Table, Row)) for x in tables) or len(tables) == 0:
---> 52         raise TypeError('`tables` arg must be a Table or sequence of Tables or Rows')
     53 
     54     # Convert any Rows to Tables

TypeError: `tables` arg must be a Table or sequence of Tables or Rows
```
hstack is incorrectly requiring a Row instead of a Column.

**Comment by taldcroft** [comment]
Agreed that should be changed.  It should be fine to add `Column` to the list of allowed inputs.  This is an easy PR though in the end there will be tests and possibly documentation updates.  Something like below should work:
```
    # Make sure each thing is a Table or Row or Column
    if any(not isinstance(x, (Table, Row, Column)) for x in tables) or len(tables) == 0:
        raise TypeError('`tables` arg must be a Table or sequence of Tables or Rows or Columns')

    for ii, tbl in enumerate(tables):
        if isinstance(tbl, Row):
            tables[ii] = Table(tbl)
        elif isinstance(tlb, Column):
            tables[ii] = Table([tbl])
```

**Comment by hrishikeshgoyal** [comment]
I'm interested in working on this issue

**Comment by mhvk** [comment]
I like the idea but wonder if we can take it further, by just duck-typing anything that is not a `Table` already. Here, it would help greatly if `Table(column)` just returned a single-column table (rather than treating it as an array with the first dimension equal to the number of columns). Might it be an idea to change table to do that (i.e., if `data` is a (mixin) column, do not treat it as an `ndarray`, but rather create a single-column table)?
