### ISSUE TITLE
Dynamic range

### ISSUE THREAD

**Issue by dnfarias** [astropy/astropy#6795]
Hi everyone,

I'm not an expert on astropy/fits format and I need to change a fits image from BITPIX -32 to BITPIX 16 (dynamic range from 0 to 65535); should I use scale() function? or I'm misinterpreting its usage? If the latter is positive, how would you do it in python/astropy?

I've been struggling a lot with this and I hope you could help me.

**Comment by dnfarias** [comment]
scale('uint16')?

**Comment by MSeifert04** [comment]
Hey @dnfarias,

normally the mailing list deals with usage questions that aren't feature requests or bug reports. 

But now that you're here: What exactly do you mean with "change a fits image from BITPIX -32 to BITPIX 16". Is the intention just to cast them to uint16 (with truncation)? Or do you want to scale them using BZERO/BSCALE? It would be useful to know what kind of range the BITPIX -32 values have and what the desired result would look like.

**Comment by MSeifert04** [comment]
Thanks for the additional explanation but I'm still not sure what's needed. The conversion from float32->int16 will always change the data, just because you cannot store any possible value as integer even with bscale and bzero.

The closest I can think of is `.scale('int16', option='minmax')` that will use the min and max of the data to scale the hdu. Maybe that's what is desired.

**Comment by saimn** [comment]
This doc section might be of interest: http://docs.astropy.org/en/stable/io/fits/usage/image.html#scaled-data
Closing as this was also discussed on the mailing-list (which is the good place for these kind of question).
