### ISSUE TITLE
transforming velocities from HCRS to LSR fails

### ISSUE THREAD

**Issue by gica3618** [astropy/astropy#6835]
Not sure whether this is really an issue or just due to my very limited understanding of coordinate transformations.
I wanted to transform a heliocentric radial velocity to the LSR. I understand that this can be achieved with astropy by transforming from ICRS to LSR. However, I also tried to transform from HCRS to LSR, and this failed; I don't know whether this is intended or a bug.
```
from astropy.coordinates import LSR,HCRS
import astropy.units as u
hcrs = HCRS(ra=8.67*u.degree, dec=53.09*u.degree,distance=117*u.pc,
            pm_ra_cosdec=4.8*u.mas/u.yr, pm_dec=-15.16*u.mas/u.yr,
            radial_velocity=23.42*u.km/u.s)
hcrs.transform_to(LSR)
```
I get "TypeError: scalar 'CartesianRepresentation' object is not iterable."
I use astropy version 2.0.2

**Comment by adrn** [comment]
Looks like a genuine bug to me!

**Comment by mhvk** [comment]
Somewhere inside the `CartesianDifferential` is transformed into `CartesianRepresentation` and then `_validate_differential` fails.

...

The underlying problem is that `get_body_barycentric_posvel` returns a `CartesianRepresentation` for the velocity - it either should return a `CartesianDifferential`, or, perhaps better since not breaking any backward compatibility, it should be turned into one in `icrs_cirs_transforms.py`.
