### ISSUE TITLE
Document how to fit with weights

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6994]
The documentation page on fitting:

http://docs.astropy.org/en/latest/modeling/fitting.html

doesn't say anything about how to use weights/errors in a fit, and how to get uncertainties out of a fit (if available). We should really document this better.

The docstring for the weights should also be improved:

<img width="233" alt="screen shot 2017-12-15 at 15 41 16" src="https://user-images.githubusercontent.com/314716/34049199-67fe4d3c-e1ae-11e7-9c7a-db863a4f9a3b.png">

**Comment by adrn** [comment]
We should clearly state that if you want to compute maximum likelihood parameters -- e.g., with `scipy.optimize.leastsq` with Gaussian errors -- the weights should be `1/y_uncertainty`, because `leastsq` accepts a function that computes `(data - model) / uncertainty`. See also: https://github.com/astropy/astropy/blob/master/astropy/modeling/fitting.py#L618

**Comment by karllark** [comment]
I am interested and could take a crack at adding this documentation in the next few days.  Ok?

**Comment by karllark** [comment]
I've been working on this today.
@astrofrog : Is your "See also:" comment pointing out that a change is needed for the `FittingWithOutlierRemoval` class?  Or that more documentation is needed?  
My reading of the `FittingWithOutlierRemoval` code is that is uses the weights for 1st iteration, but not for subsequent iterations or as part of the outlier removal.

**Comment by pllim** [comment]
I think Karl solved this one!
