### ISSUE TITLE
Can't evaluate model sets over common co-ordinate array for model_set_axis > 0

### ISSUE THREAD

**Issue by jehturner** [astropy/astropy#7159]
Related to last week's #7142 & #7143, I'm still not 100% clear on the intended usage of `model_set_axis` myself -- but shouldn't one be able to do `some_model(x, model_set_axis=False)` when `some_model` was created with a `model_set_axis` other than 0? This is not working in the cases I have tried.

```Python
import numpy as np
from astropy.modeling.models import *
from astropy.modeling.fitting import *

p = Polynomial1D(1, n_models=2, model_set_axis=1)

x = np.arange(0,4)

# Generate data for fitting 2 models and re-stack them along the last axis:
y = np.array([2*x+1, x+4])
y = np.moveaxis(y, 0, -1)

f = LinearLSQFitter()

# This seems to fit the model_set correctly:
fit = f(p, x, y)
print(fit.parameters)

# But this fails to evaluate the model, with a broadcasting error (the same
# thing happens with Polynomial1D, Polynomial2D, Chebyshev1D & Legendre1D):
model_y = fit(x, model_set_axis=False)
```

```
[ 1.  4.  2.  1.]
Traceback (most recent call last):
  File "test_model_set_axis_1.py", line 21, in <module>
    model_y = fit(x, model_set_axis=False)
  File "/home/jturner/repos/astropy/astropy/modeling/core.py", line 382, in __call__
    ('equivalencies', None)])
  File "/home/jturner/repos/astropy/astropy/modeling/core.py", line 363, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/home/jturner/repos/astropy/astropy/modeling/core.py", line 761, in __call__
    outputs = self.evaluate(*chain(inputs, parameters))
  File "/home/jturner/repos/astropy/astropy/modeling/polynomial.py", line 806, in evaluate
    return self.horner(x, coeffs)
  File "/home/jturner/repos/astropy/astropy/modeling/polynomial.py", line 840, in horner
    c0 = coeffs[-i] + c0 * x
ValueError: operands could not be broadcast together with shapes (1,2) (1,4) 
```

The reason I care about this is that I was trying to finish fixing #6819, but `FittingWithOutlierRemoval` has to evaluate the model set at each iteration, over the single `x` (/ `y`) grid supplied by the user -- ie. using `model_set_axis=False`. Since FittingWithOutlierRemoval can't just assume that `model_set_axis=0` for its input, I was checking the behaviour with other axes and found it broken in the models.

Thanks,

James.

**Comment by jehturner** [comment]
There's also the question of how `FittingWithOutlierRemoval` can determine what
`model_set_axis` it's supposed to assume for its inputs.

From [the docs](http://astropy.readthedocs.io/en/latest/modeling/fitting.html), "Fitting Models to Data" says:

_The linear fitter can fit a single input to multiple model sets creating multiple fitted models. This may require specifying the model_set_axis argument just as used when evaluating models; this may be required for the fitter to know how to broadcast the input data._.

Since the fitters don't actually have their own `model_set_axis` argument, I understand this as meaning that fitters (and thus `FittingWithOutlierRemoval`) will assume that their input `y`/`z` data are stacked to match their input `model.model_set_axis`. Does that sound right?

**Comment by jehturner** [comment]
cc @mirca, @saimn (I think you should get copied automatically via the other issues, but just in case...)

**Comment by jehturner** [comment]
At a glance, I wonder whether something like `core._prepare_inputs_model_set`, called by `Model`, should be transposing model inputs transparently but isn't doing so correctly?

**Comment by nden** [comment]
@jehturner I'll take a look tomorrow.

**Comment by jehturner** [comment]
Thanks! I could probably just assume that my handling of the `model_set_axis` in `FittingWithOutlierRemoval` is correct and carry on, though it would be nice to be able to test it 🙂. Any comments on my assumptions/understanding would also be helpful.

**Comment by nden** [comment]
@jehturner 

I agree the behavior of model sets is not well documented. And there may be bugs or at least there should be more checks. My understanding of how this works is based on reading the code only. Every time I run into a problem I have to read the code. So having done this again, I think your expectation that `fit(x, model_set_axis = False)` should work is correct. The bug is in how modeling stores parameter shapes and checks for broadcasting the shapes of parameters and inputs.

The parameter shape is such a fundamental thing in modeling that before going and fixing this particular problem and possibly creating a problem elsewhere I would like to collect use cases and spell out clear rules of what `model_set_axis` means and how it should work. I will start a gist later today and share it. Alternatively, @jehturner if you have the time you can start it and I can add to it.

**Comment by jehturner** [comment]
Good idea. I think we do need to clarify the intended usage of the many options and ways of doing things in modeling generally. I find some of them a bit baffling (eg. what are array-valued parameters for?), but they all add up to make it significantly harder to improve the existing code base than it would be to work on one's own, simpler version. Whenever one fixes a problem, one has to consider a plethora of test permutations such as model sets, model set axes, different dimensionalities, compound models, array-valued parameters and so on. Moreover, that functionality is not implemented consistently everywhere (eg. only the linear fitters works on model sets, only the non-linear fitters work on compound models etc.), which perhaps suggests that we've been overambitious in terms of trying to support too much flexibility? I think that's partly because Erik B. started working on some innovative ideas but then had to move onto other projects.

Of course, I do care about some of this sophistication (eg. compound models) and others may care about the other bits -- so perhaps it's all necessary. If so, maybe this requires significant work on documentation, code modularity and/or uniform implementation, which raises the question of whether we have enough effort.

In this particular case (of `model_set_axis > 0`), I am not really the person with a use case -- I was just trying not to break an existing option when working on `FittingWithOutlierRemoval`. However, it seems like the use case here would be to avoid the inconvenience of users having to transpose their data before fitting (eg. when fitting image columns rather than rows)? That seems legitimate if it has a significant impact on code readability. However, if every general fitter or model that someone writes has to worry about such complications individually, that seems like a barrier to participation in development. So, I would think there ought to be a layer in Model that transparently creates a transposed view if needed (if I'm not overlooking any practicalities)?

Sorry about the side rant, which I've been working up to for a while 😜. I think it would be a good idea for you to start a gist, @nden, if you have an idea what you want it to look like, but I'm happy to contribute to straightening all this out.

**Comment by nden** [comment]
@jehturner I thought about this and I think the behavior you see is by design. The reason is to avoid ambiguity. The fitter returns a modified copy of the original model and in your example above `fit` contains two models and model_set_axis is 1. This tells the evaluate method to expect two sets of input coordinates or a 2D array and to use the axis 1 as inputs. Now suppose that your input is a 2D array and you set model_set_axis to False. If it worked you will get a wrong result because each parameter set will be evaluated on the same input (the entire array) while it was meant to be evaluated on each column of the input. I think guarding against this ambiguity is what causes the above error. It has the unfortunate side effect that it doesn't work with 1D arrays where there is no ambiguity. 
The question is would it be a bigger headache to allow this?
BTW, if you keep inputs and model dimensionality consistent everything works. 

I wrote some notes (mostly for my understanding but perhaps I'll turn some of it into documentation too):

https://gist.github.com/nden/a89dad11a9789ab71e07a209fa8a7735 

Let me know if something doesn't look right there if you have a chance to look at it.

**Comment by nden** [comment]
@jehturner Obviously our posts crossed :-)

**Comment by nden** [comment]
What do you mean by "array-vallued" parameters?

**Comment by jehturner** [comment]
I mean where model parameters are arrays but *don't* correspond to different models in a set, as described in the first section [here](http://astropy.readthedocs.io/en/latest/modeling/models.html). I had never really understood what this is for, but yesterday @saimn happened to post a link to #2634 (from another issue), which looks like it contains some explanation relevant to both array parameters and model_set_axis...

Thanks for the detailed reply! I'll need to digest it (and 2634) a bit later.

**Comment by nden** [comment]
I see. Erik B. 's initial rewrite did not allow for a model parameter to be an array, e.g. a lookup table. This is what was requested in #2049. It got expanded to array-valued parameters. I think having array-valued parameters is possibly an unnecessary complicaiton to an already very complicated package.

**Comment by jehturner** [comment]
> Now suppose that your input is a 2D array and you set model_set_axis to False. If it worked you will get a wrong result because each parameter set will be evaluated on the same input (the entire array) while it was meant to be evaluated on each column of the input. I think guarding against this ambiguity is what causes the above error. It has the unfortunate side effect that it doesn't work with 1D arrays where there is no ambiguity.

Maybe I'm being slow to follow, but I don't see a difference in terms of ambiguity between 1D and 2D arrays here. Is the problem summarized by these 3 cases?

  1. Let's say `model_set_axis=M` and the `x` (/`y`) input has some dimensionality N+1 >= 2 (since you have at least one co-ordinate plus the model set axis). Each slice of the `x` input along axis M gets combined with the parameters for one model, producing an output `y`/`z` array of the same dimensionality as the input, N+1.

  2. If you set `model_set_axis=False`, you can now provide input of dimensionality N and the entire `x` (/`y`) array gets combined with the parameters for each model in turn, stacking the results along axis M (if it works) to produce an output `y`/`z` array of dimensionality N+1 again.

  3. The ambiguity I can see would occur if you *accidentally* used `model_set_axis=False` with the same `x` (/`y`) inputs as case 1 (of dimensionality N+1). That's hard to distinguish from N just being one larger to begin with and produces an output y/z array of dimensionality N+2 (ie. 3D when working with 1D co-ordinates or 4D when working in 2D). This is still true for N=1 (right?).

Note that there's nothing to prevent users from providing too high an array dimensionality for `x` (/`y`) even with *without* `model_set_axis=False`; it's just more likely to happen as a result of forgetting that `model_set_axis=False` and also less likely to be caught in that case, because `model_set_axis=False` bypasses the check for dimension M matching the number of models.

What I expected to happen in your example of a 2D input array with `model_set_axis=False` was that I'd get a 3D output, with the results of evaluating each model on that same 2D input array stacked along axis M. In fact, that *is* what I see for M=0; it just doesn't work for M = 1 or 2.

This does not mean that I'm wedded to the existing behaviour -- it was just my interpretation of how it works. Actually, I was very tempted to suggest getting rid of `model_set_axis` altogether, eliminating a lot of complexity. However, that could push a smaller amount of complexity up into user code (apart from breaking backwards compatibility), which isn't good, so I was wondering whether the parent `Model` can handle any transposition transparently (for its child classes).

Anyway, if the decision *is* that `model_set_axis=False` is not supposed to work for models instantiated with `model_set_axis > 0`, I can probably just take the `x` (/`y`) input to `FittingWithOutlierRemoval` and create a view with `np.broadcast_to` that can be used to evaluate the input model over whatever `model_set_axis` it happens to have; I just thought there was supposed to be a better way (and that I should point out if it wasn't working).

**Comment by jehturner** [comment]
Here's a 2D example that does what I had come to expect:
```
import numpy as np
from astropy.modeling.models import *
from astropy.modeling.fitting import *

p = Polynomial2D(1, n_models=2, model_set_axis=0)

y, x = np.mgrid[0:3, 0:4]

z = np.array([2*x+y+1, x+0.5*y+4])

f = LinearLSQFitter()

fit = f(p, x, y, z)
print(fit.param_sets)

model_z = fit(x, y, model_set_axis=False)
print(model_z)
```
```
[[ 1.   4. ]
 [ 2.   1. ]
 [ 1.   0.5]]

[[[ 1.   3.   5.   7. ]
  [ 2.   4.   6.   8. ]
  [ 3.   5.   7.   9. ]]

 [[ 4.   5.   6.   7. ]
  [ 4.5  5.5  6.5  7.5]
  [ 5.   6.   7.   8. ]]]
```

**Comment by jehturner** [comment]
I see Erik's rationale for `model_set_axis` was that "it may be useful for some performance critical cases in order to avoid having to swap the axes of an array around, resulting in a non-contiguous input array".

**Comment by nden** [comment]
@jehturner I agree with your analysis above. And, indeed, I was thinking that if one fitted two model to two arrays using an integer value for `model_set_axis`, they intend to evaluate on two different inputs. But I see now that it's way more flexible to be able to use `model_set_axis=False` in this case. Which means the use case you describe qualifies as a bug. 

I'm not sure this was the intention but it doesn't matter. Model sets have not been used very much and we should define now how we want them to work even if it breaks backwards compatibility.
At a first glance I think the issue here is not the dimensions of the inputs but the dimensions of the parameters when `model_set_axis` is changed from`1` to `False`. I'm not sure your 2D example works by design or by chance, simply because the parameter dimensions for values of `False` and `0` happen to be the same. Again, this doesn't matter, let's agree on how it should work.

I can work on fixing this on Thursday. And I'll start by updating the gist and turning it into documentation before I make changes.

**Comment by jehturner** [comment]
Thanks, @nden! I should note that this isn't really a road block: I have now drafted a version of `FittingWithOutlierRemoval` that works around the issue. That code would be simpler, however, if `model_set_axis=False` were working for any axis and I think the fact that it doesn't limits the usefuless of `model_set_axis` a bit.

I'm a bit concerned that it sounds like individual models need to worry about this stuff, which will just make it harder for mortal scientists to implement new ones. Maybe it's not realistic for `model_set_axis` to be incorporated transparently, though, given the performance considerations cited by Erik. I hear Knuth in my head, asking whether the parameter isn't a premature optimization (simply getting rid of it would also solve my problem), but maybe there are cases where it really matters, when evaluating a lot of models, and it probably benefits readability.
