### ISSUE TITLE
Index mismatch in Searching Around Coordinates from astropy.coordinates

### ISSUE THREAD

**Issue by mrkite92** [astropy/astropy#7164]
Hi Astropy gurus,

Here is my little piece of code:

```python
from astropy.io import ascii
from astropy.coordinates import SkyCoord as coord
import glob
import os

eros_pix_frac = 0.6 / 3600.0 / 2.0 * u.deg
photom = []
for ctl in glob.iglob(os.path.join(dir_wrk, '[cl]*.txt')):
    data = ascii.read(ctl, format='sextractor').to_pandas()
    if 'coadd' in ctl:
        data_ref = data
        data_ref = data_ref[data_ref['MAG_PSF'] < 99.0]
        cat_ref = coord(ra = data_ref['ALPHA_J2000'].values, dec = data_ref['DELTA_J2000'].values,
                        frame = 'icrs', unit = 'deg')
    else:
        cat = coord(ra = data['ALPHA_J2000'].values, dec = data['DELTA_J2000'].values,
                    frame = 'icrs', unit = 'deg')
        idx_ref, idx_cat, d2d, d3d = cat.search_around_sky(cat_ref, eros_pix_frac)
    photom.append(data)
    print os.path.basename(ctl), 'processed'
```

The screenshot shows that the returned indexes don't match. See for example column labelled 3: icx_cat is 97 while idx_ref is 36. This doesn't correspond at all to an actual match in the data. Plus, the same object (NUMBER = 98 in data, and NUMBER = 40 in data_ref) is missed.
Both data files are attached.

Thanks for you help,
Cheers,
JB
[2018-02-06 12.37.27.pdf](https://github.com/astropy/astropy/files/1698877/2018-02-06.12.37.27.pdf)

[coadd.red.txt](https://github.com/astropy/astropy/files/1698896/coadd.red.txt)
[lm05304trr6h30114.txt](https://github.com/astropy/astropy/files/1698900/lm05304trr6h30114.txt)

**Comment by macicco** [comment]
Hi Folks,I will attempt to solve this issue, is it ok for you ?

**Comment by macicco** [comment]
I am a newby on astropy git issues, but I think I could handle it

**Comment by astrofrog** [comment]
@macicco - feel free to investigate! (Note that this may not be a bug for certain)

**Comment by macicco** [comment]
Thanks!

**Comment by eteq** [comment]
@mrkite92 - a quick suggestion: if I'm reading this right you are asking because you are not sure how to do this, is that correct?  You might have better luck getting quick answers to questions like this if you go to one of the help locations listed here: http://www.astropy.org/help.html .  This issue tracker is primarily for bugs or change requests for the *code*, rather than help *using* it.

With that in mind, I had a quick look and don't see what the problem is.  If I do the following (using your files from above):
```python
from astropy import units as u
from astropy.table import Table
from astropy.coordinates import SkyCoord

eros_pix_frac = 0.3 * u.arcsec

coadd =Table.read('coadd.red.txt', format='ascii.sextractor')
coadd['coord'] = SkyCoord(coadd['ALPHA_J2000'], coadd['DELTA_J2000'], unit=u.deg)

lm = Table.read('lm05304trr6h30114.txt', format='ascii.sextractor')
lm['coord'] = SkyCoord(lm['ALPHA_J2000'], lm['DELTA_J2000'], unit=u.deg)

idx1, idx2, d2d, _ = lm['coord'].search_around_sky(coadd['coord'], eros_pix_frac)
```

I then see this:
```python
>>> coadd[idx1][0]['coord']
<SkyCoord (ICRS): (ra, dec) in deg
    ( 71.0085242, -71.4128749)>
>>> lm[idx2][0]['coord']
<SkyCoord (ICRS): (ra, dec) in deg
    ( 71.0085004, -71.4128784)>
```

which looks like exactly what you were looking for?

Also, keep in mind that there are a few different functions for this sort of activity.  If you're actually trying to find *one* match to the ref coordinates (which is what I speculate based on the names of the files), you want to use `match_coordinates_sky` instead.  See http://docs.astropy.org/en/stable/coordinates/matchsep.html for more on this.

(And @macicco, just so you know, if @mrkite92  agrees this is what they were looking for, then there's no actual issue to be solved here - the code is working as it should.)

**Comment by macicco** [comment]
Hi @eteq ! I spent all day long trying figure out which problem  could it be. 
I read search_around_sky docs and I couldn't  understand what was wrong with outputs.
So  I totally agree your last post!

**Comment by astrofrog** [comment]
> then there's no actual issue to be solved here

Although it would be interesting to understand in what places the documentation was unclear

**Comment by mrkite92** [comment]
Hi Erik,

You’re fully right, I misinterpreted the outputs. Apologies for the entropy.

Cheers,
JB
