### ISSUE TITLE
How to swap RA and DEC axes.

### ISSUE THREAD

**Issue by jermainegug** [astropy/astropy#7200]
I have found that RA is automatically set on the horizontal axis and DEC on the vertical, is there anyway to change this?

**Comment by astrofrog** [comment]
@jermainegug - I'm very sorry for not replying before. Yes, you can set the positioning by doing e.g.

```python
ax.coords[0].set_ticklabel_position('l')
ax.coords[0].set_ticks('lr')
ax.coords[1].set_ticklabel_position('b')
ax.coords[1].set_ticks('bt')
```

This puts the labels for the first coordinate (e.g. RA) on the left axis, ticks on the left and right axis, then the labels for the second coordinate (e.g. Dec) on the bottom axis, and ticks on the bottom and top.

Since there is already a section in the docs on this:

http://docs.astropy.org/en/stable/visualization/wcsaxes/ticks_labels_grid.html#tick-tick-label-and-axis-label-position

I'll close this issue, but please feel free to re-open if you feel the documentation could be made clearer, or if it doesn't work!
