### ISSUE TITLE
No index() for Columns?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#7286]
I'm running v3.0 and I just noticed that I can't index a `Column` object:

    some_col['ID'].index('element')
    *** AttributeError: 'Column' object has no attribute 'index'

Converting the `Column` to list first, does work:

    aa = list(some_col['ID'])
    aa.index('element')

Does this feature have a different name instead of `index()` or is this not something that can be done with a `Column`? If so, could it be added? It's such a basic operation to perform that it's weird not having it.

**Comment by mcara** [comment]
Did you have a look at http://docs.astropy.org/en/stable/table/indexing.html?

**Comment by Gabriel-p** [comment]
I have @mcara, as far as I can tell the steps to reproduce the `.index()` functionality starting from a `Table` object are:

1. Add an index with `t.add_index('ID')`
2. Use the `loc` property: `t.loc['element']`

Not only is this far more complicated than a simple `,index()` call, it does not seems to work on `Column` objects.

**Comment by mcara** [comment]
@Gabriel-p I am not very familiar with `astropy.tables` and because you did not mention `add_index()` and `loc()` in your issue - I just thought I would ask this just to make sure that you are not satisfied with what is available.

Based on what I see in the code, it seems that columns inherit from `numpy.ndarray`. So, you can do the same thing on them as you could do on a 1D `numpy` array. So, you could do this:
``` python
idx = np.flatnonzero(some_col['ID'] == 'element')[0]
```
or
```python
idx = some_col['ID'].tolist().index('element')
```
In my opinion, this is not awfully complicated, but if there is enough interest to introduce this method - maybe someone will think of introducing it. However, from what I see, columns are not limited to hold exclusively 1D data (lists) but can hold, e.g., 2D data. In that case situation becomes more complicated as it is not obvious how to perform the search.

**Comment by saimn** [comment]
Yes, `Column` objects are Numpy arrays, so indexing can be done the Numpy way, e.g. `np.where(some_col['ID'] == 'element')`, or `some_col['ID'][some_col['ID'] == 'element]'` to retrieve or modify the values.

**Comment by Gabriel-p** [comment]
I think the comments by @mcara and @saimn have settled this issue. Thank you both!
