### ISSUE TITLE
Velocity transformation from GCRS to ITRS

### ISSUE THREAD

**Issue by Tarlan0001** [astropy/astropy#7294]
I have the following code, which works correctly.

```
from astropy import coordinates as coord
from astropy import units as u
from astropy.time import Time
from astropy import time

now = Time('2018-03-14 23:48:00')
# position of satellite in GCRS or J20000 ECI:
xyz=[-6340.40130292,3070.61774516,684.52263588]

cartrep = coord.CartesianRepresentation(*xyz, unit=u.km)
gcrs = coord.ITRS(cartrep, obstime=now)
itrs = gcrs.transform_to(coord.GCRS(obstime=now))
loc= coord.EarthLocation(*itrs.cartesian.xyz)
print(loc)
```

But, how to transform velocity?  I didn't find such a functionality in the documentation.

**Comment by Tarlan0001** [comment]
Solved, found solution in the source code.

**Comment by bsipocz** [comment]
@Tarlan0001 - There are quite a few velocity related examples in the following page: http://docs.astropy.org/en/stable/coordinates/velocities.html#transforming-frames-with-velocities

Let us know if you found that page but were still missing something to find it useful. Otherwise if you didn't see that page before, but it would have been the one you were looking for, please close the issue.

**Comment by Tarlan0001** [comment]
Thanks, may be closed
