### ISSUE TITLE
Development version only activates in distribution directory

### ISSUE THREAD

**Issue by emilydeibert** [astropy/astropy#7299]
These instructions http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#activate-development-astropy say that you should try to activate the development version _outside._ the distribution directory. When I do this, I get my local version (2.0.3) instead. I only get the development version when I am inside the astropy distribution directory.

I first tried following the instructions exactly, but since I am using Python3 it didn't work (as noted in the instructions). I then set up a virtual environment instead using conda, but I'm still getting the same issue.

 I believe this is because my environment installs astropy 2.0.3 automatically, and it is not being overwritten when I install the development version. Should the instructions be changed? I tried installing it via `python setup.py install` as well as `python setup.py develop`.

**Comment by emilydeibert** [comment]
The solution seems to be uninstalling astropy after creating the conda environment, and then installing the developer version. I'm happy to change the documentation if desired but I'm not sure if this should be included in the instructions or not.

**Comment by eteq** [comment]
I think it's a good idea to change the directions as you say @emilydeibert. 

I haven't tried this in a while, but I know that the rules for what takes precedence when something is installed *and* you do `develop` are rather ill-determined. It might be even platform-specific, so that for *some* people it works out of the box and for others they need to do what you had to do. But better to be safe than sorry here, and your approach will definitely work more often than just `develop` without the uninstall!

**Comment by drdavella** [comment]
@emilydeibert my experience has been much the same, so it's a good idea to document it. In general it seems like installed packages take precedence over ones installed in development mode (I guess the term "installed" is a little overloaded here). It's certainly a bit confusing, but updating the docs will mean your struggles were not in vain 😄.
