### ISSUE TITLE
Tool to get SFD dustmap values

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#733]
(This is based in part on the discussion in #700) 

We should add a function/class that retrieves the Schlegel, Finkbeiner, and Davis 1998 dustmaps, caches them, and uses that to get E(B-V) at arbitrary locations (specified by objects from `astropy.coordinates`).  We probably also should include the R_X coefficients from the SFD paper, so people can get out extinctions directly in their preferred bandpass.

We might also include the improved [Schlafly & Finkbeiner 2011](http://adsabs.harvard.edu/abs/2011ApJ...737..103S) calibrations, although that might not be "standard" enough yet.

Note that there's already a python/numpy [implementation of the interpolation scheme in astropysics.](https://github.com/eteq/astropysics/blob/master/astropysics/obstools.py#L2272) So most of the work is already done between that and the astropy data/caching framework.

**Comment by sebaguro** [comment]
etud had an excellent method in "astropysics" to return E(B-V) values for multiple sources it was quick and one needed to first download the SFD_dust_4096_ngp.fits SFD_dust_4096_sgp.fits (granted)

I think astropy + affilated packages (incl. astroquery) currently do not efficiently support a E(B-V) query for a large number of sources? If true would it not be worth reconsidering to include the etud astropysics code into astropy (as mentioned by Erik in one of the related tickets)?

**Comment by kbarbary** [comment]
I haven't looked at the implementation in astropysics lately, but we have similar code in sncosmo that could be upstreamed:

http://sncosmo.readthedocs.org/en/v1.1.x/api/sncosmo.SFD98Map.html (class interface)
http://sncosmo.readthedocs.org/en/v1.1.x/api/sncosmo.get_ebv_from_map.html (functional interface)

It also requires the user to download the maps manually, just because I felt dodgy about automatically dumping 200MB+ into `~/.cache/`.

**Comment by sebaguro** [comment]
I guess being able to access many E(B-V) values (for many sources)
is useful for many extra-galactic projects and will become increasingly
useful in LSST era. Maybe it is a good idea to have kbarbary "sncosmo" or etud
"astropysics" version in core because of this argument?

Do I understand correctly that the newer 2011 E(B-V) values are just
found by re-scaling the 1998 E(B-V) values by a constant value?  Such that:
 
 E(B − V)2011 = 0.86[E(B − V)1998]

**Comment by kbarbary** [comment]
For anyone finding this issue: there are now a few stand-alone pip packages that provide this functionality:

- [sfdmap](https://github.com/kbarbary/sfdmap) (factored out from sncosmo)
- [mwdust](https://pypi.python.org/pypi/mwdust)
- [dustmaps](http://dustmaps.readthedocs.io/en/latest/)

Brief comparisons [here](https://github.com/kbarbary/sfdmap#alternatives).

**Comment by bwinkel** [comment]
> A similar tool that would be interesting to include for X-ray astonomy is a function to obtain the total galactic neutral hydrogen column density for given coordinates. A good all-sky survey to use is the Leiden/Argentine/Bonn (LAB) Survey of Galactic HI, found in VizieR at http://vizier.cfa.harvard.edu/viz-bin/Cat?VIII/76

Please don't use LAB data anymore. Even the main author of the data release paper (Peter Kalberla, a colleague of mine) considers it as deprecated. There is a much better alternative now: [HI4PI](http://cdsarc.u-strasbg.fr/viz-bin/qcat?J/A+A/594/A116). HI column densities are provided in HEALPix and various other projections.

**Comment by cdeil** [comment]
@eteq - Given that this is available in other packages now (see comment https://github.com/astropy/astropy/issues/733#issuecomment-262022484 by @kbarbary above), maybe close this issue from 2013? Or would you still prefer to add / maintain this feature in Astropy core?

**Comment by kakirastern** [comment]
Hi, am triaging and would like to check if this Issue should be kept open... Would opening a new issue and continue the discussion there in light of the developments leading up to late Feb 2019 be more favorable? 

Please advise. Thanks!

**Comment by bsipocz** [comment]
I'm going ahead and close this issue. As @kakirastern pointed out, not much happened in core about it but in the meantime other packages and affiliated packages have been created to cover the topic.
