### ISSUE TITLE
search_around_sky is too slow

### ISSUE THREAD

**Issue by ellot** [astropy/astropy#7358]
I am handling a catalog with sources more than 10 millions. I found the "search_around_sky" is much slower than the "separation" method.

**Comment by pllim** [comment]
Hi. Please provide your `astropy` version, the exact way you are using the function, machine specs, and some timing info. Also, does using the latest dev version from `master` give you any improvement?

**Comment by kakirastern** [comment]
Hi, am triaging and would like to check to see if the Issue has been adequately addressed... @ellot, could you provide more details about the problem you had been experiencing so that some follow-up can be facilitated? Would appreciate any input such as more background information, ideas, suggestions, or even opinions you might have.
