### ISSUE TITLE
WCSAxes changes font size and axis spine styles

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#7485]
`WCSAxes` seems to modify or set some matplotlib style settings

Compare:
```python
with mpl.rc_context(rc=mpl.rcParamsDefault):
    fig, ax = plt.subplots(1, 1, figsize=(4, 4))
```
![image](https://user-images.githubusercontent.com/583379/40329045-293ee500-5cfd-11e8-91d6-c8cc50acc87c.png)

vs. 
```python
with mpl.rc_context(rc=mpl.rcParamsDefault):
    fig, ax = plt.subplots(1, 1, figsize=(4, 4), 
                           subplot_kw=dict(projection=wcs))
```
![image](https://user-images.githubusercontent.com/583379/40329050-2e6386a8-5cfd-11e8-97ab-4e6fe53d7b7b.png)

* Does it need to change the tick font size? 
* Any idea why markers are appearing at the intersections of the axis spines? 
* It also seems to add ticks to the upper and right axes.

cc @astrofrog

**Comment by astrofrog** [comment]
Just for some background, WCSAxes draws everything from scratch, so it's up to us to make sure that it does actually reproduce the default axes. I'm assuming these defaults include your matplotlibrc file? (the true default matplotlib includes a sans-serif font).

If so the issue is we don't yet take into account all the different rcParams - this is a WIP that I started here: https://github.com/astropy/astropy/pull/6992 - maybe you could try that out to see if that helps?

For the markers - I have no idea! That does seem like a bug.

For the ticks on the upper and right, I think it does make sense for images, so I think that's ok?
