### ISSUE TITLE
astropy.coordinates.concatenate drops velocity data

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#7506]
Behavior right now:
```python
c1 = coord.SkyCoord(ra=100*u.deg,
                    dec=-20*u.deg,
                    distance=10*u.kpc,
                    pm_ra_cosdec=10*u.mas/u.yr,
                    pm_dec=10*u.mas/u.yr)
coord.concatenate((c1, c1))
```
outputs:
```
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, kpc)
    [(100., -20., 10.), (100., -20., 10.)]>
```

But this should preserve the velocity (proper motion) data.

We'll have to decide what to do if one frame has velocity data (full or partial) and the other doesn't, or has different components (e.g., one as proper motions, the other has radial velocity).

**Comment by bsipocz** [comment]
@sunilk747 - I don't think anyone is actively working on this, but please note the note above that some decisions need to be made.

But if you have a working solution, please feel free to open a PR and that discussion can happen there.

**Comment by eteq** [comment]
@adrn - I'd propose the following as the behavior:

``coord.concatenate([c0, c1, c2,...cn])``

* If all have velocities of the same kind, do the obvious thing of just combining
* If they all have velocities, but some are radial and other are pms, or a mix of all three, always revert to 3-velocities, assuming the missing one is "0" in whatever frame it's defined in (because e.g. a radial velocity in ICRS is not an all-radial velocity in some other frame, and the ``cn``s aren't guaranteed to be the same frame)
* If some have velocities and some don't, don't drop velocities, but instead assume all-0s in the input frame.  In mixed-frame cases this will always yield 3-velocities, but if e.g. ``c1`` has a `RadialVelocity`, and cns have *no* velocity but are all in the same frame, the result should have a `RadialVelocity`, but it should be all zeros (except for the first one).

**Comment by adrn** [comment]
@eteq On points 2 and 3, I think I'd prefer to assume `nan` or play it safe and raise an exception.

**Comment by eteq** [comment]
Good point, @adrn.  I think I favor the `NaN` solution because there *are* use cases of wanting to do things with e.g. radial velocities only and wanting to mix with things that are not radial velocities. Relatedly, I worry that the `NaN` might "infect" some calculations that involve going through an intermediate frame, though.  

What about having the default behavior be `NaN` but add a keyword like "vfill" that defaults to `nan` but could be `0`?

**Comment by adrn** [comment]
RE: @eteq's points 2 and 3 above, @eteq and I just discussed this offline and decided that it would be better to raise an exception if the velocity data isn't compatible. That way the onus is on the user to "fill" the other velocity components with whatever they want if the velocity data isn't compatible (e.g., concatenating 2 coordinates, 1 with an RV and no proper motions, the other with proper motions and an RV).
