### ISSUE TITLE
Request for better warning: PyYaml package is required for Unit support is astropy.io.ascii.read

### ISSUE THREAD

**Issue by ccossou** [astropy/astropy#7564]
The problem occurs with the following code:
```python
from astropy.io import ascii
t = ascii.read('WASP43_LDCs_A100.txt')
assert t["wavelength"].unit != None
```

The data file:
[WASP43_LDCs_A100.txt](https://github.com/astropy/astropy/files/2101773/WASP43_LDCs_A100.txt)

If the module pyyaml is not installed, Unit are not working properly and instead of having "microns", I simply get "None" and my code crashes. 

Thanks to astrofrog (from the astropy Slack), we've successfully linked my crash problem with this package missing. 

Since this package is not automatically installed with astropy, and we currently don't get any warning that we might need it. 

Could something be done to:

1. warn user, 
2. add a dependency to astropy (either in ascii.read or in astropy.unit) ?

I would personnally be in favor of simply adding "pyyaml" to the requirements.txt, but I don't know what is your policy in the Astropy Team, and maybe another solution might be preferred.

**Comment by pllim** [comment]
General requirements policy is that `numpy` is the only hard requirement for Astropy to work (and also `pytest` for testing). Everything else should be optional (e.g., `scipy`, `matplotlib`, etc). Adding a warning should be non-controversial enough.

**Comment by bsipocz** [comment]
@ccossou - FYI the dependencies detailed quite thoroughly on the main install page: http://docs.astropy.org/en/stable/install.html#requirements

I agree though that a warning or even an exception would be useful.

**Comment by ccossou** [comment]
I read the dependencies but I hadn't linked PyYAML to my Unit problem since it only talked about Table and ASCII files and my error was with Unit(). 

To be honest, I even thought that the Table thing didn't concern me directly. I didn't knew it was a Table once read. But that's because I was desperately looking for the "Unit" keyword, while "enhanced CSV" was what I was looking for.

**Comment by taldcroft** [comment]
This is a bit of a corner case.  As noted indirectly, the file in question is ECSV format, which requires pyyaml.  But the way that you read the file was using the "guessing" functionality of io.ascii to guess the format.  Since io.ascii doesn't know the file format, when guessing it just skips over any format that generates an exception.  This happens a lot under the hood and you never see it.  So when using ECSV fails because of the missing dependency it carries on and reads it as a normal space-separated file, and there is no unit information.

If however you read in that file with the format specified (`format='ecsv'`) then you get an exception.
```
In [2]: t = ascii.read('/Users/aldcroft/Downloads/WASP43_LDCs_A100.txt', format='ecsv')
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/anaconda3/envs/noyaml/lib/python3.6/site-packages/astropy/table/meta.py in get_header_from_yaml(lines)
    320     try:
--> 321         import yaml
    322     except ImportError:

ModuleNotFoundError: No module named 'yaml'
...
ImportError: `import yaml` failed, PyYAML package is required for serializing mixin columns
```
But I agree this is confusing.  In theory if a file is ECSV (defined by the presence of the correct opening stanza), then failing to read as ECSV should at least generate a warning.

**Comment by taldcroft** [comment]
@pllim - the fix for this is low effort, but unfortunately does require some understanding of `io.ascii` to do correctly, so I updated the labels.

**Comment by taldcroft** [comment]
See #7580.
