### ISSUE TITLE
Possible units bug in array slicing

### ISSUE THREAD

**Issue by findesgh** [astropy/astropy#7582]
Playing around a bit and following a discussion on astropy slack, I believe there is a bug in assigning a quantity to an array slice:

```python
In [2]: import numpy as np

In [3]: from astropy import units as u

In [4]: arr = np.ones(3)

In [5]: arr[2:3] = 1*u.cm/u.m

In [6]: arr
Out[6]: array([1., 1., 1.])

In [7]: arr[2:3] = [1*u.cm/u.m]

In [8]: arr
Out[8]: array([1.  , 1.  , 0.01])

In [9]: arr[2] = 1*u.cm/u.m

In [10]: arr
Out[10]: array([1.  , 1.  , 0.01])
```

What to the units experts make of this?

**Comment by pllim** [comment]
cc @mhvk

**Comment by mhvk** [comment]
@findesgh - this is a version of a known bug [1], that array methods do not check `ndarray` subclasses properly, but just take their values. So, if you do
```
arr[2:3] = 2.*u.kg
```
it sadly just takes the `2` as well...

It is interesting that if you set a scalar or use a list, it does work. I think this is because that causes, effectively, `np.array` to be called on it, which in turn tries to convert the quantity to a float, which goes via `Quantity.__float__`, and we do implement that.

So, there's ideally two things that would happen: (1) have a fix in numpy (non-trivial); (2) update the documentation. Are you interested in doing (2)?

[1] http://docs.astropy.org/en/latest/known_issues.html#quantity-issues

**Comment by findesgh** [comment]
Busy time, sorry for taking so long. Let me know if I should change anything.

**Comment by pllim** [comment]
This is documented as a known issue in #7656. Since this is all we can do on our side until it is fixed upstream, I think it is reasonable to close this issue. However, feel free to re-open if you feel otherwise. Thank you!
