### ISSUE TITLE
Lomb Scargle False Alarm Probability weird values

### ISSUE THREAD

**Issue by jradavenport** [astropy/astropy#7618]
We (@ZoeHMC and I) are finding that the Flare Alarm Probabilities that `satrapy.stats.LombScargle` produces do not match the amplitudes we expect. Two examples of Kepler/K2 data from our [script](https://github.com/ZoeHMC/K2_Rotation_Summer_2018/blob/master/FindP.py):

in this example, we have a very nice signal, that we find a FAP=0.0
![example with false alarm probability of 0 0](https://user-images.githubusercontent.com/3179868/42180109-ca53062a-7dea-11e8-8fc8-949e933491cc.png)

while here we have a weak periodic signal, but the FAP is only 0.000348. 
![example with false alarm probability 0-1 000348](https://user-images.githubusercontent.com/3179868/42180037-9cc19de8-7dea-11e8-8c85-3b36d65fa4c1.png)

Is there unexpected behavior here? We are never able to get large FAP values for our data.

**Comment by pllim** [comment]
@jakevdp , could you please advise? Thank you.

**Comment by jakevdp** [comment]
I believe the FAP calculation is correct, but you need to keep in mind what it is measuring.

The FAP estimates the probability of attaining a peak as high or higher than the one you observed under the null hypothesis that your signal is pure Gaussian noise.

In particular, it's not a measure of how probable it is that the peak you observed is false, though that's how it is often presented.

My overall recommendation would be to not use the false alarm probability as an indicator of whether the signal you measure is trustworthy – it's fundamentally the wrong statistic for that purpose (but it's often used because the right statistic doesn't really exist).
