### ISSUE TITLE
Daily Updating of IERS EOP data

### ISSUE THREAD

**Issue by besu5739** [astropy/astropy#7623]
For my application, I need to use the most up-to-date EOP data, e.g. 10 day old prediction data won't be sufficient.  IERS provides daily EOP files which can be found here: http://maia.usno.navy.mil/ser7/finals2000A.daily.  It is possible to concatenate this with the long term file that gets updated weekly.  I believe this would be a valuable feature to have added as an option for people who need more accurate EOP data.  For additional context, see below:

IERS data access (astropy.utils.iers) from http://docs.astropy.org/en/stable/utils/iers.html:

"The IERS Service provides the default online table (http://maia.usno.navy.mil/ser7/finals2000A.all) and updates the content once each 7 days. The default value of auto_max_age is 30 days to avoid unnecessary network access, but one can reduce this to as low as 10 days."

**Comment by mhvk** [comment]
@besu5739 - It would be nice if this could be done automatically! But while not super-difficult it is also not a trivial few-line change and hence I'm not sure who would have the time to actually implement this (I wrote most of the code, but sadly don't foresee having time to do it). Would you be interested to attempt it yourself?

**Comment by besu5739** [comment]
You are of course correct that it is not a trivial change, hence I posted the issue here :).  I'm pretty new to using Astropy and Python in general, but I will give it a shot.  I already have code that does this in MATLAB, so I have something to go off of and validate results with.

**Comment by mhvk** [comment]
@besu5739 - great that you are willing to give it a go! You'll probably already have seen that the "action" is all in https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py.
The class you'll want to look at is `IERS_Auto`, and in particular its `_refresh_table_as_needed` method:
https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L664

It may be good to think a little on how it should work. What do you have in mind? Simplest might be to trigger looking at daily predictions when `auto_max_age` is less than the week or so that one gets with the `finals2000A.all` files.  (If that makes sense, haven't looked at exactly what `.all` and `.daily` contain.)

**Comment by besu5739** [comment]
@mhvk `finals2000A.all` contains historical data from 1973 to date, is propagated forward 365 days, and gets updated weekly on Thursdays.  `finals2000A.daily` contains data for the current date +/- 90 days and gets updated daily at ~1705 UTC.  They both contain the same data types and formatting.  

The simplest solution would be to check if the IERS data has been updated for the current date, and if not, pull the most recent `.all` and `.daily` files and just replace the 181 lines in the `.all` file with the corresponding lines from the `.daily` file.  I have no supporting analysis for whether or not this is the ideal solution, but it is how an application I use in MATLAB currently does it.

On a related note, I'm actually a little unsure why in the current iers code `auto_max_age` can't be set to less than 10 when `finals2000A.all` gets updated every 7 days(?)

**Comment by mhvk** [comment]
@besu5739 - OK, thanks for the explanation. In terms of implementation, it might be easiest to just convert all relevant files to IERS tables, then select parts based on dates, and finally join them.

As for the minimum time currently set, that part @taldcroft wrote, but I assume it is just to avoid downloading files too frequently.

Out of curiosity, what are you doing that needs the extra precision?

**Comment by nikkelj** [comment]
I recently wrote a matlab class that has this functionality for a masters thesis, it reads the finals files, and provides a generalized lookup by julian date (perhaps a Time object in this case).  For precision applications, it must also provide a spline interpolation for intra-day values.

Ideally it would also include functionality to allow posterior simulation with predicts at any point in the past as well.  It gets pretty complicated to set that up, but should also really be included in a serious solution.

I will see if I can port & contrib it at some point in the near future.

**Comment by mhvk** [comment]
@nikkelj - it would be great if you could help! Just to be sure: basic lookup of course exists and right now we do interpolate linearly. The issue here is about allowing the predictions to be updated more frequently, possibly combining different files.

There is a separate issue (a very old one...) about better interpolation - #1803 - as I wrote there, ideally we simply port the scheme that is used by IERS itself. That issue seems to me of somewhat more general importance - for instance, for any pulsar timing experiment, the extra precision would remove a small noise contribution.

**Comment by besu5739** [comment]
@nikkelj That would be great!  Unfortunately I've had very little bandwidth to contribute myself, but I'm still invested in seeing this get implemented.

**Comment by nikkelj** [comment]
Thanks for the cross-reference, that helps, yep believe I understand the intent.  I am still pretty new to this lib, and it will still be a while yet before I can find time to do it too, probably spring-ish.
