### ISSUE TITLE
Unknown ufunc apio13

### ISSUE THREAD

**Issue by dkirkby** [astropy/astropy#7665]
Travis tests on a [package derived from the astropy template](https://github.com/desihub/specsim) are failing for `ASTROPY_VERSION=development` with multiple instances of:
```
Unknown ufunc apio13.  Please raise issue on https://github.com/astropy/astropy
```
All other combinations in the test matrix are passing.  A sample travis log is [here](https://travis-ci.org/desihub/specsim/jobs/405690907).

**Comment by mhvk** [comment]
@dkirkby - thanks for reporting! These failures indicate that `Quantity` instances are being passed into erfa. Previously, the units were stripped unconditionally (i.e., the answer would be wrong if the quantity was in the wrong units), but because the erfa routines now is wrapped in ufunc (as of #7502 - it gives a substantial performance boost), `Quantity` attempts to override it, only to find it doesn't know this erfa ufunc. That will change eventually, i.e., the quantity will be converted properly, and I really hope to have that done before 3.1 is released (initial work in #7639).

In the meantime, the easiest thing probably is to ensure a proper array is passed in - this should be as simple as change of `<quantity>.to(unit)` to `<quantity>.to_value(unit)` -- though from the travis log you linked to it is not obvious where that would be... Indeed, I worry it is somewhere in our coordinates code! If it isn't obvious to you too, could you attempt to find a more minimal example that fails?

**Comment by dkirkby** [comment]
Ok, I created an astropy-dev conda env using:
```
conda create --name astropy-dev --clone desi
conda activate astropy-dev
git clone --recursive git@github.com:astropy/astropy.git
cd astropy
python setup.py develop
```
I can now reproduce the problem with:
```
import astropy.time
import astropy.coordinates
import astropy.units as u

sky = astropy.coordinates.ICRS(0 * u.deg, 0 * u.deg)
altaz = astropy.coordinates.AltAz(
    obstime=astropy.time.Time(55000., format='mjd'),
    location=astropy.coordinates.EarthLocation(-1463987.5 * u.m, -5166642.1 * u.m, 3435006.2 * u.m),
    relative_humidity=u.Quantity(0))
```
Replacing the `u.Quantity(0)` with just `0` fixes the problem, which sounds consistent with what you described.

**Comment by mhvk** [comment]
Thanks!  That means the problem is on our side...  Indeed, the error trace points right to the problem! Will fix and add a test to be sure this doesn't recur....

**Comment by mhvk** [comment]
In fact, it is a bug - I can happily pass in a quantity with units of m and I don't get an error.

**Comment by mhvk** [comment]
See #7668 for the fix...
