### ISSUE TITLE
time_delta issue in astropy.Time's UTC format

### ISSUE THREAD

**Issue by shivaksingh** [astropy/astropy#7695]
I was using time delta for generating UTCs for an entire year at an interval of 12 hours.

time_start = Time( str(year)+ '-01-01 00:00:00', scale='utc')
time_start_plus_one_second = Time( str(year)+ '-01-01 00:00:01', scale='utc')
time_start_plus_24_hours = Time( str(year)+ '-01-02 00:00:00', scale='utc')

#time_difference
one_second = time_start_plus_one_second - time_start
one_day = time_start_plus_24_hours - time_start

for day in range(0,days,1):
        for i in range(0,24x60x60,step):

            time = time_start + (one_second*i) + (one_day*day)
            print (time)

for year 2015 the output I got is fine until i reach July 1:

2015-06-29 00:00:00.000
2015-06-29 12:00:00.000
2015-06-30 00:00:00.000
2015-06-30 12:00:00.000
2015-06-30 23:59:60.000
2015-07-01 11:59:59.000
2015-07-01 23:59:59.000
2015-07-02 11:59:59.000
2015-07-02 23:59:59.000
2015-07-03 11:59:59.000

Similar is the output for year 2012. 

But if I enter 2017,2016,2014 the output is exactly what I expected:

2017-06-29 00:00:00.000
2017-06-29 12:00:00.000
2017-06-30 00:00:00.000
2017-06-30 12:00:00.000
2017-07-01 00:00:00.000
2017-07-01 12:00:00.000
2017-07-02 00:00:00.000
2017-07-02 12:00:00.000
2017-07-03 00:00:00.000
2017-07-03 12:00:00.000

Interestingly year 2015,2012 had leap second introduced in month of July by IERS.

As per my knowledge, UTC is supposed to be independent of it as we have UTI for irregularities in earth revolution.

I request you to give a look.

Sincerely

**Comment by mhvk** [comment]
Indeed, UTC has leap seconds. If you want to avoid those, you'll need to use TAI. Note that for this reason your `TimeDelta` is already in `TAI` - it is not possible to have a delta in UTC since one needs to know the associated dates to know what "1 day" means in terms of seconds.

If this answers your questions, could you close this issue? Or, if you can suggest some way the documentation could be better, do let us know (or make a pull request...)
