### ISSUE TITLE
Add narrative docs for WCSAxes's plot_coord

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7799]
At the moment, the very handy ``plot_coord`` method in WCSAxes is only mentioned in the API docs, but we really should add a paragraph about it in the narrative docs.

**Comment by pllim** [comment]
@giang-nghg , thank you for your interest! Please see http://docs.astropy.org/en/stable/development/workflow/development_workflow.html for some help in how to contribute. Perhaps @astrofrog can advise on the actual content to be added to narrative docs.

**Comment by pllim** [comment]
> should I leave this issue for someone else who hasn't contributed to astropy?

Not necessarily. Given the number of open issues, there is no shortage for everyone interested. 😅  I'll leave it up to your discretion.

**Comment by giang-nghg** [comment]
Ok, then I'll continue with this. @astrofrog I don't know the library or its audience well to come up with a guide for said method. Can you suggest what kind of example/guide do you want to add for it? Thanks!

**Comment by astrofrog** [comment]
@giang-nghg - I think it would make more sense to focus on a different issue, as this one does require a good understanding of the use cases for ``plot_coord``.

**Comment by giang-nghg** [comment]
Ok, I'll pick another issue then :)

**Comment by davidmpaz** [comment]
Hi all,

If it is ok for everybody, I would like to have my take on this one :) 

Since I wanted to start contributing and am a novice, I have already read:

* https://www.astropy.org/contribute.html
* https://docs.astropy.org/en/latest/development/codeguide.html
* http://docs.astropy.org/en/stable/development/workflow/development_workflow.html

That being said, let me get o the point. I see the docblock in the method providing developer documentation. Allow me to ask please, what are the  expectations for this task ? And where to add the narrative?, I did look into the wcs directory (docs/wcs) for `plot_coord` but did not found any reference to it.

thanks in advance,
David

**Comment by davidmpaz** [comment]
Hi @astrofrog,

I was reading:

> Perhaps @astrofrog can advise on the actual content to be added to narrative docs.

 Any hints on what to do achieve/write here? 

thanks in advance,
Cheers

**Comment by astrofrog** [comment]
I think we should update this section:

https://docs.astropy.org/en/stable/visualization/wcsaxes/overlays.html

to first mention plot_coord and scatter_coord, and then continue to show the current examples as a more general/advanced way.

**Comment by davidmpaz** [comment]
Can someone suggest resources where a non specialist like me could learn about coordinate systems. How are used in Astronomy, coordinate systems with high curvature, etc... Please keep in mind that despite I have a (rusty) Math background from Computer Sciences, my Astronomy background is the one of someone from High School :-)

thanks in advance,
Regards
