### ISSUE TITLE
EarthLocation.of_address now fails because Google maps API requires a key

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#7867]
As of June 2018, the [Google maps API requires a dev key](https://developers.google.com/maps/billing/important-updates). This breaks `EarthLocation.of_address`.

**Comment by astrofrog** [comment]
Does OpenStreetMap provide an API for this?

**Comment by bsipocz** [comment]
How come that CI didn't choke on this? Is there a way for the tests to distinguish between issues like this and a failure due to the API rate limits?

**Comment by pllim** [comment]
As for why CI didn't choke, it is because of #7266 (I did it) 😬 😬 😬

**Comment by eteq** [comment]
I like @astrofrog's suggestion of defaulting OSM: https://wiki.openstreetmap.org/wiki/Nominatim has the info on that.  From that you can do e.g.: ``https://nominatim.openstreetmap.org/search.php?q=3700+san+martin+dr%2C+baltimore%2C+md&format=json``, and the first result indeed turns out to be the correct one (STScI).  The JSON is not too different from what google provides so it Should Be A Quick Fix™️.

So I'd propose the following as a solution:
1. default to OSM
2. @pllim's suggestion of introducing a `google_key` keyword to get back the old behavior. The docstring can provide links to the google developer console and instructions on how to get that.  Not sure how to implement this in the tests, but probably just not worth it at this point?

**Comment by adrn** [comment]
How should we test the `google_key` part? I guess we can make a key for Astropy and add it as an env variable to CI, but this seems like a lot of engineering...

**Comment by pllim** [comment]
It is not good practice to publish the key, so if the env variable is publicly accessible when added to CI, please don't do it. And to obtain the key, it needs to be associated to a Google Account (I guess you can use any existing project Gmail for that). I agree with @eteq  that testing with the key is not worth the trouble.
