### ISSUE TITLE
Change default cosmology?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8003]
Should we consider changing the default cosmology for v3.1? Currently, this is WMAP9, but presumably we should try and keep up to date and change this to Planck15? I feel like we can't stay stuck on WMAP9 forever - I think people will realize that for stability they should specify an explicit cosmology (we say something to that effect in the docs):

> In general it’s better to use an explicit cosmology (for example WMAP9.H(0) instead of cosmology.default_cosmology.get().H(0)). Use of the default cosmology should generally be reserved for code that will be included in the Astropy core or an affiliated package.

Obviously this would need a what's new entry!

**Comment by eteq** [comment]
I guess I'm not sure we actually want to do this because of two things:
* My understanding is that the final Planck and WMAP results are actually somewhat in conflict.  So we may be "picking a side" here, and if we want to stick with WMAP it's best not to change.  And I guess if we're picking a side, paradoxically, it may be better to pick the one with somewhat larger error bars (WMAP) since that makes it more "conservative".
* I just noticed no one has added the Planck 2018 (final end-ofmission) parameters - presumably that's what we'd want if we wanted "the latest"...? #8006

That said, if we get #8006 in maybe that overrides the first concern if we just go on the "newest/lower error bars is best" principle.

**Comment by aconley** [comment]
I think you are overthinking what the default cosmology is for.  I sincerely hope anybody who is in the state where the disagreement matters knows enough to not just chose the default.  The people who don't just want 'the latest', and the truth is Planck is the more accepted consensus, disagreement or not.

Yes, the latest should be added from #8006.  I was waiting until they were accepted, but then promptly forgot.
 
Plus, sticking with WMAP counts as a stance at this point.

**Comment by eteq** [comment]
Gotcha, good points all, @aconley - that sounds reasonable.  So we can either default to Planck18 if we resolve #8006 in time for release, otherwise Planck15?

**Comment by aconley** [comment]
That sounds good to me.

**Comment by bsipocz** [comment]
@eteq @aconley - has the default been changed to Planck15 yet? If not, please get it done asap so it'll end up in 3.1 RC

**Comment by aconley** [comment]
I was thinking we were too close for that, but sure, will do.

**Comment by bsipocz** [comment]
Changing the default should happen only in a major release, and we've talked about this quite a lot, so I very much suppose it can end up in 3.1, but only if it makes the RC. I'm waiting for one more fix that should happen tonight/tomorrow, and then ~ ready to make the RC.

**Comment by aconley** [comment]
So it is tight.  I will not be able to work on this during working hours tomorrow, so hopefully the tests on #8123 pass modulo astropy-bot.

I suppose one of these days I should get work approval to contribute; it wouldn't mean I spent more time on it, but at least I could do minor things from work.

**Comment by bsipocz** [comment]
Thank you @aconley!

**Comment by bsipocz** [comment]
#8123 is merged, so this can be now closed.
