### ISSUE TITLE
Moffat2DKernel FWHM

### ISSUE THREAD

**Issue by ycopin** [astropy/astropy#8095]
Moffat2DKernel FWHM

https://github.com/astropy/astropy/blob/2b8fe1305b2689d8b2715f98985e36f2c7d5c0d9/astropy/convolution/kernels.py#L806

is wrong (compare w/ https://github.com/astropy/astropy/blob/2b8fe1305b2689d8b2715f98985e36f2c7d5c0d9/astropy/modeling/functional_models.py#L2291).

It should either use built-in fwhm model property, or
```
fwhm = 2.0 * gamma * (2.0 ** (1.0 / alpha) - 1.0) ** 0.5
```

BTW, I suspect the flux normalization is wrong too (it looks too simple).

**Comment by pllim** [comment]
The convolution kernel was added by @cmccully in #3965

**Comment by saimn** [comment]
This is probably because of the confusion between astropy names and the usual ones (e.g. https://www.gnu.org/software/gnuastro/manual/html_node/PSF.html): astropy's alpha is beta, and gamma is alpha). So :+1: to use the model's fwhm, that I think was added later.
For the amplitude, the kernel is normalized anyway, we can probably just remove the factor.

**Comment by saimn** [comment]
Good catch by the way! This will enlarge a bit the default size for the kernel.

**Comment by saimn** [comment]
To illustrate the impact: (where alpha is astropy's gamma :grin:)
```
<Table length=3>
alpha      fwhm old      size old      fwhm new     size new
int64      float64        int64        float64       int64  
----- ------------------ -------- ----------------- --------
    3 2.0392981141358346        9 3.861565517433496       17
    4  1.739917768184329        7 5.148754023244662       21
    5 1.5424570269386961        7 6.435942529055827       27
```
