### ISSUE TITLE
Precision issue when slicing time

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8132]
There are a variety of issues open currently related to precision, but I believe this one isn't covered:

```
>>> times = Time([1, 2, 3, 8, 9, 12], format='unix', scale='tai')
>>> times[0]
<Time object: scale='tai' format='unix' value=0.9999999999921627>
```

There is no arithmetic involved here, unlike #7899 and https://github.com/astropy/astropy/issues/6970

**Comment by astrofrog** [comment]
I think this is because of the internal conversion from seconds to fractional days, and is maybe expected. Feel free to close if so.

**Comment by mhvk** [comment]
Yes, it is not due to slicing, but rather due to how ndarray presents values in arrays with slightly less precision than are given for scalars:
```
In [5]: times.value
Out[5]: array([ 1.,  2.,  3.,  8.,  9., 12.])

In [6]: times.value[0]
Out[6]: 0.9999999999921627
```

So, let me indeed close this (it might be good to document the rounding issue better, but on the other hand I fear it would make very little difference, as it is something that you really only think about when you encounter it).
