### ISSUE TITLE
Name of uncertainties: StdDevUncertainty vs. VarianceUncertainty vs. InverseVariance

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#8151]
There is a bit of inconsistency between the names. The first (`StdDevUncertainty`) is somewhat abbreviated and has the "Uncertainty" suffix, the second (`VarianceUncertainty`) uses the full name and the suffix, while the last one (`InverseVariance`) uses the full name without suffix.

Since they shouldn't be "offically released" yet we still could make the names more consistent with `StdDevUncertainty` (the already released one)? Maybe `VarUncertainty` and `IVarUncertainty` (or `InvVarUncertainty`)?

Not sure if this is actually necessary, I just noticed and wanted to ask if someone else is bothered about the naming. 😅

**Comment by bsipocz** [comment]
Would be nice to sort this out before the release ;)

**Comment by MSeifert04** [comment]
@mwcraig

**Comment by mwcraig** [comment]
I thought about this for a while when picking the new names. What I would really like to do is go with longer names, ideally without `Uncertainty` in them at all. So my ideal would be `StandardDeviation`, `Variance`, and `InverseVariance`. These are all camera and explicit, and presumably one doesn’t need the reminder that one is using an `Uncertainty` if you know to use one.

I think I went with the names actually in the PR to avoid deprecating `StdDevUncertainty` (and it avoid annoying people who use it with a deprecation warning), added `Uncertainty` to `Variance` to be consistent with `StdDevUncertainty` but didn’t put `Uncertainty` on `InverseVariance` because it was too long.

What do you think about going the route of my preferred names? I can do the change later today or on Friday. 

If we do change the name of `StdDevUncertainty` I’m inclined to leave the old name in without a deprecation warning to avoid another overwrite/clobber debate. 

Thoughts?

**Comment by MSeifert04** [comment]
Good points.

> to avoid another overwrite/clobber debate.

Yeah, we don't need one of these again 😄 

Personally I would prefer not changing or aliasing the `StdDevUncertainty` class and just naming the new classes similarly, it's consistent and doesn't require anyone to change their code (even if it's just following the "approach we recommend"). 
But it's just a question about how consistent we want to be - it's just slightly bugging me...

**Comment by pllim** [comment]
C'mone, overwrite/clobber debate is so 2016. Moffat alpha/beta/gamma is all the rage now. :wink:

**Comment by MSeifert04** [comment]
> alpha/beta/gamma

so we should provide the uncertainty (or should I say *delta*) problem?

**Comment by mwcraig** [comment]
I'm inclined to punt on this one until the coordination meeting...

**Comment by MSeifert04** [comment]
Okay. Sounds good to me.

**Comment by bsipocz** [comment]
Was there any decision about this at the coordination meeting? If yes, 3.2 could be a good time to get the changes in as deprecations and finalize them in 4.0.

**Comment by mwcraig** [comment]
Not that I recall.... @crawfordsm do you remember?

**Comment by bsipocz** [comment]
Removing milestone, though I would hash out that 4.0 is the best time to rename things.

**Comment by saimn** [comment]
Probably too late to rename things now isn't it ? Should we close ?

**Comment by bsipocz** [comment]
Yes, it feels like this ship might have sailed. Next convenient renaming is in 1.5 years with the new LTS release. 

I leave the closing of the issue to the subpackage maintainers, as they yet to comment on it.

cc @eteq @mhvk @astrofrog

**Comment by pllim** [comment]
I trust the bot more. 😏 🤖

**Comment by astrofrog** [comment]
Well we can still rename if we want, preserving compatibility for the old names without deprecation for now.
