### ISSUE TITLE
CODATA 2018 + Revision of the SI

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8155]
cc @mhvk and @adrn 

#### References

https://en.wikipedia.org/wiki/Redefinition_of_SI_base_units (thanks to @bsipocz )

http://iopscience.iop.org/article/10.1088/1681-7575/aa950a/meta

https://www.nist.gov/publications/data-and-analysis-codata-2017-special-fundamental-constants-adjustment-revision-si

http://www.codata.org/committees-and-groups/fundamental-physical-constants

**Comment by mhvk** [comment]
And cc @stargaser - I have not quite wrapped my head around what this means for `constants` and `units`.

p.s. Funny how one can read the news without realizing impacts...

**Comment by astrofrog** [comment]
I don't think this really needs the 'Refactoring' label - we have infrastructure in place to deal with new sets of constants.

**Comment by pllim** [comment]
@astrofrog , what about the "revision of SI" part?

**Comment by pllim** [comment]
Took a small stab at some of this over at #8167.

**Comment by mhvk** [comment]
From my https://github.com/astropy/astropy/pull/8167#pullrequestreview-177673593:
I worry we are misinterpreting the status of things: from Newell et al. http://iopscience.iop.org/article/10.1088/1681-7575/aa950a, it seems this is a two-step process. For 2017, there is an adjustment of just those fundamental constants, so that the best possible values are set before fixing them. But as I understand it, in the 2017 system these still have measurement errors. Only in the 2018 system will they become fixed values and will the rest be adjusted.

I wonder if this means we should just try to get ready for the 2018 adjustment for 3.2, and leave things as they are in 3.1. Certainly, that seems to be what NIST is doing [1], so we are in good company...

[1] https://physics.nist.gov/cuu/Constants/

**Comment by stargaser** [comment]
I agree that we should prepare this for 3.2. I think we should make a CODATA2018 version and not make CODATA2017. 

The CODATA2018 update appears to be guaranteed [2] to appear by 20 May 2019. 

[2] https://www.bipm.org/en/the-si/

**Comment by pllim** [comment]
OK, feel free to close #8167 .

**Comment by mhvk** [comment]
Changed the title to make clear this is CODATA2018. At least, it gives us some time to think how this affects the various units.

**Comment by bsipocz** [comment]
ping @stargaser - could you please give an update about the status of `CODATA2018`? With the new framework can the new set added to constants?

**Comment by stargaser** [comment]
The redefinition of SI takes effect on 2019 May 20 onwards. `CODATA2018` is also expected to be available on 2019 May 20 (World Metrology Day) [1].

Since this date falls after the 3.2 feature freeze, but before the 3.2 release...I suppose this will have to be remilestoned to 4.0? Otherwise, we'd have to implement a `CODATA2018` placeholder and "fix it" after May 20th.

[1] http://www.codata.org/committees-and-groups/fundamental-physical-constants under "Task Group Outputs".

**Comment by mhvk** [comment]
I'd call that a bug fix... I think it would be great to be ready for it (if someone has the time...)

**Comment by pllim** [comment]
Bug fix as in 3.3 in late May or ...?

**Comment by stargaser** [comment]
If we could make a 3.3 release that would be good, schedule-wise. Or we could treat this as an "astropy constants are outdated" bug on May 20th and add it to a 3.2.1 bugfix release.

I don't think we can drop a `codata2018.py` by this Friday from @pllim 's #8167 and fix it up during 3.2 testing, can we? I think code coverage would fail and it feels too tricky.

**Comment by mhvk** [comment]
Am not sure that much more than @pllim's PR is needed...  And it would be great to have it in for 3.2, and then fix it up (if there is any fixing up to do...). But do you have time? Note that the release calendar [1] has no 3.3; the next release (in Fall) should be 4.0.

[1] https://github.com/astropy/astropy/wiki/Release-Calendar

**Comment by bsipocz** [comment]
If the numbers are out on the 20th of May sharp it may still be able to get into 3.2 if we have a long release candidate testing period. This of course assumes we have the skeleton ready and numbers just needs to be copy pasted rather than anything more substantial.

(and given my travel schedule that is totally what is expected unless we can roll out all the RC issues in a week).

**Comment by pllim** [comment]
Did someone ping me? So, what is the plan? Do you want me to revive my old PR as a new PR?

**Comment by mhvk** [comment]
@pllim - yes, would be great! At least in https://github.com/astropy/astropy/pull/8167#issuecomment-444976586 I seem to have concluded that that was what eventually should happen -- I didn't rethink...

**Comment by pllim** [comment]
Revived in #8595

**Comment by bsipocz** [comment]
Let's keep this issue in this milestone as a reminder until the actual release is out.

**Comment by bsipocz** [comment]
Data is out as of today: https://physics.nist.gov/cuu/Constants/index.html

**Comment by bsipocz** [comment]
This has been partially solved, so I remilestone to 4.0 for the remaining stuff.

**Comment by pllim** [comment]
Is #8761 the remaining PR necessary to fully resolve this issue? Can @mhvk or @adrn confirm that no changes to unit composition is necessary?

**Comment by stargaser** [comment]
Do we still treat `kg` as an irreducible unit? For an example, see the [standard units section of the docs](http://docs.astropy.org/en/latest/units/standard_units.html?highlight=irreducible).

**Comment by mhvk** [comment]
As far as I understand it, the `kg` happily stays a base unit. But it can now be converted into, e.g., `s`, without any uncertainty.

**Comment by pllim** [comment]
As much as I like the progress of science, I hope the constants stay constant for a while now...

**Comment by stargaser** [comment]
The next CODATA update will be the 2022 one. The next IAU meeting will be in 2021. Constants should stay the same for some time!
