### ISSUE TITLE
Error when writing out empty CSV table with fast writer

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8275]
```python
In [1]: from astropy.table import Table
t 
In [2]: t = Table()

In [3]: t['a'] = []

In [5]: t.write('test.csv', format='ascii.csv', fast_writer=True)
WARNING: AstropyDeprecationWarning: test.csv already exists. Automatically overwriting ASCII files is deprecated. Use the argument 'overwrite=True' in the future. [astropy.io.ascii.ui]
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-5-c3427795d222> in <module>()
----> 1 t.write('test.csv', format='ascii.csv', fast_writer=True)

~/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/table/table.py in write(self, *args, **kwargs)
   2590         serialize_method = kwargs.pop('serialize_method', None)
   2591         with serialize_method_as(self, serialize_method):
-> 2592             io_registry.write(self, *args, **kwargs)
   2593 
   2594     def copy(self, copy_data=True):

~/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/io/registry.py in write(data, format, *args, **kwargs)
    558 
    559     writer = get_writer(format, data.__class__)
--> 560     writer(data, *args, **kwargs)
    561 
    562 

~/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/io/ascii/connect.py in io_write(format, table, filename, **kwargs)
     41     from .ui import write
     42     format = re.sub(r'^ascii\.', '', format)
---> 43     return write(table, filename, format=format, **kwargs)
     44 
     45 

~/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/io/ascii/ui.py in write(table, output, format, Writer, fast_writer, overwrite, **kwargs)
    910     writer = get_writer(Writer=Writer, fast_writer=fast_writer, **kwargs)
    911     if writer._format_name in core.FAST_CLASSES:
--> 912         writer.write(table, output)
    913         return
    914 

~/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/io/ascii/fastbasic.py in write(self, table, output)
    200         output masked values as empty fields.
    201         """
--> 202         self._write(table, output, {'fill_values': [(core.masked, '')]})
    203 
    204 

~/miniconda3/envs/dev/lib/python3.7/site-packages/astropy/io/ascii/fastbasic.py in _write(self, table, output, default_kwargs, header_output, output_types)
    177         write_kwargs.update(self.kwargs)
    178         writer = cparser.FastWriter(table, **write_kwargs)
--> 179         writer.write(output, header_output, output_types)
    180 
    181 

~/Dropbox/Code/Astropy/astropy/astropy/io/ascii/cparser.pyx in astropy.io.ascii.cparser.FastWriter.write()

UnboundLocalError: local variable 'i' referenced before assignment
```

We should probably exit ``write`` early if there are no rows to write.

**Comment by pllim** [comment]
I am not sure if we want to. There had been request in the past to write out empty table, for whatever reason.

**Comment by mcara** [comment]
> ... request in the past to write out empty table, for whatever reason.

I do not remember now the exact reason; probably related to `photutils` sometimes not finding any sources in our simulations.

I could probably fantasize forever about "reasons". For example, let's assume my code needs to create a table, but for unknown reasons has no data to write to the table. Then I want to save the table to a file (i.e., because user wants to see what is inside the table). Should I just log that the table is empty and have the user look through the log file after they complain to the helpdesk that program X does not create any output? (with time they'll learn that program X _sometimes_ may not output anything). Should the program crash? Or maybe we should create a file with a header (when the table is initialized with some column names) and no rows. Would this be an unexpected behavior? What if my program Y expects to read the table created by program X. If no "empty table file" is created, should program Y assume that the program X was never run, was run but crashed, or that it was run but found no sources?

In my opinion, a file with an empty table conveys some information unlike not having a file at all.

However, currently this `write()` method crashes with all kinds of uninformative errors not obviously related to the table being empty.

**Comment by astrofrog** [comment]
Just to clarify, I just meant exit that specific function early - so basically stop writing the file once the headers have been written out.

**Comment by mcara** [comment]
> ... stop writing the file *once the headers have been written out*.

Yes! That's what I think is the most sensitive approach.
