### ISSUE TITLE
QuantityAttribute cannot have a unit and default=None

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#8276]
```python
import astropy.units as u
from astropy.coordinates import (
    BaseCoordinateFrame,
    QuantityAttribute,
    frame_transform_graph,
    FunctionTransform,
    AltAz,
)


class MyFrame(BaseCoordinateFrame):
    a = QuantityAttribute(unit=u.m)


@frame_transform_graph.transform(FunctionTransform, MyFrame, AltAz)
def trans(my_frame_coord, altaz_frame):
    pass

```

This results in

```
Traceback (most recent call last):
  File "test_astropy.py", line 15, in <module>
    @frame_transform_graph.transform(FunctionTransform, MyFrame, AltAz)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 659, in deco
    register_graph=self, **kwargs)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 813, in __init__
    register_graph=register_graph)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/transformations.py", line 709, in __init__
    for from_nm in fromsys.get_frame_attr_names():
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/baseframe.py", line 690, in get_frame_attr_names
    for name in cls.frame_attributes)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/baseframe.py", line 690, in <genexpr>
    for name in cls.frame_attributes)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/attributes.py", line 105, in __get__
    out, converted = self.convert_input(out)
  File "/home/maxnoe/.local/anaconda3/lib/python3.7/site-packages/astropy/coordinates/attributes.py", line 306, in convert_input
    raise TypeError('Tried to set a QuantityAttribute with '
TypeError: Tried to set a QuantityAttribute with something that does not have a unit.

```

Which is highly surprising behaviour to me.

**Comment by adrn** [comment]
If i remember correctly, `QuantityAttribute` expects a default value, so a fix here would be to do:
```
a = QuantityAttribute(default=0, unit=u.m)
```

I also would have expected this to work:
```
a = QuantityAttribute(default=None, unit=u.m)
```
so this might be something we want to support.

@eteq Was there a reason we don't support a `None` default value?

**Comment by MaxNoe** [comment]
`None` is the default of `default`. And I kind of expected that the default would not blow up.

Is there a way to require frame attributes to be set?

Why is a Frame instantiated (or the Attribute), when a transform is registered?

**Comment by eteq** [comment]
Thanks for finding this, @MaxNoe.  I'd say this is indeed a bug in the sense that either the default should work or it should be a *required* keyword. (i.e., it should fail at `QuantityAttribute(unit=u.m)` rather than only when used. So I've re-labeled this a bug with that in mind.

But to decide which is the better fix between those two options: what would the `value` being `None` and having a unit mean? @MaxNoe - in your use case that prompted this (presumably not this example, which is nice and simple but doesn't illustrate the actual need), why would you *want* the `None` (if at all)?

If there's no clear interpretation I'd say that argues for just making `None` not the default, and adding in a clear error message that says something like "you need to give a default or this won't work".

**Comment by MaxNoe** [comment]
> I think I can see this potentially working (and might solve some of @Cadair's problems?), but is there any chance you can link me to wherever you have this need, @MaxNoe? (i.e., is there a github repo?) I want to understand the details just a bit better.

It's in https://github.com/cta-observatory/ctapipe

We are currently reworking the coordinates here: https://github.com/cta-observatory/ctapipe/pull/896
