### ISSUE TITLE
Reduce power consumption for testing

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#8307]
The number of CI tests we run on every PR is becoming quite large, and I wonder whether we cannot reduce it more (while there is no cost to us, all these tests do use power, which, at ~100 W times ~2 hr of processing time, is not negligible). For travis, we already try to minimize by doing first two main tests before running the full suite and for circle CI I think we do the same for 32-bit, and the matplotlib tests only do visualization.

Still, could we not spread testing older versions between windows (circle-ci) and linux (travis)? And might it be possible to move more tests to running, e.g., anything is actually merged in master, or nightly? Or, more ambitiously, start defining a base and full suite of tests? Obviously, all these ideas would have the side benefit that tests actually complete faster...

p.s. I realize that raising an issue like this really comes with an obligation to bring up more concrete solutions, but I'm lazily hoping that others have more concrete suggestions...

**Comment by astrofrog** [comment]
Another possibility is to combine multiple versions to test into a single build (e.g multiple numpy versions). That is, a single Travis job could run multiple tox commands. For instance we could even just have one travis job per Python version and do any variations within the job itself. This would speed things up a bit in the sense that quite a bit of the overhead is in starting up the instance and setting up conda (and Windows especially has a very large overhead for starting up)

**Comment by bsipocz** [comment]
I'm a bit sceptic with your suggestion Tom, changing numpy we can't avoid reinstalling the numpy dependent dependencies as well as rebuilding astropy before running the full tests again. So at best, I wouldn't expect it to save more than very few minutes.

Actually, the only one where we could save a ton is to move the docs build back to travis and run it after a full test suite has passed as a second command on that given build. But then we rely on giles for artefacts, and I'm not sure how difficult to reconfigure it to get it from travis instead of circleci.

Also, while appveyor is indeed super slow to spin up, I think it's a separate issue from the minimizing power consumption angle. E.g., we can already move the windows build to travis as a workaround.

**Comment by mhvk** [comment]
If we can do more on travis, where everything is done only when tests generally passes, I think that is a good thing.  Though travis is a bit slow overall.

**Comment by pllim** [comment]
By the way, our energy consumption is nothing compared to [what bitcoin is using](https://arstechnica.com/tech-policy/2018/05/new-study-quantifies-bitcoins-ludicrous-energy-consumption/). `#themoreyouknow`

**Comment by astrofrog** [comment]
> Actually, the only one where we could save a ton is to move the docs build back to travis and run it after a full test suite has passed as a second command on that given build. But then we rely on giles for artefacts, and I'm not sure how difficult to reconfigure it to get it from travis instead of circleci.

Or we could move the full test suite to the docs build on CircleCI?

I agree that my suggestion before wouldn't work for testing different Python versions, but it would work for testing e.g. Python 3.6 + numpy and then doing a second test run with all dependencies (since astropy wouldn't need to be re-built)

**Comment by bsipocz** [comment]
I'm closing this issue. I think we consistently review the matrix from time to time to avoid repetitions both here an in the package template. Hopefully doing stages on e.g. Azure would address many of the outstanding ideas.

**Comment by mhvk** [comment]
Agreed to close - I think we're quite aware. Another reason to switch to very recent versions of our dependencies :smiley_cat:

**Comment by bsipocz** [comment]
One improvement I'm planning to for a while is to switch to use nightly wheels for the upstream dev testing. So it's on my radar.
(Also, I'm sorry going for the close button too aggressively, but I feel we would tackle more outstanding issues if we just close the general discussion ones after a while, after all they can be always reopened if people feel we need more discussion).
