### ISSUE TITLE
Add top menubar from astropy.org

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8320]
Having the top menubar for the docs from astropy.org would be super nice, among others, it would definitely enhance the visibility of e.g. the affiliated packages, the team the the need for citation.

 https://github.com/astropy/astropy/pull/8293#issuecomment-447949198

**Comment by blatted** [comment]
Hi - I'd like to take this on as a first issue if no one else has. Might need some guidance though,

**Comment by bsipocz** [comment]
Hi @blatted! This issue is all yours. 
General contributions guide is here: https://astropy.readthedocs.io/en/latest/development/workflow/development_workflow.html though for this issue it's a bit different (e.g. no need to write tests, etc) as it involves changing the sphinx theme.
The task here is to modify the top menubar at http://docs.astropy.org/en/latest/ to get the same options* as over on the main webpage http://www.astropy.org/. 

The main repo for the webpage is here: https://github.com/astropy/astropy.github.com. 

(* but keep the current "index" and "modules" ones on the right hand side)

**Comment by bsipocz** [comment]
Yes, you possibly need to also modify the theme, to add this top bar as an option, and then in this repo add the content.

**Comment by blatted** [comment]
Thanks @bsipocz , I made changes and am currently trying to preview them before submitting a PR. Having trouble getting it to work, do you know of a good way to quickly preview the webpage?

**Comment by bsipocz** [comment]
(Oh for the astropy docs, it's detailed in the developer documentation how to do it locally:
`python setup.py build_docs` at the bottom of this page: http://docs.astropy.org/en/latest/development/docguide.html)

**Comment by sunn-e** [comment]
Hey Hi @bsipocz . Is this issue resolved, if not, then I think I can do this. Can you help me with what should I put in menu bar. I want to get started with astropy. But I am not much familiar with it. Till I get some documentation, I could help with the website problem.

**Comment by bsipocz** [comment]
Hey @sunn-e! This hasn't been solved, and the whole idea is detailed out above in https://github.com/astropy/astropy/issues/8320#issuecomment-456924488

**Comment by sunn-e** [comment]
Hey @bsipocz , I tried a lot and nav bar still breaks. Also, I have a doubt, do I need to modify the main webpage's menubar or the documentation page's menubar? Because in the later scenario, I can't find the html file related to the documentations pages in github repo. Can you please confirm whether they are in the main website's repo or somewhere else. Thanks a lot.

**Comment by kakirastern** [comment]
Hi @bsipocz, can I try this issue if no one has solved it? (I can wait until the time is right.) Actually I really wanted to try this since a couple weeks ago, but someone else was working on it previously so I hesitated. I feel I really would learn a lot from the experience, since I have not done so (professionally) before...

**Comment by bsipocz** [comment]
@kakirastern - go for it, so far no one came up with a draft PR so it's more than fair game to give it a go.

**Comment by kakirastern** [comment]
Thanks @bsipocz! I will give it a try right away...

**Comment by kakirastern** [comment]
> Yes, you possibly need to also modify the theme, to add this top bar as an option, and then in this repo add the content.

@bsipocz Regarding the "content" item referenced above in a previous comment, could you provide us with more hints on it?

**Comment by kakirastern** [comment]
Do you mean the html files needed?

**Comment by kakirastern** [comment]
Hi @bsipocz! PR's opened in the astropy/astropy-sphinx-theme and astropy/astropy repos to attempt to address this Issue. But unless the PR astropy/astropy-sphinx-theme#4 is approved and merged GILES will not show the changes applied.

**Comment by kakirastern** [comment]
Think the menubar is ready at PR #8440 now...

**Comment by astrojuanlu** [comment]
@kakirastern If I understand correctly, #8440 stalled because https://github.com/astropy/astropy-sphinx-theme/pull/4 was merged instead to address this issue, right? Then there's a mention of https://github.com/astropy/astropy-sphinx-theme/pull/9, which refers to https://github.com/astropy/astropy-sphinx-theme/issues/12, but I suppose this one can be closed.

**Comment by kakirastern** [comment]
Hi @astrojuanlu Yeah, actually I was about to work with @astrofrog a bit more on the sphinx-theme issue a while (at least a few months) back, but I reckon we both got sidetracked... I still remember this issue except I think Tom is currently hard at work getting a new version of `glueviz` released. Maybe I will send reminders on Slack again regarding this. I do think this issue can be closed for now, since many things have changed now and the best approach may be sorted out at https://github.com/astropy/astropy-sphinx-theme/. If need be I will open another PR for this in this repo.

**Comment by astrofrog** [comment]
I think what remains to be done here is enabling ``astropy_project_menubar`` in our ``conf.py`` here

**Comment by astrofrog** [comment]
Ah there was a PR: https://github.com/astropy/astropy/pull/8440 - I think there were basically some CSS issues to resolve?

**Comment by kakirastern** [comment]
Will need to check the latest RTD build of the docs to ascertain the status...

**Comment by pllim** [comment]
I think this is done.
