### ISSUE TITLE
Please do not install tests

### ISSUE THREAD

**Issue by yurivict** [astropy/astropy#8365]
The production machine should have no tests installed. They should only be run after build.

**Comment by pllim** [comment]
Hello. We do have reason to include them; i.e., to let users run `import astropy; astropy.test(...)` to test their installation. Can you please provide more context on why these tests are giving you a problem? Thank you.

**Comment by astrofrog** [comment]
@pllim is correct that including the tests is a deliberate pattern we use for all packages in the project, as it allows us to more easily diagnose user issues. I'll go ahead and close this issue, but feel free to re-open if this is actually causing issues (rather than being a preference) on your side.
