### ISSUE TITLE
Unable to save CompressedHDU when data has nan

### ISSUE THREAD

**Issue by harshmathur1990** [astropy/astropy#8392]
Hi,
Please find the steps to recreate this issue.

```
from astropy.io import fits
import numpy as np
data = np.arange(10, dtype=float)
data[data>5] = np.nan
print (data)
hdu = fits.CompImageHDU(data)
hdu.writeto('sample.fits')
ff = fits.open('sample.fits')
print (ff[1].data)
```

The output is : 

```
[ 0.  1.  2.  3.  4.  5. nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan]
```

As shown above, when the data is partial values and nan's, it only saves nan's and data is lost.

The Environment used is:
OS: macOS Mojave 10.14
Numpy Version: 1.16.0
Astropy Version: 3.1.1
Python Version: 3.7.0

Regards
Harsh Mathur

**Comment by saimn** [comment]
I thought it was a bug but actually this is because of the way the compression works for floating point values, (and in this particular example probably because it has too few valid values). For instance with fewer NaNs it works:
```
In [2]: data = np.arange(10, dtype=float)                                                      

In [3]: data[data>8] = np.nan                                                                  

In [4]: hdu = fits.CompImageHDU(data)                                                          

In [5]: hdu.writeto('sample.fits', overwrite=True)                                             

In [6]: fits.getdata('sample.fits')                                                            
Out[6]: array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., nan])
```

I'm not expert in the way compression algorithm works, but `CompImageHDU`'s docstring gives some information, in particular for `quantize_level`: http://docs.astropy.org/en/latest/io/fits/api/images.html#astropy.io.fits.CompImageHDU

Another example:
```
In [14]: data = np.arange(10, dtype=float)                                                     

In [15]: data[data>5] = np.nan                                                                 

In [16]: data                                                                                  
Out[16]: array([ 0.,  1.,  2.,  3.,  4.,  5., nan, nan, nan, nan])

In [17]: hdu = fits.CompImageHDU(data, quantize_level=-1)                                      

In [18]: hdu.writeto('sample.fits', overwrite=True)                                            

In [19]: fits.getdata('sample.fits')                                                           
Out[19]: 
array([ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,  3.00000000e+00,
        4.00000000e+00,  5.00000000e+00, -2.14748365e+09, -2.14748365e+09,
       -2.14748365e+09, -2.14748365e+09])
```
(NaNs are not recognized, we get extreme values instead, but the valid values are ok).

More generally I think that you must be very carefully when using these compression algorithm with floating point data. You will loose precision, and must choose the parameters carefully.

**Comment by yannick1974** [comment]
The compression is destructive on float values  as [explained there](https://heasarc.gsfc.nasa.gov/docs/software/fitsio/compression.html) (I was thinking that only the RICE compression method was but apparently all are). A solution is to convert the data to integer with a scaling parameter.
