### ISSUE TITLE
Add log_a as an argument to simple_norm

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#8432]
Currently ``simple_norm`` exposes an ``asinh_a`` argument for the arcsinh stretch - it would be nice to similarly expose a ``log_a`` argument for ``LogStretch``

**Comment by SG004** [comment]
I'd like to give this a try if I am permitted.
If I am allowed, I will have  a few questions.

**Comment by bsipocz** [comment]
@SG004 - of course, go for it!

**Comment by moon05** [comment]
@bsipocz Hey! I have been meaning to look into Astropy for a while and just decided that I can try contributing. Since SG004 is giving it a try I will not attempt it, but after going through the code I just had a question. For exposing an argument like, `log_a` as an input for (where the `default=1000`) `LogStretch`, is it enough to just introduce an arg and that's it!? Or am I missing something?

Also, in strech.py should there be a check in `AsinhStretch` to make sure the input is between 0 and 1? For `LogStretch` does it not matter whatever value goes in? Is there no min, max since it isn't mentioned?

**Comment by bsipocz** [comment]
Has been addressed by #8436
