### ISSUE TITLE
discretize_model gives an error for some range values using oversample mode

### ISSUE THREAD

**Issue by mrtommyb** [astropy/astropy#8492]
I'm using discretize_model to convolve a Gaussian2d model with a pixel image. I'm using the oversample method. For some values of y_range and oversample factors the code gives me a value error. However, it's fine for most values. Below is an example of when the code fails.

```python
from astropy.modeling.functional_models import Gaussian2D
from astropy.convolution import discretize_model
gmodel = Gaussian2D(amplitude=1.0, x_mean=5., 
                    y_mean=125., x_stddev=0.75, y_stddev=3)
discretize_model(gmodel,
                 x_range=[0, 10],
                 y_range=[100, 135],
                 mode='oversample', factor=10)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-367-5c0a8b7bdf3d> in <module>
      6                  x_range=[0, 10],
      7                  y_range=[100, 135],
----> 8                  mode='oversample', factor=10)

~/anaconda3/lib/python3.6/site-packages/astropy/convolution/utils.py in discretize_model(model, x_range, y_range, mode, factor)
    183             return discretize_oversample_1D(model, x_range, factor)
    184         if ndim == 2:
--> 185             return discretize_oversample_2D(model, x_range, y_range, factor)
    186     elif mode == "integrate":
    187         if ndim == 1:

~/anaconda3/lib/python3.6/site-packages/astropy/convolution/utils.py in discretize_oversample_2D(model, x_range, y_range, factor)
    270     # Reshape and compute mean
    271     shape = (y.size // factor, factor, x.size // factor, factor)
--> 272     values = np.reshape(values, shape)
    273     return values.mean(axis=3).mean(axis=1)[:-1, :-1]
    274 

~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in reshape(a, newshape, order)
    290            [5, 6]])
    291     """
--> 292     return _wrapfunc(a, 'reshape', newshape, order=order)
    293 
    294 

~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     54 def _wrapfunc(obj, method, *args, **kwds):
     55     try:
---> 56         return getattr(obj, method)(*args, **kwds)
     57 
     58     # An AttributeError occurs if the object does not have

ValueError: cannot reshape array of size 39710 into shape (36,10,11,10)
```

**Comment by pllim** [comment]
From `git blame`... @adonath , do you remember the implementation details?

**Comment by mrtommyb** [comment]
Here's my version:
astropy: 3.1.2
python: 3.6.7
numpy: 1.16.0

**Comment by adonath** [comment]
I've looked a bit into this and it seems to be a numerical issue. Internally the `discretize_oversample_2D` uses `np.arange()` to set up the grids for the model evaluation. The upper bound for `np.arange(start, stop, step)` (or the `stop` argument...) is computed as `y_range[1] + 0.5 * (1 + 1 / factor)`. Normally the stop value is excluded when using `np.arange()`, but in your specific case it's included, because of numerical precision. The last value returned by `np.arange()` comes out as ` 134.54999999999802`, while it should rather be `134.45`. I think the fix here is easy: the upper bound should be changed to `y_range[1] + 0.5` (or `134.5` in your case). This introduces a margin of `0.5 * 1 / factor`, which is far above the numerical precision. I hope this explanation makes sense.

I don't have the time to implement the fix now ( I think a few other functions might be affected as well). 
@mrtommyb Maybe you want to give it try?
