### ISSUE TITLE
Can't import Representation class twice (from different packages/telescopes)

### ISSUE THREAD

**Issue by noahhdf** [astropy/astropy#8509]
I try to import two functions from two packages of two telescopes ([CTA](https://github.com/cta-observatory/ctapipe) / [FACT](https://github.com/fact-project/pyfact)).
Both define a `PlanarRepresentation` class internally.

Error:
```
    438         if repr_name in REPRESENTATION_CLASSES:
    439             raise ValueError("Representation class {0} already defined"
--> 440                              .format(repr_name))
    441 
    442         REPRESENTATION_CLASSES[repr_name] = cls

ValueError: Representation class planar already defined
```

MWE without the packages, but same Error, basically just redefining the Representation class:
```python
from astropy.coordinates import BaseRepresentation

class PlanarRepresentation(BaseRepresentation): 
     attr_classes = ['a', 'b'] 
     def __init__(self, x, y, copy=True, **kwargs): 
         pass

class PlanarRepresentation(BaseRepresentation): 
     attr_classes = ['a', 'b'] 
     def __init__(self, x, y, copy=True, **kwargs): 
         pass
```

**Comment by adrn** [comment]
Hi @noahhdf: First off, the reason this happens is because all representation classes (i.e. anything that subclasses `BaseRepresentation`) gets registered by name in a dictionary within astropy, and as you've encountered, if two subclasses have the same name, the registration process throws an error. I don't have much advice at this point, but maybe @eteq or @mhvk can chime in?

**Comment by pllim** [comment]
Theoretically, you can let the latter silently (or with warning) overwrite the former. But I am not sure if that is more dangerous than it's worth.

**Comment by mhvk** [comment]
@noahhdf - yikes. Are the two classes identical? And do you actually need those representations? If not, then as a work-around, you can import one package, delete the entry in `astropy.coordinates.representation.REPRESENTATION_CLASSES`, and import the next package.

As a work-around in astropy proper: we could also decide that if names are duplicated, we *remove* the entry from the classes altogether (and keep a list of these removed classes), so that everything keeps working as long one doesn't use that class. Here, it is good to remember that the list is not itself all that important: all it does is translate from string to class when people do things like `coord.spherical`; in most internal use, we use the classes themselves, which works fine.

**Comment by mhvk** [comment]
p.s.  We'd remove while warning, obviously!

**Comment by noahhdf** [comment]
> delete the entry in `astropy.coordinates.representation.REPRESENTATION_CLASSES`, and import the next package

thanks @mhvk, this did the trick for me

```python
1  from astropy.coordinates.representation import REPRESENTATION_CLASSES
2  from fact.analysis.source import calc_off_position
3  REPRESENTATION_CLASSES.pop("planar")
4  from ctapipe.coordinates import CameraFrame
```

**Comment by mhvk** [comment]
This issue may pop up again. I think we should at least document it!  Also, @noahhdf, do you actually use planar? I.e., could we go for my astropy fix of "in the face of ambiguity, refuse the temptation to guess"? One worry would be that `fact` uses it internally and now will get an inconsistent class...

Actually, perhaps better longer term, if both use essentially the *same* class, is to move it upstream...

**Comment by noahhdf** [comment]
the two classes are **exactly** the same.
This is what the fact version says in its docstring:
```
Representation of a point in a 2D plane. This is needed for coordinate
frames to store their coordinates internally.
This is essentially a copy of the Cartesian representation used in astropy.
Copied from ctapipe.
```

**Comment by mhvk** [comment]
@noahhdf - thanks for looking that up! If you have time, could you do us a favour and for both packages raise an issue, pointing to this astropy one, and asking whether they can coordinate? Since it is used in two packages, I think it would also be reasonable to push it up to astropy itself, though I am still not completely sure what it is good for. 

Anyway, at least for your case, it means there is no risk in the import-one, delete, import-other trick!

**Comment by noahhdf** [comment]
[pyfact issue](https://github.com/fact-project/pyfact/issues/121)
[ctapipe issue](https://github.com/cta-observatory/ctapipe/issues/1043)

**Comment by MaxNoe** [comment]
We use these 2d Representation to implement detector coordinates that together with a pointing coordinate if the telescope represent a valid sky coordinate.

See https://github.com/fact-project/pyfact/tree/pyfact/coordinates/camera.py

Maybe we could use something like `__qualname__` in case a name collision occurs?

**Comment by MaxNoe** [comment]
```python

if repr_name in REPRESENTATION_CLASSES:
    repr_name = cls.__qualname__
    # maybe emit a warning here?

REPRESENTATION_CLASSES[repr_name] = cls
```

**Comment by MaxNoe** [comment]
I opened a PR adressing this here #8561

**Comment by MaxNoe** [comment]
`representation='planar'`

I never so code giving representations as strings. We certainly not use it. I thought representations were internal attributes of coordinae frames, nothing a user of the coordinate system directly interfaces with.

What use cases do people have for specifying representations?

**Comment by mhvk** [comment]
@MaxNoe - you can specify the representation using a string when initializing a `SkyCoord(x=..., y=..., z=..., representation_type='cartesian')`, and if you do `coord.cartesian`, internally, 'cartesian' is looked up in the representation classes to find out what you want. Similarly, you can do `coord.planar` once your representation class is registered.

Overall, `SkyOffsetFrame` would still seem the correct one, just with a projection of the angles on a tangent plane.

But I think we're letting this issue become too big, and perhaps we should try to reduce it to separate ones:
1. Should we have a way to not just raise when an attempt is made to register a duplicate name? (Which really this issue is about.)
2. Should we include planar coordinates in `astropy` proper?
3. Should we have a detector frame class in astropy proper?

My sense is yes to (2) and (3), but I'm still unsure what to do about duplicate names.

**Comment by mhvk** [comment]
p.s. @noahhdf - thanks for raising the issues!

**Comment by MaxNoe** [comment]
> `you can specify the representation using a string when initializing a SkyCoord(x=..., y=..., z=..., representation_type='cartesian')`

Could you explain why or when this would be useful?

**Comment by mhvk** [comment]
> Could you explain why or when this would be useful?

Well, it certainly is not something we can change any more; it is even in the Getting Started section on coordinates; http://docs.astropy.org/en/latest/coordinates/index.html#representation

**Comment by MaxNoe** [comment]
> Well, it certainly is not something we can change any more; it is even in the Getting Started section on coordinates

I get this. I would love to see a usecase for this anyway. So I could think about a fix. 
For the meantime, I will rename planar to `fact_planar` in pyfact.

**Comment by mhvk** [comment]
The use case is arguably mostly laziness: if you want to initialize or convert, you don't have to import the relevant class, but just give its name.

So, indeed, changing the name of your class would resolve it, though I think that longer term it still seems reasonable to move the class up to astropy.

**Comment by MaxNoe** [comment]
> The use case is arguably mostly laziness: if you want to initialize or convert, you don't have to import the relevant class, but just give its name.

Sorry, I was unclear.

I don't mean the usecase for specifying the representation as string. 
I mean the usecase for specifying a representation on the SkyCoord level *at all*.

All reference frames have a fixed representation, do they not?

**Comment by eteq** [comment]
All of that said: I think #8561 is a not unreasonable work-around.  It allows there to be two similarly named classes, *but* you can always get around the "name" problem by passing in the classes themselves instead of their names, right?  I *think* we've done this consistently. If not, I think it's fair to declare any cases where it turns out this does *not* work to be bugs.

There's still potential for confusion if the user thinks they're getting the "other" version of a representation, since import-order now matters... But I think the warning is sufficient to catch that.  Seem reasonable, @mhvk?

(We probably should add some words about this subtlety to the docs, but that could be next week if we want to get this into the feature freeze now.)

**Comment by mhvk** [comment]
There's a bit of a problem with discussion now happening in two places...  I do think we should not get into a case where a user gets the wrong representation, ever, depending on package import error.

**Comment by eteq** [comment]
> There's a bit of a problem with discussion now happening in two places

OK sure, lets restrict the discussion about whether to use #8561 there (I moved here because of your comment in that PR, @mhvk - my bad!)
