### ISSUE TITLE
raise ValueError('One of the inputs to search_around_sky is a scalar. )

### ISSUE THREAD

**Issue by rasputin1917** [astropy/astropy#8536]
Hi, I am using `search_around_sky` almost like that:

`_center = SkyCoord(3*u.deg, 4*u.deg, frame=FK5)`
`full_cat=SkyCoord(full_cat["RA(core)"], full_cat["DEC(core)"],  unit="deg")`

`print(_center.isscalar)      ##--> it is returning True`
`print(full_cat.isscalar)      ##-->it is returning False`
                                                                                                                                                                            `idxc, idxcatalog, d2d, d3d = search_around_sky(_center, full_cat, seplimit=1*u.deg)`

Then I get the following error:

`    raise ValueError('One of the inputs to search_around_sky is a scalar. '
ValueError: One of the inputs to search_around_sky is a scalar. search_around_sky is intended for use with array coordinates, not scalars.  Instead, use ``coord1.separation(coord2) < seplimit`` to find the coordinates near a scalar coordinate.`

`_center` **shouldn't** be scalar though because of the `SkyCoord`, right? What I am doing wrong?`

I cannot find a proper example about that

Please some help, I need to use search_around_sky

**Comment by adrn** [comment]
Hi @rasputin1917: The "scalar" here just means that your object `_center` contains a single coordinate, even though it is indeed a `SkyCoord` instance. As the error message says, in this case when you are searching for catalog neighbors to a single coordinate (i.e. a scalar coordinate), you can use `.separation()` instead of `search_around_sky()`, which is mainly useful for cross-matching or searching for neighbors when you have *two* catalogs. So here, as the error says, the easiest thing to do is:
```python
d2d = full_cat.separation(_center)
mask =  d2d < 1*u.deg
```
where here `mask` will be a boolean array of length `len(full_cat)` and will be True where the catalog entries are within 1 degree of your `_center` coordinate. In this particular case, if you really want to use `search_around_sky()` (which, again, I don't recommend), you could make `_center` a length 1 array and do, e.g.:

```python
idxc, idxcatalog, d2d, d3d = search_around_sky(_center[None], full_cat, seplimit=1*u.deg)
```
(the `[None]` makes the scalar `_center` a 1D array with 1 element).

Please reopen and let me know if anything is still unclear!
