### ISSUE TITLE
1D wcs transformations not returning single array

### ISSUE THREAD

**Issue by nmearl** [astropy/astropy#8559]
The [documentation for wcs transformations](http://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS.all_world2pix) state that the `all_world2pix`, etc, operations return a single array if the input is a single array. However, currently, they return a list of length 1 with the single array of pixel coordinates (in the case of `all_world2pix`/`world_to_pixel`):

```python
In [6]: my_wcs = fitswcs.WCS(header={'CDELT1': 1, 'CRVAL1': 6562.8, 'CUNIT1': 'Angstrom', 'CTYPE1': 'WAVE', 'RESTFRQ': 1400000000, 'CRPIX1': 25})

In [7]: my_wcs.world_to_pixel(np.arange(10) * u.nm)
Out[7]:
[array([-6538.8, -6528.8, -6518.8, -6508.8, -6498.8, -6488.8, -6478.8,
        -6468.8, -6458.8, -6448.8])]
```

This is also inconsistent with the current GWCS interface that returns a single array of coordinates.

**Comment by pllim** [comment]
cc @nden and @astrofrog

**Comment by eteq** [comment]
I think this is a bug (relevant because it means we don't have to try to fix it for the feature freeze...), do you agree @astrofrog and/or @nden?

**Comment by eteq** [comment]
Oh, and @Cadair or @keflavich might have opinions here as APE14 co-authors

**Comment by astrofrog** [comment]
I've had a chance to think about this some more and I think I'd rather keep the current behavior, at least in the APE 14 interface.

My reasoning is that consistency is important here, because it would be frustrating to sometimes get back a tuple and sometimes not. A good example of where this would be annoying is the case of a 2D WCS that returns a SkyCoord versus a 2D WCS that returns positional offset and velocity for example. In the first case, a single world coordinate is returned, and in the second case, two are returned. Knowing which case this would be and therefore knowing whether slicing is needed requires introspecting ``world_axis_object_classes`` and ``world_axis_object_components``.

In the current behavior, one can chain transformations with ``wcs2.pixel_to_world(wcs1.world_to_pixel(...))`` which is useful e.g. for reprojection/resampling of data. If we start to sometimes return tuples and sometimes not, we'd have to special case these calls to artificially add tuples in some cases.

I think for the original ``wcs_world2pix`` etc. methods it may be that the behavior is inconsistent with the docstring. In this case we should check if the current behavior has been there for a while, and if so update the docstring.

**Comment by eteq** [comment]
I see the merits of the "consistency" argument, but to ensure that consistency I suppose we need to do the same in GWCS (and more generally it should be part of the APE14 API) - @nden does that seem problematic to you? (I haven't checked myself but if I understood @nmearl it's currently not the way @astrofrog is proposing here?)

**Comment by nmearl** [comment]
@astrofrog are you suggesting then that gwcs also follow this paradigm of returning tuples?

**Comment by astrofrog** [comment]
@nmearl - whatever we decide, I think that GWCS should do the same, since the APE14 API is meant to be universal after all.

**Comment by nmearl** [comment]
Yeah, I mean, that's my concern: I can't make specutils compatible with ape 14 until every's compatible with each other. :stuck_out_tongue:

**Comment by nden** [comment]
I think you may be misinterpreting the [documentation](https://github.com/astropy/astropy/issues/8559). It's best understood if you think about the default case (naxis=2). Coordinate inputs are accepted in two formats

- 1 array (N x naxis) coordinates, [x, y]. In this case the return value is one array of the same shape.
Example for pixels (1, 1) and (1,2) 
```
xy = np.array([[1, 1], [1, 2]])
print(xy)
array([[1, 1],
       [1, 2]])
print(wcs.all_pix2world(xy, 1))
[[  5.52645703 -72.05171891]
 [  5.52647641 -72.05173153]]
```
- Alternatively the input can be separate values for `x` and `y` in which case a list `[ra, dec]` is returned.
  Note that in this case when scalars are passed in the return of `all_pix2world` is again a list of 2 arrays
`[array(5.52645703), array(-72.05171891)]`

So the "single array" in the `Returns` section refers to the first case above, not to the number of axes in the WCS object. This has been the behavior of `all_pix2world` and `wcs_pix2world` for a long time.

Now APE 14 says
```
def pixel_to_world_values(self, *pixel_arrays):
        """
        Convert pixel coordinates to world coordinates. This method takes
        n_pixel scalars or arrays as input, and pixel coordinates should be
        zero-based. Returns n_world scalars or arrays in units given by
        ``world_axis_units``. 
```
I says `n_world arrays`, not a `list of n_world arrays`. However the return values implemented in fitswcs are in the format of the core wcs functions as described above. Am I misinterpreting this?

OTH, gwcs treats the inputs separately and the rule is that the shape of the return values is the same as the shape of the inputs. The reason for this was partly the fact that using one array to pack all inputs is less clear than using separate inputs. I am hesitant to change that as it will require many other changes in other packages. However I have no problem changing the APE 14 functions if that's what everyone agrees on (although as mentioned I thought I am following the spec.) So as a start may be the APE needs to be clarified?

**Comment by mcara** [comment]
Original message refers to the documentation for `all_world2pix()` but provides an example that uses APE 14 `world_to_pixel()`. IMO this is an issue of documentation. More specifically, the documentation for [`world_to_pixel()`](http://docs.astropy.org/en/stable/api/astropy.wcs.wcsapi.BaseHighLevelWCS.html#astropy.wcs.wcsapi.BaseHighLevelWCS.world_to_pixel) is really missing and users should not have to go to https://zenodo.org/record/1188875#.XMnPAC-ZNdA in order to download APE 14 to get to the documentation.

@astrofrog wrote:
> whatever we decide, I think that GWCS should do the same, since the APE14 API is meant to be universal after all.

I thought the point of APE 14 was to develop an interface - not to make other packages (i.e., GWCS) change their interfaces. If you want GWCS have the same behavior as FITS WCS, why not just have `all_world2pixel()` in GWCS and get rid of APE 14? I mean, this is really just a function name. Why not have the same name as in FITS WCS? Problem solved. (?)

**Comment by mcara** [comment]
@nmearl wrote in the original message:

> This is also inconsistent with the current GWCS interface that returns a single array of coordinates.

Which function in the GWCS interface do you refer to in the above? `world_to_pixel` or `invert()`? (or  `pixel_to_world` vs `__call__`)?

**Comment by nmearl** [comment]
I think the point is that having a proposal for a generalized abstraction layer over a wcs implementation is not very useful if every generalization is unique. Currently, APE 14 allows for the both the fitswcs and gwcs interpretation of what the output data ought to look like, and right now they're not the same. As it stands, I have to be aware of which wcs implementation I'm dealing with, defeating the purpose of the abstraction.

APE 14 should be clarified in this respect, and the implementation of the abstraction fixed on whichever implementation is inconsistent.

> Which function in the GWCS interface do you refer to in the above? world_to_pixel or invert()? (or pixel_to_world vs __call__)?

Any. As @nden mentions:

> gwcs treats the inputs separately and the rule is that the shape of the return values is the same as the shape of the inputs.

And this is indeed the case -- a single array of world values or pixel values returns a single array of pixel values or world values, regardless of which transformation method I call. Likewise, fitswcs insists on providing back lists of arrays.

**Comment by astrofrog** [comment]
Thinking about this some more, I'd be ok with returning variables *not* in a list/tuple in the single coordinate case, but this means that chaining as:

```
wcs2.pixel_to_world(*wcs1.world_to_pixel(...))
``` 

won't work. One way around this is to say that ``pixel_to_world`` and ``world_to_pixel`` should be able to accept a tuple, and in this case, it should auto-expand it, so that we could then do:

```
wcs2.pixel_to_world(wcs1.world_to_pixel(...))
```

**Comment by astrofrog** [comment]
Relating to some of the discussion above, I'm not interested in changing the default behavior of the 'native' methods for GWCS and FITS-WCS, just the APE 14 API - which I think is still fine to do since it was new in 3.1.
