### ISSUE TITLE
TST: Add tests for ASDF schemas in io.misc.asdf

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8637]
To make sure that the actually work. xref #8636 

This requires someone familiar with ASDF to tackle.

**Comment by Cadair** [comment]
Specifically this is related to how the tags load the schemas, not validating the schemas or the tags themselves.

**Comment by nden** [comment]
Can you clarify what kind of tests you think should be added. The tags have tests in each directory and the schemas are tested separately. I'm just not sure what is missing. 

#8413 moved the location of the schemas and changed `SCHEMA_PATH` in the extension but the schema `id`s were not change - they still point to the old path. I wonder if this is what caused the error in #8636. It'd have been helpful if #8636 provided a traceback.

**Comment by Cadair** [comment]
@nden I am not sure if there needs to be more tests or if there is some other reason the CI didn't catch the error I experienced.

There were two issues, firstly my schema was needing the core table tag, which I have amended to be `anyOf` core and astropy table. After that fix I got the following error:

```
self = <jsonschema.validators.RefResolver object at 0x7f8d296fc438>, url = 'tag:astropy.org:astropy/table/table-1.0.0'

    def resolve_from_url(self, url):
        url, fragment = urldefrag(url)
        try:
            document = self.store[url]
        except KeyError:
            try:
                document = self.resolve_remote(url)
            except Exception as exc:
>               raise RefResolutionError(exc)
E               jsonschema.exceptions.RefResolutionError: [Errno 2] No such file or directory: '/home/stuart/Git/astropy/astropy/io/misc/asdf/data/schemas/astropy.org/astropy/table/table-1.0.0.yaml'

../../../.virtualenvs/dkist/lib/python3.7/site-packages/jsonschema/validators.py:385: RefResolutionError
```

**Comment by nden** [comment]
@Cadair It appears the fits tag tests did not fail due to spacetelescope/asdf#571 which makes it possible to write to and read from an asdf file without a schema. In this case a Warning is raised but `assert_roundtrip_tree` does not catch it and passes.
I'm not sure what the best way to avoid this in the future is.

**Comment by pllim** [comment]
I think this is done, right, @eslavich ?

**Comment by eslavich** [comment]
Something is fishy with the two FITS serializers:

https://github.com/astropy/astropy/blob/master/astropy/io/misc/asdf/tags/fits/fits.py#L85

They both claim the honor of handling `HDUList`, and I'm not sure how the tie is broken.  The answer may be system-dependent since it depends on the order that the entry points are loaded.  Is there ever a need to write the fits-1.0.0 tag from the ASDF Standard?  If not, then I can remove `HDUList` from `AsdfFitsType` to clear up the ambiguity.

I should probably add at least one more test that makes an explicit check of the tag of the serialized `HDUList` to ensure that it's using the astropy tag and not the one from the ASDF Standard.

**Comment by pllim** [comment]
No longer relevant. It is now `asdf-astropy` package.
