### ISSUE TITLE
Conversion of Table values to Python types

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#8721]
We are frequently annoyed by type conversions from Astropy Table to Python types, typically when willing to insert a table in a database, for which we need pure Python types and not Numpy ones. And I don't know if there is a good way to always get Python types ? 

- For numeric types (integer, float), using `column.tolist()` converts to Python types, but `list(column)` do not.
- For string types, with the unicode sandwich, `list(column)` converts to unicode, but `column.tolist()` returns bytes.

Is there another way or something that can be improved in `Table`, to be sure to always get the most convenient Python types (`int`, `float`, *and* `str`) ?

```
In [79]: t2                                                                                    
Out[79]: 
<Table length=4>
  id     comment    
int64    bytes14    
----- --------------
    1            foo
    2            bar
    3           plop
    4 a long comment

In [75]: type(t2['id'].tolist()[0])                                                            
Out[75]: int

In [76]: type(list(t2['id'])[0])                                                               
Out[76]: numpy.int64

In [77]: type(t2['comment'].tolist()[0])                                                       
Out[77]: bytes

In [78]: type(list(t2['comment'])[0])                                                          
Out[78]: str
```

**Comment by mhvk** [comment]
I think that `column.tolist()` should indeed return a list of `str` if the unicode sandwich is in place - probably just an oversight that it wasn't done. @taldcroft, what do you think?

**Comment by taldcroft** [comment]
Yes, `column.tolist()` should return a list of `str`, so that was an oversight.

I think the current `list(column)` behavior is what I would expect for numerical values: namely it iterates over the values in `column` and puts them in a `list`.  The fact that the values in `column` are numpy objects and not Python objects is fundamental to the whole design and that is not likely to change.   The fact that `list(column_of_bytes)` actually gives a list of Python `str` objects is a bit of an inconsistency in my mind, related to the not-perfect handling of unicode in numpy.

**Comment by taldcroft** [comment]
@saimn - any interest in a PR?  *Maybe* something as simple as below would do the job?
```
# In BaseColumn class 
from numpy import chararray

def tolist(self):
    if self.dtype.kind == 'S':
        return chararray.decode(self, encoding='utf-8').tolist()
    else:
        return super().tolist()
```
You would definitely want to test a multidimensional `bytes` Column.
