### ISSUE TITLE
matplotlib.pyplot.hist does not work on Quantities in matplotlib version 3.1.0

### ISSUE THREAD

**Issue by eblur** [astropy/astropy#8743]
The [learn astropy Quantities tutorial](http://learn.astropy.org/rst-tutorials/quantities.html) makes a histogram with an array of Astropy Quantities. This works in matplotlib 3.0.2 but not matplotlib 3.1

We have adjusted the pip-requirements file for the Learn Astropy repo. However, we expect this to become an issue for users in the near future.

See [astropy-tutorials Issue #359](https://github.com/astropy/astropy-tutorials/issues/359)

**Comment by mhvk** [comment]
I think part of the problem is actually with the example as given, in that it doesn't set up matplotlib to work with units... I don't have matplotlib 3.1 handy, but if I try
```
from astropy.visualization import quantity_support
quantity_support()
plt.hist(v)
```
I actually get a plot with the units already present, while without it, `v` is just treated as an array.

Does the above work with 3.1?

If not, perhaps best is in the tutorial to use this opportunity to mention that `Quantity` does not always work automatically with `matplotlib`, and explicitly do `plt.hist(v.value)` - but I'd then also do
```
plt.xlabel("Velocity ({})".format(v.unit))
```
to teach good habits of always tracking the actual unit, not the one you think it is.

(Alternatively, do `plt.hist(v.to_value(u.km/u.s))`)

**Comment by astrofrog** [comment]
This will be fixed in Matplotlib 3.1.1 - https://github.com/matplotlib/matplotlib/pull/14289

**Comment by mhvk** [comment]
@astrofrog - thanks for the quick fix!

@eblur - independently, I think it would be nice to introduce `quantity_support()` in the example, especially as it immediately gives a unit on the x axis.

**Comment by eblur** [comment]
I checked `astropy.visualization.quantity_support`, and it does work in matplotlib 3.1.0

[I've added this update for Quantities tutorial to our todo list](https://github.com/astropy/astropy-tutorials/issues/362)

**Comment by mhvk** [comment]
OK, sounds all good!
