### ISSUE TITLE
Permission denied for generated parsetab 

### ISSUE THREAD

**Issue by KeithSloan** [astropy/astropy#8783]
I am trying to use astroquery to access GAMA Survey.

The supplied test is
`     from astroquery.simbad import Simbad`
     `result_table` = `Simbad.query_object("m1")`
     `result_table.pprint(show_unit=True)`

I get an error  `WARNING: Couldn't create 'astropy.units.format.cds_parsetab'. [Errno 13] Permission denied:
 '     /usr/lib/python3/dist-packages/astropy/units/format/cds_parsetab.py'
`
Now I could use sudo but suspect there is something I should have done at installation that
should cause parsetab to be created somewhere other than /usr/lib

**Comment by MSeifert04** [comment]
Thanks for the report. 

Just one follow up question: What astropy version are you using and how did you install it?

**Comment by KeithSloan** [comment]
Sorry should have said from the out set. Installed on Ubuntu 18.04 with
`   sudo apt-get update -y`
   ` sudo apt-get install -y python3-astroquery`

**Comment by bsipocz** [comment]
While the parsetab permission issue may still be around both the versions you're using are over a year old. One option would be to switch to manage the python packages by a more pythonic package manager, either with conda or pip rather than distro distributed. This is definitely the recommendation for astroquery for which, due to changing upstream changes to the archive APIs, we cannot guarantee that an old version will even work.

**Comment by bsipocz** [comment]
(note to maintainers: I labeled this as a bug even though not entirely sure that this is a packaging issue or something we need to have a workaround in `astropy.units`)

**Comment by KeithSloan** [comment]
Okay I installed anaconda and no longer get the permissions problem.

I was going by this page [https://astroquery.readthedocs.io/en/latest/](url) 

I did initially try the conda command which as it was not installed gave an error.
and sudo apt-get install conda gave package not found.
So I googled for install ubuntu 18.04 astroquery and got [http://zoomadmin.com/HowToInstall/UbuntuPackage/python3-astroquery](url)

Only after your comments did I go back to install instructions to wonder if conda and anaconda were related.

**Comment by bsipocz** [comment]
Yes, confusingly `anaconda` is the name of the distribution (and the company) while `conda` is the name of the command.

**Comment by mhvk** [comment]
This may be a bug in Debian too, so cc @olebole. 

And for the record: my advice is generally to *use* Ubuntu/Debian packages as (i) they are good at solving bugs themselves or passing them on to use; (ii) conda does quite a bit of monkeypatching, at least for numpy, leading to enough conda-specific bugs that numpy has a separate label for it.

**Comment by bsipocz** [comment]
@mhvk - In the example above astropy has the version 3.0. If that's the most recent Ubuntu has to offer I don't think we should recommend to use that. As for issues with conda, yes, I would rather suggest to use pip.

Anyway, the original issue rings a bell that we saw similar ones before. e.g. based on https://github.com/astropy/astropy/issues/7228 this is a packaging issue (and due to the fact that ubuntu probably relies on standalone rather than the bundled external packages).

**Comment by mhvk** [comment]
Ubuntu 18.04 means it is about a year old (2018 April), so it containing astropy 3.0 makes sense. And, yes, if one needs to, staying up to date with `pip` is a good idea.

**Comment by olebole** [comment]
I will have a look into this on astropy in Ubuntu ([copied bug report](https://bugs.launchpad.net/ubuntu/+source/astropy/+bug/1831421)) and try to make an update there. It does not happen on the Debian Buster Astropy package (3.1.2).

**Comment by KeithSloan** [comment]
My history is mainframes to AIX to Linux so expect to install stuff via sudo apt-get instal <package>
anaconda is all new to me.

As to Ubuntu 18.04 being a year old. 18.04 is a long term version. Next long term will be 20.04. I have had bad experiences of upgrading to non long term versions so stick to long term versions.

**Comment by bsipocz** [comment]
Hmm, that's unfortunate. We have a long term support astropy branch, 2.0.x, I feel it should have been the one then that gets into the Ubuntu LTS, though it will also cease to be supported at the end of this year (along with python2).

**Comment by bsipocz** [comment]
(and I simply feel that python and probably javascript are those systems that have their own packaging preferences and thus doesn't really served that well by the standard LTS distro packagers. just my 2 cents, the situation has both pro and con. 
And anyway even then those version combinations should work without issues).

**Comment by mhvk** [comment]
@KeithSloan - just to echo @bsipocz, definitely don't feel you have to change your work flow; this is a real bug you uncovered, but it may be in the packaging rather than in astropy. But worth fixing regardless.

**Comment by olebole** [comment]
> Hmm, that's unfortunate. We have a long term support astropy branch, 2.0.x, I feel it should have been the one then that gets into the Ubuntu LTS

Well, that is my fault -- I didn't think about which version to select, and just the latest release went into Ubuntu. Same will happen for Debian Buster where 3.1.2 will end up. And both will stay, only with (selected) important bug fixes applied if needed.
Aside from my unfortunate ignorance, this is a bit of a unresolvable conflict: I want to have the latest release in Debian Testing -- first, people require this for their work as well, but also to get them tested. My current workflow is that if there are important bugs reported, I would try to backport the fix from the newer versions. Fortunately, this happens *very* rarely over the lifetime of a Debian release (or at least is seldom reported). BTW, the Astropy version in the current Debian stable release ("Stretch") is still 1.3.
Another way to get a fixed (and updated) package in Debian are backports of the newer packages in a specific repository. This is currently done on request (due to manpower). For Ubuntu, similar mechanisms exist, but they were not used yet at all -- volunteers are welcome here.

That is agreeable a bit suboptimal, and probably we should have some common strategy how to do the versioning here properly. This also affects other non-rolling distributions like Fedora (@sergiopasra).

@KeithSloan -- I will try to fix this in Ubuntu; however this will take some time (also because of the slow distribution machinery which requires some approvals by Ubuntu officials).

**Comment by bsipocz** [comment]
> Well, that is my fault -- I didn't think about which version to select, and just the latest release went into Ubuntu. Same will happen for Debian Buster where 3.1.2 will end up. And both will stay, only with (selected) important bug fixes applied if needed.

well, at the end it doesn't matter that much. We nominally support the LTS for 2 years, but if the distros life cycle is 5 years then it doesn't really matter which release was picked to begin with. And your testing is extremely valuable as it recovers numerous bugs that slips through CI.  It's just the unfortunate fact that timescales differs this much, but then the purpose of a science package and an LTS operating system is different.

**Comment by mhvk** [comment]
It does not seem we can do anything about this issue - and hopefully it has not been an issue recently - so closing.
