### ISSUE TITLE
BUG: Frame attributes in sky coordinates do not obey Numpy broadcasting rules

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#8812]
Originally prompted by @mhvk in  https://github.com/astropy/astropy/pull/8805#discussion_r291744415. 

The crux of the issue is this: this doesn't work:
```
from astropy import units as u
from astropy.coordinates import FK5
from astropy.time import Time

FK5(0*u.deg, 0*u.deg, equinox=time.Time(['J2000', 'J2001']))
```
whereas this does:
```
FK5([0]*2*u.deg, [0]*2*u.deg, equinox=Time(['J2000', 'J2001']))
```

The latter proves that there's nothing in the machinery to prevent this all working the way you'd want, but the fact that the former fails is a sign that the broadcasting is not working the way you'd expect - e.g. ``1 + np.random.randn(2)`` works just fine so it seems like the former example here should. 

I consider this a bug because it was always the *intent* for broadcasting to work naturally in places like this.  

cc @adrn

**Comment by Cadair** [comment]
:+1: this could be *super* useful for a bunch of SunPy stuff.

**Comment by mhvk** [comment]
@eteq - now that I look at your examples again, I vaguely recall that at the time we felt that attributes should not have a shape that includes dimensions that the coordinates do not have. Indeed, we [specifically test](https://github.com/astropy/astropy/blob/master/astropy/coordinates/attributes.py#L112) that the attribute can be broadcast to the shape of the representation.

In principle, we can change this to a test that the attribute and the coordinates can be broadcast together - though for sure that means that we should then actually broadcast the coordinates (otherwise slicing will become strange), i.e., the output of your two examples should be identical (they both have shape `(2,)`. Is this what you envision?

A question that arises is what to do with setting an attribute after the fact. It may not be crazy to insist that for that case the attribute must still be broadcastable to the instance's shape, so that we can guarantee that the instances shape does not change.

In fact, just doing it in the initializer might make things cleaner, as it may well be possible to avoid the [specific logic](https://github.com/astropy/astropy/blob/master/astropy/coordinates/baseframe.py#L598) for the case that a frame has no data

**Comment by mhvk** [comment]
Doesn't seem like anybody is getting around to this, so removing milestone.

**Comment by lpsinger** [comment]
> A question that arises is what to do with setting an attribute after the fact. It may not be crazy to insist that for that case the attribute must still be broadcastable to the instance's shape, so that we can guarantee that the instances shape does not change.

I agree with that.

**Comment by mhvk** [comment]
@lpsinger - as I wrote over in #11571, I think your example serves to make clear that really we need to fix this! It should not actually be all that hard....

**Comment by mhvk** [comment]
See also discussion following https://github.com/astropy/astropy/pull/13398#discussion_r929752132, which showed that even the person who wrote the initial code continues to think that broadcasting works, when it at present does not.
