### ISSUE TITLE
WCSAxes silently ignores SIP coefficient

### ISSUE THREAD

**Issue by ceb8** [astropy/astropy#8813]
When using WCSAxes to plot an image, the underlying function used is `wcs.wcs_world2pix` rather than `wcs.all_world2pix`, meaning that any SIP coefficients are ignored.  This can cause problems as demonstrated in this notebook: https://github.com/ceb8/tessworkshop_wcs_hack/blob/master/tesscut_wcs_hack.ipynb

Suggest producing a warning if SIP coefficients are detected in the WCS object passed to WCSAxes.

**Comment by pllim** [comment]
cc @astrofrog and @nden

**Comment by astrofrog** [comment]
In principle there's no reason we couldn't use the ``all_`` function in WCSAxes, or have a keyword-argument to control whether or not to use the distortions. The latter would probably make sense because I've seen files that had leftover distortions in the header which should be ignored.

@ceb8 - would you be interested in trying to add a keyword argument to control this?

**Comment by ceb8** [comment]
@astrofrog Yeah, I can look into adding a keyword argument for this.

**Comment by ceb8** [comment]
The changes to WCSAxes due to the APE 14 updates have solved this problem in the next release.
