### ISSUE TITLE
Upstream minimal versions to support for v4.0 LTS

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#8822]
I open this  issue as a place to discussion which versions we drop from support for the upcoming LTS release. 

E.g. shall be support numpy 1.15+ or be even more drastic and do 1.16+?

Other packages to consider: matplotlib, pytest, sphinx, scipy, etc.

**Comment by pllim** [comment]
Complete list, for reference:

https://github.com/astropy/astropy/blob/c9d7d401295685f2c41046e1a5ec9f390bd55ac9/setup.cfg#L27-L30

https://github.com/astropy/astropy/blob/c9d7d401295685f2c41046e1a5ec9f390bd55ac9/setup.cfg#L47-L75

**Comment by mhvk** [comment]
Repeating a note made elsewhere: for a LTS release, it seems reasonable to be relatively strict, since we are stuck with versions for 2 years.

For the extras, we rarely seem to define minimum versions (e.g., for scipy I am fairly sure there is one). Overall, this is probably OK.

**Comment by bsipocz** [comment]
I'm not sure we even have a blanket scipy limit, except of course the minimum will be the one that added support for the minimum numpy version we require.

**Comment by mhvk** [comment]
As a random data point, in https://github.com/astropy/astropy/pull/8782, @astrofrog has to work around issues with matplotlib < 2.2, so perhaps 2.2 could be a minimum (released Mar 2018). Or (my preference), we could be bold and go with the python-3 only version 3.0 (Aug 2018).

**Comment by bsipocz** [comment]
I'm interested what @taldcroft and @olebole think?

I would be definitely on board to be more strict when we start a new LTS, that would also probably have the side effect that we don't necessarily need to drop support in consecutive non LTS feature releases.

**Comment by taldcroft** [comment]
I'm not precisely sure what "strict" means, but from context that means bumping to the latest possible?  

I can add a real-world story of astropy in a production environment.  For Chandra operations we are still using astropy 3.0.x.  That isn't directly driven by wanting to be on LTS, but rather a convoluted set of circumstances that requires we support CentOS-5.  In order to avoid building the entire scientific stack ourselves, we are using an old set of conda packages from when conda was built on CentOS-5.  So that means numpy 1.12.1.  Which means astropy 3.0.  This does not make me happy, but if I found out that astropy 4.0 required such new packages that I could not even support CentOS-6 or 7, then I would be a bit annoyed.

Takeaway - there are users of astropy that are stuck on ancient OS's and weird reasons that the whole stack can get dragged down.  So generally my take is to support as old as we can until it becomes a bit painful.

About the LTS, from my perspective that is exactly the release to be most *conservative* with upgrading versions.  That takes care of our institutional customers that may be stuck on older versions.  Then on LTS + 1 feature release you can up-rev a lot.  Those folks staying on LTS for 2 years (and living with only getting bug fixes) are generally not chomping at the bit to get everything bleeding edge.

At Chandra we do hope to get up to CentOS-7 within a year and modernize the whole stack, but I'm terrified of what will break with the latest numpy from 1.12.  Our testing ranges from OK to almost non-existent..  sigh.

**Comment by bsipocz** [comment]
Then the question is that how many new features from astropy would such pipelines need? I foresee that there won't be that many bugs needing to be fixed in 2.0 even after we drop support, and supporting numpy releases back to many years is actually a bit painful (see those messy repr doctest issues, etc.). I suppose the logic here was to have a big step at the LTS change, when downstream might need to do their upgrades anyway, and whether it's an upgrade to np 1.13 or np 1.15 is probably the same pain.)
Also, supporting something that stops receiving updates in the middle of our release (centOS-7: Q4 2020) seems rather suboptimal.
 
Do you have a list of centos-7 python packages? I can't find one easily.

**Comment by taldcroft** [comment]
Chandra may be a special case, but mostly I'm interested in performance enhancements.  I already had to work around problems in Table, and those workarounds ended up being the basis for some Table performance PRs in 3.2.  But whatever, the workarounds are in the Chandra ops code and they work.

To be clear, we don't use any CentOS python packages, it's 100% conda, with most of the core packages coming from the Continuum builds and the rest as custom conda builds.

I think you misread versions, CentOS-6 is EOL in 2020, CentOS-7 is until 2024, at least if wikipedia is right.

In any case, I see your points and one part of me wants to get everything to the latest.  But I just wanted to share my perspective that you'd be surprised what some institutions are running.

**Comment by bsipocz** [comment]
> I think you misread versions, CentOS-6 is EOL in 2020, CentOS-7 is until 2024, at least if wikipedia is right.

yes, I read the same table, but took the middle column of "Updates" rather than security updates from the last column. The 10 year lifetime of CentOS is just unrealistic for any python package to keep up with.

On the other hand, I wonder whether there would be any limitations for using pip wheels rather than conda for Chandra? Most packages are building wheels now, and support for older version combinations are dropped much later than in the conda world (as far as I see).

**Comment by mhvk** [comment]
Hmm, I see the point of the pain. In a way, astropy 4.0 is a bit special, though, since it is the first LTS for python3 only, and extends well beyond the python2 cutoff. One might argue that one should go with the python3-only versions of the packages we use as well.

Maybe this is one for the mailing list?

**Comment by olebole** [comment]
@bsipocz Minimal versions? To ease backports, best would be the current (Debian Buster) versions: numpy 1.16, matplotlib 3.0.2, pytest 3.10, sphinx 1.8.5, scipy 1.1.0, Python 3.7.3. However, except for the Python version, this is not that important, since in the worst case, we would need to backport the updated dependency as well (which then should not result in a chain of dependency backports). We can also choose to somehow work around "unimportant" stuff (Do we really need a perfect doc-package for the backport? However: Tests are probably too essential to just disable them).

**Comment by bsipocz** [comment]
> One might argue that one should go with the python3-only versions of the packages we use as well.

scipy python3 only version is 1.3, that is a few weeks old only. On the other hand I can't foresee that saying we support scipy 1.3, would not also mean that anything 1.0+ would still work, maybe even beyond (after all we're not testing for those anyway, the matrix only has numpy and mpl combinations).

However setting a minimum version would be good for our CI, we can actually start testing for the min versions as well as for the latest ones without wasting to much CPU time.

**Comment by bsipocz** [comment]
Due to the packaging issue we run into (#8671), I would be very much in favour of having np 1.16 as minversion for 4.0, otherwise it'll be a logistical nightmare of remembering to always use an old numpy  to create the releases.

**Comment by pllim** [comment]
Whatever we decide, it needs to be advertised somewhere people can find. Either core docs or APE would be good, IMHO.

**Comment by mhvk** [comment]
Trying to imagine what would be most useful to users, it might be that the release notes of a given version should not just state what the minimum version for the given version is, but also what it will be for tne next. I.e., version 3.2 release notes would already have what will be the minimum versions for astropy 4.0.

Concretely, this might mean separating out from `install.rst` the requirements.

Alternatively, and perhaps simpler, we could have an APE that describes the process (and is allowed to be updated), with a link to it in the requirements section.

**Comment by bsipocz** [comment]
Oh, and we should say something about the Cython version, too: https://github.com/astropy/astropy/issues/3473

I'm perfectly OK with the suggestion in that issue to always use the latest to create the sdist.

**Comment by astrofrog** [comment]
@taldcroft - I also have the same question as @bsipocz regarding why you can't use wheels instead of conda? To me, it seems like some of the limitations you are running into are based on what the conda team has chosen to support, but in principle there's no reason you can't pip install Numpy 1.16 on CentOS 6 or 7, right?

**Comment by taldcroft** [comment]
@astrofrog - about conda vs wheels, basically we made a decision about two years ago to go all in on conda, and spent about a year building a system around that (https://github.com/sot/skare3).  One of the key features is having meta-packages that allow 100% pinning / dependency control of every package.  Our "flight" environment has every package configuration controlled for flight operations so it is basically not allowed to change any package version [1].  The infrastructure of build recipes and the rest works pretty well for us, and the "guarantee" of consistency of core package (numpy, scipy, matplotlib) provided by the uniform Continuum conda builds is re-assuring.

Once we get away from the CentOS-5 requirement, then the rest should work perfectly well.

[1] - is there any analog in pip / wheels now?  Basically an environment-level set of package requirements that are consistently solved?

**Comment by taldcroft** [comment]
And the takeaway from the above is just that some organizational users are doing things that might seem insanely conservative or replaceable by more agile systems, but that's the reality (esp. for satellite ops).

But I also said that I don't mind the plan of pushing all packages as far forward as people want, we'll deal (or else not upgrade from astropy 3.0 if it comes to that...).  Welcome to my world.  :smile:

**Comment by bsipocz** [comment]
As @mhvk pointed out this numpy NEP is somewhat related (though the picture is bigger with discussing CPython support): https://github.com/numpy/numpy/pull/14086

**Comment by bsipocz** [comment]
This ship has long sailed, so closing the issue.
