### ISSUE TITLE
TST: Remove arbitrary pytest markers and replace ccd_data fixture

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8879]
As @bsipocz pointed out, `pytest` emits the following warning in `nddata` tests (turned into error in this exercise), which we currently ignore:

```
__ ERROR collecting astropy/nddata/tests/test_ccddata.py __
astropy/nddata/tests/test_ccddata.py:98: in <module>
    @pytest.mark.data_size(10)
.../_pytest/mark/structures.py:337: in __getattr__
    PytestUnknownMarkWarning,
E   _pytest.warning_types.PytestUnknownMarkWarning: Unknown pytest.mark.data_size
- is this a typo?  You can register custom marks to avoid this warning
- for details, see https://docs.pytest.org/en/latest/mark.html
```

This is because of

https://github.com/astropy/astropy/blob/a22c724006036c1ddf5e68aa896ae90bf7e0b6a0/astropy/nddata/tests/test_ccddata.py#L38-L43

https://github.com/astropy/astropy/blob/a22c724006036c1ddf5e68aa896ae90bf7e0b6a0/astropy/nddata/tests/test_ccddata.py#L46-L47

https://github.com/astropy/astropy/blob/a22c724006036c1ddf5e68aa896ae90bf7e0b6a0/astropy/nddata/tests/test_ccddata.py#L64

https://github.com/astropy/astropy/blob/a22c724006036c1ddf5e68aa896ae90bf7e0b6a0/astropy/nddata/tests/test_ccddata.py#L98-L99

I think the tests would still work if we remove `ccd_data` as a fixture, but rather re-implements it as a helper function that takes all those custom markers as regular arguments. Better yet, we can memoize that function so that requesting array of same size will return a cached copy instead of creating a new one from scratch (more memory usage but better performance). Given that `ccd_data` generates random number and there is no reason why randomness has to be that random between different unit tests, memoization is probably okay?

What do you think, @mwcraig , @crawfordsm , or @MSeifert04 ?

**Comment by MSeifert04** [comment]
> I think the tests would still work if we remove ccd_data as a fixture, but rather re-implements it as a helper function that takes all those custom markers as regular arguments. 

I agree. I tend to avoid markers for such things because it makes the whole setup much less discoverable. In some cases they really make sense, however in the end (and in my opinion) a fixture is essentially just a helper function that's very hard to find. 😄 

However I wouldn't go so far as to memoize the function (just yet). That's probably premature-optimization. In case the creation of ccddata objects is really a performance problem we probably should invest the time and check if we can reduce the size of these objects. It's always good to reduce power/setup, but there are probably much more (and more significant) low-hanging fruits in our test suites.

**Comment by crawfordsm** [comment]
That sounds like a reasonable solution to me.  Thanks for taking a look at
this !

**Comment by mwcraig** [comment]
I agree  the comments the others made. If memoization is easy ten I don't think it would hurt.

**Comment by MSeifert04** [comment]
Okay, seems like we all agree. I could have a look into this if none of you is already working on that.

**Comment by mwcraig** [comment]
go for it!
