### ISSUE TITLE
Deprecate representation, remove _normalize_representation_type

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8886]
In #7958 , @adrn wrote this

https://github.com/astropy/astropy/blob/a22c724006036c1ddf5e68aa896ae90bf7e0b6a0/astropy/coordinates/sky_coordinate_parsers.py#L200-L201

I am not very sure what this means or when "future" is.

**Comment by adrn** [comment]
This should read "deprecate the .representation attribute, remove this in future"

"future" was intentionally left vague, because we agreed for @taldcroft that we would do a "soft" deprecation of this attribute: we added `.representation_type` in its stead, and changed all documentation, but didn't begin deprecating `.representation`. I guess we could officially deprecate this for v4.0, and start the clock to remove in the next LTS version? 🤷‍♂cc @eteq

**Comment by taldcroft** [comment]
Sounds fine to me.

**Comment by bsipocz** [comment]
>  I guess we could officially deprecate this for v4.0

To minimize the chance of not running into this issue before the release I added the milestone.
