### ISSUE TITLE
coordinate transformation graph becoming unreadable

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#8999]
http://docs.astropy.org/en/latest/coordinates/index.html#module-astropy.coordinates - rather impossible to see what is there.  Might help to make graph direction left to right instead of top to bottom, so that frames in similar positions form a column rather than a row.

![image](https://user-images.githubusercontent.com/2789820/61235946-c3e84e00-a704-11e9-82c7-0987e6e158df.png)

**Comment by ayshih** [comment]
After #9001, the transform graph looks much better, at least for Astropy's graph (see below).  However, I am annoyed that #9001 actually make things worse for SunPy's graph because we have three additional ranks below HCRS, so everything gets squished badly.  I'm going to find a way to move the HCRS node.

![astropy-graph](https://user-images.githubusercontent.com/991759/61244975-732f2000-a719-11e9-89e5-d9171131e118.png)

**Comment by mhvk** [comment]
Beautiful! As you say, it should be possible to move `HCRS`, e.g. above `GCRS`.

Aside: wonder why GCRS->HCRS doesn't have a reverse transformation...
