### ISSUE TITLE
Rationalize blackbody models/functions

### ISSUE THREAD

**Issue by karllark** [astropy/astropy#9066]
There are three ways to calculate the emission from a blackbody in astropy.modeling - BlackBody1D, blackbody_lambda, and blackbody_nu.  The first is a full fittable 1D model and the latter two are functions.  The same answer is obtained with BlackBody1D and blackbody_nu (as stated in the docs).  Having 3 ways seems at least 1 too many.

It would be more consistent if any and all blackbody models in modeling were full fittable 1D models.  Mainly as all the rest of the models in modeling are modeling.models, not functions.

Probably it would be good to keep the two functions, but should deprecate them.

Additional minor comment.  BlackBody1D has two parameters - temperature and bolometric luminosity.  The 2nd parameter is more specific to (likely) stellar astrophysics - other areas of astronomy use other scalings usually a simple multiplicative amplitude (would allow other units).  It would be good to support a more generic way of supplying the amplitude (instead of bolometric or in addition).

**Comment by pllim** [comment]
To add to the fun, `synphot` has its own [BlackBody1D](https://github.com/spacetelescope/synphot_refactor/blob/6b09100d2fa855db831ca81e7692d71e5550e833/synphot/models.py#L39) and [BlackBodyNorm1D](https://github.com/spacetelescope/synphot_refactor/blob/6b09100d2fa855db831ca81e7692d71e5550e833/synphot/models.py#L139) classes. 😬

**Comment by karllark** [comment]
@pllim : would it be worth a discussion to see if there is a path forward to getting the capabilities that are in synphot into the astropy.modeling BlackBody1D model?

**Comment by pllim** [comment]
Yes, we should discuss it. I did not move it up because the models in `synphot` are "historical"; that is, I cannot change the API, and hence lack flexibility.

**Comment by karllark** [comment]
The equivalent of `blackbody_lambda` and `blackbody_nu` can be obtained from `BlackBody1D` using the appropriate unit conversion. 

![bb_check](https://user-images.githubusercontent.com/1554536/62377592-100efd00-b511-11e9-9cb5-ce846fbff221.png)

Code showing the conversions (and plot).
```
import numpy as np
import matplotlib.pyplot as plt

from astropy.modeling.blackbody import blackbody_lambda, blackbody_nu
from astropy.modeling.blackbody import BlackBody1D
import astropy.units as u
from astropy import constants as const

wavelengths = np.logspace(np.log10(1000), np.log10(3e4), num=1000) * u.AA

# blackbody parameters
temperature = 10000 * u.K

# provides the result in ergs/(cm^2 Hz s sr)
spectrum_lam = blackbody_lambda(wavelengths, temperature)

# provides the results in ergs/(cm^2 A s sr)
spectrum_nu = blackbody_nu(wavelengths, temperature)

# BlackBody1D provides the resultrs in W/m^2
#   the amplitude is specified as bolometric flux in ergs(cm^2 s)
bolometric_flux = const.sigma_sb * temperature ** 4 / np.pi
bolometric_flux.to(u.erg / (u.cm * u.cm * u.s))
bb_astro = BlackBody1D(temperature=temperature, bolometric_flux=bolometric_flux)

# plot the nu and lam results from both methods
fig, ax = plt.subplots(ncols=2, figsize=(8.0, 4.0))

# lambda forms
ax[0].plot(wavelengths, spectrum_lam, label="spectrum_lam", linewidth=6, alpha=0.5)

# the BlackBody1D has to be converted to the spectrum_nu units
ax[0].plot(
    wavelengths,
    bb_astro(wavelengths).to(
        u.erg / (u.cm * u.cm * u.Angstrom * u.s),
        equivalencies=u.spectral_density(wavelengths),
    )
    / u.sr,
    label="BB1D_lam",
)

# nu forms
ax[1].plot(wavelengths, spectrum_nu, label="spectrum_nu", linewidth=6, alpha=0.5)

# the BlackBody1D has to be converted to the spectrum_lam units
ax[1].plot(
    wavelengths,
    bb_astro(wavelengths).to(u.erg / (u.cm * u.cm * u.Hz * u.s)) / u.sr,
    label="BB1D_nu",
)


ax[0].set_xlabel(r"$\lambda$ [{}]".format(wavelengths.unit))
ax[0].set_ylabel(r"$Flux$ [{}]".format(spectrum_lam.unit))

ax[1].set_xlabel(r"$\lambda$ [{}]".format(wavelengths.unit))
ax[1].set_ylabel(r"$Flux$ [{}]".format(spectrum_nu.unit))

ax[0].set_xscale("log")
ax[0].set_yscale("log")

ax[1].set_xscale("log")
ax[1].set_yscale("log")

ax[0].legend(loc="best")
ax[1].legend(loc="best")

plt.tight_layout()
plt.show()
```

**Comment by karllark** [comment]
> To add to the fun, `synphot` has its own [BlackBody1D](https://github.com/spacetelescope/synphot_refactor/blob/6b09100d2fa855db831ca81e7692d71e5550e833/synphot/models.py#L39) and [BlackBodyNorm1D](https://github.com/spacetelescope/synphot_refactor/blob/6b09100d2fa855db831ca81e7692d71e5550e833/synphot/models.py#L139) classes.

@pllim : it looks like the synphot BlackBody1D is mainly a wrapper around BlackBody1D.  But maybe with an extra property or two.  So the astropy.modeling BlackBody1D is very close to what synphot uses, but returns in different units.

**Comment by karllark** [comment]
I would recommend two changes and one optional change.

1) deprecate `blackbody_lam` and `blackbody_nu`.  These two functions are the *only* two in astropy.modeling that do not use the model classes.  In addition, they can be calculated from each other or BlackBody1D using the wonder of astropy.units.
Fine with keeping them around, but they should no longer be recommended/advertised.

2) Update the BlackBody1D class to be more general.  Currently, the amplitude is given as the bolometric luminosity and the results is bolometric flux.  This is does not seem what would be expected by a general user.  For example, computing the emission from an extended structure (gas or dust emission) would expect to get the result in surface brightness, not flux.
Changing the BlackBody1D to have the units of the amplitude give the appropriate results in the same units would make the function more general.  

3) *Optional* The current BlackBody1D could be renamed to BolometricBlackBody1D to support the intended use case.  Such a renaming would provide a nice descriptive name that would be less confusing to the general user.

**Comment by pllim** [comment]
@karllark , Option 2 is possible but we need to be careful about backward compatibility. 4.0 is LTS, so we'll be stuck with the consequences for 2 years after release. Option 3 sounds non-backward compatible because it sounds like you plan to change default behavior of `BlackBody1D` after renaming it?

**Comment by nden** [comment]
Ping - ing @eteq @astrofrog

**Comment by karllark** [comment]
> @karllark , Option 2 is possible but we need to be careful about backward compatibility. 4.0 is LTS, so we'll be stuck with the consequences for 2 years after release. Option 3 sounds non-backward compatible because it sounds like you plan to change default behavior of `BlackBody1D` after renaming it?

It might be possible to pick option 2 and if the units of the amplitude are input as a luminosity to have the  results in bolometric flux.  Maybe be able to set the scaling with `amplitude` or `bolometric_flux` making it possible to have the current behavior and while supporting a more general behavior.

**Comment by dhomeier** [comment]
From a naïve theorist's POV I find the current behaviour rather confusing. Blackbody flux in the strict sense only depends on a single parameter, temperature, so it should return a unique value of F_lambda/F_nu as the default. A scale could enter in various forms like a generic factor for optically thin emission. With the current `bolometric_flux` parameter the user needs to first manually calculate the correct spectrum-integrated bolometric flux as in the example above, making this inconvenient as a generic substitute for `blackbody_lambda`, `blackbody_nu` at this point.
OTOH the flux unit the `bolometric_flux` parameter is supplied in already conveniently sets the output unit accordingly (e.g. `bolometric_flux=1*u.Unit('erg/(cm2 s)')` will return the output in `erg/(cm2 Hz s)`, `bolometric_flux=1*u.Unit('W/m2')` in `W/(Hz m2)` etc., but this looks a bit more like an Easter egg than good API design.

Ideally, IMO the default behaviour would be to return the correct BB flux density (IOW have `bolometric_flux=const.sigma_sb * temperature**4 / np.pi` as default), but that is obviously not doable in light of the backward compatibility issues. One could leave the `bolometric_flux` parameter as an optional form, and add an alternative scale keyword, making clear this is indeed simply a dimensionless scaling factor (something like just `scale` sounds more intuitive to me than `amplitude` in this context). Maybe a solution to the issues of your Option 2 could be to use the new default `bolometric_flux=const.sigma_sb * temperature**4 / np.pi` **if** the new `scale` parameter is present, and stick with the old default of `1. erg/(cm2 s)` otherwise. Optionally make your suggested `BolometricBlackBody1D` a wrapper for the latter case, although I still see some potential for confusion with both options.
Also the desired output unit could then better be set via a separate *kw. Although it's easy enough to set it with `.to('unit')` afterwards anyway.
Finally to become a useful substitute for `blackbody_lambda` I strongly advocate for an additional option to internally convert to F_lambda to spare the user the hassle with `equivalencies=u.spectral_density(wavelengths)`. In fact my natural assumption would be that an F_lambda is automatically returned when called with a wavelength, and F_nu for a frequency, but that would obviously create backward compatibility issues as well

**Comment by karllark** [comment]
In person discussion with @nden @jdavies-st @perrygreenfield summary of a proposed solution for the BlackBody1D parameter issues.

Create BlackBody model with temperature and scale as parameters (put in new file called 'physical_models.py').  Avoids breaking functionality provided by BlackBody1D where the parameters are temperature and bolometric_flux.

Deprecate BlackBody1D, blackbody_lam, and blackbody_nu.

Provide documentation that shows how to get the same functionality from BlackBody that are currently provided by the three deprecated functions.

**Comment by pllim** [comment]
Why a new module? Why not put your `BlackBody` in the same module as the deprecated `BlackBody1D`?

**Comment by karllark** [comment]
The basic idea is that this provides a module for other physical models.  There likely will be others (e.g, the Drude model is an electron in a solid).  Other physical (versus mathematical) models can then go in this module.  Just seems better setup for the future.
