### ISSUE TITLE
Wrong transfrom SkyCoord to AltAz

### ISSUE THREAD

**Issue by altairgomes** [astropy/astropy#9138]
```python
from astropy.coordinates import SkyCoord, AltAz, EarthLocation
import astropy.units as u
from astropy.time import Time
site = EarthLocation( +314.417361100,   -22.53550000,    1864.0)
time = Time('2019-08-15 04:00:00')
```

Coordinate without distance:
```python
coord = SkyCoord('19 30 41.1132', '-22 16 37.2904', unit=(u.hourangle,u.deg), location=site, obstime=time)
coord.transform_to(AltAz())
Out: <SkyCoord (AltAz: obstime=2019-08-15 04:00:00.000, location=(4126307.21644704, -4211092.88677915, -2430002.83327423) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt) in deg
    (261.49067159, 48.80042555)>
```

Coordinate with distance:
```python
coord = SkyCoord('19 30 41.1132', '-22 16 37.2904', 10, unit=(u.hourangle,u.deg, u.AU), location=site, obstime=time)
coord.transform_to(AltAz())
Out: <SkyCoord (AltAz: obstime=2019-08-15 04:00:00.000, location=(4126307.21644704, -4211092.88677915, -2430002.83327423) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0.0, obswl=1.0 micron): (az, alt, distance) in (deg, deg, m)
    (259.97101219, 45.70743971, 1.36938057e+12)>
```

The difference is too large to be explained by parallax.

**Comment by pllim** [comment]
Why does this sound familiar? Maybe @eteq or @adrn can follow up.

**Comment by StuartLittlefair** [comment]
Sorry this took so long to get around to! 

Actually, this is just parallax.

```python
from astropy.coordinates.solar_system import get_body_barycentric
# direction of object at infinite distance (no parallax)
coord = SkyCoord('19 30 41.1132', '-22 16 37.2904', unit=(u.hourangle,u.deg))
dir1 = coord.cartesian

# at finite distance. rough parallax correction
earth = get_body_barycentric('earth', time)
coord = SkyCoord('19 30 41.1132', '-22 16 37.2904', 10, unit=(u.hourangle,u.deg, u.AU))
dir2 = coord.cartesian - earth
dir2 /= dir2.norm()

# angle between them
np.arccos(dir1.dot(dir2)).to(u.deg)
# Quantity 3.25990391 deg
```

**Comment by altairgomes** [comment]
Ok. So the problem here is that I understood the SkyCoord with a given site to be topocentric,
or at least geocentric, which is not the case.
Instead, it is barycentric (ICRS) but then corrected to the topocenter when transforming to AltAz.
In this case, I think it may be confusing allowing a location in SkyCoord if this location is not at the origin of the coordinates given.
I think you should reconsider it.
Anyway, I'll be passing the GCRS to the SkyCoord frame attribute to get the expected transform.

Thank you for your reply.

**Comment by StuartLittlefair** [comment]
hi @altairgomes 

If you want a topocentric or geocentric coordinate frame, you have to specify that when you construct the `SkyCoord`. The default frame is `ICRS`.

As you say it is confusing that you can create a SkyCoord the way you have done here; adding `location` to a `SkyCoord` which is in a frame for which `location` makes no sense. However, we are stuck with this somewhat, since a `SkyCoord` can have attributes that don't make sense for the frame to allow round-trip transforms. 

For example, one might create a `SkyCoord` in a topocentric `GCRS` frame and transform to ICRS and back again. The `SkyCoord` will remember the location attributes of the topocentric frame so a transform back to GCRS gives the original coordinate.
