### ISSUE TITLE
Update Galactocentric default parameters?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy#9199]
Thanks to [GRAVITY](https://ui.adsabs.harvard.edu/abs/2018A%26A...615L..15G/abstract), [Gaia](https://ui.adsabs.harvard.edu/abs/2019MNRAS.482.1417B/abstract), and [a combination of GRAVITY+VLBA](https://ui.adsabs.harvard.edu/abs/2018RNAAS...2d.210D/abstract), we now have new standard measurements of the solar motion, sun-galactic center distance, and solar height above the midplane. Given this, it's probably time to update the default Galactocentric frame parameters in astropy.coordinates. But is this a good idea? Updating the defaults will affect code downstream for anyone using the default frame. On one hand, maybe this is OK: if anyone wants to be certain of the frame they are using, we could recommend that they hard-set the values. On the other hand, this could lead to some confusion from users. So, what should we do: Change the values? Make a new `Galactocentric2019` frame? or?

Thoughts? @eteq @mhvk @Juanlu001

**Comment by mhvk** [comment]
Looking at the current frame, I see it is a collection of references; I guess there is not an IAU working group or so responsible for defining this, unlike for `Galactic`? It might not be a bad idea to contact whatever is the most relevant group and ask if they are planning to have a recommendation.

Barring that, we could perhaps repurpose [machinery in `constants`](http://docs.astropy.org/en/latest/constants/index.html#collections-of-constants-and-prior-versions) to provide different versions? (Or `cosmology`?)

Overall, I do think `GalactoCentric` itself should aim to be the best currently available.

**Comment by eteq** [comment]
Hmm. I tend to think there is indeed no formal definition to worry about here - in the past the IAU has generally been mostly concerned with frames as abstract coordinate constructs, rather than physically interpretable things.  And indeed that's how I think we originally cast `Galactic` vs `Galactocentric` - the former is the conventional construct, whereas the later has all the extra parameters because it's meant to be at the discretion of the user which parameters to trust.

That said, I see @mhvk's point that a quick check to ensure there aren't plans afoot to make some sort of official something-or-other of relevance.  The trouble is, I really have no idea which IAU commission applies here - it's probably something in (division A)[https://www.iau.org/science/scientific_bodies/divisions/A/], right? Conveniently, I am a member of that division so could ask around if we agree that's the best place to start?

I don't think asking that should stop us from moving forward as @adrn proposes unless there's something obvious/imminent, though. My initial instinct is to go with @adrn's suggestion of:

> if anyone wants to be certain of the frame they are using, we could recommend that they hard-set the values

That is, we can update the documentation to say that we are *not* guaranteeing the defaults are stable, but rather that they are "most recent good guesses" or similar.

I'm inclined to not go the direction of e.g. re-purposing `constants` machinery unless we want to do this for other frames too, though. And conceptually in other spaces I think we've tended towards defining *new* frames for that sort of thing (or frame-generating functions) instead of stateful defaults.

Actually that makes me think of one more option though: we could instead change to a function called `get_latest_galactocentric_frame` or something like that, which would yield our "current best" answer.  I.e., leave the defaults as they are for backwards compatibility but switch the docs and examples to use that function instead with a note demonstrating *why* that is done?  It's not ideal but it's a way to avoid the backwards compatibility issues...?

**Comment by mhvk** [comment]
Thanks, I think it would be good to ask about IAU defaults (if only as a way to let people know that, if this doesn't happen, `astropy` will start to *define* standards by default...)

But also agreed that we should just move on. My sense would be to just update `Galactocentric` - i.e., the default is the latest and greatest is. The main question is then in what form to provide information about previous versions. Options:
1. Nothing. Just mention that the current values were used since astropy 4.0.
2. Mention previous values in docstring only
3. Another class (which can be mentioned in docstring)
4. Some mechanism a la `constants` - from `astropy.coordinates.astrocoord20 import Galactocentric`.

Right now, I'd lean towards easiest, i.e., option (1), but I don't really use it...  The disadvantage of 3 and 4 is that it introduces more stuff that needs to be maintained/tested/etc without it being clear at all it would ever be used.

**Comment by adrn** [comment]
Thanks for the thoughts @eteq and @mhvk! 

I think I lead towards option 1 of Marten's list as well. I think we can add a references to the previous values in the docstring, and we could even provide a function for retrieving the past values, but I would be in favor of adopting the convention that `Galactocentric` will stay "modern". I will also send an email to IAU folks to find out if there is any plan for defining a standard, but I doubt they will take a stance here...

**Comment by adrn** [comment]
This was done in #9322
