### ISSUE TITLE
CDS reader ignores nullability for columns with a limits specifier

### ISSUE THREAD

**Issue by ajtribick** [astropy/astropy#9291]
The CDS reader fails to treat columns as nullable if the ReadMe file contains a limits specifier. Examples include the `Tc`, `Lc` and `phi` columns of the main.dat file in [XHIP (V/137D)](http://cdsarc.u-strasbg.fr/ftp/V/137D/ReadMe)

The issue appears to be the following regular expression: https://github.com/astropy/astropy/blob/af4708ec1aedccdd1fb304704a59fcb7f29ec567/astropy/io/ascii/cds.py#L128-L129

 This will only match a `?` character at the start of the description. As the [file format description](http://vizier.u-strasbg.fr/doc/catstd-3.4.htx) states, the limits must be specified *before* nullability.

As a local fix, I have replaced the regular expression with

    r'(?:[\[\]] \S* [\[\]])? \? (?P<equal> =)? (?P<nullval> \S*) (\s+ (?P<descriptiontext> \S.*))?'

This handles the case where limits are supplied. I'm not sure either this or the current version will work properly in the presence of order specifiers though.

**Comment by bsipocz** [comment]
cc @cds-astro/cds

**Comment by bhavyakh** [comment]
A general solution for this issue can be to search for descriptions with '?'  and some string following it (so as to prevent a 'question mark' at the end of a string). As in [XHIP (V/137D)](http://cdsarc.u-strasbg.fr/ftp/V/137D/ReadMe) the '?' is in between the description text. 
Can you confirm if there are ReadMe files that have '?' character in between the description string but are not meant to be nullable, I looked at a few files from the Vizier Database, didn't find any. @hamogu 
(except "when the ? is followed by the = sign and a numeric value without intervening space, the value is the alternative NULL value and is equivalent to the FITS TABLES extension TNULL keyword, e.g. ?=99.99 "  as given at [File format description](http://vizier.u-strasbg.fr/doc/catstd-3.4.htx) )

**Comment by hamogu** [comment]
I don't know if there are such tables, but I don't see the ? explicitly forbidden in the text of the description. We don't want ot go through all CDS table so see if anyone ever came up with a description like this "We use ? to say this is important to solve and ! to make where out method can be applied". Probably not, but since the failure described in this PR is also a really rare case, it might be good not to replace this with another edge case. 

I would build on the regex that was suggested above and add a "order" group to it. The format is pretty explicit. https://regex101.com should be able to help you puzzle together all the pieces - that's a great tool to see immediately what is what is matched to what and to try out interactively how my regex needs to be adjusted.
