### ISSUE TITLE
Impossible to input np.longdouble into custom time formats

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#9341]
I am trying to write a custom time format "mjd_long" which accepts and returns np.longdouble values upon conversion, to make nanosecond accuracy easier. Unfortunately during the preparation stage, before values are handed off to the custom code, they are passed through _make_array, which forcibly converts any non-approved types, including np.longdouble, into np.float64, losing accuracy in the process. As far as I can tell it is a simple matter of allowing higher-precision numerical dtypes (np.float96, np.float128, np.longdouble) through untouched. There is some delicacy about platforms like Windows/MSVC that do not have extended-precision types, where I think some of the type names are not defined. But as far as I can tell this is the only obstacle to writing a custom mjd_long type. (I think with some care plain mjd objects could be made to respect the extra precision of np.longdouble as well, but that's another issue.) 

```python
def _make_array(val, copy=False):
    """
    Take ``val`` and convert/reshape to an array.  If ``copy`` is `True`
    then copy input values.

    Returns
    -------
    val : ndarray
        Array version of ``val``.
    """
    val = np.array(val, copy=copy, subok=True)

    # Allow only float64, string or object arrays as input
    # (object is for datetime, maybe add more specific test later?)
    # This also ensures the right byteorder for float64 (closes #2942).
    if not (val.dtype == np.float64 or val.dtype.kind in 'OSUMaV'):
        val = np.asanyarray(val, dtype=np.float64)

    return val
```

**Comment by aarchiba** [comment]
As a workaround I can probably make mjd_decimal, not that that's completely interoperable, but it gives users a way to get single-number MJDs that might not lose much accuracy.

**Comment by mhvk** [comment]
Hmm, I wonder if it wouldn't be better to leave this dtype checking to the various `TimeFormat` classes - those actually know what they need. @taldcroft - what do you think? at some level, all one wants here is that the output has a shape.

p.s. @aarchiba - since kind 'V' is excluded, you can probably work around it by passing in structured arrays (with a single item). But it is really ugly.
p.s.2 There might be some value in being able to pass in an `mjd_string` type; I've done something similar for my `Phase` class (which might make it to PINT if that ever drops python2); see https://github.com/mhvk/scintillometry/blob/master/scintillometry/phases/phase.py#L86

**Comment by aarchiba** [comment]
Er. I was waiting for it to be working to put in the feature request and PR: https://github.com/aarchiba/PINT/blob/precision-testing/src/pint/pulsar_mjd.py

**Comment by taldcroft** [comment]
> Hmm, I wonder if it wouldn't be better to leave this dtype checking to the various TimeFormat classes - those actually know what they need. 

I think we need to be a little bit careful with this because the `TimeFormat` classes (including potential custom user classes that we don't know about) have been written assuming this data normalization (coercion) up front.  So the classes can be lazy and assume any floats are always float64.

But not to stand in the way of progress, maybe there is some back-compatible way to make things work.   Here is one possibility:
- Remove the part of `_make_array` that does the 64-bit coercion.  (At that point probably remove `_make_array` entirely?).
- Rename the current `TimeFormat` class to `BaseTimeFormat`.
- Make a new `TimeFormat` class which has only this for `__init__`:
```
def __init__(val1, val2, ...):
    if not (val1.dtype == np.float64 or val1.dtype.kind in 'OSUMaV'):
        val1 = np.asanyarray(val1, dtype=np.float64)
    if not (val2.dtype == np.float64 or val2.dtype.kind in 'OSUMaV'):
        val2 = np.asanyarray(val2, dtype=np.float64)
    super().__init__(val1, val2, ...)
```
Then custom classes that don't want this data normalization can inherit from `BaseTimeFormat`.

**Comment by aarchiba** [comment]
It does simplify my client code to be guaranteed arrays, possibly zero-dimensional, that are definitely the same shape. So that much input normalization is good. I don't think there is much demand for Time formats whose input formats are complex, or quaternion, or less than 64 bits. Which leaves 64 bits and more-than-64-bits as plausible numeric formats (e.g. some hypothetical numpy double-double/quad-double/binary128 data type); most everything else is likely to come in as objects (e.g. Decimal) or an existing type. So generalizing too far is maybe not necessary. But your modification is probably reasonable in terms of comprehensibility and maintainability, and it would solve my problem.

**Comment by mhvk** [comment]
We can also be simpler and just let any format be OK to which `float64` can cast safely (or just pass in `float>64` explicitly).

**Comment by aarchiba** [comment]
The code makes reference to a mysterious endianness problem that I was hesitant to mess with. Frankly, the concerns expressed in #2942 about whether ERFA chokes on wrong-endianness data make me very nervous and I feel like someone maybe needs to write a whole bunch of test cases? Anyway I didn't want to risk messing with that.

But really, shouldn't there be some normalization on the way *out* of the custom format creation, to ensure that jd1 and jd2 are only ever stored as arrays of native-endian float64s?
