### ISSUE TITLE
Unicode support for astropy units

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#9347]
Dealing with unit strings received from somewhere, it would be nice if astropy  supported common unicode symbols.

E.g. 

```python
import astropy.units as u

u.Unit('µg')  # MICRO SIGN (U+00B5)
u.Unit('μm') # GREEK SMALL LETTER MU (U+03BC)
u.Unit('m²')  # SUPERSCRIPT TWO (U+00B2)
u.Unit('m³') # SUPERSCRIPT THREE (U+00B3)
u.Unit('s⁻¹') # SUPERSCRIPT MINUS  (U+207B) + SUPERSCRIPT 1 (U+00B9) 
```

Probably there is more...

**Comment by pllim** [comment]
"Somewhere" is.... sympy?

**Comment by MaxNoe** [comment]
No, I really mean "somewhere". For me it was a webpage with copy / paste.

**Comment by pllim** [comment]
Ah, okay. 😅 

@MaxNoe , given it is Hacktoberfest, you want to attempt an exploratory PR? 😉

**Comment by MaxNoe** [comment]
Yeah sure, can you direct me to an entry point?

**Comment by pllim** [comment]
Maybe here? Thanks!

https://github.com/astropy/astropy/blob/4deafe9a18c16e60f0e4f108433596467f367561/astropy/units/core.py#L2160

And the contribution guide, in case you need it: https://docs.astropy.org/en/latest/development/workflow/development_workflow.html

**Comment by mhvk** [comment]
@MaxNoe - this would be lovely!

There are two places where we could deal with unicode input. One is where @pllim pointed to - which is for the prefixes of individual units. I think this would get you the micro's - essentially just add it to the `short` list for micro.  Note that this also means that one will be able to do `u.µg`!!! (nothing in python stopping us from that). Though it is a bit annoying that there are multiple code points for micro - some [string translation](https://docs.python.org/3/library/stdtypes.html#str.translate) may be needed.

For anything related to composition, thus including superscripts, the work is done by a string parser in [`units.formats.generic`](https://github.com/astropy/astropy/blob/master/astropy/units/format/generic.py).

Right now, that does not deal with unicode at all. However, unicode is dealt with in some detail for parsing of angles from strings in [`coordinates.angle_parser`](https://github.com/astropy/astropy/blob/master/astropy/coordinates/angle_utilities.py#L133), so that might help to get an idea of how to do this.

**Comment by MaxNoe** [comment]
Ok, the micro part was quite easy, see https://github.com/astropy/astropy/pull/9348

**Comment by MaxNoe** [comment]
The superscripts should be directly replaceable by their non-superscript counterparts.

Would you think this is a good approach?
```python
unicode_translation_table = {
    ord('\N{SUPERSCRIPT MINUS}'): '-',
    ord('\N{SUPERSCRIPT ONE}'): '1',
}
s = s.translate(unicode_translation_table)
```

**Comment by mhvk** [comment]
(see discussion in PR)

**Comment by MaxNoe** [comment]
@mhvk 

For adding support for stuff like `u.µΩ`, I found a neat solution using module level `__getattr__`.

What would you think about this (astropy/units/__init__.py):

```python
def __getattr__(name):
    # python normalizes identifiers to ''NFKC", this applies the same 
    # normalization if someone uses `getattr(u, name)` instead of `u.name`
    normalized = unicodedata.normalize('NFKC', name)
    
    try:
        return Unit(name)
    except ValueError:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'") from None
```

**Comment by mhvk** [comment]
I wondered about that as well, and like your solution - but `module.__getattr__` was introduced in python 3.7 and for astropy 4.0 we still support python 3.6...

**Comment by MaxNoe** [comment]
Okay, but it does not harm in 3.6, just a 3 line function doing nothing.

However, as I found out that python normalizes all identifiers to NFKC, the problem is much smaller than I thought.

So just adding three characters for Angstrom, Ohm and Micro would be all, the degree sign is not a valid identifier, neither are the super scripts.

**Comment by mhvk** [comment]
Tthat normalization is certainly very helpful! It seems we could then do it as a follow-up on #9348.

@astropy/coordinators - what is your feeling about having unicode attributes on the units module? #9348 introduces the ability to read things like 'μm', is there a use for also having `u.μm`?

**Comment by taldcroft** [comment]
My first reaction is not thrilled about non-ASCII attributes on units.  I don't feel really strongly, but the units attribute list is already quite long, and I don't think that most users can easily type those when coding.

This seems different from being able to parse them as a string in `Unit()`, which I think is wonderful.

**Comment by MaxNoe** [comment]
I concur, this is why I thought it would be a good compromise to use the getattr version, which would enable it via falling back to string parsing.

**Comment by bsipocz** [comment]
#9348 has implemented this
