### ISSUE TITLE
Operations on MaskedColumn after unit conversion use pre-converted units

### ISSUE THREAD

**Issue by ajtribick** [astropy/astropy#9521]
### Description

After converting the unit of a `MaskedColumn` with `convert_unit_to`, subsequent manipulations of the column use the old unit.

### Expected behavior

The new unit should be used with the converted values. E.g. if after conversion from km to m the value is 300 m, then 300 m * 2 = 600 m

### Actual behavior

The old unit was used with the converted value. E.g. if after conversion from km to m the value is 300 m, then multiplying by 2 results in 300 m * 2 = 600 km.

### Steps to Reproduce

Example triggering the bug:
```python
>>> from astropy.table import MaskedColumn
>>> import astropy.units as u
>>> c = MaskedColumn([3.5,2.4,1.7], name='test', unit=u.km)
>>> c
<MaskedColumn name='test' dtype='float64' unit='km' length=3>
3.5
2.4
1.7
>>> c.convert_unit_to(u.m)
>>> c
<MaskedColumn name='test' dtype='float64' unit='m' length=3>
3500.0
2400.0
1700.0
>>> # all looks fine up to this point, now for the bug...
>>> c*2.0
<MaskedColumn name='test' dtype='float64' unit='km' length=3>
7000.0
4800.0
3400.0
>>> # unit should be 'm' not 'km'
```

This does not occur with `Column`:

```python
>>> from astropy.table import Column
>>> import astropy.units as u
>>> c = Column([3.5,2.4,1.7], name='test', unit=u.km)
>>> c.convert_unit_to(u.m)
>>> c
<Column name='test' dtype='float64' unit='m' length=3>
3500.0
2400.0
1700.0
>>> c*2.0
<Column name='test' dtype='float64' unit='m' length=3>
7000.0
4800.0
3400.0
```

### System Details

Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45)
Numpy 1.17.3
Scipy 1.3.1
astropy 3.2.3 (also occurs on development version 4.0.dev26764)

**Comment by pllim** [comment]
Thank you for your detailed report, @ajtribick !

cc @taldcroft and @mhvk

**Comment by mhvk** [comment]
Wow, that is a strange error - thanks so much for reporting. I did find the problem, but am not yet sure about the solution. As usual, it is due to strange behaviour of `MaskedArray` - this stores some of the underlying `Column` information so that it can "helpfully" restore it when needed. And in this case, just after the unit conversion in your example,
```
c._optinfo
# For some reason it also has `_basedict` with the same information 
{'_parent_table': None,
 'indices': [],
 '_name': 'test',
 '_unit': Unit("km"),
 '_format': None,
 'description': None,
 '_meta': OrderedDict()}
```
Hey, presto, the unit is still the old one!

Indeed, if I blatantly go ahead and delete *both*, things do work:
```
del c._optinfo
del c._basedict
c * 2.
<MaskedColumn name='test' dtype='float64' unit='m' length=3>
7000.0
4800.0
3400.0
```

It would need a bit of experimenting to see whether it is OK to just delete these two upfront (they're used in `MaskedArray._update_from`), which I won't get to immediately (am at a conference).

Anyway, this does encourage me to continue working with an alternative implementation of masking - both to help `MaskedColumn` and finally get a `MaskedQuantity` (which would make all this unnecessary).
