### ISSUE TITLE
Issues in poisson_conf_interval with kraft-burrows-nousek

### ISSUE THREAD

**Issue by yuzl00** [astropy/astropy#9596]
### Description

When I use poisson_conf_interval with kraft-burrows-nousek interval, there is something wrong with it. This is the code:
```
>>> from astropy.stats import poisson_conf_interval
>>> poisson_conf_interval(1000,'kraft-burrows-nousek',1,900,0.9)
```
The output is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/stats/funcs.py", line 718, in poisson_conf_interval
    cache=True)(n, background, conflevel)
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/usr/lib/python3/dist-packages/astropy/stats/funcs.py", line 1244, in _kraft_burrows_nousek
    return _mpmath_kraft_burrows_nousek(N, B, CL)
  File "/usr/lib/python3/dist-packages/astropy/stats/funcs.py", line 1150, in _mpmath_kraft_burrows_nousek
    N = mpf(N)
  File "/usr/lib/python3/dist-packages/mpmath/ctx_mp_python.py", line 77, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
  File "/usr/lib/python3/dist-packages/mpmath/ctx_mp_python.py", line 96, in mpf_convert_arg
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from 1000
```
I check the codes and find that mpf can't convert type numpy.int64, so I modify the code in function `_mpmath_kraft_burrows_nousek(N, B, CL)` in astropy/stats/funcs.py:
```
N = mpf(N)
B = mpf(B)
```
to
```
N = mpf(int(N))
B = mpf(float(B))
```
After that, the output is changed to:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/astropy/stats/funcs.py", line 718, in poisson_conf_interval
    cache=True)(n, background, conflevel)
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/usr/lib/python3/dist-packages/astropy/stats/funcs.py", line 1244, in _kraft_burrows_nousek
    return _mpmath_kraft_burrows_nousek(N, B, CL)
  File "/usr/lib/python3/dist-packages/astropy/stats/funcs.py", line 1192, in _mpmath_kraft_burrows_nousek
    S_max = findroot(func, N - B, tol=1e-4)
  File "/usr/lib/python3/dist-packages/mpmath/calculus/optimization.py", line 979, in findroot
    % (norm(f(*xl))**2, tol))
ValueError: Could not find root within given tolerance. (0.0100000000000009105486 > 0.0001)
Try another starting point or tweak arguments.
```
If run with:
`poisson_conf_interval(1000,'kraft-burrows-nousek',1,901,0.9)`
it outputs the result:
```
array([[ 47.95246273],
       [151.84619844]])
```
but with <=900 background, it doesn't continue.
It seems that `S_max = findroot(func, N - B, tol=1e-4)` in `_mpmath_kraft_burrows_nousek(N, B, CL)` can't find the root. If it is modified to `S_max = findroot(func, 155, tol=1e-4)`, the code with 900 background will run correct. It outputs:
```
array([[ 48.94414313],
       [152.85511478]])
```
So, I think this part of code should be modified to imporve it.

### System Details
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
Numpy 1.16.2
Scipy 1.1.0
astropy 3.1.2

**Comment by pllim** [comment]
cc @crawfordsm and @larrybradley

**Comment by woldroyd** [comment]
I am getting similar errors whenever kraft-burrows-nousek switches to the mpf implementation (N>=100), both with the TypeError and, after a work around, the lack of convergence. A simple test case I was trying for this was:

`poisson_conf_interval(200,background=0,conflevel=0.68,interval='kraft-burrows-nousek').T`

Additionally, I'm getting an error in the scipy implementation. With a test case:

`poisson_conf_interval(91,background=0,conflevel=0.68,interval='kraft-burrows-nousek').T`

I get the error:

`Traceback (most recent call last):
  File "plot_R_vs_V.py", line 118, in <module>
    print('poisson_conf_interval 91:',poisson_conf_interval(91,background=0,conflevel=0.68,interval='kraft-burrows-nousek').T)
  File "/anaconda3/lib/python3.7/site-packages/astropy/stats/funcs.py", line 713, in poisson_conf_interval
    cache=True)(n, background, conflevel)
  File "/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/anaconda3/lib/python3.7/site-packages/astropy/stats/funcs.py", line 1233, in _kraft_burrows_nousek
    return _scipy_kraft_burrows_nousek(N, B, CL)
  File "/anaconda3/lib/python3.7/site-packages/astropy/stats/funcs.py", line 1110, in _scipy_kraft_burrows_nousek
    S_max = brentq(func, N - B, 100)
  File "/anaconda3/lib/python3.7/site-packages/scipy/optimize/zeros.py", line 775, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
ValueError: f(a) and f(b) must have different signs
`

This works fine for N<=90. I suspect that the function struggles not only when N>=100 (which is when it switches to the mpf version), but it also can't handle it if the upper bound is >= 100. Based on the error, I think brentq has a hard time finding a root when the a and b arguments are close to one another (since they need to have opposite signs). This function could probably use a more robust method for handling various cases.

**Comment by hamogu** [comment]
I've encountered similar problems on the other end (very few counts):
```
In [30]: poisson_conf_interval(0., background=3., confidence_level=0.9, interval='kraft-burrows-nousek').T                                             
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-53f2549a660e> in <module>
----> 1 poisson_conf_interval(0., background=3., confidence_level=0.9, interval='kraft-burrows-nousek').T

/melkor/d1/guenther/soft/python/astropy/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    523                             kwargs[old_name[i]] = value
    524 
--> 525             return function(*args, **kwargs)
    526 
    527         return wrapper

/melkor/d1/guenther/soft/python/astropy/astropy/stats/funcs.py in poisson_conf_interval(n, interval, sigma, background, confidence_level)
    752             raise ValueError('Background must be >= 0.')
    753         conf_interval = np.vectorize(_kraft_burrows_nousek,
--> 754                                      cache=True)(n, background, confidence_level)
    755         conf_interval = np.vstack(conf_interval)
    756     else:

/nfs/melkor/d1/guenther/soft/anaconda/envs/astropy/lib/python3.7/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2089             vargs.extend([kwargs[_n] for _n in names])
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 
   2093     def _get_ufunc_and_otypes(self, func, args):

/nfs/melkor/d1/guenther/soft/anaconda/envs/astropy/lib/python3.7/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2159             res = func()
   2160         else:
-> 2161             ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
   2162 
   2163             # Convert args to object arrays first

/nfs/melkor/d1/guenther/soft/anaconda/envs/astropy/lib/python3.7/site-packages/numpy/lib/function_base.py in _get_ufunc_and_otypes(self, func, args)
   2119 
   2120             inputs = [arg.flat[0] for arg in args]
-> 2121             outputs = func(*inputs)
   2122 
   2123             # Performance note: profiling indicates that -- for simple

/melkor/d1/guenther/soft/python/astropy/astropy/stats/funcs.py in _kraft_burrows_nousek(N, B, CL)
   1273                                  'large.')
   1274     if HAS_MPMATH:
-> 1275         return _mpmath_kraft_burrows_nousek(N, B, CL)
   1276 
   1277     raise ImportError('Either scipy or mpmath are required.')

/melkor/d1/guenther/soft/python/astropy/astropy/stats/funcs.py in _mpmath_kraft_burrows_nousek(N, B, CL)
   1221         return out - CL
   1222 
-> 1223     S_max = findroot(func, N - B, tol=1e-4)
   1224     S_min = find_s_min(S_max, N, B)
   1225     return float(S_min), float(S_max)

/nfs/melkor/d1/guenther/soft/anaconda/envs/astropy/lib/python3.7/site-packages/mpmath/calculus/optimization.py in findroot(ctx, f, x0, solver, tol, verbose, verify, **kwargs)
    977                              '(%s > %s)\n'
    978                              'Try another starting point or tweak arguments.'
--> 979                              % (norm(f(*xl))**2, tol))
    980         return x
    981     finally:

ValueError: Could not find root within given tolerance. (0.00999779962759141724597 > 0.0001)
Try another starting point or tweak arguments.
```
(This uses `mpmath` because I made an environment that does not habe `scipy`)
Again, it's due to the numerics.

**Comment by hamogu** [comment]
@yuzl00: I've encountered enough of those problems that I've done a deeper debug of it. As you discovered already, the problem is that the numerical optimization does not always find the root of the function, if the starting value is too far from the true root. That happens in particular if B=0, B > N, or abs(N-B) is large. So, in your particular case, setting the starting values to `155` worked because that's pretty close to the answer (about 152), while your default guess of `N-B` = 100 is apparently too far. However, we obviously can't hardcode 155 in there, because that won't work in most cases. I've tried to come up with a better estimate, but they always fail for something. So, I think we actually need to change the numerical implementation.

The original Karft-Burrows-Nousek paper uses a numerical integration from the most-probable value in both directions at the same time. When I wrote this code for astropy 5 years ago, I reformulated it as an optimization problem, because that way I could use the existing root finding functions instead of writing my own integration routine, but as we see, the shape of the optimized functions just does not work well for that. I'm working on a PR to address this. I don't quite know how to do it yet, but I look into either re-writing this as 2D optimization (works, but painfully slow for N > 100) or doing a cheap "grid-search" to find the starting values for the root finding that's implemented in the current implementation (I fear edge cases where my grid is not large enough or I don't get close enough to the true value for the optimization to work).
