### ISSUE TITLE
Missing values in Time obj raise error when format is changed

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy#9612]
### Description

In #6028 it became possible to initialize Time objects using masked arrays to represent missing data. There's a hitch that occurs though when you try to change the format of a Time object which contains missing data. This hiccup was encountered while tackling astropy/astroplan#398.

### Expected behavior

```python
from astropy.time import Time
import numpy as np

jd = [np.nan]
ma = np.ma.masked_array(jd, mask=np.isnan(jd))
masked_time = Time(ma, format='jd')

# Change the format of the Time object
masked_time.format = 'iso'
print(masked_time)
```
should return
```
[--]
```

### Actual behavior

```
Traceback (most recent call last):
  File "example.py", line 46, in <module>
    print(masked_time)
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/time/core.py", line 636, in __str__
    return str(getattr(self, self.format))
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/time/core.py", line 1542, in __getattr__
    value = tm._shaped_like_input(tm._time.to_value(parent=tm))
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/time/formats.py", line 269, in to_value
    return self.mask_if_needed(self.value)
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/time/formats.py", line 878, in value
    for kwargs in self.str_kwargs():
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/time/formats.py", line 831, in str_kwargs
    self.jd1, self.jd2_filled)
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/_erfa/core.py", line 14979, in d2dtf
    check_errwarn(c_retval, 'd2dtf')
  File "/Users/bmmorris/miniconda3/lib/python3.7/site-packages/astropy/_erfa/core.py", line 89, in check_errwarn
    raise ErfaError('ERFA function "' + func_name + '" yielded ' + emsg)
astropy.utils.exceptions.ErfaError: ERFA function "d2dtf" yielded 1 of "unacceptable date (Note 6)"
```

### System Details

```
Darwin-15.6.0-x86_64-i386-64bit
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.3
Scipy 1.3.0
astropy 3.2.3
```

**Comment by bmorris3** [comment]
Upon some more investigation, it looks like what's happening is by default the masked array sets the `fill_value = 1e20`, which yields an "unacceptable date" by ERFA. The expected behavior can be reproduced if the user specifies

```python
ma = np.ma.masked_array(jd, mask=np.isnan(jd), fill_value=0)
```
in the example above.

**Comment by mhvk** [comment]
@bmorris3 - nice detective work! It does sound like this could be solved by ensuring the fill value is reasonable. @taldcroft?

**Comment by bmorris3** [comment]
I'm diving a bit deeper, and it looks like the only way to successfully specify a time with a `np.nan` is to [set an item in a vector time's array equal to `np.nan`](https://github.com/astropy/astropy/blob/master/astropy/time/core.py#L1147-L1149), like this: 
```python
>>> a = Time([0], format='jd')
>>> a[0] = np.nan
<Time object: scale='utc' format='jd' value=[--]>
```

**Comment by mhvk** [comment]
Indeed, `nan` is used to track the mask in `Time` (an implementation detail that at some point I hope to change, but that's no reason not to try to get rid of this bug!)

**Comment by taldcroft** [comment]
Indeed this reveals a limitation in the implementation, which is that it relies on having at least one unmasked value in order to infer something reasonable to use as a fill value when calling ERFA.

https://github.com/astropy/astropy/blob/c0e2cf774885194933762cbc8a1f2ebc59b4b51c/astropy/time/core.py#L2495

This function is called in `_init_from_vals()`, where vals can be any format.
https://github.com/astropy/astropy/blob/c0e2cf774885194933762cbc8a1f2ebc59b4b51c/astropy/time/core.py#L480

So in your original example if there was at least one "reasonable" JD then all is well.
```
In [23]: from astropy.time import Time
    ...: import numpy as np
    ...: 
    ...: jd = [np.nan, Time.now().jd]
    ...: ma = np.ma.masked_array(jd, mask=[True, False])
    ...: masked_time = Time(ma, format='jd')
    ...: 
    ...: # Change the format of the Time object
    ...: masked_time.format = 'iso'
    ...: print(masked_time)
    ...: 
    ...: 
[-- '2019-11-18 21:35:13.236']
```

**Comment by taldcroft** [comment]
This issue is not related to the `jd2 as np.nan` implementation per se and would not be immediately fixed using some MaskedArray wrapper or mixin.  The underlying problem is that it is most convenient to do the ERFA operations by passing in a filled array.  But that runs into a problem when the input is entirely masked and so you just don't know what the fill value should be.

A different implementation would be using the mask to select out the good (unmasked) values and only pass those to ERFA.  That's fine, it just means more array wrangling to flatten to a 1d array, take the good values, call ERFA, then reconstruct the original N-d array with fill values in the original masked cells.  All this is possible of course.

**Comment by taldcroft** [comment]
There may be a very simple fix. At least this fixes the original problem and passes tests:
```
(astropy) neptune$ git diff
diff --git a/astropy/time/core.py b/astropy/time/core.py
index d4e32c937..dff953fc7 100644
--- a/astropy/time/core.py
+++ b/astropy/time/core.py
@@ -489,6 +489,7 @@ class Time(ShapedLikeNDArray):
         # with shape broadcastable to jd2.
         if mask is not False:
             mask = np.broadcast_to(mask, self._time.jd2.shape)
+            self._time.jd1[mask] = 2451544.5  # Set to JD for 2000-01-01
             self._time.jd2[mask] = np.nan
 
     def _get_time_fmt(self, val, val2, format, scale,
```

**Comment by taldcroft** [comment]
See #9624.

**Comment by mhvk** [comment]
Nice!

**Comment by mhvk** [comment]
p.s. And, yes, I see that this would affect any masking implementation.

**Comment by bmorris3** [comment]
Thanks @taldcroft!
