### ISSUE TITLE
TST: Investigate cache warnings in tests (currently ignored)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9620]
### Description

Un-ignore the following warnings and investigate whether they can be mitigated without being ignored whole-sale.

https://github.com/astropy/astropy/blob/6864219167a402cb2e574c45ff91e3bb7a23861f/setup.cfg#L115-L116

Maybe @aarchiba can advise on the effort to address this issue.

### Additional context

This is a follow-up of #7928 

xref #9182 #9575 #9594

**Comment by aarchiba** [comment]
Running with -Werror should clarify - in a few cases I explicitly run tests where the cache is badly misconfigured, and in these cases we should demand emission of this warning (a warning because the code should fall back to no cache, but the user should know the cache isn't working). In other cases it may be being emitted when the cache is simply missing, and these are bugs.

If the problem arises only on Windows, it may be possible to trigger it on other systems by using the context manager to enforce use of the "dumb" dbm backend; this may not work, as Windows sometimes produces different exceptions in problematic filesystem conditions.
