### ISSUE TITLE
Fits Header to CSV file converter feature

### ISSUE THREAD

**Issue by joncwong** [astropy/astropy#9650]
Hi,

I'm currently working on a fits header to CSV file converter for the group I'm interning under. I was wondering how much interest there is in the AstroPy project for there to be an easily reusable API or script that generates a CSV file based on specified headers of a fits file since I don't know how useful this would be outside my group.

For example, given 500 fits files in a directory (or directories), I would be able to generate 500 rows of a CSV file. 

Example 1 (single directory):
`./fits-to-csv.py /myfits --headers=ra,dec,epoch,date --output-file=myfits.csv`

Example 2 (multiple directories):
`./fits-to-csv.py /oct_fits/ /nov_fits/ /dec_fits/ --headers=ra,dec,epoch,date --output-file=2019_fits.csv`

**Comment by saimn** [comment]
Actually there is already something similar (and inspired from other tools that do the same thing, like ESO's dfits+fitsort, IRAF probably also has the same):

* not csv, but gives one column per keyword in ascii format:
```
fitsheader -e 0 -k NAXIS -k BITPIX -f astropy/io/fits/tests/data/*.fits
```

* for csv there is another option but less useful since it gives only one column for keyword and one for value, and multiple keywords get in the same column:
```
fitsheader -e 0 -k NAXIS -k BITPIX -t ascii.csv astropy/io/fits/tests/data/*.fits
```

**Comment by mhvk** [comment]
@joncwong - if the above tips are useful, is there a way to document them such that you would have found it? Or do you have ideas for how to extend the behaviour for `ascii.ecsv`?

**Comment by joncwong** [comment]
Will close for now, will reopen if I find answers in the future.
