### ISSUE TITLE
ASCII reader `converters` uses guessed column names

### ISSUE THREAD

**Issue by griffin-h** [astropy/astropy#9701]
### Description
When using `ascii.read` with both the `names` and `converters` arguments, the `converters` dictionary ignores the user-supplied names and requires that you know the guessed names. I think it would be clearer if the keys of `converters` were meant to be the values in `names`.

### Steps to Reproduce

```python
from astropy.io import ascii

csv_text = '''a,b,c
1,2,3
4,5,6'''
names = ['A', 'B', 'C']

converters_bad = {
    'A': [ascii.convert_numpy(float)], 
    'B': [ascii.convert_numpy(int)],
    'C': [ascii.convert_numpy(str)]
}
t_bad = ascii.read(csv_text, format='csv', names=names, converters=converters_bad)
print(t_bad.dtype)  # all columns are incorrectly parsed as integers

converters_good = {
    'a': [ascii.convert_numpy(float)], 
    'b': [ascii.convert_numpy(int)],
    'c': [ascii.convert_numpy(str)]
}
t_good = ascii.read(csv_text, format='csv', names=names, converters=converters_good)
print(t_good.dtype)  # columns are parsed as intended
```

### System Details

macOS-10.15.1-x86_64-i386-64bit
Python 3.8.0 (default, Nov  6 2019, 15:49:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.17.4
astropy 4.1.dev27074

**Comment by pllim** [comment]
cc @taldcroft and @hamogu

**Comment by dhomeier** [comment]
It's not just a matter of the names from the header "overriding" the names in `converters` - even if you ignore the header with
```
ascii.read(csv_text, format='no_header', delimiter=',', names=names, converters=converters_bad, data_start=1)
```
the converters are still not honoured.

I think this is because the custom names are only applied at the very end of `BaseReader.read()` with `_apply_include_exclude_names`; will probably not be quite straightforward to map them to the default names before the actual table is read in.

**Comment by mhvk** [comment]
Ah, yes, this bit me too while creating the `LeapSeconds` class; see https://github.com/astropy/astropy/blob/master/astropy/utils/iers/iers.py#L1088; would be good to solve this!

**Comment by taldcroft** [comment]
Yup, this should be fixed.  I *think* it might not be too bad.  The relevant code is linked below in the main base reader `read` method:
https://github.com/astropy/astropy/blob/8c2bf82a1708840cdc998be9cd6c60dc106ca89d/astropy/io/ascii/core.py#L1204

One needs to run `_apply_include_exclude_names` on `cols` prior to the `self.outputter` call.

So the catch is that `_apply_include_exclude_names` requires an astropy table and is used a few other places for writing.  So we need to basically split that into a version for reading that takes as input the list of `cols` instead of a table. I've labeled this as package-intermediate (at the low end) as I think the change should be quite isolated in that one function.

**Comment by pllim** [comment]
See #9739
