### ISSUE TITLE
Add Torr unit to units packages

### ISSUE THREAD

**Issue by timj** [astropy/astropy#9783]
### Description

The LSST camera vacuum engineers wish to use the torr unit.

This is *almost* the same as mmHg which is in the CDS units package but it's not quite that (7 parts in a million). See https://en.wikipedia.org/wiki/Torr

I believe that torr is defined as:

```python
torr = u.def_unit("Torr", cds.atm/760.0)
```

I'm happy to do a pull request for this but I'm not completely sure where I should define the unit. It seems that `cds` might be the best place but I'm not sure whether `cds` has some restrictive definition that it must only come from some master list held at CDS.  Please advise.

**Comment by pllim** [comment]
I don't think it should be listed under `cds` but maybe @mhvk can advise.

**Comment by timj** [comment]
It's not SI, it's not Imperial. It's derived from a unit in CDS so must depend on that. It was originally defined as mmHg (which is in cds) but is now slightly different.

**Comment by mhvk** [comment]
I don't think we need to involve `atm`, since that is defined in `constants`, so one could depend on that and define similar to the pressure units in `units/si.py`,
```
def_unit(['Torr'], _si.atm.value/760. * Pa, namespace=_ns, prefixes=[(['m'], [], 1.e-3)])
def_unit(['millitorr'], Torr * 1.e-3, namespace=_ns)
```
(the two definitions are needed to ensure we don't get either `torr` or `mTorr`; the use of `milli` described on the wikipedia page is a bit odd; possibly we should just ignore the `millitorr`, since really it should be a `PrefixUnit`...).

Now the main question is whether to just add this to the miscellaneous section in `astrophys.py`, or to create a new file with "additional units" that one can enable if need be. I somewhat lean to keeping it simple - it is only two (or three) extra entries.

**Comment by timj** [comment]
I was going to say that it seems odd to put torr in the astrophys file but then I see that in the misc section at the end of the file it has byte in it and it's imported by default so maybe it doesn't matter.

I think the comment in wikipedia about millitorr vs mTorr is a completely general statement about how SI units work.  SI units named after people are written in lower case when written out in full (tesla, pascal) but upper case in symbol form (T, Pa).  You therefore say "millipascal" and "mPa" and you say "millitorr" and "mTorr" because the full name of the unit is "torr" and the symbol for the torr is "Torr".

The unit class seems to treat "millipascal" and "milliPascal" as the same thing so I suggest we don't change that here for millitorr and milliTorr.

**Comment by mhvk** [comment]
Ah, that also suggests we are a bit too generous with our unit definitions!
