### ISSUE TITLE
cannot update astropy

### ISSUE THREAD

**Issue by manulcaux** [astropy/astropy#9850]
Following the mail announcing the delivery of astropy 4.0 I tried to install it using conda but it doesn't work
```
[macp2021:~] caux% conda update astropy
Collecting package metadata (current_repodata.json): done
Solving environment: / 

Updating astropy is constricted by 

anaconda -> requires astropy==3.2.2=py37h1de35cc_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

# All requested packages already installed.

[macp2021:~] caux% 
```

**Comment by jehturner** [comment]
I'm not sure whether the `astropy` code repo is the best place to report anaconda-related problems (@bsipocz? @saimn?), but not to worry -- since I've also been looking at this problem I'll post a workaround.

I think this conflict with `anaconda` is a change in behaviour in conda 4.7, presumably related to the publicized changes in dependency resolution in that version (eg. see https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/). I also see some similar issues posted by the wider anaconda community in recent months. Updating to the latest conda 4.8.1 does not (currently) solve this.

What you can do is just forcibly remove the `anaconda` meta-package itself, in order to eliminate the conflicting specification while retaining the other packages it installs:
```
> conda remove anaconda --force
> conda install astropy=4
```
I might report this upstream if I can clarify what's going on, but I think there is already some awareness of this problem. Does that help?

**Comment by jehturner** [comment]
FYI it looks like this is where `astropy` gets packaged for anaconda:
  https://github.com/conda-forge/astropy-feedstock/issues
but any problem report probably belongs upstream, in the conda issue tracker:
  https://github.com/conda/conda/issues
As I say, I might post there if I have something useful to add (or just a :+1:).

**Comment by saimn** [comment]
> I'm not sure whether the astropy code repo is the best place to report anaconda-related problems 

It should probably be reported upstream, as you said, but it's good to keep track of it here since anaconda is kind of officially supported by astropy as one of the main installation method, and this will probably annoy more people.

**Comment by manulcaux** [comment]
I ran a conda self update and although my conda was uptodate, running conda update astropy worked correctly afterwards...
