### ISSUE TITLE
Inconsistent handling of "\n" delimiter in fast parser

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#9928]
As @dhomeier pointed out in https://github.com/astropy/astropy/pull/9923#issuecomment-582562851 and https://github.com/astropy/astropy/pull/9923#issuecomment-582577704 .

This issue was discovered after an unsuccessful attempt to clean-up the code in `tokenizer.c` to remove so many repetitions of:

```c
if (col >= self->num_cols)
    RETURN(TOO_MANY_COLS);
```

**Comment by dhomeier** [comment]
After a brief look into `core.py`, I'd say that the Python parser (`fast_reader=False`) is simply splitting the input along the newline characters before the value of `delimiter` is ever considered; so after that no `\n`s are left in the lines, leaving one always with a single-column table.
That seems not so straightforward with the C parser, since the `\n` chars are not actually removed from the string.

**Comment by dhomeier** [comment]
The solution turned out to be quite simple, moving the `if (c == '\n')` ahead in the `FIELD` block as well. :)
