### ISSUE TITLE
Incorrect transformation of coordinates with SkyCoord

### ISSUE THREAD

**Issue by tfitoussi** [astropy/astropy#9940]
Hello everyone,

I was trying to transform galactic coordinates in Cartesian coordinates but when I go back from Cartesian to galactic, the coordinates of the source has changed (see the code below).
```python
from astropy.coordinates import SkyCoord
from astropy import units as u

lon = 251
lat = -26
dist = 5 

coord = SkyCoord(lon, lat, dist, frame="galactic", unit=(u.deg, u.deg, u.Mpc))
print(coord)

coord = coord.cartesian
print(coord)
x, y, z = coord.x.value, coord.y.value, coord.z.value

coord = SkyCoord(x, y, z, unit=u.Mpc, representation_type="cartesian")
print(coord)
print(coord.galactic)
```
output:
```
<SkyCoord (Galactic): (l, b, distance) in (deg, deg, Mpc)
    (251., -26., 5.)>
(-1.46309359, -4.24913233, -2.19185573) Mpc
<SkyCoord (ICRS): (x, y, z) in Mpc
    (-1.46309359, -4.24913233, -2.19185573)>
<SkyCoord (Galactic): (l, b, distance) in (deg, deg, Mpc)
    (354.46656629, 12.84625821, 5.)>
```

I made a test and it seems that the galactic longitude and latitude are interpreted as right ascension and declination. Indeed, in the next code I put my galactic longitude and latitude as RA, Dec and I obtain the same results as before:
```python
coord = SkyCoord(ra=lon, dec=lat, distance=dist, unit=(u.deg, u.deg, u.Mpc))
print(coord.cartesian)
print(coord.galactic)
```
output:
```
(-1.46309359, -4.24913233, -2.19185573) Mpc
<SkyCoord (Galactic): (l, b, distance) in (deg, deg, Mpc)
    (354.46656629, 12.84625821, 5.)>
```

It appears that during the transformation, the galactic coordinates are always read as ICRS coordinates. I don't know if the problem occurs with other system of coordinates (I didn't try) but I guess the reference system is not taking into account during transformation.

Right now, I solved the problem by first converting the galactic coordinates in ICRS and then converting it in cartesian.
```python
coord = SkyCoord(lon, lat, dist, frame="galactic", unit=(u.deg, u.deg, u.Mpc))
RA, DEC = str(coord.icrs.to_string('hmsdms')).split(" ")
coord = SkyCoord(ra=RA, dec=DEC, distance=dist, unit=(u.deg, u.deg, u.Mpc))
print(coord.cartesian)
print(coord.galactic)
```
output:
```
(-0.11744916, 3.60221526, -3.46558089) Mpc
<SkyCoord (Galactic): (l, b, distance) in (deg, deg, Mpc)
    (251.00000002, -25.99999998, 5.)>
```

Cheers,
Thomas

**Comment by eteq** [comment]
@tfitoussi - it looks to me like the issue here is one of expectation. In `astropy.coordinates`, "caresian" is not a coordinate frame, it is a representation of a given coordinate frame.  So for example we can have "galactic coordinates in a cartesian representation", "altaz coordinates in a cartesian representation", "icrs coordinates in a spherical representation", etc. You can see a bit more on that here: https://docs.astropy.org/en/stable/coordinates/index.html#overview-of-astropy-coordinates-concepts

So when you converted to cartesian in your example, all the frame information like "this is in Galactic coordinates" is lost, so when you re-created it in the last line there's no way for the code to know that you were expecting it to be galactic coordinates. Your third-to-last line could have instead been:
```
coord = SkyCoord(x, y, z, unit=u.Mpc, representation_type="cartesian", frame='galactic')
```
and then all would work as you wanted.  Or alternatively, you could do something like this to keep the frame information the whole way through:
```
>>> coord = SkyCoord(lon, lat, dist, frame="galactic", unit=(u.deg, u.deg, u.Mpc))
>>> coord.cartesian
<CartesianRepresentation (x, y, z) in Mpc
    (-1.46309359, -4.24913233, -2.19185573)>
>>> coord2 = coord.transform_to('icrs')
>>> coord2
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, Mpc)
    (91.86745039, -43.87729038, 5.)>
>>> coord2.cartesian
<CartesianRepresentation (x, y, z) in Mpc
    (-0.11744916, 3.60221526, -3.46558089)>
>>> coord3 = coord2.transform_to('galactic')
>>> coord3
<SkyCoord (Galactic): (l, b, distance) in (deg, deg, Mpc)
    (251., -26., 5.)>
>>> coord3.cartesian
<CartesianRepresentation (x, y, z) in Mpc
    (-1.46309359, -4.24913233, -2.19185573)>
```
which shows how the representation *changes* if you change the frame.

Based on the above it doesn't seem to me there's any bug here.  If you agree, feel free to close this, @tfitoussi, but alternatively if you have a concrete suggestion for how the documentation could be improved to make these concepts clearer, we can re-classify this as a docs issue to address that!

**Comment by tfitoussi** [comment]
@eteq,

Thank you for the answer.
Indeed, I did not realize that I was mixing two different things between representation type and coordinate system when I was doing this. Seeing it now seems pretty logical. 

For me, you can close the issue. 
Concerning the documentation, your explanation is clear enough and if someone has the same problem later, he or she should find the answer here now.

Cheers

**Comment by mhvk** [comment]
Am closing this as there was no consensus on what further documentation might be needed and I might as well avoid someone else thinking there is something wrong and reading through the issue.
