### ISSUE TITLE
Instantiating a Time from a Time looses the location

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#9962]
As found by @luojing1211 in https://github.com/nanograv/PINT/issues/609, initializing a table column from a list of time instances loses the location. Further investigation showed that more generally, initializing a `Time` from another `Time` instance causes loss of location, and that likely the fact that it now happens in `Table` reflects a change in how tables initialize from list:
```
from astropy.time import Time
from astropy.table import Table
t = Time('J2010', location=(45, 45))
print(t.location)
# (3194419.14506057, 3194419.14506057, 4487348.40886592) m
print(Table([[t]])['col0'][0].location)
# None
print(Time(t).location)
# None
```
Looking back, in versions prior to 4.0 (checked 3.2.x and 3.1), the `Table([[t]])` kept the location, but the `Time(t)` already did not.

**Comment by taldcroft** [comment]
This comes down to the time pseudo-format `TimeAstropyTime` being broken (see below).  The change in behavior related to Table is from the improvement in initialization, and I believe that Table is behaving correctly by delegating to `Time`, which then fails.
https://github.com/astropy/astropy/blob/9ca53839f048a65f40a82526b2de44b17a9d1b44/astropy/table/table.py#L1032

### TimeAstropyTime

This class is indeed ignoring `location`, along with `_delta_ut1_utc` and `_delta_tdb_tt`.  Getting this right is a little tricky because all three of those can be any value that is broadcastable to the shape of `jd1/2`.  In theory one can broadcast all those to the same shape and concatenate in the same way as with `jd1/2`.  Looking at this code and behavior now I don't really like it as it does not seem "expected" to me.  But that's what it is...

In digging around I discovered a potentially deeper problem that I causes issues and which I really don't understand:

https://github.com/astropy/astropy/blob/9ca53839f048a65f40a82526b2de44b17a9d1b44/astropy/time/formats.py#L689


```
# Expected
In [31]: np.array([Time([1], format='cxcsec'), Time([2,3], format='cxcsec')])                                                                                   
Out[31]: 
array([<Time object: scale='tt' format='cxcsec' value=[1.]>,
       <Time object: scale='tt' format='cxcsec' value=[2. 3.]>],
      dtype=object)

# Expected
In [32]: np.array([Time(1, format='cxcsec'), Time([2,3], format='cxcsec')])                                                                                     
Out[32]: 
array([<Time object: scale='tt' format='cxcsec' value=1.0>,
       <Time object: scale='tt' format='cxcsec' value=[2. 3.]>],
      dtype=object)

# Not expected, should have shape=(2,) not shape=(2, 2)
In [33]: np.array([Time([1,2], format='cxcsec'), Time([2,3], format='cxcsec')])                                                                                 
Out[33]: 
array([[<Time object: scale='tt' format='cxcsec' value=1.0>,
        <Time object: scale='tt' format='cxcsec' value=2.0>],
       [<Time object: scale='tt' format='cxcsec' value=2.0>,
        <Time object: scale='tt' format='cxcsec' value=3.0>]],
      dtype=object)
```

**Comment by mhvk** [comment]
@taldcroft - `nd.array` does behave strangely depending on whether things are iterable and appear to have compatible shape - indeed, I even raised an issue about this: https://github.com/numpy/numpy/issues/13958

**Comment by mhvk** [comment]
On the larger question, I agree that it is good that `Table` now defers to `Time` itself to make things work, and that `TimeAstropyTime` is the problem. Given also the `np.array` issues, which already need work-arounds in `_make_array`, it may be best to try to address possibility of an iterable of time instances at a higher level (in `__new__`?) - see #9882...
(aside, it is now possible to override numpy functions like `np.concatenate` - so perhaps we can use the opportunity to make things work even better! See #8610.

**Comment by mhvk** [comment]
Looking further into the code where this is causing a problem, before `Table` just created a `Column` with object dtype that contained a time instance for each entry; that behaviour is easy to reproduce, but obviously having a proper `Time` column is far better!
